### ISSUE TITLE
will attract more/fewer

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#1000]
### スクリーンショット

![yobiyose](https://github.com/user-attachments/assets/d9f8ac9c-1deb-4cfc-8cde-65e79e05f9ce)
![yobiyose2](https://github.com/user-attachments/assets/a265d9ae-a24f-4d00-a043-24f26a449258)

### 問題のあるインターフェイス

will attract more/fewerの訳文（赤枠内）

### 問題のテキスト

さらなる〇〇を呼び寄せる
少数の〇〇を呼び寄せる

### 希望する変更

〇〇を呼び寄せやすくなる
〇〇を呼び寄せにくくなる

### 変更の理由（概要）

誤訳の修正

### 変更の理由（詳細）

法律を制定した際に、IGへのattractionを変更させる効果があるときのメッセージ。
添付画像は一例で、世襲制は貴族が知識人IGに加入しやすくなり、選挙制は公務員が小ブルジョワに加入しやすくなる。このとき例えば選挙制から世襲制に変えようとすると、「貴族が知識人IGに加入しやすくなる」「公務員が小ブルジョワに加入しにくくなる」という意味のメッセージが出る。
そのため、will attract fewerを「少数の〇〇を呼び寄せる」とするのは誤訳であり、改訳したい。
「will attract more」のほうは誤訳ではないが、will attract fewerを改訳するのに合わせて表現を揃えたい。

### ゲームバージョン

1.7.X

### MOD有無

翻訳改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
提案通り修正しました。
