### ISSUE TITLE
国有化画面の修正

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#1001]
### スクリーンショット

![nationalization](https://github.com/user-attachments/assets/504596c2-e3f7-4fc3-9ea8-c4c5c27e7e01)

### 問題のあるインターフェイス

国有化画面

### 問題のテキスト

国有化(鉄鉱山)
国有化(6)施設レベル
(金融街)の(嶺南)が所有する(1)
(1.20M)補償コスト
国有(6)新型レベルの(6.0)維持コスト

### 希望する変更

国有化(鉄鉱山) → (鉄鉱山)の国有化
国有化(6)施設レベル → (6)レベルの施設を国有化
(金融街)の(嶺南)が所有する(1) → (嶺南)の(金融街)が所有する(1)レベル
(1.20M)補償コスト → (1.20M)の補償コスト
国有(6)新型レベルの(6.0)維持コスト → 新たに(6)レベルを国有化することで維持コスト(6.0)

### 変更の理由（概要）

変数の順番ミスなど、誤訳の修正

### 変更の理由（詳細）

同上

### ゲームバージョン

1.7.X

### MOD有無

翻訳改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
内部の議論の結果、以下のように変更しました。

国有化(鉄鉱山) → (鉄鉱山)の国有化
国有化(6)施設レベル → (6)施設レベルを国有化 (語順が提案通り入れ替えられなかったため)
(金融街)の(嶺南)が所有する(1) → (嶺南)の(金融街)が所有する(1)レベル
(1.20M)補償コスト → (1.20M)の補償コスト
国有(6)新型レベルの(6.0)維持コスト → 新たに国有化した(6)レベル分の維持コスト@(6.0) (@=アイコン)
