### ISSUE TITLE
戦争支持率のツールチップ

### ISSUE THREAD

**Issue by flowlanss** [matanki-saito/vic3jpadvmod#1002]
### スクリーンショット

![image](https://github.com/user-attachments/assets/ae78eebe-1220-48e2-ad47-ac95e7e10e9f)

### 問題のツールチップ

戦争ビューの味方側・敵側の戦争支持率のマウスオンツールチップ

### 問題の表現

軍の最大規模である#v [SCOPE.GetRootScope.GetCountry.GetNumCombatUnits|D],000#!と比較し、[SCOPE.sWar('war').GetCasualties(SCOPE.GetRootScope.GetCountry.Self)|Dv]の[concept_casualties]が出ており、相手側は[SCOPE.sWar('war').GetSizeWeightedLostBattlesFraction(SCOPE.GetRootScope.GetCountry.Self)|%1v]の戦闘で敗北しました (戦闘規模により自動調整)

### 問題箇所の英文

```
[SCOPE.sWar('war').GetCasualties(SCOPE.GetRootScope.GetCountry.Self)|Dv] [concept_casualties] suffered compared to max military size of #v [SCOPE.GetRootScope.GetCountry.GetNumCombatUnits|D]K#! and their side has lost [SCOPE.sWar('war').GetSizeWeightedLostBattlesFraction(SCOPE.GetRootScope.GetCountry.Self)|%1v] of battles (scaled by battle size)
```

### 希望する変更

軍の最大規模#v [SCOPE.GetRootScope.GetCountry.GetNumCombatUnits|D]K#!に対して[SCOPE.sWar('war').GetCasualties(SCOPE.GetRootScope.GetCountry.Self)|Dv]の[concept_casualties]を出しており、本陣営は[SCOPE.sWar('war').GetSizeWeightedLostBattlesFraction(SCOPE.GetRootScope.GetCountry.Self)|%1v]の戦闘で敗北している (戦闘規模により調整)

### 変更の理由（概要）

誤訳など

### 変更の理由（詳細）

・”Their side”は「相手側は～」となっているが、これはツールチップが出ている側(こちら側)を指すため誤訳。
・軍の最大規模について、大隊数にKを付けるフォーマットで出力しているところを「,000」に置き換えて、かえって後の死傷者数の計算とのフォーマットに差異が出ているため、Kに差し戻す。
・「戦闘規模により自動調整」→自動はいらない。どこから出てきたの？
・この文のあとには「：-0.17」のような補正値が来るので、全体が「これこれこういう条件でこの値が導き出されますよ」という文脈がわかるようにする。
・これを読んでいる間も戦争は続くため、「～している」という形に

### ゲームバージョン

1.7.X

### MOD有無

日本語改善Mod,Universal Names

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by flowlanss** [comment]
原案通り修正しました。
