### ISSUE TITLE
勢力圏マップモードでのツールチップ

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#1003]
### スクリーンショット

![Victoria 3 Screenshot 2024 08 04 - 22 52 16 82](https://github.com/user-attachments/assets/247c485e-09a4-450a-8ec4-4630a1535038)

### 問題のツールチップ

勢力圏マップモードでのツールチップ

### 問題の表現

```POWER_BLOC_NON_MEMBER_COUNTRY_TOOLTIP: "#header [Country.GetName]#!\nどの[concept_power_bloc][ConcatIfNeitherEmpty('\n', '$INVITE_DESC$')][ConcatIfNeitherEmpty( '\n$TOOLTIP_DELIMITER$\n',Country.GetLeverageBreakdown)]にも所属していません"```

### 問題箇所の英文

```POWER_BLOC_NON_MEMBER_COUNTRY_TOOLTIP: "#header [Country.GetName]#!\nIs not part of any [concept_power_bloc][ConcatIfNeitherEmpty('\n', '$INVITE_DESC$')][ConcatIfNeitherEmpty( '\n$TOOLTIP_DELIMITER$\n',Country.GetLeverageBreakdown)]```

### 希望する変更

```POWER_BLOC_NON_MEMBER_COUNTRY_TOOLTIP: "#header [Country.GetName]#!\nどの[concept_power_bloc]にも所属していません[ConcatIfNeitherEmpty('\n', '$INVITE_DESC$')][ConcatIfNeitherEmpty( '\n$TOOLTIP_DELIMITER$\n',Country.GetLeverageBreakdown)]"```

### 変更の理由（概要）

日本語として不自然なため

### プレイ国家

ペルシア

### ゲームバージョン

1.7.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
変数の位置修正だけでしたので即時修正しました。以後、同様の事例ありましたらDiscordの方で簡易報告していただいて結構です。起票ありがとうございました。
