### ISSUE TITLE
集団移住求心力マップモードのツールチップ

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#1004]
### スクリーンショット

![Victoria 3 Screenshot 2024 08 04 - 22 50 21 08](https://github.com/user-attachments/assets/04cf5550-9744-42e0-9cff-c94ba6f01935)

### 問題のツールチップ

集団移住求心力マップモードのツールチップ

### 問題の表現

①○条件を満たす州未満の国は集団移住求心力に追加のペナルティを受けます。
②自分の集団移住求心力も、現在の移住と市民権法律が国への移行について、文化を妨げる場合に、さらに影響を受けます。

### 問題箇所の英文

```$concept_countries$ with less than #b $PENALTY_THRESHOLD$#! $concept_mass_migration_eligible$ $concept_states$ suffer an additional penalty to their $concept_mass_migration_pull$.\n\nYour $concept_mass_migration_pull$ can also be further affected by your current [GetLawGroup('lawgroup_migration').GetName] and [GetLawGroup('lawgroup_citizenship').GetName] [Concept('concept_law', '$concept_laws$')] if they hinder the $concept_culture$ in question of migrating to your $concept_country$.```

### 希望する変更

①条件を満たす州が○未満の国は集団移住求心力に追加のペナルティを受けます。
②現在の移住と市民権に関する法律が自国への移住の問題となっている文化を妨げる場合、集団移住求心力はさらに影響を受けます。

### 変更の理由（概要）

構文ミス、日本語としての不自然さ

### 変更の理由（詳細）

①は変数の位置がおかしい
②については日本語として読みにくいため、合わせて修正したい

### プレイ国家

ペルシア

### ゲームバージョン

1.7.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
議論の結果、原案に一部修正箇所を追加し以下のように修正しました。起票ありがとうございました。
```#header [concept_mass_migration_pull]#!
$TOOLTIP_DELIMITER$
[Country.GetAdjective]の$concept_mass_migration_pull$#b $MASS_MIGRATION_ATTRACTION|1$#!は、以下の[Concept('concept_migration_target', '$concept_mass_migration_eligible$')]$concept_states$の平均[concept_migration_pull]に基づいています:

[COUNTRY.GetMassMigrationAttractionBreakdown]

$concept_mass_migration_eligible$$concept_states$が#b $PENALTY_THRESHOLD$#!未満の$concept_countries$は$concept_mass_migration_pull$に追加のペナルティを受けます。

現在の[GetLawGroup('lawgroup_migration').GetName]と[GetLawGroup('lawgroup_citizenship').GetName]に関する[Concept('concept_law', '$concept_laws$')]が自$concept_country$への移住の問題となっている$concept_culture$を妨げる場合、$concept_mass_migration_pull$はさらに影響を受けます。```
> 集団移住求心力
> 
> [国名]の集団移住求心力$数値$は、以下の条件を満たす 州の平均移住求心力に基づいています:
> 
> [COUNTRY.GetMassMigrationAttractionBreakdown]
> 
> 条件を満たす州が$数値$未満の国は集団移住求心力に追加のペナルティを受けます。
> 
> 現在の移住と市民権に関する法律が自国への移住の問題となっている文化を妨げる場合、集団移住求心力はさらに影響を受けます。
