### ISSUE TITLE
勢力圏メンバーに対する法律のImpose

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#1005]
### スクリーンショット

![image](https://github.com/user-attachments/assets/0202ce01-8264-47ae-a390-9ca1ee391a1e)
![image](https://github.com/user-attachments/assets/2aecddfa-fae7-42f7-b042-5147cf066bc1)

### 問題の用語

強制/課す

### 英語版の表現

Impose

### 希望する変更

強要

### 変更の理由（概要）

不適格な訳

### 変更の理由（詳細）

> 普通、国内で一定の支持がないと制定できない法律でも、勢力圏リーダーが命令することで10%の成功率を付与して議論させることができる仕様

上記を鑑みると「強制」は不適格なため

### ゲームバージョン

1.7.X

### MOD有無

日本語改善Mod

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通り修正しました。
