### ISSUE TITLE
【修正】この[数値]の[職業名]には急進派が[数値]人います

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#1006]
### スクリーンショット

![image](https://github.com/user-attachments/assets/6e901fb2-0fef-4cc1-a647-8c816130281d)

### 問題のあるインターフェイス

州画面>人口タブ

### 問題のテキスト

```#header $LOYALISTS$#!\n この[PopListItem.GetTotalPopSize|dv]の[PopListItem.GetPopType.GetName]には$LOYALISTS$が#v [PopListItem.GetNumLoyalists|d]#!人います```
```#header $RADICALS$#!\n この[PopListItem.GetTotalPopSize|dv]の[PopListItem.GetPopType.GetName]には$RADICALS$が#v [PopListItem.GetNumRadicals|d]#!人います```
```#header $RADICALS$#!\n この#v [PopListItem.GetTotalPopSize|d]#!の[PopListItem.GetPopType.GetName]には$RADICALS$が#v [PopListItem.GetNumRadicals|d]#!人います```

### 希望する変更

```#header $LOYALISTS$#!\n[PopListItem.GetPopType.GetName][PopListItem.GetTotalPopSize|dv]には#v [PopListItem.GetNumLoyalists|d]#!の$LOYALISTS$がいます```
```#header $RADICALS$#!\n[PopListItem.GetPopType.GetName][PopListItem.GetTotalPopSize|dv]には#v [PopListItem.GetNumRadicals|d]#!の$RADICALS$がいます```
```#header $RADICALS$#!\n[PopListItem.GetPopType.GetName]#v  [PopListItem.GetTotalPopSize|d]#!には#v [PopListItem.GetNumRadicals|d]#!の$RADICALS$がいます```

### 変更の理由（概要）

日本語として不自然なため

### ゲームバージョン

1.7.X

### MOD有無

日本語改善Mod

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
チーム内での議論の結果、wakkunteitoku2さんからの類似の提案であるISSUE-970に合わせ、「[職業名][数値]人のうち[数値]人が[急進派]です。」のように変更を行いました。

参考
https://github.com/matanki-saito/vic3jpadvmod/issues/970
