### ISSUE TITLE
【語弊】同じ宗教で国家より高い外交提案受諾率

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#1009]
### スクリーンショット

![image](https://github.com/user-attachments/assets/e90ec446-993f-41c6-9180-89ec4a607cee)

### 問題のツールチップ

勢力圏画面>原則管理ウィンドウ>「神聖なる市民 III」マウスオーバー

### 問題の表現

```同じ[concept_religion]で[Concept('concept_country','$concept_countries$')]より高い外交提案受諾率```

### 問題箇所の英文

```Higher Diplomatic Proposal Acceptance for [Concept('concept_country','$concept_countries$')] with same [concept_religion]```

### 希望する変更

```同[concept_religion]の[Concept('concept_country','$concept_countries$')]に対するより高い外交提案受諾率```

### 変更の理由（概要）

語弊を招く表現のため

### プレイ国家

フランス

### ゲームバージョン

1.7.X

### MOD有無

日本語改善Mod

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通り修正しました。
