### ISSUE TITLE
外交画面－維持するコスト

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#1010]
### スクリーンショット

![Victoria 3 Screenshot 2024 08 10 - 22 58 50 89](https://github.com/user-attachments/assets/d30ad09d-207f-43ab-8332-9382ab49f9b8)
![Victoria 3 Screenshot 2024 08 10 - 22 59 01 61](https://github.com/user-attachments/assets/9c0d98bd-b6dc-4291-8dd0-145f0fa3d8e5)

### 問題のあるインターフェイス

外交確認画面

### 問題のテキスト

DIPLOMATIC_ACTION_POPUP_MAINTENANCE_COST: "維持するコストが$COST$かかる"
DIPLOMATIC_ACTION_POPUP_MAINTENANCE_COST_BREAK: "今後は維持するコストが$COST$かからなくなる"

### 希望する変更

DIPLOMATIC_ACTION_POPUP_MAINTENANCE_COST: "維持コスト$COST$が必要"
DIPLOMATIC_ACTION_POPUP_MAINTENANCE_COST_BREAK: "今後は維持コスト$COST$が不要"

### 変更の理由（概要）

表現が冗長なので修正したい

### ゲームバージョン

1.7.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通り修正しました。起票ありがとうございました。
