### ISSUE TITLE
軍の編制カスタマイズ画面

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#1011]
### スクリーンショット

![Victoria 3 Screenshot 2024 08 12 - 23 00 10 58](https://github.com/user-attachments/assets/8f799ddd-80cf-443b-946a-00dbe698ba8c)

### 問題のあるインターフェイス

軍の編成カスタマイズ画面

### 問題のテキスト

①基礎上
②国旗のパターン
③国旗の色

### 希望する変更

①基礎 or ベース
②エンブレムのパターン
③エンブレムの色

### 変更の理由（概要）

不自然な表現の修正ほか

### 変更の理由（詳細）

①はBase onをそのまま訳しているが、意味がわかりにくい
　単に基礎あるいはベースで良い気がする
②③は軍隊のエンブレムのカスタマイズであり国旗ではない

### ゲームバージョン

1.7.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
議論の結果以下のように修正しました。対応遅れ申し訳ありませんでした。
①大隊名
②軍旗のパターン
③軍旗の色
