### ISSUE TITLE
軍隊/艦隊選択画面

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#1012]
### スクリーンショット

![Victoria 3 Screenshot 2024 08 12 - 22 58 24 32](https://github.com/user-attachments/assets/048b1094-de71-4aae-9f91-a63dcfe126a5)
![Victoria 3 Screenshot 2024 08 12 - 22 58 32 23](https://github.com/user-attachments/assets/3eae6173-9fa3-4e7d-ab5e-1de434274338)

### 問題のあるインターフェイス

軍隊/艦隊選択画面

### 問題のテキスト

（国名）からの軍
（国名）からの艦隊

### 希望する変更

（国名）の軍
（国名）の艦隊

### 変更の理由（概要）

表現として不自然なため

### ゲームバージョン

1.7.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通り修正しました。対応遅れ申し訳ありませんでした。
