### ISSUE TITLE
Major/Minor Unification

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#1013]
### スクリーンショット

![major](https://github.com/user-attachments/assets/bb016f79-7074-4fae-8eca-da78218ec4ef)
![minor](https://github.com/user-attachments/assets/8239c6de-6fd7-4ab7-89a6-1fbd84a3b973)

### 問題の用語

大国統一/小国統一

### 英語版の表現

Major Unification/Minor Unification

### 希望する変更

大統一/小統一

### 変更の理由（概要）

ゲームメカニズムに沿った改訳

### 変更の理由（詳細）

国家形成において
・統一外交戦が使用可能
・直接支配や属国にする必要が無く、外交上の支援だけで統合できる
・同一ティアでも形成可能
の条件で形成できるものをMajor Unification、できないものをMinor Unificationとしている。

ゲーム上では国の大小とは直接関係なく、上述のメカニズムが使用可能かどうかだけで分けられているため、
例えば神聖ローマ帝国や中国などの大国も「小国統一」とされていて紛らわしい。
そのため誤解を招かないような名称に改訳したい。

### ゲームバージョン

1.7.X

### MOD有無

翻訳改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
提案通り修正しました。
