### ISSUE TITLE
（威信内訳）弾薬の生産者よりの+20 威信 第1位

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#1014]
### スクリーンショット

![image](https://github.com/user-attachments/assets/f32a2aaf-7451-49b0-a2d6-cd5cc0d669f4)

### 問題のツールチップ

威信マウスオーバー>主要生産国数値マウスオーバー

### 問題の表現

[Goods.GetTextIcon][Goods.GetName]の生産者よりの#v $VAL|=+$#! [concept_prestige]#v 第$SPOT|v$位#!

### 問題箇所の英文

#v $VAL|=+$#! [concept_prestige] from #v ##$SPOT|v$#! producer of [Goods.GetTextIcon][Goods.GetName]

### 希望する変更

#v $VAL|=+$#! [concept_prestige] [Goods.GetTextIcon][Goods.GetName]#v 第$SPOT|v$位#!の生産国

### 変更の理由（概要）

日本語として不自然

### 変更の理由（詳細）

![image](https://github.com/user-attachments/assets/a4007c1c-5465-4d91-b280-91271d900dbf)

### プレイ国家

フランス

### ゲームバージョン

1.7.X

### MOD有無

日本語改善Mod

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原文通り修正しました。
