### ISSUE TITLE
かんがい

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#1018]
### スクリーンショット

![irrigation](https://github.com/user-attachments/assets/98733958-770d-4218-8881-6d08b59eac47)

### 問題の用語

かんがい自動化

### 英語版の表現

Automatic Irrigation

### 希望する変更

灌漑自動化

### 変更の理由（概要）

交ぜ書きの修正

### 変更の理由（詳細）

公文書や新聞等では常用漢字を平仮名にする交ぜ書きをするが、ゲームのテキストは常用漢字に縛られる必要はないため、漢字表記に修正したい。
Issue #945 で「こう着」を「膠着」に修正しており、それと同様の漢字表記修正。

### ゲームバージョン

1.7.X

### MOD有無

翻訳改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。
