### ISSUE TITLE
leverageツールチップの誤訳

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#1019]
### スクリーンショット

![leverage1](https://github.com/user-attachments/assets/3cd61c76-528f-4877-8115-9b371ddef044)
![leverage2](https://github.com/user-attachments/assets/79a81d9b-a7fc-46b6-b1f5-79edd5eda77c)

### 問題のツールチップ

leverageツールチップ

### 問題の表現

[SCOPE.sCountry('target').GetName]と歩調を合わせている[concept_power_bloc_leader]
[SCOPE.sCountry('target').GetName]と戦略的に近似している

### 問題箇所の英文

[concept_power_bloc_leader] being adjacent to [SCOPE.sCountry('target').GetName]
strategic adjacency to [SCOPE.sCountry('target').GetName]

### 希望する変更

[concept_power_bloc_leader]が[SCOPE.sCountry('target').GetName]に隣接している
[SCOPE.sCountry('target').GetName]と戦略的重要地域が隣接している

### 変更の理由（概要）

誤訳の修正

### 変更の理由（詳細）

この補正値は勢力圏のリーダー国と対象国が隣接している場合に付く補正であり、ゲーム上の挙動に合わせた訳語に修正したい。

### プレイ国家

どこでも

### ゲームバージョン

1.7.X

### MOD有無

翻訳改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
提案通り修正しました。
