### ISSUE TITLE
収獲状況

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#1020]
### スクリーンショット

![Victoria 3 Screenshot 2024 11 24 - 18 04 33 48](https://github.com/user-attachments/assets/e01c012b-50b8-4e88-9445-742a2edd2ea9)

### 問題の用語

収獲状況

### 英語版の表現

Harvest Condition

### 希望する変更

収穫補正　等

### 変更の理由（概要）

用語として違和感があるため

### 変更の理由（詳細）

農作物の収穫に影響を及ぼす自然現象を表す用語で「○○で収獲状況が開始」というように使用されているため、現行では違和感を感じます。
Harvest Condition自体は作況と訳すのが一般的なようですが、「収穫補正」とかでも良いのではないかなと思います。

ちなみに収「獲」の漢字が使われていますが、収「穫」の方が適切と思われますので、同時に修正をお願いしたいです。

### ゲームバージョン

1.8.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
作況変動、で修正しました
