### ISSUE TITLE
収獲状況－凍結

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#1021]
### スクリーンショット

![Victoria 3 Screenshot 2024 11 24 - 18 54 02 87](https://github.com/user-attachments/assets/6dd0c1ec-b47a-4f32-96ba-70fa53f3342a)

### 問題の用語

凍結

### 英語版の表現

Frost

### 希望する変更

寒波、寒気　等

### 変更の理由（概要）

違和感があるため

### 変更の理由（詳細）

寒波や寒気の方が適切かと思います

### ゲームバージョン

1.8.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
関連エントリの一部も修正しました。起票ありがとうございました。

Drought　干ばつ
Flood　洪水
Frost　凍結　→　霜
Wildfire　野火
Hailstorm　ひょうの嵐　→　雹害
Locust Swarm　イナゴの大群　→　蝗害
Heatwave　熱波
Disease Outbreak　疫病の感染爆発　→　悪疫
Extreme Winds　暴風
Torrential Rains　集中豪雨
Pollinator Surge　授粉媒介者の急増
Optimal Sunlight　最適な太陽光　→　最適な日照
Moderate Rainfall　適度な雨
