### ISSUE TITLE
収獲状況の期間を示す形容詞

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#1025]
### スクリーンショット

![Victoria 3 Screenshot 2024 11 24 - 22 09 41 39](https://github.com/user-attachments/assets/c2fbd44f-2579-4f4e-87e0-b7235a586deb)

### 問題の用語

収獲状況の期間を示す形容詞

### 英語版の表現

変更の理由に記載

### 希望する変更

一見して期間の違いがわかりやすいものへの変更

### 変更の理由（概要）

違いがわかりにくいのと一部誤訳がある

### 変更の理由（詳細）

収獲状況（干ばつ・洪水など収穫に影響を及ぼす自然災害）の期間（キー名にDURATIONとあるため期間を表していると推測）を表す形容詞について、現在以下のようになっているが、違いがわかりにくいのと、一部誤訳がある。

（日本語版）
 HARVEST_CONDITION_DURATION_LABEL_VERY_HIGH: "終わりのない"
 HARVEST_CONDITION_DURATION_LABEL_HIGH: "終わりが見えない"
 HARVEST_CONDITION_DURATION_LABEL_MODERATE: "不朽の"
 HARVEST_CONDITION_DURATION_LABEL_LOW: "長引く"
 HARVEST_CONDITION_DURATION_LABEL_VERY_LOW: "衰えていく"
 HARVEST_CONDITION_DURATION_LABEL_LOWEST: "助成の"

（英語版）
 HARVEST_CONDITION_DURATION_LABEL_VERY_HIGH: "Endless"
 HARVEST_CONDITION_DURATION_LABEL_HIGH: "No end in sight"
 HARVEST_CONDITION_DURATION_LABEL_MODERATE: "Enduring"
 HARVEST_CONDITION_DURATION_LABEL_LOW: "Lingering"
 HARVEST_CONDITION_DURATION_LABEL_VERY_LOW: "Waning"
 HARVEST_CONDITION_DURATION_LABEL_LOWEST: "Subsiding"

元の単語の意味を活かすとあまり良い訳案が思いつかないので、一部単語の意味が変わってしまいますが
一案として

 HARVEST_CONDITION_DURATION_LABEL_VERY_HIGH: "終わりのない"
 HARVEST_CONDITION_DURATION_LABEL_HIGH: "長期にわたる"
 HARVEST_CONDITION_DURATION_LABEL_MODERATE: "中期的な"
 HARVEST_CONDITION_DURATION_LABEL_LOW: "長引く"
 HARVEST_CONDITION_DURATION_LABEL_VERY_LOW: "短期的な"
 HARVEST_CONDITION_DURATION_LABEL_LOWEST: "一時的な"

のような感じではどうかなと思います。
プロジェクトの方でご議論ください。

また、形容詞と自然現象名の間に不要な「の」が入っているので、こちらの修正もお願いしたいです。
よろしくお願いします。

### ゲームバージョン

1.8.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
お待たせしました。議論の結果、原文の表現を活かしつつ程度の差が区別できる日本語訳に修正しました。
