### ISSUE TITLE
アップデートで追加・変更された法律名

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#1027]
### スクリーンショット

![20241125145327_1](https://github.com/user-attachments/assets/5729bbd4-936e-46d6-aeea-1c5b271a6a7b)

### 問題の用語

カーストに基づく覇権国家・カースト制度が施行されていません・肯定的アクション・企業国家・治安維持なし・労働基本権の無保障・集団農業

### 英語版の表現

Caste Hegemony・Caste Not Enforced・Affirmative Action・Corporate State・No Home Affairs・No Workers' Rights・Collectivized Agriculture

### 希望する変更

カースト支配・カースト非施行・肯定的措置・協同体国家・内務省なし・労働者の権利なし・集団化農業

### 変更の理由（概要）

誤訳の修正、および他の訳と合わせるため

### 変更の理由（詳細）

カーストに基づく覇権国家　→　カースト支配　誤訳であるため
カースト制度が施行されていません　→　カースト非施行　長すぎることに加え、法律名としておかしい
肯定的アクション　→　肯定的措置　誤訳であり、法律名としてもおかしい
企業国家　→　協同体国家　東インド会社やハドソン湾会社のようなものではなく、イタリアのファシスト政権がモデルのため
治安維持なし　→　内務省なし　原文がHome Affairsであるため
労働基本権の無保障　→　労働者の権利なし　警察なし（No Police）や学校なし（No Schools）に合わせる
集団農業　→　集団化農業　商業化農業（Commercialized Agriculture）に合わせる

### ゲームバージョン

1.8.X

### MOD有無

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
