### ISSUE TITLE
アップデートで追加・変更された政体名と称号名

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#1030]
### スクリーンショット

なし

### 問題の固有名詞：希望する変更

行政区域：総督領
ナワバテ：太守国
ナワブ：太守
ベーグム：女太守
ナワブザーダ：次期太守
ナワブザーディ：次期太守
メータル：メフタル
メリクドム：マリク国
ニザーム王国：ニザーム国
ディーワーン：ディーワーン国
ラワラーン：ラーワル国
企業国家：協同体国家
ファランジズト国家：ファランヘ主義国家
スタスミニスター：首相
ヘフェイ：総統
へファ：総統
フューラー：総統
フューレリン：総統
ナワブ・べーガム：ナワーブ・ベーグム
シャーザディ：シャーザーディ
ニザム：ニザーム
ディワン：ディーワーン

### 変更の理由（概要）

誤訳、もしくは定訳に沿っていないため

### ゲームバージョン

1.8.X

### MOD有無

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
