### ISSUE TITLE
政治運動の名称

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#1031]
### スクリーンショット

なし

### 問題の固有名詞：希望する変更

[宗教名]伝統主義者運動：[宗教名]伝統主義運動
[国名]の至上主義運動：[国名]至上主義運動
[文化名]全国運動：[文化名]国民運動
王党派運動：君主主義運動
絶対主義派運動：絶対主義運動
連合会議：統一会議
オルレアン主義運動：オルレアニスム運動
レジティミスト運動：レジティミスム運動
ボナパルティスト運動：ボナパルティスム運動
ファシスト運動：ファシズム運動
協調組合主義運動：コーポラティズム運動
フェミニスト運動：フェミニズム運動
近代化主義運動：近代化運動
全インド・ヒンドゥー・マハーサバー：全インド・ヒンドゥー大会
イスラム民族主義運動：ムスリム民族主義運動

### 変更の理由（概要）

誤訳、もしくは定訳に沿っていないため

### 変更の理由（詳細）

[宗教名]伝統主義者運動：[宗教名]伝統主義運動　「主義」を推進する運動のため
[国名]の至上主義運動：[国名]至上主義運動　「の」は必要ない
[文化名]全国運動：[文化名]国民運動　インド国民運動を意識していると思われるため
王党派運動：君主主義運動　運動名として違和感がある
絶対主義派運動：絶対主義運動　「派」は必要ない
連合会議：統一会議　一般的ではない表現
オルレアン主義運動：オルレアニスム運動　Issue-732に合わせる
レジティミスト運動：レジティミスム運動　「主義」を推進する運動のため
ボナパルティスト運動：ボナパルティスム運動　同上
ファシスト運動：ファシズム運動　同上
協調組合主義運動：コーポラティズム運動　Issue-785に合わせる
フェミニスト運動：フェミニズム運動　同上
近代化主義運動：近代化運動　主義ではない
全インド・ヒンドゥー・マハーサバー：全インド・ヒンドゥー大会　分かりにくいため、党名の方と同じにした
イスラム民族主義運動：ムスリム民族主義運動　原文を尊重

### ゲームバージョン

1.8.X

### MOD有無

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
