### ISSUE TITLE
大統領府軍

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#1032]
### スクリーンショット

![20241125213021_1](https://github.com/user-attachments/assets/61ebceba-e6b5-475e-af56-e6697943319b)

### 問題の固有名詞：希望する変更

大統領府軍：管区軍

### 変更の理由（概要）

誤訳であるため

### 変更の理由（詳細）

訳の変更に合わせ、解説文も以下の様にしたい。

大統領府軍は植民地インドの武装勢力で、通常、ヨーロッパ将校の指揮下にある先住民のインド出身のセポイで構成されています。

↓

管区軍は植民地インドの軍隊で、通常、ヨーロッパ人将校の指揮下にある先住民のインド出身のセポイで構成されています。

### ゲームバージョン

1.8.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
