### ISSUE TITLE
州名変更時のインターフェイス

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#1033]
### スクリーンショット

![20241126191329_1](https://github.com/user-attachments/assets/c3753e53-de58-4734-a69f-dc4f9163d8b8)

### 問題のあるインターフェイス

州名変更ウィンドウ

### 問題のテキスト

名前をカスタマイズ

国家
国家の首都
港町
農業の町
採鉱の町
林業の町

国家とその拠点の名前をカスタマイズします

### 希望する変更

名前を変更

州
州都
港湾町
農業町
鉱業町
林業町

州と街の名前を変更します

### 変更の理由（概要）

誤訳修正と訳の統一のため

### 変更の理由（詳細）

名前をカスタマイズ　→　名前を変更　冗長

国家　→　州　誤訳
国家の首都　→　州都　同上
港町　→　港湾町　下記に合わせ三文字表記にする
農業の町　→　農業町　「の」は冗長、〇業で統一する
採鉱の町　→　鉱業町　同上
林業の町　→　林業町　同上

国家とその拠点の名前をカスタマイズします　→　州と町の名前を変更します　ツールチップだが関連するため同時に直したい。

### ゲームバージョン

1.8.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Nebimo** [comment]
鉱業に関連する施設を対象としたハブに対し、工業町は不適切と考えます。鉱業町ならばともかく。
バニラにおいて gfx\map\city_data\city_types の *_mine.txt で紐づけされている施設が対象です。
このファイル内ではバニラにおける炭鉱・鉄鉱山・鉛鉱山・硫黄鉱山・金鉱脈・採金地が鉱業関連の施設として紐づけされています。
工業の場合、バニラにおける製鉄所等が連想されます。ですがバニラにおいて製鉄所増設に伴うグラフィック更新は
*_city.txt に紐づけされています。
以上より、「工業町」の採用は見直していただきたいと考えます。

**Comment by ChiefIdeologue** [comment]
すみません「工業」は「鉱業」の誤字でした、修正しました。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
