### ISSUE TITLE
カースト制度が施行されていません

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#1038]
### スクリーンショット

![Victoria 3 Screenshot 2024 11 29 - 19 50 34 72](https://github.com/user-attachments/assets/b7ad31db-9aa6-4769-9a29-cf4846093f1b)

### 問題の用語

カースト制度が施行されていません

### 英語版の表現

Caste Not Enforced

### 希望する変更

カースト制度未施行、カースト制度施行なし　等

### 変更の理由（概要）

ここだけですます調で不自然なため

### ゲームバージョン

1.8.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
#1027 にて既に議論中ですのでクローズいたします
