### ISSUE TITLE
政治運動活動の閾値

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#1039]
### スクリーンショット

![Victoria 3 Screenshot 2024 11 30 - 15 46 39 05](https://github.com/user-attachments/assets/b83472d1-41d8-4ece-ac1d-01bfdcd50888)

### 問題の用語

政治運動活動の閾値

### 英語版の表現

変更の理由に記載

### 希望する変更

変更の理由に記載

### 変更の理由（概要）

日本語として不自然な部分があるため

### 変更の理由（詳細）

（現行）
 RADICALISM_PASSIVE: "#b 受動的#!"
 RADICALISM_AGITATING: "#b 扇動的#!"
 RADICALISM_PROTESTING: "#N 抗議中#!"
 RADICALISM_MILITANT: "#N 武闘派#!"

（英語）
 RADICALISM_PASSIVE: "#b Passive#!"
 RADICALISM_AGITATING: "#b Agitating#!"
 RADICALISM_PROTESTING: "#N Protesting#!"
 RADICALISM_MILITANT: "#N Militant#!"

（変更案）
 RADICALISM_PASSIVE: 消極的
 RADICALISM_AGITATING: 扇動的
 RADICALISM_PROTESTING: 抗議的
 RADICALISM_MILITANT: 闘争的 or 戦闘的 or 過激

### ゲームバージョン

1.8.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
RADICALISM_PASSIVE: 消極
RADICALISM_AGITATING: 扇動
RADICALISM_PROTESTING: 抗議
RADICALISM_MILITANT: 闘争

「的」を無くす形で修正しました。起票ありがとうございました。
