### ISSUE TITLE
【修正提案】都市センター Urban Center

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#104]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![Urban_Center](https://user-images.githubusercontent.com/50406316/198453869-12a43e5e-a760-445b-a1d9-520a3ce23cb3.png)

## 問題の用語（必須）
都市センター

## 英語版の表現（任意）
Urban Center

## 希望する変更（必須）
市街地

## 変更の理由（必須）
誤訳の修正

## ゲームバージョン（必須）
1.0.3

## DLC有無（必須）
無し

## MOD有無（必須）
なし

**Comment by matanki-saito** [comment]
内部検討中です。進捗がありましたらここに報告します。校正メンバーと議論が必要である場合はお手数ですが#github議論板にて確認をお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1035372762690236457/1035372762690236457

**Comment by starjard** [comment]
市街地に変更でクローズします。
