### ISSUE TITLE
年のトリガーに関して

### ISSUE THREAD

**Issue by Nebimo** [matanki-saito/vic3jpadvmod#1043]
### スクリーンショット

![Untitled](https://github.com/user-attachments/assets/b8e7432a-2b0c-47ad-9b66-d23e99eeecf8)

### 問題のツールチップ

年に関するトリガー

### 問題の表現

 TRIGGER_YEAR_EQUAL:0 "西暦が$NUM$である"
 TRIGGER_YEAR_EQUAL_NOT:0 "西暦が$NUM$#bold ではない#!"
 TRIGGER_YEAR_LESS_THAN:0 "$NUM$以前"
 TRIGGER_YEAR_LESS_THAN_OR_EQUAL:0 "$NUM$以前あるいは同年"
 TRIGGER_YEAR_GREATER_THAN:0 "$NUM$以後"
 TRIGGER_YEAR_GREATER_THAN_OR_EQUAL:0 "$NUM$以後あるいは同年"

### 希望する変更

 TRIGGER_YEAR_EQUAL:0 "$NUM$年である"
 TRIGGER_YEAR_EQUAL_NOT:0 "$NUM$年#bold ではない#!"
 TRIGGER_YEAR_LESS_THAN:0 "$NUM$年より前である"
 TRIGGER_YEAR_LESS_THAN_OR_EQUAL:0 "$NUM$年以前である"
 TRIGGER_YEAR_GREATER_THAN:0 "$NUM$年より後である"
 TRIGGER_YEAR_GREATER_THAN_OR_EQUAL:0 "$NUM$年以後である"

### 変更の理由（概要）

単位抜け・表記が統一されていない・表記がくどい

### 変更の理由（詳細）

概要の通りです。
表記の見直しを検討願います。

### ゲームバージョン

1.8.X

### MOD有無

日本語改善MOD

**Comment by inarizushi0309** [comment]
原案通り修正しました。起票ありがとうございました。
