### ISSUE TITLE
収穫状況の期間

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#1044]
### スクリーンショット

![Victoria 3 Screenshot 2024 12 07 - 16 31 07 05](https://github.com/user-attachments/assets/087b16b6-a2a8-434e-978e-a3e3bc1d920d)

### 問題のあるインターフェイス

収穫状況の期間

### 問題のテキスト

最小$DURATION$で進行

### 希望する変更

少なくともあと$DURATION$続く　最短であと$DURATION$続く　等

（原文）
```HARVEST_CONDITION_DURATION_MORE_THAN: "at least $DURATION$ to go"```

### 変更の理由（概要）

日本語として不自然なため

### ゲームバージョン

1.8.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通り修正しました。起票ありがとうございました。
