### ISSUE TITLE
交渉支援

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#1045]
### スクリーンショット

![Victoria 3 Screenshot 2024 12 11 - 21 00 08 04](https://github.com/user-attachments/assets/114b5d81-b3d0-4db3-845f-b165669ad622)

### 問題のあるインターフェイス

外交戦画面

### 問題のテキスト

交渉支援

（英語版）
Offer Support

### 希望する変更

支援交渉、支援提案　など

### 変更の理由（概要）

日本語として不自然なため

### ゲームバージョン

1.8.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by inarizushi0309** [comment]
「支援提案」に修正しました。起票ありがとうございました。
