### ISSUE TITLE
勢力圏加盟可否に関するフィード

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#1046]
### スクリーンショット

![Victoria 3 Screenshot 2024 12 14 - 17 38 06 87](https://github.com/user-attachments/assets/e461713d-af3c-4b41-9ed2-819b5db1d249)

### 問題のあるインターフェイス

勢力圏加盟可否に関するフィード

### 問題のテキスト

```join_power_bloc_proposal_third_party_accepted_name: "$join_power_bloc_proposal_declined_name$"```
```join_power_bloc_proposal_third_party_declined_name: "$join_power_bloc_proposal_accepted_name$"```

通知タイトルと内容が逆になっている
（上記の呼び出す変数が逆になっているためと思われます）

### 希望する変更

```join_power_bloc_proposal_third_party_accepted_name: "$join_power_bloc_proposal_accepted_name$"```
```join_power_bloc_proposal_third_party_declined_name: "$join_power_bloc_proposal_declined_name$"```

### 変更の理由（概要）

通知タイトルと内容が逆になっているため

### ゲームバージョン

1.8.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
即日対応しました。起票ありがとうございました。
