### ISSUE TITLE
作況変動開始フィード

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#1049]
### スクリーンショット

![Victoria 3 Screenshot 2024 12 22 - 17 24 15 10](https://github.com/user-attachments/assets/f48cbf1b-fd75-4a04-b8ee-0d99274277ea)

### 問題のあるインターフェイス

作況変動開始フィード

### 問題のテキスト

```notification_harvest_condition_started_in_market_desc: "[SCOPE.sHCA('area').GetRemainingDurationLabel][SCOPE.sHCA('area').GetType.GetName]が[SCOPE.sS('state').GetCountry.GetFlagTextIcon][SCOPE.sS('state').GetName]で始まり、[SCOPE.GetValue('num_states')|0v]個の市場内の[Concept('concept_state', '$concept_states$')]に影響を与えています。[Concept('concept_harvest_condition_intensity', '$concept_harvest_condition_intensity_short$')]は[SCOPE.GetValue('intensity')|1v]です。"```

```notification_harvest_condition_started_in_country_desc: "[SCOPE.sHCA('area').GetRemainingDurationLabel]の[SCOPE.sHCA('area').GetType.GetName]が[SCOPE.sS('state').GetCountry.GetFlagTextIcon] [SCOPE.sS('state').GetName]で始まり、[SCOPE.GetValue('num_states')|0v]個のあなたの[Concept('concept_state', '$concept_states$')]に影響を与えています。[Concept('concept_harvest_condition_intensity', '$concept_harvest_condition_intensity_short$')]は[SCOPE.GetValue('intensity')|1v]です。"```

### 希望する変更

```notification_harvest_condition_started_in_market_desc: "[SCOPE.sHCA('area').GetRemainingDurationLabel][SCOPE.sHCA('area').GetType.GetName]が[SCOPE.sS('state').GetCountry.GetFlagTextIcon][SCOPE.sS('state').GetName]で始まり、市場内の[SCOPE.GetValue('num_states')|0v][Concept('concept_state', '$concept_states$')]に影響を与えています。[Concept('concept_harvest_condition_intensity', '$concept_harvest_condition_intensity_short$')]は[SCOPE.GetValue('intensity')|1v]です。"```

```notification_harvest_condition_started_in_country_desc: "[SCOPE.sHCA('area').GetRemainingDurationLabel][SCOPE.sHCA('area').GetType.GetName]が[SCOPE.sS('state').GetCountry.GetFlagTextIcon][SCOPE.sS('state').GetName]で始まり、あなたの[SCOPE.GetValue('num_states')|0v][Concept('concept_state', '$concept_states$')]に影響を与えています。[Concept('concept_harvest_condition_intensity', '$concept_harvest_condition_intensity_short$')]は[SCOPE.GetValue('intensity')|1v]です。"```

### 変更の理由（概要）

日本語として自然になるように

### ゲームバージョン

1.8.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通り修正しました。起票ありがとうございました。
