### ISSUE TITLE
【修正提案】電力プラント Power Plants

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#105]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![Power_Plants](https://user-images.githubusercontent.com/50406316/198455497-d46629cd-eb05-42a0-a0eb-7244066d0954.png)

## 問題の用語（必須）
電力プラント

## 英語版の表現（任意）
Power Plants

## 希望する変更（必須）
発電所

## 変更の理由（必須）
電力プラントでも間違いではないが、一般的には発電所と訳すのが定訳であるため

## ゲームバージョン（必須）
1.0.3

## DLC有無（必須）
無し

## MOD有無（必須）
なし

**Comment by matanki-saito** [comment]
内部検討中です。進捗がありましたらここに報告します。校正メンバーと議論が必要である場合はお手数ですが#github議論板にて確認をお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1035373540607787068/1035373540607787068

**Comment by starjard** [comment]
変更しました。これにてクローズします。
