### ISSUE TITLE
【修正提案】製鋼工場 Steel Mills

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#106]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![Steel_Mills](https://user-images.githubusercontent.com/50406316/198462562-0bc929c9-7a49-4407-839b-337c231632d7.png)

## 問題の用語（必須）
製鋼工場

## 英語版の表現（任意）
Steel Mills

## 希望する変更（必須）
製鉄所

## 変更の理由（必須）
製鋼工場でも間違いではないが、製鉄所のほうがより一般的な訳語であるため

## ゲームバージョン（必須）
1.0.3

## DLC有無（必須）
無し

## MOD有無（必須）
なし

**Comment by matanki-saito** [comment]
内部検討中です。進捗がありましたらここに報告します。校正メンバーと議論が必要である場合はお手数ですが#github議論板にて確認をお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1035376566026391653/1035376566026391653

**Comment by starjard** [comment]
こちら、製鉄所で確定させてクローズします
