### ISSUE TITLE
【修正提案】後見人 Legal Guardianship

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#107]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![Legal_Guardianship](https://user-images.githubusercontent.com/50406316/198466314-498b3d79-5bab-4363-ac90-7bade07f6b7c.png)

## 問題の用語（必須）
後見人
女性は法的には男性の保護下にあり、ほとんど権利を享受していません。

## 英語版の表現（任意）
Legal Guardianship
Women are legally under the guardianship of men and enjoy very few rights.

## 希望する変更（必須）
被後見
女性は法的には男性の後見下にあり、ほとんど権利を享受していません。

## 変更の理由（必須）
後見している側ではなくされている側を指すため。
説明テキストではguardianship が保護とされており、訳語不統一になっているため、こちらも後見に統一する。

## ゲームバージョン（必須）
1.0.3

## DLC有無（必須）
無し

## MOD有無（必須）
なし

**Comment by matanki-saito** [comment]
内部検討中です。進捗がありましたらここに報告します。校正メンバーと議論が必要である場合はお手数ですが#github議論板にて確認をお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1035379409575743550/1035379409575743550

**Comment by starjard** [comment]
翻訳チームよりLegalを訳出したほうがいいという意見が出たため、最終的に「法的被後見」と決定しました。これにてクローズします。
