### ISSUE TITLE
【修正提案】国家至上 National Supremacy

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#108]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![National_Supremacy](https://user-images.githubusercontent.com/50406316/198470547-ca079382-c63f-42bb-974b-b293e0da8411.png)

## 問題の用語（必須）
国家至上 

## 英語版の表現（任意）
National Supremacy

## 希望する変更（必須）
国民至上

## 変更の理由（必須）
主要文化とheriageおよび言語が共通の文化だけ市民権がある、いわゆる国民国家（Nation State）を想定した制度であり、Nationalは国家よりは国民と訳したほうが適切だと考えるため

## ゲームバージョン（必須）
1.0.3

## DLC有無（必須）
無し

## MOD有無（必須）
なし

**Comment by matanki-saito** [comment]
内部検討中です。進捗がありましたらここに報告します。校正メンバーと議論が必要である場合はお手数ですが#github議論板にて確認をお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1035380918690512957/1035380918690512957

**Comment by starjard** [comment]
国民至上に変更でクローズします。
