### ISSUE TITLE
建造物の生産性のテキストおよびツールチップ

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#109]
## スクリーンショット（必須）
![text1](https://user-images.githubusercontent.com/50406316/198485673-87f66035-70f9-443f-9567-98a93e6f682c.png)
![text2](https://user-images.githubusercontent.com/50406316/198485698-e3dc74be-720a-4af1-a367-9b7b6c61170e.png)
![text3](https://user-images.githubusercontent.com/50406316/198487215-f599de05-88d0-4f22-8045-725bec855469.png)

## 問題のツールチップ（必須）
建造物の収益性順位の本文及びツールチップ

## 問題の表現（必須）
・本文
 BUILDING_RANK:0 "[Building.GetProfitabilityCompareIconInType] ##[Building.GetProfitabilityRankInType|v] [Building.GetBuildingType.GetNameNoFormatting]"
 BUILDING_RANK_WORLD:0 "世界の[Building.GetProfitabilityCompareIcon] ##[Building.GetProfitabilityRank|v] "

・ツールチップ
 TOOLTIP_BUILDING_HEALTH_WORLD:0 "#BOLD #V [Building.GetName]#!#!\n#variable ##[Building.GetProfitabilityRank]#!は世界で最も生産的な施設です\n#variable [Building.GetProfitability]#!([Building.GetProfitabilityCompareIcon])平均的な施設との比較[concept_productivity]\n\n収入: #tooltip:[Building.GetTooltipTag],EARNINGS_BREAKDOWN @money!#bold [Building.GetEarnings|D=+]#!#!\n賃金: #BOLD #N @money!-[Building.GetLastWagesExpenses|D-]#!#!\n"
 TOOLTIP_BUILDING_HEALTH_BUILDING_TYPE:0 "#BOLD #V [Building.GetName]#!#!\n#variable ##[Building.GetProfitabilityRankInType]#!は世界で最も生産的な[Building.GetName]です\n#variable [Building.GetProfitabilityInType]#! ([Building.GetProfitabilityCompareIconInType])平均的な[Building.GetBuildingType.GetName]との比較[concept_productivity]\n\n収入: #tooltippable #tooltip:[Building.GetTooltipTag],EARNINGS_BREAKDOWN @money!#bold [Building.GetEarnings|D=+]#!#!#!\n賃金: #BOLD #N @money!-[Building.GetLastWagesExpenses|D-]#!#!\n"
 TOOLTIP_BUILDING_PRODUCTIVITY:1 "#header [concept_productivity]#!\n値: @money![Building.GetAverageAnnualEarningsPerEmployeeFormatted] / 年 (#tooltippable #tooltip:[Building.GetTooltipTag],TOOLTIP_BUILDING_HEALTH_BUILDING_TYPE,GraphTooltipTypeProfitability [Building.GetProfitabilityCompareIconInType]#!#! / #tooltippable #tooltip:[Building.GetTooltipTag],TOOLTIP_BUILDING_HEALTH_WORLD,GraphTooltipWorldProfitability [Building.GetProfitabilityCompareIcon]#!#!)\n$TOOLTIP_DELIMITER$\n#variable ##[Building.GetProfitabilityRankInType]#!は世界で最も生産的な[Building.GetBuildingType.GetName]です\n[Building.GetProfitabilityInType]平均的な[Building.GetBuildingType.GetName]との比較[concept_productivity]\n\n#variable ##[Building.GetProfitabilityRank]#!は世界で最も生産的な施設です\n[Building.GetProfitability] 平均的な施設との比較[concept_productivity] \n"

## 問題箇所の英文（任意）
・本文
 BUILDING_RANK:0 "[Building.GetProfitabilityCompareIconInType] ##[Building.GetProfitabilityRankInType|v] [Building.GetBuildingType.GetNameNoFormatting]"
 BUILDING_RANK_WORLD:0 "[Building.GetProfitabilityCompareIcon] ##[Building.GetProfitabilityRank|v] in the world"

・ツールチップ
 TOOLTIP_BUILDING_HEALTH_WORLD:0 "#BOLD #V [Building.GetName]#!#!\n#variable ##[Building.GetProfitabilityRank]#! most productive Building in the World\n#variable [Building.GetProfitability]#! ([Building.GetProfitabilityCompareIcon]) [concept_productivity] compared to the average Building\n\nEarnings: #tooltip:[Building.GetTooltipTag],EARNINGS_BREAKDOWN @money!#bold [Building.GetEarnings|D=+]#!#!\nWages: #BOLD #N @money!-[Building.GetLastWagesExpenses|D-]#!#!\n"
 TOOLTIP_BUILDING_HEALTH_BUILDING_TYPE:0 "#BOLD #V [Building.GetName]#!#!\n#variable ##[Building.GetProfitabilityRankInType]#! most productive [Building.GetName] in the World\n#variable [Building.GetProfitabilityInType]#! ([Building.GetProfitabilityCompareIconInType]) [concept_productivity] compared to the average [Building.GetBuildingType.GetName]\n\nEarnings: #tooltippable #tooltip:[Building.GetTooltipTag],EARNINGS_BREAKDOWN @money!#bold [Building.GetEarnings|D=+]#!#!#!\nWages: #BOLD #N @money!-[Building.GetLastWagesExpenses|D-]#!#!\n"
 TOOLTIP_BUILDING_PRODUCTIVITY:1 "#header [concept_productivity]#!\nValue: @money![Building.GetAverageAnnualEarningsPerEmployeeFormatted] / year (#tooltippable #tooltip:[Building.GetTooltipTag],TOOLTIP_BUILDING_HEALTH_BUILDING_TYPE,GraphTooltipTypeProfitability [Building.GetProfitabilityCompareIconInType]#!#! / #tooltippable #tooltip:[Building.GetTooltipTag],TOOLTIP_BUILDING_HEALTH_WORLD,GraphTooltipWorldProfitability [Building.GetProfitabilityCompareIcon]#!#!)\n$TOOLTIP_DELIMITER$\n#variable ##[Building.GetProfitabilityRankInType]#! most productive [Building.GetBuildingType.GetName] in the world \n[Building.GetProfitabilityInType] [concept_productivity] compared to the average [Building.GetBuildingType.GetName]\n\n#variable ##[Building.GetProfitabilityRank]#! most productive Building in the world \n[Building.GetProfitability] [concept_productivity] compared to the average Building\n"

## 希望する変更（必須）
・本文
 BUILDING_RANK:0 "[Building.GetProfitabilityCompareIconInType] [Building.GetBuildingType.GetNameNoFormatting]で##[Building.GetProfitabilityRankInType|v]位 "
 BUILDING_RANK_WORLD:0 "[Building.GetProfitabilityCompareIcon] 世界で##[Building.GetProfitabilityRank|v]位"

・ツールチップ
 TOOLTIP_BUILDING_HEALTH_WORLD:0 "#BOLD #V [Building.GetName]#!#!\n世界で#variable ##[Building.GetProfitabilityRank]#!番目に生産的な施設です\n平均的な建造物と比べた[concept_productivity]は#variable [Building.GetProfitability]#!([Building.GetProfitabilityCompareIcon])です\n\n収入: #tooltip:[Building.GetTooltipTag],EARNINGS_BREAKDOWN @money!#bold [Building.GetEarnings|D=+]#!#!\n賃金: #BOLD #N @money!-[Building.GetLastWagesExpenses|D-]#!#!\n"
 TOOLTIP_BUILDING_HEALTH_BUILDING_TYPE:0 "#BOLD #V [Building.GetName]#!#!\n世界で#variable ##[Building.GetProfitabilityRankInType]#!番目に生産的な[Building.GetName]です\n平均的な[Building.GetBuildingType.GetName]と比べた[concept_productivity]は#variable [Building.GetProfitabilityInType]#! ([Building.GetProfitabilityCompareIconInType])です\n\n収入: #tooltippable #tooltip:[Building.GetTooltipTag],EARNINGS_BREAKDOWN @money!#bold [Building.GetEarnings|D=+]#!#!#!\n賃金: #BOLD #N @money!-[Building.GetLastWagesExpenses|D-]#!#!\n"
 TOOLTIP_BUILDING_PRODUCTIVITY:1 "#header [concept_productivity]#!\n値: @money![Building.GetAverageAnnualEarningsPerEmployeeFormatted] / 年 (#tooltippable #tooltip:[Building.GetTooltipTag],TOOLTIP_BUILDING_HEALTH_BUILDING_TYPE,GraphTooltipTypeProfitability [Building.GetProfitabilityCompareIconInType]#!#! / #tooltippable #tooltip:[Building.GetTooltipTag],TOOLTIP_BUILDING_HEALTH_WORLD,GraphTooltipWorldProfitability [Building.GetProfitabilityCompareIcon]#!#!)\n$TOOLTIP_DELIMITER$\n世界で#variable ##[Building.GetProfitabilityRankInType]#!番目に生産的な[Building.GetBuildingType.GetName]です\n平均的な[Building.GetBuildingType.GetName]と比べた[concept_productivity]は[Building.GetProfitabilityInType]です\n\n世界で#variable ##[Building.GetProfitabilityRank]#!番名生産的な建造物です\n平均的な建造物と比べた[concept_productivity]は[Building.GetProfitability]です \n"

## 変更の理由（必須）
変数構造を把握していない翻訳ミスであるため

## ゲームバージョン（必須）
1.0.3

## DLC有無（必須）
なし

## MOD有無（必須）
なし

**Comment by matanki-saito** [comment]
内部検討中です。進捗がありましたらここに報告します。校正メンバーと議論が必要である場合はお手数ですが#github議論板にて確認をお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1035391840553271326/1035391840553271326

**Comment by matanki-saito** [comment]
修正案が分裂しているので纏めます
※順位の前についていた#は削除しています
BUILDING_RANK```[生産性増減アイコン] [施設名]第[順位]位```
BUILDING_RANK_WORLD```[生産性増減アイコン] 世界第[順位]位```
TOOLTIP_BUILDING_HEALTH_WORLD```[施設名]
世界で[順位]番目に生産的な施設です
平均的な建造物と比べた[コンセプト（生産性）]は[生産性%（全体比較）]（[生産性増減アイコン（全体比較）]）です

収入：@money![収入]
賃金：@money!-[賃金]```
TOOLTIP_BUILDING_HEALTH_BUILDING_TYPE```[施設名]
世界で[順位]番目に生産的な[施設名]です
平均的な[施設名]と比べた[コンセプト（生産性）]は[生産性%（同タイプ内比較）]（[生産性増減アイコン（同タイプ内比較）]）です

収入：@money![収入]
賃金：@money!-[賃金]```
TOOLTIP_BUILDING_PRODUCTIVITY```[コンセプト（生産性）]
値：@money![平均収入]/年（[生産性増減アイコン（全体比較）] / [生産性増減アイコン（同タイプ内比較）]）
---------------
世界で[順位]番目に生産的な[施設名]です
平均的な[施設名]と比べた[コンセプト（生産性）]は[生産性%（同タイプ内比較）]です

世界で[順位]番目に生産的な施設です
平均的な建造物と比べた[コンセプト（生産性）]は[生産性%（全体比較）]です ```

**Comment by inarizushi0309** [comment]
以上内容で修正しました
