### ISSUE TITLE
【修正提案】利益 Interest

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#110]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![interest](https://user-images.githubusercontent.com/50406316/198495500-4e1f4ff7-798f-46cd-839d-d59bfb8250c9.png)

## 問題の用語（必須）
利益

## 英語版の表現（任意）
Interest

## 希望する変更（必須）
利息

## 変更の理由（必須）
誤訳修正

## ゲームバージョン（必須）
1.0.3

## DLC有無（必須）
無し

## MOD有無（必須）
なし

**Comment by matanki-saito** [comment]
内部検討中です。進捗がありましたらここに報告します。校正メンバーと議論が必要である場合はお手数ですが#github議論板にて確認をお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1035394390602031126/1035394390602031126

**Comment by clamm0363** [comment]
修正しました
interest: 利子、interest rate: 利子率となるように修正しています。
