### ISSUE TITLE
【修正提案】奉仕 Services

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#111]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![Services](https://user-images.githubusercontent.com/50406316/198501441-58c1a770-0c90-4881-aaf1-49759153a3de.png)

## 問題の用語（必須）
奉仕

## 英語版の表現（任意）
Services

## 希望する変更（必須）
サービス

## 変更の理由（必須）
奉仕では直訳で違和感がある。Urban Center（市街地）で生産されるので、サービス業の役務提供を想定していると思われるため。

## ゲームバージョン（必須）
1.0.3

## DLC有無（必須）
無し

## MOD有無（必須）
なし

**Comment by matanki-saito** [comment]
内部検討中です。進捗がありましたらここに報告します。校正メンバーと議論が必要である場合はお手数ですが#github議論板にて確認をお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1035407542366519296/1035407542366519296

**Comment by Zousuikakka** [comment]
すいません投稿者に気づくのが遅れました。
