### ISSUE TITLE
Columbia District

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#112]
## スクリーンショット（任意）
![Columbia_District](https://user-images.githubusercontent.com/50406316/198504337-573ace5c-2173-4f40-a48c-103ff33bfa48.png)

## 問題の固有名詞（必須）
コロンビア特別区

## 希望する変更（必須）
コロンビア地区

## 変更の理由（必須）
USAの首都ではなく、当時の英領北米における未編入地の名称のこと。
https://en.wikipedia.org/wiki/Columbia_District

定訳があるわけではないが、首都の特別区ではないので、単純に地区と訳すほうがいいと思います。

## ゲームバージョン（必須）
1.0.3

## DLC有無（必須）
なし

## MOD有無（必須）
なし

**Comment by matanki-saito** [comment]
内部検討中です。進捗がありましたらここに報告します。校正メンバーと議論が必要である場合はお手数ですが#github議論板にて確認をお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1035414000646766632/1035414000646766632

**Comment by starjard** [comment]
変更しました、クローズします
