### ISSUE TITLE
【修正提案】臣下 subjet および君主国 overlord

### ISSUE THREAD

**Issue by N-der** [matanki-saito/vic3jpadvmod#114]
＜ゲームシステム用語＞

## 問題の用語（必須）

臣下
君主国

## 英語版の表現（任意）

subject
overlord

## 希望する変更（必須）

従属国
宗主国

## 変更の理由（必須）

外交関係を示す適切な用語ではないため。
puppet, tributary, dominion, protectorateなど幅広い主従関係を包括する用語なので、広い意味を持つ訳語を充てたい。
また、地の分としてもいくらか使われているため、そちらも変更すべき。

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

無し

## MOD有無（必須）

無し

**Comment by matanki-saito** [comment]
内部検討中です。進捗がありましたらここに報告します。校正メンバーと議論が必要である場合はお手数ですが#github議論板にて確認をお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1035440615774752811/1035440615774752811

**Comment by inarizushi0309** [comment]
原案通り修正しました。起票ありがとうございました。
