### ISSUE TITLE
【修正提案】公共施設 Institution

### ISSUE THREAD

**Issue by N-der** [matanki-saito/vic3jpadvmod#115]
＜ゲームシステム用語＞

## 問題の用語（必須）

公共施設

## 英語版の表現（任意）

Institution

## 希望する変更（必須）

政府機関、行政機関など

## 変更の理由（必須）

政府において行政を遂行するような、官公庁の役割を果たしているため。

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

無し

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。進捗がありましたらここに報告します。校正メンバーと議論が必要である場合はお手数ですが#github議論板にて確認をお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1035453490220245002/1035453490220245002

**Comment by oooFUNooo** [comment]
修正が完了しました。

**Comment by matanki-saito** [comment]
政府機関、行政機関など　ー＞　制度で修正しました。
