### ISSUE TITLE
「基本価格」のツールチップの説明文「物資が～」

### ISSUE THREAD

**Issue by WoodlandsGitHub** [matanki-saito/vic3jpadvmod#116]
## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/29177147/198524344-2c0bb211-c012-4cd6-95b2-b31db38b6e42.png)

## 問題のツールチップ（必須）

各商品にある「基本価格」のツールチップ

## 問題の表現（必須）

物資が需要と完全に等しい時の商品の価格です

## 問題箇所の英文（任意）

 concept_sell_orders_supply:0 "物資"
 concept_sell_orders_supply:0 "Supply"

※参考
 concept_base_price:0 "基本価格"
 concept_base_price_desc:1 "[Concept('concept_sell_orders','$concept_sell_orders_supply$')]が [Concept('concept_buy_orders','$concept_buy_orders_demand$')]と完全に等しい時の[concept_good]の価格です。"
 concept_base_price:0 "Base Price"
 concept_base_price_desc:1 "The price of a [concept_good] when its [Concept('concept_sell_orders','$concept_sell_orders_supply$')] exactly equal its [Concept('concept_buy_orders','$concept_buy_orders_demand$')]."

## 希望する変更（必須）

供給

## 変更の理由（必須）

市場での需給に関連した意味でのsupplyなので、「物資」でなく「供給」が適切

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。進捗がありましたらここに報告します。校正メンバーと議論が必要である場合はお手数ですが#github議論板にて確認をお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1035456728826904616/1035456728826904616

**Comment by Zousuikakka** [comment]
供給に修正。また語順を需要と供給に並び替えました。「物資」は軍事用語としても定義されており、同様にSupplyですが、供給と訳すかは議論の余地があると思ったので、こちらは今回は統一していません。
