### ISSUE TITLE
【修正提案】他国首都をマウスオーバーした時のツールチップ

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#117]
## スクリーンショット（必須）

![20221028174402_1](https://user-images.githubusercontent.com/42710893/198545850-fc2b7c44-2d74-4626-b6b0-eef864bb1181.jpg)

## 問題のツールチップ（必須）

他国の首都をマウスオーバーした時のツールチップ

## 問題の表現（必須）

"我が国に対する[STATE.GetCountry.GetAdjectiveNoFormatting] [concept_attitude]: #tooltippable #tooltip:[STATE.GetCountry.GetTooltipTag],COUNTRY_ATTITUDE_TOOLTIP [STATE.GetCountry.GetAttitudeTowards(GetPlayer.Self).GetName]#!#! (#tooltippable #tooltip:[STATE.GetCountry.GetTooltipTag],COUNTRY_ATTITUDE_SCORE_TOOLTIP [STATE.GetCountry.GetAttitudeTowards(GetPlayer.Self).CalcScore|+0]#!#!)"

## 希望する変更（必須）

"我が国に対する[STATE.GetCountry.GetAdjectiveNoFormatting]**の**[concept_attitude]: #tooltippable #tooltip:[STATE.GetCountry.GetTooltipTag],COUNTRY_ATTITUDE_TOOLTIP [STATE.GetCountry.GetAttitudeTowards(GetPlayer.Self).GetName]#!#! (#tooltippable #tooltip:[STATE.GetCountry.GetTooltipTag],COUNTRY_ATTITUDE_SCORE_TOOLTIP [STATE.GetCountry.GetAttitudeTowards(GetPlayer.Self).CalcScore|+0]#!#!)"

## 変更の理由（必須）

日本語として不自然なため。

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。進捗がありましたらここに報告します。校正メンバーと議論が必要である場合はお手数ですが#github議論板にて確認をお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1035475739673366539/1035475739673366539

**Comment by oooFUNooo** [comment]
修正が完了しました。
