### ISSUE TITLE
【修正提案】法律に対する支持・不支持の説明

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#118]
## スクリーンショット（必須）

![20221027163254_1](https://user-images.githubusercontent.com/42710893/198550520-fb169e13-795a-42aa-bdac-dccf07828567.jpg)

## 問題のあるインターフェイス（必須）

法律に対する支持・不支持の説明文

## 問題のテキスト（必須）

concept_opposition:0 "対立"
concept_oppose:0 "対立"
IG_DISAPPROVES_OF_LAW_CHANGE:1 

## 希望する変更（必須）

・IG_DISAPPROVES_OF_LAW_CHANGE:1の中にある`$concept_oppose$`が「対立」と訳されているのを「反対」に変更
・「…はこの変更を」の部分を「…はこの変更**に**」に変更

## 変更の理由（必須）

日本語として不自然なため

## ゲームバージョン（必須）

1.0.3

## DLCの有無（必須）

なし

## MODの有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。進捗がありましたらここに報告します。校正メンバーと議論が必要である場合はお手数ですが#github議論板にて確認をお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1035482667296243762/1035482667296243762

**Comment by oooFUNooo** [comment]
修正を完了しました。
最終的に、endorsementを「賛成」、oppositionを「反対」、indifferentを「無関心」と訳すことに決定しました。
