### ISSUE TITLE
【起票テスト】「海軍の侵攻」について

### ISSUE THREAD

**Issue by clamm0363** [matanki-saito/vic3jpadvmod#12]
＜ゲームシステム用語＞

## スクリーンショット（任意）
割愛

## 問題の用語（必須）

海軍の侵攻

## 英語版の表現（任意）

Naval Invasion

## 希望する変更（必須）

上陸作戦

## 変更の理由（必須）

実際のゲームメカニズムと異なっているため

## ゲームバージョン（必須）

1.0.1

## DLC有無（必須）

無し

## MOD有無（必須）

※できるだけMODのない状態で問題を確認してください。

なし

**Comment by clamm0363** [comment]
ここに、メンバーがParatranzの該当キーのリンクを貼ったり、修正の要否を書いたり、議論する感じでいけそうです

**Comment by matanki-saito** [comment]
Discordはこちら:https://discord.com/channels/1022767005662724096/1033342609453752370/1034107504524795904
