### ISSUE TITLE
【修正提案】外交画面/臣下の開放

### ISSUE THREAD

**Issue by Shiletoko** [matanki-saito/vic3jpadvmod#120]
## スクリーンショット（必須）
![2022_10_28_3](https://user-images.githubusercontent.com/116886486/198577302-fa508cef-d2e8-45aa-94c2-7225794a01b0.png)

## 問題のあるインターフェイス（必須）
臣下(subject)の開放

## 問題のテキスト
蝦夷を(subject)国として日本幕府に開放

## 希望する変更
蝦夷を(subject)国として日本幕府から開放

## 変更の理由
文章が不自然である為。

## ゲームバージョン
1.0.3

## DLCの有無
Victoria 3 Grand Editionに同梱されているもの。

## MODの有無
なし

**Comment by matanki-saito** [comment]
内部検討中です。進捗がありましたらここに報告します。校正メンバーと議論が必要である場合はお手数ですが#github議論板にて確認をお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1035516712797347872/1035516712797347872

**Comment by oooFUNooo** [comment]
修正が完了しました。
