### ISSUE TITLE
【修正提案】実績/ハプスブルクの再興

### ISSUE THREAD

**Issue by Shiletoko** [matanki-saito/vic3jpadvmod#121]
## スクリーンショット（任意）
![2022_10_28_6](https://user-images.githubusercontent.com/116886486/198585221-f2565b82-51b2-473b-bec6-ac7614a88890.png)

![2022_10_28_5](https://user-images.githubusercontent.com/116886486/198585203-779aeade-b63d-488b-84bd-9ccb07e4e283.png)

##　問題部分（タイトル・本文・選択肢）

オーストリアとしてスタートし、自身のシレジアとプロイセンを非主要国もしくはそれより低いランクに留める。
(元文)
Starting as Austria, own Silesia and Prussia must be Minor Power or Lower rank

## 問題の実績タイトル（必須）

ハプスブルクの再興

## 希望する変更（必須・修正部分のみ）
オーストリアとしてスタートしてシレジアを領有し、プロイセンを非主要国もしくはそれより低いランクにする。

## 変更の理由（必須）
翻訳ミス

## ゲームバージョン（必須）
1.0.3

## DLC有無（必須）
Victoria 3 Grand Edition に同梱されているDLC

## MOD有無（必須）
なし

**Comment by matanki-saito** [comment]
内部検討中です。進捗がありましたらここに報告します。校正メンバーと議論が必要である場合はお手数ですが#github議論板にて確認をお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1035530654936477817/1035530654936477817
