### ISSUE TITLE
【修正提案】州画面の布告のツールチップ

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#122]
## スクリーンショット（必須）

![20221028211900_1](https://user-images.githubusercontent.com/42710893/198592032-414be850-85d2-4be7-b768-00bf1597f876.jpg)

## 問題のツールチップ（必須）

州画面の布告のツールチップ

## 問題の表現（必須）

`#header $NAME$[AddTextIf(State.IsValid,'で')][AddTextIf(State.IsValid,State.GetName)]#!発布[ConcatIfNeitherEmpty('\n','$ERRORS$')]\n$EFFECT$\n\n#title コスト: #! #tooltippable #tooltip:[GetRawTextTooltipTag('$BREAKDOWN$')] #variable $COST|0$#!#!#! $AUTHORITY$\n\n#lore $DESC$#! #`

## 問題箇所の英文（任意）

`#header Issue $NAME$[AddTextIf(State.IsValid,' in ')][AddTextIf(State.IsValid,State.GetName)]#![ConcatIfNeitherEmpty('\n','$ERRORS$')]\n$EFFECT$\n\n#title Cost:#! #tooltippable #tooltip:[GetRawTextTooltipTag('$BREAKDOWN$')] #variable $COST|0$#!#!#! $AUTHORITY$\n\n#lore $DESC$#! #`

## 希望する変更（必須）

`#header $NAME$を[AddTextIf(State.IsValid,State.GetName)]#![AddTextIf(State.IsValid,'で')]発布[ConcatIfNeitherEmpty('\n','$ERRORS$')]\n$EFFECT$\n\n#title コスト: #! #tooltippable #tooltip:[GetRawTextTooltipTag('$BREAKDOWN$')] #variable $COST|0$#!#!#! $AUTHORITY$\n\n#lore $DESC$#! #`

## 変更の理由（必須）

日本語としておかしいため

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。進捗がありましたらここに報告します。校正メンバーと議論が必要である場合はお手数ですが#github議論板にて確認をお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1035538671174168610/1035538671174168610

**Comment by Zousuikakka** [comment]
[AddTextIf(State.IsValid,State.GetName)][AddTextIf(State.IsValid,'で')]#header $NAME$#!を発布[ConcatIfNeitherEmpty('
','$ERRORS$')]
$EFFECT$

#title コスト: #!$AUTHORITY$#tooltippable #tooltip [GetRawTextTooltipTag('$BREAKDOWN$')] #variable $COST|0$#!#!#!

#lore $DESC$#! 
上記で修正
