### ISSUE TITLE
【修正提案】教育自由度 Education Access

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#123]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![education](https://user-images.githubusercontent.com/50406316/198598819-fae86eeb-3cc1-42bf-9288-aa4c8b112382.png)

## 問題の用語（必須）
教育自由度

## 英語版の表現（任意）
Education Access

## 希望する変更（必須）
教育アクセス

## 変更の理由（必須）
時間とともに各POPの識字率は生活水準や諸々の補正に従ったターゲットに向けて近付いていくが、そのターゲット値にかかる補正値のこと。
原文と訳語が異なっている。

## ゲームバージョン（必須）
1.0.3

## DLC有無（必須）
無し

## MOD有無（必須）
なし

**Comment by matanki-saito** [comment]
内部検討中です。進捗がありましたらここに報告します。校正メンバーと議論が必要である場合はお手数ですが#github議論板にて確認をお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1035540741163847681/1035540741163847681

**Comment by N-der** [comment]
別の訳語として「教育機会」を挙げます。
若干意味合いが異なるかもしれませが、「教育機会」のほうが聞き馴染みがあり分かりやすいと考えるためです。

**Comment by oooFUNooo** [comment]
修正が完了しました。
