### ISSUE TITLE
【表記ゆれ】護衛/輸送船団　Convoys

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#124]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![image](https://user-images.githubusercontent.com/37979626/198627653-e9af1aa3-ff0b-4f1a-a9ad-f7eeb1dc8c23.png)
![image](https://user-images.githubusercontent.com/37979626/198627977-5d85e3c6-06f9-4b89-a8d8-fbfa6ad1b43d.png)

## 問題の用語（必須）

護衛

## 英語版の表現（任意）

Convoys

## 希望する変更（必須）

輸送船団

## 変更の理由（必須）

ここだけ表記ゆれを起こしているため

## ゲームバージョン（必須）

1.0.1

## DLC有無（必須）

無し

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。進捗がありましたらここに報告します。校正メンバーと議論が必要である場合はお手数ですが#github議論板にて確認をお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1035553247227822131/1035553247227822131

**Comment by matanki-saito** [comment]
修正しました
