### ISSUE TITLE
【修正提案】地主

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#125]
＜ゲームシステム用語＞

## スクリーンショット（任意）

![20221028120241_1](https://user-images.githubusercontent.com/43299334/198631355-f60ea1a7-a463-48fd-b47a-e3627dd271c1.jpg)

## 問題の用語（必須）

地主

## 英語版の表現（任意）

Landowners

## 希望する変更（必須）

地主貴族

## 変更の理由（必須）

画像のように、単なる土地所有者というよりは貴族的な色彩が強いため。
ユンカーなどの地主貴族（土地貴族）が含まれる。

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。進捗がありましたらここに報告します。校正メンバーと議論が必要である場合はお手数ですが#github議論板にて確認をお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1035557674626060448/1035557674626060448

**Comment by starjard** [comment]
ゲーム中のインターフェイスだと貴族、聖職者、将校が地主に加入すると出ていて貴族に限定されないので、包括的な表現として現状の地主のままのほうがいいと思います。
