### ISSUE TITLE
【未訳】ジャーナル内の将軍・提督の必要な決断がgeneral,admiralになっている箇所

### ISSUE THREAD

**Issue by 30denarius** [matanki-saito/vic3jpadvmod#126]
## スクリーンショット（必須）
※画像はドラッグ＆ドロップで貼り付けられます。
※できるだけ問題箇所の前後を含めて貼ってください。
![20221028231242_1](https://user-images.githubusercontent.com/105610712/198636735-e2e55cd6-61d8-47e9-93a4-d7cbc9b0705b.jpg)

## 問題のあるインターフェイス（必須）

ジャーナル内の判断「ニジェール川遠征」

## 問題のテキスト（必須）

・generalの役割を持っています
・admiralの役割を持っています

## 希望する変更（必須）

・将軍の役割を持っています
・提督の役割を持っています

## 変更の理由（必須）

訳されていないので

## ゲームバージョン（必須）

1.0.2

## DLCの有無（必須）

なし

## MODの有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。進捗がありましたらここに報告します。校正メンバーと議論が必要である場合はお手数ですが#github議論板にて確認をお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1035558062636937256/1035558062636937256

**Comment by clamm0363** [comment]
ほかの言語でも翻訳されておらず、ローカリゼーションキーにも該当する箇所が見当たらないため、ゲームのバグであると思われます。今のところ、これを修正する簡単な方法はございません。
パラドに報告を上げることとして、修正は保留させて頂きます。

**Comment by matanki-saito** [comment]
報告しました。
https://forum.paradoxplaza.com/forum/threads/victoria-iii-localization-bug.1558598/

**Comment by matanki-saito** [comment]
報告したためClose致します
