### ISSUE TITLE
カタカナになっている漢字圏の人名（非ランダム人名）

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#128]
## 問題の固有名詞と希望する変更（必須）

ダオグアング：道光
イズフ：奕詝
アイシン・ギオロ：愛新覚羅
ジズヘン：自珍
ゴング：龔
シャンリン：長齢
ユアン：元
ルアン：院
キイング：耆英
レクシング：楽行
ユピアン：育楩

バンボ：堂輔
ビュングク：炳国
ビュンハク：炳学
ビュンシ：炳始
チョイウン：最応
ドンイン：敦仁
ドゥセオン：淳斗
ハユン：昰応
ホンジプ：弘集
ホングン：興根
ギュホ：奎鎬
インヨン：寅永
ジョスン：祖淳
ジョンヤン：重陽
ジャグン：左根
キョンジェ：景在
サンワン：相璜
ソンモク：淳穆
ソンタク：舜沢
ワンヨン：元容
ヨンソン：英淳
ユワン：有源
ビョン：昪
チョク：坧
ゲウン：昑
ミョウンボク：命福
サン：祘
ジャヨン：茲映
ジュンソン：曽順
ヒョウユ：孝裕
オクジョン：玉貞
ウォン：元
ソン：宋
ソク：石
ソン：成
シン：申
パーク：朴
ナ：羅
ムン：文
コ：高
ガン：姜
オク：檍
ナングン：南宮
ボンハク：奉劾
サンオク：尚沃
イム：林
ジョンヒ：正喜

## 変更の理由（必須）
カタカナ表記は一般的な表記からかけ離れている。

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。進捗がありましたらここに報告します。校正メンバーと議論が必要である場合はお手数ですが#github議論板にて確認をお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1035634057989595236/1035634057989595236

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
