### ISSUE TITLE
【表記ゆれ】義務と恩義（Obligation）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#133]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![Obligation](https://user-images.githubusercontent.com/42687608/198814136-b23fed74-3ddb-402c-925f-5e99eb7507a1.jpg)

## 問題の用語（必須）
義務/恩義

## 英語版の表現（任意）
Obligation

## 希望する変更（必須）
借り

## 変更の理由（必須）
場所によって「義務」と「恩義」で表記ゆれを起こしている。
ゲーム上の意味は外交上の貸し借り。CK3のフックに相当する。
訳は「恩義」でも構わないが、個人的には意味がわかりやすい「借り」に変更したい。

## ゲームバージョン（必須）
1.0.3

## DLC有無（必須）
- Victoria II Remastered Soundtrack
- American Buildings Pack

## MOD有無（必須）
なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
修正が完了しました。
