### ISSUE TITLE
【修正提案】揺さぶり（Sway）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#134]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![Sway](https://user-images.githubusercontent.com/42687608/198814453-1f6c51b5-1692-4b1e-aadc-2bf9d37cc258.jpg)

## 問題の用語（必須）
揺さぶり

## 英語版の表現（任意）
Sway

## 希望する変更（必須）
懐柔

## 変更の理由（必須）
直訳としては間違っていないが、CK2/CK3では同じ単語を「懐柔」と訳しているため共通にしたい。
また、用語が別の場面で引用される場合、熟語の方がなにかと扱いやすい。

## ゲームバージョン（必須）
1.0.3

## DLC有無（必須）
- Victoria II Remastered Soundtrack
- American Buildings Pack

## MOD有無（必須）
なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
修正が完了しました。
