### ISSUE TITLE
【修正提案】将軍（Shogun/General）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#135]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![Shogun](https://user-images.githubusercontent.com/42687608/198814645-19e57a85-2eda-4b23-85ee-82a424844a89.jpg)

## 問題の用語（必須）
将軍

## 英語版の表現（任意）
Shogun/General

## 希望する変更（必須）
征夷大将軍/将軍

## 変更の理由（必須）
用語が重複しており、日本プレイではShogunとGeneralの見分けがつかないため。
Shogunを「征夷大将軍」、Generalを「将軍」と訳し分けることで区別できるようにする。

## ゲームバージョン（必須）
1.0.3

## DLC有無（必須）
- Victoria II Remastered Soundtrack
- American Buildings Pack

## MOD有無（必須）
なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
修正を完了しました。
