### ISSUE TITLE
【修正提案】周縁集団（Marginalized）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#136]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![Marginalized](https://user-images.githubusercontent.com/42687608/198814821-d95bdadc-4aee-400b-8ea1-cfcd262eb962.jpg)

## 問題の用語（必須）
周縁集団

## 英語版の表現（任意）
Marginalized

## 希望する変更（必須）
非主流派

## 変更の理由（必須）
誤訳のため。
Marginalizedは形容詞として名詞を修飾するだけでなく、補語として単独でも使われるので訳語の選択には注意が必要。

## ゲームバージョン（必須）
1.0.3

## DLC有無（必須）
- Victoria II Remastered Soundtrack
- American Buildings Pack

## MOD有無（必須）
なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
修正が完了しました。
