### ISSUE TITLE
【修正提案】法定相続人（Heir Apparent）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#137]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![Shogun](https://user-images.githubusercontent.com/42687608/198815067-7836759a-9826-4e6c-9d00-97135618eec1.jpg)

## 問題の用語（必須）
法定相続人

## 英語版の表現（任意）
Heir Apparent

## 希望する変更（必須）
後継者

## 変更の理由（必須）
誤訳のため。

## ゲームバージョン（必須）
1.0.3

## DLC有無（必須）
- Victoria II Remastered Soundtrack
- American Buildings Pack

## MOD有無（必須）
なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
修正が完了しました。「後継者」とすることに決まりました。
