### ISSUE TITLE
【修正提案】政府体制支持者（Loyalist）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#138]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![Loyalist](https://user-images.githubusercontent.com/42687608/198815222-cccb4f34-e4ad-493f-b45d-0b11ce2ef181.jpg)

## 問題の用語（必須）
政府体制支持者

## 英語版の表現（任意）
Loyalist

## 希望する変更（必須）
体制派

## 変更の理由（必須）
対になる急進派（Radical）と対になっておらず、一部の画面では文字あふれを起こしているため。

## ゲームバージョン（必須）
1.0.3

## DLC有無（必須）
- Victoria II Remastered Soundtrack
- American Buildings Pack

## MOD有無（必須）
なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
修正が完了しました。
