### ISSUE TITLE
【修正提案】動揺度（Turmoil）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#139]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![Turmoil](https://user-images.githubusercontent.com/42687608/198815528-12fc3921-52ed-4e5d-b8a2-3a45f0f80cd7.jpg)

## 問題の用語（必須）
動揺度

## 英語版の表現（任意）
Turmoil

## 希望する変更（必須）
騒乱度/混乱度

## 変更の理由（必須）
ゲーム上の意味は、州ごとの急進派の割合を示すパラメーター。
値がhighやlowで言及されるので「度」をつけることには賛成。
動揺は人間の状態を表す言葉なので、州の状態を表す言葉に変更したい。

## ゲームバージョン（必須）
1.0.3

## DLC有無（必須）
- Victoria II Remastered Soundtrack
- American Buildings Pack

## MOD有無（必須）
なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by kecy3** [comment]
マインスイメージで不穏度なんかもありかなぁとは思いましたが、ゲーム的には内乱なんかが起きる目安なのを考えると「混乱度」よりも「騒乱度」のほうがわかりやすいかも、と個人的には思いました。急進派との結びつきもよさそうな言葉ですし！

**Comment by clamm0363** [comment]
こちら、議論の結果「社会不安」となりました。
また、あわせてCultural Turmoilの訳語も検討し、「民族不安」と修正しました。その際、Cultural TurmoilからはTurmoilのツールチップを経由しないとCultural Turmoilのツールチップに飛べない不都合があったため、直接Cultural Turmoilのツールチップに飛べるように修正を施しました。

クローズします。
