### ISSUE TITLE
【修正提案】利益（Interest）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#140]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![Interest](https://user-images.githubusercontent.com/42687608/198815756-2302fcd8-2d91-455e-855a-509f93a601be.jpg)

## 問題の用語（必須）
利益

## 英語版の表現（任意）
Interest（キーはconcept_budget_interest）

## 希望する変更（必須）
利子

## 変更の理由（必須）
誤訳。
支出欄の細目であり、まったく逆の意味になっている。

## ゲームバージョン（必須）
1.0.3

## DLC有無（必須）
- Victoria II Remastered Soundtrack
- American Buildings Pack

## MOD有無（必須）
なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
修正しました
interest: 利子、interest rate: 利子率となるように修正しています。
