### ISSUE TITLE
【修正提案】サプライネットワーク（Supply Network）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#141]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![Supply Network](https://user-images.githubusercontent.com/42687608/198816016-0de323c4-dfac-4484-98e2-672b1c30700b.jpg)

## 問題の用語（必須）
サプライネットワーク

## 英語版の表現（任意）
Supply Network

## 希望する変更（必須）
供給ネットワーク

## 変更の理由（必須）
カタカナではわかりにくいため。
「供給網」はSupply Chainの定訳らしいので「供給ネットワーク」とした。
軍事にしか使われない用語なら「兵站〜」もあり。

## ゲームバージョン（必須）
1.0.3

## DLC有無（必須）
- Victoria II Remastered Soundtrack
- American Buildings Pack

## MOD有無（必須）
なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
「補給網」に決定し、修正を完了しました。
