### ISSUE TITLE
【誤訳訂正】各商品画面＞適用タブ中の「製法は（国名）で（商品名）を使用しています」

### ISSUE THREAD

**Issue by WoodlandsGitHub** [matanki-saito/vic3jpadvmod#143]
## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/29177147/198815824-02044414-48be-4be7-9518-f4b4b6d7655e.png)

## 問題のあるインターフェイス（必須）

各商品＞適用タブ＞使用者の項目

## 問題のテキスト（必須）

製法は（国名）で（商品名）を使用しています

## 希望する変更（必須）

（国名）で（商品名）を使用中の製法
ないし
（国名）で（商品名）を使用している製法

## 変更の理由（必須）

現訳が誤訳のため。
元訳では、分詞構文で文中の「製法」を後置修飾する形になっているので。

※参考（元訳）：
 ACTIVE_PRODUCTION_METHODS_CONSUMING:1 "[Concept('concept_production_method', '$concept_production_methods$')] using [Goods.GetTextIcon][Nbsp][Goods.GetName] in [GetPlayer.GetName]"

## ゲームバージョン（必須）

1.0.3

## DLCの有無（必須）

なし

## MODの有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
#142同様に、こちらもご提案通り修正しました。「～～を使用中の製法」としています。起票ありがとうございました。

**Comment by oooFUNooo** [comment]
代理でクローズします。「（国名）で（商品名）を使用中の製法」という表現に修正しました。
