### ISSUE TITLE
【修正提案】技術ツリーの生産量（Production）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#144]
## スクリーンショット（必須）
![Production](https://user-images.githubusercontent.com/42687608/198817132-47f9c3f6-a270-4b22-8457-fcb973b9a2bc.jpg)

## 問題のあるインターフェイス（必須）
技術ツリーのカテゴリータブ

## 問題のテキスト（必須）
生産量

## 希望する変更（必須）
生産

## 変更の理由（必須）
誤訳（原文はProduction）
このインターフェイス以外のProductionを誤って修正しないように注意。
キーはproduction

## ゲームバージョン（必須）
1.0.3

## DLC有無（必須）
- Victoria II Remastered Soundtrack
- American Buildings Pack

## MOD有無（必須）
なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
修正を完了しました。
