### ISSUE TITLE
【修正提案】下層民・中堅層・上流層（Lower Strata, Middle Strata, Upper Strata）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#145]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![POP](https://user-images.githubusercontent.com/42687608/198817346-4e6d2ded-7d78-4fd9-ad56-190388786bf1.jpg)

## 問題の用語（必須）
下層民/中堅層/上流層

## 英語版の表現（任意）
Lower Strata / Middle Strata / Upper Strata

## 希望する変更（必須）
下流階級、中流階級、上流階級

## 変更の理由（必須）
3つの訳語が対になっていないため。
strataは「社会階層」を表す言葉だが、一般的にはclass（階級）が用いられる。
https://ja.wikipedia.org/wiki/%E7%A4%BE%E4%BC%9A%E9%9A%8E%E7%B4%9A

## ゲームバージョン（必須）
1.0.3

## DLC有無（必須）
- Victoria II Remastered Soundtrack
- American Buildings Pack

## MOD有無（必須）
なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
修正を完了しました。
