### ISSUE TITLE
【修正提案】店主

### ISSUE THREAD

**Issue by clamm0363** [matanki-saito/vic3jpadvmod#146]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![image](https://user-images.githubusercontent.com/29382778/198817505-8fb2c438-dc48-4082-a9c2-fc03ce613b50.png)

## 問題の用語（必須）

店主

## 英語版の表現（任意）

Shopkeepers

## 希望する変更（必須）

商店主

## 変更の理由（必須）

好みです。

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

Grand Edition

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
「商店主」に修正しました。

クローズします。
