### ISSUE TITLE
【修正提案】軍人

### ISSUE THREAD

**Issue by clamm0363** [matanki-saito/vic3jpadvmod#147]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![image](https://user-images.githubusercontent.com/29382778/198817606-acb4cdf3-fbf1-471f-9503-ecee33070b62.png)

## 問題の用語（必須）

軍人

## 英語版の表現（任意）

Servicemen

## 希望する変更（必須）

兵士

## 変更の理由（必須）

軍人だと高位の士官・将校を含む概念であるため

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

Grand Edition

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
「兵士」と修正しました。

クローズします。
