### ISSUE TITLE
【修正提案】ゲームルール画面説明文の文体

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#148]
## スクリーンショット（必須）

![20221029142611_1](https://user-images.githubusercontent.com/42710893/198817531-c7727529-460c-41de-af77-1d9fd6d2005a.jpg)

## 問題のあるインターフェイス（必須）

ゲームルール画面

## 問題のテキスト（必須）

形成可能な国、解放可能な国の説明文

## 希望する変更（必須）

ですます調に

## 変更の理由（必須）

この2つのルールの説明だけ、ですます調になっていないので統一するべき。

## ゲームバージョン（必須）

1.0.3

## DLCの有無（必須）

なし

## MODの有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
setting_all_formable_nations_desc
```Allow implausible and fantasy-esque nations to be formed```
非現実的なファンタジー風国家の形成を可能にします

**Comment by matanki-saito** [comment]
setting_all_releasable_nations_desc
```Allow implausible and fantasy-esque nations to be released```
非現実的なファンタジー風国家の解放を可能にします

**Comment by inarizushi0309** [comment]
上記案で修正しました。起票ありがとうございました。
