### ISSUE TITLE
【修正提案】官僚

### ISSUE THREAD

**Issue by clamm0363** [matanki-saito/vic3jpadvmod#149]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![image](https://user-images.githubusercontent.com/29382778/198817650-c246a470-2777-45f7-8652-c8a86c2b2c73.png)

## 問題の用語（必須）

官僚

## 英語版の表現（任意）

Bureaucrats

## 希望する変更（必須）

公務員

## 変更の理由（必須）

官僚は主に中央省庁の公務員を指すが、今作では公共セクターで働く事務員のことを言っているため

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

無し

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
「公務員」と修正しました。
