### ISSUE TITLE
【修正提案】併合された州・併合されていない州（Incorporated State, Unincorporated State）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#150]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![Incorporated](https://user-images.githubusercontent.com/42687608/198817798-2469ab14-ffa2-4e27-bf76-6e51cd6c03b5.jpg)

## 問題の用語（必須）
併合された州 / 併合されていない州

## 英語版の表現（任意）
Incorporated State / Unincorporated State

## 希望する変更（必須）
編入州 / 未編入州

## 変更の理由（必須）
「併合」は国を併合するAnnexの訳語としても使われており、重複している。
また、「併合済」（Incorporated）という表記ゆれもある。
訳語が無駄に長いので、短くする方針で「併合」とは異なる訳をあてるべき。

## ゲームバージョン（必須）
1.0.3

## DLC有無（必須）
- Victoria II Remastered Soundtrack
- American Buildings Pack

## MOD有無（必須）
なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
修正を完了しました。
