### ISSUE TITLE
【修正提案】資源見込み（Resource Potential）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#153]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![Resource Potential](https://user-images.githubusercontent.com/42687608/198818122-8eb32da0-0f5b-4a3c-aee3-71254f6a63c4.jpg)

## 問題の用語（必須）
資源見込み

## 英語版の表現（任意）
Resource Potential

## 希望する変更（必須）
潜在的資源

## 変更の理由（必須）
用語の意味がわかりにくいため。
ゲーム中の使われ方がまだよく分かっていないので、変更には注意が必要。

## ゲームバージョン（必須）
1.0.3

## DLC有無（必須）
- Victoria II Remastered Soundtrack
- American Buildings Pack

## MOD有無（必須）
なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
修正を完了しました。
