### ISSUE TITLE
【修正提案】判断（Decision）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#154]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![Decision](https://user-images.githubusercontent.com/42687608/198818350-a6f9c4c2-1522-4411-8917-e7b54da2316f.jpg)

## 問題の用語（必須）
判断

## 英語版の表現（任意）
Decision

## 希望する変更（必須）
決断 / ディシジョン

## 変更の理由（必須）
従来のParadox作品の翻訳とかけ離れているため。
「決断」と「ディシジョン」のどちらを採用するかは議論が必要。

## ゲームバージョン（必須）
1.0.3

## DLC有無（必須）
- Victoria II Remastered Soundtrack
- American Buildings Pack

## MOD有無（必須）
なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
「ディシジョン」とすることに決定し、修正が完了しました。
