### ISSUE TITLE
【修正提案】国威（Prestige）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#155]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![Prestige](https://user-images.githubusercontent.com/42687608/198818855-40e7f83f-68b3-49e0-823e-c6b8b6368dd6.jpg)

## 問題の用語（必須）
国威

## 英語版の表現（任意）
Prestige

## 希望する変更（必須）
威信

## 変更の理由（必須）
他のParadox作品の翻訳に揃えるため。

## ゲームバージョン（必須）
1.0.3

## DLC有無（必須）
- Victoria II Remastered Soundtrack
- American Buildings Pack

## MOD有無（必須）
なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
「威信」に修正することで確定し、修正が完了しました。
