### ISSUE TITLE
【修正提案】母艦　Carriers

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#156]
## スクリーンショット（任意）
![image](https://user-images.githubusercontent.com/37979626/198819081-a5a0a461-b261-4ded-b98e-c8d470af15f3.png)

## 問題の固有名詞（必須）

母艦

## 希望する変更（必須）

空母

## 変更の理由（必須）

誤訳

## ゲームバージョン（必須）

1.0.1

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。
