### ISSUE TITLE
【修正提案】お金（Money）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#157]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![Money](https://user-images.githubusercontent.com/42687608/198819182-04cf4ccf-795b-4008-b73d-828aee5d0774.jpg)

## 問題の用語（必須）
お金

## 英語版の表現（任意）
Money

## 希望する変更（必須）
金銭 / 資金

## 変更の理由（必須）
脱力感を感じるため。
十分な議論の上で代案を決めるべき。
「（Money）は世界を動かしています。」との文章があり、「資金」だと意味が通らなくなる。

## ゲームバージョン（必須）
1.0.3

## DLC有無（必須）
- Victoria II Remastered Soundtrack
- American Buildings Pack

## MOD有無（必須）
なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
「資金」に決定し、修正を完了しました。文脈上おかしい部分はそのまま「お金」を残してあります。
