### ISSUE TITLE
司令官ランク、および将軍/提督

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#159]
＜ゲームシステム用語＞

## スクリーンショット（任意）

![20221029160839_1](https://user-images.githubusercontent.com/43299334/198819256-8de5a95f-1d45-4aa7-ad12-2df6128aefa8.jpg)

## 問題の用語（必須）

将軍/提督
司令官ランク

## 英語版の表現（任意）

General/Admiral
Commander Rank
全体の階級は以下の通り（低い順）
陸：Brigadier General/Major General/Lieutenant General/General/Field Marshal
海：Commodore/Rear Admiral/Vice Admiral/Admiral/Grand Admiral

## 希望する変更（必須）

陸軍大将/海軍大将
司令官階級

## 変更の理由（必須）

司令官の陸海軍の総称としての将軍、提督と訳が被っているため。
もともとの訳に合わせてそれぞれ大将とした。
また明らかに軍内部の階級をさしているため、司令官ランクを司令官階級とした。

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
案通り、陸軍・海軍大将/司令官階級で修正しました
