### ISSUE TITLE
【修正提案】軍艦の名称表記

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#160]
## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/37979626/198820109-a1f089a6-02fc-4def-b996-856c10b7d149.png)

## 問題のあるインターフェイス（必須）

軍事ウィンドウの海軍タブ
海軍基地ウィンドウの情報タブ

## 問題のテキスト（必須）

[艦名] [艦種]

## 希望する変更（必須）

[艦種] [艦名]

## 変更の理由（必須）

軍艦の名称については艦種・艦名の順で表記するのが一般的
間の空白は一応残すが、イベントなどで引用されるようであれば改行防止のため、消すことも検討すべきか

## ゲームバージョン（必須）

1.0.2

## DLCの有無（必須）

なし

## MODの有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
COMBAT_UNIT_FLOTILLA_FULL_NAME修正
