### ISSUE TITLE
各ユニット（陸軍の最小単位）における動員/解体表記

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#161]
＜ゲームシステム用語＞

## スクリーンショット（任意）

![20221029145711_1](https://user-images.githubusercontent.com/43299334/198820195-acb64d3b-b46c-4281-9789-32547befc202.jpg)

## 問題の用語（必須）

動員/解体

## 英語版の表現（任意）

Mobilized/Demobilized

## 希望する変更（必須）

動員済/未動員

## 変更の理由（必須）

そのユニットが動員済であるかどうかの表記。
特に「解体」は部隊の消去コマンドと誤認させるため良くない。
現在の状態を表示するものであり、「動員中」ではまさに動員が進んでいるのか、動員済みの状態なのかが判別できないため、上記としている。

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
動員済/未動員で修正
