### ISSUE TITLE
【バグ修正】○○年○○月月○○日

### ISSUE THREAD

**Issue by clamm0363** [matanki-saito/vic3jpadvmod#162]
## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/29382778/198820450-b9045176-28e8-4df5-9103-5691a3b35dc8.png)

## 問題のあるインターフェイス（必須）

グラフ下部に表示される年月日

## 問題のテキスト（必須）

○○年○○月月○○日

## 希望する変更（必須）

○○年○○月○○日

## 変更の理由（必須）

「月」が二つ表示されている

## ゲームバージョン（必須）

1.0.3

## DLCの有無（必須）

なし

## MODの有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
別issueにて解決されました

クローズします。
