### ISSUE TITLE
【修正提案】爆発物（Explosives）

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#163]
＜ゲームシステム用語＞

## スクリーンショット（任意）

![20221029164242_1](https://user-images.githubusercontent.com/42710893/198820553-c4ae16cb-0f73-425f-8b92-7ddce334f0b1.jpg)

## 問題の用語（必須）

爆発物

## 英語版の表現（任意）

Explosives

## 希望する変更（必須）

爆薬

## 変更の理由（必須）

爆発物でも間違いではありませんが、個人的に爆薬のほうがしっくり来ます。

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

無し

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通り修正しました。起票ありがとうございました。
修正エントリ
dynamite_production_modifier
production_tech_events.102.d
explosives
dynamite_desc
modifier_building_output_explosives_add
modifier_building_output_explosives_add_desc
modifier_building_input_explosives_add
modifier_building_input_explosives_add_desc
pmg_explosives_building_chemical_plants
pmg_explosives_building_coal_mine
pmg_explosives_building_iron_mine
pmg_explosives_building_lead_mine
pmg_explosives_building_sulfur_mine
pmg_explosives_building_gold_mine
