### ISSUE TITLE
【修正提案】建設のツールチップ

### ISSUE THREAD

**Issue by discordine** [matanki-saito/vic3jpadvmod#164]
## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/46787431/198820741-7cb98c6a-1120-484f-8fdc-b030f6fb42ea.png)

## 問題のツールチップ（必須）

建設

## 問題の表現（必須）

#header [Country.GetName][AddLocalizationIf(Country.IsConstructionPaused, '$CONSTRUCTION_IS_PAUSED$')]の[concept_construction]#!
$TOOLTIP_DELIMITER$
[Country.GetName]#v #tooltippable #tooltip:[Country.GetTooltipTag],CONSTRUCTION_SPEED_USED_TOOLTIP [GetPlayer.CalcUsedConstruction|2]を使用しています#!#!#!毎週[concept_construction]、#v #tooltippable #tooltip:[Country.GetTooltipTag],CONSTRUCTION_SPEED_BASE_TOOLTIP [Country.CalcBaseConstructionSpeed|2]#!#!#!毎週$concept_construction$を生産します。

#v #tooltippable #tooltip:[Country.GetTooltipTag],CONSTRUCTION_QUEUE_ACTIVE_PROJECTS [Country.GetNumActiveConstructionQueueElements]#!#!#! [concept_under_construction]と#v #tooltippable #tooltip:[Country.GetTooltipTag],CONSTRUCTION_QUEUE_INACTIVE_PROJECTS [Country.GetNumInactiveConstructionQueueElements]#!#!#!追加プロジェクトが[concept_construction_queue]に入っています

## 問題箇所の英文（任意）

#header [concept_construction]#! in [Country.GetName][AddLocalizationIf(Country.IsConstructionPaused, '$CONSTRUCTION_IS_PAUSED$')]
$TOOLTIP_DELIMITER$
[Country.GetName] is using #v #tooltippable #tooltip:[Country.GetTooltipTag],CONSTRUCTION_SPEED_USED_TOOLTIP [GetPlayer.CalcUsedConstruction|2]#!#!#! [concept_construction] each week and produces a total of #v #tooltippable #tooltip:[Country.GetTooltipTag],CONSTRUCTION_SPEED_BASE_TOOLTIP [Country.CalcBaseConstructionSpeed|2]#!#!#! $concept_construction$ each week.

There are #v #tooltippable #tooltip:[Country.GetTooltipTag],CONSTRUCTION_QUEUE_ACTIVE_PROJECTS [Country.GetNumActiveConstructionQueueElements]#!#!#! project(s) [concept_under_construction] and #v #tooltippable #tooltip:[Country.GetTooltipTag],CONSTRUCTION_QUEUE_INACTIVE_PROJECTS [Country.GetNumInactiveConstructionQueueElements]#!#!#! additional projects queued in the [concept_construction_queue]

## 希望する変更（必須）

#header [Country.GetName][AddLocalizationIf(Country.IsConstructionPaused, '$CONSTRUCTION_IS_PAUSED$')]における[concept_construction]#!
$TOOLTIP_DELIMITER$
[Country.GetName]は #v #tooltippable #tooltip:[Country.GetTooltipTag],CONSTRUCTION_SPEED_USED_TOOLTIP [GetPlayer.CalcUsedConstruction|2] 使用しています。毎週#!#!#!#v #tooltippable #tooltip:[Country.GetTooltipTag],CONSTRUCTION_SPEED_BASE_TOOLTIP [Country.CalcBaseConstructionSpeed|2]#!#!#![concept_construction] を生産します。

#v #tooltippable #tooltip:[Country.GetTooltipTag],CONSTRUCTION_QUEUE_ACTIVE_PROJECTS [Country.GetNumActiveConstructionQueueElements]#!#!#! 件の事業が[concept_under_construction]、#v #tooltippable #tooltip:[Country.GetTooltipTag],CONSTRUCTION_QUEUE_INACTIVE_PROJECTS [Country.GetNumInactiveConstructionQueueElements]#!#!#! 件の事業が[concept_construction_queue]に入っています

表示例（願望）：
パラグアイにおける建設
ーーーーーーーーーーー
パラグアイは 0 使用しています。毎週 5 を生産します。

1 件の事業が建設中、5 件の事業が建設キューに入っています。

## 変更の理由（必須）

違和感

## ゲームバージョン（必須）

1.0.1

## DLC有無（必須）

なし

## MOD有無（必須）

※できるだけMODのない状態で問題を確認してください。

（例）なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。
