### ISSUE TITLE
【修正提案】○○での施設

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#165]
## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/37979626/198820988-e5843c79-be43-4dfa-8957-d5eeac0c4079.png)

## 問題のあるインターフェイス（必須）

施設ウィンドウ

## 問題のテキスト（必須）

[地名]での施設

## 希望する変更（必須）

[地名]の施設

## 変更の理由（必須）

わざわざ「での」にする必要はない（そもそも日本語表現的に微妙）

## ゲームバージョン（必須）

1.0.2

## DLCの有無（必須）

なし

## MODの有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通りBUILDING_DETAILS_LINE_TWO修正しました
