### ISSUE TITLE
【固有名詞】形容詞形がおかしい

### ISSUE THREAD

**Issue by discordine** [matanki-saito/vic3jpadvmod#166]
## スクリーンショット（任意）
※画像はドラッグ＆ドロップで貼り付けられます。
※できるだけ問題箇所の前後を含めて貼ってください。

![image](https://user-images.githubusercontent.com/46787431/198821261-9611302b-6dce-4e34-8b8a-4b5e0c508035.png)

## 問題の固有名詞

グラン・パラ

## 希望する変更（必須）

グラン・パラの

## 変更の理由（必須）

「～人」になっているところが（おそらく）いくつかある。

## ゲームバージョン（必須）

1.0.1

## DLC有無（必須）

なし

## MOD有無（必須）

※できるだけMODのない状態で問題を確認してください。

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
アフガン→アフガニスタン
新アンゴラ→アンゴラ・ジャンガ
アイヌ→アイヌモシリ
アルテーノ→ロスアルトス
アラブ→アラビア
ブラックフット→ニイトシタピ
ボスニア→ボスニア・ヘルツェゴビナ
ブルトン→ブルターニュ
連合国→アメリカ連合国
モルモン→デザレット
連邦→イギリス連邦
マグナ・マンチェスター→グレーター・マンチェスター
スーダン・マフディー国→マフディー国
ナイル川流域自由国→ナイル川流域
サウジ→サウジアラビア
スカンジナビア→カルマル同盟
ウェールズ・パタゴニア→ア・ウラドヴァ
ハザーラ→ハザーラジャート
クリー・アシニボイン→鉄の連合
シャンマル→ジャバル・シャンマル
クルド→クルディスタン
メクレンブルク→メクレンブルク＝シュトレーリッツ
ムガル→ヒンドゥスターン
北コーカサス→山岳共和国
ニューサウスウェールズ→ニュー・サウス・ウェールズ
ナヴァホ→ナヴァホランド
ピエモンテ→サルデーニャ＝ピエモンテ
シダマ→シダモ
ドイツ→南ドイツ
シチリア→両シチリア
太平→太平天国
チュニジア→チュニス
ヤオ→ウヤオ
グリカ→グリカランド
西インド→西インド諸島

**Comment by clamm0363** [comment]
別issueですでに修正済みのものを除き、上記の形容詞形を修正しました。

クローズします。
