### ISSUE TITLE
【修正提案】テキストアイコンの直後の半角スペースで改行される

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#167]

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。
