### ISSUE TITLE
【修正提案】テキストアイコンの直後の半角スペースで改行される

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#168]
## スクリーンショット（必須）
![icon](https://user-images.githubusercontent.com/42687608/198821816-73d5f5d5-fb6f-4721-b122-21977aab6dbf.png)

## 問題のあるインターフェイス（必須）
国名、利益団体名などにはデフォルトでアイコンがつき、その直後に半角スペースが挿入されるため、そこで意図しない改行が発生している。

## 問題のテキスト（必須）
スクリーンショットを参照。

## 希望する変更（必須）
cutomized_tooltips_l_japanese.ymlで半角スペースを定義していることを特定したので、これをノンブレークスペースに置き換える。

## 変更の理由（必須）
半角スペースで意図せぬ改行が発生するため。

## ゲームバージョン（必須）
1.0.3

## DLC有無（必須）
- Victoria II Remastered Soundtrack
- American Buildings Pack

## MOD有無（必須）
なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
完了しました。
