### ISSUE TITLE
【修正】の研究に必要

### ISSUE THREAD

**Issue by discordine** [matanki-saito/vic3jpadvmod#170]
## スクリーンショット（必須）

![image](https://user-images.githubusercontent.com/46787431/198822598-35bd33bd-47d7-474a-a0bc-227f3c6c8b77.png)

## 問題のツールチップ（必須）

研究残り時間

## 問題の表現（必須）

(時間)の研究に必要

## 希望する変更（必須）

(時間)研究に必要

## 変更の理由（必須）

「の」はいらない

## ゲームバージョン（必須）

（例）1.0.1

## DLC有無（必須）

（例）なし

## MOD有無（必須）

※できるだけMODのない状態で問題を確認してください。

（例）なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
修正が完了しました。「研究に◯ヶ月必要」という表現になりました。
