### ISSUE TITLE
【修正提案】残高　Balance

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#172]
## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/37979626/198822880-06d20c1c-d1bc-4ab7-be5c-05520b3b4195.png)
![image](https://user-images.githubusercontent.com/37979626/198823062-c539ad11-7e0e-4238-8375-8c33682a1336.png)

## 問題のあるインターフェイス（必須）

予算ウィンドウ
市場ウィンドウ

## 問題のテキスト（必須）

残高
コンセプトでは「バランス」

## 希望する変更（必須）

収支

## 変更の理由（必須）

両方ともに誤訳

## ゲームバージョン（必須）

1.0.2

## DLCの有無（必須）

なし

## MODの有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
「収支」として修正しました。関連する部分も修正してあります。

クローズします。
