### ISSUE TITLE
【修正提案】一部のインターフェイスで日付の「月」が重複している

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#173]
## スクリーンショット（必須）
![date](https://user-images.githubusercontent.com/42687608/198824053-6c5124fa-dc84-4f08-b073-1612b4fef930.jpg)

## 問題のあるインターフェイス（必須）
グラフ下部の日付表示ほか多数。

## 問題のテキスト（必須）
◯◯年◯月月◯日

## 希望する変更（必須）
◯◯年◯月◯日

## 変更の理由（必須）
明白な誤り。

## ゲームバージョン（必須）
1.0.3

## DLC有無（必須）
- Victoria II Remastered Soundtrack
- American Buildings Pack

## MOD有無（必須）
なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
修正済みです
