### ISSUE TITLE
【修正提案】ビッキーペディア（Vickypedia）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#176]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![Vickypedia](https://user-images.githubusercontent.com/42687608/198824367-aa03ef24-b854-4f87-8cc7-98646dd625a2.jpg)

## 問題の用語（必須）
ビッキーペディア

## 英語版の表現（任意）
Vickypedia

## 希望する変更（必須）
ヴィキペディア / Vickypedia（翻訳しない）

## 変更の理由（必須）
日本語タイトルとの整合性が取れておらず、なんのことかわからないため。

## ゲームバージョン（必須）
1.0.3

## DLC有無（必須）
- Victoria II Remastered Soundtrack
- American Buildings Pack

## MOD有無（必須）
なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
修正が完了しました。最終的に「ヴィキペディア」で確定しました。
