### ISSUE TITLE
【修正提案】財政権

### ISSUE THREAD

**Issue by saarland68** [matanki-saito/vic3jpadvmod#178]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![image](https://user-images.githubusercontent.com/70930137/198824829-9bca9027-2189-4877-8ba5-58b2726bea36.png)

## 問題の用語（必須）
財政権

## 英語版の表現（任意）
Power of the Purse
## 希望する変更（必須）
金力

## 変更の理由（必須）
意味合いが異なってるため

## ゲームバージョン（必須）

1.0.1

## DLC有無（必須）

無し

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by saarland68** [comment]
修正せずクローズします
