### ISSUE TITLE
【修正提案】武装勢力

### ISSUE THREAD

**Issue by Yoto** [matanki-saito/vic3jpadvmod#179]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![2022-10-29 (1)](https://user-images.githubusercontent.com/388340/198824451-9dffb7ab-703b-4ae4-b86c-a8e4179cfca0.png)

## 問題の用語（必須）

武装勢力

## 英語版の表現（任意）

Armed Forces

## 希望する変更（必須）

軍人 or 軍人階級

## 変更の理由（必須）

説明文には「国の軍事に強い関心や興味を示す職業軍人などのことです。」とあるため
いわゆるゲリラなどの武装勢力ではなく、軍人を代表とする利益団体の名称であるため

## ゲームバージョン（必須）

Vanilla(1.0.3), チェックサム：5fc2

## DLC有無（必須）

無し

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
軍部に修正完了、クローズします。
