### ISSUE TITLE
【修正提案】ライバル宣言時の通知

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#180]
## スクリーンショット（必須）

![20221028183401_1](https://user-images.githubusercontent.com/42710893/198824953-e667a43d-7c76-442a-ae84-78f2ff1c2b02.jpg)

## 問題のあるインターフェイス（必須）

ライバル宣言時の通知タイトル

## 問題のテキスト（必須）

"[INITIATOR_COUNTRY.GetAdjectiveNoFormatting]-[TARGET_COUNTRY.GetAdjectiveNoFormatting] [concept_rivalry]が宣言されました"

## 希望する変更（必須）

"[INITIATOR_COUNTRY.GetAdjectiveNoFormatting]-[TARGET_COUNTRY.GetAdjectiveNoFormatting]間の[concept_rivalry]宣言"

"[INITIATOR_COUNTRY.GetAdjectiveNoFormatting]-[TARGET_COUNTRY.GetAdjectiveNoFormatting]間の[concept_rivalry]関係が宣言されました"　でも良いがあまり長いと文字が見切れてしまう。タイトルであるし簡潔な表現の方が良い

また、他の方のissueにあったように[concept_rivalry]は競争ではなく、ライバルとするのが良い。

## 変更の理由（必須）

日本語として不自然なため。

## ゲームバージョン（必須）

1.0.3

## DLCの有無（必須）

なし

## MODの有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案とほぼ同様の形で修正しました。
```[INITIATOR_COUNTRY.GetAdjectiveNoFormatting]・[TARGET_COUNTRY.GetAdjectiveNoFormatting]間の[concept_rivalry]宣言```
起票ありがとうございました。なお、[concept_rivalry]については別起票の結果をお待ちください。
