### ISSUE TITLE
【未訳】Strata

### ISSUE THREAD

**Issue by saarland68** [matanki-saito/vic3jpadvmod#181]
## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/70930137/198825147-e08e193c-b8dd-49c6-80b4-7ca4e088a1c4.png)

## 問題のツールチップ（必須）
ステートクリック時のUIでpopをマウスオーバーした際の表示

## 問題の表現（必須）
Strata

## 希望する変更（必須）
階級

## 変更の理由（必須）
未訳のため

## ゲームバージョン（必須）

1.0.1

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by saarland68** [comment]
修正しました
クローズします
