### ISSUE TITLE
【修正提案】予想最低額

### ISSUE THREAD

**Issue by saarland68** [matanki-saito/vic3jpadvmod#182]
## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/70930137/198825669-ef36dd7d-b83c-4505-9bb3-59d2592499d9.png)

## 問題のあるインターフェイス（必須）
州UIの情報タブのモディファイア

## 問題のテキスト（必須）
予想最低額

## 希望する変更（必須）
予想される最低値/期待値（最小）

## 変更の理由（必須）
最低額だと金額のことを指しているため

## ゲームバージョン（必須）
1.0.2

## DLCの有無（必須）
なし

## MODの有無（必須）
なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by saarland68** [comment]
修正しました
「予想最低額」→「予想される最低値」
クローズします
