### ISSUE TITLE
アジア人などの姓名順逆転

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#184]
## 問題の固有名詞と希望する変更（必須）

家斉 徳川→徳川家斉　など多数

## 変更の理由（必須）

日本人、中国人、韓国人などのアジア人を中心とする人名はふつう姓名順で表記され、また間にスペースや・を挟まないのが普通だが、このゲームではそういった慣習は無視され、名姓順に並びスペースが挿入されており、没入感を損なっている。
すでに修正MODが出ているものの、変更箇所が多岐にわたるため、公式による修正が望ましい。

## ゲームバージョン（必須）

（例）1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
報告しました。
https://forum.paradoxplaza.com/forum/threads/oriental-name-order-issue.1558609/

**Comment by matanki-saito** [comment]
報告完了したためCloseと致します。
