### ISSUE TITLE
【修正提案】生産量の表記

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#189]
## スクリーンショット（必須）
①現在の生産量・消費量・雇用数（施設全体）
![image](https://user-images.githubusercontent.com/37979626/198824932-070edf4c-1980-4dae-a3e0-b30a9e172ced.png)
②現在の生産量・消費量・雇用数（レベル別）
![image](https://user-images.githubusercontent.com/37979626/198824940-b71e564a-f5a5-4e20-aac4-63c9115ba055.png)
③変更時の生産量・消費量・雇用数変動数（施設全体）
![image](https://user-images.githubusercontent.com/37979626/198825001-3a628058-2427-4117-a314-8eea1ebdef53.png)
④変更時の生産量・消費量・雇用数変動数（レベル別）
![image](https://user-images.githubusercontent.com/37979626/198825009-e30ad0d6-d9fc-4c2e-b1d6-b26fb12b77ef.png)

## 問題のあるインターフェイス（必須）

施設ウィンドウの生産画面

## 問題のテキスト（必須）

'$TOTAL_CHANGE|=+D$合計（+○○ 合計）
'$TOTAL_DELTA|=+D$ 合計で$MORE_OR_LESS$（+○○ 合計でもっと）
'$PER_LEVEL_DELTA|=+D$$MORE_OR_LESS$/レベル（+○○ もっと/レベル）

## 希望する変更（必須）

合計で$TOTAL_CHANGE|=+D$（合計で+○○）
合計で$TOTAL_DELTA|=+D$$MORE_OR_LESS$します（合計で+○○増加します）
レベルごとに$PER_LEVEL_DELTA|=+D$$MORE_OR_LESS$します（レベルごとに+○○増加します）

## 変更の理由（必須）

自然な表現にするため
※スクショの「3州に」は別で修正予定
## ゲームバージョン（必須）

1.0.2

## DLCの有無（必須）

なし

## MODの有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
以下の案で修正しました
```合計で$TOTAL_CHANGE|=+D$（合計で+○○）
合計で$TOTAL_DELTA|=+D$$MORE_OR_LESS$します（合計で+○○増加します）
レベルごとに$PER_LEVEL_DELTA|=+D$$MORE_OR_LESS$します（レベルごとに+○○増加します）```
