### ISSUE TITLE
【修正提案】お金 (ツールチップ)

### ISSUE THREAD

**Issue by ikabomb** [matanki-saito/vic3jpadvmod#190]
## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/84853597/198835670-a590a235-04cb-4a7f-b138-4e52cd4f1dea.png)
issue #157 から流用
## 問題のツールチップ（必須）

「お金」にマウスオンしたときに表示されるツールチップ(コンセプト)

## 問題の表現（必須）

お金は世界を動かしています。国家公務員の給金、官僚制の生産、建設資材、産業**界**の助成、貿易ルートの護衛、軍備などの支払いに使われます。POP**から**の課税と関税の**執行**によってお金を得ることができます。余ったお金は国庫で、債務の返済や、金保有高に金を備蓄するために使われます。お金が足りない場合は、債務が与信限度まで増えていきます。**これ**は、自国の施設の手元資金にどの程度のお金があるかによって決まります。

## 問題箇所の英文（任意）

$concept_money$ makes the world go 'round. It is used to pay for [Concept('concept_government_wage','$concept_government_wages$')] and [concept_bureaucracy] production, [concept_construction] materials, **industry** [concept_subsidies], [concept_convoys] for your [Concept('concept_trade_route','$concept_trade_routes$')], _and last but probably not least_, your military. You gain $concept_money$ *by* [Concept('concept_taxes','$concept_taxing$')] your [Concept('concept_pop', '$concept_pops$')] and *enforcing* [concept_tariffs]. Excess $concept_money$ in your [concept_treasury] balance is used to pay off your [concept_loans] or stockpile gold in your [concept_gold_reserves]. Insufficient $concept_money$ increases your $concept_loans$ towards your [Concept('concept_credit','$concept_credit_limit$')], which is determined by how much $concept_money$ is in your $concept_buildings$' [concept_cash_reserves].

## 希望する変更（必須）

産業界の助成　→　産業の助成
POPからの課税　→　POPへの課税
関税の執行　→　関税の徴収
これは　→　与信限度は

また、訳されていない文節 "and last but probably not least" があり(斜体部)、これについて
「～貿易ルートの護衛などに使われ、そして最後にまだ資金が余っているときにのみ軍備にも使われます。」
あたりに変更しても良いかと思います

## 変更の理由（必須）

日本語の整合性のため:
産業界は産業の集合体であり、助成対象ではありません
課税は税を課すことであり、国家はPOPから課税されません
関税は税であり、税をenforceするなら(強制的な)徴収であろうと思います

分かりづらいため:
施設の手元資金と与信限度がリンクすることは私には非直感的だったので、「これ」では何を指しているのか不明瞭に思えたためです

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
> お金は世界を動かしています。[Concept('concept_government_wage','$concept_government_wages$')]、[concept_bureaucracy]の生産、[concept_construction]資材、産業の[concept_subsidies]、[Concept('concept_trade_route','$concept_trade_routes$')]の[concept_convoys]、軍備などの支払いに使われます。[Concept('concept_pop', '$concept_pops$')]への[Concept('concept_taxes','$concept_taxing$')]と[concept_tariffs]の徴収によって$concept_money$を得ることができます。余った$concept_money$は[concept_treasury]で、[concept_loans]の返済や、[concept_gold_reserves]に金を備蓄するために使われます。$concept_money$が足りない場合は、$concept_loans$が[Concept('concept_credit','$concept_credit_limit$')]まで増えていきます。[conceot_credit_limit]は、自国の$concept_buildings$の[concept_cash_reserves]にどの程度の$concept_money$があるかによって決まります。

**Comment by clamm0363** [comment]
以上のように修正しました。

クローズします。

**Comment by clamm0363** [comment]
タイポがあったので修正しました。
