### ISSUE TITLE
【修正提案】製品価格の表記

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#191]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![image](https://user-images.githubusercontent.com/37979626/198835966-9d1a0f69-3e0d-40d0-8a81-20b5ae116a8b.png)
![image](https://user-images.githubusercontent.com/37979626/198835970-7f4a3a2e-283c-4404-bd13-d0a78597c1e3.png)
![image](https://user-images.githubusercontent.com/37979626/198837857-2b2e259b-af5a-44fb-83a6-37be67fe827f.png)

## 問題の用語（必須）

施設ウィンドウの生産画面の価格（価格帯）
※「合計でもっと」のあたりは別で起票中

## 英語版の表現（任意）

`([現在の価格帯]) → ([変更後の価格帯]) in $NUM_STATES$ [Concept('concept_state', '$concept_states$')]`
`@money!$MIN_PRICE|1v$ $MIN_PRICE_ICON$ - @money!$MAX_PRICE|1v$ $MAX_PRICE_ICON$ in $NUM_STATES$ [Concept('concept_state', '$concept_states$')]`
`@money!$PRICE|1v$ $PRICE_ICON$ in [Market.GetName]`

## 希望する変更（必須）

`([現在の価格帯]) → ([変更後の価格帯]) これは$NUM_STATES$[Concept('concept_state', '$concept_states$')]が対象です`
`$NUM_STATES$[Concept('concept_state', '$concept_states$')]で@money!$MIN_PRICE|1v$ $MIN_PRICE_ICON$ - @money!$MAX_PRICE|1v$ $MAX_PRICE_ICON$`
`[Market.GetName]で@money!$PRICE|1v$ $PRICE_ICON$`

## 変更の理由（必須）

分かりづらいため
特に最初のは価格帯が括弧で表記されているため、急に「〇州で」と表示されても後ろに続くのが分かりにくいため、こちらで補う必要があると判断

## ゲームバージョン（必須）

1.0.1

## DLC有無（必須）

無し

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
https://discordapp.com/channels/1022767005662724096/1035916190599618621/1035916190599618621
issue189も連動しているので統一します
修正するエントリ
SINGLE_GOODS_OR_EMPLOYMENT_MORE
SINGLE_GOODS_OR_EMPLOYMENT_LESS
SINGLE_GOODS_AMOUNT_PRODUCTION_TOTAL
SINGLE_GOODS_AMOUNT_PRODUCTION_PER_LEVEL
SINGLE_GOODS_AMOUNT_CONSUMPTION_TOTAL
SINGLE_GOODS_AMOUNT_CONSUMPTION_PER_LEVEL
SINGLE_GOODS_DELTA_PRODUCTION_TOTAL
SINGLE_GOODS_DELTA_PRODUCTION_PER_LEVEL
SINGLE_GOODS_DELTA_CONSUMPTION_TOTAL
SINGLE_GOODS_DELTA_CONSUMPTION_PER_LEVEL
SINGLE_GOODS_MARKET_PRICE_RANGE
SINGLE_GOODS_STATE_PRICE_RANGE
SINGLE_GOODS_STATE_PRICE_RANGE_TOOLTIPPABLE
SINGLE_GOODS_MARKET_PRICE_RANGE_WITH_DELTA
SINGLE_GOODS_STATE_PRICE_RANGE_WITH_DELTA
SINGLE_GOODS_STATE_PRICE_RANGE_TOOLTIPPABLE_WITH_DELTA
SINGLE_POP_EMPLOYMENT_CHANGE_FROM_BASE_TOTAL
SINGLE_POP_EMPLOYMENT_DELTA_TOTAL
SINGLE_POP_EMPLOYMENT_DELTA_PER_LEVEL
SINGLE_GOODS_FORMAT
SINGLE_GOODS_FORMAT_WITH_SHORTAGE
