### ISSUE TITLE
【バグ】急進派および政府体制支持者ツールチップ

### ISSUE THREAD

**Issue by clamm0363** [matanki-saito/vic3jpadvmod#192]
## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/29382778/198842704-e9b8a5c7-26fa-4e8c-b029-b4f76f360625.png)
![image](https://user-images.githubusercontent.com/29382778/198842712-646a1391-9493-4014-a6ab-aedeef5c6535.png)

## 問題のツールチップ（必須）

トップバーなどの「急進派」および「政府体制支持者」のツールチップ

## 問題の表現（必須）

「急進派の数は、[日時]」で不自然に途切れている

## 問題箇所の英文（任意）

変数ばかりなので割愛

## 希望する変更（必須）

変数の取り扱い誤りを直して正しく表示されるようにしたい。修正後参考画像は下記。
![image](https://user-images.githubusercontent.com/29382778/198842780-3bccd439-c791-4142-9141-2dc716bce90c.png)

## 変更の理由（必須）

変数取り扱いミスによるバグで正しく表示されていないため。

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
<img width="700" alt="image" src="https://user-images.githubusercontent.com/35730970/198845927-d4a7fa01-c09e-480c-8315-57a18fd35c6e.png">

青枠が
```
[ConcatIfNeitherEmpty('\n\n',SelectLocalization( GreaterThan_int32(Country.CalcNumStatesInTurmoil, '(int32)0'), 'STATES_IN_TURMOIL', '' ))]
```
赤枠が
```
[ConcatIfNeitherEmpty('',SelectLocalization( Country.HasIGApprovalFromRadicals, 'RADICALS_IG_APPROVAL', '' ))]
```
なのでこの2つは文章の最下部に置く必要がある。これであっていますか？

**Comment by clamm0363** [comment]
@matanki-saito さん
お返事が遅れて申し訳ありません。お見込みのとおりです。
変数で呼ばれる青枠と赤枠の翻訳そのものはこのキーには現れてきません。別で起票する必要があります（翻訳もおかしいのでいずれ直します）

**Comment by clamm0363** [comment]
issue内修正後画像となるように修正しました。
「急進派」ツールチップと、その隣にあるLoyalistのツールチップが修正されています。
クローズします。

**Comment by Yoto** [comment]
![2022-10-31 (1)](https://user-images.githubusercontent.com/388340/198937505-58c00c65-30c4-4d6b-9c45-0d513c687c88.png)
画像のように末尾の「。」が重複しています。

**Comment by clamm0363** [comment]
報告ありがとうございます！修正しましたので、次回アプデで反映されると思います。
