### ISSUE TITLE
条件文のパターン

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#193]
## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/37979626/198847401-2f7282e3-9d94-4163-ae8d-3308408ab5d0.png)
![image](https://user-images.githubusercontent.com/37979626/198847406-8e46f366-759d-4f7b-bcab-904415662521.png)
![image](https://user-images.githubusercontent.com/37979626/198847384-8de43864-3d28-4c77-a90b-41217b88656f.png)
## 問題のあるインターフェイス（必須）

条件文

## 問題のテキスト（必須）

多すぎるので割愛

## 希望する変更（必須）

基本方針
・助詞は「が」を基本用いる（その方が主語がはっきりさせられる）
・コロンの後に条件となるものの名前や数値が表記されている場合は「次の」「以下の」を補う
・簡潔な表現を実現するために体言止めを基本使う（使えない箇所は「である」「ではない」で基本代用する）
①である or #bold ではない#!
　[concept_state]が[TARGET_CULTURE.GetName][concept_homeland]である
②がある or が#bold ない#!
　特性[STATE_TRAIT.GetName]がある
　次のゲームルールがある：$SETTING$
　[BuildingType.GetName]がある　←公式では「所有」を使っているが大抵、州にあるかないかを聞いているので「ある」で
③～中（済） or #bold 未～#!
　ローカルプレイヤーが操作中 or ローカルプレイヤーが#bold 未操作#!
　ゲームが開始済 or ゲームが#bold 未開始#!
　[BuildingType.GetName]が稼働中 or [BuildingType.GetName]が#bold 未稼働#!
　[COUNTRY.GetNameNoFlag]が[INSTITUTION_TYPE.GetName][concept_institution]を所有済 or [COUNTRY.GetNameNoFlag]が[INSTITUTION_TYPE.GetName][concept_institution]を#bold 未所有#!

## 変更の理由（必須）

条件文を端的に表現するため

## ゲームバージョン（必須）

1.0.2

## DLCの有無（必須）

なし

## MODの有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
あらかた修正完了したのでクローズ
