### ISSUE TITLE
【修正提案】国有軍 National Militia

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#194]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![national_militia](https://user-images.githubusercontent.com/50406316/198849945-eab0ed6a-b051-4094-990f-8bc02b077d7b.png)

## 問題の用語（必須）
国有軍

## 英語版の表現（任意）
National Militia

## 希望する変更（必須）
国民民兵

## 変更の理由（必須）
原文はMilitiaで、テキストでも常備軍を持たない代わりに戦時に民兵が戦うものと書いてあるため、より原文の意味に沿った訳語にしたい。

## ゲームバージョン（必須）
1.0.3

## DLC有無（必須）
無し

## MOD有無（必須）
なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Kinni03** [comment]
説明文を見る限り、国家によって管理された民兵とよみとれるような気がするので、国家民兵とかどうでしょうか？

**Comment by starjard** [comment]
開始時のUSA、スイス、アルゼンチンなどがこの制度を採用しています。
たぶん独立戦争時のUSAみたいに、戦時になると市民が武装して義勇兵として自発的に国軍に同行してくるようなのを想定してるので、国家によって管理されてるというわけではないと思います。

**Comment by Kinni03** [comment]
なるほど…、こちらの知識不足でした。たしかに、それなら国民民兵のほうが正確ですね。申し訳ない。

**Comment by starjard** [comment]
いえいえ、コメントありがとうございます。翻訳チーム内でも諮った結果、当初の案通り国民民兵に変更することにしてクローズします。
