### ISSUE TITLE
【修正提案】支持者と急進派のツールチップ

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#196]
## スクリーンショット（必須）
![20221028204951_1](https://user-images.githubusercontent.com/42710893/198864438-2a118f0d-7961-49fb-bfae-fe0d860b8d15.jpg)

![20221028204955_1](https://user-images.githubusercontent.com/42710893/198864443-e0ca880b-2d17-4b25-9ae9-ff2c53d7139d.jpg)

## 問題のツールチップ（必須）

支持者と急進派のツールチップ

## 問題の表現（必須）

あなたは現在〇〇〇〇がいません

## 希望する変更（必須）

現在○○○○はいません

## 変更の理由（必須）

あなたは　は不要と思われます

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
「現在[急進派/体制派]は存在しません」と修正しました。

クローズします。
