### ISSUE TITLE
【修正提案】外交プレイの家臣化

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#197]
＜ゲームシステム用語＞

## スクリーンショット（任意）

![20221030160934_1](https://user-images.githubusercontent.com/42710893/198867407-4cc472cb-d0e7-496b-bb41-fde69c172d78.jpg)

## 問題の用語（必須）

war_goal_make_vassal_type_name:0 "家臣化"

## 英語版の表現（任意）

war_goal_make_vassal_type_name:0 "Make Vassal"

## 希望する変更（必須）

従属化

## 変更の理由（必須）

国家間の外交関係を示す適切な用語ではないため。

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

無し

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
提案ありがとうございます。該当の単語だけではなくそれ以外の各属国タイプの名称について翻訳チーム内で全面的に精査を行った結果、Vassalを属国、Make Vassalを属国化と改訳することになりました。これにてクローズします。
