### ISSUE TITLE
【修正提案】チュートリアルのジャーナル完了条件

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#198]
## スクリーンショット（必須）

![20221030160632_1](https://user-images.githubusercontent.com/42710893/198867996-224726de-1cdd-4a74-b7ec-901bcb25f45c.jpg)

## 問題のあるインターフェイス（必須）

チュートリアルのジャーナルの完了条件

## 問題のテキスト（必須）

ケープ植民地にあるレベル3小麦畑(現在レベル2)

je_tutorial_expand_basic_building_goal:0 "[JournalEntry.GetTarget.GetBuilding.GetState.GetName]にあるレベル[JournalEntry.GetTotalGoalValue|v0] [JournalEntry.GetTarget.GetBuilding.GetName] (現在レベル[JournalEntry.CalcCurrentGoalValue|v0])"

## 希望する変更（必須）

ケープ植民地の小麦畑がレベル3である(現在レベル2)
ケープ植民地の小麦畑のレベルが3である(現在レベル2)
等

## 変更の理由（必須）

日本語として不自然なため。

## ゲームバージョン（必須）

（例）1.0.3

## DLCの有無（必須）

なし

## MODの有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
「ケープ植民地の小麦畑がレベル3」と表示されるように修正しました。

クローズします。
