### ISSUE TITLE
【修正提案】国-州/Nation-State

### ISSUE THREAD

**Issue by clamm0363** [matanki-saito/vic3jpadvmod#199]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![image](https://user-images.githubusercontent.com/29382778/198870461-15151f14-c700-4d0a-be71-09ffb1aadfae.png)

## 問題の用語（必須）

国-州

## 英語版の表現（任意）

Nation-State

## 希望する変更（必須）

国民国家

## 変更の理由（必須）

誤訳

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

Grand Edition

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
「国民国家」と修正しました。

クローズします。
