### ISSUE TITLE
【修正提案】より青々しい生物キャンペーン Greener Grass Campaign

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#201]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![green_glass](https://user-images.githubusercontent.com/50406316/198871117-4495c788-3e93-49c4-b7ad-7b8f3aa925d4.png)

## 問題の用語（必須）
より青々しい生物キャンペーン

## 英語版の表現（任意）
Greener Grass Campaign

## 希望する変更（必須）
隣の芝は青い運動

## 変更の理由（必須）
誤訳のため
原文は「隣の芝生は青く見える」が元ネタ

## ゲームバージョン（必須）
1.0.3

## DLC有無（必須）
無し

## MOD有無（必須）
なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
これは本当に意味が不明だったのでぜひ直したいです

**Comment by kecy3** [comment]
他の布告が〇〇の推奨、みたいなシンプルな効果説明になっている中、なぜかこれはキャンペーン名みたいになっているんですよね。
英文を気にせずに、単純に「移住の誘致」みたいな効果説明にしてしまうのも、手なのかなと個人的には思いました。

**Comment by starjard** [comment]
翻訳チーム内でご提案の「移住の誘致」と原案の「隣の芝は青い運動」で決を取ったところ、主に原文のニュアンスを取りたいという理由で「隣の芝は青い運動」に変更することに決定しました。今回は採用には至りませんでしたが、ご提案ありがとうございます。これにてクローズします。
