### ISSUE TITLE
【修正提案】戦闘画面の表記－戦闘の開始

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#203]
## スクリーンショット（必須）

![FgTopP2UUAAXiTr](https://user-images.githubusercontent.com/42710893/198871585-0e80abdf-8b76-4b83-9439-ef0a2f65c5d4.jpg)

## 問題のあるインターフェイス（必須）

戦闘画面

## 問題のテキスト（必須）

戦闘の開始
英語版ではStart of Battle

## 希望する変更（必須）

戦闘開始時

## 変更の理由（必須）

戦闘開始時点での兵力等を示している部分と思われるため。

## ゲームバージョン（必須）

1.0.3

## DLCの有無（必須）

なし

## MODの有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
「戦闘開始時」で修正が完了しました。
