### ISSUE TITLE
同地域を複数の国家が領有している際の地名表記

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#204]
## スクリーンショット（任意）
![image](https://user-images.githubusercontent.com/37979626/198872517-d8e66b52-31e2-48b5-89a9-055ac8247e72.png)

## 問題の固有名詞（必須）

$OWNER$ $REGION$

## 希望する変更（必須）

$OWNER$領$REGION$

## 変更の理由（必須）

分かりにくいため

## ゲームバージョン（必須）

1.0.1

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
修正エントリ
SPLIT_STATE_FORMAT
