### ISSUE TITLE
ヨーロッパの都市名

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#205]
## 問題の固有名詞と希望する変更（必須）

ボマースンド：ボマルスンド
エッケロ：エッケレ

クリスチャンスン：クリスチャンサン
フレデリクシャルド：フレデリクシャールド
コングスビンゲル：コングスヴィンゲル
スンツバル：スンツヴァル

ルーレオー：ルレオ
ソーデルハムン：セーデルハムン
ニュヒェーピング：ニューショーピング
ファルン：ファールン
シェブデ：シェヴデ
ベクシェー：ヴェクショー
ビスビュー：ヴィスビュー
ロマクロスター：ロマクロステル
スライト：スリテ
クリスチャンスタード：クリシャンスタード
ホル：ヘール

ネストベズ：ネストヴェズ
イェリング：ヤアイング

シュテッティン：シュテティーン
シュヴェット：シュヴェート
ケスリン：ケスリーン
シュタルガルト：シュタールガルト
エルフルト：エアフルト
ゲラ：ゲーラ
アウグスブルク：アウクスブルク
カイゼルスラウテルン：カイザースラウテルン
ブランズウィック：ブラウンシュヴァイク
マグデブルク：マクデブルク
ステンダール：シュテンダール
パダーボルン：パーダーボルン

シャルルロア：シャルルロワ
ブルージュ：ブルッヘ

アーンヘム：アルンヘム
グローニンゲン：フローニンゲン
ハーリンゲン：ハルリンゲン
ドラハテン：ドラフテン
ブルック・イン・ウォーターランド：ブルク・イン・ヴァテルラント

マーサーティドビル：マーサー・ティドビル
ニューキャッスル：ニューカッスル
リバプール：リヴァプール
バローインファーネス：バロー＝イン＝ファーネス
エジンバラ：エディンバラ
ダンフリース：ダンフリーズ
インバネス：インヴァネス
オーマ：オマー
カバン：キャヴァン
ガルウェー：ゴールウェイ
スリゴ：スライゴ
キャッスルバー：カスルバー
ラウレア：ローレイ

ヴァネス：ヴァンヌ
サン・ブリュー・サン＝ブリユー
アブランシュ：アヴランシュ
ボーベ：ボーヴェ
サン・カンタン：サン＝カンタン
レ・サーブル・ドロンヌ：レ・サブル＝ドロンヌ
ポアティエ：ポワティエ
サン・ジュニアン：サン＝ジュニアン
クレルモン・フェラン：クレルモン＝フェラン
モンソー・レ・ミーヌ：モンソー＝レ＝ミーヌ
プイイ・アン・オオワ：プイイ＝アン＝オスワ
メッス：メス
ガープ：ガプ
トゥルーズ：トゥールーズ
モン・ド・マルサン：モン＝ド＝マルサン
パウ：ポー

ベジャ：ベージャ
フィゲイラ・ダ・フォズ：フィゲイラ・ダ・フォス
ビゼウ：ヴィゼウ
カシュテロ・ブランコ：カステロ・ブランコ
ファーロ：ファロ

ヴィゴ：ビーゴ
オヴィエド：オビエド
ヴィトリア：ビトリア
ザラゴザ：サラゴサ
カラタユド：カラタユー
マドリッド：マドリード
シウダード・レアル：シウダー・レアル
カルタゲナ：カルタヘナ
カステリョ・デ・ラ・プラナ：カステリョン・デ・ラ・プラナ
ヴィック：ビック
イビザ：イビサ

カグリアリ：カリャリ
ヌオロ：ヌーオロ
カルボニア：カルボーニア
カルタニセッタ：カルタニッセッタ
カタニア：カターニア
アルカーモ：アルカモ
コセンザ：コゼンツァ
コリリアーノ・カラブロ：コリリアーノ・カーラブロ
バリ：バーリ
タラント：ターラント
フォッジア：フォッジャ
サラ・コンシリナ：サーラ・コンシリーナ
カセルタ：カゼルタ
ポテンザ：ポテンツァ
ペスカラ：ペスカーラ
アンコナ：アンコーナ
ペサーロ：ペーザロ
ペルジア：ペルージャ
アスコーリ・ピセノ：アスコリ・ピチェーノ
リボルノ：リヴォルノ
グロセット：グロッセート
ラベンナ：ラヴェンナ
サン・マリノ：サンマリノ
ベローナ：ヴェローナ
パドゥア：パドヴァ
ブレシャ：ブレシア
ノヴァラ：ノヴァーラ
クネオ：クーネオ

トノン・レ・バン：トノン＝レ＝バン
サン・ジャン・ド・モーリエンヌ：サン＝ジャン＝ド＝モーリエンヌ 
ジュネーブ：ジュネーヴ

メラノ：メラーノ
ロベレト：ロヴェレート
ボルザノ：ボルツァーノ

グラズ：グラーツ

チェスケ：チェスケー
スビタビ：スヴィタヴィ
ピルセン：ピルゼン
ブレクラフ：ブジェツラフ
イフラバ：イフラヴァ
ジリーナ：ジリナ
トレンチン：トレンチーン
コシチェ：コシツェ
ウジホロド：ウージュホロド
ポプラド：ポプラト

ナジバーラド：ナジヴァーラド
ベレクサース：ベレグサース
ソトマルニメティ：サトマールネーメティ
コロジュバール：コロジュヴァール

アルバ・ルリア：アルバ・ユリア
ティミソアラ：ティミショアラ
オルティソアラ：オルツィショアラ
ファゲ：ファジェト
ノビサド：ノヴィ・サド
パンチェボ：パンチェヴォ
ベリキ・ベチュケレク：ヴェリキ・ベチケレク
サバトカ：サバドカ
ブロド・ナ・サビ：ブロド・ナ・サヴィ
ブイェロバル：ビェロヴァル
オシイェク：オシエク
グラディスカ：グラディシュカ
セーケシュフェヘールバール：セーケシュフェヘールヴァール
プトゥイ：プトゥーイ
ノボメスト：ノヴォ・メスト
プラ：プーラ
ウディネ：ウーディネ
カーロヴァック：カルロヴァツ
シザク：シサク
ザダール：ザダル
サラエボ：サラエヴォ
モスター：モスタル
ベルグラード：ベオグラード
クルシェバツ：クルシェヴァツ
スメデロボ：スメデレヴォ
クラリエボ：クラリェヴォ
プリスティナ：プリシュティナ
レスコヴァク：レスコヴァツ
ベシアーヌ：ベシアナ
ポドゴリカ：ポドゴリツァ
バー：バール
モイコバツ：モイコヴァツ
ベラーネ：ベラネ
ハノビ：ハノヴィ
ベラート：ベラト
カヴァダルシ：カヴァダルツィ
プリレップ：プリレプ

フローリナ：フロリナ
クサンチ：クサンティ
カルドヒツァ：カルディツァ
カラマータ：カラマタ
コリント：コリントス
テラ：テーラ
ミティリニ：ミティリーニ

プロブディフ：プロヴディフ
バルガス：ブルガス
スターラ・ザゴラ：スタラ・ザゴラ
コンスタンタ：コンスタンチャ
イアシ：ヤシ
ラダウティ：ラダウツィ
フォクサーニ：フォクシャニ

ルブフ：ルヴフ
チェルノフツィ：チェルニウツィー
スタニスラビブ：スタニスラーヴィウ
ビエルスコ：ビェルスコ
ケーニヒシュッテ：ケーニヒスヒュッテ
クロイツベルク：クロイツブルク
ポーセン：ポーゼン
ソーン：トルン
ストラスブルク：シュトラスブルク
インスタブルク：インスターブルク
アレンスタイン：アレンシュタイン

チェンストホバ：チェンストホヴァ
トマシュフ・マゾビエツキ：トマシュフ・マゾヴィエツキ
キエルツェ：キェルツェ
ロムザ：ウォムジャ
オストロレカ：オストロウェンカ
ビルニュス：ヴィルニュス
リーガ：リガ
リアパーヤ：リエパーヤ
エルガワ：イェルガヴァ
マドーナ：マドナ
ナルバ：ナルヴァ

クローンシュタット：クロンシュタット
ゴメル：ゴメリ
ビイテプスク：ヴィチェプスク
ボリソフ：バルイサウ
マズィル：モーズィリ
バブルイスク：ボブルイスク
ロブノ：ロヴノ
ターノポール：タルノーポリ
コヴェル：コーヴェリ
ノヴォフラード・ヴォルインスキー：ノヴォフラード＝ヴォルィーンシキー
キーフ：キーウ
スムイ：スームィ
ニコラエフ：ニコラーエフ
オデッサ：オデーサ
エリザベートグラード：エリザヴェトグラード
ボズネセンスク：ヴォズネセンスク
スダク：スダーク
エカテリノスラフ：エカチェリノスラーフ

ロデイノイェ・ポリェ：ロジェーイノイェ・ポーリェ
ペトロザボーツク：ペトロザヴォーツク
シャンガリー：シャーンガルィ
ベレツニク：ベレージニク
リビンスク ：ルィビンスク 
コノシャ：コーノシャ
ヴェルスク：ヴェリスク
リャツァン：リャザン
アルツァマス：アルザマス
ブヤトカ：ヴャトカ
ペンツァ：ペンザ
アレクサンドロ・グルシェフスカヤ：アレクサンドロ＝グルシェフスカヤ
ノボチェルカスク：ノヴォチェルカッスク
チムリャンスカヤ：ツィムリャーンスカヤ
イェカテリノダール：エカチェリノダール
ピャティゴルスク：ピャチゴルスク
ティクホレツスク：チホレツク
メイコプ：マイコープ
アルマビル：アルマヴィル
ペトロフスク・ポルト：ペトロフスク＝ポルト
ブラジカフカス：ヴラジカフカース
グロズニー：グロズヌイ
アストラカーン：アストラハン
カラチ：カラーチ

アクトーベ：アクトベ
クルサリー：クルサルィ
シャルカール：シャルカル
グリェフ：グリーエフ
サマラ：サマーラ
オレンブルグ：オレンブルク
ウーファ：ウファ
リスファ：ルィシヴァ
ベレツニキ：ベレズニキ
アムデルマ：アンジェルマ
カールタ：ハルター
エカテリンブルク：エカチェリンブルク
ニジニ・タジル：ニジニ・タギル
ハンティ・マンシースク：ハンティ＝マンシースク
グブキンスキー：グープキンスキー
セルジノ：セルギノ
ノボニコラエフスク：ノヴォニコラエフスク
ウスチ・アバカンスコエ：ウスチ＝アバカンスコエ
バーナウル：バルナウル
アク・ドヴラク：アク＝ドヴラーク
マクラコボ：マクラコーヴォ
ヴァンガシュ：ヴァンガーシュ
カルパシェヴォ：コルパーシェヴォ
ブラツク：ブラーツク
サンガー：サンガール
ミルニー：ミールヌイ
スコヴォロディノ：スコヴォロジノ
アラフ・ユニ：アラフ＝ユニ
ユニクチャン：ウィヌィクチャン
ボルガー：ボルグル
ベリンゴフスキー：ベーリンゴフスキー
アチャイファエム：アチャーイヴァヤーム
ヴァエギ：ヴァイェーギ
ペトロパブロフスク・カムチャツキー：ペトロパヴロフスク＝カムチャツキー
ギジガ：ギージガ
ミルコヴォ：ミーリコヴォ
クリヤチ：クリュチ
ユジノ・サハリンスク：ユジノ＝サハリンスク
オクハ：オハ
ノジリキ：ノギリキ

## 変更の理由（必須）
日本語では一般的ではない表記であるため。

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正内容変更
エッケロ：エケレ　→　エッケレ

修正内容から削除
フレドリクスタ：フリードリヒシュタト

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
