### ISSUE TITLE
【修正提案】課税キャパシティの説明文

### ISSUE THREAD

**Issue by WoodlandsGitHub** [matanki-saito/vic3jpadvmod#206]
## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/29177147/198869544-4407ab20-24c4-4534-a1f1-f427d81e3311.png)

## 問題のツールチップ（必須）

課税キャパシティのツールチップ

## 問題の表現（必須）

州の課税キャパシティの各ポイントは、10.0k
POPの課税を効率化します。
（改行ママ

## 問題箇所の英文（任意）

＞concepts_l_english.yml
concept_tax_capacity_desc:2 "Each point of Taxation Capacity in a [concept_state] allows for the efficient taxation of [GetDefine('NPops','INDIVIDUALS_TAXED_PER_TAX_CAPACITY')|vK] [Concept('concept_pop','$concept_pops$')]. If the population of a [concept_state] outgrows its Taxation Capacity, the efficiency of all forms of taxation will be reduced. Taxation Capacity can be increased through researching certain $SOCIETY$ $concept_technologies$ or constructing [SelectLocalization(GetPlayer.IsValid, 'concept_tax_capacity_desc_added','Government Administration')] [Concept('concept_building','$concept_buildings$')] in the [concept_state]."

## 希望する変更（必須）

州に設定されている課税キャパシティは、1ポイント毎に10.0kのPOPへの課税を効率化（or適正化）します。
[concept_state]の人口が課税キャパシティ以上に成長すると、すべての課税効率が下がります。
課税キャパシティを高める手段は、特定の$SOCIETY$$concept_technologies$の研究や、[concept_state]で[SelectLocalization(GetPlayer.IsValid, 'concept_tax_capacity_desc_added','Government Administration')][Concept('concept_building','$concept_buildings$')]の建設です。"

※課税キャパシティ以内に収めるのが当たり前のようなので、効率化（＋αなニュアンス）より適正化（100%にするニュアンス）
の方がふさわしいように思う。
※課税キャパシティを高める手段は他に、行政府施設での「製法」変更があるので、元文に追記される可能性あり。

## 変更の理由（必須）

半角スペースによる改行が入ったりして分かりづらい。
意味合いを取りやすく改訳。

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。
