### ISSUE TITLE
【修正提案】○○の移住

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#207]
## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/37979626/198877148-6b4028c8-feba-479c-87f7-7b662714e767.png)

## 問題のツールチップ（必須）
移住に関するポップアップ画面

## 問題の表現（必須）
[SCOPE.GetRootScope.GetState.GetMassMigrationCulture.GetName]の移住
[SCOPE.GetRootScope.GetState.GetMassMigrationCulture.GetName]である人々の大多数が我が国の州である[SCOPE.GetRootScope.GetState.GetName]およびその近隣州に移住し始めています。
[SCOPE.GetRootScope.GetState.GetMassMigrationCulture.GetName]である人々の大多数が[SCOPE.GetRootScope.GetState.GetName]の州およびその近隣州に移住し始めています。

## 問題箇所の英文（任意）
[SCOPE.GetRootScope.GetState.GetMassMigrationCulture.GetName] Migration
Large numbers of [SCOPE.GetRootScope.GetState.GetMassMigrationCulture.GetName] people have begun migrating to our state of [SCOPE.GetRootScope.GetState.GetName] and its surrounding states.
Large numbers of [SCOPE.GetRootScope.GetState.GetMassMigrationCulture.GetName] people have begun migrating to the state of [SCOPE.GetRootScope.GetState.GetName] and its surrounding states.

## 希望する変更（必須）
[SCOPE.GetRootScope.GetState.GetMassMigrationCulture.GetName]系移民
多くの[SCOPE.GetRootScope.GetState.GetMassMigrationCulture.GetName]系移民が我が国の[SCOPE.GetRootScope.GetState.GetName]州およびその近隣州に移住し始めています。
多くの[SCOPE.GetRootScope.GetState.GetMassMigrationCulture.GetName]系移民が[SCOPE.GetRootScope.GetState.GetName]州およびその近隣州に移住し始めています。

## 変更の理由（必須）
自然な日本語表現にするため
別地域のPOPが移ってくることからpeopleを「移民」と訳す

## ゲームバージョン（必須）
1.0.1

## DLC有無（必須）
なし

## MOD有無（必須）
なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
提案どおりに修正しました。

クローズします。
