### ISSUE TITLE
信用→与信

### ISSUE THREAD

**Issue by nagi0330** [matanki-saito/vic3jpadvmod#208]
＜ゲームシステム用語＞

## スクリーンショット
![20221101123819_1](https://user-images.githubusercontent.com/6514922/199387917-818f25d6-3ac2-443f-b809-28088f6621be.jpg)

## 問題の用語（必須）

信用

## 英語版の表現（任意）

credit

## 希望する変更（必須）

与信/与信枠/与信残高

## 変更の理由（必須）

一般的に金融的な文脈での翻訳はcreditの場合与信が適切かと。

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

無し

## MOD有無（必須）

無し

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
こちら使用画面が分かるようスクショ貼っていただけますか

**Comment by matanki-saito** [comment]
恐らくこれですかね

**Comment by matanki-saito** [comment]
与信って単語もゲーム内で出てますね

**Comment by nagi0330** [comment]
遅くなりましたがスクショ添付しました。

数値化するものに対して信用ってワードが使われるのに違和感があるんですよね。
与信枠、よりは与信残高の方が適切かもしれないです

**Comment by starjard** [comment]
与信とは信用を与える行為で、例えば個人のクレジットカード使用だとカード会社が使用者に信用を与えているので与信という単語を使います。しかし国家の債券発行による借金については、通常は誰かから信用を供与されているわけではなく、自らの持つ信用によって債券を発行しているだけなので、与信という単語は使いません。
信用を数値として使う用例については、例えば以下のようなものがあります。

財務省　外貨準備等の状況（令和4年8月末現在）
https://www.mof.go.jp/policy/international_policy/reference/official_reserve_assets/data/0408.html
>(a) 外国中央銀行、BIS、IMF及びその他国際金融機関からの信用枠

ロイターニュース
https://jp.reuters.com/article/ukraine-crisis-gas-uniper-idJPKBN2OT10L
> 経営難に陥っているドイツのガス・電力会社ウニパーは１８日、国営のドイツ復興金融公庫（ＫｆＷ）に対して現在２０億ユーロ（約２０億３０００万ドル）の信用枠を引き上げるよう申請した。

**Comment by nagi0330** [comment]
なるほど、となると「信用枠」というワードが適切でしょうか

**Comment by starjard** [comment]
ゲームでは信用枠がありますが、現実の用語に合わせたフレーバーとしては、「枠」は付けないほうがいいと考えます。
上の用例で「枠」が付いているのは借り手が民間会社だったり、貸し手が外国だったりして債務の上限が決まっている性質のものだからですが、国債発行については上限と言うものがありません。
国債については目に見えるような信用枠もあるわけではなく、市場関係者の空気によりなんとなくこの国はまだ信用できる・できないというのが決まります。例えば日本はこれだけ債務が積みあがっていてもまだ信用があるので低利で国債を発行でき、ギリシャは信用がなくなり債務危機が起きましたが、信用のあるなしを決める境目となる債務額がどれくらいなのかは誰にもわかりません。
ただそれをゲームに落とし込む際には境目が不明というわけにもいかないので、便宜的にゲーム内ではGDPの〇%を信用上限とするゲームルールを作っているにすぎないのだと思います。
説明が長くなりましたが、「枠」を付けてしまうとゲーム的になってしまい雰囲気を損なうと思います。現実の用語同様に、「枠」を付けないほうが雰囲気が出ると思います。

**Comment by nagi0330** [comment]
まあここは感覚の問題だと思うので他の方の議論に任せますが、ゲーム的云々以前に日本語として"信用"が数字で表されている事に対して違和感が拭えないんですよね。事実としてVictoria3はゲーム的な処理をしている部分が多いですし

**Comment by N-der** [comment]
このゲームにおいての債務上限は、すなわち「国内建造物の金準備上限の総計」と同じになっているはずです。
(今ゲームを立ち上げることができないので、古いですが代わりに開発日記を挙げます。3つめのCredit Limitの画像で示されています。)
https://simulationian.com/2021/08/vic3-dd20210826/

ゲームとしては国内産業の大きさに応じて信用の上限を疑似的に決定するという意図もあると思われるので、上にあげられた財務省のページで使われるような「信用枠」とは意味合いが異なるかもしれません。
とはいえ、ゲームのわかりやすさの点から、上限が明確に定まっているものを「信用」と呼ぶよりは、「信用枠」としたほうが僕としては適切に見えます。

**Comment by starjard** [comment]
ご意見ありがとうございます。ご両人のコメントを受けて翻訳チーム内で議論を行った結果、やはりゲームでの分かりやすさを重視たいということになり、「信用枠」とすることに決定しました。これにてクローズします。
