### ISSUE TITLE
【修正提案】稼働率の説明文「最大productive能力」

### ISSUE THREAD

**Issue by WoodlandsGitHub** [matanki-saito/vic3jpadvmod#209]
## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/29177147/198880535-fba6cb31-de0e-4e97-bf51-8b06a8ff65cf.png)

## 問題のツールチップ（必須）

稼働率

## 問題の表現（必須）

最大productive能力

## 問題箇所の英文（任意）

ファイル：concepts_l_japanese.yml
キー：concept_occupancy_desc:1
その最大[Concept('concept_good_production','Productive')]能力のうち

## 希望する変更（必須）

その最大[Concept('concept_good_production','生産')]能力のうち

## 変更の理由（必須）

未訳

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

日本語改善MOD
Switch Languages

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
> 定員に対し、ある[concept_building]がどれだけの雇用を達成しているかを示します。また、その稼働率はその施設の最大[Concept('concept_good_production','Productive')]効率をどれだけ活用できるかを決定します。もし$concept_building$にもっと多くの[concept_workforce]を雇用する余地があれば、常にそうしようとします。提供できる[concept_building_wage]によって雇用が制限されている場合、[concept_building_balance]がプラスのままである限り、$concept_building_wages$を増加させます。

**Comment by clamm0363** [comment]
上記のように修正しました。

クローズします。
