### ISSUE TITLE
【修正提案】承認→賛意

### ISSUE THREAD

**Issue by WoodlandsGitHub** [matanki-saito/vic3jpadvmod#210]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![image](https://user-images.githubusercontent.com/29177147/198882442-00b515fc-a08d-4c3d-bd90-e6ec56445668.png)
![image](https://user-images.githubusercontent.com/29177147/198883135-ac215e02-262b-47c5-aa69-60224149005b.png)

## 問題の用語（必須）

承認

## 英語版の表現（任意）

Approval

## 希望する変更（必須）

賛意

## 変更の理由（必須）

政府への支持度合いを示す用語であり、承認よりも意味合いがタイトな賛意の方が向いてると思う。

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

無し

## MOD有無（必須）

日本語改善MOD
Switch Languages

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
先んじて法律への支持が賛成に決定しており、読みにくいため、こちらを支持に変更
