### ISSUE TITLE
【修正提案】認知度→承認国

### ISSUE THREAD

**Issue by WoodlandsGitHub** [matanki-saito/vic3jpadvmod#211]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![image](https://user-images.githubusercontent.com/29177147/198883244-42c661bd-9da0-46f3-b0d9-3688bb9e0797.png)
![image](https://user-images.githubusercontent.com/29177147/198883562-5db8b1fb-b007-43e6-a3b1-df4bb0dabbf2.png)

## 問題の用語（必須）

 concept_recognized_power:0 "認知度"
 concept_recognized_powers:0 "認知度"

## 英語版の表現（任意）

 concept_recognized_power:0 "Recognized Power"
 concept_recognized_powers:0 "Recognized Powers"

## 希望する変更（必須）

 concept_recognized_power:0 "承認国"
 concept_recognized_powers:0 "承認国"

## 変更の理由（必須）

誤訳

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

無し

## MOD有無（必須）

日本語改善MOD
Switch Languages

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
ご提案どおり修正しました。

クローズします
