### ISSUE TITLE
【修正提案】Methods producing/using

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#212]
## 問題のあるインターフェイス（必須）
![method_producing](https://user-images.githubusercontent.com/50406316/198888383-b5e1b3da-a8b6-4d6f-86bc-3f10bb63f755.png)
![method_producing_en](https://user-images.githubusercontent.com/50406316/198888395-9da51866-c52b-4875-8d54-2ce7862446a1.png)
※該当箇所は折り畳みになっており、開くとこの場合はガラスを生産・使用する建造物のmethod一覧がずらっと出てくる

## 問題のテキスト（必須）
[Concept('concept_production_method', '$concept_production_methods$')]は、[GetPlayer.GetName]で[Goods.GetTextIcon][Nbsp][Goods.GetName]を生産しています
[Concept('concept_production_method', '$concept_production_methods$')]は、[GetPlayer.GetName]で[Goods.GetTextIcon][Nbsp][Goods.GetName]を使用しています

## 希望する変更（必須）
[GetPlayer.GetName]で[Goods.GetTextIcon][Nbsp][Goods.GetName]を生産する[Concept('concept_production_method', '$concept_production_methods$')]
[GetPlayer.GetName]で[Goods.GetTextIcon][Nbsp][Goods.GetName]を使用する[Concept('concept_production_method', '$concept_production_methods$')]
（スクショの例だと「プロイセンでガラスを生産する方式」「プロイセンでガラスを使用する方式」となる）

## 変更の理由（必須）
日本語として不自然で、意味が読み取りにくい訳文になっているため修正したい

## ゲームバージョン（必須）
1.0.3

## DLCの有無（必須）
なし

## MODの有無（必須）
スクショでは和訳修正MODを入れており、製法→方式に改訳されているが、それ以外は影響がない

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by WoodlandsGitHub** [comment]
#143 , #144で起票済みでする

**Comment by starjard** [comment]
重複でしたね。こちらは取り下げします。

**Comment by WoodlandsGitHub** [comment]
数が増えてきていて、重複しないように既存のissueを探す時間が長くなってきてる感じがありますね…
