### ISSUE TITLE
アジア、アフリカの都市(hub)

### ISSUE THREAD

**Issue by N-der** [matanki-saito/vic3jpadvmod#213]
## 問題の固有名詞と希望する変更（必須）

ソウル→漢城
泰州→台州　綴りは同じだが、場所が異なるため
ラーサ→ラサ
スリナガール→スリナガル

クザンド→ホジェンド
コッカンド→コーカンド
ヌカス→ヌクス
アシュガバット→アシガバート
バルカナバット→バルカナバート
トルクメナバット→トルクメナバート
バク→バクー
ポチ→ポティ
ナクシヴァニ→ナヒチェヴァン
バツミ→バトゥミ

シヴァス→シバス　原音に則るならスィヴァス
コニャ→コンヤ
アンターリャ→アンタルヤ
ジダー→ジッダ
リヤヅ→リヤド
コラマバッド→ホッラマーバード
ケルマンシャー→ケルマーンシャー
アーヴァズ→アフワーズ
バンダー・マーシャー→バンダレマーシャー
コラムシャー→ホッラムシャー
シラズ→シーラーズ
ヤスジ→ヤースージ
バンダー・アッバス→バンダレアッバース
ケルマン→ケルマーン
バンダー・エシャラク→バンダレシャラク
イスファハン→イスファハーン
コム→ゴム　やや細かい？
カズヴィン→ガズヴィーン
マシャード→マシュハド
ザヘダン→ザーヘダーン
アラーハバード→アラーハーバード

マイスール→マイソール
コチ→コーチ
ヴィシャハパルマン→ヴィシャカパトナム　Vishakhapatnam の誤りだと思われる
アンビカプール→アンビカプル　語末のpurは短母音のため。以下同じ
ジャグダルプール→ジャグダルプル
サムバルプール→サンバルプル
バガルプール→バガルプル
ランチ→ラーンチー

ケール→カレ
フパカン→ファカン
マラウク→ミャウウー
バゴ→バゴー
マンダレイ→マンダレー
ナイピタウ→ネピドー　ネーピードーの方が良いか？
ケンタン→ケントゥン
ヒュエ→フエ
カンソー→カントー
クロン・バンラン→クロン・バンルン
クロン・シエムリープ→クロン・シェムリアップ
ナコンサワン→ナコーンサワン
ペカンバル→プカンバル
メントク→ムントク
メンガラ→ムンガラ
シレボン→チレボン　チェリボンでも良いか
セラン→スラン
マリング→マリン
バンジェルマシン→バンジャルマシン
ザンボアンガ→サンボアンガ
メナド→マナド　Manado の誤りだと思われる

サオ・ヴィセント→サン・ヴィセンテ
タンギエルス→タンジール
メリラ→メリリャ
ノウアクショット→ヌアクショット
コンスタンティン→コンスタンティーヌ
マルサ・マトルフ→マルサ・マトルーフ
ポート・セイド→ポートサイド
ディボウティ→ジブチ
ジッマ→ジンマ
ブロエムフォンテイン→ブルームフォンテーン
ルクスビル→ルービル
ニューキャッスル→ニューカッスル
ウィンドフーク→ウィントフック
ベングエラ→ベンゲラ
サオ・サルバド→サンサルバドル　São Salvadol の誤りだと思われる
ブラッザビル→ブラザビル
オニツシャ→オニシャ
コトノー→コトヌー
ローメ→ロメ
アックラ→アクラ
ヤムーッソークロ→ヤムスクロ
コナクリー→コナクリ
サンタ・クルツ・デ・テネリフェ→サンタ・クルス・デ・テネリフェ

## 変更の理由（必須）

日本語の標準的な表記と異なるため

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by N-der** [comment]
アフリカに関してはざっと目を通して気になるところに手を入れただけなので、より細かく修正をお願いしたいです。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
なお、一部のアフリカの都市名はIssue #319 と共に修正します。
