### ISSUE TITLE
【修正提案】電力建造物

### ISSUE THREAD

**Issue by mochi115** [matanki-saito/vic3jpadvmod#214]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![スクリーンショット_20221031_073117](https://user-images.githubusercontent.com/117048815/198909080-c8995530-8f6a-45e8-b434-07e036c31135.png)
## 問題の用語（必須）

電力建造物

## 英語版の表現（任意）

Power Structure

## 希望する変更（必須）

権力構造

## 変更の理由（必須）

誤訳の修正です。

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

無し

## MOD有無（必須）

無し

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by mochi115** [comment]
重複のため取り下げます
