### ISSUE TITLE
【修正提案】インテリゲンチャ

### ISSUE THREAD

**Issue by mochi115** [matanki-saito/vic3jpadvmod#215]
＜ゲームシステム用語＞

## 問題の用語（必須）

インテリゲンチャ

## 希望する変更（必須）

知識人/知識階級

## 変更の理由（必須）

他の利益団体の名前と比べて浮いているため

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

無し

## MOD有無（必須）

無し

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Via-GitHub** [comment]
同意します。インテリゲンチャ自体は知識階級を示す包括的な単語として広く使われており、元となった「インテリゲンチャ」という綴り（とそのニュアンス）を翻訳時に残す必要はないと思われます。

**Comment by kecy3** [comment]
ゲーム内の説明でも
「文学、芸術、音楽、演劇で国家のトレンドを牽引する知識階級です。」
とあるので、私も知識階級にしてしまってよいかと思います。

**Comment by Zousuikakka** [comment]
知識人で修正
