### ISSUE TITLE
【修正提案】敬虔

### ISSUE THREAD

**Issue by mochi115** [matanki-saito/vic3jpadvmod#216]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![スクリーンショット_20221031_063300](https://user-images.githubusercontent.com/117048815/198914103-1ea99521-c448-413a-ad61-b2726c3968a5.png)

## 問題の用語（必須）

敬虔

## 英語版の表現（任意）

Devout

## 希望する変更（必須）
敬虔な信者/信者/聖職者/宗教団体

## 変更の理由（必須）

敬虔だけでは団体の名前として違和感があるため。

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

無し

## MOD有無（必須）

無し

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by WoodlandsGitHub** [comment]
ヤカ族は、Ndzambyaphuunguを創造神とする伝統宗教を信仰している一方、お祭りや儀式は先祖の霊に志向したものらしいです。シャーマニズムに近いのかな…

**Comment by Via-GitHub** [comment]
組織化された宗教の構成員ではない、ローカルの宗教に熱心な人々の集団といったニュアンスでしょうか。端的に表すのはちょっと難しいですね。個人的には「信仰者」「宗徒」かな…？

**Comment by kecy3** [comment]
翻訳ファイルの敬虔の説明には「大多数の宗教において最も献身的な信者であり、そのことを道徳的ならびに政治的知啓の最良の源であると見なしています。」とありますね。
カトリック教会のようなメジャーどころから異教シャーマンなんてマイナーっぽそうな宗教関係の利益集団が存在する中、それらとの違いを表すのが難しいですよね。
（自分用に作っている適当翻訳では狂信者としましたが、敬虔とは逆の悪い奴感がすごい）
ほかの宗教団体よりも強力な信奉をしているという意味がニュアンスから伝わりそうという意味で、変更案にもある「敬虔な信者」あたりなのかなぁと個人的には思いました。

**Comment by Via-GitHub** [comment]
そういう記述があったとは…しっかり確認せずいい加減なことを言ってはいけないと自戒。英語でもThe most dedicated followers of the majority religion（（その国の）主流宗教で最もひたむきな人々）とのことで、民間信仰であるかは関係なさそうです。一段強い信仰であることの明瞭化、中立的ニュアンスで狂信に対応する表現が欲しいところですが、「敬虔な信者」が最大公約数的な気はしますね。「篤信家/者」「帰依者」あたりも選択肢かもしれませんが、ここでは少々場違い？
