### ISSUE TITLE
【文字数調整および校正提案】都市施設新規追加「5はShift+をクリック」

### ISSUE THREAD

**Issue by WoodlandsGitHub** [matanki-saito/vic3jpadvmod#218]
## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/29177147/198942285-e1be3aa4-032d-42f9-8b66-418db6cf491b.png)

## 問題のツールチップ（必須）

都市施設を新規追加するリストから各施設をマウスオーバーした際のツールチップ

## 問題の表現（必須）

クリックで1レベルをキューに入れる、5はShift+をクリック、10はCtrl+をクリック

## 問題箇所の英文（任意）

EXPAND_BUILDING_MODIFIERS_INSTRUCTIONS:2 "#instruction Click to queue 1 level, $SHORTCUT_KEY_MOD_shift$Click for $SHIFT_NUM_LEVELS$, $SHORTCUT_KEY_MOD_ctrl$Click for $CTRL_NUM_LEVELS$#!\n#instruction $SHORTCUT_KEY_MOD_alt$Click to queue at the top of the Construction Queue"

## 希望する変更（必須）

クリックで1レベル分をキューに入れる、Shift+クリックで5、Ctrl+クリックで10
Alt+クリックで建設キューの先頭に入れる

 EXPAND_BUILDING_MODIFIERS_INSTRUCTIONS:2 "#instruction クリックで1つ分をキューに入れる、$SHORTCUT_KEY_MOD_shift$クリックで$SHIFT_NUM_LEVELS$、$SHORTCUT_KEY_MOD_ctrl$クリックで$CTRL_NUM_LEVELS$#!\n
#instruction $SHORTCUT_KEY_MOD_alt$クリックで建設キューの先頭に入れる"

## 変更の理由（必須）

1行目の「ク」だけ改行されて具合悪いので文字数調整
ついでに校正も

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

日本語改善MOD
Switch Languages

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
![image](https://user-images.githubusercontent.com/29382778/199733632-3f223479-02ce-4275-986e-aa641c50284c.png)
![image](https://user-images.githubusercontent.com/29382778/199733660-9c68f980-f095-4345-9bc5-15df1d2610ea.png)

**Comment by clamm0363** [comment]
上記のように修正しました。

クローズします。

**Comment by clamm0363** [comment]
「10分をキューに入れる」とタイポしていた部分を「10レベル分をキューに入れる」と修正しました。
