### ISSUE TITLE
【修正提案】外交画面、関係悪化相手のマウスオーバー時のポップアップ

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#219]
## スクリーンショット（必須）

![20221030213655_1](https://user-images.githubusercontent.com/42710893/198967094-850f9744-25c5-43a2-9871-8d238cfeb8f4.jpg)

## 問題のあるインターフェイス（必須）

外交画面、関係悪化相手の国旗マウスオーバー時のポップアップ

## 問題のテキスト（必須）

DIPLO_PACT_RELATIONS_CHANGE_NEG:2 "#b [concept_relations]悪化#!に向けた取り組みの進捗度は `$PROGRESS|2%v$`（$PROGRESS_DAILY|%=v2$/日）であり、`$DATE|v$` 日で相互の[concept_relations]が #N #b -1#!#! 変化します。"

`$DATE|v$`には18○○年△月◇日のように、関係値が変化する日付が入る
なお、関係改善の場合も全く同様の文章がある

（参考）
DIPLO_PACT_RELATIONS_CHANGE_POS:2 "#b [concept_relations]改善#!に向けた取り組みの進捗度は `$PROGRESS|2%v$`（$PROGRESS_DAILY|%=v2$/日）であり、`$DATE|v$` 日で相互の[concept_relations]が #P #b +1#!#! 変化します。"

## 希望する変更（必須）

 "#b [concept_relations]悪化#!に向けた取り組みの進捗度は `$PROGRESS|2%v$`（$PROGRESS_DAILY|%=v2$/日）であり、`$DATE|v$`**には**相互の[concept_relations]が #N #b -1#!#! 変化します。"　等

## 変更の理由（必須）

変数部分との接続がおかしいため。

## ゲームバージョン（必須）

1.0.3

## DLCの有無（必須）

なし

## MODの有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
該当キー
```DIPLO_PACT_RELATIONS_CHANGE_POS

#b 遂行中の#b [concept_relations]改善#!は$PROGRESS|2%v$（$PROGRESS_DAILY|%=v2$[Nbsp]/[Nbsp]日）の進捗度です。\n$DATE|v$に相互の[concept_relations]が#P #b +1#!#!変化します。```

**Comment by matanki-saito** [comment]
```#b 遂行中の[concept_relations]悪化#!は$PROGRESS|2%v$（$PROGRESS_DAILY|%=v2$/日）の進捗度です。\n$DATE|v$に相互の[concept_relations]が#N #b -1#!#!変化します。```

**Comment by matanki-saito** [comment]
以上のように修正しました。

クローズします
