### ISSUE TITLE
アジアの都市名

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#220]
## 問題の固有名詞と希望する変更（必須）

ポートアーサー：旅順
ハバロフスク：ハバロフカ
ベロゴロスク：ベロゴルスク
ホヅホ：ホジョ

連雲港：海州
蘇州：宿州
南洋：南陽
咸陽：襄陽
インメン：荊門
トゥーユン：都勻
ゴウルオ：果洛

シュヴィー・クーレン：シヴェー・フレン
ディングァンイン：定遠営
バヤンコーンゴール：バヤンホンゴル
コルゴ：ホルゴ
ドルツバ：ドルージュバ

ンガリ：ガリ
ドロンパ：ドンパ

クリャブ：クリャーブ
アンイ：アイニ
ナリン：ナルン
アルマティンスク：アルマチンスク
ザーケント：ジャルケント
パブロダル：パヴロダル
ザナオゼン：ジャナオゼン
マリー：マル
トルクメナバット：テュルクメナバート

ランカラン：レンキャラン
エリザベトポリ：エリザヴェトポリ
アレクサンドロポル：アレクサンドロポリ

ジレスン：ギレスン
ヨズガート：ヨズガト
シヴァス：スィヴァス
シノプ：スィノプ
ケンゲリ：チャンクル
エレグリ：エレーリ
バリケシール：バルケスィル
クルク・クルス：クルク・キリセ
ミジェ：ミディエ
アイディン：アイドゥン
アフヨン：アフィヨン
リマソル：リマソール
メルシン：メルスィン
マラチャ：マラティヤ

ラス・アルアイン：ラース・アル＝アイン
タルトゥス：タルトゥース
ハマ：ハマー
サラミヤ：サラミーヤ
デイル・エル・カマール：デイル・エル＝カマール
サルト：アッ＝サルト
アル・フダイダ：アル＝フダイダ
アル・ムカラ：アル＝ムカッラー
サララー：サラーラ
ダーラーン：ザフラーン
ブレイダ：ブライダ
ダンマン：ダンマーム
ハイル：ハーイル
カーティフ：カティーフ
クト：クート
アマラ：アマーラ
ナシリア：ナーシリーヤ
バグダッド：バグダード
モスル：モースル

タブリズ：タブリーズ
スフィアン：スフィヤン
マラゲ：マラーゲ
アルダビル：アルダビール
ロレスタン：ロレスターン
イラム：イーラーム
アーヴァズ：アフヴァーズ
バンダー・マーシャー：バンダレ・マーフシャフル
デズフル：デズフール
コラムシャー：ホッラムシャフル
マスジェド・ソレイマン：マスジェデ・ソレイマーン
ブシェー：ブーシェフル
ヤスジ：ヤースージュ
カンガン：カンガーン
ベベハン：ベフベハーン
ハッジバード：ハージアーバード
バンダー・アッバス：バンダレ・アッバース
ジャスク：ジャースク
バンダー・エシャラク：バンダレ・チャーラク
イスファハン：エスファハーン
カシャン：カーシャーン
コーメイン：ホメイン
セムナン：セムナーン
サリ：サーリー
カムシャー：ガーエムシャフル
シャルス：チャールース
ゴナバッド：ゴナーバード
ボンジヌルド：ボジュヌールド
イランシャー：イーラーンシャフル
チャバハール：チャーバハール
ラスク：ラースク
ザラバード：ザラーバード

グワダール：グワーダル
オルマラ：オルマーラ
ヘラット：ヘラート
ガーズニ：ガズニー
フェイザバード：ファイザーバード
コーハート：コハート
ペシャワール：ペシャーワル
ムルタン：ムルターン
バハワルプール：バハーワルプル
サクール：サッカル
アハメダバード：アフマダーバード
ポルバンダール：ポールバンダル
ラジコット：ラージコート
スラット：スーラト
ブージ：ブジ
コタ：コーター
アジメール：アジュメール
バレイリー：バレーリー
アリガー：アリーガル
アラーハバード：イラーハーバード
ゴラクプール：ゴーラクプル
カンプール：カーンプル
インドア：インドール
レワ：リーワー
ノヴァゴア：ノヴァ・ゴア
ドゥール：ドゥーレ
ラトナギリ：ラトナーギリー
ムナール：ムンナル
グダルール：クーダルール
ダンブラ：ダンブッラ
ヴァヴニヤ：バブニヤ
ヴェロール：ヴェールール
サレム：セーラム
ヴィシャハパルマン：ヴィシャーカパトナム
ブラマプール：ブラマプル
ヴィジャヤワダ：ヴィジャヤワーダ
マバブナガール：マフブーブナガル
アムラヴァティ：アムラーワティー
サムバルプール：サンバルプル
ブバネシュワル：ブバネーシュワル
プラバニ：プールバニ
バガルプール：バーガルプル
ムザファルプール：ムザッファルプル
ジャムシェドプル：ジャムシェードプル
ラングプル：ロンプール
クミラ：クミッラ
バリシャール：バリサル
アイザウル：アイゾール
ディブルガル：ディブルーガル
インファル：インパール
グワハティ：グワーハーティー

ミトキナ：ミッチーナー
プタオ：プーターオ
ピヤポン：ピャーポン
モニワ：モンユワ
マグウェイ：マグウェ
タンギー：タウンジー
クトカイ：クカイ
ケンタン：チャイントン
ラシオ：ラーショー

ナン：ナーン
ランパン：ランパーン
カンガイ：クアンガイ
クロン・バッタンバン：クロン・バタンバン
コンカエン：コーンケン
サムソンクラム：サムットソンクラーム
ポトサヌロク：ピッサヌローク
サラブリ：サラブリー
プラチュアップキリカーン：プラチュワップキーリーカン
マウラミーネ：モーラミャイン
チュンフォン：チュムポーン
ムアール：ムアル
テロカベトン：テロクベトン
バタビア：バタヴィア
バンドゥン：バンドン
ポンティアナク：ポンティアナック
カイエリ：カイェリ
ビーマ：ビマ

## 変更の理由（必須）
日本語では一般的ではない表記であるため。

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
