### ISSUE TITLE
【修正提案】製紙工場の製法－まっさらな紙

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#221]
＜ゲームシステム用語＞

## スクリーンショット（任意）

![20221031180035_1](https://user-images.githubusercontent.com/42710893/198971422-a7126238-c6c5-448a-bfa5-46941e3372fb.jpg)

## 問題の用語（必須）

まっさらな紙

## 英語版の表現（任意）

Paper Bleaching

## 希望する変更（必須）

「漂白紙」、あるいは単に「漂白」　等

## 変更の理由（必須）

まっさらな紙では意味がわかりにくい。

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

無し

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
起票ありがとうございます。漂白紙はBleached paperですが、こちらはPaper Bleachingなので、生産する紙ではなくそれを漂白する工程を指しています。そのため希望案のうち後者の漂白と改訳しました。これにてクローズします。
