### ISSUE TITLE
ideologyの固有名詞

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#222]
## 問題の固有名詞と希望する変更（必須）

ニヒリスト：虚無主義者
廃止論者：奴隷制廃止論者
奴隷商人：奴隷所有者
ジンゴイスト：好戦主義者
王政主義者：王党派
社会民主主義：社会民主主義者
コミュニスト：共産主義者
前衛主義：前衛主義者
エスノ・ナショナリズム：民族主義者
神権主義者：神政主義者
市場リベラル：市場自由主義者

パターナリズム：父権主義
ポピュリスト：大衆主義
軍政主義：権威主義
レッセフェール：自由放任主義
個別主義：独立主義
ジンゴイスト：好戦主義
プロレタリアン：プロレタリア
反奴隷主義：奴隷制反対派
奴隷制支持：奴隷制支持派
アグレアリアン：農本主義
スカラー・ジェントリー：紳士
司教主義：教皇主義
儒教主義：儒者
神道敬虔主義：神道原理主義
軍事独裁主義：カウディーリョ主義

## 変更の理由（必須）
日本語では一般的ではない表記であるため。

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
敬虔主義：敬虔は既にIssueが立っていたため、削除しました。

**Comment by ChiefIdeologue** [comment]
修正内容を変更
神道敬虔主義：国家神道派　→　神道原理主義

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
