### ISSUE TITLE
【修正提案】Plants プラント

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#223]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![plants](https://user-images.githubusercontent.com/50406316/198982933-0f24cff1-e520-49d7-9255-0ed579eeac79.png)

## 問題の用語（必須）
 pm_hydroelectric_plant:0 "水力発電プラント"
 pm_coal-fired_plant:0 "石炭燃焼プラント"
 pm_oil-fired_plant:0 "石油燃焼プラント"

## 英語版の表現（任意）
 pm_hydroelectric_plant:0 "Hydroelectric Plant"
 pm_coal-fired_plant:0 "Coal-Fired Plant"
 pm_oil-fired_plant:0 "Oil-Fired Plant"

## 希望する変更（必須）
水力発電所/石炭火力発電所/石油火力発電所

## 変更の理由（必須）
一般には〇〇発電所と訳すのが定訳であるため。
#105にてPower Plantsを電力プラント→発電所に改訳しており、それに表記を合わせたい。

## ゲームバージョン（必須）
1.0.3

## DLC有無（必須）
無し

## MOD有無（必須）
JapaneseLanguageAdvancedMod（更新: 10月31日 @ 7時10分）

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
提案通り変更してクローズします
