### ISSUE TITLE
【修正提案】州画面＞概要タブの「メキシコされています」

### ISSUE THREAD

**Issue by WoodlandsGitHub** [matanki-saito/vic3jpadvmod#224]
## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/29177147/199015458-9bc612d9-5570-47b3-b809-0b7ddb16620d.png)

## 問題のあるインターフェイス（必須）

植民地化されている州画面＞概要タブ

## 問題のテキスト（必須）

メキシコされています。

## 希望する変更（必須）

メキシコに植民地化されています。

## 変更の理由（必須）

テキストが何かの理由で切れてしまっているため

## ゲームバージョン（必須）

1.0.3

## DLCの有無（必須）

なし

## MODの有無（必須）

日本語改善MOD
Switch Languages

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
![image](https://user-images.githubusercontent.com/29382778/199730426-7a77e1f5-e3ad-4895-8639-f3335848d441.png)
![image](https://user-images.githubusercontent.com/29382778/199730487-5572ee80-0d18-456e-b9cb-714973ef1da5.png)

**Comment by clamm0363** [comment]
> [Concept('concept_colony', '$concept_colonized$')]\n[SelectLocalization(EqualTo_int32(State.GetNumColonizers,'(int32)1'),State.GetColonizers('STATE_REGION_COLONIZER_SINGLE_WIDGET'),State.GetColonizers('STATE_COLONIZER_WIDGET_ITEM'))]が入植中

**Comment by clamm0363** [comment]
上記のように修正しました。

クローズします。
