### ISSUE TITLE
戦線の彼我の戦力ポップアップ

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#225]
## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/37979626/199012380-067a1158-9e11-4a8b-8472-cd6664ab929d.png)

## 問題のツールチップ（必須）

戦争中の戦線に関するポップアップ

## 問題の表現（必須）
我々は$US|v$ユニット、相手は$THEM|v$持っています
我々は$US|v0$の平均的攻撃/防御、相手は$THEM|v0$持っています

## 問題箇所の英文（任意）
```$TAB$We have $US|v$ Units, they have $THEM|v$```
```$TAB$We have $US|v0$ Average Offense/Defense, they have $THEM|v0$```

## 希望する変更（必須）
```$TAB$我々はユニットを$US|v$、相手は$THEM|v$有しています```
```$TAB$我々の平均攻撃力/防御力は$US|v0$、相手は$THEM|v0$あります```

## 変更の理由（必須）
自然な表現にするため

## ゲームバージョン（必須）
1.0.1

## DLC有無（必須）
なし

## MOD有無（必須）
なし

**Comment by clamm0363** [comment]
> $TAB$我々のユニット数は$US|v$、相手は$THEM|v$です
> $TAB$我々の平均攻撃力/防御力は$US|v0$、相手は$THEM|v0$です

**Comment by clamm0363** [comment]
以上のように修正しました（斜体のTABはドル記号付きです）

クローズします。
