### ISSUE TITLE
軍艦の名称変更

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#226]
## 問題の固有名詞と希望する変更（必須）
装甲船：装甲艦
ドレッドノート：弩級戦艦
戦艦：超弩級戦艦

## 変更の理由（必須）
![image](https://user-images.githubusercontent.com/37979626/199059899-4e216a35-584a-40df-bc2c-c36996130947.png)
このように並んでいることを鑑みるとすべて「〇〇艦」とした方がすっきりしているため
※既に「軍艦」は「戦列艦」に修正済

## ゲームバージョン（必須）
1.0.1

## DLC有無（必須）
なし

## MOD有無（必須）
なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
起票の経緯はissue44にて

**Comment by matanki-saito** [comment]
## スクリーンショット

![image](https://user-images.githubusercontent.com/37979626/199059899-4e216a35-584a-40df-bc2c-c36996130947.png)
