### ISSUE TITLE
【修正提案】 利益団体の補正(Modifier)タブ

### ISSUE THREAD

**Issue by mochi115** [matanki-saito/vic3jpadvmod#227]
## スクリーンショット（必須）

![20221031084045_1](https://user-images.githubusercontent.com/117048815/199093747-f91db140-2192-4834-b367-746b4fa59668.jpg)

## 問題のあるインターフェイス（必須）

利益団体の補正(Modifier)タブ

## 問題のテキスト（必須）
時限補正(Timed Modifier)
補正記事(Modifier Entry)

## 希望する変更（必須）

一時的な補正
補正一覧/補正

## 変更の理由（必須）
日本語として自然ではないため。

## ゲームバージョン（必須）

1.0.3

## DLCの有無（必須）

なし

## MODの有無（必須）

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
ご提案どおり、「一時的な補正 / 補正一覧」と修正しました。

クローズします。
