### ISSUE TITLE
【未訳】Employment

### ISSUE THREAD

**Issue by clamm0363** [matanki-saito/vic3jpadvmod#228]
## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/29382778/199098984-485372d3-e1f8-443b-84fd-5e2b2868cc9c.png)

## 問題のツールチップ（必須）

施設の雇用者数ツールチップ

## 問題の表現（必須）

Employment

## 問題箇所の英文（任意）

[施設名] Employment

## 希望する変更（必須）

[施設名]の雇用状況

## 変更の理由（必須）

未訳のため。

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。
