### ISSUE TITLE
 【修正提案】 小作農 Peasants

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#229]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![peasant](https://user-images.githubusercontent.com/50406316/199136456-0a2338d8-52cf-4218-9115-66e334bdb3b3.png)

## 問題の用語（必須）
小作農

## 英語版の表現（任意）
Peasants

## 希望する変更（必須）
百姓

## 変更の理由（必須）
英語のPeasantsは土地を持たず地代を払っている小作農と小規模な土地を持つ自作農を両方含むが、日本語で小作人としてしまうと前者の土地なし農民だけを表してしまうことになり、訳語が対応していない。
現実でも日本の小作農は全農家中の2～3割程度だったらしいし、フランスのように革命で自作農が増えた国でもゲーム中では大量のPeasantsがいるので、小作人とするのは適していないように思える。
（参考）
https://kotobank.jp/word/%E5%B0%8F%E4%BD%9C%E8%BE%B2-500855
議論の結果、「百姓」となった。

## ゲームバージョン（必須）
1.0.3

## DLC有無（必須）
無し

## MOD有無（必須）
JapaneseLanguageAdvancedMod（更新: 11月1日 @ 7時10分）

**Comment by matanki-saito** [comment]
内部検討の結果、「百姓」にしました。

**Comment by matanki-saito** [comment]
上記のように修正しました。

クローズします。
