### ISSUE TITLE
【修正提案】イベント本文のタイポ（漢字変換ミス）

### ISSUE THREAD

**Issue by Syayan1** [matanki-saito/vic3jpadvmod#230]
## スクリーンショット（任意）
![ahenn](https://user-images.githubusercontent.com/117130842/199137905-ddbbcd44-1972-4639-8a5a-1914d6bfb8c1.png)

##　問題部分（タイトル・本文・選択肢）

本文

## 問題のイベントタイトル（必須）

アヘン中毒

## 問題のイベント本文（任意・抜粋可）

アヘン乗用車

## 希望する変更（必須・修正部分のみ）

アヘン常用者

## 変更の理由（必須）

漢字の変換ミス

## プレイ国家

フィリピン

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

テスト用フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Syayan1** [comment]
アヘン「乗用車」の漢字変換ミスを「常用者」に変更しました。

**Comment by Syayan1** [comment]
クローズします。
