### ISSUE TITLE
【修正提案】イベント「私か、彼らか」（全体修正）

### ISSUE THREAD

**Issue by Via-GitHub** [matanki-saito/vic3jpadvmod#231]
## 問題部分（タイトル・本文・選択肢）

タイトル:
私か、彼らか

本文:
[リーダー名]は、与党[団体名]のリーダーですが、連立パートナーである彼のとの間の妥協にうんざりしているようです。彼は彼のの協力者に命令に従うよう要求しており、さもなければ彼の[団体名]は変更について承認しないと言っています。

「それがリーダーの仕事ではないのか？私が主導し皆がそれに従う。簡単な話だと思うがね。もし彼らが統率したいのであれば彼ら自身のリーダーになっていただろうが、誰も自分にその素養があると考えてはいなかったのだろう。

私のやり方はこれすなわち成功への常道なり！」

選択肢:
何とも馬鹿げた物言いだ。
よかろう。[団体名]に指導権を任せようじゃないか。

## 問題のイベントタイトル（必須）

私か、彼らか

## 希望する変更（必須・修正部分のみ）

タイトル:
私か、**奴ら**か

本文:
[リーダー名]**は与党**[団体名]のリーダーですが、連立パートナーに**対するこれまでの譲歩にうんざりしています。彼は協力中の党へ指示に従うよう要求し、さもなければ彼らの改正案について**[団体名]**は今後いっさい賛同しないと言っています**。

「それがリーダーの仕事**というものだろう？私が率い、君らは従う**。簡単な話だと思うがね。**そんなに主導したければ御自身がリーダーになればよかったのだ。連中に指導者の資質があるなど誰も思わないだろうがね、奴ら以外**。

**私に従えない連中は出て行きたまえ、ということだ**！」

選択肢:
何とも馬鹿げた物言いだ。
よかろう。[団体名]に**牽引役**を任せようじゃないか。

## 変更の理由（必須）

タイトルのMe or Themを「彼ら」で訳すのは十分正しいですが、このイベントでは連立パートナーを示す「彼ら」と与党リーダーである「彼」で混同しやすく、対象をはっきりさせるため「奴ら」の方が良いのではと感じます。

"[リーダー名], leader of the ruling [団体名], has had enough of compromising with his coalition partners. He has demanded that either his collaborators follow his orders, or [団体名] will never approve of their changes. "の部分は原翻訳ではイベントの主人公がこれまで譲歩を続けてきた点や、今後連立パートナーから提出された法改正（their changes）に非協力を宣言している状況が分かりづらく、より明確な言葉遣いをしてはどうかと思います。
また[issue#210](https://github.com/matanki-saito/vic3jpadvmod/issues/210)での指摘にもありますが、政党間でのapproveは制度上の上下関係がなく、「承認」より「賛成」の方が相応しいかもしれません。

"I lead, you follow"の部分は一般論について言及しているためyouは「皆」で十分機能しますが、この場合は傲慢な話者が聞き手を含めた人々に従順であることを求めるニュアンスもある程度含まれているように考えられるため、とりあえず「君ら」としておきました（英語話者はこういう場合、やはりyouを具体的に目の前のあなたを起点としているイメージだと聞き及んでいるからでもありますが、非常に個人的な経験則ですし、不要そうであれば原文そのままで良いかと思います）。

"If they wanted to lead they could have been leaders themselves, but I guess no one else thought they could"の部分は全体的に不正確に訳されているようです。自身のリーダーではなく連立政権のリーダーになれという当てこすりであり、ここでのcould have beenは過去の可能性ではなく「なればよかったのに」といった遠い仮定だと考えます。またno one elseなので「彼ら以外は誰もリーダーの資格が彼らにはないと思っているだろう」という文になるかと思います。

"my way or the highway!" は「嫌なら帰れ」的な成句で、原翻訳はおそらく誤訳と思われます。It'sがついているため、「～、ということだ」のように前段のセリフを統括する形にする方がより原文のニュアンスに近いかもしれません。

"leading force"は指揮権といった具体的なものではなく、牽引役や主導役などの訳語がベターだと思われます。

## プレイ国家

日本（おそらく汎用イベント）

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

有・ランダムイベントのためMODを外しての確認ができませんでした
Dense Trade Routes Tab, Dense Market Details, JapaneseLanguageAdvancedMod, Universal Names, Japanese Namelist Improvement

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
丁寧な考察、ありがとうございました。検討の上、下記のように校正いたしました。

タイトル「リーダーはひとり」
It's Me, or Themは「私か、奴か」で翻訳としては間違っていないのですが、要は「二者択一」のことを言っています。暗に、「当然私を選ぶだろう」という意思が込められたものです。直訳ではこのニュアンスが出せないので、校正訳のようにしました。

> [人名], leader of the ruling [党名], has had enough of compromising with [his] coalition partners. [He] has demanded that either [his] collaborators follow [his] orders, or [与党] will never approve of their changes.

この部分は代名詞が多くてややこしいのですが、二行目の[He]は変数的に「他党の党首」を指しており、「[他党の党首]が[私=Me]に要求したことは、[他党]を[私]の指示に従わせるか、それができないのなら、[与党]は何を変えようとしても賛同を得られない」という意味になっています。

（ここで登場する与党党首の人物は変数内でsmug_leaderと書かれており、独善的なタイプです。調整にうんざりしていたのは、そもそも他党との折衝などせずに一人で決めてしまいたいからです。一方、他党の党首にはmeticulous_leaderが使われており、細かなところまでこだわるタイプです）

よって、この部分は次のように校正しました。

> 与党[SCOPE.gsInterestGroup('smug_ig').GetName]の党首[SCOPE.sCharacter('smug_leader').GetFullName]は、連立を組む他党との調整にうんざりしています。[SCOPE.sCharacter('smug_leader').GetHerHis]は他党の党首から、「我々の協力が無ければ君のやりたいことは何一つ実現できないのだから、君もちゃんと協力したまえ」と要求されているからです。

次の部分

> "That's what leaders are for, right? I lead, you follow. Sounds rather simple to me. If they wanted to lead they could have been leaders themselves, but I guess no one else thought they could.
> 
> It's my way or the highway!"

この部分は基本的にご提案に沿ったものとしていますが、no one else thought they couldは「（私のほかにはリーダーになろうとしたものはいない」という意味だと解釈しました。よって校正訳は次のようになります。

> 「それがリーダーの仕事というものだろう？私が率い、君らは従う。簡単な話だと思うがね。そんなに主導したかったのなら、君らがリーダーになればよかったのだ。だが、そんな奴は一人もいなかったように思うがね。\n\n私に従えないなら、勝手にどこへでも行くといい！」

選択肢に関しては、ご提案のとおりに修正しました。

**Comment by clamm0363** [comment]
issueをクローズします。

**Comment by Via-GitHub** [comment]
変数をしっかり見ないと汲み取れない状況もあるとは、これは完全な盲点…。no one elseの部分も「私」を起点とした方がより筋が通っていますね。素晴らしい訂正ありがとうございました。
