### ISSUE TITLE
【修正提案】政治レンズ－利益団体のツールチップ

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#232]
## スクリーンショット（必須）

![20221030161827_1](https://user-images.githubusercontent.com/42710893/199168305-5acd6e65-81ef-408d-89a1-df47f5a0de91.jpg)

## 問題のツールチップ（必須）

政治レンズで利益団体マウスオーバー時のツールチップ

## 問題の表現（必須）

この利益団体はその影響力は20%以上ですにより、強力とみなされています。

POWERFUL_IG_DESC:0 "\nこの[concept_interest_group]は[INTEREST_GROUP.GetInfluenceReason]により、[concept_powerful]とみなされています"

## 問題箇所の英文（任意）

POWERFUL_IG_DESC:0 "\nThis [concept_interest_group] is considered [concept_powerful] because [INTEREST_GROUP.GetInfluenceReason]"

## 希望する変更（必須）

この利益団体は影響力が20%以上であることで、強力とみなされています。　等

[INTEREST_GROUP.GetInfluenceReason]が呼んでいる部分の修正が必要

## 変更の理由（必須）

変数との接続部分が不自然なため

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
```[強力]
POWERFUL_REASON_ABOVE_THRESHOLD: [concept_clout]が#variable [GetDefine('NPolitics', 'POWERFUL_IG_THRESHOLD')|%0]#!を超えている

POWERFUL_REASON_ABOVE_CUTOFF: [concept_clout]が#variable [GetDefine('NPolitics', 'POWERFUL_IG_CUTOFF')|%0]#!以上である

POWERFUL_IG_DESC: \n[INTEREST_GROUP.GetInfluenceReason]ため、この[concept_interest_group]は[concept_powerful]とみなされています```

**Comment by clamm0363** [comment]
> [非主流派]
> MARGINALIZATION_REASON_BELOW_THRESHOLD: [concept_clout]が#variable [GetDefine('NPolitics', 'MARGINAL_IG_THRESHOLD')|%0]#!未満である
> 
> MARGINALIZATION_REASON_REVOLTING: #variable [INTEREST_GROUP.GetCountry.GetName]#!に対して反乱を起こしている
> 
> MARGINAL_IG_DESC: \n[INTEREST_GROUP.GetInfluenceReason]ため、この[concept_interest_group]は[concept_marginalized]とみなされています

**Comment by clamm0363** [comment]
> [強力]
> POWERFUL_REASON_ABOVE_THRESHOLD: [concept_clout]が#variable [GetDefine('NPolitics', 'POWERFUL_IG_THRESHOLD')|%0]#!を超えている
> 
> POWERFUL_REASON_ABOVE_CUTOFF: [concept_clout]が#variable [GetDefine('NPolitics', 'POWERFUL_IG_CUTOFF')|%0]#!以上である
> 
> POWERFUL_IG_DESC: \n[INTEREST_GROUP.GetInfluenceReason]ため、この[concept_interest_group]は[concept_powerful]とみなされています

**Comment by clamm0363** [comment]
上記のように修正しました。

クローズします
