### ISSUE TITLE
【修正提案】フィルム（Film）（技術の名称）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#233]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![film](https://user-images.githubusercontent.com/42687608/199171425-254c42c9-7112-4304-af3b-9cab347581eb.jpg)

## 問題の用語（必須）
フィルム

## 英語版の表現（任意）
Film

## 希望する変更（必須）
映画

## 変更の理由（必須）
アイコンからも説明文からも映画を意味していると思われるため。

## ゲームバージョン（必須）
1.0.3

## DLC有無（必須）
- Victoria II Remastered Soundtrack
- American Buildings Pack

## MOD有無（必須）
- 自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
「活動写真」に確定し、修正を完了しました。
