### ISSUE TITLE
【修正提案】悪名（Notorious）（Imfamyの段階の名称）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#234]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![Notorious](https://user-images.githubusercontent.com/42687608/199172011-48b9c4df-4e50-4643-9898-133c8917add7.jpg)

## 問題の用語（必須）
悪名

## 英語版の表現（任意）
Notorious

## 希望する変更（必須）
外道 / 悪辣 / 無法 / 非道 など

## 変更の理由（必須）
外交評判の悪さを意味する用語Infamyの訳が「悪名」であり、重複しているため。
Infamyの各段階は次の通りで、これらの訳の妥当性も併せて議論したい。
- Reputable（良好）
- Infamous（不信）
- Notorious（悪名）
- Pariah（疎外）

## ゲームバージョン（必須）
1.0.3

## DLC有無（必須）
- Victoria II Remastered Soundtrack
- American Buildings Pack

## MOD有無（必須）
- 自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Via-GitHub** [comment]
原文でもinfamyとinfamousで類似語だったりで、完全なニュアンスの汲み取りは難しそうですね。
Infamy: ここを「批判」等にできれば「悪」が被らずに済むメリットがありますが…前作から悪名と呼ばれていた部分なので変えづらいようにも。
Reputable: 悪名が良好とは一体…という気もしますし、「好評」「信用」「信頼」あたりでも？
Notorious: 無法か、悪辣でしょうか。できれば自身の状態ではなく評判がひどく悪いことを示す言葉を当てたい気もしますが、端的なのが思いつかない。「糾弾」？
Pariah: 国際的パーリアの文脈において疎外と表現されることが多く、ここはこのままでいいかもしれません。あるいは「孤立」が多少分かりやすいか。
Notoriousで悪名が被ってる件を除けば誤訳とまでは行ってないと思われますし、非MOD導入環境との互換性を考慮すると変更は最小限な方が良い？

**Comment by matanki-saito** [comment]
非常に建設的かつ具体的なご意見ありがとうございます。参考にさせていただきます。

**Comment by Zousuikakka** [comment]
なし/不評/顰蹙/孤立　で修正しました
