### ISSUE TITLE
【修正提案】イベント選択肢のツールチップ－補正の獲得

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#235]
## スクリーンショット（必須）

![FgdTGCPVsAEwJTU](https://user-images.githubusercontent.com/42710893/199177030-81ef0cdf-158e-4771-8aa9-bfc225d4162e.jpg)

## 問題のツールチップ（必須）

イベント選択肢のツールチップー補正の獲得文章

## 問題の表現（必須）

スクショの例だと
清はアヘン戦争の敗北（期間：19年の期間）を得ます。

## 希望する変更（必須）

清はアヘン戦争の敗北（期間：19年）を得ます。

## 変更の理由（必須）

「期間」が重複しているため

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
ご提案どおりに修正しました。

クローズします。
