### ISSUE TITLE
他国から外交戦：揺さぶりをかける　を受けた時のポップアップの文章

### ISSUE THREAD

**Issue by flowlanss** [matanki-saito/vic3jpadvmod#236]
## スクリーンショット（必須）

![image](https://user-images.githubusercontent.com/54560025/199186225-d26c3310-d1f8-480d-a0eb-05d199a320ab.png)

## 問題のあるインターフェイス（必須）

他国からの外交戦：揺さぶりをかけるを受けた時のポップアップ

## 問題のテキスト（必須）

[国旗]イギリスは、進行中の外交戦において、我が国が加勢することを条件に清戦争賠償金に向けた戦争目標を申し出ています。

## 希望する変更（必須）

[国旗]イギリスは、清に対して進行中の外交戦において我が国が加勢するならば、戦争賠償金の戦争目標を提供すると申し出ています。(要検証)

## 変更の理由（必須）

清を指す変数後にスペースがなく文が一部消えているようだ。また文章としてよく意味が通らないので通るように修正する。
英語原文：[Proposal.GetActor.GetName] offers us a [concept_war_goal] to #variable [Proposal.GetDiplomaticPlay.GetSwayOfferWarGoal(Proposal.GetActor.Self).GetName]#! if we will back them in the ongoing [concept_diplomatic_play].

## ゲームバージョン（必須）

1.0.3

## DLCの有無（必須）

Victoria II Remastered Soundtrack
American Buildings Pack

## MODの有無（必須）

JapaneseLanguageAdvancedMod

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by flowlanss** [comment]
他issueで揺さぶりを変更しているようなので　揺さぶりをかける　というのにも修正が必要か。別のissueにするべきか

**Comment by flowlanss** [comment]
「清 戦争賠償金」のまとまりで一変数となっているので自然な訳にするのが難しくなっている。
「イギリスは、進行中の外交戦において、我が国が加勢することを条件に清 戦争賠償金の戦争目標の提供を申し出ています。」とするか、

「～以下の戦争目標の提供を申し出ています。\n清 戦争賠償金」とするのがよいか。

**Comment by flowlanss** [comment]
「イギリスは、進行中の外交戦において、我が国が加勢することを条件に以下の戦争目標の提供を申し出ています:清 戦争賠償金」として修正。\nはParaTranzのタグ比較に引っかかるのが嫌でなしに。もしかしたら国名の長さによっては微妙になる？要検証
