### ISSUE TITLE
非ランダム人物名の表記修正

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#237]
## 問題の固有名詞と希望する変更（必須）

ドスト：ドースト
フォン・ヴィンディッシュ・グラッツ：フォン・ヴィンディシュ＝グレーツ
エルツァーツォグ：エルツヘルツォーク
ツァーリンゲン：ツェーリンゲン
アンドレ・ランベルト：アンドレ＝ランベール
エヴァイン：エヴァン
レオポルド：レオポルド1世
オブ・ザクセン・コーブルク・ゴータ：ド・サクス＝コブール・エ・ゴータ
プリッセ：プリス
バラオ：バラオン
デ・アルカンターラ・ベルガルデ：デ・アルカンタラ・ベルガルデ
オラフ：オーラヴ
ホイットワース・アイルマー：ホイットワース＝アイルマー
ブルゴーニュ：バーゴイン
ソマーセット：サマセット
サー・ジョージ：ジョージ
テオドロス二世：テオドロス2世
アシャード：アシャール
ジーン・バプティステ：ジャン・バティスト
ベルナルド・ピエール：ベルナール・ピエール
マグナン：マニャン
バラゲイ：バラゲ
バラゲイ・ディリエ：バラゲ・ディリエ
ジャッケス・ルイス：ジャック・ルイ
レイル：レイユ
バートランド：ベルトラン
クラウセル：クローゼル
イオアニス：イオアンニス
ジーン・ピエール：ジャン＝ピエール
フォン・ドルンベルグ：フォン・デルンベルク
ヴィルヘルム二世：ヴィルヘルム2世
フォン・ヘッセ・カッセル：フォン・ヘッセン＝カッセル
プリンス・フリードリッヒ：フリードリヒ
メーラブ二世：メフラブ2世
ディ・ブルボン・パルマ：ディ・ボルボーネ＝パルマ
マーティン・ペルフェクト：マルティン・ペルフェクト
フランセスコ四世：フランチェスコ4世
ハプスブルク・エステ：ハプスブルク＝エステ
ペトロヴィチ・ニジェゴス：ペトロヴィチ＝ニェゴシュ
デイヴィド・ヘンドリク：ダヴィト・ヘンドリク
フランス・デイヴィド：ダーヴィド・フェレンツ
ヘンドリク・マーカス：ヘンドリク・メルクス
カレル・ベルンハルド：カレル・ベルンハルト
ファン・ザクセン・ワイマール・アイセナハ：ファン・サクセン＝ヴァイマル＝アイセナフ
ジーン・フランソワ：ジャン＝フランソワ
ド・レゴ・バレット：ド・レゴ・バーレト
フォン・クラウセンネック：フォン・クラウゼネック
フォン・マフリング：フォン・ミュフリンク
フォン・コロンブ：フォン・コロンプ
フォン・グロルマン：フォン・グロールマン
ルール：リューレ
カール・フリードリッヒ：カール・フリードリヒ
ツゥ・ドーナ・シュロビッテン：ツー・ドーナ＝シュロービッテン
フリードリッヒ・グラフ：フリードリヒ・グラーフ
フォン・ノイマン・コーセル：フォン・ノイマン・コーゼル
フォン・レイハー：フォン・ライハー
クフラポヴィツスキー：フラポヴィツキー
ニコレイ：ニコライ
ムラフヨフ・カルスキー：ムラヴィヨーフ＝カールスキー
カーロ・アルベルト：カルロ・アルベルト
サヴォイ：サヴォイア
エマヌエレ：エマヌエーレ
バヴァ：バーヴァ
ド・ソナズ：デ・ソナス
アゴスティノ：アゴスティーノ
シオード：キオド
アレクサンダー：アレクサンダル
カラドルデヴィチ：カラジョルジェヴィチ
プリンス・レオポルド：レオポルド
ブルボン・両シチリア：ボルボーネ・ディ・シチリア
ヨハン・ペーター：ユハン・ペーテル
アフ・ビルベルグ：アーヴ・ビルベルグ
レシド・メフメド：レシト・メフメト
メフメド・ナミク：メフメト・ナムク
アブドゥルケリム：アブデュルケリム
レオポルド二世：レオポルド2世
ハプスブルク・トスカーナ：ダスブルゴ＝トスカーナ
エドムンド・P：エドモンド・P
ガイネス：ゲインズ
ヴィルヘルム一世：ヴィルヘルム1世
ゴードン・レノックス：ゴードン＝レノックス
ジョセフ・アントン：ヨーゼフ・アントン
フォン・マッフェイ：フォン・マッファイ
ルードヴィヒ一世：ルートヴィヒ1世
フォン・ギース：フォン・ギーゼ
ルードヴィヒ・ゲオルグ：ルートヴィヒ・ゲオルク
ウィンター：ヴィンター
マクルーリン：マクローリン
ルシア：リュシエ
ムハンメド・ベッロ：ムハンマド・ベッロ
フォン・コロブラト・リーブスタンスキー：フォン・コロヴラト＝リープシュタインスキー
ヴィンセンツ：ヴィンツェンツ
ミラビュー：ミラボー
トマス・ジェファソン：トーマス・ジェファーソン
ウヴァロフ：ウヴァーロフ
ヘルゼン：ゲルツェン
オスマンオグル：オスマンオウル
コカ・フスレフ：コジャ・ヒュスレヴ
ムスタファ・レシード：ムスタファ・レシト
ド・ブログリー：ド・ブロイ
ジャン・ド・デュー：ジャン＝ド＝デュー
フェルディナンド・フィリッペ：フェルディナン・フィリップ
ルイス・ナポレオン：ルイ＝ナポレオン
ギヨーム・ヘンリー：ギヨーム・アンリ
ヴィットーリオ・エマヌエレ：ヴィットーリオ・エマヌエーレ
イザベル：イサベル
アンキロン：アンツィロン
フォン・ヴィリヒ・ウンド・ロットゥム：フォン・ヴィリヒ・ウント・ロットゥム
マリア・ルイーサ：マリア・ルイーザ
カーロ・ルドヴィーコ：カルロ・ルドヴィーコ
スタルク：シュターク
フォン・ナッサウ・ヴァイルブルク：フォン・ナッサウ＝ヴァイルブルク
アスカニール：アスカーニエン
ジョセフ・ルードヴィヒ：ヨーゼフ・ルートヴィヒ
フォン・アルマンスペルグ：フォン・アーマンスペルク

ムハンマド・アリ：ムハンマド・アリー
アル・アラウィーヤ：アル＝アラウィーヤ
アル・ハシミ：アル＝ハーシミ
アブド・アル・ムッターリブ：アブド・アル＝ムッタリブ
サウド：サウード
アル・サウド：アル＝サウード
アル・マンスール・アリ：アル＝マンスール・アリー
アル・カシム：アル＝カーシム
アン・ナシール・アブダラー：アン＝ナースィル・アブドゥッラー
トゥワイニ：スワイニー
カーリファ：ハリーファ
カジャール：ガージャール
ミルザ・アカシ：ミールザー・アカーシ
バロホ：バローチ
マー・シャー：ミール・シャー
タルプール：タルプル
サヤジ・ラオ：サヤージー・ラーオ
ゲクワド：ガーイクワード
バラクザイ：バーラクザイ
コカンド：コーカンド
シャー・アリ：シール・アリー
アラー・カリ・バハダール：アッラーフ・クリ・バハドゥール
マン・シング：マーン・シング
ナシール・ウド・ディン・ハイダール：ナーシルッディーン・ハイダル
マングード：マンギト
ムザッファール・アル・ディン：ムザッファルッディーン
アブドゥルメシド：アブデュルメジト
ラグホズイ：ラグージー
ブホンサーレ：ボーンスレー
ナシール・ウド・ダウラー：ナーシル・ウッダウラ
アフザル・ウド・ダウラー：アフザル・ウッダウラ
アサフ・ジャー：アーサフ・ジャー
ギャルシェン：ギャルツェン
ギャツソ：ギャツォ
ミン・マン：ミンマン
ティエウ・トリ：ティエウチ
アリ・イスカンダール：アリー・イスカンダル
アル・アラウィ：アル＝アラウィー
アブデルカデール：アブド・アルカーディル
サーレ・セラッシー：サーレ・セラシエ
ハイル・メレコット：ハイレ・メレコト

ホセ・ギャスパー：ホセ・ガスパル
ド・オルベゴソ：デ・オルベゴソ
ド・パウラ・サンタンデール：デ・パウラ・サンタンデール

ボルキアー：ボルキア
アル・アッバス：アル＝アッバース
シャー・アリ：シール・アリー
ガイ・ヴィクトール：ギー＝ヴィクトル
デュプラ：デュペレ
バウディン：ボーダン
アントニオ・ロペズ：アントニオ・ロペス
ド・サンタ・アンナ：デ・サンタ・アナ
エンジェルベルタス：エンヘルベルトゥス
フェルディナンド二世：フェルディナンド2世
カーロ・アルベルト一世：カルロ・アルベルト1世
シューブリック：シュブリック

アブドゥケリム・ナディール：アブデュルケリム・ナディール
ロバート・チャールス：ロバート・チャールズ
ジョージ・アウグスタス：ジョージ・オーガスタス
ヨツェフ・フランツ・カール：ヨーゼフ・フランツ・カール
ウィーログロウスキー：ヴィエログウォフスキ
シャーナー：チャーナー
タコン・イ・ロシーク：タコン・イ・ロシケ
エルネスト・アウグストゥス：アーネスト・オーガスタス
シャルル・マリー・ナポレオン：シャルル＝マリー＝ナポレオン
ジーン・クレティエン：ジャン・クレティアン
リビングストーン：リヴィングストン
コズロウスキー：コズウォフスキ
マクロヴィッツ：マクウォヴィチ
ランコウスキー：ワンコフスキ
ブコヴィッツ：ブコヴィチ
ドルジマラ：ドゥジマワ
神聖大公アルブレヒト：大公アルブレヒト
フォン・ハプスブルク・ロートリンゲン：フォン・ハプスブルク＝ロートリンゲン
アルベルト・フローレント・ヨセフ：アルベール＝フローラン＝ジョゼフ
アンドレアス・ヴィクトール：アンドレアス・ヴィクトル
ムハンマド・アリムデｨｰン：ムハンマド・アリームッディーン
ムハンマド・ジャラーロッディーン：ムハンマド・ジャラールッディーン
アジ・ムハンマド・サレフデｨｰン：アジ・ムハンマド・サレーフッディーン
アブドゥル・ジャリル・シャイフデｨｰン：アブドゥル・ジャリール・シャイーフッディーン
アル・カーリファ：アル＝ハリーファ
プリンス・カール・テオドール：カール・テオドール

レスペス：レスペ
ジョルジュ・エルネス：ジョルジュ・エルネスト
フランソワ・アシレ：フランソワ・アシル
プリンスジ・ルイス：ルイス
サー・アレクサンダー：アレクサンダー
バーデン・ポーウェル：ベーデン＝パウエル
プリンス・ジョージ：ジョージ
プリンス・フリードリッヒ・カール：フリードリヒ・カール
ボロエヴィク：ボロイェヴィッチ
フランツ・エドアルド：フランツ・エドゥアルト
神聖大公フリードリッヒ：大公フリードリヒ
オスマン・ヌリ：オスマン・ヌーリ
メフメド・アリ：メフメト・アリー
ディアズ：ディアス
ソラノ・ロペス：ソラーノ・ロペス
フランツ・コンラード：フランツ・コンラート
大公ニコラス：大公ニコライ
ランゲル：ヴラーンゲリ
織部：オリベ
ヨアキム・ジョゼ：ジョアキン・ジョゼ
グラッドストーン：グラッドストン
プリンス・ゴング：奕訢

アウクランド：オークランド
ダビッドソン：デイヴィッドソン
オブ・オーストリア・エステ：ダスブルゴ＝エステ
フィッツジェイムス：フィッツジェームズ
コーンウォリス・ウエスト：コーンウォリス＝ウェスト
ハンフリース・オーウェン：ハンフリーズ＝オーウェン
ロイド・モスティン：ロイド＝モスティン
ルウェリン・ジョーンズ：ルウェリン＝ジョーンズ
プライス・グウィン：プライス＝グウィン
ジョバンニ・マリア：ジョヴァンニ・マリーア
マルティム・フランシスコ：マルティン・フランシスコ
リベイロ・デ・アンドラーダ：リベイロ・デ・アンドラダ
ダ・クンハ・バルボサ：ダ・クーニャ・バルボーザ
デ・サウザ・エ・オリヴェイラ・コーティニョ：デ・ソウザ・エ・オリヴェイラ・コウティーニョ
ジョアオ・パウロ；ジョアン・パウロ
ダマド・メフメド：ダマト・メフメト
ウスマン・バーコマンダ：ウスマン・ブルコマンダ
フランツ・ジョセフ：フランツ・ヨーゼフ
イグナツ：イグナーツ
フォン・ドブルホフ・ダイアー：フォン・ドブルホフ＝ディーア
ディ・サルッツオ：ディ・サルッツォ
サウリ・ディグリアーノ：サウリ・ディリアーノ
ソラロ・デラ・マルガリータ：ソラーロ・デッラ・マルガリータ
ゴメズ・ファリアス：ゴメス・ファリアス
ロドビコ：ロドヴィーコ
マンギーノ・イ・メンディビル：マンヒーノ・イ・メンディビル
アフ・ウィンガルド：アヴ・ヴィンゴルド
マリー・テレーセ：マリー・テレーズ
セスバ：シェフスヴァル
ロバノフ・ロストフスキー：ロバーノフ＝ロストーフスキー
メスチェルスキー：メシチェールスキー
ピストルカーズ：ピストリコルス
サルティコフ：サルトィコフ
イェンガリチェフ：エンガルィーチェフ
パレイ：パーレイ

アダルバート：アーダルベルト
シギスムンド：ジギスムント
ワルデルマール：ヴァルデマール
カール・ルードヴィヒ：カール・ルートヴィヒ
ルードヴィヒ：ルートヴィヒ
アブドゥラジズ：アブデュルアズィズ
アブドゥルメジド：アブデュルメジト
バエジド：バヤズィト
ケマレディン：ケマレッディン
フェルディナンド・フィリップ：フェルディナン＝フィリップ
セベリム・デ・ノロンハ：セヴェリン・デ・ノローニャ
フォン・ホルシュタイン・ゴットルプ：フォン・ホルシュタイン＝ゴットルプ
フォン・ヘッセ：フォン・ヘッセン
フォン・グルックスバーグ：フォン・グリュックスブルク
ユアン・カルロス：フアン・カルロス
ウィレム・アレキサンダー：ウィレム・アレクサンダー

デ・ブルボン：デ・ボルボン
デ・ボルボン・アンジョー：デ・ボルボン＝アンホー
デ・ボルボン・パルマ：デ・ボルボン＝パルマ
デ・ハブスブルゴ：デ・アブスブルゴ
デ・ヴィッテルスバッハ：デ・ビッテルスバチ
ゴンカルブス・ダ・シルバ：ゴンサルヴェス・ダ・シルヴァ
デ・サウサ・ネト：デ・ソウザ・ネト
ヨアキム・マルケス：ジョアキン・マルケス
リスボア：リジュボア
ユスフ・マクサムド・イブラヒム：ユースフ・マハムード・イブラヒム
ド・ブルボン・コンデ：ド・ブルボン＝コンデ

ラバル・ニュージェント：ラヴァル・ヌゲント
フォン・ウエストミース：フォン・ヴェストミース
フォン・フィクケルモント：フォン・フィケルモント
フォン・バディエラ：フォン・バンディエラ
ゴッドウィン：ゴドウィン
サー・チャールズ：チャールズ
サー・トーマス・ビアム：トーマス・バイアム
ファビアン・ゴットリーブ：ファビアン・ゴットリープ
ハフィズ・オスマン：ハーフィズ・オスマン
オマール・ラトフィ：オメル・リュトフィ
エリー・アウグスタス・フレドリック：エリー・オーガスタス・フレドリック
ジャン・ヴィクトル：ジャン＝ヴィクトル
パシャ・アブ・ウィダン：パシャ・アブー・ウィダーン

## 変更の理由（必須）
日本語では一般的ではない表記であるため。
気付いたところのみを列挙。

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
