### ISSUE TITLE
日本文化のランダムキャラクターの名前

### ISSUE THREAD

**Issue by awak1180** [matanki-saito/vic3jpadvmod#238]
## 問題の固有名詞と希望する変更（必須）
※改行して書いてください。「：」で分離してください

names_l_japanese.yml
権野兵衛：権兵衛
早尾：速雄
比古之丞：彦之丞
博士：浩
岩尾：巌
景秋：景明
景教：景範
勘太郎：貫太郎
一重：一成
圭佑：啓介
健吉：謙吉
浩一郎：小一郎
言仁：載仁
小僧：航三
蔵之介：倉之助
正岳：正毅
ミチスラ：道貫
峰尾：岑生
満季：光衛
延吉：信義
茂人：重遠
新作：晋作
惣六：操六
佑典：資紀
佐之：祐亨
住吉：純義
高森：隆盛
高良：孝允
武明：武揚
為基：為楨
外間三郎：苫三郎
友之介：鞆之助
年吉：利良
弥八：矢八
安方：保鞏
安吉：安芳
吉賀：良馨
義道：好道
優作：勇作
麻子：浅子
千賀子：親子
銀子：吟子
玉蘭：玉瀾
果穂：花圃
恵：慶
粂八：九女八
美樹：美幾
のぶ：延
纓：応為
輝：照
上尾：神尾
可児：閑院
正木：真崎
大隅：大角
芝山：柴山
白河：白川
橘：立花
上田：植田
山県：山縣
山谷：山屋

## 変更の理由（必須）

下記ページで考証した通り、アルファベット表記を読む限りはVictoria3の日本文化のランダムキャラクターの名前は軍人・将軍など明治時代の実在人物をもとにしている。日本語訳を作成するにあたりこうした出典は考慮されなかったと考えられ、「小僧(Kozo)」など明らかに不適切な訳を生んでしまっている。これを、本来の意図と思われる表記に統一する。
https://bitbucket.org/awak1180/nmih-1180-scenario/wiki/Victoria3%E3%81%AE%E6%97%A5%E6%9C%AC%E8%AA%9E%E4%BF%AE%E6%AD%A3%E3%81%AE%E3%81%9F%E3%82%81%E3%81%AE%E3%83%A1%E3%83%A2

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by kecy3** [comment]
リンク先でも苗字が間違って混入した？とある「吉田」はきっと松蔭があることから吉田松蔭が元ネタっぽそうだと思いますが、「吉田」も「松陰」も下の名前で定義されてしまってる以上、とりあえず「吉田」は適当に名前っぽいものに変えておいた方が良さそうですよね。
うちには徳川吉田なる怪しい人物が生まれてしまいましたし。

音が似てるところから「義人（よしと）」とか？

**Comment by awak1180** [comment]
名前扱いになっているYoshidaについては、悩ましいですが「日本語訳の問題というよりも、Victoria3本体側の不備」と考えて今回のリストに含めていません。こういった件の取り扱いについては、他の方のご意見も待ちたいと思います。

**Comment by clamm0363** [comment]
上記ご提案のとおり修正いたしました。
「名前に『吉田』が含まれている」問題については他の報告と合わせてパラドに報告いたします

クローズします

**Comment by awak1180** [comment]
ありがとうございました。報告についても、お手数をおかけしますがお願い致します。
