### ISSUE TITLE
（制度）を修復/（制度）を制定

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#239]
＜ゲームシステム用語＞

## スクリーンショット（任意）

![20221028114757_1](https://user-images.githubusercontent.com/43299334/199206354-9fc26f1b-b4ef-48b5-82fd-9bacb64d9a30.jpg)
![20221028114813_1](https://user-images.githubusercontent.com/43299334/199207307-423b82ad-5308-408d-bbef-4f0d6219201e.jpg)

## 問題の用語（必須）

（制度）を修復

## 英語版の表現（任意）

Restore [LawType.GetName]
Enact [LawType.GetName]

## 希望する変更（必須）

（制度）の復活
（制度）の制定

## 変更の理由（必須）

日本語として不自然なため
体言止めでなくするなら、「（制度）を復活させる」などになる

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
の制定/の復活　に修正しました
