### ISSUE TITLE
【修正提案】廃止論者の訪問

### ISSUE THREAD

**Issue by ikabomb** [matanki-saito/vic3jpadvmod#240]
## スクリーンショット（任意）
![image](https://user-images.githubusercontent.com/84853597/199203961-a2128788-1629-4d01-b6c2-eacbfff72b11.png)

##　問題部分（タイトル・本文・選択肢）

タイトル、本文、(選択肢)

## 問題のイベントタイトル（必須）

廃止論者の訪問

## 問題のイベント本文（任意・抜粋可）

インテリゲンチャのフェヴジ ズルフィカールは、最近上エジプトを巡っているようです。これは、廃止論者のためのプロパガンダと証言の収集のためであるようです。この州の奴隷所有者はこれを奴隷の間での激しい反乱を扇動しようとしているものとみなし、ズルフィカールを直ちに州から追い出すように要求しています。

「ああ、あなたは彼 **を** を **「** 穏健派 **」** だと考えているのですね？彼**を**が話すのを聞いたことはありますか？彼**が**公然と奴隷が主人に対して蜂起するよう演説することはありません。ですが、どの演説でも、制度そのものとそれを支持するすべての人を激しく非難しているのです。**それ故に、その大義に共感している聴衆が他の結論を導き出すとは到底思えませんね。**奴隷はそのような演説を聞くことを許されないかもしれませんが、このような演説がここで行われていると聞くだけでも、奴隷の勇気となるでしょう。**時間の問題です、よく覚えておいてください**」

## 問題のイベント選択肢（任意）

その懸念には根拠がある。ズルフィカールはトラブルメーカーだ。

## 希望する変更（必須・修正部分のみ）

タイトル:
廃止論者の訪問　→　奴隷廃止論者の遊説

本文上部:
インテリゲンチャのフェヴジ ズルフィカールは、最近奴隷制を廃止するためのプロパガンダ及び証言収集のため上エジプトを巡っているようです。この州の奴隷所有者はこの動きを奴隷の間での激しい反乱を扇動しようとしているものと見て、ズルフィカールを直ちに州から追い出すように要求しています。

本文下部:
彼をを「穏健派」だと　→　彼のことを『穏健派』だと
彼をが　→　彼が
彼が公然と奴隷が主人に対して蜂起するよう演説することはありません。　→　彼は公然と奴隷が主人に対して蜂起するよう演説することはありません。
それ故に、その大義に共感している聴衆が他の結論を導き出すとは到底思えませんね。　→　ですから、奴隷制廃止の大義に共感している聴衆がそれ以外の結論に至るとは到底思えませんね。
時間の問題です、よく覚えておいてください　→　反乱は時間の問題です

選択肢:
懸念はもっともだ。ズルフィカールは厄介者だ。

## 変更の理由（必須）

タイトル:
abolitionismのことだろうから廃止論ではなく奴隷廃止論としたほうが良さそう

本文:
全体的に日本語の噛み合いが悪いため

選択肢:
せっかくなので硬直していない日本語に変更

## プレイ国家

エジプト

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by discordine** [comment]
本文、選択肢等関連エントリを修正
