### ISSUE TITLE
法律の名称

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#243]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![20221031150036_1](https://user-images.githubusercontent.com/38329957/199223896-50143b21-fc23-4922-8b31-c44d6f53102c.jpg)
![20221031150150_1](https://user-images.githubusercontent.com/38329957/199223976-c06c652b-830e-4f1e-b8f6-322b028e4345.jpg)
![20221031150047_1](https://user-images.githubusercontent.com/38329957/199227193-25b8b16b-e73c-457f-9603-85d1f19539dd.jpg)

## 問題の用語（必須）

教育システム
経済システム
陸軍モデル

政府の原則
民間学校
公共学校

地方警察

## 英語版の表現（任意）

Education System
Economic System
Army Model

Governance Principles
Private Schools
Public Schools

Local Police Force

## 希望する変更（必須）

教育制度
経済制度
軍隊の規範

政府原理
私立学校
公立学校

現地警察

## 変更の理由（必須）

日本語の表現として違和感を感じる。

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

無し

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by N-der** [comment]
教育制度、現地警察、私立学校、公立学校については賛成です。
他のものについて、別案があるので下に述べます。

公式訳のまま
- 経済システム　経済制度よりこちらのほうが良い気がする。好み。

別案あり
- 政府の原則　→　統治原理　定訳だと思われる。
- 陸軍モデル　→　陸軍体制　ここでも"model"は全体としての構造や体制を示していると思われるため。

他の法律についての翻訳案
- 国有軍(National Militia)　→　国家民兵　「民兵」であることを強調したい。「国民民兵」という案もあるが、下の国民皆兵と紛らわしいのでこちらにした。
- 大規模徴兵(Mass Conscription)　→　国民皆兵　好みだが、こちらのほうが適切ではないか。
- 小学校義務教育(Conpulsory Primary School)　→　義務初等教育/初等義務教育　小学校は日本の学校についてのみ使われる単語のため

**Comment by matanki-saito** [comment]
国民皆兵は#86のMandatory Serviceで使ってしまってるので、同じ訳語を別の原語には当てないほうがいいと思います

**Comment by matanki-saito** [comment]
- 経済システム　ここだけシステムにすると見栄えが悪くなり、なおかつ法律の中にあるので違和感があります。

- 政府の原則　→　統治原理　自分が無知なだけかもしれませんが、この訳を見たことがありません。

**Comment by N-der** [comment]
国民皆兵は使われていたんですね。見落としておりました。
同じく国有軍についても issue が立てられていたので、撤回します。失礼しました。

経済システムについては、法律の内容が「政府がどのように市場に介入するか」の側面が強いように見えるので、上で挙げられたように「経済制度」でよいと思いなおしました。

統治原理についてはローカルで(自身の学業のなかで)使っていたので、勝手に一般的な訳語だと思い込んでいました。
ただ個人的な意見としては、GovernmentではなくGovernanceが使われていることを鑑みて、「統治の原則」や「統治の原理」などが適訳ではないかと思っております。

適当な意見でお騒がせしてすみませんでした。

**Comment by ChiefIdeologue** [comment]
チーム内での議論の結果、以下の様に修正されました。

教育システム　→　教育制度
経済システム　→　経済制度
陸軍モデル　→　兵役制度

政府の原則　→　統治原理
民間学校　→　私立学校
公共学校　→　公立学校

地方警察　→　現地警察

クローズします。
