### ISSUE TITLE
【表記ゆれ】激しく・強く（Very Strongly, Strongly）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#244]
## スクリーンショット（必須）
![Strongly](https://user-images.githubusercontent.com/42687608/199226794-55034e6d-74ea-4a57-8ffa-62d645fb00d8.jpg)

## 問題のツールチップ（必須）
利益団体のイデオロギーのツールチップ

## 問題の表現（必須）
激しく / 強く（賛成・反対）

## 問題箇所の英文（任意）
Very Strongly / Strongly

## 希望する変更（必須）
現在「激しく」と翻訳されているイデオロギーのツールチップを「強く」に変更

## 変更の理由（必須）
他の場所では Very Strongly を「激しく」、Strongly を「強く」と明確に訳し分けているのに、このツールチップだけ表記ゆれを起こしているため。
ParaTranzでStronglyを検索するとひと目で分かります。

## ゲームバージョン（必須）
1.0.3

## DLC有無（必須）
- Victoria II Remastered Soundtrack
- American Buildings Pack

## MOD有無（必須）
- 自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
「強く」に修正を完了しました。
