### ISSUE TITLE
【修正提案】好機（Chance、キャラ特性のツールチップ）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#245]
## スクリーンショット（必須）
![Chance](https://user-images.githubusercontent.com/42687608/199230822-04bb5341-e5c8-4f37-99dd-f819e09a822f.jpg)

## 問題のツールチップ（必須）
キャラクターの特性ツールチップ。
確認したのは将軍の特性の補正値だが、他にも影響を及ぼす可能性あり。

## 問題の表現（必須）
```
好機
```

## 問題箇所の英文（任意）
```
Chance
```

## 希望する変更（必須）
```
確率
```

## 変更の理由（必須）
誤訳であるため。

## ゲームバージョン（必須）
1.0.3

## DLC有無（必須）
- Victoria II Remastered Soundtrack
- American Buildings Pack

## MOD有無（必須）
- 自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
「確率」への修正を完了しました。
