### ISSUE TITLE
【修正提案】移民発生時のトースト

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#246]
## スクリーンショット（必須）
![Migration](https://user-images.githubusercontent.com/42687608/199231434-3d7b3e4f-bb09-4077-9924-76bbd4ddb694.jpg)

## 問題のあるインターフェイス（必須）
移民発生時のトースト（画面上部のポップアップ）

## 問題のテキスト（必須）
```
「（文化名）である人々の大多数が〜」
```

## 希望する変更（必須）
```
「大多数の（文化名）人が〜」あるいは「（文化名）文化の人々の大多数が〜」
```

## 変更の理由（必須）
変数部分が文化名であることが考慮されていないため。

## ゲームバージョン（必須）
1.0.3

## DLC有無（必須）
- Victoria II Remastered Soundtrack
- American Buildings Pack

## MOD有無（必須）
- 自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。
