### ISSUE TITLE
[concept_rivalry]関係の終了のフィード

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#248]
※「```」は消さないでください

## スクリーンショット（必須）
割愛

## 問題のあるインターフェイス（必須）

ライバル宣言終了時の通知タイトル

## 問題のテキスト（必須）

```
[INITIATOR_COUNTRY.GetAdjectiveNoFormatting]-[TARGET_COUNTRY.GetAdjectiveNoFormatting] [concept_rivalry]が終了しました
```

## 希望する変更（必須）

```
[INITIATOR_COUNTRY.GetAdjectiveNoFormatting]・[TARGET_COUNTRY.GetAdjectiveNoFormatting]間の[concept_rivalry]宣言が終了
```

## 変更の理由（必須）

https://github.com/matanki-saito/vic3jpadvmod/issues/180
にて修正されたエントリの対になるものであるため

## ゲームバージョン（必須）

1.0.2

## DLCの有無（必須）

なし

## MODの有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。
