### ISSUE TITLE
【修正提案】市場の月間価格報告フィード

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#249]
※「```」は消さないでください

## スクリーンショット（必須）

![20221101223042_1](https://user-images.githubusercontent.com/42710893/199245859-c61f5b17-6c2f-499e-86aa-452231a4e4a6.jpg)

## 問題のあるインターフェイス（必須）

市場の月間価格報告フィード

## 問題のテキスト（必須）

```
スクショの一番上の爆発物を例に取ると
△(アイコン)52.2→爆発物の58.9
```

## 希望する変更（必須）

```
△(アイコン)爆発物：52.2→58.9
```

## 変更の理由（必須）

商品名が変な位置に入ってしまっているため。

## ゲームバージョン（必須）

1.0.3

## DLCの有無（必須）

なし

## MODの有無（必須）

なし

**Comment by matanki-saito** [comment]
原案に従うと実際の改訳案は以下のようになります
```$DIRECTION$ [Goods.GetTextIcon][Goods.GetName] @money!$PREV_PRICE|v1$ ($PREV_ICON$) @arrow_right! @money!$CUR_PRICE|v1$ ($CUR_ICON$)```

**Comment by matanki-saito** [comment]
上記案で修正しました。起票ありがとうございました。
