### ISSUE TITLE
【未訳】Current

### ISSUE THREAD

**Issue by clamm0363** [matanki-saito/vic3jpadvmod#25]
## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/29382778/197829042-d188afa0-8c90-4d1b-ab38-8a11892df4bb.png)

## 問題のツールチップ（必須）

国家ランクのマウスオーバーツールチップ

## 問題の表現（必須）

Current

## 問題箇所の英文（任意）

Current

## 希望する変更（必須）

現在（の）

## 変更の理由（必須）

未訳

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

Victoria 3: Grand Edition同梱のもの

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1034502636264767538
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by clamm0363** [comment]
修正しました。
「現在の国威」と表示されるように修正しています。

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。
