### ISSUE TITLE
【未訳】外交プレイ対象をマウスオーバーした時のツールチップ－or above

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#250]
※「```」は消さないでください

## スクリーンショット（必須）

![20221101212148_1](https://user-images.githubusercontent.com/42710893/199247707-eaa24556-ce4e-4718-85fb-10f665d39ce1.jpg)

## 問題のツールチップ（必須）

外交プレイ対象をマウスオーバーした時のツールチップ

## 問題の表現（必須）

```
CORDIAL_RELATIONS_WITH_TARGET:4 "[COUNTRY.GetName]と[TARGET_COUNTRY.GetName]間の[concept_relations]は、[concept_diplomatic_play]を始めるには($relations_cordial$ or above)が高すぎます"
```

## 問題箇所の英文（任意）

```
```

## 希望する変更（必須）

```
CORDIAL_RELATIONS_WITH_TARGET:4 "[COUNTRY.GetName]と[TARGET_COUNTRY.GetName]間の[concept_relations]は、[concept_diplomatic_play]を始めるには高すぎます($relations_cordial$以上である)"　等
```

## 変更の理由（必須）

or aboveが未訳
()の位置も文末のほうがわかりやすい気がします

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
「[国A]・[国B]間の[関係]が[親密]以上のため、[外交戦]を開始できません」と表示されるように修正しました。

クローズします。
