### ISSUE TITLE
物資（ユニットの補給用語）

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#251]
※「```」は消さないでください

## スクリーンショット（任意）

![20221101223244_1](https://user-images.githubusercontent.com/43299334/199249013-be8cd8fb-a121-4c44-98ed-d23f728a9cfe.jpg)
![20221101223255_1](https://user-images.githubusercontent.com/43299334/199249038-910b4947-e9fc-4cfd-b3e3-822fe65fa5c1.jpg)

## 問題の用語（必須）

```
物資
```

## 英語版の表現（任意）

```
Supply
```

## 希望する変更（必須）

```
補給、補給物資　など
```

## 変更の理由（必須）

ツールチップでは比較的分かりやすいが、そうでない場合、直感的に意味が把握しづらいため。
またSupplyは各商品の供給の意味でも使われ、そちらは「供給」訳に統一した。
（公式日本語訳ではどちらも「物資」と訳されていた）

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

姓名逆転MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
補給物資で修正
