### ISSUE TITLE
輸出入ルートの開廃フィード

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#253]
## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/37979626/199248593-b1585864-0019-4875-a5bc-31c3463f69c2.png)
![image](https://user-images.githubusercontent.com/37979626/199251376-d27104b6-721a-44ab-91c1-8c81496f02dd.png)

## 問題のあるインターフェイス（必須）

輸入・輸出開始時のフィード

## 問題のテキスト（必須）
```notification_new_trade_route_name: [資源アイコン] [資源アイコン]が対象の[国旗] [輸出or輸入]ルート```
```notification_new_trade_route_desc: [国旗付き国家]は[資源アイコン][資源]のための[輸出元]から[輸入先]までの[輸出or輸入]ルートを開始しました。[レベル予測に関する文]```
```notification_canceled_trade_route_name: [国旗] [輸出or輸入] [資源アイコン] [[資源] のルートが廃止されました```
```notification_canceled_trade_route_desc: [国旗付き国家]は[資源アイコン][資源]のための[輸出元]から[輸入先]までの[輸出or輸入]ルートを廃止しました。```

## 希望する変更（必須）
```[資源アイコン][資源アイコン]の[国旗][Nbsp][輸出or輸入]ルート```
```[国旗付き国家]が[資源アイコン][資源]の[輸出or輸入]ルートを[輸出元]～[輸入先]間で開始しました。[レベル予測に関する文]```
```[資源アイコン][資源アイコン]の[国旗][Nbsp][輸出or輸入]ルートが廃止```
```[国旗付き国家]は[資源アイコン][資源]の[輸出元]～[輸入先]間[輸出or輸入]ルートを廃止しました。```
※国旗の変数のうしろはスペースを空けた方が良いので、ノーブレークスペースを挿入する（半角スペースだと誤って消えてしまう可能性があるため）
## 変更の理由（必須）

自然な表現にするため

## ゲームバージョン（必須）
1.0.2

## DLCの有無（必須）
なし

## MODの有無（必須）
なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
```[国旗][Nbsp][資源アイコン][資源名]の[輸入/輸出]ルート
[国旗付き国家]が[資源アイコン][資源]の[輸出or輸入]ルートを[輸出元]～[輸入先]間で開始しました。[レベル予測に関する文]```
```[国旗][Nbsp][資源アイコン][資源名]の[輸入/輸出]ルートが廃止
[国旗付き国家]は[輸出元]～[輸入先]間の[資源アイコン][資源][輸出or輸入]ルートを廃止しました。```

**Comment by matanki-saito** [comment]
このようにしたいです。特に廃止の方ですが、フィードの頭に国旗を持ってきた方が分かりやすいと思います。

**Comment by inarizushi0309** [comment]
> ```
> [国旗付き国家]が[資源アイコン][資源]の[輸出or輸入]ルートを[輸出元]～[輸入先]間で開始しました。[レベル予測に関する文]```
> ```[国旗][Nbsp][資源アイコン][資源名]の[輸入/輸出]ルートが廃止
> [国旗付き国家]は[輸出元]～[輸入先]間の[資源アイコン][資源][輸出or輸入]ルートを廃止しました。```
> ```

こちらで修正しました
