### ISSUE TITLE
【修正提案】日本海/東海→日本海

### ISSUE THREAD

**Issue by aramoiukon** [matanki-saito/vic3jpadvmod#255]
## スクリーンショット（任意）

![Victoria 3 令和4年11月2日 1_01_15](https://user-images.githubusercontent.com/117195163/199280744-51317c87-3b8a-4e94-96c9-db8c2479786f.png)

## 問題の固有名詞（必須）

　日本海/東海

## 希望する変更（必須）

　日本海

## 変更の理由（必須）
　https://www.mofa.go.jp/mofaj/a_o/na/page1w_000153.html
　上記のURLの通り歴史的にもそうですが、ゲームで取り扱われている時代を考えると特に東海表記はおかしいかなと。

## ゲームバージョン（必須）

　1.0.1

## DLC有無（必須）

　なし

## MOD有無（必須）

　なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
お疲れ様です。下記の方針とします。
いまSteamにModとして出してる中には変更を入れ、Pdxを通して提出するLQA reportに含めてそれを受け入れるかどうかはPdx側に判断していただきます。
よろしくお願いします。

**Comment by matanki-saito** [comment]
クローズします。
