### ISSUE TITLE
【修正提案】関税同盟等で商品の関税をいじれない時「あなたはこの市場に参加していないため～」

### ISSUE THREAD

**Issue by WoodlandsGitHub** [matanki-saito/vic3jpadvmod#256]
※「｀｀｀」は消さないでください

## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/29177147/199264764-3c026c83-c16b-478d-96b2-09e66ce67c89.png)
## 問題のツールチップ（必須）

■前提条件
ケープ植民地等の特定市場下に組み込まれた国

各商品の関税設定アイコン

## 問題の表現（必須）

```
あなたはこの市場に参加していないため、×はイギリス市場の穀物を優先することができません
 NOT_PLAYER_MARKET_PRIORITY:0 "あなたはこの[concept_market]に参加していないため、@red_cross!は[Goods.GetMarket.GetName]の[Goods.GetName]を優先することは#b できません#!"
```

## 問題箇所の英文（任意）

```
 NOT_PLAYER_MARKET_PRIORITY:1 "@red_cross! Can #b not#! set priority on [Goods.GetName] in the [Goods.GetMarket.GetName] since you are not part of this [concept_market]"
```

## 希望する変更（必須）

```
 NOT_PLAYER_MARKET_PRIORITY:1 "@red_cross![Goods.GetMarket.GetName]の[Goods.GetName]の優先度を#b 設定できません#!。 この[concept_market]で重要な外交的地位にいないためです"
```

## 変更の理由（必須）

red_crossを主語と誤認して訳しているため。
ついでに校正。
ただし、since you are not part of this [concept_market]の訳は、直訳すると「この市場の構成国ではないため」ぐらいな意味合いになるが、それだと市場内部にいる実態とそぐわない。
「（関税同盟であったり傀儡であったりして関税設定を触れない低い地位＝）市場での役目がないため」ぐらいの意味合いで拾って意訳した。

適宜訂正求む

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

日本語改善MOD
Switch Languages

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
> @red_cross![Nbsp]あなたはこの[concept_market]を主導する立場ではないため、[Goods.GetMarket.GetName]で[Goods.GetName]の関税を設定#b できません#!

**Comment by clamm0363** [comment]
上記のように修正しました。

クローズします。
