### ISSUE TITLE
【修正提案】○○にいます

### ISSUE THREAD

**Issue by clamm0363** [matanki-saito/vic3jpadvmod#257]
※「｀｀｀」は消さないでください

## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/29382778/199313453-6002d103-0c76-44cc-8013-6a8f28e2b4fd.png)

## 問題のツールチップ（必須）

ゲーム内で "in [国名]" が呼ばれる箇所全体

## 問題の表現（必須）

```
[国旗つき国名]にいます
```

## 問題箇所の英文（任意）

```
in [国旗つき国名]
```

## 希望する変更（必須）

```
「[国旗つき国名]」のみとする
```

## 変更の理由（必須）

日本語がおかしな表記になるため

## ゲームバージョン（必須）

1.0.3

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
上記のとおり修正しました。

クローズします。
