### ISSUE TITLE
【修正提案】奴隷を労働者として用いる時のツールチップ

### ISSUE THREAD

**Issue by clamm0363** [matanki-saito/vic3jpadvmod#258]
※「｀｀｀」は消さないでください

## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/29382778/199314393-dc9b0665-14e9-43a8-898b-e1f5b703305d.png)

## 問題のツールチップ（必須）

レンズで施設建設する際のツールチップ

## 問題の表現（必須）

```
[奴隷]をの[労働者]として使用します
```

## 問題箇所の英文（任意）

```
Uses [POP_TYPE.GetName] as [TARGET_POP_TYPE.GetName][SelectLocalization( ObjectsEqual(Country.Self, GetPlayer.Self), '', 'IN_COUNTRY' )]
```

## 希望する変更（必須）

```
[POP_TYPE.GetName]を[SelectLocalization( ObjectsEqual(Country.Self, GetPlayer.Self), '', 'IN_COUNTRY' )][SelectLocalization( ObjectsEqual(Country.Self, GetPlayer.Self), '', 'の' )][TARGET_POP_TYPE.GetName]として使用します
```

## 変更の理由（必須）

「の」をうまく処理できていないため、必要のない時にも「の」が表示されているため

## ゲームバージョン（必須）

1.0.3

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
上記のとおり修正しました。

クローズします。
