### ISSUE TITLE
法律制定時の効果説明文・「抑圧の影響です」など

### ISSUE THREAD

**Issue by flowlanss** [matanki-saito/vic3jpadvmod#259]
※「｀｀｀」は消さないでください

## スクリーンショット（必須）

![image](https://user-images.githubusercontent.com/54560025/199359583-d3a0b975-7268-4387-bac3-fde507d6b564.png)

## 問題のあるインターフェイス（必須）

法律制定時のポップアップ・法律の効果の説明文

## 問題のテキスト（必須）

```
~
利益団体の求心力における抑圧の影響です：-30%
利益団体の求心力における強化の影響です：+30%
インテリゲンチャ(27.5%)は、昨今における検閲から集会の権利への変更を賛成: +5
~
```

## 希望する変更（必須）

```
利益団体の求心力に対する抑圧の影響: -30%
利益団体の求心力に対する強化の影響: +30%
インテリゲンチャ(27.5%)は、昨今における検閲から集会の権利への変更に賛成: +5
```

## 変更の理由（必須）

効果を示すところを体言止めに、またコロンが全角のようなので半角にする。日本語として不自然なところを修正したい。

## ゲームバージョン（必須）

1.0.3

## DLCの有無（必須）

Victoria II Remastered Soundtrack
American Buildings Pack

## MODの有無（必須）

JapaneseLanguageAdvancedMod

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by flowlanss** [comment]
上記のように、但しコロンは全角にして修正。クローズします。
