### ISSUE TITLE
【未訳】location

### ISSUE THREAD

**Issue by clamm0363** [matanki-saito/vic3jpadvmod#26]
## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/29382778/197829850-ec88f9ce-1c0d-47a7-a68b-8cb3d1655b47.png)

## 問題のツールチップ（必須）

将軍・提督のマウスオーバーツールチップ

## 問題の表現（必須）

location

## 問題箇所の英文（任意）

location

## 希望する変更（必須）

現在地

## 変更の理由（必須）

未訳

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

（例）なし

## MOD有無（必須）

Victoria 3: Grand Edition同梱のもの

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1034503298838958160
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by clamm0363** [comment]
修正しました。
「Location: ~」の部分が「現在地: ～」と表示されるように修正しています。
