### ISSUE TITLE
【修正提案】徴兵制を開始しました（通知）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#260]
## スクリーンショット（必須）
![Conscription](https://user-images.githubusercontent.com/42687608/199380964-9a4a923a-da73-4559-a5f6-271127303732.jpg)

## 問題のあるインターフェイス（必須）
徴兵を開始したときに表示される通知

## 問題のテキスト（必須）
```
徴兵制を開始しました
```

## 希望する変更（必須）
```
徴兵を開始しました
```

## 変更の理由（必須）
この場合のConscriptionは「徴兵制」ではなく「徴兵」と訳すべきだから。
関連するキーはconcept_conscription_center_conscriptionとnotification_country_conscription_nameで、他の場所では使われていない。

## ゲームバージョン（必須）
1.0.3

## DLC有無（必須）
- Victoria II Remastered Soundtrack
- American Buildings Pack

## MOD有無（必須）
- 自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
該当箇所のみ「徴兵」に修正を完了しました。
