### ISSUE TITLE
【修正提案】助詞「の」の重複

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#261]
## スクリーンショット（任意）
![nono](https://user-images.githubusercontent.com/42687608/199381661-af47916b-d9ca-44ac-bebf-20088f0076d3.jpg)

## 問題部分（タイトル・本文・選択肢）
```
本文（フレーバーテキスト）
```

## 問題のイベントタイトル（必須）
```
拡声装置の脱線
```

## 問題のイベント本文（任意・抜粋可）
```
彼のの差配により / 彼のの政敵から
```

## 問題のイベント選択肢（任意）
```
```

## 希望する変更（必須・修正部分のみ）
```
彼の差配により / 彼の政敵から
```

## 変更の理由（必須）
代名詞を代入する変数の処理に失敗し、助詞の「の」が重複しているため。
影響があらゆるところに及ぶ可能性があるので、慎重に修正する必要がある。

以下のキーが関連していると思われる。
CHARACTER_HER：her / 彼女の
CHARACTER_HIS：his / 彼の
CHARACTER_HIM：him / 彼を

## プレイ国家
スペイン

## ゲームバージョン（必須）
1.0.3

## DLC有無（必須）
- Victoria II Remastered Soundtrack
- American Buildings Pack

## MOD有無（必須）
- 自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
修正対応が終わりましたのでクローズします。
