### ISSUE TITLE
【修正提案】シビア・マラリア（Severe Malaria）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#262]
## スクリーンショット（任意）
![Malaria](https://user-images.githubusercontent.com/42687608/199385190-a9f59a85-3851-4f83-8b7d-307008e01d54.jpg)

## 問題の用語（必須）
```
シビア・マラリア
```

## 英語版の表現（任意）
```
Severe Malaria
```

## 希望する変更（必須）
```
過酷なマラリア
```

## 変更の理由（必須）
日本語に翻訳されていないため。この表現は州の特性にも使われています。変更案は一例です。

## ゲームバージョン（必須）
1.0.3

## DLC有無（必須）
- Victoria II Remastered Soundtrack
- American Buildings Pack

## MOD有無（必須）
- 自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
議論の末、「深刻なマラリア」に決定し、修正を完了しました。
