### ISSUE TITLE
ブータン「現世的支配者」

### ISSUE THREAD

**Issue by nagi0330** [matanki-saito/vic3jpadvmod#263]
※「｀｀｀」は消さないでください

## スクリーンショット（必須）
![20221101180831_1](https://user-images.githubusercontent.com/6514922/199387095-28498556-dffb-4146-ae57-8f612ec2dc41.jpg)

## 問題のツールチップ（必須）

ブータンの政治体制説明

## 問題の表現（必須）

```
現世的支配者
```

## 希望する変更（必須）

```
世俗的支配者
```

## 変更の理由（必須）

現世的支配者なんて言い方しないと思うので、、、確認していませんがスルタンのツールチップも同じ表現になってそうです。

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
ご指摘通り、「世俗的」に修正しました。ありがとうございます。

**Comment by matanki-saito** [comment]
修正したためクローズします。
