### ISSUE TITLE
反乱軍の名称の修正

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#264]
※「｀｀｀」は消さないでください

## スクリーンショット（任意）
なし

## 問題の用語（必須）

```
[国名]（階級名などが入る）の反乱
革命主義的な[国名]
```

## 英語版の表現（任意）

```
[COUNTRY.GetDefinition.GetAdjective] Peasant Revolt
Revolutionary [COUNTRY.GetDefinition.GetName]
```

## 希望する変更（必須）

```
[国名]（階級名などが入る）反乱軍
革命[国名]
```

## 変更の理由（必須）

現在の訳では日本語として違和感を覚える表現になっている。
イギリス小作農の反乱　→　イギリス小作農反乱軍
革命主義的なイギリス　→　革命イギリス
という様な表現にしたい。

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

無し

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
以下の様に修正しました。
共産主義: [国名]赤衛軍
ファシスト:  [国名]国粋派
急進派:  [国名]急進派
農村民:  [国名]農民一揆
地主:  [国名]地主反乱軍
知識人:  [国名]自由主義反乱軍
実業家:  [国名]資本家反乱軍
軍部:  [国名]反乱軍
宗教家:  [国名]宗教反乱軍
小ブルジョワ: [国名]・ブルジョワ反乱軍
労働組合:  [国名]・プロレタリア反乱軍
汎用1:  [国名]革命軍
汎用2:  [国名]反政府軍
汎用3:  [国名]抵抗運動

クローズします。
