### ISSUE TITLE
【修正提案】「我が国の法律の一部です」

### ISSUE THREAD

**Issue by WoodlandsGitHub** [matanki-saito/vic3jpadvmod#265]
## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/29177147/199391684-1747f228-e1e8-4f26-a824-01ca377f44e4.png)

## 問題のツールチップ（必須）

政策ウィンドウ＞法律タブ＞（政府の原則や経済システム等の選択）＞（試行中の法律の名称をマウスオーバー）

## 問題の表現（必須）

```
我が国の法律の一部です
 ACTIVE_LAW:0 "@green_checkmark! 我が国の[Concept('concept_law', '$concept_laws$')]の一部です"
```

## 問題箇所の英文（任意）

```
 ACTIVE_LAW:0 "@green_checkmark! Part of our [Concept('concept_law', '$concept_laws$')]"
```

## 希望する変更（必須）

```
施行中の法律
```

## 変更の理由（必須）

part of を一律、～の一部と訳していて不自然な日本語になっているため

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

日本語改善MOD
Switch Languages

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
「我が国で施行中の法律です/ではありません」と表示されるように修正しました。

クローズします。
