### ISSUE TITLE
【修正提案】「我が国の法律の一部ではありません」

### ISSUE THREAD

**Issue by WoodlandsGitHub** [matanki-saito/vic3jpadvmod#266]
## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/29177147/199401293-1d6f5753-22fc-41ec-9d8e-87ee390e229b.png)

## 問題のツールチップ（必須）

政策ウィンドウ＞法律タブ＞（政府の原則や経済システム等の選択）＞（制定前の法律の名称をマウスオーバー）

## 問題の表現（必須）

```
我が国の法律の一部ではありません
 INACTIVE_LAW:0 "@red_cross! 我が国の[Concept('concept_law', '$concept_laws$')]の一部ではありません"
```

## 問題箇所の英文（任意）

```
 INACTIVE_LAW:0 "@red_cross! Not part of our [Concept('concept_law', '$concept_laws$')]"
```

## 希望する変更（必須）

```
制定前の法律
```

## 変更の理由（必須）

part of を一律、～の一部と訳していて不自然な日本語になっているため

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

日本語改善MOD
Switch Languages

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Via-GitHub** [comment]
端的な表現に同意します。part ofは数量に厳密な英語ならではという感じですね。
[issue#265](https://github.com/matanki-saito/vic3jpadvmod/issues/265)と統一する形で「施行中/未施行の法律」「制定済み/未制定の法律」あたりはどうでしょうか。「制定前」だと今から制定するつもりのようなニュアンスも？

**Comment by WoodlandsGitHub** [comment]
#265で修正が終わりクローズされたので、合わせてこちらもクローズします

**Comment by WoodlandsGitHub** [comment]
対となる#265が修正の上クローズされたので、こちらもクローズします
