### ISSUE TITLE
【修正提案】シニアパートナー・ジュニアパートナー (Senior Partner, Junior Partner)

### ISSUE THREAD

**Issue by kurutto115** [matanki-saito/vic3jpadvmod#267]
## スクリーンショット（任意）
![Victoria 3 2022_11_02 14_09_47](https://user-images.githubusercontent.com/117251782/199404734-e72a0208-b666-4d2a-bf94-bf359e9e2780.png)

## 問題の用語（必須）

```
シニアパートナー
ジュニアパートナー
```

## 英語版の表現（任意）

```
Senior Partner
Junior Partner
```

## 希望する変更（必須）

```
主導メンバー
傘下メンバー
```

## 変更の理由（必須）

音訳であり分かりにくいため

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

無し

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
議論の結果、以下の表記で修正を完了したため、クローズしました。
シニアパートナー：盟主国
ジュニアパートナー：加盟国
