### ISSUE TITLE
漢字化されていない清の人名

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#268]
## 問題の固有名詞と希望する変更（必須）

ティアンペイ：天培
フアンシェン：化成
ブヤンタイ：布彦泰
ヤンザ：顔扎
雲輝：雲飛
ゲ：葛

トン：佟
デング：鄧

## 変更の理由（必須）
日本語では一般的ではない表記であるため。

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

日本語修正MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
