### ISSUE TITLE
諸言語の固有名詞

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#269]
## 問題の固有名詞と希望する変更（必須）

アラビア語：アルバニア語
モン・クメール語派：モン・クメール語
ミャオ・ヤオ語族：ミャオ・ヤオ語

スラブ語：スラヴ諸語
ユーゴスラビア語：ユーゴスラヴ諸語
アラブ語圏：アラビア語圏
チュルク語族：テュルク諸語
漢字文化圏：漢文化圏
ヒマラヤ語系：ヒマラヤ諸語
タイ語：タイ諸語
バントゥー系民族：バントゥー諸語
エチオピア語：エチオピア諸語
カフカース語：コーカサス諸語
ポリネシア語：ポリネシア諸語
ケルト語：ケルト諸語

## 変更の理由（必須）
日本語では一般的ではない表記であるため。

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

日本語修正MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
