### ISSUE TITLE
識字率のツールチップ内のtypo

### ISSUE THREAD

**Issue by Yoto** [matanki-saito/vic3jpadvmod#272]
※「｀｀｀」は消さないでください

## スクリーンショット（必須）

![2022-11-02 (1)](https://user-images.githubusercontent.com/388340/199437703-f9aa332f-ba16-49c5-a718-ea74a79ac08c.png)

## 問題のツールチップ（必須）

トップバーの識字率のマウスオンヒント

## 問題の表現（必須）

```
[○○M][○○M]のうち、日本の編入州に住んでいる人は読み書きができ、・・・

さらに、現在の識字率率によって、・・・
```

## 希望する変更（必須）

```
[○○M]のうち、日本の編入州に住んでいる[○○M]人は読み書きができ、・・・

さらに、現在の識字率によって、・・・
```

## 変更の理由（必須）

typo

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

Victoria II Remastered Soundtrack
American Buildings Pack

## MOD有無（必須）

JapaneseLanguageAdvancedMod
Japanese Font
Japanese Namelist Improvement

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by WoodlandsGitHub** [comment]
![image](https://user-images.githubusercontent.com/29177147/199663335-b96d029c-e627-45e0-80d8-8d411a35f788.png)
日本語だと最後の部分が重複してるが、英語だと重複は解消されている。
日本語のファイルでコピーミスしてると思われる。

**Comment by matanki-saito** [comment]
上記指摘を鑑みここのツールチップ全体を修正したいと思います。
修正簡易版
```[コンセプト（識字率）]#!
[国名]の[コンセプト（編入州）]に住んでいる[総人口]人の内、[読み書き可能人口]人が読み書きができ、その結果、識字率は[識字率%]（全世界で第$RANKING$位）となっています。
------------------
これにより、[コンセプト（革新）]上限が@innovation![革新最大値]になっています。
現在、毎週@innovation![革新生産量]生産しています。（上限なしだと@innovation![上限抜きの革新生産量]）

さらに現在の[コンセプト（識字率）]によって[コンセプト（技術の普及）]率は毎週[下振れ値]～[上振れ値]相当の@innovation![コンセプト（革新）]になっています。[SelectLocalization(EqualTo_int32(GetPlayer.GetTotalPopulation,GetPlayer.GetIncorporatedPopulation),'','LITERACY_UNINCORPORATED_TOOLTIP')]
------------------
また、[コンセプト（未編入州）]も考慮した場合、[国名]の[コンセプト（POP）][総人口]人の内、[読み書き可能人口]([Country.GetTotalLiteracyRate|%v])が読み書きができます。（全世界で第$RANKING$位）```

（全世界で第$RANKING$位）→RANKING_FORMAT

**Comment by matanki-saito** [comment]
修正正規版
```#header [concept_literacy]#!\n#variable [Country.GetName]#!の[concept_incorporated_state]に住んでいる#variable [Country.GetIncorporatedPopulation|*]#!の内#variable [Country.GetNumIncorporatedLiteratePops|*]#!が読み書きができ、その結果、識字率は[Country.GetIncorporatedLiteracyRate|%v][Country.GetIncorporatedLiteracyRanking]となっています。\n$TOOLTIP_DELIMITER$\nこれにより、[concept_innovation]上限が#tooltippable #tooltip:[GetPlayer.GetTooltipTag],INNOVATION_POINTS_MAX_BREAKDOWN @innovation![Country.GetWeeklyMaxInnovation|1]#!#!になっています。\n現在、毎週#tooltippable #tooltip:[GetPlayer.GetTooltipTag],INNOVATION_POINTS_CURRENT_BREAKDOWN #v @innovation![Country.GetWeeklyInnovation|+=1]#!#!#!生産しています。（上限なしだと@innovation![Country.GetWeeklyRawInnovation|+=1]）\n\nさらに現在の[concept_literacy]によって[concept_technology_spread]率は毎週#P #tooltippable #tooltip:[GetPlayer.GetTooltipTag],TECHNOLOGY_SPREAD_RATE_BREAKDOWN [Country.GetMinWeeklyTechnologySpread|1]～[Country.GetMaxWeeklyTechnologySpread|1]#!#!#!相当の@innovation![concept_innovation]になっています。[SelectLocalization(EqualTo_int32(GetPlayer.GetTotalPopulation,GetPlayer.GetIncorporatedPopulation),'','LITERACY_UNINCORPORATED_TOOLTIP')]```
```\n$TOOLTIP_DELIMITER$\nまた、[Concept('concept_unincorporated_state','$concept_unincorporated_states$')]も考慮した場合、#variable [Country.GetName]#!の#variable [Concept('concept_pop','$concept_pops$')]#!#variable [Country.GetTotalPopulation|*]#!の内、#variable [Country.GetNumTotalLiteratePops|*]#!（[Country.GetTotalLiteracyRate|%v]）が読み書きができます。[Country.GetTotalLiteracyRanking]```
```（全世界で#tooltippable #tooltip:$LEADERBOARD$ #v 第$RANKING$位#!#!#!）```
