### ISSUE TITLE
Gold Fields とGold Mine（金鉱山）

### ISSUE THREAD

**Issue by setopic** [matanki-saito/vic3jpadvmod#274]
※「｀｀｀」は消さないでください

### **Gold Fields**
![image](https://user-images.githubusercontent.com/45805826/199457634-f7774f93-04ce-43f2-8bd3-2d7997483001.png)

### **Gold Mine**
![image](https://user-images.githubusercontent.com/45805826/199457770-acab2924-907b-47f1-b7da-28fbeb672d37.png)

## 問題の用語（必須）
```
金鉱山
```

## 英語版の表現（任意）

```

Gold Fields
Gold Mine

```

## 希望する変更（必須）
```
Gold Fields(building_gold_fields) -> 採金地 （グラフィックでは川が描かれており、おそらく砂金を表しているため）
Gold Mine(building_gold_mine) -> 金鉱山 （現状から変更の必要無し。一応記載。）
```

## 変更の理由（必須）

原語及びゲーム上では別のものとして扱われているが、日本語訳ではその違いが読み取れないため。

## ゲームバージョン（必須）

1.0.4

## DLC有無（必須）

無し

## MOD有無（必須）

無し

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
ご指摘の通り「採金地」に変更しました。ありがとうございます。
変更したためクローズします
