### ISSUE TITLE
【修正提案】貯蓄 pool

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#276]
※「｀｀｀」は消さないでください

## スクリーンショット（任意）

![pool_jp](https://user-images.githubusercontent.com/50406316/199473161-3e9b955a-d361-4e77-8cff-1a14ca02629b.png)
![pool](https://user-images.githubusercontent.com/50406316/199473174-75cd20a4-bc04-4686-b107-50ff69e0949d.png)

## 問題の用語（必須）

```
貯蓄
```

## 英語版の表現（任意）

```
Pools
```

## 希望する変更（必須）

```
プール
```

## 変更の理由（必須）

現在の訳は貯蓄となっているが、これは信用プール（借金可能枠）と使用分および投資プールのことを指す項目であり、特に前者の信用プールは貯蓄とは関係なくプレイヤーの誤解を招くため改訳したい。

## ゲームバージョン（必須）

1.0.4

## DLC有無（必須）

無し

## MOD有無（必須）

JapaneseLanguageAdvancedMod(更新: 11月2日 @ 7時11分)

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
提案通り変更してクローズします
