### ISSUE TITLE
国家主義

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#279]
## スクリーンショット（任意）
![20221102191125_1](https://user-images.githubusercontent.com/38329957/199465767-5ea296d8-7ea7-49f4-9163-bb3b9ab51745.jpg)
![20221102191141_1](https://user-images.githubusercontent.com/38329957/199465805-329c12b4-d6d0-4141-a3ee-2ef1e09d169c.jpg)
![20221102191858_1](https://user-images.githubusercontent.com/38329957/199465839-dadc2d56-7e4d-4d17-a96a-6d40c6a2d116.jpg)

## 問題部分（タイトル・本文・選択肢）

```
国家主義と表記されてるところ全て。
```

## 問題のイベントタイトル（必須）

```
国家主義者のオペラ
```
など
## 問題のイベント本文（任意・抜粋可）

```
なし
```

## 問題のイベント選択肢（任意）

```
なし
```

## 希望する変更（必須・修正部分のみ）

```
民族主義
```

## 変更の理由（必須）

国家主義だと文章がおかしくなる部分が多々あり、なおかつVictoria3の時代は民族主義運動の全盛期であり、言葉としても適訳であるため。

## プレイ国家

どこでも

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
