### ISSUE TITLE
【typo】扶養者所得ツールチップ

### ISSUE THREAD

**Issue by clamm0363** [matanki-saito/vic3jpadvmod#28]
## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/29382778/197838973-a4db8063-f3ac-43ee-9ae6-21434284d1d7.png)
## 問題のツールチップ（必須）

扶養者所得のツールチップ

## 問題の表現（必須）

concept_dendents

## 問題箇所の英文（任意）

concept_dendents

## 希望する変更（必須）

正しい変数に修正する

## 変更の理由（必須）

変数におそらくタイポがあるため

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

Victoria 3: Grand Edition同梱のもの

## MOD有無（必須）

なし

**Comment by WoodlandsGitHub** [comment]
正しい変数はconcept_dependents（扶養者）だと思われます。

**Comment by clamm0363** [comment]
ありがとうございます。どうやらゲームのバグで、国家選択前は一部の変数が正しく読み込まれないようです。この問題はおそらくMOD側で解決できません。

**Comment by clamm0363** [comment]
@WoodlandsGitHub すみません、ご指摘通り、原文のタイポでした

**Comment by clamm0363** [comment]
変数表記を修正しました。

クローズします。
