### ISSUE TITLE
【修正提案】原料不足　サジェスチョン

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#280]
## スクリーンショット（任意）

![20221102180111_1](https://user-images.githubusercontent.com/43299334/199490595-6de171d4-e06e-45cf-9999-0e96e3cb75af.jpg)

## 問題の用語（必須）

```
原料不足
（市場）での（商品）の原料不足
```

## 英語版の表現（任意）

```
Input Goods Shortage

[SCOPE.GetRootScope.GetMarketGoods.GetGoods.GetTextIcon] [SCOPE.GetRootScope.GetMarketGoods.GetGoods.GetName] [concept_input_goods_shortage] in the [SCOPE.GetRootScope.GetMarketGoods.GetMarket.GetName]
```

## 希望する変更（必須）

```
不足

（市場）における（商品）の不足
```

## 変更の理由（必須）

誤訳というわけではないが、（商品）の原料が不足しているように読めてしまうため。
（実際に不足しているのは表示されている商品そのもの）
ただし、場合によっては「原料不足」の訳が適当な場合もあり、修正については相談したい。

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

フォント文字化け改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
画像の「原料不足」のみ、[Concept('concept_input_goods_shortage', '不足')]として「不足」にしました
