### ISSUE TITLE
【バグ】輸出入ルートのツールチップ

### ISSUE THREAD

**Issue by clamm0363** [matanki-saito/vic3jpadvmod#281]
※「｀｀｀」は消さないでください

## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/29382778/199503769-c598fcd2-f083-4e26-9652-94087ff8cafb.png)
![image](https://user-images.githubusercontent.com/29382778/199503804-a4859cba-8386-467b-a157-e51cd5385ba0.png)

## 問題のツールチップ（必須）

貿易ルート内で、輸出入ルートにマウスオーバーした際のツールチップ

## 問題の表現（必須）

```
ルート: [州A]から[州B]へ
```

## 問題箇所の英文（任意）

```
[州A] to [州B]
```

## 希望する変更（必須）

```
[州B]から[州A]へ
```

## 変更の理由（必須）

英語版・日本語版とも、輸出入のルートが逆に記載されている

## ゲームバージョン（必須）

1.0.4

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
見当の結果、[州A][州B]は輸出入とは関係がなく、その交易ルートを管轄している国がどちらかで決まってくるようです。よって、[州A] ～ [州B]と表示されるように修正しました。

クローズします。
