### ISSUE TITLE
【修正提案】美術学校

### ISSUE THREAD

**Issue by clamm0363** [matanki-saito/vic3jpadvmod#282]
※「｀｀｀」は消さないでください

## スクリーンショット（任意）
![image](https://user-images.githubusercontent.com/29382778/199507127-c3359cca-722c-40c5-aa5c-278025d2d77f.png)

## 問題の用語（必須）

```
美術学校
```

## 英語版の表現（任意）

```
Arts Academy
```

## 希望する変更（必須）

```
美術院もしくは芸術院
```

## 変更の理由（必須）

イギリス最古の美術学校、Royal Academy of Artsは「王立芸術院」と訳される。Arts Academyの解禁技術はロマン主義であり、王立芸術院はその発展に大きく寄与したとされる。こうした歴史的背景を考えると、ただの「学校」ではなく、箔のある名称にすべき。

## ゲームバージョン（必須）

1.0.4

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
「芸術院」と修正しました

クローズします
