### ISSUE TITLE
不健全な経済ツールチップ

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#283]
※「｀｀｀」は消さないでください

## スクリーンショット（必須）

![20221102181104_1](https://user-images.githubusercontent.com/43299334/199508754-a05c3567-6272-450c-bd70-95c9272ffccc.jpg)

## 問題のツールチップ（必須）

不健全な経済　ツールチップ

## 問題の表現（必須）

```
あなたの経済は$HEALTH$
$TAB$$INCOME_RATIO$です
$TAB$$CREDIT_RATIO$ (元金: #variable @money!$CURRENT_LOAN_BALANCE|D$#!)


@red_cross!#tooltippable #tooltip:[GetPlayer.GetTooltipTag],TOTAL_EXPENSES_BREAKDOWN,TotalExpensesTooltip #variable @money!$EXPENSES|-K$#!#!#!の固定支出が、#tooltippable #tooltip:[GetPlayer.GetTooltipTag],TOTAL_INCOME_BREAKDOWN,TotalIncomeTooltip #variable @money!$INCOME|+K$#!#!#!の週間収入を超過しています
```

## 問題箇所の英文（任意）

```
Your economy is $HEALTH$
$TAB$$INCOME_RATIO$
$TAB$$CREDIT_RATIO$ (Principal: #variable @money!$CURRENT_LOAN_BALANCE|D$#!)

@red_cross! Fixed expenses of #tooltippable #tooltip:[GetPlayer.GetTooltipTag],TOTAL_EXPENSES_BREAKDOWN,TotalExpensesTooltip #variable @money!$EXPENSES|-K$#!#!#! exceeds weekly income of #tooltippable #tooltip:[GetPlayer.GetTooltipTag],TOTAL_INCOME_BREAKDOWN,TotalIncomeTooltip #variable @money!$INCOME|+K$#!#!#!

```

## 希望する変更（必須）

```
$TAB$$INCOME_RATIO$
```

## 変更の理由（必須）

日本語として不自然なため
黒字の場合は
@green_checkmark!#tooltippable #tooltip:[GetPlayer.GetTooltipTag],TOTAL_INCOME_BREAKDOWN,TotalIncomeTooltip #variable @money!$INCOME|+K$#!#!#!の週間収入が、#tooltippable #tooltip:[GetPlayer.GetTooltipTag],TOTAL_EXPENSES_BREAKDOWN,TotalExpensesTooltip #variable @money!$EXPENSES|-K$#!#!#!の固定支出を超えています
となっており、この場合でも「です」はない方がよさそう

## ゲームバージョン（必須）

（例）1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

マップ文字化け改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
不要な「です」を削除しました
