### ISSUE TITLE
【修正提案】徴兵センター/建設セクター/交易センター

### ISSUE THREAD

**Issue by clamm0363** [matanki-saito/vic3jpadvmod#284]
※「｀｀｀」は消さないでください

## スクリーンショット（任意）
![image](https://user-images.githubusercontent.com/29382778/199521920-002e9631-428c-43d4-81c0-2c00b40c7b54.png)
![image](https://user-images.githubusercontent.com/29382778/199522431-6ba1da08-0548-4596-b49f-d35486d79f29.png)

## 問題の用語（必須）

```
徴兵センター/建設セクター/交易センター
```

## 英語版の表現（任意）

```
Conscription Center/Construction Sector/Trade Center
```

## 希望する変更（必須）

```
徴兵局/建設局/商社
```

## 変更の理由（必須）

好みです。あと文字数が減るのでUI的に優しい

## ゲームバージョン（必須）

1.0.4

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。
