### ISSUE TITLE
【修正提案】州教に神道 State Shinto

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#285]
※「｀｀｀」は消さないでください

## スクリーンショット（任意）
![state_shinto](https://user-images.githubusercontent.com/50406316/199522203-defb1cc7-f6ed-482d-9de9-d730d6aeef34.png)

## 問題部分（タイトル・本文・選択肢）

```
(ja)
 shinto_decision:0 "州教に神道を導入"
 shinto_decision_desc:0 "皇室が政権に復帰したことにより、天皇の神性を重んじる現地人の信仰を国教として統合することが賢明であると考えられます。"
(en)
 shinto_decision:0 "Adopt State Shinto"
 shinto_decision_desc:0 "With the restoration of the imperial household to political power, it would be wise to integrate local beliefs into an official state religion emphasizing the Emperor's divinity."
```

## 問題のイベントタイトル（必須）

```
州教に神道を導入
```

## 問題のイベント本文（任意・抜粋可）

```
皇室が政権に復帰したことにより、天皇の神性を重んじる現地人の信仰を国教として統合することが賢明であると考えられます。
```

## 問題のイベント選択肢（任意）

```
```

## 希望する変更（必須・修正部分のみ）

```
国家神道の導入
皇室が政権に復帰したことにより、天皇の神性を重んじる我が国の信仰を国教として統合することが賢明であると考えられます。
```

## 変更の理由（必須）
タイトルのState Shintoの誤訳修正
合わせてイベント文中の「現地人の」も自国を対象にするディシジョンでは違和感があるので、「我が国の」と意訳

## プレイ国家
日本

## ゲームバージョン（必須）
1.0.4

## DLC有無（必須）
なし

## MOD有無（必須）
JapaneseLanguageAdvancedMod(更新: 11月2日 @ 7時11分)

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
提案通り変更してクローズします
