### ISSUE TITLE
【修正提案】絹農園

### ISSUE THREAD

**Issue by clamm0363** [matanki-saito/vic3jpadvmod#286]
※「｀｀｀」は消さないでください

## スクリーンショット（任意）
![image](https://user-images.githubusercontent.com/29382778/199523653-a4d39e99-0fd6-4e9f-bc3b-aff32fe3bcaf.png)

## 問題の用語（必須）

```
絹農園
```

## 英語版の表現（任意）

```
Silk Plantations
```

## 希望する変更（必須）

```
桑農園
```

## 変更の理由（必須）

一般に「絹農園」とは言わず、カイコ蛾の餌である「桑畑」と言う。「農園」としたのは、プランテーション系施設であるため。

## ゲームバージョン（必須）

1.0.4

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by N-der** [comment]
桑畑は養蚕業と一体化しているので桑農園でも間違いではないと思うのですが、生産物が絹であることを考えると「養蚕農園」とするほうが分かりやすいのではないでしょうか。

**Comment by clamm0363** [comment]
議論でも「養蚕農園」が良いのではないかという案がでて、私もそれに賛成です。ありがとうございます。

**Comment by clamm0363** [comment]
「養蚕農園」と修正しました。

クローズします。
