### ISSUE TITLE
港の基礎方式　停泊→停泊地

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#287]
## スクリーンショット（任意）
![image](https://user-images.githubusercontent.com/37979626/199524593-ff2e1cab-df6a-4ab7-ab8f-8f16a35b214e.png)

## 問題の固有名詞（必須）
停泊

## 希望する変更（必須）
停泊地

## 変更の理由（必須）
場所を指すのであれば「地」を付けるべき

## ゲームバージョン（必須）
1.0.1

## DLC有無（必須）
なし

## MOD有無（必須）
なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
pm_anchorageを修正
