### ISSUE TITLE
【修正提案】利益団体

### ISSUE THREAD

**Issue by clamm0363** [matanki-saito/vic3jpadvmod#288]
※「｀｀｀」は消さないでください

## スクリーンショット（任意）
![image](https://user-images.githubusercontent.com/29382778/199526957-53e75188-fd41-439f-a530-964e30c3ecb8.png)

## 問題の用語（必須）

```
利益団体
```

## 英語版の表現（任意）

```
Interest Group
```

## 希望する変更（必須）

```
利益集団
```

## 変更の理由（必須）

特定の団体名ではなく、もっと広いグループを指しているため

## ゲームバージョン（必須）

1.0.4

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
上記のとおり修正しました

クローズします
