### ISSUE TITLE
海軍基地の方式　一括修正

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#289]
## スクリーンショット（任意）
![image](https://user-images.githubusercontent.com/37979626/199528401-01121286-1fff-4bf4-be94-6a66573e8e6f.png)
![image](https://user-images.githubusercontent.com/37979626/199528435-8514f5d6-025b-4402-98b0-042011c632f3.png)
![image](https://user-images.githubusercontent.com/37979626/199525182-2f015f5e-452d-47e2-8f8e-2f5db775c8ba.png)

## 問題の固有名詞（必須）
船のクラス　Ship Class
輸送船団護衛　Convoy Escorts
輸送船団レイダー　Convoy Raiders
　レイダー進撃　Commerce Raiders

## 希望する変更（必須）
Ship Class　艦種
Convoy Escorts　船団護衛
Convoy Raiders　船団襲撃
　Commerce Raiders　通商破壊船
## 変更の理由（必須）
誤訳

## ゲームバージョン（必須）
1.0.4

## DLC有無（必須）
なし

## MOD有無（必須）
なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
旗艦、随伴艦、襲撃艦、通商破壊船で修正
