### ISSUE TITLE
【未訳】currently

### ISSUE THREAD

**Issue by nakka8** [matanki-saito/vic3jpadvmod#29]
## スクリーンショット（必須）
![スクリーンショット (379)](https://user-images.githubusercontent.com/61678668/197951310-c9ac511b-7dbb-4f03-8dfe-d272a417203b.png)

## 問題のツールチップ（必須）

都市施設の建築

## 問題の表現（必須）

currently ￡1.65K

## 希望する変更（必須）

現在 ￡1.65K

## 変更の理由（必須）

未翻訳

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

Grand Edition付属のもの

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1034716763352485928
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by clamm0363** [comment]
修正しました。
「Currently hogehoge」となっていた2カ所を「現在 hogehoge」と表示されるように修正しています。

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。
