### ISSUE TITLE
【修正】ローワー・カナダ

### ISSUE THREAD

**Issue by clamm0363** [matanki-saito/vic3jpadvmod#290]
## スクリーンショット（任意）
![image](https://user-images.githubusercontent.com/29382778/199530130-40849af8-5785-4b20-bd51-9e26fd8911db.png)

## 問題の固有名詞（必須）

[全角スペース]ローワー・カナダ

## 希望する変更（必須）

ローワー・カナダ

## 変更の理由（必須）

不必要な全角スペースが国名の頭に入っているため

## ゲームバージョン（必須）

1.0.4

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
起票のとおりに修正しました。

クローズします
