### ISSUE TITLE
外交プレイの戦略に関するポップアップ

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#291]
## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/37979626/199533086-6e0f86ce-4303-4087-ac35-ca55d2c0de2c.png)

## 問題のあるインターフェイス（必須）
外交プレイ時の戦略アイコンのポップアップ

## 問題のテキスト（必須）
DIPLO_PLAY_MANEUVERS_INITIATOR_TOOLTIP```#header 先制国[戦略]#!\n[先制国名]に残された[戦略]は[数値]回です。```
DIPLO_PLAY_MANEUVERS_TARGET_TOOLTIP```#header 標的国[戦略]#!\n[標的国名]に残された[戦略]は[数値] 回です。```

## 希望する変更（必須）
```#header 先制国の[戦略]#!\n[先制国名]の[戦略]は残り[数値]です。```
```#header 標的国の[戦略]#!\n[標的国名]の[戦略]は残り[数値]です。```

## 変更の理由（必須）
数値なのに「回数」になってしまっているため

## ゲームバージョン（必須）
1.0.4

## DLCの有無（必須）
なし

## MODの有無（必須）
なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通り修正しました。
