### ISSUE TITLE
【修正提案】石油

### ISSUE THREAD

**Issue by clamm0363** [matanki-saito/vic3jpadvmod#292]
※「｀｀｀」は消さないでください
![image](https://user-images.githubusercontent.com/29382778/199539570-3a2f223c-fb27-416d-9dd8-124bc25a44d6.png)
## 問題の用語（必須）

```
石油
```

## 英語版の表現（任意）

```
Oil
```

## 希望する変更（必須）

```
燃油
```

## 変更の理由（必須）

クジラからも取れるため

## ゲームバージョン（必須）

1.0.4

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
上記修正しました。

クローズします
