### ISSUE TITLE
国家形成（大国の統一）のツールチップ一括修正

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#293]
## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/37979626/199537548-609cfa32-446d-40b1-8b11-bfa4f364763b.png)
![image](https://user-images.githubusercontent.com/37979626/199539352-8849b0d6-6145-48d5-8df3-f02410d35854.png)

## 問題のあるインターフェイス（必須）
国家形成（大国の統一）のツールチップ

## 問題のテキスト（必須）
FORM_COUNTRY_LAUNCH_UNIFICATION_PLAY```[コンセプト（プレイ）]統合の発足```
FORM_COUNTRY_CULTURE_COUNTRIES_HEADER```[対象文化圏] [コンセプト（国）]```
FORM_COUNTRY_STATE_REGIONS_HEADER```#v [必要数]#!の[形成国家名] [コンセプト（州地域）]中#v [現在数]#!を制圧しています```
FORM_COUNTRY_STATE_REGIONS_REQUIRED```[必要数]に支配されている[コンセプト（州地域）]が[形成国名]を築く必要があります```
CANNOT_FORM_COUNTRY_NOT_ENOUGH_STATES```#v [形成国家名]#!の形成に必要な[コンセプト（州地域）] #v [必要数]#!つのうち#v [現在数]#!のみを制圧しています:\n[必要州リスト]```
CAN_FORM_COUNTRY_DESC```#v [形成国家名]#!の形成に必要な[コンセプト（州地域）] #v [必要数]#!つのうち全#v [現在数]#!州を制圧しています:\n[必要州リスト]```
※[コンセプト（プレイ）]はconcept_diplomatic_play_short参照

## 希望する変更（必須）
```統一[プレイ]の開始```
```[対象文化圏]の[コンセプト（国）]```
```[形成国家名]の[コンセプト（州地域）]の#v [現在数]#!/#v [必要数]#!を支配しています```
```[形成国名]形成には[必要数]の[コンセプト（州地域）]を支配する必要があります```
```#v [形成国家名]#!形成に必要な[コンセプト（州地域）]#v [必要数]#!州の内#v [現在数]#!州のみ支配している：\n[必要州リスト]```
```#v [形成国家名]#!形成に必要な[コンセプト（州地域）]#v [必要数]#!州の内#v [現在数]#!州を完全に支配している：\n[必要州リスト]```

## 変更の理由（必須）
変数をうまく落とし込めていないため

## ゲームバージョン（必須）
1.0.4

## DLCの有無（必須）
なし

## MODの有無（必須）
なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
```CANNOT_FORM_COUNTRY_NOT_ENOUGH_STATES: #v [形成国家名]#!の形成に必要な[コンセプト（州地域）] #v [必要数]#!つのうち#v [現在数]#!のみを制圧しています:\n[必要州リスト]```

**Comment by matanki-saito** [comment]
ここはトリガー文ではなくcannotの理由を述べている部分なので
```ドイツの形成に必要な州地域19のうち、7しか支配していません：```

**Comment by inarizushi0309** [comment]
FORM_COUNTRY_STATE_REGIONS_REQUIREDについては数詞の都合上、
```[CountryFormation.GetName]形成には[Concept('concept_state_region', '$concept_state_regions$')]を[CountryFormation.GetNumRequiredStates|v]州支配する必要があります```
に修正案を変更しました
