### ISSUE TITLE
「スプリット」問題

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#295]
## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/37979626/199553649-b4dad697-f56c-4650-a906-e22a264b6925.png)
![image](https://user-images.githubusercontent.com/37979626/199553686-e67ac77f-981a-4a4c-b10d-d001ca729fae.png)
![image](https://user-images.githubusercontent.com/37979626/199553725-fcdb7573-8c79-4892-8690-c4f572052799.png)

## 問題のあるインターフェイス（必須）
文化>国家形成＞形成に必要な州の一覧

## 問題のテキスト（必須）
```スプリット```

## 希望する変更（必須）
```分割 / 分裂```

## 変更の理由（必須）
そもそもここの仕組みがかなりの力技で、国旗の下にもconcept_split_state_shortキーでSplitが入っている。それを別の判定で分裂状態でない場合は、領有国の国旗が上に重なるよう配置されるようになっている。そのため、「スプリット」という字が国旗の下に入り込んでいる。
これを解消するには全角2文字以内に収め、英語版同様、国旗の下に収まるようにしなければならないため、コンセプト名である「分割州」ではなく「分割」または「分裂」を使用しなくてならない。

## ゲームバージョン（必須）
1.0.4

## DLCの有無（必須）
なし

## MODの有無（必須）
なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
「分割」で修正しました
