### ISSUE TITLE
税率のツールチップ

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#296]
※「｀｀｀」は消さないでください

## スクリーンショット（必須）
![tax_desc](https://user-images.githubusercontent.com/50406316/199564961-4f3bf2c1-a8cf-42af-ad8a-92fedbbfdfcb.png)

## 問題のツールチップ（必須）
POPの税率のツールチップ

## 問題の表現（必須）

```
〇〇税に支払われる収入のXX%
（$TAX_TYPE$に支払われる収入の$TAX_LEVEL|%1v$）
```

## 問題箇所の英文（任意）

```
XX% of income paid in OO
（$TAX_LEVEL|%1v$ of income paid in $TAX_TYPE$）
```

## 希望する変更（必須）

```
収入のXX%を〇〇税で支払
（収入の$TAX_LEVEL|%1v$を$TAX_TYPE$で支払）
```

## 変更の理由（必須）
語順の誤りの修正

## ゲームバージョン（必須）
1.0.3

## DLC有無（必須）
なし

## MOD有無（必須）
JapaneseLanguageAdvancedMod(更新: 11月2日 @ 7時11分)

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
提案通り修正してクローズします
