### ISSUE TITLE
【修正提案】運動

### ISSUE THREAD

**Issue by clamm0363** [matanki-saito/vic3jpadvmod#297]
※「｀｀｀」は消さないでください

## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/29382778/199570912-450b9a0c-6670-4f73-ad01-24bf66a16c39.png)

## 問題のあるインターフェイス（必須）

選挙ウインドウ

## 問題のテキスト（必須）

```
[西暦年]運動
```

## 希望する変更（必須）

```
[西暦]年選挙戦
```

## 変更の理由（必須）

誤訳のため

## ゲームバージョン（必須）
1.0.4

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
上記修正しました

クローズします
