### ISSUE TITLE
【修正提案】ジーランド

### ISSUE THREAD

**Issue by Chechen0507** [matanki-saito/vic3jpadvmod#298]
## スクリーンショット（任意）
![20221103030611_1](https://user-images.githubusercontent.com/117307322/199567733-00091d8c-9ef2-4913-920d-3ac88eb84b8f.jpg)

## 問題の固有名詞（必須）

ジーランド

## 希望する変更（必須）

シェラン

## 変更の理由（必須）

画像でジーランドとされている地域は日本語では「シェラン」が最も一般的な名称であるため
## ゲームバージョン（必須）

1.0.4

## DLC有無（必須）

American Building Pack
VictoriaⅡRemastered Songs

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正しました。
クローズします。
