### ISSUE TITLE
国旗のツールチップ（Government, Military）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#299]
## スクリーンショット（必須）
![20221103035857_1](https://user-images.githubusercontent.com/42687608/199583296-41a8b63b-614f-403c-8396-4ab7ad5d80ef.jpg)

## 問題のツールチップ（必須）
国旗にカーソルを合わせたときのツールチップ

## 問題の表現（必須）
```
行政 / 軍事
```

## 問題箇所の英文（任意）
```
Government / Military
```

## 希望する変更（必須）
```
政府 / 陸軍
```

## 変更の理由（必須）
Governmentは政体を意味しており、他の部分の翻訳と整合性を取るなら「政府」となる。
Militaryは直訳としては正しいが、アイコンや直後に海軍があることから考えると「陸軍」が適切。

## ゲームバージョン（必須）
1.0.4

## DLC有無（必須）
- Victoria II Remastered Soundtrack
- American Buildings Pack

## MOD有無（必須）
- 自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
原案の通り修正を完了しました。
