### ISSUE TITLE
【修正提案】モディファイア

### ISSUE THREAD

**Issue by nakka8** [matanki-saito/vic3jpadvmod#30]
## スクリーンショット（必須）
![スクリーンショット (380)](https://user-images.githubusercontent.com/61678668/197952691-a0d9104e-f214-4b92-a873-838c9f9c3e21.png)

## 問題のツールチップ（必須）

海軍の軍艦にマウスオーバーしたところ

## 問題の表現（必須）

モディファイア

## 問題箇所の英文（任意）

modifierと推測

## 希望する変更（必須）

補正

## 変更の理由（必須）

モディファイアと言われても正直分かりません。ググっても専門用語ばかり出てきます。

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

Grand Editon付属のもの

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1034718999881191454
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by clamm0363** [comment]
修正しました。
「モディファイア」が「補正」と表示されるように修正しています。
