### ISSUE TITLE
オセアニア、南北アメリカ、一部ヨーロッパの都市名

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#300]
## 問題の固有名詞と希望する変更（必須）

タウンスビル：タウンズビル
トゥーウーンバ：トゥーンバ
カサリン：キャサリン
ジャブリ：ジャビルー
ペルス：パース
ポート・ヘッドランド：ポートヘッドランド
バンブリー：バンバリー
ポート・ピリー：ポートピリー
クーバー・ペディ：クーバーペディ
ターコーラ：タークーラ
ミルドゥラ：ミルデューラ
アルムダール：アームデール
ポート・アルバート：ポートアルバート
ワーナンブール：ウォーナンブール
バリンスデール：バーンズデール
ラウンセストン：ローンセストン
ストラハン：ストラーン
ブレンハイム：ブレナム
アウクランド：オークランド
ナピエ：ネーピア
パルメルストン：パーマストン
ファンガレイ：ファンアーレイ
タフナ：ターフナ
ナディ：ナンディ
ラバサ：ランバサ
コウマク：コマク
ノウメア：ヌメア
オウベア：ウヴェア
ポルト・バト：ポート＝ヴァト
ルガンビル：ルーガンビル
フォラーリ：フォラリ
ウォジェ：ウォッジェ
ヌクヒヴァ：ヌク・ヒバ
カイルアコナ：カイルア・コナ
プリンセビル：プリンスヴィル

イーサフィヨルズル：イーサフィヨルズゥル
ブレンドゥオス：ブリョンドゥオゥス
アクレイリ：アークレイリ
エギルスタディール：エイイルススタジル
ゴットハフン：ゴズハウン
キルケスピルダーレン：キアゲスピルデーレン
カンゲルルススアーク：スンラ・ストラムフィヨーア
フィスケナッセト：フィスケネスズ
セントジョージ：セントジョージズ
フラッツ・ビレッジ：フラッツヴィレッジ
サマーセット・ビレッジ：サマセットヴィレッジ
アングラ・ド・ヘロイスモ：アングラ・ド・エロイズモ
ホルタ：オルタ

セントジョン：セントジョンズ
シェシャツィウ：シェハツィウ
シクティミ：シクーティミ
シャーブルック：シェルブルック
バル・ドール：ヴァルドール
サッドブリー：サドバリー
フォート・ダグラス：フォートダグラス
ホエール・コーブ：ホエール・コーヴ
フォート・レゾリューション：フォートレゾリューション
フォート・スミス：フォートスミス
フォート・プロビデンス：フォートプロヴィデンス
レギーナ：レジャイナ
フォート・エドモントン：フォートエドモントン
フォート・マックマレー：フォートマクマレー
バンダーホーフ：バンダーフーフ
フォート・ネルソン：フォートネルソン
イヌビク：イヌヴィック
カルマクス：カーマクス
ヴァルデズ：ヴァルディーズ

アウグスタ：オーガスタ
ザ・フォーク：ザフォークズ
バンゴール：バンゴー
コンコルド：コンコード
モンペリエ：モントピリア
ルドロウ：ラドロー
ジェームスタウン：ジェームズタウン
ニューヘブン：ニューヘイブン
ビンハントン：ビンガムトン
アルバニー：オールバニ
モーリスタウン：モリスタウン
アンナポリス：アナポリス
フレドリックスバーグ：フレデリックスバーグ
ホルダービー・ランディング：ホルダービーズ・ランディング
コロンブス：コロンバス
アテネ：アセンズ
トレド：トリード
オー・クレア：オークレア
ペオリア：ピオリア
エバンスビル：エバンズビル
ルイスビル：ルイビル
ラレイグ：ローリー
メコン：メイコン
アウグスタ：オーガスタ
バーミンガム：バーミングハム
ビロクシー：ビロクシ
トゥペロ：テューペロ
トゥルサ：タルサ
イダベル：アイダベル
マックアレスター：マカレスター
ケープ・ジラードー：ケープジラード
トペカ：トピカ
ロワシティ：アイオワシティ
アイツキン：エイキン
ピエール：ピア
ビスマルク：ビズマーク
ミノット：マイノット
リードビル：レッドビル
アルブクエルク：アルバカーキ
ルイドース：ルイドソ
トゥクソン：ツーソン
ホルブルック：ホルブロック
ソルトレークシティ：ソルトレイクシティ
レノ：リノ
カンデラリア：キャンディラリア
ボイス：ボイシ
カー・ダレーン：コー・ダリーン
ベリンガム：ベリンハム

サンクエンティン：サン・ケンティン
メキシカリ：メヒカリ
カボ・サン・ルーカス：カボ・サン・ルカス
サンタローゼリア：サンタ・ロサリア
ノヴォジョア：ナボホア
シフアフア：チワワ
ジメネズ：ヒメネス
クアウテモック：クアウテモク
サンチアゴ・パパスキアロ：サンティアゴ・パパスキアロ
エルサルト：エル・サルト
モンテレリー：モンテレイ
シウダード・ヴァレス：シウダー・バージェス
シウダード・ヴィクトリア：シウダー・ビクトリア
ザカテカス：サカテカス
フレスニヨ：フレスニジョ
ジャルパ：ハルパ
ヴァルパライソ：バルパライソ
サンルイスポトシ：サン・ルイス・ポトシ
グアナジュアト：グアナフアト
シウダード・ヴァレス：シウダー・バージェス
フチタン・デ・ザラコザ：フチタン・デ・サラゴサ
エル・フォルテ：エル・フエルテ
グアダラジャ：グアダラハラ
プレルト・ヴァラルタ：プエルト・バジャルタ
チルパンチンゴ：チルパンシンゴ
ジフアタネジョ：シワタネホ
チルパンチンゴ：チルパンシンゴ
ヴェラクルズ：ベラクルス
ジャラパ：ハラパ
パヨオビスポ：パヨ・オビスポ
エスキンツラ：エスクイントラ

ベリーゼ・シティ：ベリーズシティ
アカジュツルア：アカフトラ
プレルト・コルテス：プエルト・コルテス
サン・ペドロ・スラ：サン・ペドロ・スーラ
シナンデーガ：チナンデガ
サンノゼ：サンホセ
デイヴィド：ダビド
カルタゲナ：カルタヘナ
ブエナヴェンツラ：ブエナベントゥラ
ネイヴァ：ネイバ
トゥンジャ：トゥンハ
イバギュー：イバゲー
マニザレス：マニサレス
ヴィラビセンチオ：ビジャビセンチオ
フローレンシア：フロレンシア
サン・ホセ・デル・グアビアレ：サン・ホセ・デル・グアビアーレ
プレルト・カレーノ：プエルト・カレーニョ
サン・フェルナンド・ド・アプール：サン・フェルナンド・デ・アプレ
カイエン：カイエンヌ
ノイゲダハト：ノイトヘダフト
ベレム：ベレン
サン・セバスチアン：サン・セバスティアン
ボア・ビスタ：ボア・ヴィスタ
カンポグランデ：カンポ・グランデ
カロリーナ：カロリナ
インペラトリズ：インペラトリス
マカオ：マカウ
パレルハス：パレリャス
ジャボアタオ：ジャボアタン
イルヘウス：イリェウス
ベロ・ホリゾンテ：ベロオリゾンテ
パトス・ド・ミナス：パトス・デ・ミナス
リベイラオ・プレト：リベイロン・プレト
ヴィトリア：ヴィトーリア
マンフアク：マニュアス
ジュイス・デ・フォラ：ジュイス・デ・フォーラ
サオ・パウロ：サンパウロ
クリティバ：クリチバ
カスカベル：カスカヴェル
クルツアルタ：クルスアルタ
プンタ・デル・エスタ：プンタ・デル・エステ
バーゲ：バジェ
サン・ゴンカロ・デ・アマランテ：サン・ゴンサーロ・デ・アマランテ
イグアツ：イグアトゥ
クリティバノス：クリチバノス
ロドリゲス・アルベス：ロドリゲス・アルヴェス
パラヒバ：パライバ
ジュアゼリンホ：ジュアゼリニョ
バヒア・ブランカ：バイアブランカ
トレス・アロイス：トレス・アロヨス
ザラーテ：サラテ
ゴーヤ：ゴヤ
エスキーナ：エスキナ
レジステンシア：レシステンシア
モンテ・クエマド：モンテ・ケマド
ジュジュイ：フフイ
クイネス：キネス
メンドーザ：メンドーサ
サン・ユアン：サンフアン
ネウクエン：ネウケン
サンジュリアン：サンフリアン
ザパラ：サパラ
スタンレー：スタンリー
プンタ・アレナス：プンタ・アレーナス
プエルト・モント：プエルトモント
コイハケ：コイアイケ
ヴァルディヴィア：バルディビア
ヴィラリカ：ビジャリカ
ヴァルパライソ：バルパライソ
トコピラ：トコピジャ
サンタ・クルツ：サンタクルス
サント・コラゾン：サント・コラソン
ポゾ・コロラド：ポソ・コロラド
ドクトール・ペドロP.ペーニャ：ドクトル・ペドロ・ペ・ペーニャ
ペドロ・ジュアン・カバレロ：ペドロ・フアン・カバリェロ
ヴィアチャ：ビアチャ
トリニダード：トリニダ
イクイク：イキケ
ハンバーストーン：ウンベルストネ
モレンド：モジェンド
アヤクチョ：アヤクーチョ
カラオ：カヤオ
フアンカヨ：ワンカヨ
プカラパ：プカルパ
フアヌコ：ワヌコ
トルヒーヨ：トルヒージョ
チクラヨ：チクラーヨ
イクイトス：イキトス
サン・ロレンツォ：サン・ロレンソ
サンティアゴ・デ・キューバ：サンティアゴ・デ・クーバ
サンタ・クララ：サンタ・クラーラ
ナッサウ：ナッソー
ニコルスタウン：ニコールズタウン
カプ・アイシアン：カパイシャン
ポルタウプリンス：ポルトープランス
コルニロン：コルニヨン
ハクメル：ジャクメル
レス・ケイス：レカイ
サンティアゴ・デ・ロス・カバレロス：サンティアゴ・デ・ロス・カバリェロス
サント・ドミンゴ：サントドミンゴ
ラ・ヴェガ：ラベガ
ポンケ：ポンセ
サン・ユアン：サンフアン
サン・ピエール：サン＝ピエール
ブラッサテッレ：ブラサ・テレ

ミディナ：イムディーナ

## 変更の理由（必須）
日本語では一般的ではない表記であるため。

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
