### ISSUE TITLE
小国 Insignificant

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#301]
※「｀｀｀」は消さないでください

## スクリーンショット（必須）
![insignificant_ja](https://user-images.githubusercontent.com/50406316/199649783-7c388650-b180-4936-b683-1f5ada0261f9.png)
![insignificant_en](https://user-images.githubusercontent.com/50406316/199649789-6e5db154-fd75-4b71-b056-a805e8199861.png)

## 問題のあるインターフェイス（必須）
小国

## 問題のテキスト（必須）

```
Insignificant
```

## 希望する変更（必須）

```
僅か、僅少など
```

## 変更の理由（必須）
州画面で失業者がごくわずかであることを意味するツールチップなのだが、国ランクの小国を表すInsignificantと共通のものを使っており、ここだけを修正したくても修正できない。
備忘としてissueを挙げておく。

## ゲームバージョン（必須）
1.0.4

## DLCの有無（必須）
なし

## MODの有無（必須）
JapaneseLanguageAdvancedMod(更新: 11月2日 @ 7時11分)

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。
