### ISSUE TITLE
コミュニスト

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#302]
## スクリーンショット（任意）

なし

## 問題の固有名詞（必須）

コミュニスト

## 希望する変更（必須）

共産主義者/共産主義

## 変更の理由（必須）

「共産主義」と表記揺れを起こしているため、より馴染み深い方にする。

## ゲームバージョン（必須）

1.0.4

## DLC有無（必須）

なし

## MOD有無（必須）

日本語修正MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
