### ISSUE TITLE
【修正提案】 未就業者 unemployed

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#303]
※「｀｀｀」は消さないでください

## スクリーンショット（任意）
![insignificant_ja](https://user-images.githubusercontent.com/50406316/199650638-43b191d7-9797-4de0-bf07-0acd963e33c6.png)

## 問題の用語（必須）

```
未就業者
```

## 英語版の表現（任意）

```
unemployed
```

## 希望する変更（必須）

```
失業者
```

## 変更の理由（必須）
未就業者とすると通常は働いたことが無い学生や既卒無職者などを指し、就業経験のある失業者は含まないことが多い。
ゲームの用法は単に失業しているPOPを指すので、失業者とするほうが適切。

## ゲームバージョン（必須）
1.0.4

## DLC有無（必須）
無し

## MOD有無（必須）
JapaneseLanguageAdvancedMod 【修正提案】更新: 11月3日 @ 7時10分

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
提案通り改訳でクローズします。
