### ISSUE TITLE
扶養者（Dependent）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#304]
## スクリーンショット（任意）
![20221103143953_1](https://user-images.githubusercontent.com/42687608/199655027-4751a2ab-f634-45da-bdb2-f1809223b7e3.jpg)

## 問題の用語（必須）
```
扶養者
```

## 英語版の表現（任意）
```
Dependent
```

## 希望する変更（必須）
```
被扶養者
```

## 変更の理由（必須）
誤訳により意味が逆になっているため。

## ゲームバージョン（必須）
1.0.4

## DLC有無（必須）
- Victoria II Remastered Soundtrack
- American Buildings Pack

## MOD有無（必須）
- 自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
「被扶養者」に決定し、修正を完了しました。
