### ISSUE TITLE
「Samurai」と「Gentry Assembly」

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#305]
## スクリーンショット（任意）
![20221103142510_1](https://user-images.githubusercontent.com/38329957/199653211-65d882c5-54c9-4c6e-a5f4-3608bc8fd2bb.jpg)
![20221103142526_1](https://user-images.githubusercontent.com/38329957/199653236-8701aec8-1eb0-4e5a-a44a-e1190b014184.jpg)

## 問題の用語（必須）

```
侍
上流階級会合
```

## 英語版の表現（任意）

```
Samurai
Gentry Assembly
```

## 希望する変更（必須）

```
武士
貴族会議
```

## 変更の理由（必須）

Samuraiは日本語的な表現では武士とすることが一般的なため、Gentry Assemblyはロシア語的に誤訳であるため。

## ゲームバージョン（必須）

1.0.4

## DLC有無（必須）

なし

## MOD有無（必須）

日本語修正MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
