### ISSUE TITLE
【本体バグ】下層階級の生活水準の平均期待値（最小）「STATE_EXPECTED_SOL_POOR」

### ISSUE THREAD

**Issue by WoodlandsGitHub** [matanki-saito/vic3jpadvmod#306]
## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/29177147/199659962-75bd919b-2ad2-47d3-a3d5-1acb01236db7.png)

## 問題のツールチップ（必須）

各州画面＞人口タブ＞生活水準の下層階級のアイコン＞平均期待値（最小）の数値をマウスオーバー

## 問題の表現（必須）

変数がそのまま表示されている
```
STATE_EXPECTED_SOL_POOR
```

## 問題箇所の英文（任意）

英文も同じ状態
```
STATE_EXPECTED_SOL_POOR
```

## 希望する変更（必須）
他の階級では正常に表示されてるので、それに倣って表示されてほしい
![image](https://user-images.githubusercontent.com/29177147/199660405-836e2549-3ae6-4d58-9f6a-735701b3d008.png)
```

```

## 変更の理由（必須）

変数がそのまま表示されているので

## ゲームバージョン（必須）

1.0.4

## DLC有無（必須）

なし

## MOD有無（必須）

日本語改善MOD
Switch Languages

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
報告しました
https://forum.paradoxplaza.com/forum/threads/victoria-iii-localization-bug.1558600/

**Comment by matanki-saito** [comment]
報告したためCloseとします
