### ISSUE TITLE
宿命の宣言（Manifest Destiny、ディシジョン）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#307]
## スクリーンショット（任意）
![20221103153727_1](https://user-images.githubusercontent.com/42687608/199660594-9a1d4af8-7d31-4839-9a1a-b1bd275c9333.jpg)

## 問題部分（タイトル・本文・選択肢）
```
アメリカ専用ディシジョンのタイトル
```

## 問題のイベントタイトル（必須）
```
宿命の宣言
```

## 問題のイベント本文（任意・抜粋可）
```
```

## 問題のイベント選択肢（任意）
```
```

## 希望する変更（必須・修正部分のみ）
```
マニフェスト・デスティニー
または、明白なる使命、明白なる運命、明白な天命、明白なる大命など。
```

## 変更の理由（必須）
定訳のある歴史的な用語であるため。
現在の翻訳ではなんのことだか伝わらない。

## プレイ国家
アメリカ合衆国

## ゲームバージョン（必須）
1.0.4

## DLC有無（必須）
- Victoria II Remastered Soundtrack
- American Buildings Pack

## MOD有無（必須）
- 自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
「マニフェスト・デスティニー」に決定し、修正を完了しました。
