### ISSUE TITLE
【修正提案】利益集団の態度ツールチップ

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#309]
※「｀｀｀」は消さないでください

## スクリーンショット（必須）

![20221103150930_1](https://user-images.githubusercontent.com/42710893/199663926-cd12aec2-91e8-4563-8b61-952d856c0a6a.jpg)

## 問題のツールチップ（必須）

利益集団の態度ツールチップ

## 問題の表現（必須）

```
スクショの例では
地主は君主制を強く賛成
```

## 問題箇所の英文（任意）

```
```

## 希望する変更（必須）

```
地主は君主制に強く賛成
```

## 変更の理由（必須）

日本語として自然なものにしたい。

## ゲームバージョン（必須）

1.0.4

## DLC有無（必須）

なし

## MOD有無（必須）

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
ご提案どおり、「を」から「に」へと修正しました。

クローズします。
