### ISSUE TITLE
【未訳】interest

### ISSUE THREAD

**Issue by nakka8** [matanki-saito/vic3jpadvmod#31]
## スクリーンショット（必須）
![スクリーンショット (381)](https://user-images.githubusercontent.com/61678668/197956988-235b321a-fd22-43ee-a957-e628b88c1a36.png)

## 問題のツールチップ（必須）

国のモディファイアの貸付歩合

## 問題の表現（必須）

interest率

## 希望する変更（必須）

利子率もしくは利率

## 変更の理由（必須）

未訳なんですが、interestにツールチップが付属しているので最善が分かりません。あとinterestのツールチップのタイトルも利益より利子の方がいいかもしれません。

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

Gland Edition付属

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1034724789572599868
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by clamm0363** [comment]
修正しました
interest: 利子、interest rate: 利子率となるように修正しています。
