### ISSUE TITLE
【修正提案】関心発動フィード

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#310]
※「｀｀｀」は消さないでください

## スクリーンショット（必須）

![20221103152433_1](https://user-images.githubusercontent.com/42710893/199665195-802af377-1811-4667-8921-70751c7029c3.jpg)

## 問題のあるインターフェイス（必須）

関心発動時のフィード

## 問題のテキスト（必須）

```
notification_interest_activated_third_party_name:0 "[SCOPE.sCountry('actor').GetAdjective] [SCOPE.GetRootScope.GetInterest.GetStrategicRegion.GetName] [concept_interest]が発動しました"
英語：notification_interest_activated_name:0 "[SCOPE.GetRootScope.GetInterest.GetStrategicRegion.GetName] [concept_interest] activated
```

## 希望する変更（必須）

```
"[SCOPE.sCountry('actor').GetAdjective]が[SCOPE.GetRootScope.GetInterest.GetStrategicRegion.GetName]に対する[concept_interest]を発動"　等
自国が発動した場合（notification_interest_activated_name:0）も同様に修正が必要
「発動」という訳も適当かどうか要検討と思われる
```

## 変更の理由（必須）

日本語として自然な表現にするため。

## ゲームバージョン（必須）

1.0.4

## DLCの有無（必須）

なし

## MODの有無（必須）

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
ご指摘の通り修正しました。ありがとうございます。関心は「表明」にしました。
修正完了したのでクローズします
