### ISSUE TITLE
【修正提案】雇用する将軍/提督の選択画面の「司令する」

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#311]
※「｀｀｀」は消さないでください

## スクリーンショット（必須）

![20221103150730_1](https://user-images.githubusercontent.com/42710893/199666503-4c18050f-b4ad-45e8-b2e6-468c7dec1261.jpg)
![20221103150805_1](https://user-images.githubusercontent.com/42710893/199667384-8292195d-ed03-4969-a21b-6331d341f115.jpg)

## 問題のあるインターフェイス（必須）

雇用する将軍/提督の選択画面

## 問題のテキスト（必須）

```
RECRUIT_COMMANDERS_CHARACTERS_POPUP:0 "司令する$DESC$"
英語版：RECRUIT_COMMANDERS_CHARACTERS_POPUP:0 "Will Command $DESC$"
```

## 希望する変更（必須）

```
"$DESC$を指揮予定"　等
```

## 変更の理由（必須）

英語表記を見る限り、雇用した場合に指揮する大隊/艦艇の数を示していると思われますが
現状では意味がわかりにくいです。

## ゲームバージョン（必須）

1.0.4

## DLCの有無（必須）

なし

## MODの有無（必須）

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。
