### ISSUE TITLE
砂糖農園

### ISSUE THREAD

**Issue by clamm0363** [matanki-saito/vic3jpadvmod#312]
※「｀｀｀」は消さないでください

## スクリーンショット（任意）
![image](https://user-images.githubusercontent.com/29382778/199673447-213ab13f-c432-404d-afb4-f96f84aff1de.png)
## 問題の用語（必須）

```
砂糖農園
```

## 英語版の表現（任意）

```
Sugar Plantation
```

## 希望する変更（必須）

```
サトウキビ農園
```

## 変更の理由（必須）

ゲーム的な命名でイマーシヴではないため

## ゲームバージョン（必須）

1.0.4

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
議論の結果、現行訳の「砂糖農園」のままとすることに決まりました。

クローズします。
