### ISSUE TITLE
綿農園

### ISSUE THREAD

**Issue by clamm0363** [matanki-saito/vic3jpadvmod#313]
※「｀｀｀」は消さないでください

## スクリーンショット（任意）
![image](https://user-images.githubusercontent.com/29382778/199673713-6ecc236f-f2b2-477b-9611-ffad82dda034.png)
## 問題の用語（必須）

```
綿農園
```

## 英語版の表現（任意）

```
Cotton Plantations
```

## 希望する変更（必須）

```
綿花農園
```

## 変更の理由（必須）

ゲーム的な命名でイマーシヴではないため

## ゲームバージョン（必須）

1.0.4

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
上記のとおり修正しました。

クローズします。
