### ISSUE TITLE
「ギリシャ領 The Greek State」イベント

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#314]
※「｀｀｀」は消さないでください

## スクリーンショット（任意）
![the_greek_state](https://user-images.githubusercontent.com/50406316/199673134-1dfc8ea0-aec5-4830-bfc9-966424699154.png)

## 問題部分（タイトル・本文・選択肢）

```
ギリシャ領
```

## 問題のイベントタイトル（必須）

```
ギリシャ領
原文はThe Greek State
```

## 問題のイベント本文（任意・抜粋可）

```
変更なしのため省略
```

## 問題のイベント選択肢（任意）

```
変更なしのため省略
```

## 希望する変更（必須・修正部分のみ）

```
タイトルを「ギリシャ領」から「ギリシャ国家」に変更
```

## 変更の理由（必須）
ギリシャがナショナリズムを発明すると起きるイベントで、北のマケドニアやトラキアなどギリシャ人が住むトルコ領に領有権を主張する。
本文中にも「ギリシャ国家～～」と書いてあり、ギリシャ人国家の拡大を目論むイベントなので、Stateは領ではなく国家と訳すほうが適切と思える。

## プレイ国家
ギリシャ

## ゲームバージョン（必須）
1.0.4

## DLC有無（必須）
なし

## MOD有無（必須）
翻訳改善MOD(11/3)

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
提案通り変更してクローズします
