### ISSUE TITLE
左派 - ○○を制定

### ISSUE THREAD

**Issue by clamm0363** [matanki-saito/vic3jpadvmod#316]
※「｀｀｀」は消さないでください

## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/29382778/199680240-77612700-8900-421e-b745-340790df6d00.png)
## 問題のあるインターフェイス（必須）

フィード

## 問題のテキスト（必須）

```
[利益集団] - 左派 [法律名]を制定（「[法律名]を制定」部分は「[法律名]の制定」に修正見込み）
```

## 希望する変更（必須）

```
[利益集団] - [法律名]の制定運動から離脱
```

## 変更の理由（必須）

誤訳のため

## ゲームバージョン（必須）

1.0.4

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
上記のとおり修正しました。
