### ISSUE TITLE
【改善提案】制定（180日ごとに16%の確率）

### ISSUE THREAD

**Issue by WoodlandsGitHub** [matanki-saito/vic3jpadvmod#317]
## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/29177147/199673601-32ebae09-6269-4e29-be1a-b54b0f898da1.png)

## 問題のあるインターフェイス（必須）
政策ウィンドウ＞法律タブ＞（政府の原則や経済システム等の選択）

## 問題のテキスト（必須）

```
制定（180日ごとに16%の確率）
```

## 希望する変更（必須）

```
制定（成功率16％：180日ごとに判定）
```

## 変更の理由（必須）

![image](https://user-images.githubusercontent.com/29177147/199675700-f011f930-6a5a-4b4a-ab94-19e1acda7d6b.png)
英語の場合と同様に、文中の「制定」と「成功率」の位置を近づけることで、制定の成功率を示したものだとより端的に示したい。
加えて、（他で起票するが）成功率が０％の場合に表示される文章中の文言（The chance that ...)と訳を揃えて同じ用語「制定成功率」を指していることを示したい。
![image](https://user-images.githubusercontent.com/29177147/199683683-58abe4e5-2855-499a-9342-9ecb2ee2398e.png)

## ゲームバージョン（必須）

1.0.4

## DLC有無（必須）

なし

## MOD有無（必須）

日本語改善MOD
Switch Languages

**Comment by clamm0363** [comment]
ご提案どおり修正しました。

クローズします
