### ISSUE TITLE
陸軍のPMG一括決定

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#318]
## スクリーンショット（任意）

![20221103143759_1](https://user-images.githubusercontent.com/43299334/199687934-04bbedac-4ed7-4cbf-bbbc-255cdb168d5e.jpg)
![20221103143801_1](https://user-images.githubusercontent.com/43299334/199687962-0e93992f-5cf8-4a49-81f8-e53efb863111.jpg)
![20221103143803_1](https://user-images.githubusercontent.com/43299334/199687970-0251f826-6f8d-4195-9594-aa3ee283d8a6.jpg)
![20221103143805_1](https://user-images.githubusercontent.com/43299334/199687981-fbc251c4-f6cb-456a-a2ab-ca975ff906d7.jpg)
![20221103143807_1](https://user-images.githubusercontent.com/43299334/199687994-b792c5f2-8490-446a-b613-b4bd1accba6b.jpg)

## 問題の用語（必須）

```
組織化
砲撃支援
偵察
専門部隊
医療救護
```

## 英語版の表現（任意）

```
Organization
Artillery Support
Reconaissance
Specialist Companies
Medical Aid

```

## 希望する変更（必須）

```
基本編成
支援火砲
偵察部隊
特殊部隊
医療支援
```

## 変更の理由（必須）

やや不自然な日本語のため
参考のため、各PMG配下のPMを書いておきます
こちらも修正が必要だと思いますが別issueで
組織化
　非正規軍
　戦列歩兵
　散兵
　塹壕歩兵
　分隊
　機械化歩兵
砲撃支援
　歩兵集中
　カノン砲
　騎馬砲兵
　榴散弾砲
　攻城砲
偵察
　斥候騎兵
　自転車伝令
　自動偵察
　航空偵察
専門部隊
　標準的な歩兵
　機関銃手
　潜入者
　火炎放射部隊
　化学兵器専門部隊
医療救護
　創傷包帯
　応急手当
　野戦病院

## ゲームバージョン（必須）

1.0.4

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
基本編成、支援火砲、偵察部隊、特殊部隊、医療支援
で修正しました
