### ISSUE TITLE
アフリカの都市名

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#319]
## 問題の固有名詞と希望する変更（必須）

サルレイ：サル・レイ
サオ・フィルペ：サンフィリペ
サンタ・クルツ：サンタクルス
フンチャル：フンシャル
ポルトモニズ：ポルトモニス
エストレイト・ダ・カルヘタ：エストレイト・ダ・カリェタ

タンギエルス：タンジェ
タザ：ターザ
オウダ：ウジダ
クサル・エル・ケビル：クサール・エル・ケビール
グエルミム：ゲルミン
エラチディア：エルラシディア
カルザザテ：ワルザザート
ティズニト：ティーズニート
エス・セマラ：エッ＝スマラ
サングレイブ：サングラヴ
アクジョウト：アクジュージト
フデリク：フデリック
ゴウルマ・ラハロウス：グルマ・ラルス
ボルジ・モクタル：ボルジュ・モウタール
ティミアオウイン：ティミャオウィン
ティン・ザオウティン：ティン・ザウティン
ガーラダイア：ガルダイア
ティミモウン：ティミムン
エル・オウド：エル・ウェッド
バツナ：バトナ
ミラー：ミラ

カッセリネ：カスリーヌ
サブハ：セブハ
タジルブ：タゼルボ
アジダビヤ：アジュダービヤー
アズ・ズワイティナ：アッ＝ズウェティナ
シルテ：スルト
アル・バイダ：アル・バイダー
エル・サロウム：アッ＝サルーム
シディ・バッラニ：シーディ・バラーニ
ゲベル・イウェイビド：ジェベル・イウェイビド
エル・トゥール：エルトール
ネケル：ネヘル
アリーシ：アリーシュ
アシュト：アシュート
ソハグ：ソハーグ
バッラミヤ：バッラーミーヤ
エル・カールガ：エル・ハルガ
ポート・スーダン：ポートスーダン
ワディ・ハルファ：ワジハルファ
カドゥグリ：カードゥクリー
カートゥム：ハルツーム
ワディ・メダニ：ワドメダニ
メルト：メルート
デッシー：デセ
バヒル・ダール：バハルダール
アンコベール：アンコベル
ガルカヨ：ガルカイヨ
カルデョ：カルド
グールー：グル
ダル・エス・サラーム：ダルエスサラーム
トゥレアール：テュレアール
イホロンベ：イフルンベ
モロンダバ：ムルンダヴァ
タナナリブ：タナナリヴ
タマタベ：タマタヴ
サマババ：サンバヴァ
ディエゴ・スアレズ：ディエゴ・スアレス
セント・デニス：サン＝ドニ
ポート・ルイス：ポートルイス
クレピペ：キュールピップ
クアトル・ボルネス：カトル・ボルヌ
セント・ピエール：サン・ピエール
リチンガ：リシンガ
カサマ：カザマ
フワンジェ：ワンゲ
チモイオ：シモイオ
マピンハネ：マピニャネ
サイサイ：シャイシャイ

ルクスビル：ルーヴィル
マルゲート：マルギット
グラハムスタウン：グラハムズタウン
グラーフ・ライネット：グラーフ＝ライネ
スプリングボク：スプリングボック
ブリスタウン：ブリッツタウン
ダ・アール：デ・アール
ルーデリッツ：リューデリッツ
ガーンジ：ハンツィ
オツジワロンゴ：オティワロンゴ
フアンボ：ウアンボ
アンブリズ：アンブリス
サオ・サルバド：サン・サルヴァドール
ケンゲ：ケンジュ
ムウェネ・ディト：ムワンヌ・ディトゥ
エクエタービル：エクアトゥールヴィル
ボエンデ：ブエンデ
ゲマナ：ゲメナ
ブラッザビル：ブラザヴィル
キバンゴウ：キバングー
オウエッソ：ウェッソ
リブレビル：リーブルヴィル
ポート・ジェンティル：ポールジャンティ
フォウガモウ：フガムー
マココウ：マコクー
イエオンデ・ステーション：イェオンデ・ステーション
ポート・クラレンス：ポールクラランス
ヌガオウンデレ：ンガウンデレ
ヌガオウンダル：ンガウンダル
ボッサンゴア：ボサンゴア
ワウ：ワーウ
エル・ファシャー：エル＝ファーシル
マッサコリー：マッサコリ
アガデズ：アガデス
アルリト：アーリット
ジンダー：ザンデール
ディッファ：ディファ
ボンゴール：ボンゴル
サル：サール
カラバール：カラバル
ポート・ハーコート：ポートハーコート
オニツシャ：オニチャ
ジャクパ：ジェイクパ
ピズヒ：パイジ
オンドゥ：オンド
ポルト・ノボ：ポルトノボ
ダパオン：ダパング
アタクパム：アタクパメ
タマール：タマレ
ブーナ：ブナ
フェルケッセドーグー：フェルケセドゥーグー
コルホゴ：コロゴ
クードーグー：クドゥグ
ソレンゾ：ソランゾ
シカッソ：シカソ
カイェス：カイ
クーリコロ：クリコロ
セントルイス：サン＝ルイ
ビグノナ：ビニョナ
ラーベ：ラベ
ボーケ：ボケ
グバルンガ：バルンガ
ドゥエクエ：デコエ

コスタ・アデジェ：コスタ・アデヘ
フンチャル：フンシャル
ポルトモニズ：ポルトモニス

## 変更の理由（必須）

日本語では一般的ではない表記であるため。

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
