### ISSUE TITLE
【修正提案】建設状況のパネル（非建設時）

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#32]
## スクリーンショット（必須）
![20221026092813_1](https://user-images.githubusercontent.com/43299334/197972330-489c8717-d06d-4444-ae68-fee4a3772d17.jpg)

## 問題のあるインターフェイス（必須）

右上、速度設定の下、建設状況のパネル（非建設時）

## 問題のテキスト（必須）

建設中はありません

## 希望する変更（必須）

建設中の施設はありません

## 変更の理由（必須）

日本語として違和感があるため。
変数を使っていると思われ、修正には注意が必要。

## ゲームバージョン（必須）

1.0.3

## DLCの有無（必須）

なし

## MODの有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1034743343567089664
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by Zousuikakka** [comment]
「建設中の施設はありません」に修正しました

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。
