### ISSUE TITLE
【修正および改善提案】「（法案）が制定される可能性は、…」

### ISSUE THREAD

**Issue by WoodlandsGitHub** [matanki-saito/vic3jpadvmod#320]
## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/29177147/199690502-ac625d5a-a79f-4765-8498-e7edee2862aa.png)
![image](https://user-images.githubusercontent.com/29177147/199685024-4929af94-78ac-4188-969d-bc26a807b355.png)
## 問題のツールチップ（必須）

政策ウィンドウ＞法律タブ＞（政府の原則や経済システム等の選択）＞制定成功率０％の法案の制定ボタンをマウスオーバー

## 問題の表現（必須）

```
（法案）が制定される可能性は、利益団体政府内、政治運動、またはあなたの支配者のイデオロギーの支持により0%以上である必要があります。
```

## 問題箇所の英文（任意）

```
The chance that ... can be enacted must be above 0% through support from either an Interest Group In Government, a Political Movement or your Ruler's Ideology.
```

## 希望する変更（必須）

```
（法案）の制定成功率が0%を上回らなければなりません。そのために、政府内利益団体、政治運動、統治者のイデオロギーによるサポートが必要です。
```

## 変更の理由（必須）

・「above 0%」を「0%以上」とする誤訳
・「The chance」を「制定成功率」と明示するため
・「Interest Group In Government」を「利益団体政府内」とする誤訳
・元の文が複文であり、訳にあたって、主述が離れたりして意味が分かりづらくなるのを避けるために文を分けた

## ゲームバージョン（必須）

1.0.4

## DLC有無（必須）

なし

## MOD有無（必須）

日本語改善MOD
Switch Languages

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
> [concept_interest_group]、[concept_in_government]、[concept_political_movement]、もしくは[Concept('concept_ruler','$concept_ruler_possessive$')]の[concept_ideology]によってもたらされる[Law.GetName]の制定確率が#v 0%#!を上回っている

**Comment by clamm0363** [comment]
チェックマーク付きの条件文であるため、上記のように修正しました

クローズします
