### ISSUE TITLE
外交戦撤退のフィード

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#321]
## スクリーンショット（任意）

![20221103150509_1](https://user-images.githubusercontent.com/43299334/199693026-7d4bee6e-3a31-401c-a7cf-f58a871cbc5d.jpg)

## 問題の用語（必須）

```
（国名）撤退
[SCOPE.sC('actor').GetName]は、我が国の[concept_diplomatic_play]に屈しました。主要な戦争目標が譲歩されます。
```

## 英語版の表現（任意）

```
[SCOPE.sC('actor').GetName] backs down
[SCOPE.sC('actor').GetName] backed down in our [concept_diplomatic_play], yielding the primary wargoal to us.
```

## 希望する変更（必須）

```
（国名）が屈服
（国名）は外交戦での敗北を認め、我が国が最初の戦争目標を達成することに同意しました。
```

## 変更の理由（必須）

標的となっている国でも同様のテキストであるため、撤退よりも屈服が相応しいと考えた。
また、相手国が自分の戦争目標の達成を諦めただけのようにも読めるため。

## ゲームバージョン（必須）

1.0.4

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
上記の通り、修正しました
notification_diplo_play_back_down_involved_notification_descについては修正せず、様子見としています（ゲーム中で確認していないため）
