### ISSUE TITLE
人名が正確に翻訳できない

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#323]
## 問題の固有名詞（必須）

Alfred、Michaelなど多数

## 希望する変更（必須）

アルフレッド、アルフレート、アルフレド
マイケル、ミヒャエル、ミカエル、等の文化毎の翻訳

## 変更の理由（必須）

現在は文化ごとにキーを分けずに同じスペルの人名を他文化にも流用しているため、日本語では正しく翻訳できず、表記がおかしくなってしまう。
人名を流用するのではなく人名一つ一つにキーを設定するなど、公式で修正されるべき。

## ゲームバージョン（必須）

1.0.4

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
報告しました。
https://forum.paradoxplaza.com/forum/threads/issue-names-are-shared-with-multiple-cultures.1558613/

**Comment by matanki-saito** [comment]
報告完了したためCloseと致します
