### ISSUE TITLE
宗教税のツールチップ

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#324]
※「｀｀｀」は消さないでください

## スクリーンショット（必須）
![Religious_Tax](https://user-images.githubusercontent.com/50406316/199720589-d07dfebf-86fd-42c5-b64e-8c8da669fc70.png)

## 問題のツールチップ（必須）
毎年からPOP徴収される異教税の額です。これは差別に反する宗教の信仰によるものです

## 問題の表現（必須）

```
（同上）
```

## 問題箇所の英文（任意）

```
The amount of Heathen taxes collected from Pops each year for following a Religion that is Discriminated against
```

## 希望する変更（必須）

```
差別されている宗教を信仰するPOPから毎年徴収される異教税の額です
```

## 変更の理由（必須）
語順がおかしく意味が通っていないため

## ゲームバージョン（必須）
1.0.4

## DLC有無（必須）
なし

## MOD有無（必須）
翻訳改善MOD(11/3)

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
提案通り修正してクローズします
