### ISSUE TITLE
【修正提案】New 建設

### ISSUE THREAD

**Issue by WoodlandsGitHub** [matanki-saito/vic3jpadvmod#325]
## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/29177147/199732420-888c0de2-c747-4f64-bb6c-6f431fa5bd27.png)
## 問題のツールチップ（必須）

予算ウィンドウ＞資産タブ＞投資プールの金額部分をマウスオーバー

## 問題の表現（必須）

```
New 建設
 INVESTMENT_POOL_CHANGE_FROM_CONSTRUCTION:1 "#bold New [concept_construction]:#! #v @money!$CHANGE|D+$#!"
```

## 問題箇所の英文（任意）

```
New Construction
```

## 希望する変更（必須）

```
新規建設中
 INVESTMENT_POOL_CHANGE_FROM_CONSTRUCTION:1 "#bold 新規[concept_construction]中:#! #v @money!$CHANGE|D+$#!"
```

## 変更の理由（必須）

未訳

## ゲームバージョン（必須）

1.0.4

## DLC有無（必須）

なし

## MOD有無（必須）

日本語改善MOD
Switch Languages

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
Constructionが「資材」となる見込みですので、「新規資材」となるように修正しました。

クローズします。
