### ISSUE TITLE
生活水準の高レベルの名称

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#326]
## スクリーンショット（任意）

![20221103220754_1](https://user-images.githubusercontent.com/43299334/199729250-c320e5bb-3c24-4cfc-896d-3d7d59d7be65.jpg)
![sol](https://user-images.githubusercontent.com/43299334/199732482-78f210b8-51d7-49ab-8899-8e03b64cb61d.png)

## 問題の用語（必須）
```
富裕Wealthy(Lv.40～）、豪奢Lavish(Lv.50～）、贅沢Opulent(Lv.60～）
```

## 英語版の表現（任意）

```
飢餓Starving(Lv.1～）、苦境Struggling(Lv.5～）
貧困Impoverished(Lv.10～）、中流Middling(Lv.15～）、堅実Secure(Lv.20～）
好調Prosperous(Lv.25～）、裕福Affluent(Lv.30～）、富裕Wealthy(Lv.40～）、豪奢Lavish(Lv.50～）、贅沢Opulent(Lv.60～）
```

## 希望する変更（必須）

```
富裕→贅沢、豪奢→富豪、贅沢→大富豪　など
```

## 変更の理由（必須）

テキストから水準が捉えにくいため

## ゲームバージョン（必須）

1.0.4

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
飢餓/Starving(Lv.1～）アイコン赤色
苦境/Struggling(Lv.5～）
貧困/Impoverished(Lv.10～）ここからアイコン黄色
質素/Middling(Lv.15～）
安定/Secure(Lv.20～）
充実/Prosperous(Lv.25～）ここからアイコン緑色
好調/Affluent(Lv.30～）
裕福/Wealthy(Lv.40～）
富豪/Lavish(Lv.50～）
大富豪/Opulent(Lv.60～）
で修正しました
