### ISSUE TITLE
【修正提案】イベント－耳朶に響く調べ

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#327]
※「｀｀｀」は消さないでください

## スクリーンショット（任意）

![20221103223637_1](https://user-images.githubusercontent.com/42710893/199741598-1e2eee33-dbe6-49fb-a437-63e70ff43c87.jpg)

## 問題部分（タイトル・本文・選択肢）

```
本文
```

## 問題のイベントタイトル（必須）

```
耳朶に響く調べ
```

## 問題のイベント本文（任意・抜粋可）

```
とても評判の良い旅の芸術家軍団が[SCOPE.sState('decree_state').GetName]しています。
英語:A well acclaimed troupe of wandering artists has arrived at [SCOPE.sState('decree_state').GetName],...
```

## 問題のイベント選択肢（任意）

```
```

## 希望する変更（必須・修正部分のみ）

```
とても評判の良い旅の芸術家軍団が[SCOPE.sState('decree_state').GetName]に到着しています。
```

## 変更の理由（必須）

arrived at～　の部分が訳されておらず、おかしな表記になっているため

## プレイ国家

ベルギー

## ゲームバージョン（必須）

1.0.4

## DLC有無（必須）

なし

## MOD有無（必須）

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
ご提案どおり修正しました。

クローズします。
