### ISSUE TITLE
【修正提案】禁輸開始フィード

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#328]
※「｀｀｀」は消さないでください

## スクリーンショット（必須）

![20221103222552_1](https://user-images.githubusercontent.com/42710893/199743554-f6f10b8c-704a-432e-a23e-89a10ec54190.jpg)

## 問題のあるインターフェイス（必須）

禁輸開始フィード

## 問題のテキスト（必須）

```
embargo_action_notification_third_party_desc:0 "[INITIATOR_COUNTRY.GetName]が[Concept('concept_embargo', '$concept_embargoing$')] [TARGET_COUNTRY.GetName]を開始しました。"

英語
"[INITIATOR_COUNTRY.GetName] began [Concept('concept_embargo', '$concept_embargoing$')] [TARGET_COUNTRY.GetName]."
```

## 希望する変更（必須）

```
[INITIATOR_COUNTRY.GetName]が[TARGET_COUNTRY.GetName]に対する[Concept('concept_embargo', '$concept_embargoing$')]を開始しました。
concept_embargoingの訳が「禁輸中」となっているのを「禁輸」に変える必要があると思いますが、他に影響しないか要検討

```

## 変更の理由（必須）

日本語として不自然なため。

## ゲームバージョン（必須）

1.0.4

## DLCの有無（必須）

なし

## MODの有無（必須）

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
「禁輸中」を「禁輸」と修正しました。

クローズします。
