### ISSUE TITLE
【未訳】ヴィキペディアのインフラ

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#329]
※「｀｀｀」は消さないでください

## スクリーンショット（必須）

![20221103221452_1](https://user-images.githubusercontent.com/42710893/199746072-7d172313-a7ed-465e-be49-75da4bc38fb1.jpg)

## 問題のあるインターフェイス（必須）

ヴィキペディアのインフラの項目

## 問題のテキスト（必須）

```
Railway , Port
```

## 希望する変更（必須）

```
鉄道、港
```

## 変更の理由（必須）

未訳のため

## ゲームバージョン（必須）

1.0.4

## DLCの有無（必須）

なし

## MODの有無（必須）

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
国家選択前の画面でVikipediaを開くと、一部の変数がうまく働かない問題を確認しており、これもその一つです。すべて修正することも可能ですが、パラドへの報告によって根本的な解決がなされるべきかと思います。

**Comment by clamm0363** [comment]
根本的解決をゲーム側で行ってもらうべく、「提案」タグをつけました

**Comment by matanki-saito** [comment]
報告をしました。
https://forum.paradoxplaza.com/forum/threads/victoria-iii-localization-bug.1558603/

**Comment by matanki-saito** [comment]
報告を完了したのでCloseと致します
