### ISSUE TITLE
【修正提案】実績の難易度

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#33]
## スクリーンショット（必須）
![20221026175655_1](https://user-images.githubusercontent.com/42710893/197983127-8e2a7857-a0b2-48ea-af31-1dbd47b838ed.jpg)

## 問題のあるインターフェイス（必須）

実績ウィンドウ

## 問題のテキスト（必須）

イージー、ノーマル、ハード、ベリーハード

## 希望する変更（必須）

易しい、普通、難しい、非常に難しい

## 変更の理由（必須）

日本語のほうが自然と思われます。

## ゲームバージョン（必須）

1.0.3

## DLCの有無（必須）

なし

## MODの有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1034754335604756510
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by clamm0363** [comment]
検討した結果、「修正なし」となりました。
