### ISSUE TITLE
場所を交替する

### ISSUE THREAD

**Issue by clamm0363** [matanki-saito/vic3jpadvmod#330]
※「｀｀｀」は消さないでください

## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/29382778/199908614-7ecf439c-c38c-45c1-953f-c8f515f59e67.png)

## 問題のあるインターフェイス（必須）

外交戦ウインドウ

## 問題のテキスト（必須）

```
場所を交替する
```

## 希望する変更（必須）

```
相手国側でプレイ
```

## 変更の理由（必須）

一見して意味が取れないため

## ゲームバージョン（必須）

1.0.4

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
![image](https://user-images.githubusercontent.com/29382778/199908892-85feccee-f013-4467-a5a6-bc1ea900e2bd.png)

**Comment by clamm0363** [comment]
上記のとおり修正しました

クローズします
