### ISSUE TITLE
【修正提案】シャン州 (ステート)

### ISSUE THREAD

**Issue by N-der** [matanki-saito/vic3jpadvmod#331]
## スクリーンショット（任意）

なし

## 問題の固有名詞（必須）

シャン州

## 英語版の表現

Shan States

## 希望する変更（必須）

シャン諸国

## 変更の理由（必須）

このゲームではパラドゲーで慣例的に「ステート」と呼ばれてきた地域区分が「州」に変わっているため、〇〇州という訳はふさわしくない。
また、原文のStatesは、この地域の小さな諸王権(ムアン)を表しているものなので、この"State"の意味は「州」ではなく「国家」が適当である。その点で誤訳である。

できればこの国家という意味を訳語に反映させたいので、「シャン諸国」という訳語を提案したい。
他の案として、シャン諸王権、シャン諸侯、あるいは単にシャンとすることも考えられる。

## ゲームバージョン（必須）

1.0.4

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
内部での議論の結果「シャン」に決定しました。
クローズします。

**Comment by matanki-saito** [comment]
## 英語版の表現

Shan States
