### ISSUE TITLE
分別蒸留（Fractional Distillation、技術名）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#332]
## スクリーンショット（任意）
![20221104180712_1](https://user-images.githubusercontent.com/42687608/199935310-f76bc66c-ab39-4139-956c-03b95ae9baa6.jpg)

## 問題の用語（必須）
```
分別蒸留
```

## 英語版の表現（任意）
```
Fractional Distillation
```

## 希望する変更（必須）
```
分留
```

## 変更の理由（必須）
誤訳ではないが、分留の方が一般的な用語。
Google検索で完全一致検索すると、分留の119万件に対し、分別蒸留は6千件しかない。

## ゲームバージョン（必須）
1.0.4

## DLC有無（必須）
- Victoria II Remastered Soundtrack
- American Buildings Pack

## MOD有無（必須）
- 自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
「分留」に確定し、修正が完了しました。
