### ISSUE TITLE
ドイツ系文化の姓名

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#333]
## 問題の固有名詞と希望する変更（必須）

フォン・アレンシルト：フォン・アレンチルト
フォン・ビスマルク・ボーレン：フォン・ビスマルク＝ボーレン
フォン・ブロムベルク：フォン・ブロンベルク
ヴォン・デム・クネセベック：フォン・デン・クネーゼベック
フォン・ゲブサー：フォン・ゲプザー
フォン・ヘッセン・ダルムシュタット：フォン・ヘッセン＝ダルムシュタット
フォン・ヘッセン・カッセル：フォン・ヘッセン＝カッセル
フォン・シャウムブルク・リッペ：フォン・シャウムブルク＝リッペ
フォン・ホルシュタイン・ゴットルプ：フォン・ホルシュタイン＝ゴットルプ
フォン・クリーフェルド：フォン・クレーフェルト
フォン・マントイッフェル：フォン・マントイフェル
フォン・メクレンブルク・シュヴェーリン：フォン・メクレンブルク＝シュヴェリーン
フォン・メクレンブルク・シュトレーリッツ：フォン・メクレンブルク＝シュトレーリッツ
フォン・ザクセン・アルテンブルク：フォン・ザクセン＝アルテンブルク
フォン・ザクセン・コーブルク・ゴータ：フォン・ザクセン＝コーブルク＝ゴータ
フォン・ザクセン・マイニンゲン：フォン・ザクセン＝マイニンゲン
フォン・ザクセン・ヴァイマル・アイゼナハ：フォン・ザクセン＝ヴァイマル＝アイゼナハ
フォン・シュバルツブルク：フォン・シュヴァルツブルク
フォン・シュピー：フォン・シュペー
フォン・ルーン：フォン・ローン
フォン・ジョンス：フォン・ヨンス
フォン・ニエジチョウスキー：フォン・ニェジホフスキ

アベグ：アベッグ
アレンド：アーレント
ベンケ：ベーンケ
ボーメル：ベーメル
ボーシグ：ボルジッヒ
コーデマン：コルデマン
クールメイヤー：クレマイアー
ドレイヤー：ドライアー
デュプラ：デプレ
エーラート：エーレルト
フェイヤーアーベンド：フェイアアーベント
ガルベ：ガーベ
ガーラッハ：ゲルラッハ
ゴーデラー：ゲルデラー
ゴーツ：ゲッツ
グリーブ：グレーベ
グローネル：グレーナー
グロス：グロート
ハールコート：ハーコート
ハリチ：ハーリヒ
ハッセンプフルグ：ハッセンプフルーク
ヒルシュフェルド：ヒルシュフェルト
フバッシュ：フーバッチュ
ジャストロウ：ヤストロー
ジョホウ：ヨーフ
キルヒウェガー：キルヒヴェーガー
クルムナウ：クルムノフ
ライスティコウ：ライスティコフ
レームクール：レームキュール
モール：モル
ペイサー：パイザー
ロープケ：レプケ
シッメルフェニッグ：シメルフェニク
シュリー：シュレー
ウェイデメイアー：ヴァイデマイアー
ヴィットフェルド：ヴィットフェルト
ウェーラート：ヴェーレルト
ゼラーン：ツェラーン

ダスプレー・フォン・フーブルーク：ダスプレ・フォン・ホーブロイク
シュノール・フォン・カロルスフェルド：シュノル・フォン・カロルスフェルト
フォン・ベーム・エルモッリ：フォン・ベーム＝エルモッリ
フォン・クラム・ガラス：フォン・クラム＝ガラス
フォン・ホーヘンハウゼン：フォン・ホーエンハウゼン
フォン・ディートリッヒ：フォン・ディートリヒ
フォン・ヴェイガート：フォン・ヴァイガート
フォン・ツァーリンゲン：フォン・ツェーリンゲン
ツウ・ホーエンローエ：ツー・ホーエンローエ
フォン・ウレーデ：フォン・ヴレーデ
フォン・メイヤーバッハ：フォン・マイアースバッハ
フォン・サーンベルク：フォン・トゥルンベルク

ベック・ルジコウスキー：ベック＝ルジコウスキ
ドールマン：ドルマン
フェルダーロイサー：フェルダーロイター
ジョーリング：ゲーリング
グローシェル：グレーシェル
ハイニッシュ：ハイニシュ
ヘルド：ヘルト
ヘルパッチ：ヘルパッハ
ヘルメリッヒ：ヘルメリヒ
ホムバーガー：ホンベルガー
ヒュメル：フンメル
メルゲンターラー：マーゲンターラー
プラットナー：プラトナー
プラング：プランク
レンメレ：レメレ
サイツ：ザイツ
スティーブ：シュテープ
ストラウス：シュトラウス
セイラー：ザイラー
トランク：トルンク
ウングラウブ：ウングラウプ
ヴァグナー：ヴァーグナー
ゼラー：ツェラー
ゼンガー：ツェンガー
ジンク：ツィンク

オイアーバッハ：アウエルバッハ
オイフルッシ：エフルシ
グンツブルク：ギュンツブルク
フォン・ホフマンスタール：フォン・ホーフマンスタール

アブラモビッチ：アブラモヴィッチ
コーヘン：コーエン
フリードランダー：フリートレンダー
ヤコブソン：ヤーコプゾーン
レーヴィン：レヴィン

エルウィン：エルヴィン
エンゲルバート：エンゲルベルト
ゲブハード：ゲープハルト
ゴットフリード：ゴットフリート
ラインホールド：ラインホルト
ルプレヒト：ループレヒト
レオンハルド：レオンハルト
コンラード：コンラート
ブルクハルド：ブルクハルト
フリードリッヒ：フリードリヒ
ルドウィグ：ルートヴィヒ
ラインハルド：ラインハルト
ヴェイト：ファイト
ヴィトス：フィトゥス

## 変更の理由（必須）
日本語では一般的ではない表記であるため。

## ゲームバージョン（必須）

1.0.4

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正内容に以下のドイツ系の名を追加、タイトルをドイツ系文化の姓名に変更
エルウィン：エルヴィン
エンゲルバート：エンゲルベルト
ゲブハード：ゲープハルト
ゴットフリード：ゴットフリート
ラインホールド：ラインホルト
ルプレヒト：ループレヒト
レオンハルド：レオンハルト
コンラード：コンラート
ブルクハルド：ブルクハルト
フリードリッヒ：フリードリヒ
ルドウィグ：ルートヴィヒ
ラインハルド：ラインハルト
ヴェイト：ファイト
ヴィトス：ヴィトゥス

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
