### ISSUE TITLE
【修正提案】政治運動発足のフィード

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#335]
※「｀｀｀」は消さないでください

## スクリーンショット（必須）

![20221104195156_1](https://user-images.githubusercontent.com/42710893/199979427-c8325820-21e1-45f3-8906-3dec99958453.jpg)

## 問題のあるインターフェイス（必須）

政治運動発足時のフィード

## 問題のテキスト（必須）

```
スクショでは
農本主義を制定 政治運動
```

## 希望する変更（必須）

```
農本主義を制定に向けた政治運動が発足

少し長いようなら簡潔に
政治運動が発足：農本主義を制定
等でも良いと思います。
```

## 変更の理由（必須）

日本語として自然なタイトルにするため。

## ゲームバージョン（必須）

（例）1.0.5

## DLCの有無（必須）

なし

## MODの有無（必須）

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
[concept_political_movement]：[SCOPE.GetRootScope.GetPoliticalMovement.GetName]で修正
「（法律名）を遵守」も合わせて「（法律名）の順守」に変更しました
