### ISSUE TITLE
都市-州→都市国家

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#336]
※「｀｀｀」は消さないでください
## スクリーンショット（任意）
![image](https://user-images.githubusercontent.com/37979626/199987261-0f6bb9e9-65cb-4a87-ba30-c77e0f870a17.png)

## 問題の用語（必須）
```都市-州```

## 英語版の表現（任意）
```City-State```

## 希望する変更（必須）
```都市国家```

## 変更の理由（必須）
誤訳

## ゲームバージョン（必須）
1.0.4

## DLC有無（必須）
無し

## MOD有無（必須）
なし

**Comment by inarizushi0309** [comment]
原案通り修正しました。

**Comment by matanki-saito** [comment]
## 英語版の表現（任意）
```City-State```
