### ISSUE TITLE
党・党リーダー→政党・党首

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#338]
## スクリーンショット（任意）
![image](https://user-images.githubusercontent.com/37979626/199988941-646b3e6c-3d7b-44a3-845d-166612b4e369.png)

## 問題の用語（必須）
```
党
党リーダー
```

## 英語版の表現（任意）
```
Party
Party Leader
```

## 希望する変更（必須）
```
政党
党首
```

## 変更の理由（必須）
「党」だけでは今一つな感が否めない。また、政治団体ということを考えると「政党」とするのが一般的

## ゲームバージョン（必須）
1.0.4

## DLC有無（必須）
無し

## MOD有無（必須）
なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通り修正しました。
