### ISSUE TITLE
施設拡張時のポップアップ一括修正

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#339]
## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/37979626/200013490-a09b45cd-a5aa-455c-81f8-e737bd459bd9.png)

## 問題のあるインターフェイス（必須）
施設拡張時のポップアップ

## 問題のテキスト（必須）
CAN_EXPAND_BUILDING_TOOLTIP
```$建設or拡張$[ステート名]の[施設名]（サイズ: [現在/最大])
@money!$予想収入額$収入予測 / 週
[資格取得の判定]
-----------------------
@construction! $必要建設数$ [コンセプト（建設）] ($CONSTRUCTION_COST_CHANGE$)
[投資プールの判定]
[ステートのインフラ状況]
使用可能な労働者: [peasants数] [POP名peasants] [失業者判定][軍事関連かの判定][港関連かの判定]

$操作キー$
```
失業者判定→AND_UNEMPLOYED
```
および[失業者数][コンセプト（失業者）]
```
`$CONSTRUCTION_COST_CHANGE$`→CONSTRUCTION_TOTAL_COST_IMPACTまたはCONSTRUCTION_WEEKLY_COST_IMPACT
```
@money!$COST|K-$#![コンセプト（建設商品）]で予測される合計コスト：
```
```
@money!$COST|K-=$#![コンセプト（建設商品）]の毎週のコスト
```
投資プールの判定→CONSTRUCTION_CAN_BE_FUNDED_BY_INVESTMENT_POOL
```
[コンセプト（建設商品）] は[コンセプト（投資プール）]から捻出可能です (現在 @money![投資プール額])
```

## 希望する変更（必須）
```
[ステート名]の[施設名]$建設or拡張$（規模：[現在/最大]）
@money!$予想収入額$予想収入/週
[資格取得の判定]
-----------------------
@construction![Nbsp]$必要建設数$[コンセプト（建設）]（$CONSTRUCTION_COST_CHANGE$）
[投資プールの判定]
[ステートのインフラ状況]
使用可能な労働者：[peasants数][POP名peasants][失業者判定][軍事関連かの判定][港関連かの判定]

$操作キー$
```
失業者判定
```
および[失業者数][コンセプト（失業者）]
```
`$CONSTRUCTION_COST_CHANGE$`
```
@money!$コスト額$予想される合計[コンセプト（建設商品）]コスト：
```
```
@money!$コスト額$毎週の[コンセプト（建設商品）]コスト
```
投資プールの判定
```
[コンセプト（建設商品）]は[コンセプト（投資プール）]から捻出可能です（現在@money![投資プール額]）
```

## 変更の理由（必須）
変数に対応できていないため

## ゲームバージョン（必須）
1.0.4

## DLCの有無（必須）
なし

## MODの有無（必須）
なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
「10分をキューに入れる」とタイポしているのに気づきましたので、そちら修正しておきました。スクショ感謝です。

**Comment by clamm0363** [comment]
![image](https://user-images.githubusercontent.com/29382778/200598142-be3c0477-5fd4-4d4b-b0e7-9e3488e5bc55.png)
画像のような表示となるように修正しました。

クローズします
