### ISSUE TITLE
【修正提案】軍事画面－軍隊の状態

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#34]
## スクリーンショット（必須）

![20221026183138_1](https://user-images.githubusercontent.com/42710893/198003419-1035c1bd-20d8-421c-9438-531f566eac8e.jpg)

## 問題のあるインターフェイス（必須）

軍事ウィンドウ

## 問題のテキスト（必須）

ライン本部に待機中がいます

## 希望する変更（必須）

ライン本部で待機中です

## 変更の理由（必須）

日本語として不自然なため
英語版だと
[Character.GetCommanderOrder.GetType.GetNameGerund|v] at $LOCATION|v$$ADDITIONAL_LOCATION_INFO$
[Character.GetCommanderOrder.GetType.GetNameGerund|v]には進軍中、待機中、防衛中等軍隊の現況が入ると思われます

## ゲームバージョン（必須）

1.0.3

## DLCの有無（必須）

なし

## MODの有無（必須）

※できるだけMODのない状態で問題を確認してください。

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1034776896673677352
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by clamm0363** [comment]
「[場所]で[待機中]」などのように表示されるように修正しました。
