### ISSUE TITLE
【修正提案】襲撃を受けた航路の海上ノード「輸送船団襲撃は、このノードを通過する…」

### ISSUE THREAD

**Issue by WoodlandsGitHub** [matanki-saito/vic3jpadvmod#342]
## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/29177147/199974105-904359bf-2b0a-4e41-9a89-3a3330914383.png)

## 問題のツールチップ（必須）

戦争等で輸送船団が襲撃を受けた際の、その航路上にある海上ノードをマウスオーバー

## 問題の表現（必須）

```
 SUPPLY_NETWORK_MAPMARKER_IS_RAIDED:0 "@warning![Concept('concept_raid_convoys', '$concept_convoy_raiding$')]は、このノードを通過する我々の[Concept('concept_shipping_lane', '$concept_shipping_lanes$')]が所持する[concept_convoys]を$NUM_SUNK_CONVOYS|-v$隻沈没させ、効率が平均$DAMAGE|v-%$下がりました"
```

## 問題箇所の英文（任意）

```
 SUPPLY_NETWORK_MAPMARKER_IS_RAIDED:1 "@warning! [Concept('concept_raid_convoys', '$concept_convoy_raiding$')] has sunk $NUM_SUNK_CONVOYS|-v$ [concept_convoys] belonging to our [Concept('concept_shipping_lane', '$concept_shipping_lanes$')] passing through this node, reducing their efficiency by an average of $DAMAGE|v-%$"
```

## 希望する変更（必須）

```
 SUPPLY_NETWORK_MAPMARKER_IS_RAIDED:0 "@warning!このノードを経由する[Concept('concept_shipping_lane', '$concept_shipping_lanes$')]上にて、[Concept('concept_raid_convoys', '$concept_convoy_raiding$')]を受け、我々の[concept_convoys]が$NUM_SUNK_CONVOYS|-v$隻沈没しました。その結果、効率が平均$DAMAGE|v-%$下がりました"
```

## 変更の理由（必須）

不自然な日本語なので

## ゲームバージョン（必須）

1.0.4

## DLC有無（必須）

なし

## MOD有無（必須）

日本語改善MOD
Switch Languages

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
> @warning![Nbsp]このノードを経由する[Concept('concept_shipping_lane', '$concept_shipping_lanes$')]上で[Concept('concept_raid_convoys', '$concept_convoy_raiding$')]を受け、我々の[concept_convoys]が$NUM_SUNK_CONVOYS|-v$隻沈没しました。その結果、効率が平均で$DAMAGE|v-%$下がりました

**Comment by clamm0363** [comment]
上記のように修正しました。

クローズします。
