### ISSUE TITLE
建設（コンセプトワード）/建設商品

### ISSUE THREAD

**Issue by clamm0363** [matanki-saito/vic3jpadvmod#343]
※「｀｀｀」は消さないでください

## スクリーンショット（任意）
![image](https://user-images.githubusercontent.com/29382778/200061526-8e9ce965-4baa-4941-af44-4542411c6e89.png)
![image](https://user-images.githubusercontent.com/29382778/200061549-b42d45a8-1e21-4ce2-85de-31595d2b0cb3.png)
## 問題の用語（必須）

```
建設/建設商品
```

## 英語版の表現（任意）

```
Construction/Construction Goods
```

## 希望する変更（必須）

```
資材/建設資材
```

## 変更の理由（必須）

Construction Sectorの建設をは意味が異なるため

## ゲームバージョン（必須）

1.0.5

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
上記のとおり修正しました。

クローズします。
