### ISSUE TITLE
「五カ年計画」と「4カ年計画」

### ISSUE THREAD

**Issue by BLACKTIGER-NB** [matanki-saito/vic3jpadvmod#344]
※「｀｀｀」は消さないでください

## スクリーンショット（任意）
![五カ年計画](https://user-images.githubusercontent.com/75819188/200081958-1ba359bc-f898-4161-a7cb-e634010cda36.jpg)

四カ年計画のスクリーンショットはなし

## 問題部分（タイトル・本文・選択肢）

```
タイトル
```

## 問題のイベントタイトル（必須）

```
Victoria 3\game\localization\japanese\content_1_l_japanese.yml
 je_5_year_plan:0 "五カ年計画"

Victoria 3\game\localization\japanese\content_104_l_japanese.yml
 fascism_events.5.t:0 "4カ年計画"
```

## 希望する変更（必須・修正部分のみ）

```
四カ年計画
```

## 変更の理由（必須）

漢数字とアラビア数字で表記ゆれしている

## プレイ国家
スェーデン

## ゲームバージョン（必須）

たぶん1.03

## DLC有無（必須）

American Building Pack	
Expansion Pass
Victoria 2 Remastered Soundtracks

## MOD有無（必須）

なし

--------
ommunist_welfare_modは検索しても1カ所しか見つからなくて、なんの効果かはわからない

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
数字や記号の補正は一括してプログラムで対応予定です。よろしくお願いいたします。

**Comment by matanki-saito** [comment]
上記の通りの方針のためクローズします。

**Comment by matanki-saito** [comment]
「カ年」は指摘箇所しかなかったため修正を実施しました。
