### ISSUE TITLE
稲田→稲農場("Farms"自体を「畑」じゃなくて農場で統一した方が良いのでは)

### ISSUE THREAD

**Issue by BLACKTIGER-NB** [matanki-saito/vic3jpadvmod#345]
※「｀｀｀」は消さないでください

## スクリーンショット（任意）
なし
https://github.com/matanki-saito/vic3jpadvmod/blob/main/source/JapaneseLanguageAdvancedMod/localization/japanese/buildings_l_japanese.yml

## 問題の用語（必須）

```
稲田
(作物名)畑
```

## 英語版の表現（任意）

```
Rice Farms
(作物名) Farms
```

## 希望する変更（必須）

```
稲農場
(作物名)農場
```

## 変更の理由（必須）

基本的にヨーロッパは陸稲で畑、東・東南アジアは水稲で田です。
ゲーム内での稲畑の産品切り替えのイチジクは田による栽培ではないと思います。
スペインに稲田はほとんど無いと思います。
どういった議論と投票で稲畑から稲田に変更されたかは公開されていません。
投票したら多数の日本人にとって身近の「田」が多数になるんじゃないかなと思いますが、『日本人の好みのために他地域をどのくらい犠牲にして良いのか』という面倒な話になるんじゃないですかね。
よって、農産のFarmsを栽培形態に左右されない名前にすればいいんじゃないかな主張します。
※「農園」はplantationで使われているので除外します

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

American Building Pack	
Expansion Pass
Victoria 2 Remastered Soundtracks

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Via-GitHub** [comment]
自分も稲田で適訳だと思ってましたが、製法の変更や耕作文化の違いは少し問題ですね（製法は二次なので一部が果樹園等を行ってるイメージでしょうけど）。[開発日記](https://forum.paradoxplaza.com/forum/developer-diary/victoria-3-dev-diary-3-buildings.1478868/)ではVic3の施設は個別の建物ではないと説明されており、farmは田や畑そのものではなく「稲作を中心とした産業地域」と見た方がいいのかもしれません。

**Comment by clamm0363** [comment]
参考までに、稲田に関する議論をようやくしてお伝えします。
議論では水稲と陸稲があることはもちろん、他の同系統施設に対する統一感、一般的かどうか、その言葉のもつイメージが適切に施設を表しているか、などを議論し、なおメンバー内でも意見が割れたため、最も推す声の多かった「稲田」となりました。

**Comment by Via-GitHub** [comment]
解説ありがとうございました。どちらにせよ意味が通じないわけではないし、稲作農場等より稲田の方が分かりやすいのは間違いないですね。

個人的に再考してみたところ、以下の点で農場、ないし産業地域であることを示せる訳語での統一を推したいかなぁとは思います。

- farmは貴族や公務員popが働く場でもありますが、田畑で彼らが汗水を流すわけではない

- 翻訳解決の一貫性にひずみが残る危惧。たとえば[砂糖農園](https://github.com/matanki-saito/vic3jpadvmod/issues/312)についてもビート等で製糖するケースを除外し、日本で馴染み深い「サトウキビ畑」等とするべきか

あとは些事とも言えますが、田畑はfieldなので原文もおそらく田畑自体を意図はしていなかった点を挙げられるかもしれません。没入感や自然さ、分かりやすさも勿論重要ですが、ことゲーム翻訳においてはゲームメカニックを適切に表現しているかが優先であると個人的には考えます…が、万人に受け入れてもらえる訳は本当に難しいですね。

**Comment by BLACKTIGER-NB** [comment]
私の提起から考えを示してくれたり議論の概要を教えてくれたのは、ありがとうございますと言うところですね。
ゲームプレイ的にはスペインに稲田があっても、他の施設の操作に忙しいからあまり気にしないかなとも思います。

日本語ローカライズを必要としている人の大半は日本文化の日本人で、議論も投票も日本文化に身近なものに強い影響を受けると思いますよ。
ようする議論も投票もに「日本の稲作は水田なんだから『田』」という基幹的な感覚に抗えなかったんでしょう。
その一部地域の事情を他に押しつけて良いんですかね。"Sea of Japan / East Sea"を「韓国からの押しつけ」的な反発があるとおもうんですが、逆ならやって良いんですか？(個人的には「日本海」ですけど)(厳密に言えばやっていいケースもあるんですが、置いておいてください)

万人向けの翻訳と言う発言がありましたが、「普通の日本人」むけに翻訳を校正した方が称賛が得られると思いますよ。対立意見は「普通の日本人」ではない、と処理すれば良いんですし。
EU4日本語化であったアンチ叩きも「普通の日本人」さんはやってくれますし。「普通の日本人」向けに質が高くなる意見も積極的に出ると思います。
「普通の日本人」さんは多数派意識があるだけあって、数が多いですし、そちらのdiscord内にも何人も居そうです。なので、こんな提起しなくてもそういう翻訳に変化していくのかなぁと思います
私がそうったことを是とするかどうかは別の話です。

長文になりすぎないようにこの辺で打ち切ります。

**Comment by matanki-saito** [comment]
打ち切るとされているためクローズいたします。よろしくお願いいたします。
