### ISSUE TITLE
ランク/Rank・国のランク/Country Tier

### ISSUE THREAD

**Issue by kurutto115** [matanki-saito/vic3jpadvmod#346]
## スクリーンショット（任意）
![Victoria 3 2022_11_05 1_02_50](https://user-images.githubusercontent.com/117251782/200087840-a0531d21-4f1a-4d8c-87f4-fb5e66f205ed.png)
![Victoria 3 2022_11_05 1_02_31](https://user-images.githubusercontent.com/117251782/200087874-32aac050-98d8-4565-b08e-01af0f877a9e.png)

## 問題の用語（必須）

```
（国の）ランク
国のランク
```

## 英語版の表現（任意）

```
(Country's) Rank
Country Tier
```

## 希望する変更（必須）

```
格付け
国家階級
```

## 変更の理由（必須）

用語が重複しているため

## ゲームバージョン（必須）

1.0.5

## DLC有無（必須）

無し

## MOD有無（必須）

当プロジェクトMODのみ

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
報告ありがとうございます。訳し分けは必要としても訳語については翻訳チーム内でも意見が割れ、決を取った結果、ゲームコンセプト用語としてカタカナそのままのランク/ティアとすることになりました。
