### ISSUE TITLE
【修正提案】大隊の徴兵→徴募大隊（Conscript Battalions）

### ISSUE THREAD

**Issue by WoodlandsGitHub** [matanki-saito/vic3jpadvmod#348]
## スクリーンショット（任意）
![image](https://user-images.githubusercontent.com/29177147/200105103-6ef1d28c-4f7a-49af-859a-0941989fa9c4.png)
![image](https://user-images.githubusercontent.com/29177147/200105139-9d61da77-2619-4afc-89a1-d7562345b9fb.png)

## 問題の用語（必須）

```
大隊の徴兵
```

## 英語版の表現（任意）

```
Conscript Battalions
```

## 希望する変更（必須）

```
徴兵大隊
```

## 変更の理由（必須）

誤訳

## ゲームバージョン（必須）

1.0.4

## DLC有無（必須）

なし

## MOD有無（必須）

日本語改善MOD
Switch Languages

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
troop_name_conscriptで「徴募部隊」となっているので「徴募大隊」を提案します

**Comment by WoodlandsGitHub** [comment]
揃った方が良いので「徴募大隊」を推します

**Comment by matanki-saito** [comment]
troop_name_conscriptで「徴募部隊」となっているので「徴募大隊」を提案します

**Comment by Zousuikakka** [comment]
徴募大隊　で修正
