### ISSUE TITLE
【修正提案】初任給

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#349]
※「｀｀｀」は消さないでください

## スクリーンショット（任意）
![Starting_Wages](https://user-images.githubusercontent.com/50406316/200109891-e1704c95-740a-4fe7-9f47-6f969f718b8d.png)

## 問題の用語（必須）

```
未編入州の初任給
未編入州のPOPが初任給として受け取る金額の多寡です。
```

## 英語版の表現（任意）

```
上は「Starting Wages」、下は「initial salaries」
```

## 希望する変更（必須）

```
未編入州の賃金初期値
未編入州のPOPが賃金の初期値として受け取る金額の多寡です。
```

## 変更の理由（必須）
未編入州のPOPの賃金のベース値補正のことで、初任給ではないので修正したい。
上下で表現は違うが、ここ以外に登場する単語ではなく、意味も同じなので訳語も同じとする。

## ゲームバージョン（必須）

1.0.5

## DLC有無（必須）
無し

## MOD有無（必須）
翻訳改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
提案通り変更してクローズします
