### ISSUE TITLE
【未訳】Current

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#35]
## スクリーンショット（必須）

![20221026182714_1](https://user-images.githubusercontent.com/42710893/198006800-531262b3-fd45-401d-8a5c-9b0e652b1730.jpg)

## 問題のツールチップ（必須）

国家ランキングのツールチップ

## 問題の表現（必須）

Current 国威

## 希望する変更（必須）

現在の国威

## 変更の理由（必須）

Currentが未訳のため

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1034780470367502398
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by wakkunteitoku** [comment]
既に同じものが投稿されていましたので閉じておきます。申し訳ありません。

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1034800311107321956
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。
