### ISSUE TITLE
【修正提案】関係の改善/悪化フィードのタイトル

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#350]
※「｀｀｀」は消さないでください

## スクリーンショット（必須）
![20221105162127_1](https://user-images.githubusercontent.com/42710893/200111009-aadd135a-7af6-4f20-b278-a22a3390c329.jpg)
![20221105162136_1](https://user-images.githubusercontent.com/42710893/200111018-a9ee55b0-dd84-457d-9731-8e0af61df6af.jpg)
## 問題のあるインターフェイス（必須）

関係の改善/悪化フィード

## 問題のテキスト（必須）

```
increase_relations_action_notification_name:2 "[concept_relations]が改善している[INITIATOR_COUNTRY.GetName]"
damage_relations_action_notification_name:2 "[concept_relations]が悪化している[INITIATOR_COUNTRY.GetName]"

英語版
increase_relations_action_notification_name:2 "[INITIATOR_COUNTRY.GetName] improving [concept_relations]"
damage_relations_action_notification_name:2 "[INITIATOR_COUNTRY.GetName] damaging [concept_relations]"
```

## 希望する変更（必須）

```
[INITIATOR_COUNTRY.GetName]との関係が改善
[INITIATOR_COUNTRY.GetName]との関係が悪化
```

## 変更の理由（必須）

日本語として不自然なため。

## ゲームバージョン（必須）

1.0.5

## DLCの有無（必須）

なし

## MODの有無（必須）

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
「バグ」タグについて

このツールチップ内の中立（0）はバグでツールチップが出ません。

> #tooltip:COUNTRY_RELATIONS_TOOLTIP [INITIATOR_COUNTRY.GetRelationsWithDesc( GetPlayer )|+]#!#!（#BOLD #tooltippable #tooltip:COUNTRY_RELATIONS_TOOLTIP [INITIATOR_COUNTRY.GetRelationsWith( GetPlayer )|+]#!#!#!

の部分を

> #tooltippable #tooltip:[INITIATOR_COUNTRY.GetTooltipTag],COUNTRY_RELATIONS_TOOLTIP [INITIATOR_COUNTRY.GetRelationsWithDesc( GetPlayer )|+]#!#!（#BOLD #tooltippable #tooltip:[INITIATOR_COUNTRY.GetTooltipTag],COUNTRY_RELATIONS_TOOLTIP [INITIATOR_COUNTRY.GetRelationsWith( GetPlayer )|+]#!#!#!

と修正することでツールチップが出るようになります。

**Comment by clamm0363** [comment]
![image](https://user-images.githubusercontent.com/29382778/201486219-d246881f-e087-4d1e-bc82-e5715aa9e50a.png)

**Comment by clamm0363** [comment]
上記画像のように表示されるよう修正しました。

クローズします。
