### ISSUE TITLE
 ...とさらに$COUNT$のアイテム

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#351]
## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/37979626/200111901-3b6f13d4-bb2a-48df-9539-56c5c6249061.png)

## 問題のあるインターフェイス（必須）
買い注文の内訳のようなリストで表示しきれないポップアップの下部

## 問題のテキスト（必須）
MORE_ITEMS
```
 ...とさらに$COUNT$のアイテム
```
MORE_ITEMS_TOOLTIPPABLE
```
#tooltippable #tooltip:$TAG$ ... とさらに$COUNT$のアイテム#!#!
```

## 希望する変更（必須）
```
 ...他$COUNT$件
#tooltippable #tooltip:$TAG$ ...他$COUNT$件#!#!
```

## 変更の理由（必須）
冗長であるため

## ゲームバージョン（必須）
1.0.4

## DLCの有無（必須）
なし

## MODの有無（必須）
なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通り修正しました。
