### ISSUE TITLE
$POTENTIAL|v$[BUILDING_TYPE.GetName]をサポートすることができます

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#353]
## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/37979626/200114513-534c51fc-4d67-4a49-8f2e-19ffcd731331.png)

## 問題のツールチップ（必須）
市場ウィンドウ>品物画面>マップ上でマウスオーバー

## 問題の表現（必須）
STATE_GOODS_POTENTIAL_SUMMARY
``` $POTENTIAL|v$[BUILDING_TYPE.GetName]をサポートすることができます（現在の量： $CUR|v$）：このタイプの各施設は、現在の技術と法律による基本処理量で最大 $AMOUNT|0v$[GOODS.GetTextIcon][GOODS.GetName]を生産することができます。```

## 問題箇所の英文（任意）
```Can support $POTENTIAL|v$ [BUILDING_TYPE.GetName] (Current Amount: $CUR|v$): Each building of this type can produce at most $AMOUNT|0v$ [GOODS.GetTextIcon][GOODS.GetName] at base throughput with our current technologies and laws.```

## 希望する変更（必須）
```[BUILDING_TYPE.GetName]を$POTENTIAL|v$レベル（現在：$CUR|v$）にすることができます：このタイプの施設は、現在の技術と法律による基本処理量で[GOODS.GetTextIcon][GOODS.GetName]を最大$AMOUNT|0v$生産することができます。```

## 変更の理由（必須）
変数に対応できていないため

## ゲームバージョン（必須）
1.0.4

## DLC有無（必須）
なし

## MOD有無（必須）
なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
変更案ですが、Each buildingの部分が訳抜けしてしまっていて、やや分かりにくいかと思います。
```[BUILDING_TYPE.GetName]を最大で$POTENTIAL|v$レベルにすることができます（現在：$CUR|v$）\nこのタイプの施設は、現在の技術と法律による基本処理量で[GOODS.GetTextIcon][GOODS.GetName]を1レベルあたり最大$AMOUNT|0v$生産することができます。```

**Comment by inarizushi0309** [comment]
こちらで修正しました。
