### ISSUE TITLE
【修正提案】戦争ウィンドウの受諾スコアの内訳「イギリスが推進する戦争目標」

### ISSUE THREAD

**Issue by WoodlandsGitHub** [matanki-saito/vic3jpadvmod#355]
## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/29177147/200115356-1c515860-5f93-4d89-8e4f-b1565ebf5df9.png)

## 問題のツールチップ（必須）

戦争ウィンドウの受諾スコアをマウスオーバー

## 問題の表現（必須）
interfaces_l_japanese.yml
```
（国名）が推進する戦争目標
 PEACE_ACCEPTANCE_OWN_WAR_GOALS:1 "$ADJ$が推進する[Concept('concept_war_goal', '$concept_war_goals$')]: #bold $VAL|=+$#!"
```

## 問題箇所の英文（任意）
interfaces_l_english.yml
```
Pressed (国名) War Goals

 PEACE_ACCEPTANCE_OWN_WAR_GOALS:1 "Pressed $ADJ$ [Concept('concept_war_goal', '$concept_war_goals$')]: #bold $VAL|=+$#!"
```

## 希望する変更（必須）

```
（国名）が主張する戦争目標
 PEACE_ACCEPTANCE_OWN_WAR_GOALS:1 "$ADJ$が主張する[Concept('concept_war_goal', '$concept_war_goals$')]: #bold $VAL|=+$#!"
```

## 変更の理由（必須）

誤訳にだいぶ近いと思うので

## ゲームバージョン（必須）

1.0.5

## DLC有無（必須）

なし

## MOD有無（必須）

日本語改善MOD
Switch Languages

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
議論の結果、「[国名]が要求している戦争目標」と修正しました。

クローズします
