### ISSUE TITLE
【修正提案】神権政イタリアの国名

### ISSUE THREAD

**Issue by ice-Boerk** [matanki-saito/vic3jpadvmod#356]
## スクリーンショット（任意）
![Desktop Screenshot 2022 11 05 - 20 00 04 19](https://user-images.githubusercontent.com/74766009/200119919-ce747b32-dab5-4f2a-a998-7f2280bce5fe.png)

## 問題の固有名詞（必須）

天国

## 英語での表現

dyn_c_papal_italy:0 "Kingdom of Heaven"

## 希望する変更（必須）

神の王国

## 変更の理由（必須）

国名として天国を用いるのは不自然なため。
また、EU4の同様の国家の国名として神の王国が用いられているため。

## ゲームバージョン（必須）

（例）1.0.5

## DLC有無（必須）

American Building Pack
Expansion Pass
VictoriaII Remastered Songs

## MOD有無（必須）

Universal Names + Historical Figures
JapaneseLanguageAdvancedMod
日本語フォント置き換えMODテスト版

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
ご指摘の通り修正いたしました。
修正したためクローズします

**Comment by matanki-saito** [comment]
## 英語での表現

dyn_c_papal_italy:0 "Kingdom of Heaven"
