### ISSUE TITLE
【修正提案】戦争ウィンドウの受諾スコアの内訳「（相手国）が推進する戦争目標」

### ISSUE THREAD

**Issue by WoodlandsGitHub** [matanki-saito/vic3jpadvmod#357]
## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/29177147/200118046-2efb56c8-7d68-4377-b544-356ff1cfd5c3.png)
![image](https://user-images.githubusercontent.com/29177147/200118060-32d9ec19-cba1-4867-a695-9d146e8cab23.png)
以下比較のため参考
![image](https://user-images.githubusercontent.com/29177147/200118317-72e85b39-4de8-4c55-a405-0fdee4ea26bc.png)
![image](https://user-images.githubusercontent.com/29177147/200118332-31b21485-d198-4a21-b8f8-ae165620fcf2.png)

## 問題のツールチップ（必須）

戦争ウィンドウの受諾スコアをマウスオーバー

## 問題の表現（必須）

```
 PEACE_ACCEPTANCE_ENEMY_WAR_GOALS_ON_SELF:1 "$COUNTRY$が推進する[Concept('concept_war_goal', '$concept_war_goals$')]: #bold $VAL|=+$#!"
```

## 問題箇所の英文（任意）

```
 PEACE_ACCEPTANCE_ENEMY_WAR_GOALS_ON_SELF:1 "[Concept('concept_war_goal', '$concept_war_goals$')] Pressed on $COUNTRY$: #bold $VAL|=+$#!"

```

## 希望する変更（必須）

```
（相手国）に対して主張されている戦争目標
```

## 変更の理由（必須）

誤訳
主張を受けているのに、主張をした側になっている

## ゲームバージョン（必須）

1.0.5

## DLC有無（必須）

なし

## MOD有無（必須）

日本語改善MOD
Switch Languages

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
「[国名]が要求されている戦争目標」となるように修正しました

クローズします
