### ISSUE TITLE
【修正提案】戦争ウィンドウの和平タブ「自主的な戦争目標」

### ISSUE THREAD

**Issue by WoodlandsGitHub** [matanki-saito/vic3jpadvmod#358]
## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/29177147/200115356-1c515860-5f93-4d89-8e4f-b1565ebf5df9.png)

## 問題のあるインターフェイス（必須）

戦争ウィンドウの和平タブ

## 問題のテキスト（必須）

```
自主的な戦争目標
※英語版参考
Unpressed War Goals
```

## 希望する変更（必須）

```
未主張の戦争目標
```

## 変更の理由（必須）

誤訳
というかどういう経緯で「自主的な」になった…？

## ゲームバージョン（必須）

1.0.5

## DLC有無（必須）

なし

## MOD有無（必須）

日本語改善MOD
Switch Languages

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
「和平協定に含まれていない戦争目標」と修正しました

クローズします
