### ISSUE TITLE
【報告用】日本文化名に不適当なキーが存在する

### ISSUE THREAD

**Issue by clamm0363** [matanki-saito/vic3jpadvmod#359]
## 問題の固有名詞（必須）

Yoshida/吉田　→　First Nameとして設定されている
Michisura/ミチスラ　→道貫ではないか？

## ゲームバージョン（必須）

1.0.5

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by awak1180** [comment]
日本文化の命名に絡んでですが、First Name候補に含まれている"Michisura"は19～20世紀の日本人の名前としては不適当と考えます。おそらくは、イシュー#238で比定した通り"Michitsura"(道貫)のタイプミスと思われるので、もし可能であればこちらもパラドックス社に報告して頂ければ幸いです。(もし別個で起票すべきであれば、私の方で起票します)

**Comment by clamm0363** [comment]
いえ、報告時にはこのissueを参照しますから、改めて立てて頂く必要はないと思います。こちらの起票のトップにそのことも書き添えておきますね。

**Comment by matanki-saito** [comment]
「吉田」の問題を報告しました。
https://forum.paradoxplaza.com/forum/threads/victoria-iii-mistake-japanese-culture-config.1558617/

**Comment by matanki-saito** [comment]
「Michisura」の問題を報告しました。
https://forum.paradoxplaza.com/forum/threads/victoria-iii-mistake-japanese-culture-config-typo.1558620/

**Comment by matanki-saito** [comment]
報告が完了したためCloseと致します
