### ISSUE TITLE
【修正提案】技術ツリー画面の残り月数

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#36]
## スクリーンショット（必須）

![20221026194158_1](https://user-images.githubusercontent.com/42710893/198008655-0567b5fb-5f9c-4373-a118-60384b02641e.jpg)

## 問題のあるインターフェイス（必須）

技術ツリー画面

## 問題のテキスト（必須）

31ヶ月が退出しました

## 希望する変更（必須）

残り31ヶ月

## 変更の理由（必須）

誤訳と思われるため
英語版では
[Technology.GetTimeLeftDesc( GetPlayer.Self )] left

## ゲームバージョン（必須）

1.0.3

## DLCの有無（必須）

なし

## MODの有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1034782914015146006
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by saarland68** [comment]
修正しました
「○○ヶ月が退出しました」→「残り○○ヶ月」に表記を修正
