### ISSUE TITLE
チュートリアル「利益団体とは？」9/9

### ISSUE THREAD

**Issue by AruiKashiwagi** [matanki-saito/vic3jpadvmod#360]
## スクリーンショット（必須）
![20221105220118_1](https://user-images.githubusercontent.com/52348271/200121561-a08c5d6f-3fc8-47b5-a5ab-46c6a8ca3dd2.jpg)

## 問題のあるインターフェイス（必須）

ゲームコンセプト「利益団体」をホバーして「ガイド」
→「利益団体とは？」9/9

### 日本語表示
```
利益団体が支持する法律も一覧を希望順に並べ替えることで確認できます。enactボタンにカーソルを合わせると、この利益団体や国内のその他の利益団体による承認の効力を明確化することができます。
```

### 日本語テキストデータ

tutorial_l_japanese.yml => lesson_interest_group_9_desc
```
[concept_interest_group]が支持する[Concept('concept_law', '$concept_laws$')]も一覧を希望順に並べ替えることで確認できます。$enact$ボタンにカーソルを合わせると、この利益団体や国内のその他の$concept_interest_groups$による[concept_approval]の効力を明確化することができます。
```

### 英語テキストデータ
```
[Concept('concept_law', '$concept_laws$')] the [concept_interest_group] supports are also available in list form sorted in order of most to least desired. Hovering the $enact$ button will clarify the [concept_approval] effects of the $concept_law$ on this and other $concept_interest_groups$ in the country.
```

### 変更後日本語表示
```
この利益団体が支持する法律を希望順に並べた一覧も用意されています。制定ボタンにカーソルを合わせると、この法律が国内の利益団体の承認に対して及ぼす効力を確認することができます。
```

### 変更後日本語テキストデータ

```
この[concept_interest_group]が支持する[Concept('concept_law', '$concept_laws$')]を希望順に並べた一覧も用意されています。$concept_enactment_of_laws_enact$ボタンにカーソルを合わせると、この$concept_law$が国内の$concept_interest_groups$の[concept_approval]に対して及ぼす効力を確認することができます。
```

## 変更の理由（必須）

- 誤訳のため、わかりにくい表現になっている
  - 「希望順に並べ替えることで確認できる」ではなく、並べ替えられた状態で表示されているので確認しやすいという意味
  - 制定ボタンをホバーして確認できるのは「法律の効力」であり、その対象は「利益団体の承認」に対して
- 「enactボタン」が未訳（定数$enact$が存在しないため。英語版から元々あったバグ？）

## ゲームバージョン（必須）

1.0.5

## DLCの有無（必須）

なし

## MODの有無（必須）

日本語改善MOD
Switch Languages

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
ご提案どおりに修正しました。

クローズします。
