### ISSUE TITLE
スペイン人の姓名

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#362]
## 問題の固有名詞と希望する変更（必須）

アレジャンドロ：アレハンドロ
バルタザール：バルタサル
ベニト：ベニート
カリクスト：カリスト
セレスティノ：セレスティーノ
ガビーノ：ガビノ
ガスパー：ガスパル
ジェナーロ：ヘナロ
ゴンザーロ：ゴンサロ
ヤコボ：ハコボ
ヤイメ：ハイメ
ヨアキン：ホアキン
ジョゼ：ホセ
ジョゼ・アントニオ：ホセ・アントニオ
ジョゼ・マニュエル：ホセ・マヌエル
ジョゼ・マリア：ホセ・マリア
ジュアン：フアン
ユアン・バウティスタ：フアン・バウティスタ
ジュリオ：フリオ
ジョルジ：ホルヘ
メルコール：メルチョル
ミグエル：ミゲル
セジスムンド：セヒスムンド
ヴァレリアーノ：バレリアーノ

アレジャンドリナ：アレハンドリナ
エンリケッタ：エンリケタ
グイラーミナ：ギリェルミナ
ヘルミニア：エルミニア

アルヴァレズ・デ・トレード：アルバレス・デ・トレド
デ・アルボルノズ：デ・アルボルノス
バリオヌエヴォ：バリオヌエボ
デ・ボホルケス：デ・ボオルケス
カギガル・デ・ラ・ヴェガ：カヒガル・デ・ラ・ベガ
ディエズ・デ・リヴェラ：ディエス・デ・リベラ
デ・ドメック：デ・ドメク
フェルナンデズ・デ・コルドバ：フェルナンデス・デ・コルドバ
デ・ラ・フュエンテ：デ・ラ・フエンテ
フィッツ・ジェームズ・スチュアート：フィッツ＝ジェームズ・スチュアート
デ・フィギューラ：デ・フィゲロア
フェルナンデス・ザパタ：フェルナンデス＝サパタ
フェルナンデズ・デ・コルドバ：フェルナンデス・デ・コルドバ
ギロン：ヒロン
デ・グズマン：デ・グスマン
ゴンザレズ・デ・シエンフエゴス：ゴンサレス・デ・シエンフエーゴス
ヒダルゴ・デ・シスネロス：イダルゴ・デ・シスネロス
ヨルダン・デ・ウリエス：ホルダン・デ・ウリエス
ロペス・デ・ハロ：ロペス・デ・アロ
デ・ロラク：デ・リョラチ
メッシア：メシア
オルティズ・デ・ラ・リヴァ：オルティス・デ・ラ・リバ
オードネル：オドンネル
デ・オロズコ：デ・オロスコ
プリモ・デ・リヴェーラ：プリモ・デ・リベラ
ペレズ・デ・ヘラスティ：ペレス・デ・エラスティ
デ・パラフォックス：デ・パラフォクス
パレズ・デ・ウリエス：ペレス・デ・グスマン
ピネイロ：ピニェイロ
デル・ピラー・オソリオ：デル・ピラル・オソリオ
デ・クイロス：デ・キロス
デ・クインタニラ：デ・キンタニリャ
ラミレズ・デ・サヴェドラ：ラミレス・デ・サアベドラ
デル・ロサリオ・ヴェレテラ：デル・ロサリオ・ベレテラ
デ・ロジャス：デ・ロハス
ルイズ・デ・アラナ：ルイス・デ・アラナ
スアレズ・デ・アルグディン：スアレス・デ・アルグディン
デ・シルヴァ：デ・シルバ
デ・サトゥルステギ：デ・サトルステギ
デ・サラヴェルト：デ・サラベルト
サンシズ：サンチス
デ・ウルクイジョ：デ・ウルキホ
デ・ウズクエタ：デ・ウスケタ
デ・ヴァルダ：デ・バルダ
デル・ヴァレ：デル・バリェ
デ・ヴィラロンガ：デ・ビリャロンガ
デ・ラ・ヴェラ：デ・ラ・ベラ
ヴァルデス：バルデス
デ・ズフィア：デ・スフィア

アキューナ：アクーニャ
アギューレ：アギーレ
アルカラ・ザモーラ：アルカラ＝サモーラ
アレンデサラザール：アリェンデサラサル
アリュギュエレス・メレス：アルグエリェス＝メレス
アズナール：アスナル
アルヴァレズ：アルバレス
アラボラザ：アラボラサ
アランツァディ：アランサディ
ブガラール：ブガリャル
ボニーラ：ボニーリャ
セルヴェラ：セルベラ
ディアズ：ディアス
エグイアザバル：エギアサバル
フェルナンデズ：フェルナンデス
ファジャルド：ファハルド
ゴンザレス：ゴンサレス
グラセット：グラセト
ヘレディア：エレディア
ヘルナンデス：エルナンデス
ヘレーラ：エレーラ
ヘヴィア：エビア
イザギレ：イサギレ
ロレンザナ：ロレンサナ
ランダザバル：ランダサバル
ララナーガ：ララニャーガ
マロート：マロト
マルティネズ・カンポス：マルティネス＝カンポス
メネンデズ：メネンデス
ミャジャ：ミアハ
ミラン・アストレイ：ミリャン＝アストライ
モーラ：モラ
ムノズ：ムニョス
マルケズ：マルケス
ムゲルザ：ムゲルサ
ムグルザ：ムグルサ
ナルヴェズ：ナルバエス
オルドネス：オルドーニェス
オゾレス：オソレス
パヴィア：パビア
ペレズ：ペレス
パガザ：パガサ
パチュロ：パトゥーリョ
クエポ・デ・ラーノ：ケイポ・デ・リャーノ
キンターナ：キンタナ
クイランテ：キランテ
ロジョ：ロホ
ルイズ：ルイス
レパレズ：レパレス
サンジューロ：サンフルホ
シルヴェスト：シルベストレ
サプリッサ：サプリサ
ツヅリ：トゥドゥリ
ヴァルデス：バルデス
ヴァレーラ：バレーラ
ヴィラポル：ビリャポル
ヴィラー：ビリャル
ヴェラ：ベラ
ヴィロタ：ビリョータ
ヴィラルタ：ビラルタ
ヴァラナ：バリャーナ
ヴァズケス：バスケス
ワイラー：ウェイレル
イェーグ：ヤグエ
ザモラ：サモーラ
ザバラ：サバラ

デ・オルレアン：デ・オルレアンス

デ・ブルボン：デ・ボルボン

## 変更の理由（必須）

日本語では一般的ではない表記であるため。

## ゲームバージョン（必須）

1.0.5

## DLC有無（必須）

なし

## MOD有無（必須）

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正内容追加
デ・ブルボン：デ・ボルボン

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
