### ISSUE TITLE
提督の詳細画面の艦艇の居場所

### ISSUE THREAD

**Issue by Yoto** [matanki-saito/vic3jpadvmod#363]
## スクリーンショット（必須）
![2022-11-06](https://user-images.githubusercontent.com/388340/200151089-66c6b441-aa1a-4142-a007-fd21aa39ae43.png)

## 問題のあるインターフェイス（必須）

提督の詳細画面

## 問題のテキスト（必須）

```
[場所]の
```

## 希望する変更（必須）

```
[場所]  or  [場所]に駐留しています
```

## 変更の理由（必須）

日本語として不自然

## ゲームバージョン（必須）

1.0.5

## DLCの有無（必須）

なし

## MODの有無（必須）

日本語改善Mod

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
こちら英語版でも同様の現象が起きていますので、バグ扱いにします

**Comment by Yoto** [comment]
英語では`in [場所]`となっていて、その場所に艦艇がいるのが読み取れるようになっています。わかりにくいですが。
なのでバグではなく誤訳ではないでしょうか。

**Comment by inarizushi0309** [comment]
ここのエントリがMILITARY_PANEL_BUILDING_TROOP_NAME
```[Building.GetState.GetName]の[Building.GetCustom('troop_name')]```
となっており、[Building.GetCustom('troop_name')]変数が表示されないのでバグです

**Comment by Yoto** [comment]
なるほど、変数名まで見てませんでした。了解しました。

**Comment by matanki-saito** [comment]
報告をしました。
https://forum.paradoxplaza.com/forum/threads/victoria-iii-localization-bug.1558605/

**Comment by matanki-saito** [comment]
報告を完了したのでCloseと致します
