### ISSUE TITLE
商品のツールチップ「生産中」「使用中」

### ISSUE THREAD

**Issue by yastronaut** [matanki-saito/vic3jpadvmod#364]
## スクリーンショット（必須）
![無題](https://user-images.githubusercontent.com/70649705/200151109-860d5ad1-9ddb-4b6c-ad0d-e0f24dbd0ea5.jpg)

## 問題のツールチップ（必須）
商品のツールチップ

## 問題の表現（必須）
```
生産中:
（建物リスト）
使用中:
（建物リスト）
```
## 問題箇所の英文（任意）
```
Produced in
（建物リスト）
Used in
（建物リスト）
```
## 希望する変更（必須）
```
生産中:　→　生産施設:
使用中:　→　使用施設:

他にいい案があったらお願いします

```

## 変更の理由（必須）

自分が持っていない建物もリストに表示されるようなので
〇〇中だと自国で生産・使用していると誤解されそうと思いました

## ゲームバージョン（必須）
1.0.4
## DLC有無（必須）
なし
## MOD有無（必須）
JapaneseLanguageAdvancedMod

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
ありがとうございます。提案通りに修正しました。これにてクローズします。
