### ISSUE TITLE
戦禍（Devastation）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#365]
## スクリーンショット（任意）
![20221106160815_1](https://user-images.githubusercontent.com/42687608/200158734-626479df-8a1a-4584-922f-c400e505b8a8.jpg)

## 問題の用語（必須）
```
戦禍
```

## 英語版の表現（任意）
```
Devastation
```

## 希望する変更（必須）
```
荒廃
```

## 変更の理由（必須）
戦争だけでなく洪水などの災害でも増加するため。

## ゲームバージョン（必須）
1.0.4

## DLC有無（必須）
- Victoria II Remastered Soundtrack
- American Buildings Pack

## MOD有無（必須）
- 自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
「荒廃」に確定し、修正を完了しました。
