### ISSUE TITLE
表面上の和平への条件設定（和平条件の白紙化）

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#366]
※「｀｀｀」は消さないでください

## スクリーンショット（任意）

![20221106161712_1](https://user-images.githubusercontent.com/43299334/200159297-20c4586f-ffcd-43b9-bac7-b8de6095851d.jpg)

## 問題の用語（必須）

```
表面上の和平への条件設定
```

## 英語版の表現（任意）

```
Set Terms to White Peace
```

## 希望する変更（必須）

```
条件を白紙に戻す
```

## 変更の理由（必須）

意味の通らない訳になっているため

## ゲームバージョン（必須）

1.0.5

## DLC有無（必須）

無し

## MOD有無（必須）

）なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。
