### ISSUE TITLE
戦略（外交戦）およびそのツールチップ

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#367]
※「｀｀｀」は消さないでください

## スクリーンショット（任意）
※画像はドラッグ＆ドロップで貼り付けられます。
※できるだけ問題箇所の前後を含めて貼ってください。
![20221106145814_1](https://user-images.githubusercontent.com/43299334/200159463-189e8f17-db0f-48f6-9e00-cf34db5bfb9c.jpg)

## 問題の用語（必須）

```
戦略

（国名）に残された戦略は○回です。
```

## 英語版の表現（任意）

```
Maneuver

#header 先制国[Concept('concept_maneuver', '$concept_maneuvers$')]#!
[DiplomaticPlay.GetInitiator.GetName|v]に残された[Concept('concept_maneuver', '$concept_maneuvers$')]は[DiplomaticPlay.GetNumInitiatorManeuversRemaining|v]回です。
```

## 希望する変更（必須）

```
機略

#header 先制国[Concept('concept_maneuver', '$concept_maneuvers$')]#!
[DiplomaticPlay.GetInitiator.GetName|v]に残された[Concept('concept_maneuver', '$concept_maneuvers$')]は[DiplomaticPlay.GetNumInitiatorManeuversRemaining|v]です。
```

## 変更の理由（必須）
外交戦のはじめに与えられるポイントのこと。これを消費することで戦争目標の追加が可能。
チェスにはマヌーバという用語があるが、なんとなくイメージを合わせた程度か。
戦略でも間違いではないが、公式訳ではTacticsやStrategyなど、いろんなものが戦略とされており訳が重複している。
さらに、将軍の特性も「慎重な戦略」などになっており、ややこしいので変更してしまった方が良いと思う。
ここでは少しでもコマを動かすイメージが湧くように機略としてみた。

ツールチップにあるような回数制ではないため、こちらは明確に誤訳である。
## ゲームバージョン（必須）

1.0.5

## DLC有無（必須）

無し

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。
