### ISSUE TITLE
ブリーチローダー（Breech Loaders）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#368]
## スクリーンショット（任意）
![20221106170214_1](https://user-images.githubusercontent.com/42687608/200160508-d641d1df-fb12-4c18-9587-7dc38c03824d.jpg)

## 問題の用語（必須）
```
ブリーチローダー
```

## 英語版の表現（任意）
```
Breech Loaders
```

## 希望する変更（必須）
```
後装砲
```

## 変更の理由（必須）
誤訳ではないが、技術の名称は「後装砲」（Breech-Loading Artillery）であり、統一が取れていない。
後装式の銃（元込め銃）を含んでいるとも考えられるが、スクショの通り他の方式はカノン砲、滑空砲とすべて砲であり、後装砲だけを特別扱いする理由はない。
あえてカタカナにする理由もなく、日本人にわかりやすい「後装砲」とすべきである。

## ゲームバージョン（必須）
1.0.4

## DLC有無（必須）
- Victoria II Remastered Soundtrack
- American Buildings Pack

## MOD有無（必須）
- 自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
「後装砲」に確定し、修正が完了しました。
