### ISSUE TITLE
【修正提案】技術開発画面ツールチップ（～へと導きます）

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#369]
※「｀｀｀」は消さないでください

## スクリーンショット（必須）

![20221106155255_1](https://user-images.githubusercontent.com/42710893/200161835-0faf722d-085d-466c-8fdb-15e93a9c3166.jpg)

## 問題のツールチップ（必須）

技術開発画面ツールチップ

## 問題の表現（必須）

```
TOOLTIP_UNLOCK_TECH_TYPE:0 "$TECH_TYPE$へと導きます ([concept_technology])"

```

## 問題箇所の英文（任意）

```
TOOLTIP_UNLOCK_TECH_TYPE:0 "Leads to $TECH_TYPE$ ([concept_technology])"
```

## 希望する変更（必須）

```
TOOLTIP_UNLOCK_TECH_TYPE:0 "$TECH_TYPE$に繋がります ([concept_technology])"　等
```

## 変更の理由（必須）

間違いではないが、個人的にやや不自然な言い回しに思える。

## ゲームバージョン（必須）

1.0.5

## DLC有無（必須）

なし

## MOD有無（必須）

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
「[技術]の研究を可能にします (技術)」と表示されるように修正しました。

クローズします。
