### ISSUE TITLE
修正提案：ギャリゾン

### ISSUE THREAD

**Issue by discordine** [matanki-saito/vic3jpadvmod#37]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![image](https://user-images.githubusercontent.com/46787431/198010029-820bf201-8fc0-4b50-b127-61a47093a712.png)

## 問題の用語（必須）

ギャリゾン

## 希望する変更（必須）

未割当or駐屯中

## 変更の理由（必須）

日本語になっていた方が分かりやすい

## ゲームバージョン（必須）

1.0.1

## DLC有無（必須）

無し

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1034784468759740426
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by matanki-saito** [comment]
～の一部として防衛しますって出てくるから「駐屯部隊」にしないとだめか
