### ISSUE TITLE
受け入れられた文化 / 受け入れられた宗教（Accepted Culture / Accepted Religion）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#371]
## スクリーンショット（任意）
![20221106174800_1](https://user-images.githubusercontent.com/42687608/200162072-cdb8eda0-ad7a-484c-b1ba-fa0f4535fdcf.jpg)

## 問題の用語（必須）
```
受け入れられた文化 / 受け入れられた宗教
```

## 英語版の表現（任意）
```
Accepted Culture / Accepted Religion
```

## 希望する変更（必須）
```
受容文化 / 受容宗教
```

## 変更の理由（必須）
訳語が長すぎてゲーム的に意味のある用語であることがわかりにくいため。
従来の他作品にならい accepted を「受容」と訳すことを提案する。

## ゲームバージョン（必須）
1.0.4

## DLC有無（必須）
- Victoria II Remastered Soundtrack
- American Buildings Pack

## MOD有無（必須）
- 自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
「受容文化」「受容宗教」に確定し、修正を完了しました。
