### ISSUE TITLE
ハンセン病

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#372]
## スクリーンショット（任意）
なし

## 問題部分（タイトル・本文・選択肢）

```
本文
```

## 問題のイベントタイトル（必須）

```
理想の手
```

## 問題のイベント本文（任意・抜粋可）

```
「もし誰かがハンセン病療養所を廃止することを提案したら、きっと誰もが最初に聞くのは、「患者はどこへ行くのだ？」だろう。しかし、私たちは、閉鎖された救護院から溢れ出る貧困と絶望がそのような懸念の原因にはならないはずだと思っている。まっとうな暮らしができない人たちだ。彼らが街に溢れたら、どんないいかげんな生活を送ることになるのだろうか？」
```

## 問題のイベント選択肢（任意）

ー

## 希望する変更（必須・修正部分のみ）

```
ハンセン病　→　らい病
```

## 変更の理由（必須）

この時代にハンセン病という名称は存在せず、原文でも「Hansen's disease」ではなく「leper」と書かれている

## プレイ国家

ー

## ゲームバージョン（必須）

1.0.5

## DLC有無（必須）

なし

## MOD有無（必須）

日本語改善MOD

**Comment by BLACKTIGER-NB** [comment]
VIC3のレーティングはPEGI 12です。日本のCERO B相当です。
「役身折酬」の時から疑っていたのですが、公式訳チームは日本におけるゲーム表現の自主規制を意識して翻訳しているようです。
しかし、そちらのチームはそういった視点がほとんど無いんでしょうね。それはCK2、CK3の時から知ってましたが。
議論や投票をしても被差別者が少数なので被差別者側に不利になります。それどころか、私の書き込み自体に殺害予告などの報復を受ける危険があります(ゲーマーゲート事件など)。なので、冷静さを保つのが難しい。

基本的には「当事者の考えを十分に調べて言葉を選定する」が解決方法ですが、労力的に無理ならば「他でやってることと横並び的な言葉にする」くらいですかね。

そういえば、ここの主催は「冷静だから悪意がない」という西村博之さんが聖人になるような酷い価値観を表明していましたね。(人格ではなく行動への批判)

**Comment by ikabomb** [comment]
原文でハンセン病ではなく癩病と明記されていることの意義を考えるべきでは？　英語圏であっても通常癩病と表記されることはなく、これは正面から差別の存在を描いているためでしょう。そのようなとき、果たして臭いものに蓋的に差別を見なかったことにするような語選定が適切たり得ましょうか？
当時癩病と呼ばれていたこと、そのことのみで癩病とする訳は正当化されるでしょう。

**Comment by ChiefIdeologue** [comment]
議論の結果を踏まえ、提案通りらい病に修正しました。

**Comment by ChiefIdeologue** [comment]
議論が終了したため、クローズします。
