### ISSUE TITLE
利益団体の特性が発動・解除されたときの通知

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#373]
## スクリーンショット（必須）
![20221106175638_1](https://user-images.githubusercontent.com/42687608/200162366-2fc7988f-c800-4dea-b781-bd21f299bd7d.jpg)

## 問題のあるインターフェイス（必須）
利益団体の特性が発動・解除されたときの通知

## 問題のテキスト（必須）
```
（特性名）が発動しました
（特性名）の発動が解除されました
```

## 希望する変更（必須）
```
（特性名）発動
（特性名）解除
```

## 変更の理由（必須）
発動されたのか解除されたのかわかりにくいため。解除の方は長すぎて見切れている。
原文は単にdeactivatedであり、わざわざ「発動が解除されました」と翻訳する必要はない。

## ゲームバージョン（必須）
1.0.4

## DLC有無（必須）
- Victoria II Remastered Soundtrack
- American Buildings Pack

## MOD有無（必須）
- 自作Mod多数

**Comment by clamm0363** [comment]
「[特性]が[発動/消失]」と修正しました。

クローズします。
