### ISSUE TITLE
燃焼機関（Combustion Engine）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#374]
## スクリーンショット（任意）
![20221106185103_1](https://user-images.githubusercontent.com/42687608/200164298-e2f818fa-5b1b-49a7-aff4-7c3d48ea0693.jpg)

## 問題の用語（必須）
```
燃焼機関
```

## 英語版の表現（任意）
```
Combustion Engine
```

## 希望する変更（必須）
```
内燃機関
```

## 変更の理由（必須）
直訳としては間違っていないが、ここでは外燃機関ではなく内燃機関を表していると思われるため。
根拠は説明文にある「機関内で発生する爆発力」（combustions taking place inside the engine）という表現。

## ゲームバージョン（必須）
1.0.4

## DLC有無（必須）
- Victoria II Remastered Soundtrack
- American Buildings Pack

## MOD有無（必須）
- 自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。
