### ISSUE TITLE
「選挙制の官僚」のテキスト

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#376]
※「｀｀｀」は消さないでください

## スクリーンショット（任意）
![Elected_Bureaucrats](https://user-images.githubusercontent.com/50406316/200175146-eba331d8-a795-40fd-ae88-037fd42e19f5.png)

## 問題のツールチップ（必須）

官僚制の法律の中にある選挙制の官僚

## 問題の表現（必須）

```
地方の統治者は構成員によって選出されます。権力を分散させると同時に、市民を管理しやすくなります。
```

## 問題箇所の英文（任意）

```
Local governors are elected by their constitutents, decentralizing power while making citizens easier to manage.
```

## 希望する変更（必須）

```
地方の知事は現地の選挙区民によって選出されます。権力を分散させると同時に、市民を管理しやすくなります。
「地方の統治者」→「地方の知事」、「構成員」→「現地の選挙区民」に変更
```

## 変更の理由（必須）
地方行政区画の長を選挙で選ぶ制度を想定したテキストだが、訳語が直訳すぎるので、より適切な単語に変更したい。

## ゲームバージョン（必須）

1.0.5

## DLC有無（必須）

無し

## MOD有無（必須）

翻訳改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
提案通り変更してクローズします
