### ISSUE TITLE
大清「で」後継者

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#377]
※「｀｀｀」は消さないでください

## スクリーンショット（必須）
![de](https://user-images.githubusercontent.com/50406316/200176810-f599c8e7-b7f4-4a42-9516-6791e92a6f6a.png)

## 問題のあるインターフェイス（必須）

将軍や後継者などの人物画面

## 問題のテキスト（必須）

```
大清「で」後継者
```

## 希望する変更（必須）

```
大清「の」後継者
```

## 変更の理由（必須）

助詞の訂正。
英語では[SelectLocalization(Character.IsRuler, 'of','in')]で、対象が君主かそれ以外かでofとinを使い分け、Emperor of JapanとGeneral in Japanのように使い分けているが、日本語で使い分ける必要はなく、どっちも「の」で済むため。

## ゲームバージョン（必須）

1.0.5

## DLCの有無（必須）

なし

## MODの有無（必須）

翻訳改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
提案通り直してクローズします
