### ISSUE TITLE
Additive/Multiplicative

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#378]
※「｀｀｀」は消さないでください

## スクリーンショット（任意）
![Interest](https://user-images.githubusercontent.com/50406316/200182090-ca4e7bf9-0324-4f10-ae8c-3a6081a0b564.png)

## 問題の用語（必須）

```
相加利子率補正
多重利子率補正
```

## 英語版の表現（任意）

```
Additive Interest Rate Modifiers
Multiplicative Interest Rate Modifiers
```

## 希望する変更（必須）

```
利子率増減補正
利子率乗算補正
```

## 変更の理由（必須）

計算式は(ベース＋Additive)xMultiplicativeとなる。
画像では(20%-2%-2%-2%)x(1-50%-10%)=14%x40%=5.6%。
相加や多重ではわかりにくいので、単純に増減や乗算としたい。

## ゲームバージョン（必須）

1.0.5

## DLC有無（必須）

無し

## MOD有無（必須）

翻訳改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
提案通り修正してクローズします
