### ISSUE TITLE
日本の政党名

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#379]
## 問題の固有名詞と希望する変更（必須）

国家市民同盟：国民同盟
庶民党：平民党

## 変更の理由（必須）

国民同盟　https://ja.wikipedia.org/wiki/%E5%9B%BD%E6%B0%91%E5%90%8C%E7%9B%9F_(%E6%97%A5%E6%9C%AC)
平民党　https://ja.wikipedia.org/wiki/%E6%97%A5%E6%9C%AC%E7%A4%BE%E4%BC%9A%E5%85%9A_(1906)

## ゲームバージョン（必須）

1.0.5

## DLC有無（必須）

なし

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
