### ISSUE TITLE
宗教の固有名詞

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#38]
## 問題の固有名詞と希望する変更（必須）

東方正教会：東方諸教会
スンニ派：スンナ派
ユダヤ諸語：ユダヤ教
上座仏教：上座部仏教
東方教会：東洋宗教

仏教徒：仏教
キリスト教徒：キリスト教
イスラム教徒：イスラム教

## 変更の理由（必須）
日本語では一般的ではない表記であるため

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1034803483070701598
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by ChiefIdeologue** [comment]
仏教徒、キリスト教徒、イスラム教徒、を修正内容に追加しました。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
