### ISSUE TITLE
国家の声（国家→国歌）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#380]
## スクリーンショット（任意）
![20221107114544_1](https://user-images.githubusercontent.com/42687608/200220153-60262e55-c7ed-452e-991d-87f2f7e0c486.jpg)

## 問題部分（タイトル・本文・選択肢）
```
本文、選択肢
```

## 問題のイベントタイトル（必須）
```
国家の声
```

## 問題のイベント本文（任意・抜粋可）
```
彼らは国民の精神高揚に相応しい適切な国家が欠如しているという驚きの事態に注目しているとのことです。
```

## 問題のイベント選択肢（任意）
```
今こそクールな国家を！
```

## 希望する変更（必須・修正部分のみ）
```
国家→国歌
```

## 変更の理由（必須）
原文はanthemであり、単純な誤変換だと思われる。

## プレイ国家
アメリカ合衆国

## ゲームバージョン（必須）
1.0.4

## DLC有無（必須）
- Victoria II Remastered Soundtrack
- American Buildings Pack

## MOD有無（必須）
- 自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
「国家」から「国歌」に修正を完了しました。
