### ISSUE TITLE
「和平協定を提案」ボタンの、受理されない場合のマウスオンツールチップ

### ISSUE THREAD

**Issue by flowlanss** [matanki-saito/vic3jpadvmod#381]
※「｀｀｀」は消さないでください

## スクリーンショット（必須）

![image](https://user-images.githubusercontent.com/54560025/200231330-b0ee6af0-9b1b-4982-a2f6-d15b9b8b5a03.png)

## 問題のツールチップ（必須）

「和平協定を提案」ボタンのマウスオンツールチップ

## 問題の表現（必須）

```
×どの党も和平協定に賛同しませんでした。
```

## 問題箇所の英文（任意）

```
@red_cross! #bold No party agrees to this [concept_peace_deal].#!
```

## 希望する変更（必須）

```
×この和平協定に合意する国はありません。
(　@red_cross! #bold この[concept_peace_deal]に合意する国はありません。#!　)

```

## 変更の理由（必須）

党ではなく、Partyは陣営などを指すものと思われ、賛同する場合は賛同する国が表示される。また和平協定には負ける側も署名するため、賛意のある賛同とするよりは合意くらいにしておくのがよいと思われる。

## ゲームバージョン（必須）

1.0.5

## DLC有無（必須）

Victoria II Remastered Soundtrack
American Buildings Pack

## MOD有無（必須）

Switch Languages
JapaneseLanguageAdvancedMod

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by flowlanss** [comment]
```
ファイル：japanese/interfaces_l_english.json
キー：WAR_PANEL_NONE_ACCEPT_PEACE
修正前：@red_cross! #bold どの党も[concept_peace_deal]に賛同しませんでした。#!
修正後：@red_cross! #bold この[concept_peace_deal]に合意する国はありません。#!
```
以上で修正を行いました。
クローズします。
