### ISSUE TITLE
「反乱」と「叛乱」

### ISSUE THREAD

**Issue by BLACKTIGER-NB** [matanki-saito/vic3jpadvmod#382]
※「｀｀｀」は消さないでください

## スクリーンショット（任意）
なし

## 問題の用語（必須）

```
反乱
叛乱
```

## 英語版の表現（任意）

```
uprising
Mutiny
revolt
等
```

## 希望する変更（必須）

```
反乱
```

## 変更の理由（必須）
・表記ゆれしている
・英語の単語に対応して使い分けられているわけでもなさそう
・反乱は常用漢字

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）
American Building Pack	
Expansion Pass
Victoria 2 Remastered Soundtracks

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
ご指摘の通り漢字の統一は「反乱」に揃えました。ありがとうございました。
uprising（蜂起）やMutiny（暴動）を「反乱」に包摂することは定訳の観点から指示できないので見送らせていただきます。

**Comment by matanki-saito** [comment]
修正が完了したのでクローズします。
