### ISSUE TITLE
技術・軍事統計のマウスオンツールチップ

### ISSUE THREAD

**Issue by flowlanss** [matanki-saito/vic3jpadvmod#383]
※「｀｀｀」は消さないでください

## スクリーンショット（必須）

![image](https://user-images.githubusercontent.com/54560025/200236914-4ebc4a66-d1c6-4010-bc0d-1544925eb166.png)

## 問題のツールチップ（必須）

技術→軍事統計のマウスオンツールチップ

## 問題の表現（必須）

```
動員 商品条件です： -20%

( [Concept('concept_mobilize_battalion', '$concept_mobilize_battalion_mobilization$')] [Concept('concept_good','$concept_goods$')]条件です )
```

## 問題箇所の英文（任意）

```
Mobilization Goods Requirements

[Concept('concept_mobilize_battalion', '$concept_mobilize_battalion_mobilization$')] [Concept('concept_good','$concept_goods$')] Requirements
```

## 希望する変更（必須）

```
動員大隊商品要求量： -20%
```

## 変更の理由（必須）

意味が通じないため。条件ですの部分にマウスオンすると小銃などの要求量が減る技術だとわかるため、上記のようにしたい。
商品の部分も本当は物資などとしたいが、コンセプトを持ち出しているので変更は難しいか。

## ゲームバージョン（必須）

1.0.5

## DLC有無（必須）

Victoria II Remastered Soundtrack
American Buildings Pack

## MOD有無（必須）

Switch Languages
JapaneseLanguageAdvancedMod

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by flowlanss** [comment]
「動員された大隊の商品消費」となるように修正しました。クローズします。
