### ISSUE TITLE
「百姓」

### ISSUE THREAD

**Issue by BLACKTIGER-NB** [matanki-saito/vic3jpadvmod#384]
※「｀｀｀」は消さないでください

## スクリーンショット（任意）

![自給農家](https://user-images.githubusercontent.com/75819188/200239550-ea3c15ae-ee50-4179-a632-5f1999563665.jpg)

## 問題の用語（必須）

```
百姓
```

## 英語版の表現（任意）

```
Peasants
```

## 希望する変更（必須）

```
自給農
自給農家
小農民(「百姓」への変更前に行われた提案)
```

## 変更の理由（必須）

・説明文と表記ゆれしている
・VIC3のレーティングはPEGI 12です。日本のCERO B相当です。
・現在では放送禁止用語というレベルの差別語。(個人的には運用が重要だと思います)
・「百姓」に屠殺業者等の「ケガレとされた人たち」は入ってないのではないでしょうか(今も残る問題)。
・海外の人々(たとえばアーミッシュ)を日本語文化的な「百姓」と呼んでいいとは思わない。
・「ゲーム内の存在がゲーム内の存在に向かって『百姓』と言う(自称も含む)」ならばともかく、「ゲームがゲーム内の状況を現在のプレイヤーに伝える言葉」として適切なのですか。
・公式訳は"Sea of Japan / East Sea"をそのまま訳したほど政治的相剋を避けているのに、政治的相剋のある言葉を新規に導入するのはどうなのですか。
・日本でのプレイしか想定していない人がそれなりの数居るのではないですか。それだけなら個人の自由ですが、その人達の中に他の国でプレイする人のことを何も考えてない人がそれなりにいそうです。議論も投票もその人達が満足する結果になりやすいと思います。
・日本語ローカライズなので、日本語文化によってしまうのは仕方がないでしょう。しかし、あまり日本語文化によりすぎるのは、paradoxによる世界各地へいろいろな言語で商品を売るということと相反すると思います。
・こういった問題提起をすると殺害予告などの害意を受けるのであまり冷静ではいられない。(ゲーマーゲート事件など)
・ここの主催は私に向かって「(差別は行動だから)言葉の置きかえは意味が無い」と言った過去ありましたが、paradoxはUncivilized NationからUnrecognized Countryと”言葉の置きかえ”をしました。

## ゲームバージョン（必須）

1.0.5

## DLC有無（必須）
American Building Pack	
Expansion Pass
Victoria 2 Remastered Soundtracks

## MOD有無（必須）
JapaneseLanguageAdvancedMod
地图乱码修复
Construction Queue with States
音楽追加MOD複数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
説明文はご指摘の通りに修正します。
感想ではなく、根拠を示すようにお願いします。
販売戦略については最終的にはPDXのローカライズ担当者が取り入れるかの事業判断します。
上記のため、クローズします
