### ISSUE TITLE
イベント：商売の問題の選択肢（typo）

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#385]
※「｀｀｀」は消さないでください

## スクリーンショット（任意）
![20221107205253_1](https://user-images.githubusercontent.com/42710893/200315807-3ae1cac7-efa0-4dc2-94a6-33b876a11e14.jpg)

## 問題部分（タイトル・本文・選択肢）

```
選択肢B
```

## 問題のイベントタイトル（必須）

```
商売の問題
```

## 問題のイベント本文（任意・抜粋可）

```
```

## 問題のイベント選択肢（任意）

```
exhibition_events.7.b:0 "1ペニーや2ペニー程度ならどってことない..."
```

## 希望する変更（必須・修正部分のみ）

```
1ペニーや2ペニー程度ならどうってことない...
```

## 変更の理由（必須）

typo

## プレイ国家

ベルギー

## ゲームバージョン（必須）

1.0.5

## DLC有無（必須）

なし

## MOD有無（必須）

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
原案どおり、「1ペニーや2ペニー程度ならどうってことない...」で修正
