### ISSUE TITLE
イベント：空へと伸びる手

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#386]
※「｀｀｀」は消さないでください

## スクリーンショット（任意）

![20221107210948_1](https://user-images.githubusercontent.com/42710893/200314137-1bf42ff8-975f-4816-b420-8512aa3a4002.jpg)

## 問題部分（タイトル・本文・選択肢）

```
本文
```

## 問題のイベントタイトル（必須）

```
空へと伸びる手
```

## 問題のイベント本文（任意・抜粋可）

```
skyscraper.2.d2:0 "[SCOPE.sState('skyscraper_state').GetName]の[SCOPE.sState('skyscraper_state').GetCityHubName] [SCOPE.sBuilding('skyscraper_building_scope').GetName]が完成しました…"

skyscraper.2.f:0 "…私が完全なる心の策動から生み出しものだ。…"
```

## 問題のイベント選択肢（任意）

```

```

## 希望する変更（必須・修正部分のみ）

```
skyscraper.2.d2:0"[SCOPE.sState('skyscraper_state').GetName]の[SCOPE.sState('skyscraper_state').GetCityHubName]に[SCOPE.sBuilding('skyscraper_building_scope').GetName]が完成しました…"

skyscraper.2.f:0"…私が完全なる心の策動から生み出したものだ。…"
```

## 変更の理由（必須）

助詞が抜けている
※skyscraper.2.d2:0と合わせてskyscraper.2.d:0も同様の修正が必要

skyscraper.2.f:0の方はtypoと思われる

## プレイ国家

ベルギー

## ゲームバージョン（必須）

1.0.5

## DLC有無（必須）
なし

## MOD有無（必須）
日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
skyscraper.2.d
skyscraper.2.d2
skyscraper.2.f
上記三つのキーにつきまして、提案どおりに修正しました。

クローズします。
