### ISSUE TITLE
神を崇める会

### ISSUE THREAD

**Issue by kurutto115** [matanki-saito/vic3jpadvmod#389]
## スクリーンショット（任意）
![Victoria 3 2022_11_07 21_15_54](https://user-images.githubusercontent.com/117251782/200341304-80b8f8a9-1de3-41a7-a96a-8c1468f0ed6a.png)

## 問題の固有名詞（必須）

神を崇める会

## 希望する変更（必須）

拝上帝会

## 変更の理由（必須）

この「神を崇める会」が指すのは太平天国の前身組織である[拝上帝会](https://ja.wikipedia.org/wiki/%E6%8B%9D%E4%B8%8A%E5%B8%9D%E4%BC%9A)だと思われます
（中国語に設定すると「拜上帝会」と表示され、英語では拝上帝会の定訳である"God Worshipping Society"となります）

## ゲームバージョン（必須）

1.0.5

## DLC有無（必須）

なし

## MOD有無（必須）

※できるだけMODのない状態で問題を確認してください。

本プロジェクトMODのみ

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by discordine** [comment]
関連エントリ4つを修正
