### ISSUE TITLE
外交戦の中立宣言のダイアログボックスにある「プレイ」

### ISSUE THREAD

**Issue by Yoto** [matanki-saito/vic3jpadvmod#392]
## スクリーンショット（任意）
![2022-11-08](https://user-images.githubusercontent.com/388340/200437895-f4b18059-00e3-4cc0-96eb-16d471043a61.png)

## 問題の用語（必須）

```
後からプレイに参加することはできません。
```

## 英語版の表現（任意）

```

```

## 希望する変更（必須）

```
後から外交戦に参加することはできません。
```

## 変更の理由（必須）

外交プレイが外交戦に名称変更されたが、外交プレイの略語としてのプレイが変更されていないため。

## ゲームバージョン（必須）

1.0.5

## DLC有無（必須）

Victoria II Remastered Soundtrack
American Buildings Pack

## MOD有無（必須）

テスト用フォントMod
日本語改善Mod

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
「プレイ」の部分を「外交戦」と修正しました。

クローズします。
