### ISSUE TITLE
共和国の政体説明のツールチップ

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#393]
※「｀｀｀」は消さないでください

## スクリーンショット（必須）
![republic](https://user-images.githubusercontent.com/50406316/200459978-816247cd-1cb2-45b6-9b62-d5b257a884c5.png)

## 問題のツールチップ（必須）

共和国の政体説明のツールチップ

## 問題の表現（必須）

```
選出〇〇が国を治める政府です
```

## 問題箇所の英文（任意）

```
This is a government where the country is ruled by an elected XXX.
```

## 希望する変更（必須）

```
選出された〇〇が国を治める政府です
```

## 変更の理由（必須）

変数構文に助動詞が抜けているので修正したい

## ゲームバージョン（必須）

1.0.5

## DLC有無（必須）

なし

## MOD有無（必須）

翻訳改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
提案通り変更してクローズします
