### ISSUE TITLE
「技術の普及」（concept_technology_spread_desc）の説明文

### ISSUE THREAD

**Issue by WoodlandsGitHub** [matanki-saito/vic3jpadvmod#394]
## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/29177147/200492521-50e72790-0c52-433b-afe5-f9fd9a382551.png)
## 問題のツールチップ（必須）

用語「技術の普及」をマウスオーバー

## 問題の表現（必須）
concept_technology_spread_desc
```
"各カテゴリ（$PRODUCTION_NO_CONCEPT$、$MILITARY$、$SOCIETY$）から、まだ獲得していない[concept_technology]は、それらを獲得している[Concept('concept_country','$concept_countries$')]からあなたへと常に普及してきます。$concept_technologies$の普及の進捗は、$concept_country$の[concept_literacy]に応じた基本値を中心に毎週ランダムに変動します。$concept_technology$を発明した$concept_country$がまだないのに、あなたに普及できない場合、あなたは$concept_technology_spread$によって初期の[Concept('concept_technology_era','$concept_technology_era_short$')] $concept_technologies$ を獲得する確率が、後期のものよりも高くなります。"
```

## 問題箇所の英文（任意）

```
One [concept_technology] that you have not yet acquired from each category ($PRODUCTION_NO_CONCEPT$, $MILITARY$, and $SOCIETY$) is always spreading to you from [Concept('concept_country','$concept_countries$')] that have acquired them.
The progress you get in spreading $concept_technologies$ is randomized each week around a base value depending on your $concept_country$'s [concept_literacy].
If no $concept_country$ has invented a certain $concept_technology$ yet it cannot spread to you,
so you are more likely to acquire early [Concept('concept_technology_era','$concept_technology_era_short$')] $concept_technologies$ from $concept_technology_spread$ than later ones.
```

## 希望する変更（必須）

```
（生産、軍事、社会の各カテゴリごとに）未取得の技術は、取得済みの国々から常に拡散し普及しています。
そういった技術の普及の度合いは、毎週、自国の識字率に応じた基準値付近を揺れ動きます。
もし、確固たる技術がどの国でも発見されていないのなら、自国に普及してきません。
この場合、技術の普及の影響を受けて、若い時代の技術が後の時代の技術と比べて一層獲得しやすくなります。
```

## 変更の理由（必須）

後半部分に誤訳に近い訳があるので
ついでに全体的に修正

## ゲームバージョン（必須）

1.0.5

## DLC有無（必須）

なし

## MOD有無（必須）

日本語改善MOD
Switch Languages

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
> 未取得の[concept_technology]は、（$PRODUCTION_NO_CONCEPT$、$MILITARY$、$SOCIETY$の各カテゴリごとに）から、取得済みの[Concept('concept_country','$concept_countries$')]から常に自国へと拡散し普及します。普及によって、毎週、$concept_country$の[concept_literacy]を元にしたランダムな値が、$concept_technologies$の進捗として得られます。ある$concept_technology$がどの$concept_country$でも発見されていない場合、自国への普及は起こりません。そのため、$concept_technology_spread$によって得られる$concept_technologies$は後の[Concept('concept_technology_era','$concept_technology_era_short$')]のものよりも、前の[Concept('concept_technology_era','$concept_technology_era_short$')]のもののほうが多くなります。

**Comment by clamm0363** [comment]
上記のとおり修正しました。

クローズします。
