### ISSUE TITLE
利子のツールチップのタイトル

### ISSUE THREAD

**Issue by kurutto115** [matanki-saito/vic3jpadvmod#395]
## スクリーンショット（必須）

![Victoria 3 2022_11_07 16_21_03](https://user-images.githubusercontent.com/117251782/200493689-6907496d-a661-4b0c-a4d0-548708345217.png)

## 問題のツールチップ（必須）

予算ウィンドウの利子のポップアップ

## 問題の表現（必須）

```
利益
```

## 問題箇所の英文（任意）

```
Interest
```

## 希望する変更（必須）

```
利子
```

## 変更の理由（必須）

修正漏れ

## ゲームバージョン（必須）

1.0.5

## DLC有無（必須）

なし

## MOD有無（必須）

本プロジェクトMODのみ

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
以前の修正時に修正もれしていた箇所でしたので、同様に「利子」と修正しました

クローズします
