### ISSUE TITLE
○○の復権（維新イベント・ジャーナル）

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#396]
## スクリーンショット（任意）

![20221108152548_1](https://user-images.githubusercontent.com/43299334/200496266-a12029dc-3d5e-4df9-8a0e-4bcfbacf3bb4.jpg)
![20221108155630_1](https://user-images.githubusercontent.com/43299334/200495991-16aed2ce-631c-4995-8bb0-932174cfacd5.jpg)
![20221108155650_1](https://user-images.githubusercontent.com/43299334/200496147-d4fca3e3-8cd4-4b3e-a848-47321fe68c80.jpg)
![20221108155659_1](https://user-images.githubusercontent.com/43299334/200496160-4c630686-3d21-44ba-ab77-8fc2c9bad9fc.jpg)

## 問題部分（タイトル・本文・選択肢）

```
（国家元首）の復権
```

## 問題のイベントタイトル（必須）

```
（国家元首）の復権
```

## 問題のイベント本文（任意・抜粋可）

```
なし
```

## 問題のイベント選択肢（任意）

```
なし
```

## 希望する変更（必須・修正部分のみ）

```
(国家元首)維新
```

## 変更の理由（必須）

Restorationの定訳
このジャーナルを満たすための条件ジャーナルはいずれも「維新：〇〇」となっており、維新が適当であろう

## プレイ国家

日本

## ゲームバージョン（必須）

1.0.5

## DLC有無（必須）

なし

## MOD有無（必須）

フォントMOD
日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
～維新で修正
