### ISSUE TITLE
キャラクターの経験・エキスパート特性

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#397]
## スクリーンショット（任意）
![20221108140907_1](https://user-images.githubusercontent.com/43299334/200498038-c6229603-8f6e-447e-8069-7111a8c4af65.jpg)
![20221108140847_1](https://user-images.githubusercontent.com/43299334/200498062-b58c8e8a-111a-4084-8cf5-d46637405ea5.jpg)

## 問題の用語（必須）

```
経験豊富な〇〇、エキスパート〇〇
〇〇エキスパート　など
```

## 英語版の表現（任意）

```
Experienced 〇〇、Expert 〇〇
〇〇 Expert
```

## 希望する変更（必須）

```
〇〇の専門家、〇〇の達人
〇〇の名手
```

## 変更の理由（必須）

長すぎて改行が挟まるなど、読みにくため。（SSはフォントMOD導入環境だが、バニラ環境でも改行を確認している）
なお、同じエキスパートという単語であるため分かりにくいが、上段のものは効果として
Experienced 〇〇＜Expert 〇〇　という上位・下位互換の関係にあるため、HoI4に倣って分かりやすい意訳にしている。

## ゲームバージョン（必須）

1.0.5

## DLC有無（必須）

無し

## MOD有無（必須）

フォントMOD
日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
議論の結果に基づき以下の通り修正しました。

| 原文 | 変更前 | 変更後 | 
| ---- | ---- | ---- |
| Supply Requisitions Expert | 補給物資調達エキスパート | 兵站の達人 |
| Woodland Combat Expert | 森林戦闘エキスパート | 森林戦闘の名手 |
| Open Terrain Commander | 開放地形司令官 | 平地戦闘の名手 |
| Mountain Combat Expert | 山岳戦闘エキスパート | 山岳戦闘の名手 |
| Artillery Commander | 砲撃司令官 | 砲術指揮官 |
| Experienced Artillery Commander | 経験豊富な砲撃司令官 | 砲術専門家 |
| Expert Artillery Commander | エキスパート砲撃司令官 | 砲術の達人 |
| Offensive Planner | 攻撃的計画立案者 | 攻撃戦略家 |
| Experienced Offensive Planner | 経験豊富な攻撃的計画立案者 | 攻撃戦略専門家 |
| Expert Offensive Planner | エキスパート攻撃的計画立案者 | 攻撃戦略の達人 |
| Experienced Defensive Strategist | 経験豊富な防衛戦略家 | 防衛戦略専門家 |
| Expert Defensive Strategist | エキスパート防衛戦略家 | 防衛戦略の達人 |
| Naval Commander | 海軍司令官 | 艦隊指揮官 |
| Experienced Naval Commander | 経験豊富な海軍司令官 | 艦隊指揮専門家 |
| Expert Naval Commander | エキスパート海軍司令官 | 艦隊指揮の達人 |
| Convoy Raider | 輸送船団レイダー | 船団襲撃者 |
| Experienced Convoy Raider | 経験豊富な輸送船団レイダー | 船団襲撃専門家 |
| Expert Convoy Raider | エキスパート輸送船団レイダー | 船団襲撃の達人 |
| Experienced Colonial Administrator | 経験豊富な植民地統治者 | 植民地統治専門家 |
| Expert Convoy Raider | エキスパート植民地統治者 | 植民地統治の達人 |
| Political Operator | 辣腕政治家 | 政略家 |
| Experienced Political Operator | 経験豊富な辣腕政治家 | 政略専門家 |
| Expert Political Operator | エキスパート辣腕政治家 | 政略の達人 |
