### ISSUE TITLE
フランス人の姓名

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#398]
## 問題の固有名詞と希望する変更（必須）

アシレ：アシル
アドルフェ：アドルフ
アドリエン：アドリアン
アイマブル：エマブル
アマデー：アメデ
アントーヌ：アントワーヌ
アルマンド：アルマン
アウグステ：オーギュスト
アウグスティン：オーギュスタン
アルチーデ：アルシド
アタナーセ：アタナス
カミール：カミーユ
セレスティン：セレスタン
エドゥアルド：エドゥアール
エティエンネ：エティエンヌ
エヴラード：エヴラール
エルゼアール：エルゼアル
フェルナンド：フェルナン
フェリシエン：フェリシアン
ファーミン：フィルマン
ゲオルゲス：ジョルジュ
ジローム：ギヨーム
グスタフ：ギュスターヴ
ゲルマイン：ジェルマン
ヘンリー：アンリ
ヒッポリテ：イッポリト
ヒューバート：ユベール
ハーキュール：エルキュール
ジャッキュー：ジャック
ジーン：ジャン
ジュリエン：ジュリアン
ジャスト：ジュスト
ラザレ：ラザール
ルシエン：リュシアン
ローレント：ローラン
マシュー：マテュー
マーセル：マルセル
マクシミリエン：マクシミリアン
ニコラス：ニコラ
オリビエ：オリヴィエ
プロスパー：プロスペ
ローランド：ローラン
ロドルフェ：ロドルフ
レネ：ルネ
レミー：レミ
セバスティエン：セバスティアン
ティボート：ティボー

アデレード：アデライード
アデーレ：アデル
アンゲリーク：アンジェリーク
アテナイ：アテナイス
オーギュスタイン：オーギュスティーヌ
デルフィン：デルフィーヌ
エレオノーラ：エレオノール
ユーゲネ：ウジェニー
ユーラリー：ウラリー
フランソス：フランソワーズ
ガブリエレ：ガブリエル
ヘンリエッタ：アンリエット
ホルテンセ：オルタンス
ジェーン：ジャンヌ
ジュリエッテ：ジュリエット
ジャスティン：ジュスティーヌ
レオティン：レオティーヌ
レオポルダイン：レオポルディーヌ
ルイス・ヴィクトリン：ルイーズ＝ヴィクトリーヌ
マーセル：マルセル
マーガライト：マルグリット
マリー・アンネ：マリー＝アンヌ
マリー・フェリックス：マリー＝フェリクス
メラニエ：メラニー
セラフィン：セラフィーヌ
シビレ：シビーユ
スザンナ：スザンヌ
テレーセ：テレーズ
ヴィクトリン：ヴィクトリーヌ

ドーモント：ドーモン
ベルゲレット：ベルジュレ
デ・ビューハーネス：ド・ボアルネ
デ・ビュシエール：ド・ビュシエール
デ・シャステラックス：ド・シャステリュー
デ・ショードロン・デ・カーセル：ド・ショドロン・ド・クルセル
デカゼス：ドゥカズ
デ・ダーフォート：ド・デュルフォール
デスリンク：デスラン
フェシュ：フェッシュ
グロス：グロ
デ・グラモント：ド・グラモン
デ・ゲーリン：ド・ゲラン
デ・ギュードン：ド・ゲイドン
デ・ゴーヨン：ド・ゴヨン
ケラーマン：ケレルマン
デ・ラマルティン：ド・ラマルティーヌ
デ・ラ・ルザーン：ド・ラ・リュゼルヌ
デ・レウシュテンベルグ：ド・ルシタンベール
マーボット：マルボ
ド・マクマホン：ド・マクマオン
ド・モントモレンシー・ラヴァル：ド・モンモランシー＝ラヴァル
ウーディノー：ウディノ
デ・ポールテール：ド・プルタレス
デ・ロッシェボーエ：ド・ロシュブエ
ド・ロハン・シャボー：ド・ロアン＝シャボ
ド・ソゥ：ド・ソ

アントーヌ：アントワーヌ
アルチナルド：アルシナール
アラヴォイン：アラヴォワーヌ
バザーヌ：バゼーヌ
ビロット：ビヨ
ブーランジャー：ブーランジェ
ボルバキ：ブルバキ
ブーエ・ウィヨメ：ブーエ＝ウィヨメ
ビューゲンダー：ボージャンドル
ブロンシャード：ブロンシャール
ボーデット：ボデ
ボディニエリ：ボディニエ
ビール：ビエール
カイラード：カイヤール
カンロベルト：カンロベール
クーザン・モントバン：クザン＝モントーバン
デ・カステラーネ：ド・カステラーヌ
コンベス：コンブ
コルネット：コルネ
コーラス：コラ
ショーベー：ショーヴェ
カレーレ：カレル
コンベレス：コンベル
ショーデ：ショド
クルション：クリュション
カーヴィリ：ショヴリー
ショード：ショデ
コレット：コレ
コットレル：コトレル
コードリエ：コドルリエ
コーセレス：クルセル
デュプラ：デプレ
ドゥベイル：デュバイユ
デュボイス：デュボワ
デュシェーネ：デュシェーヌ
デュプティ・トゥアール：デュプティ＝トゥアール
デスボルデス：デボルド
ドルティナク：ドルティニャック
ダルガシエス：ダルガシー
ダウメイン：ドマン
デクープ：ドコー
ダルシェ：ダルシュ
デロッフル：ドロフル
デニゾット：ドニゾ
ドゥフォール：デュフール
デヴィリー：ドヴィリ
デルス：デール
デルペシ：デルペシュ
ダイム：デーム
エクセルマンス：エグゼルマン
フォッホ：フォッシュ
フォリー：フォレ
フランシェ・デスペレー：フランシェ・デスペレ
フレイシネット：フレシネ
ファイドヘルベ：フェデルブ
フィギュ：フィグ
ガリエーニ：ガリエニ
ガーランド：グロー
ギュラマット：ギヨーマ
ゲイン：ガン
ジョルジェット：ジョルジェ
ジュラルメ：ギヤルム
ジェニン：ジェナン
ジロード：ジェロー
ゴディビエ：ゴディヴィエ
ゲルマイン：ジェルメーヌ
ガルデント：ガルダン
ハメリン：アムラン
ハリスプ：アリスプ
ホッホ：オッシュ
フムバート：ユンベール
ハビエレ：アビエル
ヘルベリン：エルブラン
ハルケット：アルク
ジャメイス：ジャメ
ヨーレス：ジョレス
ジョフレ：ジョフル
ルブエフ：ルブーフ
リアウティー：リョテ
ルグッテ：レグト
ラレメント：ラルマン
ラフォーケイド：ラフルカド
ル・バルス：ル・バール
レーマン：ルマン
ロリロン：ロリヨン
ラングレード：ラングラード
ラゲイグナー：ラガニェ
リロイ：ルロワ
ラピーゼ：ラピズ
マーモンテル：マルモンテル
ムラー：ミュラ
ド・モンティニャック：ド・モンテニャック
メイゼル：マズル
マイトロン：メトロン
メナジェル：メナジェ
メイリー：メリ
マトナート：マトナ
ネイ・デルヒンゲン：ネイ・デルシャンジャン
ニヴェレ：ニヴェル
ネボワ：ネブー
ナド：ナドー
ペタイン：ペタン
ペリッシア：ペリシエ
パウトラット：ポトラ
パイアン：パヤン
ポールミア：ポルミエ
ピエトロス：ピエトロワ
クエノン：クノン
リンジヴァル：ランジュヴァル
ラボット：ラボ
リヴィエ：リヴィエール
ローシェ：ロシュ
リカー：リコー
ロックベール：ロクベール
ロッティー：ロティー
ロヤネス：ロワイヤンヌ
トレブティエン：トレビュティアン
トラセリア：トルセリエ
テュバシェ：テュヴァシュ
ヴァイラント：ヴェラン
ヴェントレスキュー：ヴァントレスク
ヴィレッテ：ヴィレット
ヴァイディス：ヴェディ
ヴィレッテ：ヴィレット
ウィナント：ウィナン

クレメンタイン：クレマンティーヌ
ヘレネ：エレーヌ

オルレアン：ドルレアン

## 変更の理由（必須）

日本語では一般的ではない表記であるため。

## ゲームバージョン（必須）

1.0.5

## DLC有無（必須）

なし

## MOD有無（必須）

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
