### ISSUE TITLE
関心排除フィード

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#399]
※「｀｀｀」は消さないでください

## スクリーンショット（必須）

![20221108181730_1](https://user-images.githubusercontent.com/42710893/200542811-ea37b59b-cb52-412f-842f-8cb95aea9079.jpg)

## 問題のあるインターフェイス（必須）

関心排除時のフィード

## 問題のテキスト（必須）

```
notification_interest_deactivated_third_party_name:0 "[SCOPE.sCountry('actor').GetAdjective] [SCOPE.GetRootScope.GetInterest.GetStrategicRegion.GetName] [concept_interest]が排除されました。"

英語：
"[SCOPE.sCountry('actor').GetAdjective] [SCOPE.GetRootScope.GetInterest.GetStrategicRegion.GetName] [concept_interest] removed."
```

## 希望する変更（必須）

```
"[SCOPE.sCountry('actor').GetAdjective]が[SCOPE.GetRootScope.GetInterest.GetStrategicRegion.GetName]に対する[concept_interest]を撤回"　等
仮訳で撤回にしていますが、他に良い訳があればお任せします。
自国が関心を排除した場合（notification_interest_deactivated_name:1）も同様に修正が必要（こちらは現訳で「解除」になっている）
```

## 変更の理由（必須）

日本語として自然なものにするため
issue#310（関心の表明）と対になるフィードです

## ゲームバージョン（必須）

1.0.5

## DLCの有無（必須）

なし

## MODの有無（必須）

日本語改善MOD
フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
「[国名]の[地域]に対する[関心]が消失」と修正しました

クローズします。
