### ISSUE TITLE
【修正提案】外交画面タブ

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#40]
## スクリーンショット（必須）

![20221026211758_1](https://user-images.githubusercontent.com/42710893/198051659-5546fbea-f6ef-440f-9ddf-983ec156aee3.jpg)

## 問題のあるインターフェイス（必須）

外交画面タブ

## 問題のテキスト（必須）

インタラクション

## 希望する変更（必須）

関係行動

## 変更の理由（必須）

Interaction
カタカナではわかりにくいと思います。

## ゲームバージョン（必須）

1.0.3

## DLCの有無（必須）

なし

## MODの有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1034834981140307978
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by clamm0363** [comment]
議論の結果、「インタラクション」を「行動」と置き換える形で修正しました。

クローズします。
