### ISSUE TITLE
難着陸ペナルティ（Landing Penalty）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#401]
## スクリーンショット（任意）
![20221108223911_1](https://user-images.githubusercontent.com/42687608/200580383-b10e0f8a-d8d7-40d4-b4fc-24c59cd7dd7c.jpg)

## 問題の用語（必須）
```
難着陸ペナルティ
```

## 英語版の表現（任意）
```
Landing Penalty
```

## 希望する変更（必須）
```
上陸ペナルティ
```

## 変更の理由（必須）
上陸用舟艇の特性であり、明らかな誤訳であるため。

## ゲームバージョン（必須）
1.0.4

## DLC有無（必須）
- Victoria II Remastered Soundtrack
- American Buildings Pack

## MOD有無（必須）
- 自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
「上陸ペナルティ」に確定し、修正が完了しました。
