### ISSUE TITLE
ニジェール川遠征イベントのタイトル

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#402]
※「｀｀｀」は消さないでください

## スクリーンショット（任意）

![20221108220546_1](https://user-images.githubusercontent.com/42710893/200583551-34324143-6734-452d-8205-7f1913332e1e.jpg)

## 問題部分（タイトル・本文・選択肢）

```
タイトル
```

## 問題のイベントタイトル（必須）

```
expedition_events.4.t:0 "遠征出発。"
```

## 問題のイベント本文（任意・抜粋可）

```

```

## 問題のイベント選択肢（任意）

```

```

## 希望する変更（必須・修正部分のみ）

```
遠征出発
```

## 変更の理由（必須）

イベントタイトルなので最後の句点は不要
アメリカ西部への遠征イベントであるexpedition_events.203.t:0も同じようになっているので、一緒に修正したい

## プレイ国家

ベルギー

## ゲームバージョン（必須）

1.0.5

## DLC有無（必須）

なし

## MOD有無（必須）

日本語改善MOD
フォントMOD

**Comment by saarland68** [comment]
修正しました
「遠征出発。」→「遠征出発」
クローズします
