### ISSUE TITLE
Subsidize 国有化

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#403]
※「｀｀｀」は消さないでください

## スクリーンショット（任意）

![subsidize_ja](https://user-images.githubusercontent.com/50406316/200595920-ffe2fb06-988c-41fb-843a-503e0dfa78ba.png)
![subsidize_en](https://user-images.githubusercontent.com/50406316/200595939-657608a4-9309-466b-b3f7-1ea0af7ab369.png)

## 問題の用語（必須）

```
国有化
```

## 英語版の表現（任意）

```
subsidize, subsidizingなど
```

## 希望する変更（必須）

```
助成
```

## 変更の理由（必須）

上記の法律画面以外にも、複数箇所で同様の誤訳あり。
建造物の赤字の補填をすることで、建造物画面のほうではちゃんと「助成」となっているが、なぜかこの画像のように「国有化」となっている箇所が複数ある。
誤訳なうえに、共産政体でできるPMの国有化とも紛らわしいので「助成」の訳に統一させたい。

## ゲームバージョン（必須）

1.0.5

## DLC有無（必須）

無し

## MOD有無（必須）

翻訳改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
修正を行いました。なおindustrial subsidiesは自然な日本語になるよう、国有化産業→産業助成と語順を入れ替えています。
