### ISSUE TITLE
人種差別 Racial Segregation

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#406]
※「｀｀｀」は消さないでください

## スクリーンショット（任意）
![Racial_Segregation](https://user-images.githubusercontent.com/50406316/200618655-a9e2afd0-e8a3-49ac-89ce-b208ae694649.png)

## 問題の用語（必須）

```
人種差別
```

## 英語版の表現（任意）

```
Racial Segregation
```

## 希望する変更（必須）

```
人種隔離
```

## 変更の理由（必須）
Segregationは差別と訳すのでも誤りではないが、より正確には人種隔離のこと。
アメリカの黒人隔離や南アフリカのアパルトヘイトなどのようなものを指している。
また、ゲーム用語としてDiscriminationが差別の訳語を与えられているので、そちらと訳し分けたいのもある。

## ゲームバージョン（必須）

1.0.5

## DLC有無（必須）

無し

## MOD有無（必須）

翻訳改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
提案通りクローズしました
