### ISSUE TITLE
[国名]あるいはその従属国に領有されている

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#407]
## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/37979626/200618671-a0976885-ac5a-48b6-aa4b-450480b16ea9.png)

## 問題のツールチップ（必須）
条件文

## 問題の表現（必須）
```
ビルマが東インド会社あるいはその従属国に領有されている
[StateRegion.GetName]が[Country.GetNameNoFlag]あるいはその従属国に領有されている
```

## 問題箇所の英文（任意）
TRIGGER_COUNTRY_OR_SUBJECT_OWNS_ENTIRE_STATE_REGION_FIRST
```
[StateRegion.GetName] is owned by [Country.GetNameNoFlag] or its subjects
```

## 希望する変更（必須）
```
東インド会社（従属国を含む）がビルマを領有中
[Country.GetNameNoFlag]（従属国を含む）が[StateRegion.GetName]を領有中
```
以下関連エントリも修正対象とする：
TRIGGER_COUNTRY_OR_SUBJECT_OWNS_ENTIRE_STATE_REGION
```
[StateRegion.GetName]がその国（従属国を含む）に領有されている
```
TRIGGER_COUNTRY_OR_SUBJECT_OWNS_ENTIRE_STATE_REGION_NOT
```
[StateRegion.GetName]がその国（従属国を含む）に領有されて#bold いない#!
```
TRIGGER_COUNTRY_OR_SUBJECT_OWNS_ENTIRE_STATE_REGION_FIRST_NOT
```
[Country.GetNameNoFlag]（従属国を含む）が[StateRegion.GetName]を領有して#bold いない#!
```

## 変更の理由（必須）
長い

## ゲームバージョン（必須）
1.0.4

## DLC有無（必須）
なし

## MOD有無（必須）
なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通り修正しました。
