### ISSUE TITLE
アフリカでの争奪戦（Scramble for Africa、ジャーナル）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#408]
## スクリーンショット（任意）
![20221109102439_1](https://user-images.githubusercontent.com/42687608/200713975-2d09d5e8-a8b4-4f31-8744-115b2abb7dbd.jpg)

## 問題部分（タイトル・本文・選択肢）
```
ジャーナルのタイトル
```

## 問題のイベントタイトル（必須）
```
アフリカでの争奪戦
```

## 問題のイベント本文（任意・抜粋可）
```
```

## 問題のイベント選択肢（任意）
```
```

## 希望する変更（必須・修正部分のみ）
```
アフリカ分割
```

## 変更の理由（必須）
Scramble for Africaは「アフリカ分割」が定訳のため。

## プレイ国家
アメリカ合衆国

## ゲームバージョン（必須）
1.0.4

## DLC有無（必須）
- Victoria II Remastered Soundtrack
- American Buildings Pack

## MOD有無（必須）
- 自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
「アフリカ分割」に確定し、修正を完了しました。
