### ISSUE TITLE
大展覧会（Grand Exhibition、ジャーナル）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#409]
## スクリーンショット（任意）
![20221109131701_1](https://user-images.githubusercontent.com/42687608/200737421-f1f585c1-9236-4218-8a5e-a5168f3519e5.jpg)

## 問題部分（タイトル・本文・選択肢）
```
ジャーナルのタイトル
```

## 問題のイベントタイトル（必須）
```
大展覧会を開催する
```

## 問題のイベント本文（任意・抜粋可）
```

```

## 問題のイベント選択肢（任意）
```

```

## 希望する変更（必須・修正部分のみ）
```
万国博覧会の開催
```

## 変更の理由（必須）
原文はGrand Exhibition。1851年に開催されたロンドン万国博覧会（Great Exhibition）を指していると思われる。
[Wikipedia英語版の解説](https://en.wikipedia.org/wiki/Great_Exhibition)
[Wikipedia日本語版の解説](https://ja.wikipedia.org/wiki/%E3%83%AD%E3%83%B3%E3%83%89%E3%83%B3%E4%B8%87%E5%9B%BD%E5%8D%9A%E8%A6%A7%E4%BC%9A_(1851%E5%B9%B4))

## プレイ国家
アメリカ合衆国

## ゲームバージョン（必須）
1.0.4

## DLC有無（必須）
- Victoria II Remastered Soundtrack
- American Buildings Pack

## MOD有無（必須）
- 自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
「万国博覧会」に確定し、修正を完了しました。
