### ISSUE TITLE
地名（西欧を中心に複数）

### ISSUE THREAD

**Issue by nakka8** [matanki-saito/vic3jpadvmod#41]
## 問題の固有名詞と希望する変更（必須）
【エリア名】
バーガンディー：ブルゴーニュ
リムジン：リムーザン
オーベルジュ：オーベルニュ
ローン：ローヌ
ラインスター：レンスター
カタロニア：カタルーニャ

【都市名】
トゥリン：トリノ
クラコフ：クラクフ
バーゴス：ブルゴス
ジノア：ジェノヴァ
サン・テティエンヌ：サンテティエンヌ
モントーバン：モンタルバン
ナンテス：ナント
ロウエン：ルーアン
リオン：リヨン
ナムール：ナミュール

## 変更の理由（必須）

日本で一般的に聞く表記（一部違和感を感じてGoogleマップを参考に）

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

Gland Edition付属のもの

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1034838751807021126
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by ChiefIdeologue** [comment]
修正が完了したので、クローズしました。
