### ISSUE TITLE
◯◯号（タイタニック号イベント、◯◯は可変）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#410]
## スクリーンショット（任意）
![20221109140535_1](https://user-images.githubusercontent.com/42687608/200743583-affd537d-0e39-46db-9897-b42b209a11b0.jpg)

## 問題部分（タイトル・本文・選択肢）
```
タイトル
```

## 問題のイベントタイトル（必須）
```
◯◯号（◯◯は可変）
```

## 問題のイベント本文（任意・抜粋可）
```
```

## 問題のイベント選択肢（任意）
```
```

## 希望する変更（必須・修正部分のみ）
```
船の名前を翻訳せずカタカナのままにする
```

## 変更の理由（必須）
このイベントでは巨大豪華客船の名前がランダムで決まる。
選択肢は次の通りで、content_104_l_english.jsonで定義されている。
公式訳ではこれらを一部「巨大」などの日本語にしているため、不自然かつ間抜けなタイトルになっている。
```
Titanic
Olympic
Gigantic
Colossal
Herculean
Gargantuan
```

## プレイ国家

ー

## ゲームバージョン（必須）
1.0.4

## DLC有無（必須）
- Victoria II Remastered Soundtrack
- American Buildings Pack

## MOD有無（必須）
- 自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
上記エントリをカタカナ表記とすることに決定し、修正を完了しました。
