### ISSUE TITLE
無線（Radios、商品名）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#411]
## スクリーンショット（任意）

![20221109143957_1](https://user-images.githubusercontent.com/42687608/200748178-b93bb08d-bc27-4a91-a60a-0cb317ac2617.jpg)

## 問題の用語（必須）

```
無線
```

## 英語版の表現（任意）

```
Radios
```

## 希望する変更（必須）

```
無線機
```

## 変更の理由（必須）
無線を生産したり売買するのは日本語として不自然なため。
同様の例に「サービス」や「輸送」があるが、Radiosは「無線機」とすることで回避可能。
技術名の「無線」は別エントリで定義されているため共存可能。
一部テキストで「ラジオ」の意味のradioが「無線」と翻訳されていたため、あわせて修正した。

## ゲームバージョン（必須）
1.0.5

## DLC有無（必須）
- Victoria II Remastered Soundtrack
- American Buildings Pack

## MOD有無（必須）
- 自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
「無線機」に確定し、修正を完了しました。
なお、一部テキストで「ラジオ」の意味のradioが「無線」と翻訳されていたため、あわせて修正しました。
