### ISSUE TITLE
フォルモサ→台湾(ステート名)

### ISSUE THREAD

**Issue by nagi0330** [matanki-saito/vic3jpadvmod#412]
## 問題の固有名詞と希望する変更（必須）
※改行して書いてください。「：」で分離してください

フォルモサ(ステート名)：台湾
トルクメン(ステート名)：トルクメニスタン
キルギス(ステート名)：キルギスタン
カラサコフ：コルサコフ
オクハ：オハ
ノジリキ：ノグリキ

## 変更の理由（必須）
フォルモサ
清の統治下であれば台湾とするのが正しいかと
トルクメン・キルギス
近隣のステートは○○スタンになっているので統一したい
カラサコフ・オクハ・ノジリキ
一般的な読み方

## ゲームバージョン（必須）

1.0.4

## DLC有無（必須）

なし

## MOD有無（必須）
なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
議論の結果、以下の様に修正しました。

フォルモサ　→　台湾
トルクメン（ステート名）　→　（修正なし）
キルギス（ステート名）　→　（修正なし）
カラサコフ　→　コルサコフ
オクハ　→　オハ（以前に修正済み）
ノジリキ　→　ノグリキ

クローズします。
