### ISSUE TITLE
ミズーリの妥協

### ISSUE THREAD

**Issue by nagi0330** [matanki-saito/vic3jpadvmod#413]
※「｀｀｀」は消さないでください

## スクリーンショット（必須）
![20221108132105_1](https://user-images.githubusercontent.com/6514922/200752421-1ed5bc5d-741d-4928-acd7-697d102c91f5.jpg)

## 問題のツールチップ（必須）

アメリカの地主(南部プランテーション農家)のバフ

## 問題の表現（必須）

```
ミズーリの妥協
```

## 問題箇所の英文（任意）

```
Missouri Compromise
```

## 希望する変更（必須）

```
ミズーリ妥協
```

## 変更の理由（必須）
一般的な表現への変更

## ゲームバージョン（必須）

1.0.4

## DLC有無（必須）

なし

## MOD有無（必須）

※できるだけMODのない状態で問題を確認してください。

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
ありがとうございます、ご指摘の通り修正しました。これにてクローズします。
