### ISSUE TITLE
【修正提案】遺産奴隷制

### ISSUE THREAD

**Issue by saarland68** [matanki-saito/vic3jpadvmod#414]
※「｀｀｀」は消さないでください

## スクリーンショット（任意）
![image](https://user-images.githubusercontent.com/70930137/200760387-fa4a0730-27fe-4b94-a9c1-234b9eb9335f.png)

##問題の用語（必須）
```
遺産奴隷制
```

## 英語版の表現（任意）

```
Legacy Slavery
```

## 希望する変更（必須）

```
相続奴隷制
```

## 変更の理由（必須）
日本語、英語wiki等がないのではっきりしませんが少なくとも遺産の意味ではないと思われます

## ゲームバージョン（必須）

1.0.1

## DLC有無（必須）

無し

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by nagi0330** [comment]
新規に奴隷制度を拡大しないよ、という意味で遺産的に残された制度という意味では？

**Comment by matanki-saito** [comment]
これは過去の遺物という意味でのLegacyで、訳すとしたらたぶん「残された奴隷制」とか「奴隷制の残滓」とかになるし、負の遺産という意味でこのまま遺産奴隷制でもいいかもしれません
