### ISSUE TITLE
フィードタイトル全般修正

### ISSUE THREAD

**Issue by clamm0363** [matanki-saito/vic3jpadvmod#415]
※「｀｀｀」は消さないでください

## スクリーンショット（必須）

省略

## 問題のあるインターフェイス（必須）

フィードタイトル

## 問題のテキスト（必須）

```
フィードタイトル全般
```

## 希望する変更（必須）

```
体言止めにする
```

## 変更の理由（必須）

表示スペースが狭く、簡潔に表記したほうが見やすいため

## ゲームバージョン（必須）

1.0.5

## DLCの有無（必須）

ー

## MODの有無（必須）

ー

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
変更箇所多数につき列挙は割愛します。

クローズします。
