### ISSUE TITLE
イベント：印象的な航海

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#416]
※「｀｀｀」は消さないでください

## スクリーンショット（任意）

![20221109204349_1](https://user-images.githubusercontent.com/42710893/200829888-4cfb1cb0-4710-4fe8-982b-79ecbee42cb9.jpg)

## 問題部分（タイトル・本文・選択肢）

```
本文
```

## 問題のイベントタイトル（必須）

```
印象的な航海
```

## 問題のイベント本文（任意・抜粋可）

```
titanic.3.d2:0 "…すぐに処女航海の大成功が明らかになりしました。…"
```

## 問題のイベント選択肢（任意）

```

```

## 希望する変更（必須・修正部分のみ）

```
titanic.3.d2:0 "…すぐに処女航海の大成功が明らかになりました。…"
titanic.3.d:0にも同様のtypoがあり修正が必要
```

## 変更の理由（必須）

typo

## プレイ国家

ベルギー

## ゲームバージョン（必須）

1.0.5

## DLC有無（必須）

なし

## MOD有無（必須）

日本語改善MOD
フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
ご指摘の通り、typoを修正
