### ISSUE TITLE
潜入者　→　突撃隊

### ISSUE THREAD

**Issue by swokajima** [matanki-saito/vic3jpadvmod#417]
※「｀｀｀」は消さないでください

## スクリーンショット（任意）
※画像はドラッグ＆ドロップで貼り付けられます。

なし

## 問題の用語（必須）

```
潜入者
```

## 英語版の表現（任意）

```
Infiltrators
```

## 希望する変更（必須）

```
突撃隊
```

## 変更の理由（必須）

第一次世界大戦で浸透戦術というものがありました。それを実行する舞台は突撃隊と呼ばれていたので。

## ゲームバージョン（必須）
1.0.5

## DLC有無（必須）

あり

## MOD有無（必須）

日本語改善MOD
GUI改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
議論の結果、「工作部隊」と修正することに決まりました

クローズします。
