### ISSUE TITLE
宣言された関心

### ISSUE THREAD

**Issue by clamm0363** [matanki-saito/vic3jpadvmod#419]
※「｀｀｀」は消さないでください

## スクリーンショット（任意）
![image](https://user-images.githubusercontent.com/29382778/200967588-b691197c-c629-4162-96a4-d996eae83ff6.png)

## 問題の用語（必須）

```
宣言された関心、関心の宣言
```

## 英語版の表現（任意）

```
Declared Interest, Declare Interests
```

## 希望する変更（必須）

```
関心表明、関心の表明
```

## 変更の理由（必須）

より自然な用語に

## ゲームバージョン（必須）

1.0.5

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
上記のとおり修正しました。

クローズします。
