### ISSUE TITLE
【修正提案】施設画面のツールチップ

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#42]
## スクリーンショット（必須）
![20221026233351_1](https://user-images.githubusercontent.com/42710893/198069209-f9589867-403f-49da-b7b8-a588dfc5517d.jpg)

## 問題のツールチップ（必須）

施設画面の助成ツールチップ

## 問題の表現（必須）

この施設は助成中されていません

## 希望する変更（必須）

この施設は助成されていません

## 変更の理由（必須）

日本語として不自然なため

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1034851775569723454
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by clamm0363** [comment]
「この施設は助成を受けていません」と表示されるよう修正しました。

クローズします。
