### ISSUE TITLE
どのブレーメンにも支配力を行使していない

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#420]
## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/37979626/201037300-fe3a32fa-1988-4fb1-b086-9e577a5e06da.png)

## 問題のツールチップ（必須）
文化ウィンドウの国家形成画面、分割州をマウスオーバー

## 問題の表現（必須）
FORM_NATION_STATE_NO_CONTROL_REASON_GENERIC
```
@red_cross! [State.GetName]: [Country.GetName]は、どの[State.GetOwner.GetName]にも支配力を行使していません
```

## 問題箇所の英文（任意）
```
@red_cross! [State.GetName]: [Country.GetName] does not exert any control over [State.GetOwner.GetName]
```

## 希望する変更（必須）
```
@red_cross! [State.GetName]: [Country.GetName]は[State.GetOwner.GetName]に対して主導権を一切発揮していません
```

## 変更の理由（必須）
誤訳

## ゲームバージョン（必須）
1.0.4

## DLC有無（必須）
なし

## MOD有無（必須）
なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
「@red_cross! [State.GetName]: [Country.GetName]は[State.GetOwner.GetName]に対して一切の支配権を及ぼしていません」

上記のように修正しました。

クローズします。
