### ISSUE TITLE
「経済的健康」

### ISSUE THREAD

**Issue by BLACKTIGER-NB** [matanki-saito/vic3jpadvmod#423]
※「｀｀｀」は消さないでください

## スクリーンショット（任意）
![経済的健康](https://user-images.githubusercontent.com/75819188/201080182-02defd33-ba93-4989-8e99-a68d23ca464c.jpg)

## 問題の用語（必須）

```
localization\japanese\concepts_l_japanese.yml
 concept_economy_health:0 "経済的健康"
 concept_economy_health_healthy:0 "健全な経済"
 concept_economy_health_healthy_short:0 "健康"
 concept_economy_health_unhealthy:0 "不健全な経済"
 concept_economy_health_unhealthy_short:0 "不健康"
```

## 英語版の表現（任意）

```
```

## 希望する変更（必須）

```
 concept_economy_health:0 "経済的健全"
 concept_economy_health_healthy:0 "健全な経済"
 concept_economy_health_healthy_short:0 "健全"
 concept_economy_health_unhealthy:0 "不健全な経済"
 concept_economy_health_unhealthy_short:0 "不健全"
```

## 変更の理由（必須）

ツールチップの「不健全」に合ってないから。

## ゲームバージョン（必須）

1.0.5

## DLC有無（必須）
American Building Pack	
Expansion Pass
Victoria 2 Remastered Soundtracks

## MOD有無（必須）
JapaneseLanguageAdvancedMod
地图乱码修复
Construction Queue with States
音楽追加MOD複数

**Comment by matanki-saito** [comment]
検討中です

**Comment by matanki-saito** [comment]
修正が完了したためClose致します
