### ISSUE TITLE
「不健全な経済」の説明文

### ISSUE THREAD

**Issue by BLACKTIGER-NB** [matanki-saito/vic3jpadvmod#424]
## スクリーンショット（必須）
![不健全な経済](https://user-images.githubusercontent.com/75819188/201081354-4fe3761d-0d60-4adb-8992-42a11a511c27.jpg)

## 問題のツールチップ（必須）

不健全な経済

## 問題の表現（必須）

```
\localization\japanese\alerts_l_japanese.yml
高価な商品の価格を上げる
```

## 問題箇所の英文（任意）

```
 alert_unhealthy_economy_alert_hint:0 "You can improve your financial situation by increasing your income (which can be done by for instance increasing (or adding new) Taxes) or decreasing your expenses (which can be done by for instance reducing Government Wages or improving the prices for expensive Goods used in Government Buildings)."
```

## 希望する変更（必須）

```
高価な商品の価格を改善する
```

## 変更の理由（必須）

・improvingだから。
・「使われている高価な商品の価格を上げ」ても政府の収支は改善しないから。

## ゲームバージョン（必須）

1.0.5

## DLC有無（必須）
American Building Pack	
Expansion Pass
Victoria 2 Remastered Soundtracks

## MOD有無（必須）
JapaneseLanguageAdvancedMod
地图乱码修复
Construction Queue with States
音楽追加MOD複数

**Comment by matanki-saito** [comment]
検討中です

**Comment by matanki-saito** [comment]
修正が完了したためClose致します
