### ISSUE TITLE
禁輸開始フィードの説明文（issue#328での修正分）

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#425]
※「｀｀｀」は消さないでください

## スクリーンショット（必須）

![20221110194144_1](https://user-images.githubusercontent.com/42710893/201083655-e1b544c6-b0ab-43e8-9c5d-c4fb8d109eec.jpg)

## 問題のあるインターフェイス（必須）

禁輸開始フィード

## 問題のテキスト（必須）

```
[国A]が[禁輸]に対して[国B]を開始しました。
```

## 希望する変更（必須）

```
[国A]が[国B]に対して[禁輸]を開始しました。
```

## 変更の理由（必須）

issue#328で翻訳が修正された分ですが、[TARGET_COUNTRY.GetName]と[Concept('concept_embargo', '$concept_embargoing$')]の位置が逆になっていると思われます

## ゲームバージョン（必須）

1.0.5

## DLCの有無（必須）

なし

## MODの有無（必須）
日本語改善MOD
フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
翻訳の修正によるミスではなく、元から変数の位置が逆転していたことによる表示ミスです。
ご提案どおり修正しました。

クローズします。

**Comment by clamm0363** [comment]
失礼しました。前回のissueで提案されていた内容の部分の修正を怠っておりました。謹んでお詫び申し上げます。

**Comment by wakkunteitoku** [comment]
いえいえ、とんでもないです。
いつも翻訳作業ありがとうございます。
