### ISSUE TITLE
National Guard 国家警備

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#426]
※「｀｀｀」は消さないでください

## スクリーンショット（任意）
![national_guard](https://user-images.githubusercontent.com/50406316/201094584-65cf20e9-a5d3-42f8-bdfa-3305616fc572.png)

## 問題の用語（必須）

```
国家警備
```

## 英語版の表現（任意）

```
National Guard
```

## 希望する変更（必須）

```
国民衛兵
```

## 変更の理由（必須）

史実の元ネタがあって、フランス革命の際に創設されたNational Guard（国民衛兵）のことを指しているため、訳語も史実に準じたものにしたい。
1836年フランスの開始時の法もこれである。

[英wikipedia](https://en.wikipedia.org/wiki/National_Guard)
>The original National Guard was formed during the French Revolution

[コトバンク](https://kotobank.jp/word/%E5%9B%BD%E6%B0%91%E8%A1%9B%E5%85%B5-64218)
>「国民衛兵」

## ゲームバージョン（必須）

1.0.5

## DLC有無（必須）

無し

## MOD有無（必須）

翻訳改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
当初案通り改訳しました。
