### ISSUE TITLE
【誤訳】農業の国有化を許可

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#428]
## スクリーンショット（任意）
![image](https://user-images.githubusercontent.com/37979626/201108752-231e570c-5635-443d-b9f8-f8f8886b061f.png)

## 問題の用語（必須）
```
$bg_agriculture$の国有化を許可
```

## 英語版の表現（任意）
modifier_country_subsidies_bg_agriculture
```
Can Subsidize $bg_agriculture$
```
ほか関連エントリ13件も対象

## 希望する変更（必須）
```
$bg_agriculture$へ助成可能
```

## 変更の理由（必須）
誤訳

## ゲームバージョン（必須）
1.0.5

## DLC有無（必須）
無し

## MOD有無（必須）
なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
こちら #403 と重複しているので取り下げます
