### ISSUE TITLE
【修正提案】物流　Logistics

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#43]
## スクリーンショット（任意）
![image](https://user-images.githubusercontent.com/37979626/198070177-9b1cb7a9-65d9-4c0e-a877-5ef0747ace5b.png)

## 問題の固有名詞（必須）

物流

## 希望する変更（必須）

兵站

## 変更の理由（必須）

軍事技術で「物流」だと意味するものが非軍事にも及んでしまうため

## ゲームバージョン（必須）

1.0.1

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1034852404933443654
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by saarland68** [comment]
修正しました
「物流」→「兵站」に変更
