### ISSUE TITLE
経済システムの資金プール説明

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#430]
## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/37979626/201110311-76c71a57-9a7b-4fb9-a9de-75cff013edfd.png)

## 問題のあるインターフェイス（必須）
法律画面＞経済システム

## 問題のテキスト（必須）
LAW_ALLOWED_BUILDING_GROUPS_FROM_INVESTMENT_POOL
```
[concept_investment_pool]の資金を建設費用として使用可能です 
```

## 希望する変更（必須）
```
[concept_investment_pool]の資金を次の建設費用として使用可能です:
```

## 変更の理由（必須）
後ろに対象施設名が並ぶのだが、それを想定した訳になっていないため
なお、施設名を先に持ってくることができればいいが変数不明
![image](https://user-images.githubusercontent.com/37979626/201116705-ec9fd93c-5ff3-4f79-916d-c71b6068bd8d.png)

## ゲームバージョン（必須）
1.0.5

## DLCの有無（必須）
なし

## MODの有無（必須）
なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通り修正
