### ISSUE TITLE
【未訳】Effects

### ISSUE THREAD

**Issue by clamm0363** [matanki-saito/vic3jpadvmod#431]
※「｀｀｀」は消さないでください

## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/29382778/201222986-367c2dc5-fc6c-49ba-a40c-5259b5a7dcff.png)

## 問題のツールチップ（必須）

悪名ツールチップ

## 問題の表現（必須）

```
Effects
```

## 問題箇所の英文（任意）

```
Effects
```

## 希望する変更（必須）

```
効果
```

## 変更の理由（必須）

未訳

## ゲームバージョン（必須）

1.0.5

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
上記のとおり修正しました
