### ISSUE TITLE
【修正提案】イベント「アヘン戦争」文章全体の見直し

### ISSUE THREAD

**Issue by WoodlandsGitHub** [matanki-saito/vic3jpadvmod#432]
## スクリーンショット（任意）
![image](https://user-images.githubusercontent.com/29177147/200950110-3bfff2c9-1c8d-4f8a-b4ea-5dc4fe2df632.png)

## 問題部分（タイトル・本文・選択肢）

```
本文と選択肢
```

## 問題のイベントタイトル（必須）

```
アヘン戦争
```

## 問題のイベント本文（任意・抜粋可）

```
1.
清政府は大清におけるアヘン貿易を停止する意思表示をしました。イギリスはアヘンの主要輸出国であるため、これは大きな経済的関心事となっています。

2.
自由貿易と消費者の自由な選択妨げているのは誰なのか？と。

3.
需要があり、それゆえに私たちは提供しているだけなのだ。

4.
私たちが供給しなくとも、他の国が漢のアヘン常用者にモノを供給し、富を蓄えるだけだろう。

5.すべての人がアヘンを奪われなければならないのだろうか？

6.そして、すべてのイギリスの家族は、アヘンが私たちの国にもたらす富を奪われねばならないのだろうか？
```

## 問題のイベント選択肢（任意）

```
7.
彼らはアヘンを食べ、それを気に入るだろう！
```

## 希望する変更（必須・修正部分のみ）

```
1.
清政府は大清におけるアヘン貿易を停止する意思表示をしました。イギリスはアヘンの主要輸出国であるため、この意思表示は大きな経済的関心事となっています。

2.
自由貿易と消費者の自由選択を妨げるあなたは、いったい何様なのか？と。

3.
需要がある。だから私たちは供給するのだ。

4.
――私たちが供給しなければ、他の国が漢のアヘン常用者へと供給し、吸い上げ、富んでいくのだ。

5.
全人民から取り上げる必要があるのだろうか？

6.
そして、アヘンが我が国へともたらす富。それが全イギリス国民から奪い去られて当然だとでもいうのか？

7.
かの国の民はアヘンを嗜むのだ、気に入っているのだ！
```

## 変更の理由（必須）

1.「これは～」で始まるのが個人的になじまない。具体的に書くか、いっそ「これは」を省略したい。
2.もともとの文で「を」を落とすtypo。加えて、原文のI say to 「them」 を受けてのwho are 「you」 to ～の形なので、「批判者」を問い質しているのを明示したい。
3.冗長に感じるので、短くした。
4.rich off で踏み台にする、the backs of で搾取するニュアンス　
5.every manがすべての人、となるのが個人的になじまない。全体的に演説調なのに、
6.「すべてのイギリスの家族 every British family」という表現は、皆、イギリスという国家の屋根の下に住まう共同体の一員じゃないか、というニュアンスなのだろうけど、単純に国民とした。
7.誤訳。eat opiumでアヘンを吸う。ただ、常用性日常性のニュアンスを入れると「嗜む」がいいのかなと。

## プレイ国家

イギリス

## ゲームバージョン（必須）

1.0.5

## DLC有無（必須）

なし

## MOD有無（必須）

日本語改善MOD
Switch Languages

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
ご提案を参考に、以下のように修正しました。

**Comment by clamm0363** [comment]
> [SCOPE.sCountry('opium_wars_target_country').GetAdjectiveNoFormatting]政府は[SCOPE.sCountry('opium_wars_target_country').GetName]におけるアヘン貿易を停止する意思表示をしました。[ROOT.GetCountry.GetName]はアヘンの主要輸出国であるため、この意思表示は大きな経済的関心事となっています。

**Comment by clamm0363** [comment]
> 「アヘン貿易は道徳的に悪であると批判する人もいるが、私は彼らに言いたい。自由貿易と消費者の自由選択を妨げるあなたは、いったい何様なのかと。需要がある。だから私たちは供給するのだ。――私たちが供給しなければ、他の国が[SCOPE.sCulture('opium_addicted_culture').GetNameNoFormatting]人のアヘン常用者を搾取して富むだけのことだ。後先考えずにアヘンを乱用する愚か者がいるからといって、あらゆる者からアヘンを奪うなどということが許されるのだろうか。アヘンによって我が国へともたらされる富を、[ROOT.GetCountry.GetAdjectiveNoFormatting]の人々から奪い去ることが本当に許されるとでもいうのであろうか」

**Comment by clamm0363** [comment]
選択肢に関してはご提案どおりとしています。

以上をもってクローズします。
