### ISSUE TITLE
強力、影響力がある、非主流派（Powerful、Influential、Marginalized）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#433]
## スクリーンショット（任意）
![20221111130908_1](https://user-images.githubusercontent.com/42687608/201263665-7ce469cb-b18d-4d3c-8f0e-917c9ccc14ea.jpg)

## 問題の用語（必須）

```
強力、影響力がある、非主流派
```

## 英語版の表現（任意）

```
Powerful、Influential、Marginalized
```

## 希望する変更（必須）

```
主流派、準主流派、非主流派
```

## 変更の理由（必須）

現在はツールチップなどで「影響力がある」が不自然な日本語になっている。
これを改善するため、他の用語とあわせて熟語で統一する。

## ゲームバージョン（必須）
1.0.5

## DLC有無（必須）
- Victoria II Remastered Soundtrack
- American Buildings Pack

## MOD有無（必須）
- 自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
関連の用語を含め、以下のように修正しました。
leading：最有力
Powerful：主流派
Influential：準主流派
Marginalized：非主流派（別issueで用語確定済み）

クローズします。
