### ISSUE TITLE
食品産業の蒸留酒生産方式

### ISSUE THREAD

**Issue by kurutto115** [matanki-saito/vic3jpadvmod#434]
## スクリーンショット（任意）
![Victoria 3 2022_11_11 13_31_35](https://user-images.githubusercontent.com/117251782/201311681-ecc27e8a-0892-4ed1-9fbb-efd2ecd5e9b8.png)

## 問題の用語（必須）

```
蒸留酒
食糧生産優先
ポットスチル
パテントスチル
```

## 英語版の表現（任意）

```
Distilleries
Prioritize Grocery Production
Pot Stills
Patent Stills
```

## 希望する変更（必須）

```
蒸留所
食品生産優先
単式蒸留器
連続式蒸留器
```

### 蒸留酒→蒸留所
原語に忠実にするため
### 食糧生産優先→食品生産優先
GroceryやFood Industriesの訳に「食品」の語が使われているので、こちらも合わせた方が良いと考えるため
### ポットスチル・パテントスチル
音訳で分かりにくいため

（参考）[単式蒸留器 - Wikipedia](https://ja.wikipedia.org/wiki/%E5%8D%98%E5%BC%8F%E8%92%B8%E7%95%99%E5%99%A8)、[Pot still - Wikipedia](https://en.wikipedia.org/wiki/Pot_still)、[連続式蒸留器 - Wikipedia](https://ja.wikipedia.org/wiki/%E9%80%A3%E7%B6%9A%E5%BC%8F%E8%92%B8%E7%95%99%E5%99%A8)、[Column still - Wikipedia](https://en.wikipedia.org/wiki/Column_still)
（Column stillはPatent Stillの別名）

## ゲームバージョン（必須）

1.0.5

## DLC有無（必須）

無し

## MOD有無（必須）

本プロジェクトMODのみ

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
報告ありがとうございます。ご指摘の通りなので、提案通り改訳しました。
