### ISSUE TITLE
探検ディシジョンのツールチップ

### ISSUE THREAD

**Issue by kurutto115** [matanki-saito/vic3jpadvmod#435]
##  スクリーンショット（必須）
![Victoria 3 2022_11_11 13_31_00](https://user-images.githubusercontent.com/117251782/201315479-ca913f6a-b644-4cbd-975b-814b452ecd93.png)

## 問題のあるインターフェイス（必須）

探検を行うディシジョンをマウスオーバーすると表示されるツールチップ

## 問題のテキスト（必須）

```
generalの役割を持っている
admiralの役割を持っている
```

## 希望する変更（必須）

```
将軍の役割を持っている
提督の役割を持っている
```

## 変更の理由（必須）

未訳のため

## ゲームバージョン（必須）

1.0.5

## DLCの有無（必須）

なし

## MODの有無（必須）

本プロジェクトMODのみ

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
#126 で既に起票されているもので、かつバグになりますので公式による修正待ちです
