### ISSUE TITLE
戦争支持率の低下スピード

### ISSUE THREAD

**Issue by kurutto115** [matanki-saito/vic3jpadvmod#436]
## スクリーンショット（必須）
![Victoria 3 2022_11_10 20_40_44](https://user-images.githubusercontent.com/117251782/201330305-29ab07d7-812f-46b0-bbcf-08a9a00032e0.png)
![Victoria 3 2022_11_10 14_00_40](https://user-images.githubusercontent.com/117251782/201330325-f9f1165b-64c5-475b-940f-28d38c6c74e0.png)

## 問題のツールチップ（必須）
戦争支持率の数値をマウスオーバーした際のツールチップ

## 問題の表現（必須）

```
×日で、彼らは疲労により-*.**を失います
```

## 問題箇所の英文（任意）

```
In X days they will get -*.** due to Exhaustion
```

## 希望する変更（必須）

```
残り×日で、彼らは厭戦により-*.**を失います
```

## 変更の理由（必須）

表示される日数はカウントダウンになっているが、訳文ではそのニュアンスが読み取れないため
合わせて"Exhaustion"を適切な訳語に変更し、直上の行と訳を統一すべき
また、原語では更に下の行がインデントされているが和訳では無くなっているため、
この行で示された低下量の内訳であることが分かりにくくなっている

## ゲームバージョン（必須）

1.0.5

## DLC有無（必須）

なし

## MOD有無（必須）

本プロジェクトMODのみ

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。
