### ISSUE TITLE
金発見の通知

### ISSUE THREAD

**Issue by kurutto115** [matanki-saito/vic3jpadvmod#437]
## スクリーンショット（必須）
![Victoria 3 2022_11_09 23_13_17](https://user-images.githubusercontent.com/117251782/201332897-509d211e-e564-4380-8683-3f67a0340d15.png)
![Victoria 3 2022_11_11 14_02_18](https://user-images.githubusercontent.com/117251782/201332911-12d65028-1910-4b73-bbea-3a0de3867dfe.png)

## 問題のあるインターフェイス（必須）

金が発見された際の通知

## 問題のテキスト（必須）

```
この州地域が支援できる採金地が増加します
```

## 希望する変更（必須）

```
この州地域で維持できる採金地が増加します
```

## 変更の理由（必須）

日本語として不自然なため

## ゲームバージョン（必須）

1.0.5

## DLCの有無（必須）

なし

## MODの有無（必須）

本プロジェクトMODのみ

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
報告ありがとうございます。ご提案の通り変更しました。なお金が枯渇した際も同様のメッセージがあったので、そちらも支援から維持に変更しています。
