### ISSUE TITLE
【修正提案】戦艦　Man-o-Wars

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#44]
## スクリーンショット（任意）
![image](https://user-images.githubusercontent.com/37979626/198071915-6bb8410c-b2d5-4458-9c7e-a91cef3e3fcb.png)
## 問題の固有名詞（必須）

戦艦

## 希望する変更（必須）

軍艦

## 変更の理由（必須）

ゲーム開始時から生産できる品物かつアイコンを見る限り帆船なので一般的に想起される「戦艦」ではないため

## ゲームバージョン（必須）

1.0.1

## DLC有無（必須）

なし

## MOD有無（必須）

（例）なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1034855855411175474
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by matanki-saito** [comment]
> 戦列艦/装甲艦/モニター艦/ド級戦艦/超ド級戦艦
いいですね。ドレッドノートと戦艦の改訳は別で起票するとして、「戦列艦」でいきたいと思います
