### ISSUE TITLE
一部の国名と形容詞がおかしい

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#440]
## 問題の固有名詞と希望する変更（必須）

日本幕府：幕政日本
シュリーヴィジャヤ系：シュリーヴィジャヤ
スマトラ人：スマトラ
ケープ植民地群：ケープ植民地
マフディスト州：マフディー国
マフディスト・スーダン人：スーダン・マフディー国
カルマル同盟：カルマル連合
スカンジナビア人：スカンジナビア
ヌーベルフランス：ヌーヴェル・フランス
ヌーベルフランス系：ヌーヴェル・フランス
（dyn_c_bremener_raterepublic）バイエルン・レーテ共和国：ブレーメン・レーテ共和国
バクヴィアン：バクー
ザンベジ自由州：ザンベジ自由国
ナイル川自由国：ナイル川流域自由国

## 変更の理由（必須）

日本語的ではない誤訳と思われるものがある。

## ゲームバージョン（必須）

1.0.5

## DLC有無（必須）

なし

## MOD有無（必須）

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。
