### ISSUE TITLE
経済的健康（Economy Health）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#443]
## スクリーンショット（任意）

![20221112093534_1](https://user-images.githubusercontent.com/42687608/201447877-5f7e1465-d64e-4307-b041-0a5e98e94933.jpg)

## 問題の用語（必須）

```
経済的健康
```

## 英語版の表現（任意）

```
Economy Health
```

## 希望する変更（必須）

```
経済的健全性
```

## 変更の理由（必須）

定訳であるため。
経済的健全性の意味で単なるHealthが登場することがあるので注意。

## ゲームバージョン（必須）

1.0.5

## DLC有無（必須）

- Victoria II Remastered Soundtrack
- American Buildings Pack

## MOD有無（必須）

- 自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
財政健全性、およびその省略で修正
