### ISSUE TITLE
認識の強要（Force Recognition）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#444]
## スクリーンショット（任意）

![20221112103347_1](https://user-images.githubusercontent.com/42687608/201452732-4f00212b-2eda-4203-9462-1d16a5257719.jpg)

## 問題の用語（必須）

```
認識の強要
```

## 英語版の表現（任意）

```
Force Recognition
```

## 希望する変更（必須）

```
承認の強要
```

## 変更の理由（必須）

西洋列強に認められていない国は「未承認国家」と翻訳されており、表記ゆれを起こしているため。
同時に「未認識ステータス」等も修正する。

## ゲームバージョン（必須）

1.0.5

## DLC有無（必須）

- Victoria II Remastered Soundtrack
- American Buildings Pack

## MOD有無（必須）

- 自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
「認識の強要」を「承認の強要」に、「未認識ステータス」を「未承認状態」にそれぞれ修正しました。
