### ISSUE TITLE
北極

### ISSUE THREAD

**Issue by clamm0363** [matanki-saito/vic3jpadvmod#445]
※「｀｀｀」は消さないでください

## スクリーンショット（任意）
![image](https://user-images.githubusercontent.com/29382778/201456254-72e5ded6-0c5a-479c-9dcf-3da299625aea.png)

## 問題の用語（必須）

```
北極
```

## 英語版の表現（任意）

```
Arctic
```

## 希望する変更（必須）

```
氷原
```

## 変更の理由（必須）

北極ではないため

## ゲームバージョン（必須）

1.0.5

## DLC有無（必須）

Deluxe Edition

## MOD有無（必須）

日本語修正MOD等

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。
