### ISSUE TITLE
建造物マウスオーバー時のツールチップ

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#446]
※「｀｀｀」は消さないでください

## スクリーンショット（必須）

![20221110193344_1](https://user-images.githubusercontent.com/42710893/201457996-58664053-fe5a-4f3a-b769-a7684f5fca37.jpg)

## 問題のツールチップ（必須）

建造物マウスオーバー時のツールチップ

## 問題の表現（必須）

```
BUILDING_TYPE_COUNTRY_BREAKDOWN_NONEMPTY:0 "[GetPlayer.GetName][SelectLocalization(And(Not(BuildingType.IsGovernmentFunded), Not(BuildingType.IsSubsistenceBuilding)), 'BUILDING_TYPE_PRODUCTIVITY', '')]の[BuildingType.GetNameNoFormatting]の#tooltippable #tooltip:[BuildingType.GetTooltipTag],BUILDING_TYPE_COUNTRY_BREAKDOWN_TOOLTIP [BuildingType.GetLevelCountInCountry(GetPlayer.Self)]#!#!レベルがあります"
```

## 問題箇所の英文（任意）

```
BUILDING_TYPE_COUNTRY_BREAKDOWN_NONEMPTY:0 "There are #tooltippable #tooltip:[BuildingType.GetTooltipTag],BUILDING_TYPE_COUNTRY_BREAKDOWN_TOOLTIP [BuildingType.GetLevelCountInCountry(GetPlayer.Self)]#!#! Levels of [BuildingType.GetNameNoFormatting] in [GetPlayer.GetName][SelectLocalization(And(Not(BuildingType.IsGovernmentFunded), Not(BuildingType.IsSubsistenceBuilding)), 'BUILDING_TYPE_PRODUCTIVITY', '')]"
```

## 希望する変更（必須）

```
[建造物名]の生産性：○○－○○、レベル：△△です　等
```

## 変更の理由（必須）

現状は日本語として不自然

## ゲームバージョン（必須）

1.0.5

## DLC有無（必須）

なし

## MOD有無（必須）

日本語改善MOD
フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
> BUILDING_TYPE_COUNTRY_BREAKDOWN_NONEMPTY:0 "[GetPlayer.GetName]には#tooltippable #tooltip:[BuildingType.GetTooltipTag],BUILDING_TYPE_COUNTRY_BREAKDOWN_TOOLTIP [BuildingType.GetLevelCountInCountry(GetPlayer.Self)]#!#!の[BuildingType.GetNameNoFormatting]があります[SelectLocalization(And(Not(BuildingType.IsGovernmentFunded),Not(BuildingType.IsSubsistenceBuilding)),'BUILDING_TYPE_PRODUCTIVITY','')]

**Comment by clamm0363** [comment]
![image](https://user-images.githubusercontent.com/29382778/204038672-4736a168-f343-413c-8eee-64a3d6b4dc90.png)

**Comment by clamm0363** [comment]
検討の結果、上記のとおり修正しました

クローズします
