### ISSUE TITLE
【バグ】鉄道の自動拡張ツールチップ

### ISSUE THREAD

**Issue by clamm0363** [matanki-saito/vic3jpadvmod#447]
※「｀｀｀」は消さないでください

## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/29382778/201459450-331a978d-160e-43fd-aee1-ce40c20e81fe.png)

## 問題のツールチップ（必須）

鉄道の自動拡張ボタンのツールチップ

## 問題の表現（必須）

```
[地名]の[市場アクセス]が[100%]以上（現在: 94%）
```

## 問題箇所の英文（任意）

```
[State.GetName]の[concept_market_access]が$NUM|%0v$以上 (現在: $CURRENT_VALUE|%0v$)
```

## 希望する変更（必須）

```
100%未満でトリガーするはずのものが、説明文では100%以上となっている
```

## 変更の理由（必須）

キーの設定ミス

## ゲームバージョン（必須）

1.0.5

## DLC有無（必須）

Deluxe Edition

## MOD有無（必須）

日本語修正MOD等

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
@matanki-saito こちら、誤訳ではなく原文で誤ったテキストが使われています。「提案」タグが必要かと思われますがいかがでしょうか？

**Comment by inarizushi0309** [comment]
こちら公式フォーラムに報告しましたのでクローズします
