### ISSUE TITLE
恩義の拒絶の [concept_relation]　→　[concept_relations]

### ISSUE THREAD

**Issue by swokajima** [matanki-saito/vic3jpadvmod#448]
※「｀｀｀」は消さないでください

## スクリーンショット（必須）
※画像はドラッグ＆ドロップで貼り付けられます。
※できるだけ問題箇所の前後を含めて貼ってください。

## 問題のあるインターフェイス（必須）

恩義の拒絶

## 問題のテキスト（必須）

```
"私たちが[concept_obligation]を拒絶した[concept_country]との[concept_relations]が大幅に減少\n私たちが[concept_obligation]を負う他国との[concept_relation]が減少\n
```

## 希望する変更（必須）

```
"私たちが[concept_obligation]を拒絶した[concept_country]との[concept_relations]が大幅に減少\n私たちが[concept_obligation]を負う他国との[concept_relations]が減少\n
```

## 変更の理由（必須）

エラー出してるので

## ゲームバージョン（必須）

1.0.5

## DLCの有無（必須）

なし

## MODの有無（必須）

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
「貸し」「借り」への変更を含む多数の修正を実施。実際のゲーム画面で確認してください。
