### ISSUE TITLE
文化受容のトリガー

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#449]
※「｀｀｀」は消さないでください

## スクリーンショット（任意）
![trigger_vanilla](https://user-images.githubusercontent.com/50406316/201467906-c4223cec-1eff-45ee-8121-90df6c8b097c.png)
![trigger_revised](https://user-images.githubusercontent.com/50406316/201467911-73a79af4-62c7-4029-a669-f84b272fc19a.png)
![trigger_en](https://user-images.githubusercontent.com/50406316/201468024-ac954b38-39bd-4529-b133-31f3a073d9e2.png)

## 問題の用語（必須）

```
スクショ上が翻訳改善MOD使用後、中が日本語バニラ、下が英語
日本語バニラでは「いかなる主要文化（(国名)の(文化名)）とも伝統文化特性でない文化特性を共有していません」となる
キーはTRIGGER_SHARES_NON_HERITAGE_TRAIT_WITH_ANY_PRIMARY_CULTURE_NOCONTEXT
```

## 英語版の表現（任意）

```
Shares a Cultural Trait which is not a Heritage Cultural Trait with any Primary Cultures ((Culture) in (Country))
```

## 希望する変更（必須）

```
いずれかの主要文化（(国名)の(文化名)）と非系統文化特性文化特性を共有
```

## 変更の理由（必須）

バニラの段階から訳語の正否が逆になっている誤訳のため。
別のissueでトリガー表記を体言止めにするなど表現を変えているのでこちらも合わせる。

## ゲームバージョン（必須）

1.0.5

## DLC有無（必須）

無し

## MOD有無（必須）

なし/翻訳改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
別issueで解決したため取り下げ
