### ISSUE TITLE
【修正提案】自走砲　Mobile Artillery

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#45]
## スクリーンショット（任意）
![image](https://user-images.githubusercontent.com/37979626/198073625-80943b4b-1188-4c8c-aa99-0c06fa244208.png)

## 問題の固有名詞（必須）

自走砲

## 希望する変更（必須）

機動砲兵

## 変更の理由（必須）

技術「ナポレオン戦争」で解禁されるもので、明らかに自動車ではないため

## ゲームバージョン（必須）

1.0.1

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1034856219300597760
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by inarizushi0309** [comment]
騎馬砲兵で確定
