### ISSUE TITLE
【バグ】の夢（The dream）

### ISSUE THREAD

**Issue by WoodlandsGitHub** [matanki-saito/vic3jpadvmod#450]
## スクリーンショット（任意）
![image](https://user-images.githubusercontent.com/29177147/201467565-e265f0d5-5cd2-4454-b0cc-507b60bdc387.png)
![image](https://user-images.githubusercontent.com/29177147/201467568-8d814a7d-733a-4644-8db8-57d23ab3957b.png)

## 問題部分（タイトル・本文・選択肢）

```
タイトル
```

## 問題のイベントタイトル（必須）

```
の夢

※参考
 goldrush.5.t:2 "The [ROOT.GetCountry.GetAdjectiveNoFlag] Dream"
 goldrush.5.t:2 "[ROOT.GetCountry.GetAdjectiveNoFlag]の夢"
```

## 問題のイベント本文（任意・抜粋可）

```

```

## 問題のイベント選択肢（任意）

```

```

## 希望する変更（必須・修正部分のみ）

```
○○の夢
```

## 変更の理由（必須）

変数が表示されていない

## プレイ国家

ロシア

## ゲームバージョン（必須）

1.0.5

## DLC有無（必須）

なし

## MOD有無（必須）

日本語改善MOD
Switch Languages

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
バニラでの修正が確認できたためクローズします。
