### ISSUE TITLE
制度の投資レベルが上がった時のフィード

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#451]
※「｀｀｀」は消さないでください

## スクリーンショット（必須）

![20221112212440_1](https://user-images.githubusercontent.com/42710893/201473926-66bf49f5-cdb2-4c9a-bd19-efbb0eda92bb.jpg)

## 問題のあるインターフェイス（必須）

制度の投資レベルが上がった時のフィード

## 問題のテキスト（必須）

```
notification_institution_investment_increased_desc:0 "[SCOPE.GetRootScope.GetInstitution.GetInvestmentLevel|v]を目指して[SCOPE.GetRootScope.GetInstitution.GetName]制度での増資を行いました"

英語
notification_institution_investment_increased_desc:0 "Increased Investment in the [SCOPE.GetRootScope.GetInstitution.GetName] Institution to [SCOPE.GetRootScope.GetInstitution.GetInvestmentLevel|v]"
```

## 希望する変更（必須）

```
[SCOPE.GetRootScope.GetInstitution.GetName]制度への投資がレベル[SCOPE.GetRootScope.GetInstitution.GetInvestmentLevel|v]に増加しました　等
```

## 変更の理由（必須）

最終的な目標レベルではなく、到達時のレベルを示す文章なので、～を目指してという文章は不自然です。
また、数字だけでは何のことかわからないので、「レベル」を入れるべきと思います。
レベルが低下した場合notification_institution_investment_decreased_desc:0も同様に修正が必要

## ゲームバージョン（必須）

1.0.5

## DLCの有無（必須）

なし

## MODの有無（必須）

日本語改善MOD
フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
報告ありがとうございます。増加時、低下時あわせて提案通り修正しました。
