### ISSUE TITLE
清の実業家リーダー 阮元を「院」元 と字を誤っている

### ISSUE THREAD

**Issue by Keichu-Jingzhong** [matanki-saito/vic3jpadvmod#452]
## スクリーンショット（任意）
![image](https://user-images.githubusercontent.com/117831835/201502860-6aa5b741-1cb3-40af-881a-9b02dcd6ebc1.png)
![image](https://user-images.githubusercontent.com/117831835/201503154-978ad54d-9e0f-4357-a393-dc870c5111ec.png)

## 問題の固有名詞（必須）
  
  英文 「Yuan Ruan 」  ※名姓の順
  JapaneseLanguageAdvancedMod 適用状態 「元 院」※名姓の順

## 希望する変更（必須）

【院】はあやまりであるため、【阮】とする

## 変更の理由（必須）

  中国語版において「元 阮」。
【日本語版WIKI】https://ja.wikipedia.org/wiki/%E9%98%AE%E5%85%83

## ゲームバージョン（必須）

1.0.5

## DLC有無（必須）

なし

## MOD有無（必須）

JapaneseLanguageAdvancedMod
Switch Languages

**Comment by ChiefIdeologue** [comment]
「阮」に修正しました。

クローズします。
