### ISSUE TITLE
メカニカルツール

### ISSUE THREAD

**Issue by mochi115** [matanki-saito/vic3jpadvmod#453]
## スクリーンショット（任意）

![スクリーンショット (7)](https://user-images.githubusercontent.com/117048815/201519023-f8adea84-00a6-48fb-8edd-1503bbe9c75f.png)
## 問題の固有名詞（必須）

メカニカルツール

## 希望する変更（必須）

機械製工具

## 変更の理由（必須）

そのままカタカナにするより訳した方が直感的に分かりやすいと思います。

## ゲームバージョン（必須）

1.0.5

## DLC有無（必須）

なし

## MOD有無（必須）

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
報告ありがとうございます。ご提案の通り日本語訳することにした一方で、議論の中でこれは機械製ではなく工具自体が機械になっているものを指すのではないかという意見があったため、機械工具と改訳することにしました。
