### ISSUE TITLE
最大予備現金

### ISSUE THREAD

**Issue by mochi115** [matanki-saito/vic3jpadvmod#454]
※「｀｀｀」は消さないでください

## スクリーンショット（任意）

![スクリーンショット (6)](https://user-images.githubusercontent.com/117048815/201519491-d4ffa806-51e6-40da-8cda-d16f42c1d91c.png)

## 問題の用語（必須）

```
最大予備現金
```

## 希望する変更（必須）

```
最大手元資金
```

## 変更の理由（必須）

表記ゆれの修正です。

## ゲームバージョン（必須）

1.0.5

## DLC有無（必須）

無し

## MOD有無（必須）

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
最大手元資金で修正
