### ISSUE TITLE
【修正提案】列強ツールチップ内の表現

### ISSUE THREAD

**Issue by nakka8** [matanki-saito/vic3jpadvmod#456]
## スクリーンショット（必須）

![スクリーンショット (542)](https://user-images.githubusercontent.com/61678668/201520281-2853ca72-d7f7-4b00-8fcb-eb58c9366745.png)

## 問題のツールチップ（必須）

列強

## 問題の表現（必須）

```
最大に宣言された関心
```

## 問題箇所の英文（任意）

```

```

## 希望する変更（必須）

```
最大の宣言された関心（関心については別にissueがあるみたいですのでその変更があればそちらも適応してください）
```

## 変更の理由（必須）

最大「の」の方が名詞の修飾には適切なため

## ゲームバージョン（必須）

1.0.5

## DLC有無（必須）

grand edition付属

## MOD有無（必須）

Japanese Language Advanced Mod
Universal Names

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
「関心表明の最大値」と修正しました。

クローズします。
