### ISSUE TITLE
技術 化学兵器戦争

### ISSUE THREAD

**Issue by mochi115** [matanki-saito/vic3jpadvmod#457]
※「｀｀｀」は消さないでください

## 問題の用語（必須）

```
化学兵器戦争
```

## 希望する変更（必須）

```
化学戦
```

## 変更の理由（必須）

化学戦の方が一般的に使用されているかと思います。

## ゲームバージョン（必須）

1.0.5

## DLC有無（必須）

無し

## MOD有無（必須）

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
ご提案の通り「化学戦」に決定し、修正を完了しました。
