### ISSUE TITLE
技術 電気コンデンサー

### ISSUE THREAD

**Issue by mochi115** [matanki-saito/vic3jpadvmod#458]
※「｀｀｀」は消さないでください

## スクリーンショット（任意）
![スクリーンショット (12)](https://user-images.githubusercontent.com/117048815/201530869-fed7ddea-71e7-43b7-b1ae-b4bc3c81c08c.png)
## 問題の用語（必須）

```
電気コンデンサー
```

## 希望する変更（必須）

```
コンデンサ
```

## 変更の理由（必須）

一般的な名称だと思います。

## ゲームバージョン（必須）

1.0.5

## DLC有無（必須）

無し

## MOD有無（必須）
日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
議論の結果「蓄電器」と修正することになりました。

クローズします。
