### ISSUE TITLE
技術 軍用航空

### ISSUE THREAD

**Issue by mochi115** [matanki-saito/vic3jpadvmod#459]
※「｀｀｀」は消さないでください

## スクリーンショット（任意）

![スクリーンショット (13)](https://user-images.githubusercontent.com/117048815/201533274-ffa514bb-a7e3-4c65-9d77-0802dc9ba28b.png)

## 問題の用語（必須）

```
軍用航空
```

## 英語版の表現（任意）

```
Military Aviation
```

## 希望する変更（必須）

```
軍事航空
```

## 変更の理由（必須）

[(https://ja.wikipedia.org/wiki/%E8%BB%8D%E4%BA%8B%E8%88%AA%E7%A9%BA)](https://ja.wikipedia.org/wiki/%E8%BB%8D%E4%BA%8B%E8%88%AA%E7%A9%BA)
Wikipediaに一応記事がありますしそれに合わせても大丈夫だと思います。

## ゲームバージョン（必須）

1.0.5

## DLC有無（必須）

無し

## MOD有無（必須）

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
報告ありがとうございます。ご提案の通り改訳しました。
