### ISSUE TITLE
イベント「非効率な農業」の文中の余計なi

### ISSUE THREAD

**Issue by WoodlandsGitHub** [matanki-saito/vic3jpadvmod#46]
## スクリーンショット（任意）
![image](https://user-images.githubusercontent.com/29177147/198080926-8d2a9ac4-a0a5-403e-bb96-a5b87b90e509.png)

## 問題部分（タイトル・本文・選択肢）

本文

## 問題のイベントタイトル（必須）

非効率な農業

## 問題のイベント本文（任意・抜粋可）

～その紛れもないi非効率性を～

## 希望する変更（必須・修正部分のみ）

～その紛れもない非効率性を～

## 変更の理由（必須）

単純なtypo

## プレイ国家

スウェーデン

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1034866805363195925
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by Zousuikakka** [comment]
修正しました
