### ISSUE TITLE
非承認大国、非承認地方国、非承認国、非承認国家（Unrecognized Power 他）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#462]
### スクリーンショット

![20221121084046_1](https://user-images.githubusercontent.com/42687608/202933117-f0a118d5-edb8-48fc-9516-8f3396bd9143.jpg)

### 問題の用語

非承認大国、非承認地方国、非承認国、非承認国家

### 英語版の表現

Unrecognized Major Power、Unrecognized Regional Power、Unrecognized Power、Unrecognized Country

### 希望する変更

未承認大国、未承認地域大国、未承認国、未承認国家

### 変更の理由（概要）

日本語として自然な表現に変更

### 変更の理由（詳細）

「非承認」は「承認にあらず」、すなわち「承認ではない」という意味であり、日本語として意味が通っていない。
「まだ承認されていない」のだから「未承認」と翻訳するのが正しい。
それぞれの用語は Unrecognized Major Power＞Unrecognized Regional Power＞Unrecognized Power の順で国の強さを表している（「＞」は不等号）。
Unrecognized Country はこれらの国をすべて含む総称らしい。

### ゲームバージョン

1.0.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
原案通り修正を完了しました。
