### ISSUE TITLE
Breaks

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#463]
### スクリーンショット

![break](https://user-images.githubusercontent.com/50406316/203016908-5c32adce-51e3-4c4f-af7b-241a0604da8d.png)

### 問題のツールチップ

イベントで外交関係が破棄される場合のテキスト

### 問題の表現

〇〇と××との間で行われている△△(外交アクション) に乱れが生じます

### 問題箇所の英文

Breaks △△ (Diplomatic Action) between 〇〇 and ××

### 希望する変更

〇〇と××の間の△△(外交アクション) を破棄します

### 変更の理由（概要）

breakの誤訳修正

### プレイ国家

イギリス（ヴィクトリア即位イベント）

### ゲームバージョン

1.0.X

### MOD有無

翻訳改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
提案通り変更しました。付随して、翻訳チーム内でスクリーンショット内の「ハノーファー関税同盟～～」のテキストについても指摘があったため、文体を敬体に統一およびメンバー→構成国への変更を行いました。
