### ISSUE TITLE
ニューゲーム選択後のサンドボックスの文言「目標を定めずプレイし、国選択に進む」

### ISSUE THREAD

**Issue by WoodlandsGitHub** [matanki-saito/vic3jpadvmod#464]
### スクリーンショット

![image](https://user-images.githubusercontent.com/29177147/203025166-46209c2f-dbcf-4f38-a95d-ec3a527cd104.png)

### 問題のあるインターフェイス

メインメニュー＞ニューゲーム＞一番右のサンドボックスの文言

### 問題のテキスト

目標を定めずプレイし、国選択に進む

### 希望する変更

目標を定めずにプレイ

### 変更の理由（概要）

日本語として不自然で、文字溢れも具合悪い

### ゲームバージョン

1.0.X

### MOD有無

日本語改善MOD、Switch Languages

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
原案の通りに修正を完了しました。
