### ISSUE TITLE
Freedom of Conscience

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#465]
### スクリーンショット

![Conscience](https://user-images.githubusercontent.com/50406316/203035769-9626f9ad-56fe-4f57-8eae-15683eecea77.png)

### 問題の用語

良心の自由

### 英語版の表現

Freedom of Conscience

### 希望する変更

信条の自由

### 変更の理由（概要）

ゲーム上の効果に合わせた改訳

### 変更の理由（詳細）

Conscienceは良心、思想、信教、信条などの意味。ゲーム上では宗教法のカテゴリで、国教の異端（カトリックに対するプロテスタント、スンニ派に対するシーア派など）まで受容するという意味なので、宗教と分かる訳語に変えたい。なお信教の自由としてしまうと全宗教受容するTotal Separation（完全分離）と紛らわしいので信条とした。

### ゲームバージョン

1.0.X

### MOD有無

翻訳改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
翻訳チーム内の議論の中で信仰の自由などとの違いが分かりにくいという指摘も出ましたが、日本語の「信条」はキリスト教用語で教派を分けるような成文箇条を意味する用語であること（カルケドン信条など）と、原文のConscienceの訳語にも使えることで、原文から離れない範囲で宗教を意味する訳語であるとして提案通り改訳することになりました。
