### ISSUE TITLE
戦争支持の説明

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#466]
### スクリーンショット

![wargoal](https://user-images.githubusercontent.com/50406316/203036867-8a509262-6a22-4208-950b-5c3a124c575c.png)

### 問題のツールチップ

戦争支持を0未満にすることができない理由

### 問題の表現

戦争支持率を0未満にすることはできません。彼らは首都を保持しており、次の戦争目標に専念できなくなるためです:

### 問題箇所の英文

War Support cannot be reduced below 0 because they hold their capital and the following wargoals are not being occupied:

### 希望する変更

彼らは首都を保持しており、かつ以下の戦争目標が占領されていないため、戦争支持率を0未満にすることはできません：

### 変更の理由（概要）

誤訳でゲームルールの意味が伝わらなくなっているため

### 変更の理由（詳細）

ゲームルールでは敵の首都を占領する、または戦争目標を全て占領することで敵の戦争支持率を0未満にすることができ、どちらも達成できていないと敵の戦争支持率は下限0でキャッピングされてマイナスにならないが、誤訳によりそのルールが説明できていないため。

### プレイ国家

どの国でも

### ゲームバージョン

1.0.X

### MOD有無

翻訳改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
「彼らは首都を保持しており、かつ以下の戦争目標となっている地域が占領されていないため、戦争支持率を0未満にすることはできません：」となるように修正しました。

クローズします。
