### ISSUE TITLE
外交レンズ＞外交アクション＞貿易協定から適当な国「（数値）影響力に貿易協定を送る」

### ISSUE THREAD

**Issue by WoodlandsGitHub** [matanki-saito/vic3jpadvmod#467]
### スクリーンショット

![image](https://user-images.githubusercontent.com/29177147/203031759-c9f49257-4dad-4147-b3c5-2a13c3ad1fdc.png)
![image](https://user-images.githubusercontent.com/29177147/203031678-ad1e12c4-34d7-4730-b085-eedd3228af21.png)

### 問題のツールチップ

外交レンズ＞外交アクション＞貿易協定＞適当な国をマウスオーバー

### 問題の表現

（国名）

メンテナンスコスト：（アイコン）（数値）影響力に貿易協定を送る

参考：
```
MAP_INTERACTION_DIPLOMATIC_ACTION_TOOLTIP:0 "[TARGET_COUNTRY.GetName][AddTextIf(GreaterThan_CFixedPoint('(CFixedPoint)$MAINTENANCE_COST$','(CFixedPoint)0'),Concatenate('\n\nメンテナンスコスト: @inf!$MAINTENANCE_COST|v0$#! ',concept_influence))]に[DIPLOMATIC_ACTION_TYPE.GetName|v]を送る"
```

### 問題箇所の英文

添付スクリーンショット参考

### 希望する変更

（国名）に貿易協定を送る

維持コスト：（アイコン）（数値）影響力

### 変更の理由（概要）

訳文のコピーミス

### 変更の理由（詳細）

訳文の「貿易協定」に当たる部分が各種外交アクションによって変化する汎用文なので、かたっぱしから変なところに「に～～を送る」が付く形になっている。

この訳文が使われる外交アクションは以下の通り
・保護国
・保護国化の打診
・同盟
・朝貢国
・朝貢国化の打診
・禁輸
・私たちの関税同盟に変更
・融資
・貿易協定
・関係改善
・関係破壊
・関税同盟
・関税同盟に参加
・防衛協定

### プレイ国家

オスマントルコ

### ゲームバージョン

1.0.X

### MOD有無

日本語改善MOD、Switch Languages

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
> [TARGET_COUNTRY.GetName]に[DIPLOMATIC_ACTION_TYPE.GetName|v]を送る[AddTextIf(GreaterThan_CFixedPoint('(CFixedPoint)$MAINTENANCE_COST$','(CFixedPoint)0'),Concatenate('\n\n維持コスト: @inf!$MAINTENANCE_COST|v0$#! ',concept_influence))]

**Comment by clamm0363** [comment]
上記のように修正しました。

クローズします
