### ISSUE TITLE
軍事レンズ＞施設タブ＞兵舎「（国名）の兵舎の（数字）レベルがあります」

### ISSUE THREAD

**Issue by WoodlandsGitHub** [matanki-saito/vic3jpadvmod#468]
### スクリーンショット

![image](https://user-images.githubusercontent.com/29177147/203048255-7da0c6ad-b0f0-49f5-b4b6-b2a04474cd1c.png)
![image](https://user-images.githubusercontent.com/29177147/203048330-f0be34be-6ac8-4a5e-8016-c61a94f59cc4.png)

### 問題のツールチップ

軍事レンズ＞施設タブ＞兵舎

### 問題の表現

（国名）の兵舎の（数字）レベルがあります

参考：
```
 BUILDING_TYPE_COUNTRY_BREAKDOWN_NONEMPTY:0 "[GetPlayer.GetName][SelectLocalization(And(Not(BuildingType.IsGovernmentFunded), Not(BuildingType.IsSubsistenceBuilding)), 'BUILDING_TYPE_PRODUCTIVITY', '')]の[BuildingType.GetNameNoFormatting]の#tooltippable #tooltip:[BuildingType.GetTooltipTag],BUILDING_TYPE_COUNTRY_BREAKDOWN_TOOLTIP [BuildingType.GetLevelCountInCountry(GetPlayer.Self)]#!#!レベルがあります"
```

### 問題箇所の英文

上のSS参考

### 希望する変更

（国名）には（数字）レベル分の兵舎があります

### 変更の理由（概要）

日本語が不自然

### プレイ国家

オスマントルコ

### ゲームバージョン

1.0.X

### MOD有無

日本語改善MOD、Switch Languages

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
ISSUE#446の関連キーとして修正済みですのでクローズします。
