### ISSUE TITLE
文化の固有名詞

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#47]
## 問題の固有名詞と希望する変更（必須）

ワロニア：ワロン
アングロ・カナダ：イギリス系カナダ
カタロニア：カタルーニャ
フランス・カナダ：フランス系カナダ
南スラブ：南スラヴ
東スロバキア：東スラヴ
ベラルーシ：白ロシア
バルティック：バルト
マスリ：ミスル
アマジグ：アマーズィーグ
ペルシャ：ペルシア
ハザラ：ハザーラ
マニプリ：マニプル
パンジャブ：パンジャーブ
マラーティー：マラーター
小アジア：アジア少数民族
広東：粤
サポテク：サポテカ
ナヴァホ：ナバホ
ミスキティア：ミスキート
カリブ：カリベニョ
アフリカ・アメリカ：アフリカ系アメリカ
アフリカ・カリブ：アフリカ系カリブ
アフリカ・カリブ：アフリカ系カリベニョ
アフリカ・ブラジル：アフリカ系ブラジル
アフリカ・アンティル：アフリカ系アンティル
江戸：エド
ハラチン：ハラティン
モッシ：モシ
コンゴ：バコンゴ
アフリカ・少数民族：アフリカ少数民族
シダマ：シダモ
オクシタニア：オック
スマトラ人：スマトラ
ボルネオ人：ボルネオ
バリ人：バリ

イエメン系：イエメン

## 変更の理由（必須）
日本語では一般的ではない表記であるため

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）
なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1034886936361435257
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by ChiefIdeologue** [comment]
イエメン系：イエメンを追加しました。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
