### ISSUE TITLE
方式の変更ツールチップ（原料不足が起きる場合の警告メッセージ）

### ISSUE THREAD

**Issue by AruiKashiwagi** [matanki-saito/vic3jpadvmod#470]
### スクリーンショット

![20221121211956_1b](https://user-images.githubusercontent.com/52348271/203054334-2f78b9a8-895b-414d-8603-9e468a1686ef.jpg)

### 問題のツールチップ

いずれかの施設→いずれかの方式をマウスオーバー→変更の詳細ツールチップ

### 問題の表現

「原料不足が鋼鉄の場合、すべての施設出力にペナルティが課せられます。」

interfaces_l_japanese.yml
```
CHANGE_PRODUCTION_METHOD_WARNING_GOODS_SHORTAGE:0 "@warning![concept_input_goods_shortage]が$LIST$の場合、すべての[concept_building]出力にペナルティが課せられます。"
```

### 問題箇所の英文

interfaces_l_english.yml
```
CHANGE_PRODUCTION_METHOD_WARNING_GOODS_SHORTAGE:0 "@warning! [concept_input_goods_shortage] of $LIST$ will result in a penalty on all [concept_building] outputs"
```

### 希望する変更

例：「鋼鉄が原料不足のため、すべての施設出力にペナルティが課せられます。」
```
 CHANGE_PRODUCTION_METHOD_WARNING_GOODS_SHORTAGE:0 "@warning! $LIST$が[concept_input_goods_shortage]のため、すべての[concept_building]出力にペナルティが課せられます。"
```

### 変更の理由（概要）

語順ミス、文脈に合っていない表現

### 変更の理由（詳細）

語順がおかしい。
変更すると確実に原料不足が起きる際の警告メッセージなので、「～の場合」ではなく断定にするべき。

### プレイ国家

ハワイ

### ゲームバージョン

1.1.X

### MOD有無

Japanese Language Advanced Mod, Visual Methods

**Comment by Zousuikakka** [comment]
[商品]が[不足]するため、[施設]の生産すべてにペナルティが生じるでしょう
で修正しました
