### ISSUE TITLE
【一括修正】effects_l_english

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#471]
### スクリーンショット

![image](https://user-images.githubusercontent.com/37979626/203053504-b3c84faf-89f7-4aa3-89ec-50a832d2adcf.png)

### 問題のツールチップ

例）宗主国の外交画面>独立要請ツールチップ

### 問題の表現

[COUNTRY.GetName]と[TARGET_COUNTRY.GetName]は、$MONTHS|0v$ヶ月#!の#variable 停戦協定を締結しました

### 問題箇所の英文

[COUNTRY.GetName] and [TARGET_COUNTRY.GetName] gets a #variable truce for $MONTHS|0v$ months#!

### 希望する変更

[COUNTRY.GetName]と[TARGET_COUNTRY.GetName]は、$MONTHS|0v$ヶ月#!の#variable 停戦協定を締結

### 変更の理由（概要）

丁寧な表現（敬体）ゆえに冗長になり、ツールチップが見づらくなっているため

### 変更の理由（詳細）

そもそも英語から日本語に直す際になぜか過去形に訳されている箇所がeffects_l_englishに散見されており、ゲーム内での使われ方に一致していない。
さらに条件文同様、常体・体言止めにした方が良い。
※各エントリの中身に関する修正は都度起票することとする

### プレイ国家

東インド会社

### ゲームバージョン

1.1.X

### MOD有無

JapaneseLanguageAdvancedMod, Japanese Flavor, Universal Names

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
文末表現を未来形に統一する形で確定

**Comment by inarizushi0309** [comment]
議論の結果、文末表現を敬体で統一する方針で確定
