### ISSUE TITLE
(提案) 貿易関連の「従業員、年間」

### ISSUE THREAD

**Issue by swokajima** [matanki-saito/vic3jpadvmod#472]
### スクリーンショット

![image](https://user-images.githubusercontent.com/32781802/203058671-1552767c-ddd1-4c10-b84a-6d20332e555e.png)

### 問題のあるインターフェイス

貿易関連

### 問題のテキスト

TRADE_ROUTE_REVENUE_AFTER_TARIFF:0 "[concept_tariffs]後の[concept_trade_revenue]: #tooltippable #tooltip:$BREAKDOWN_TAG$ @money!$REVENUE_AFTER_TARIFF|D+$#!#! （@money!$PRODUCTIVITY|D+$/従業員、年間）"

### 希望する変更

TRADE_ROUTE_REVENUE_AFTER_TARIFF:0 "[concept_tariffs]後の[concept_trade_revenue]: #tooltippable #tooltip:$BREAKDOWN_TAG$ @money!$REVENUE_AFTER_TARIFF|D+$#!#! （@money!$PRODUCTIVITY|D+$/レベル、年間）"

### 変更の理由（概要）

貿易に従業員はいない

### 変更の理由（詳細）

貿易に従業員はいないので、おそらく建物の文章を使いまわしてると思います。
英語もおかしいので正しい文章がわからず困ってます。

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
報告ありがとうございます。ゲームでは貿易ルート1レベルごとに取引所が自動的に建設されて1000人の従業員が雇われ、その貿易の利益から給料が出るため、従業員というのはそれのことを指しています。英語でも日本語と同様にemployee annuallyであるため、チーム内での議論の結果表記はこのままにすることとなりました。
