### ISSUE TITLE
破産宣告ツールチップ（急進派POPの数に関して）

### ISSUE THREAD

**Issue by AruiKashiwagi** [matanki-saito/vic3jpadvmod#474]
### スクリーンショット

![20221119164932_1b](https://user-images.githubusercontent.com/52348271/203060012-c1103bbb-1825-4584-8a69-f09e78345f0a.jpg)

### 問題のツールチップ

予算→資産タブ→破産宣告ツールチップ

### 問題の表現

「6.83K施設に影響する株式を所有していることから POPはより急進派になります」
interfaces_l_japanese.yml
```
 DECLARE_BANKRUPTCY_POP_EFFECTS:0 "#v $AMOUNT|*$#![Concept('concept_building','$concept_buildings$')]に影響する株式を所有していることから[Concept('concept_pop','$concept_pops$')]はより[concept_radical]になります"
```

### 問題箇所の英文

interfaces_l_english.yml
```
 DECLARE_BANKRUPTCY_POP_EFFECTS:0 "#v $AMOUNT|*$#! [Concept('concept_pop', '$concept_pops$')] will become more [concept_radical] due to owning shares in affected [Concept('concept_building', '$concept_buildings$')]"
```

### 希望する変更

例：「6.83K POPは、影響する施設の株式を所有していることから急進派になります」
```
 DECLARE_BANKRUPTCY_POP_EFFECTS:0 "#v $AMOUNT|*$#! [Concept('concept_pop', '$concept_pops$')]は、影響する[Concept('concept_building', '$concept_buildings$')]の株式を所有していることから[concept_radical]になります"
```

### 変更の理由（概要）

語順ミス、ゲームシステムにあわせた表現修正

### 変更の理由（詳細）

語順ミスにより、数値や言葉の掛かる先が変わってしまっている。
- POPを表すはずの数値が、施設に対して掛かっている
- 「影響する施設」のはずが、「影響する株式」になっている

また「より急進派になる」は原文のbecome more radicalの直訳ではあるが、ゲーム的には急進派であるか否かの二択しかないので、「急進派になる」と断言するべきでは。

### プレイ国家

ハワイ

### ゲームバージョン

1.1.X

### MOD有無

Japanese Language Advanced Mod, Visual Methods

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
「影響を受ける施設の株式を所有していることから、6.83KのPOPが急進派になります」
のように表示されるよう修正しました

クローズします
