### ISSUE TITLE
（コンセプト説明）人頭税

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#477]
### スクリーンショット

![image](https://user-images.githubusercontent.com/37979626/203089859-e035e0ee-4f26-45a2-a25e-2b4514126d4a.png)

### 問題のツールチップ

予算画面>人頭税マウスオーバー

### 問題の表現

それが適用される[Concept('concept_working_adults', '$concept_working_adult$')]から一律で徴収される[Concept('concept_taxes','$concept_tax$')]です。$concept_budget_poll_taxes$は$concept_pop$の収入に比例しないので、[concept_lower_strata]に最も影響を与える傾向があります。

### 問題箇所の英文
```
A flat [Concept('concept_taxes','$concept_tax$')] collected on every [Concept('concept_working_adults', '$concept_working_adult$')] it applies to. Since $concept_budget_poll_taxes$ do not scale with the $concept_pop$'s income it tends to impact the [concept_lower_strata] the most.
```
### 希望する変更

**すべての**[Concept('concept_working_adults', '$concept_working_adult$')]**に一律に適用される**[Concept('concept_taxes','$concept_tax$')]です。$concept_budget_poll_taxes$は$concept_pop$の収入に比例しない**ため**、[concept_lower_strata]に最も影響を与える傾向があります。

### 変更の理由（概要）

不自然な表現

### 変更の理由（詳細）

文頭から代名詞が入っており、日本語表現として不適当

### プレイ国家

東インド会社

### ゲームバージョン

1.0.X

### MOD有無

JapaneseLanguageAdvancedMod, Japanese Flavor, Universal Names

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
`課税対象の[Concept('concept_working_adults', '$concept_working_adult$')]から同額ずつ徴収する[Concept('concept_taxes','$concept_tax$')]です。$concept_budget_poll_taxes$は$concept_pop$の収入に比例しないため、[concept_lower_strata]に最も影響を与える傾向があります。`

**Comment by clamm0363** [comment]
上記のとおり修正しました。

クローズします
