### ISSUE TITLE
武器工場PM「鋳物工場」

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#478]
### スクリーンショット

![image](https://user-images.githubusercontent.com/37979626/203095731-acc02ca3-c194-45cd-9d9a-a0970dd4bb53.png)

### 問題の用語

鋳物工場

### 英語版の表現

Foundries

### 希望する変更

鋳造所

### 変更の理由（概要）

一般的な表現にするため

### 変更の理由（詳細）

鋳物＝製品を指すので、工場を指すには不適格

### ゲームバージョン

1.0.X

### MOD有無

JapaneseLanguageAdvancedMod, Japanese Flavor, Universal Names

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通り修正しました。
