### ISSUE TITLE
【一括修正】カートリッジ

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#479]
### スクリーンショット

![image](https://user-images.githubusercontent.com/37979626/203096710-66b016e8-ee9d-41df-9fa3-7a63cc2560b7.png)

### 問題の固有名詞：希望する変更

軍に支給される予定の新型ライフルについて、ヒンドゥー教やイスラム教でタブーとされている獣脂やラードが含まれている可能性のあるカートリッジ・グリースを使用しているとの懸念が示されました。：軍に支給される予定の新型ライフル**の薬包**について、ヒンドゥー教やイスラム教でタブーとされている獣脂やラードが含まれている可能性**があ**るとの懸念が示されました。

「カートリッジを噛んでみると、その味がわかる。戦いのさなかに、会社が最も忠実な兵士である我々の信頼を裏切るような巧妙で卑怯な方法を見つけたと知って、この上ない裏切りだと感じたのだ。もし、その男に弾を撃ち込むことができたなら、迷わずそうしただろう」：「**薬包**を噛んでみると、その味がわかる。戦いのさなかに、会社が最も忠実な兵士である我々の信頼を裏切るような巧妙で卑怯な方法を見つけたと知って、この上ない裏切りだと感じたのだ。もし、その男に弾を撃ち込むことができたなら、迷わずそうしただろう」

カートリッジの変更：**薬包**の変更
カートリッジ製作：**薬包**製作

### 変更の理由（概要）

当時の一般的呼称にするため

### 変更の理由（詳細）

カートリッジと武器の呼称を音読み・カナ表記するのは戦後の流れなので避けたい。
なお、イベント文に関しては「カートリッジ・グリース（cartridge grease）」が馴染みのない言葉なので避けつつ、自然な表現になるよう修正を加えた。

### ゲームバージョン

1.0.X

### MOD有無

JapaneseLanguageAdvancedMod, Japanese Flavor, Universal Names

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通り修正しました。
