### ISSUE TITLE
【修正提案】Peasant Levies

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#48]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![Peasant_Levies](https://user-images.githubusercontent.com/50406316/198100700-1a529cf1-f602-4895-9907-6da4b510b46e.png)

## 問題の用語（必須）
農民徴兵
軍隊の主力は、基礎訓練を受けていない徴兵制の歩兵です。

## 英語版の表現（任意）
Peasant Levies
The army's main force comes from conscripted infantry with zero to basic training.

## 希望する変更（必須）
農民召集兵
軍隊の主力は、全く基礎訓練を受けていない召集兵です。

## 変更の理由（必須）
こちらはLevyで、下にある大規模徴兵（Mass Conscription）と訳し分けたい。
意味合い的にも、制度化された徴兵ではなく、臨時で召集される農民を指していると思われるため。

## ゲームバージョン（必須）
1.0.3

## DLC有無（必須）
無し

## MOD有無（必須）
なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1034888155863724132
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by starjard** [comment]
提案通り修正しました
