### ISSUE TITLE
$TAB$のバグ

### ISSUE THREAD

**Issue by clamm0363** [matanki-saito/vic3jpadvmod#480]
### スクリーンショット

![image](https://user-images.githubusercontent.com/29382778/203099061-6c7c7b4c-5491-420f-94c4-c741cfc8b386.png)

### 問題のツールチップ

$TAB$が使われているツールチップ全般

### 問題の表現

$TAB$で呼ばれるインデントが機能していない

### 問題箇所の英文

   
（半角スペース3つ）

### 希望する変更

英語版同様に「半角スペース3つ」とする

### 変更の理由（概要）

様々なツールチップのレイアウトが崩れているため

### 変更の理由（詳細）

$TAB$が使われている様々なツールチップのレイアウトが崩れているため

### プレイ国家

NONE

### ゲームバージョン

1.0.X

### MOD有無

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
英語版に倣い、[半角スペース３つ」として修正しました。

クローズします。
