### ISSUE TITLE
主要文化POPの説明

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#482]
### スクリーンショット

![primary_ja](https://user-images.githubusercontent.com/50406316/203199276-21cdfecb-8a2d-4c4c-8c6e-1709992b2668.png)
![primary_en](https://user-images.githubusercontent.com/50406316/203199282-8b43d9bb-6f06-4ecf-9377-2390445562ff.png)

### 問題のツールチップ

主要文化POPが常に受容されることの説明

### 問題の表現

当POPは（市民権法名）に所属するため、常に受容されます
当POPは[Pop.GetCountry.GetActiveLawFromGroup('lawgroup_citizenship').GetName]に所属するため、常に受容されます

### 問題箇所の英文

As this Pop is of the Primary Culture they will always be Accepted
As this Pop is of the [Concept('concept_primary_cultures','$concept_primary_culture$')] they will always be Accepted

### 希望する変更

当POPは主要文化に所属するため、常に受容されます
当POPは[Concept('concept_primary_cultures','$concept_primary_culture$')]に所属するため、常に受容されます

### 変更の理由（概要）

原文と変数が違っているミスの修正

### 変更の理由（詳細）

原文では[Concept('concept_primary_cultures','$concept_primary_culture$')]（主要文化）を呼び出す変数を使っているが、日本語では[Pop.GetCountry.GetActiveLawFromGroup('lawgroup_citizenship').GetName]（現在の市民権法）の変数を使っているミスのため、原文通りの変数に修正したい。

### プレイ国家

どの国でも

### ゲームバージョン

1.0.X

### MOD有無

翻訳改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
提案通り修正しました。
