### ISSUE TITLE
輸送船沈没時のフィード

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#483]
### スクリーンショット

![20221121225950_1](https://user-images.githubusercontent.com/42710893/203282765-20bbf05b-74de-44c3-a92a-43b62c7ba304.jpg)

### 問題のあるインターフェイス

輸送船沈没時のフィード

### 問題のテキスト

notification_our_convoys_raided_desc:0 "敵対[concept_admiral]が#v 我が国の[concept_convoys]である[SCOPE.GetRootScope.GetCharacter.GetLastConvoyRaidingDamageTo(SCOPE.sCountry('target').Self)]#!を撃沈しました。攻撃のあった海域は次のいずれかであると考えられます: [SCOPE.GetRootScope.GetCharacter.GetSeaNodesMightBeConvoyRaidingInDesc(SCOPE.sCountry('target').Self)]"

英語版：
"A hostile [concept_admiral] sunk #v [SCOPE.GetRootScope.GetCharacter.GetLastConvoyRaidingDamageTo(SCOPE.sCountry('target').Self)]#! of our [concept_convoys]. We think the attack happened in one of these Sea Zones: [SCOPE.GetRootScope.GetCharacter.GetSeaNodesMightBeConvoyRaidingInDesc(SCOPE.sCountry('target').Self)]"
### 希望する変更

notification_our_convoys_raided_desc:0 "敵の[concept_admiral]が#v 我が国の[concept_convoys]を[SCOPE.GetRootScope.GetCharacter.GetLastConvoyRaidingDamageTo(SCOPE.sCountry('target').Self)]隻撃沈#!しました。攻撃のあった海域は次のいずれかであると考えられます: [SCOPE.GetRootScope.GetCharacter.GetSeaNodesMightBeConvoyRaidingInDesc(SCOPE.sCountry('target').Self)]"　等

### 変更の理由（概要）

日本語として不自然なため

### ゲームバージョン

1.0.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
すみません、システムから通知が漏れていたため確認が遅れました 🙇

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
タグの位置だけ微修正しましたが、そのほかはご提案どおり修正しました。

クローズします。
