### ISSUE TITLE
法の進歩フィード

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#484]
### スクリーンショット

![20221121221915_1](https://user-images.githubusercontent.com/42710893/203302263-14d9395e-0e26-457a-871b-7b69d879400a.jpg)
![20221121221906_1](https://user-images.githubusercontent.com/42710893/203302284-e5e42e40-21f4-4065-a6ab-2425ac93ff20.jpg)

### 問題のあるインターフェイス

法の進歩フィード

### 問題のテキスト

notification_law_notification_debate_fail_desc:0 "[SCOPE.sLaw('current_law_scope').GetName]は公開討論で悪い結果を残し、[concept_enactment_success]が10%低下しました。"

### 希望する変更

[concept_enactment_success]で呼ばれているconcept_enactment_success:1の訳が「制定成功」となっているのを「制定成功率」としたい
スクショの2枚目の説明を見る限り確率を示す用語なので、制定成功率の方が適当と思われるが、他の部分に影響しないか要検討

### 変更の理由（概要）

日本語として不自然なため

### ゲームバージョン

1.0.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
報告ありがとうございます。ご提案の制定成功率に加えて、制定前進率、制定引き延ばし率、制定論争率も同様に「率」を加えました。なお別のエントリでは既に「率」とが付いているものが一部存在したため、「制定前進率率」みたいにならないように重複する率表記を削ることも行っています。
