### ISSUE TITLE
【実績】メキシコ宣言 / Manifest Mexico

### ISSUE THREAD

**Issue by ikabomb** [matanki-saito/vic3jpadvmod#485]
### スクリーンショット

![image](https://user-images.githubusercontent.com/84853597/203328083-752eebf0-309d-4e90-8428-e733a8ec621b.png)

### 問題の用語

メキシコ宣言

### 英語版の表現

Manifest Mexico

### 希望する変更

明白なるメキシコ

### 変更の理由（概要）

Manifest Distiny(明白なる天命)に引っ掛けているが、訳はそのようになっていないため

### ゲームバージョン

1.0.X

### MOD有無

JapaneseLanguageAdvancedMod

**Comment by ikabomb** [comment]
というか、これManifestoじゃなくてManifestなので普通に誤訳かもです

**Comment by oooFUNooo** [comment]
議論の結果、マニフェスト・メキシコに決定し修正を完了しました。
