### ISSUE TITLE
外交関係の評価用語　一括修正

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#486]
### スクリーンショット

![20221123000913_1](https://user-images.githubusercontent.com/43299334/203352434-2bd639b7-ca0f-4088-90ce-5181007eed02.jpg)
![20221123000914_1](https://user-images.githubusercontent.com/43299334/203352444-0b15a47f-cac8-4997-baae-732f0d81fc1b.jpg)
![20221123000920_1](https://user-images.githubusercontent.com/43299334/203352452-a97b8123-fad8-48e9-86a0-e21b7aa8fb46.jpg)
![20221123000922_1](https://user-images.githubusercontent.com/43299334/203352468-90e0e8e9-098f-4121-946f-284efe200aa8.jpg)

### 問題の用語

親しみ/友好/親愛/中立/不信/冷淡/敵対

### 英語版の表現

Friendly/Amicable/Cordial/Neutral/Poor/Cold/Hostile

### 希望する変更

親愛/友好/信用/（以降は原案のまま）

### 変更の理由（概要）

レベルが分かりにくいため

### 変更の理由（詳細）

関係値の高い順に並んでいる。しきい値は
80/50/20/-20/-50/-80

### ゲームバージョン

1.0.X

### MOD有無

日本語改善MOD、日本語フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
親愛/友好/信用/（以降は原案のまま）で修正
