### ISSUE TITLE
JCP→日本共産党

### ISSUE THREAD

**Issue by nagi0330** [matanki-saito/vic3jpadvmod#487]
### スクリーンショット

![20221123003153_1](https://user-images.githubusercontent.com/6514922/203354871-e8465539-afe3-4dc6-9b4b-94bfdc925eea.jpg)

### 問題の固有名詞：希望する変更

JCP:日本共産党

### 変更の理由（概要）

日本語では一般的でない

### ゲームバージョン

1.0.X

**Comment by clamm0363** [comment]
ご提案のJCP→日本共産党を含め、大半の略称政党名について翻訳を行う修正を実施しました。

クローズします
