### ISSUE TITLE
アメリカ南北戦争

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#489]
### スクリーンショット

なし

### 問題の固有名詞：希望する変更

アメリカ南北戦争：南北戦争

### 変更の理由（概要）

日本語では一般的ではない表記であるため

### ゲームバージョン

1.0.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
原案の通り修正を完了しました。
