### ISSUE TITLE
【修正提案】Debt Slavery

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#49]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![Debt_Slavery](https://user-images.githubusercontent.com/50406316/198101293-58ea8c09-57bf-49a5-98d9-e596fed3d3c9.png)

## 問題の用語（必須）
役身折酬

## 英語版の表現（任意）
Debt Slavery

## 希望する変更（必須）
債務奴隷

## 変更の理由（必須）
役身折酬は古代史用語で一般に使用する用語ではないため、より一般的な名称の債務奴隷としたい。

## ゲームバージョン（必須）
1.0.3

## DLC有無（必須）
無し

## MOD有無（必須）
なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1034889214816432129
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by starjard** [comment]
提案通り修正しました
