### ISSUE TITLE
ジャーナル：覇権国の完了条件

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#492]
### スクリーンショット

![20221117181758_1](https://user-images.githubusercontent.com/42710893/203501581-fd4b2d87-6e64-4611-9efa-0faeeda7cc55.jpg)

### 問題のツールチップ

ジャーナル：覇権国の完了条件

### 問題の表現

``` je_the_hegemon_final_tt:0 "世界の$concept_population$.の半分を支配。"```

### 問題箇所の英文

```je_the_hegemon_final_tt:0 "Control half of the global $concept_population$."```

### 希望する変更

 ```je_the_hegemon_final_tt:0 "世界の$concept_population$の半分を支配"```

### 変更の理由（概要）

不要な「.」の削除、最後の句点も不要と思われる

### プレイ国家

イタリア

### ゲームバージョン

1.0.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
「世界人口の半分を支配している」となるように修正しました。

クローズします
