### ISSUE TITLE
威信(バニラの訳：国威 英語：Prestige)の内訳が確認できない

### ISSUE THREAD

**Issue by Jizouyakusi** [matanki-saito/vic3jpadvmod#493]
### スクリーンショット

![20221123172116_1](https://user-images.githubusercontent.com/7272398/203500979-1d057ce3-9672-4eae-ad2a-2394b83d8aa6.jpg)

### 問題のツールチップ

国のランクアイコン or 威信数値にマウスオンした際に出る「ランク」のツールチップ

### 問題の表現

「現在の威信：1100」の数字の箇所にマウスカーソルを合わせると、バニラでは威信の内訳が表示されますが、
日本語改善MODを適用した状態だと表示されません

### 問題箇所の英文

Current Prestige:1100

### 希望する変更

威信の内訳のツールチップが表示される
（技術的なことにはわからないので、どう修正すれば治るのかはわかりません、申し訳ありません）

### 変更の理由（概要）

威信の内容が確認できずプレイに支障があるため

### プレイ国家

フランス

### ゲームバージョン

1.0.X

### MOD有無

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
確認しました。
日本語改善MODはスペースによる意図しない改行を可能な限り排除しているのですが、恐らくそのせいでこの問題が発生しており、本来は国旗の後ろのスペースで改行されるのが無くなったのが問題を引き起こしているように見えます。
一旦下記のようにスペースを意図して入れて改行させることで、この問題を解決しようとは思いますが、恐らく他にも同様の問題が起きている可能性が高いです。
また見つけましたらお手数ですが起票をお願い致します mm
![image](https://user-images.githubusercontent.com/35730970/203795156-a46b58c3-d366-40d8-8ede-da3fa6678620.png)

**Comment by matanki-saito** [comment]
修正を完了したためClose致します
