### ISSUE TITLE
ボーア人国家の名前

### ISSUE THREAD

**Issue by TdHskw** [matanki-saito/vic3jpadvmod#495]
### スクリーンショット

![name](https://user-images.githubusercontent.com/108180041/203541726-e2fc5709-9be2-4280-b802-632113a09023.jpg)

### 問題の固有名詞：希望する変更

オラニエ：オレンジ
トランスヴァール：トランスヴァール（変更なし）
または
オラニエ：オラニエ（変更なし）
トランスヴァール：トランスファール

### 変更の理由（概要）

英語読み（またはオランダ語読み）での統一

### 変更の理由（詳細）

オラニエがオランダ語読み、トランスヴァールが英語読みなのは不揃いなので、どちらかに統一させたい。
トランスファールというのはなじみが無い名前なので、どちらかといえば英語読みを希望。

### ゲームバージョン

1.0.X

### MOD有無

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
原案通り英語読みで統一することに決定しました。
具体的には、オラニエをオレンジに修正し、トランスヴァールはそのまま変更せずに残しています。
