### ISSUE TITLE
ゲームルール「ファンタジー風国家」

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#497]
### スクリーンショット

![20221123213317_1](https://user-images.githubusercontent.com/43299334/203584396-7951dffc-26c7-465b-9ac7-7e0d1a211d43.jpg)
![20221123213318_1](https://user-images.githubusercontent.com/43299334/203584410-9f7a8e30-6702-4099-a118-a25a430073f8.jpg)

### 問題の用語

非現実的なファンタジー風国家の形成を可能にします

### 英語版の表現

Allow implausible and fantasy-esque nations to be formed

### 希望する変更

非現実的、空想的な国家の形成を可能にします

### 変更の理由（概要）

誤解を生む表現のため

### 変更の理由（詳細）

ゲームルールにおける国家の形成、解放の制限に関する設定項目。
「ファンタジー風」と書いてあるが一般的に日本でイメージされるファンタジーの要素を含んだ国家というわけではなく、単純に形成/解放が現実的ではない、架空の国家のことをさしている。

### ゲームバージョン

1.0.X

### MOD有無

日本語改善MOD、日本語フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
非現実的、空想的な～　で修正しました
