### ISSUE TITLE
throughputの表記ゆれ統一

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#498]
### スクリーンショット

![throughput_en](https://user-images.githubusercontent.com/50406316/203769260-b877c49e-accf-41c6-9533-ddd98db17091.png)
![throughput_en2](https://user-images.githubusercontent.com/50406316/203769272-bcce6946-3248-4910-9243-9caeb3db532d.png)
![throughput_viki](https://user-images.githubusercontent.com/50406316/203769429-98d12127-9a7d-4858-9e59-1187af19cdb6.png)

### 問題の用語

処理量、生産量

### 英語版の表現

throughput

### 希望する変更

処理量

### 変更の理由（概要）

表記ゆれの統一

### 変更の理由（詳細）

throughputは規模ボーナスや植民地搾取などで獲得できるボーナスで、施設の消費量と産出量が同じ割合だけ増加する。
処理量と生産量で表記ゆれをしているので統一したい。
生産量はProductionの訳語で使ってしまっていて重複するうえに、消費量が増える効果が名前からは分かりにくいため、処理量としたい。
なおvikiのthroughputの説明文もぎこちない日本語なので、こちらは別のissueで改訳を起票します。

### ゲームバージョン

1.0.X

### MOD有無

翻訳改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
処理量に統一させました。

**Comment by starjard** [comment]
報告ありがとうございます。#498で同じissueを決定しているため、同様にこちらも改訳して用語統一させました。
