### ISSUE TITLE
throughputのvikipedia説明

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#499]
### スクリーンショット

![throughput_viki](https://user-images.githubusercontent.com/50406316/203770336-dfca2028-9658-40a3-882d-29be04d6189b.png)

### 問題部分

本文

### 問題のイベントタイトル

throughput

### 問題のイベント本文（抜粋可）

[施設]の[労働者]が[商品流入量]を[商品流出量]などにどれだけ効果的に変化できるかを示すものです。[throughput]は、[規模の経済]の結果によって増加することも、[補正]によって上下に調整されることもあります。

How effectively the [workforce] of a [building] can turn [input_goods] into [output_goods] or other effects. [throughput] can increase as a result of [economy_of_scale], and might be adjusted up or down due to [modifiers].

※[ ]内は変数

### 希望する変更（修正部分のみ）

[施設]の[労働者]が[商品流入量→原料]をもとに[商品流出量→生産物]を製造する効率性を示すものです。[throughput]は[規模の経済]や[補正]などによって上下するでしょう。

※[商品流入量→原料]と[商品流出量→生産物]の変更は別issueで起案

### 変更の理由（概要）

不自然な文章の改訳

### 変更の理由（詳細）

変数に対応した文章になっておらず、日本語が不自然なので改訳したい。

### プレイ国家

指定なし

### ゲームバージョン

1.0.X

### MOD有無

翻訳改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
提案通り改訳しました。
