### ISSUE TITLE
【修正提案】Motor Industries

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#50]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![Motor_Industries](https://user-images.githubusercontent.com/50406316/198104870-84c7fc49-17ec-4fd9-ba41-f746bf6432eb.png)

## 問題の用語（必須）
自動車産業

## 英語版の表現（任意）
Motor Industries

## 希望する変更（必須）
発動機産業

## 変更の理由（必須）
誤訳。生産物はEngines（発動機）であり、画像で作っているのも機関車であるため。

## ゲームバージョン（必須）
1.0.3

## DLC有無（必須）
無し

## MOD有無（必須）
なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1034894088442482728
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by starjard** [comment]
提案通り修正しました
