### ISSUE TITLE
Input/Output Goods

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#500]
### スクリーンショット

![throughput_viki](https://user-images.githubusercontent.com/50406316/203775086-b9479297-ee11-4644-a331-f917babff3a4.png)

### 問題の用語

商品流入量、商品流出量

### 英語版の表現

Input/Output Goods、~~Goods Input/Goods Output~~
※11/25追記 Goods Input/Goods Outputは対象から除外

### 希望する変更

原料、生産物

### 変更の理由（概要）

誤訳の修正

### 変更の理由（詳細）

vikiのコンセプト用語で、施設で生産するための原料と生産物のこと。InputのほうはInput Goods Shortageがすでに原料不足と訳されているので合わせたい。Outputのほうは生産物とする。

### ゲームバージョン

1.0.X

### MOD有無

翻訳改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
提案通り変更しました。
