### ISSUE TITLE
独立に関するハイチへの支払い

### ISSUE THREAD

**Issue by mochi115** [matanki-saito/vic3jpadvmod#501]
### スクリーンショット

![image](https://user-images.githubusercontent.com/117048815/203809664-ebf7379c-a18b-4eb1-bd73-3d479d9ec75c.png)

### 問題のツールチップ

フランスの補正

### 問題の表現

独立に関するハイチへの支払い

### 希望する変更

独立に関するハイチの支払い

### 変更の理由（概要）

誤訳

### 変更の理由（詳細）

賠償金を支払っているのはハイチであるから

### ゲームバージョン

1.0.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
「ハイチの独立賠償金」で修正することになりました。起票ありがとうございました。
