### ISSUE TITLE
貸付歩合

### ISSUE THREAD

**Issue by mochi115** [matanki-saito/vic3jpadvmod#502]
### スクリーンショット

![スクリーンショット (8)](https://user-images.githubusercontent.com/117048815/203815516-65112d86-ee2a-4666-b7a6-a350c8e28fa2.png)
![スクリーンショット (16)](https://user-images.githubusercontent.com/117048815/203815558-f8b0a466-285f-4d2b-9b7a-6a0b7ea2d3f6.png)

### 問題の用語

貸付歩合

### 英語版の表現

Loan Interest Rate

### 希望する変更

利子率

### 変更の理由（概要）

表現の修正

### 変更の理由（詳細）

借入利率にする案もありましたが、利子率に補正をかけるため分かりやすさを重視して利子率としました

### ゲームバージョン

1.0.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
提案ありがとうございます。「利子率」の提案は採用しつつも、既に存在する「interest rate/利子率」との訳語被りを避けるため、こちらはLoanを訳出して「借入利子率」とすることにしました。

**Comment by mochi115** [comment]
![20221201192212_1](https://user-images.githubusercontent.com/117048815/205029131-1de8f6f7-093f-49b9-be23-aa1848570404.jpg)
Loan interest RateはInterest Rateを増減させるため訳語が被っていても問題ないと思います。分けてしまうより統一してしまった方が分かりやすいかと思い提案させていただきました。
