### ISSUE TITLE
執着するする

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#503]
### スクリーンショット

![image](https://user-images.githubusercontent.com/37979626/203830248-b13a5320-0b6b-483c-9ec0-724571c88844.png)

### 問題の用語

concept_obsessed　執着する

### 英語版の表現

Obsessed

### 希望する変更

執着

### 変更の理由（概要）

誤訳

### 変更の理由（詳細）

コンセプト変数の後に「する」が補われているため、「（執着）する」「する」と被ってしまっている

### ゲームバージョン

1.0.X

### MOD有無

JapaneseLanguageAdvancedMod, Japanese Flavor, Universal Names

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通り修正しました。
