### ISSUE TITLE
制度の投資レベルが上がった時のフィード（#issue451での修正分）

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#504]
### スクリーンショット

![20221124230306_1](https://user-images.githubusercontent.com/42710893/203936330-bb834176-f36f-4ef4-8b1a-847651016e21.jpg)

### 問題のあるインターフェイス

制度の投資レベルが上がった時のフィード

### 問題のテキスト

[レベル]制度への投資がレベル[制度名]に増加しました

### 希望する変更

[制度名]制度への投資がレベル[レベル]に増加しました

### 変更の理由（概要）

変数が逆になっている

### 変更の理由（詳細）

issue#451で翻訳が修正された分ですが、[SCOPE.GetRootScope.GetInstitution.GetName]と[SCOPE.GetRootScope.GetInstitution.GetInvestmentLevel|v]の位置が逆になっていると思われます。
レベルが低下した場合notification_institution_investment_decreased_desc:0も同様に修正が必要と思われます。

### ゲームバージョン

1.0.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
報告ありがとうございます。修正ミスだったため、あらためて正しく直しました。
