### ISSUE TITLE
キャラクターが役割を複数持つ場合の表記

### ISSUE THREAD

**Issue by ikabomb** [matanki-saito/vic3jpadvmod#505]
### スクリーンショット

![image](https://user-images.githubusercontent.com/84853597/203993795-f1208f1e-623e-4aec-9fa2-3fe8b6d03ba3.png)

### 問題の用語

提督と政治家

### 希望する変更

提督にして政治家

### 変更の理由（概要）

日本語の用法上自然になるため

### 変更の理由（詳細）

彼の役割は提督と政治家である v 彼は提督にして政治家である　のどちらの文として補うのか、という話になるはずですが、前者は日本語における人間の描写としてはあまり見られないかと思います

### ゲームバージョン

1.0.X

### MOD有無

JapaneseLanguageAdvancedMod

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
（この修正はANDキー、およびAND_LISTキーに対して行われました）
