### ISSUE TITLE
大政奉還後日本の「皇帝」

### ISSUE THREAD

**Issue by aramoiukon** [matanki-saito/vic3jpadvmod#506]
### スクリーンショット

![Victoria 3 令和4年11月18日 7_25_45](https://user-images.githubusercontent.com/117195163/204062136-3dd74467-f81a-48a2-9c5f-08a0e35bf711.png)

### 問題部分

本文

### 問題のイベントタイトル

明治維新

### 問題のイベント本文（抜粋可）

1.皇帝明治が…
2.皇帝は政治的同盟者を…

### 希望する変更（修正部分のみ）

1.明治天皇が
2.天皇は政治的同盟者を

### 変更の理由（概要）

「天皇」が一般的だから

### ゲームバージョン

1.0.X

### MOD有無

日本語改善MOD 他UI変更系多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by aramoiukon** [comment]
他にイベント「皇帝が、政治的プロセスに介入」のタイトルと本文の「皇帝」を「天皇」に、選択肢の「皇帝の仰せのままに！」の方はセリフっぽい言い回しを踏まえて「陛下」とかに改めたほうがいいと思うんですが、別個起票したほうがいいですか？

**Comment by matanki-saito** [comment]
それらの「皇帝」はゲームが統治者の呼称を変数として動的に引用している可能性が高いです。その場合、もとの「皇帝」を「天皇」に修正すると、ヨーロッパなどの皇帝もすべて天皇になってしまいます。詳しく調査しますので結果をお待ちください。

**Comment by inarizushi0309** [comment]
こちら「皇帝」名称はいじらず、イベント本文のみの修正に留めることになりました。以下修正版
```佐幕派の権力は失墜し、王政復古がなされました。この重要な出来事は、日本における何世紀もの幕府支配の終わりを示し、近代化と改革の新しい時代の到来を告げています。天皇は政治的同盟者を慎重に選択する必要があります。```
```[SCOPE.gsInterestGroup('shogunate_ig').GetName]の権力は失墜し、王政復古がなされました。この重要な出来事は、[ROOT.GetCountry.GetName]における何世紀もの幕府支配の終わりを示し、近代化と改革の新しい時代の到来を告げています。天皇は政治的同盟者を慎重に選択する必要があります。```
