### ISSUE TITLE
哲学的プラグマティズム（Philosophical Pragmatism）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#507]
### スクリーンショット

![20221126085437_1](https://user-images.githubusercontent.com/42687608/204063990-14657856-9791-488b-b745-677e42184082.jpg)

### 問題の用語

哲学的プラグマティズム

### 英語版の表現

Philosophical Pragmatism

### 希望する変更

プラグマティズム

### 変更の理由（概要）

日本語として冗長な表現

### 変更の理由（詳細）

原文は日常英語の「現実的な、実用的な」という意味と区別するため、PragmatismにPhilosophicalを補っていると考えられる。
しかし、日本語で「プラグマティズム」と書く場合は哲学用語であることがほとんどなので、Philosophicalを「哲学的」と訳出するのは冗長である。

### ゲームバージョン

1.0.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
議論の結果、「実用主義」と修正しました。

クローズします。
