### ISSUE TITLE
財産を持つ女性（Propertied Women）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#508]
### スクリーンショット

![20221126090400_1](https://user-images.githubusercontent.com/42687608/204064367-702c6f72-1f55-436d-b5f6-1eca1f2e39f6.jpg)

### 問題の用語

財産を持つ女性

### 英語版の表現

Propertied Women

### 希望する変更

女性の財産権

### 変更の理由（概要）

法律名として不自然な表現

### 変更の理由（詳細）

翻訳としては間違っていないが、法律の名前なので法律用語をあてたい。
調べたところ、同等の意味を持つ「女性の財産権」というキーワードがGoogleの「完全一致検索」で86万件ヒットした。

### ゲームバージョン

1.0.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
原案の通りに確定し、修正を完了しました。
