### ISSUE TITLE
「公務員」のツールチップ上の誤字

### ISSUE THREAD

**Issue by aramoiukon** [matanki-saito/vic3jpadvmod#509]
### スクリーンショット

![Victoria 3 令和4年11月21日 10_52_09](https://user-images.githubusercontent.com/117195163/204065239-80f0f79a-1f4d-49a1-8b56-c16c5a8dd57e.png)

### 問題のツールチップ

人口メニューの詳細一覧タブの公務員のツールチップ

### 問題の表現

1.…政治的には知識人や少ブルジョアに属する傾向があります。…

2…。.識字率とが大きいほど、…

### 希望する変更

1.…政治的には知識人や小ブルジョワに属する傾向があります。…

2…。.識字率が大きいほど、…

### 変更の理由（概要）

恐らく誤字

### ゲームバージョン

1.0.X

### MOD有無

日本語改善MOD 他UI変更系多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by discordine** [comment]
識字率とが〜については聖職者のツールチップでも発生してたので合わせて修正
