### ISSUE TITLE
【typo】イベント「ゴムの隆盛」の未変換箇所

### ISSUE THREAD

**Issue by 30denarius** [matanki-saito/vic3jpadvmod#51]
## スクリーンショット（任意）

![20221027050829_1](https://user-images.githubusercontent.com/105610712/198126937-df64cd21-d2d8-4137-ae50-a6e8f8300f3e.jpg)

##　問題部分（タイトル・本文・選択肢）

○○にてゴム栽培にせいこうしました。（後略）

## 問題のイベントタイトル（必須）

ゴムの隆盛

## 問題のイベント本文（任意・抜粋可）

○○にてゴム栽培にせいこうしました。（後略）

## 希望する変更（必須・修正部分のみ）

○○にてゴム栽培に成功しました。

## 変更の理由（必須）

変換されていないと気になります

## プレイ国家

イギリス

## ゲームバージョン（必須）

1.0.1

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1034923513552846950
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by clamm0363** [comment]
「せいこうしました」を「成功しました」と修正しました。
