### ISSUE TITLE
◯◯の戦闘（Battle in, Battle for, Battle near）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#510]
### スクリーンショット

![20221126092249_1](https://user-images.githubusercontent.com/42687608/204065434-b3350339-4fa3-4dc9-9fd2-1494a9d538ca.jpg)

### 問題のあるインターフェイス

戦闘ウィンドウ

### 問題のテキスト

◯◯の戦闘（都市以外が戦場の場合）
◯◯での戦闘（都市が戦場の場合）
◯◯付近での戦闘（都市周辺が戦場の場合）

### 希望する変更

◯◯の戦い（都市が戦場の場合）
◯◯攻防戦（都市が戦場の場合）
◯◯近郊の戦い（都市周辺が戦場の場合）

### 変更の理由（概要）

定訳とは異なる表現

### 変更の理由（詳細）

歴史的な戦闘に対する日本語の定訳は「◯◯の戦い」であり、ゲームの没入感を高めるためには修正が必要である。

| キー | 原文 | 現在の訳 | 修正案 |
| --- | --- | --- | --- |
| BATTLE_IN | `Battle in $STATE_REGION_NAME$` | `$STATE_REGION_NAME$の戦闘` | `$STATE_REGION_NAME$の戦い` |
| BATTLE_FOR | `Battle for $CITY_NAME$` | `$CITY_NAME$での戦闘` | `$CITY_NAME$攻防戦` |
| BATTLE_NEAR | `Battle near $CITY_NAME$` | `$CITY_NAME$付近での戦闘` | `$CITY_NAME$近郊の戦い` |

### ゲームバージョン

1.0.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
以下の通り修正を完了しました。

◯◯の戦い（都市以外が戦場の場合）
◯◯攻防戦（都市が戦場の場合）
◯◯郊外の戦い（都市周辺が戦場の場合）
