### ISSUE TITLE
不自然な戦線名（◯◯ ✕✕戦線）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#511]
### スクリーンショット

![20221126092325_1](https://user-images.githubusercontent.com/42687608/204066101-d3d91822-1659-4358-b886-e3659cd6b0f3.jpg)

### 問題の用語

◯◯ ✕✕戦線

### 英語版の表現

◯◯ ✕✕ Front

### 希望する変更

◯◯〜✕✕戦線

### 変更の理由（概要）

日本語として不自然な表現

### 変更の理由（詳細）

現在は戦線を構成する2つの地域の名前が半角スペースでつながっており、読みにくい上に日本語として不自然である。
これを改善するため、半角スペースを「〜」「＝」などの記号に置き換える（「・」は地名に用いられるため使えない）。

関連するキーは以下の2つ。コマンドを利用して条件分岐しているため、内容を理解した上で修正する必要がある。
FRONT_NAME_FORMAT
FRONT_TWO_PART_NAME_FORMAT

### ゲームバージョン

1.0.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
原案のとおりに確定しました。
