### ISSUE TITLE
引き伸ばし（Stall）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#512]
### スクリーンショット

![20221126094622_1](https://user-images.githubusercontent.com/42687608/204066382-ceb7e63d-4ee5-48d1-a8a0-f8b29025aa8e.jpg)

### 問題の用語

引き伸ばし

### 英語版の表現

Stall

### 希望する変更

後退

### 変更の理由（概要）

実際のゲームメカニズムと異なっている

### 変更の理由（詳細）

実際のゲームでは「法律の制定時、成功率が減る」という効果であり、翻訳が正確でない。
成功率が増えるAdvanceが「前進」と訳されていることから「後退」と訳すのが妥当である。

### ゲームバージョン

1.0.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
原案の通りに確定し、修正を完了しました。
