### ISSUE TITLE
急進派（Radical）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#513]
### スクリーンショット

![20221126100126_1](https://user-images.githubusercontent.com/42687608/204066635-2a5a5a85-81be-4a10-84d1-50d5d1f79559.jpg)

### 問題の用語

急進派

### 英語版の表現

Radical

### 希望する変更

急進主義者（イデオロギーの場合のみ）

### 変更の理由（概要）

同じ用語の重複

### 変更の理由（詳細）

体制派と対になるRadicalと、イデオロギーのひとつであるRadicalが同じ「急進派」と訳されており、区別がつかないため。
原文でも同じ単語であるが、多義的な意味を持つと考え、イデオロギーの方を「急進主義者」と訳しわける。

### ゲームバージョン

1.0.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
議論の結果「急進主義者」と修正しました。

クローズします。
