### ISSUE TITLE
人口（Population）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#514]
### スクリーンショット

![20221126100645_1](https://user-images.githubusercontent.com/42687608/204066804-1db4fce8-aff3-444b-8853-a823d51626e6.jpg)

### 問題の用語

人口

### 英語版の表現

Population

### 希望する変更

民衆、国民、人民など

### 変更の理由（概要）

実際のゲームメカニズムと異なっている

### 変更の理由（詳細）

「人口」とは人の数のことであり、ゲームにおけるPOPとは意味合いが異なる。
本来は「同じ特徴を共有する集団」という意味の訳語をあてるべきであるが、適当な日本語が思いつかないので次善の策として人数ではなく人間を表す単語をあてる。

### ゲームバージョン

1.0.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。
