### ISSUE TITLE
浪費税額（Tax Waste）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#515]
### スクリーンショット

![20221126101547_1](https://user-images.githubusercontent.com/42687608/204067023-c3f3d34c-fe38-4a20-8fba-6fb36902a0ab.jpg)

### 問題のあるインターフェイス

行政力のポップアップウィンドウ（画面左上）

### 問題のテキスト

浪費税額

### 希望する変更

税の無駄遣い、税の浪費など

### 変更の理由（概要）

紛らわしい表現

### 変更の理由（詳細）

現在の「浪費税額」は「消費税額」と文字が似ており、プレイヤーの誤解を招くため。

### ゲームバージョン

1.0.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
議論の結果、「税の浪費率」と修正しました。

クローズします。
