### ISSUE TITLE
元政治家◯◯が死亡しました

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#516]
### スクリーンショット

![20221126102937_1](https://user-images.githubusercontent.com/42687608/204067359-ad2c0a5f-a955-4171-a231-9e22c4aa29ac.jpg)

### 問題のあるインターフェイス

画面右下の通知

### 問題のテキスト

元政治家◯◯が死亡しました。

### 希望する変更

政治家◯◯が死亡しました。

### 変更の理由（概要）

日本語として不自然な表現

### 変更の理由（詳細）

原文は「Former xxx xxxxxx has died.」であり、直訳としては間違っていない。
しかし、日本語では死亡した人物の肩書に「元」をつける習慣はなく、「元」をつけるとかえって不自然である。
なお、「政治家」の部分は将軍など他の役割に動的に変わる。

### ゲームバージョン

1.0.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
議論の結果、「[役職]の[人名]が死亡しました。」と修正しました。

クローズします。
