### ISSUE TITLE
人口タブ：移住求心力のツールチップ

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#517]
### スクリーンショット

![20221125223030_1](https://user-images.githubusercontent.com/42710893/204072958-a1dbc949-659d-4b9e-b979-52d8e912b706.jpg)

### 問題のツールチップ

人口タブ：移住求心力のツールチップ

### 問題の表現

TOOLTIP_STATE_MIGRATION_PULL_DESC:1 "#header [concept_migration_pull]#!\n$TOOLTIP_DELIMITER$\n[State.GetName]が#v [State.GetMigrationPull|1]#!を[concept_migration_pull]する要因: \n$DETAILS$\n[State.GetMigrationDetailsDesc]"

### 問題箇所の英文

TOOLTIP_STATE_MIGRATION_PULL_DESC:1 "#header [concept_migration_pull]#!\n$TOOLTIP_DELIMITER$\nThe [State.GetName] [concept_migration_pull] of #v [State.GetMigrationPull|1]#! is due to:\n$DETAILS$\n[State.GetMigrationDetailsDesc]"

### 希望する変更

"#header [concept_migration_pull]#!\n$TOOLTIP_DELIMITER$\n[State.GetName]の[concept_migration_pull]が#v [State.GetMigrationPull|1]#!である要因: \n$DETAILS$\n[State.GetMigrationDetailsDesc]"

### 変更の理由（概要）

日本語として不自然なため

### ゲームバージョン

1.0.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
ご提案どおり修正しました

クローズします
