### ISSUE TITLE
【修正提案】外交プレイ

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#52]
＜ゲームシステム用語＞

## スクリーンショット（任意）

![20221027064418_1](https://user-images.githubusercontent.com/43299334/198144579-8ff5b7d1-d1d8-4f08-b4ca-b953eb5bd865.jpg)

## 問題の用語（必須）

外交プレイ

## 英語版の表現（任意）

Diplomatic play

## 希望する変更（必須）

外交戦

## 変更の理由（必須）

直訳になっているが、直感的に意味がわからず、あまりよい訳語にはなっていない。
グラフィックや、常に敵対する主要対戦相手が一国あることなどからチェスの対戦をイメージしているのは明らかであり、
これに対応した訳語としては外交戦が相応しいであろう。

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

無し

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1034946947750047786
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by Zousuikakka** [comment]
外交戦で修正
