### ISSUE TITLE
野盗（キャラクター特性）

### ISSUE THREAD

**Issue by kurutto115** [matanki-saito/vic3jpadvmod#520]
### スクリーンショット

![Victoria 3 2022_11_26 10_29_49](https://user-images.githubusercontent.com/117251782/204082235-74943d8e-b4db-4807-bcf9-57a73ad5cf24.png)

### 問題の用語

野盗

### 英語版の表現

Bandit

### 希望する変更

無法者

### 変更の理由（概要）

日本語として違和感があるため

### 変更の理由（詳細）

実際に盗賊行為を行っていないであろう人物を「野盗」と評するのは日本語として違和感があります
”「森の掟」に従う人物”と説明があるように、「村の掟」に従わない野盗・山賊というニュアンスなので、
”無法者”と訳すのが自然ではないでしょうか

### ゲームバージョン

1.0.X

### MOD有無

本プロジェクトMODのみ

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by WoodlandsGitHub** [comment]
参考までに。
森の掟は、原文では「a graduate of the University of the green forest」になっていて、張作霖の経歴が元ネタです。
 bandit_desc:0 "This character is known for being a graduate of the 'University of the Green Forest'."
ご存じ馬賊の張作霖です。字義どおりの「野盗」あがりです。
なので、野盗という字面は浮いてはいますが、あながち間違いでもないです。
