### ISSUE TITLE
融資（外交アクション）

### ISSUE THREAD

**Issue by kurutto115** [matanki-saito/vic3jpadvmod#521]
### 問題の用語

融資

### 英語版の表現

Bankroll

### 希望する変更

資金援助

### 変更の理由（概要）

実際のゲームメカニズムと異なっているため

### 変更の理由（詳細）

Bankrollとは資金を出すことで、必ずしも返済を伴うものではないようです
[英語「bankroll」の意味・使い方・読み方 | Weblio英和辞書](https://ejje.weblio.jp/content/bankroll)
[BANKROLL | 意味, Cambridge 英語辞書での定義](https://dictionary.cambridge.org/ja/dictionary/english/bankroll)
実際ゲーム中でも返済が行われるわけではないことから、「融資」の語は実態を反映していないと思われます

### ゲームバージョン

1.0.X

### MOD有無

無し

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
報告ありがとうございます。ご提案通り改訳しました。
