### ISSUE TITLE
布告の用語の修正

### ISSUE THREAD

**Issue by mochi115** [matanki-saito/vic3jpadvmod#522]
### スクリーンショット

![スクリーンショット_20221121_164443](https://user-images.githubusercontent.com/117048815/204087930-c8a0c833-426a-4647-89ff-d2b20a01d3d0.png)

### 問題の用語

〜を奨励する、隣の芝は青い運動

### 希望する変更

〜の奨励、隣の芝生は青い運動

### 変更の理由（概要）

複数

### 変更の理由（詳細）

〜を奨励するを発布、など不自然な日本語になるので体言止めに修正します。

より一般的な語であり、隣の芝生は青い/運動といい感じに改行されます。

### ゲームバージョン

1.0.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
ご提案どおり修正しました

クローズします
