### ISSUE TITLE
【脱字】[将軍名]解雇することはできない。

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#523]
### スクリーンショット

![image](https://user-images.githubusercontent.com/37979626/204090820-3fd49b6a-e0d0-4dd3-aaa5-067f40518943.png)

### 問題部分

選択肢

### 問題のイベント選択肢

```[SCOPE.sCharacter('arguing_commander_two').GetFullName]解雇することはできない。```

### 希望する変更（修正部分のみ）

```[SCOPE.sCharacter('arguing_commander_two').GetFullName]を解雇することはできない。```

### 変更の理由（概要）

脱字

### 変更の理由（詳細）

助詞が抜けている

### プレイ国家

ロシア

### ゲームバージョン

1.0.X

### MOD有無

JapaneseLanguageAdvancedMod, Japanese Flavor, Universal Names

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通りで確定しました
