### ISSUE TITLE
奴隷禁止

### ISSUE THREAD

**Issue by mochi115** [matanki-saito/vic3jpadvmod#525]
### スクリーンショット

![20221126191033_1](https://user-images.githubusercontent.com/117048815/204092698-3a427f87-d1b9-4893-b652-c8fd97c854ea.jpg)

### 問題の用語

奴隷禁止

### 希望する変更

奴隷制廃止

### 変更の理由（概要）

しっくりくる語に修正

### 変更の理由（詳細）

農奴制廃止に合わせてよりしっくりくる語に修正します。

### ゲームバージョン

1.0.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
議論の結果「奴隷制禁止」に決定し、修正を完了しました。
