### ISSUE TITLE
織物工場

### ISSUE THREAD

**Issue by mochi115** [matanki-saito/vic3jpadvmod#526]
### スクリーンショット

![20221126172811_1](https://user-images.githubusercontent.com/117048815/204094971-6a4ef64b-78e0-4bd6-89d3-8413d923c5e2.jpg)

### 問題の用語

織物工場

### 希望する変更

衣類工場

### 変更の理由（概要）

違和感のある訳

### 変更の理由（詳細）

織布だけでなく縫製もして衣類を生産しているため、織物工場では違和感があります。

### ゲームバージョン

1.0.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。
