### ISSUE TITLE
税回避

### ISSUE THREAD

**Issue by mochi115** [matanki-saito/vic3jpadvmod#527]
### スクリーンショット

![スクリーンショット (9)](https://user-images.githubusercontent.com/117048815/204095984-68049687-e784-47f4-ac48-c4e80e11e864.png)

### 問題の用語

税回避

### 英語版の表現

Tax Avoidance

### 希望する変更

租税回避

### 変更の理由（概要）

Wikipediaに載っている語に修正

### 変更の理由（詳細）

Wikipediaに載っている一般的な語に修正します。
https://ja.wikipedia.org/wiki/%E7%A7%9F%E7%A8%8E%E5%9B%9E%E9%81%BF

### ゲームバージョン

1.0.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
ご提案どおりに修正しました

クローズします
