### ISSUE TITLE
「人頭税」の訳語被り

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#528]
### スクリーンショット

上がpoll taxの、下がper-capitaの人頭税
![poll_taxes](https://user-images.githubusercontent.com/50406316/204096353-04ba9a86-b020-4f72-bf85-1d4faeb693e7.png)

こちらはpoll taxの人頭税
![propotional](https://user-images.githubusercontent.com/50406316/204096495-281d5168-4413-4179-a2d5-94f99a67480c.png)

### 問題の用語

人頭税

### 英語版の表現

Poll tax、Per-capita tax

### 希望する変更

上手い訳語が思いつかないため要議論

### 変更の理由（概要）

異なるゲームコンセプトに同じ訳語が当てられているため訳し分けたい

### 変更の理由（詳細）

ゲーム中には広義の人頭税に当たるものが2種類存在し、peasantsのみに課されるland tax（地税と訳）とそれ以外に課されるper-capita tax（人頭税と訳）があり、それらの総称をpoll tax（こちらも人頭税と訳）と呼んでいる。

個別の税の人頭税と総称としての人頭税で、異なるゲームコンセプトに同じ訳語が当てられているのは紛らわしいので、何らかの訳語を使って訳し分けたい。

### ゲームバージョン

1.0.X

### MOD有無

翻訳改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
議論の結果、「人頭税/地税」と併記するよう修正しました。

クローズします。
