### ISSUE TITLE
奴隷制の差異による関係悪化フィード

### ISSUE THREAD

**Issue by ikabomb** [matanki-saito/vic3jpadvmod#529]
### スクリーンショット

![image](https://user-images.githubusercontent.com/84853597/204118355-07aba232-20c2-4938-b7f3-cacca255dfb0.png)

### 問題のあるインターフェイス

上画像のフィード

### 問題のテキスト

オスマン帝国は、我が国との関係を低下させました。こちらの奴隷制排除により、相手国の奴隷たちが自由を求めて我が国の領土へと逃れるようになったためです。

### 希望する変更

オスマン帝国との関係が低下しました。オスマン帝国の奴隷らが、奴隷制の禁止されている我が国へ自由を求めて逃れていることに由来します。

### 変更の理由（概要）

日本語として不自然だと感じたため

### ゲームバージョン

1.0.X

### MOD有無

JapaneseLanguageAdvancedMod

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
検討の結果、
「[国名]の奴隷たちが、奴隷制を禁止した我が国へと自由を求めて逃れてきているため、両国間の[関係]が低下しました。」
と表示されるように修正しました。

クローズします
