### ISSUE TITLE
【修正提案】ウォー

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#53]
＜ゲームシステム用語＞

## スクリーンショット（任意）

![20221027064944_1](https://user-images.githubusercontent.com/43299334/198145714-2b9f57ce-b5d6-42ba-a773-8a909ce21d40.jpg)

## 問題の用語（必須）

ウォー

## 英語版の表現（任意）

War

## 希望する変更（必須）

戦争

## 変更の理由（必須）

なぜか音写されており意味が分かりにくいため。
特に一般的な戦争と異なる概念ではない。

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

無し

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1034948343564091394
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by Zousuikakka** [comment]
戦争で修正
