### ISSUE TITLE
peasantsの訳語

### ISSUE THREAD

**Issue by Winterkonig** [matanki-saito/vic3jpadvmod#530]
### 問題の用語

百姓

### 英語版の表現

peasants

### 希望する変更

貧農、または小作農

### 変更の理由（概要）

百姓が日本史独自の用語であるため

### 変更の理由（詳細）

百姓という訳語について非常に大きな違和感があります。
農民の説明に小作人とありそれがParadox訳のPeasantsの翻訳小作人と被るから百姓を採用したのかと拝察しますが、百姓は明らかに日本史独自の用語であるため、日本史以外の文脈では違和感が強すぎます。
日本史用語としての百姓の意味は改めて書く必要もないかもしれませんが、百姓という言葉は、百の姓を持つ者、つまり天皇から姓を賜っていない庶民（貴族の対義語としての）という意味になります。
日本史学者の網野善彦が著書で述べているように、中世日本では海運や金融業で巨額の財を成した百姓もいました。
確かに江戸時代では百姓が農民に限定される傾向が高いので、時代的に誤りとは言い切れないかもしれません。
しかしいずれにせよ、「百姓」という単語は明らかに日本史独自の用語であり、日本的であり、日本以外の国でプレイするのなら違和感が強すぎます。
日本でプレイするのに限定したとしても、百姓という言葉自体には「貧しい農民」という意味は存在しないので、訳語として適切とは思えません。
ましてヨーロッパ諸国で「百姓」といわれると、日本のステレオタイプのお百姓さんがヨーロッパに転生でもされてきたかのような違和感ばかりです。
この件について変更を考えていただきたいと思います。

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Winterkonig** [comment]
まず私は学究の徒ではないので素人としてしか議論できないということを一応表明しておきます。
百姓が日本史独自の用語である点のエビデンスは現在調べております。

しかし私としては逆に百姓が世界史に普遍的な用語であるということを示していただきたいところです。
百姓の語源は上述の通りであり世界的に普遍的な用語とはとても思えません。
百姓が貧しい農民という概念自体も網野善彦によれば日本史研究史の中で生まれた偏見とされています。
中世生活史やヨーロッパ近代史の専門書は数冊読みましたが百姓という言葉が出てきた記憶はありません。

それから「感覚的な」「主観的な」ものになってしまいますが、百姓という言葉はあまりに日本的に感じられます。
普遍性を感じません。
たとえるならば日本の中世史を欧米人が書いたときに百姓を"serf"と翻訳するのと同じでしょう。

とりあえず調査はしておきますが、私はここでの過去のやり取りに参加していないので、本問題についての自分の見解を改めて書いておきます。

**Comment by mochi115** [comment]
百姓と検索しても日本のものしか出てきませんし、フランスの百姓、イギリスの百姓と言われても違和感があります。
海外の小作人の方を百姓と称しているのは確かに聞いたことが無いですね...

**Comment by matanki-saito** [comment]
今までの議論が十分に共有されていなかったと感じたためここに共有いたします。
まず日本語の小作人（小作農）だと土地を借りている意味が含まれますがゲーム内にその意味合いはないため外しました。またゲーム内のpeasnansはたとえ中流階級だったとしてもpeasnansのままなので、貧という限定した言葉も除外した経緯があります。またそもそも農民という言葉にすれば良いという案もあったのですが、peasantsと別にfarmersが存在し、そちらが農家と翻訳されているため誤読を防ぐためになるべく別の用語にしたい経緯もありました。

**Comment by mochi115** [comment]
![20221201223941_1](https://user-images.githubusercontent.com/117048815/205075414-0d9288c0-f46e-4b27-b442-ffba60963e96.jpg)
![20221201223937_1](https://user-images.githubusercontent.com/117048815/205075428-3b95d607-cfa2-49c8-9b19-ee5e31227a00.jpg)
Vic3のPeasantsは自給自足して暮らしているPOPだけを表す語みたいです。
小作人、自作人はFarmersの方に含まれています。
![20221201230600_1](https://user-images.githubusercontent.com/117048815/205076751-14537ed2-8059-40bc-9e3b-3781038e4f5d.jpg)
Peasantsは生産する商品がそのままPeasantsの需要になっている特殊なPOPであり、生活水準も低く制限されています。
このような実態を表すためPeasantsの訳語は自給農が適切かと思われます。

**Comment by TdHskw** [comment]
私は百姓でも小作農でも構いませんが、できれば一般的に存在する単語を使用してほしく、造語を使うのは英語の原文からして造語だったり、日本語にその概念が無い時だったりなどやむを得ない時に限定してほしいです。
百姓や小作農よりも造語のほうが適切というのは私には賛同できません。

**Comment by Winterkonig** [comment]
まずは繰り返しになりますが百姓という言葉について書いておきます。
百姓は語源、用法から考えてやはり日本史に独自の言葉と考えます。
百姓は百の姓を持つ者、つまり天皇から姓を賜っていない庶民が原義です。言い換えれば貴族ではない日本人はすべて百姓になります。その後、網野善彦によれば、19～20世紀になって何故か（基本的に江戸幕府について「士農工商」という言葉を用いたことなどが端緒）百姓は日本の農民を指す言葉だと誤用されるようになったとされています。実際には江戸時代であっても海運業で富を築いた百姓もいると網野善彦により証明されています。
そしてやはりヨーロッパの歴史に関する本に、特にその本が専門的であればあるほど「ヨーロッパの百姓」という言い方をしないと、自分の読書歴から考えます。
百姓という言葉はあまりに日本的すぎて、ゲームの主人公たちであるヨーロッパ諸国は無論、日本以外の国すべてのプレイで違和感を覚える言葉かと思います。
少なくとも「中立的な」言葉とは思えません。

次にゲームのルールなどと合わせて考えました。
このゲームのPeasantはつまるところFarmで働いていない、Farmerではない農民のことを指すという、歴史的な背景を持った用語というよりもルール上作られた人工的なものです。
研究社新英和中辞典のpeasantの項目には「小さな土地を耕す農民か、または雇われ農民のことをさすが、現在英・米・カナダ・オーストラリアなどでは農業が大規模で farmer（農場経営者）によって行なわれているので、peasant はいない」という解説文がありますが、Victoria3ではまさにこの意味で使い分けがされています。経営しているのは資本家ではなく貴族ですが。
この日本語訳を面倒にしているのはFarmerの説明文に小作人（sharecropper）とあるからですが、別にこれらは歴史的な背景を持った使い分けではなくVictoria3のゲーム的な都合によるものです。
よってそもそもゲームのルールが人為的な以上造語の利用も問題ないとは個人的に思います。
なおゲーム上のPeasantに小作の定義が当てはまらないとありますがゲーム上ロシアの農奴もPeasantなので開発者側はそこまで使い分けていないのではないでしょうか。

私としては使い分けがそもそも曖昧である以上そこを無視して小作農とするか、造語として自給農を利用するかが良いかと考えます。
これについて厳密な翻訳はあまり意味がないとも思えます。開発者の方でも方便としてPeasantを使っているだけでしょうから。

**Comment by inarizushi0309** [comment]
確かに「百姓」というワードは「日本的」な言葉として世に定着していますが、イコール日本限定でしか使えないことの証左になるのでしょうか？ドン＝キホーテをはじめとする海外文学の邦訳版のいくつかで「百姓」をいうワードは散見される以上、欧米（非日本）地域においても使用できるのではないでしょうか？

**Comment by Winterkonig** [comment]
最初に。百姓という言葉は日本史独自の言葉と書いてきましたが、元々は中華文明の言葉であり、東アジア諸国では歴史的に利用されてきました。ですので百姓という言葉は日本史独自の言葉ではなく、東アジア史独自の言葉と訂正させていただきます。

確かに百姓という言葉をヨーロッパ史の文脈の中で使っても、強引で下手な翻訳ですが間違いではないでしょう。私は百姓という言葉を使ったヨーロッパ文学の翻訳の記憶はありませんが、あったとしても、下手な翻訳とは思いますが使用の否定はできないかもしれません。

しかし百姓という言葉はやはり東アジア的すぎます。ヨーロッパ史やアメリカ史の文脈では間違いではないかもしれませんが、違和感が強すぎと思います。敢えて言うなら（パラドゲーというファンタジーである）19世紀ヨーロッパのセンス・オブ・ワンダーを阻害します。それがパラドゲーというファンタジーであればこそ余計邪魔をします。

なお、これまで歴史上認められてきた「誤訳」の代表的なものにドイツ語の"Putsch"があります。有名なものに「ミュンヘン・プッチ」つまり「ミュンヘン一揆」があります。現代のところ一応「ミュンヘン一揆」は歴史用語として存在していますが、「一揆」の意味と"Putsch"の意味とで歴史的に乖離が大きいとして「良くない翻訳」の代表とされています。ドイツ語の"Putsch"は「暴動」といった意味になりますが、「一揆」は日本史において「一つの目標のためにかわされる盟約」という意味です。
Victoria3のPeasantを「百姓」と翻訳するのはこのPutschを一揆と翻訳するのと同じ轍を踏むことになるかと思います。

不思議なのは、厳密に厳密に、「貧」という言葉や「小作」という言葉をPeasantの訳語から取り除いていったのに、何故百姓という言葉を乱暴に持ち出してきたのか、ということではあります。あくまでも個人の感想ですが。

なお「自給農」という日本語は存在します。農地法にも記述があります。


ですので私としては、

1.Peasantsの訳語として「自給農」を採用する。

2.ゲーム上大規模農場の従業員として設定されているFarmersを「農業従事者」もしくは「農業従業員」と訳しPeasantsを「農民」と訳す。

があるかと思います。
私としては2.を特に推したいかと思います。

**Comment by nagi0330** [comment]
その理論だと「皇帝」も「経済」も東アジア史独自の言葉になるような気がしますが、、、
一般的に日本文学の英訳では百姓はPeasantsと訳されていますので、百姓で問題ないかなと。

ただ、ゲーム的にはpeasantsが減ると地主の影響力も減るので、小作農という表現もあながち間違いではないのかなとも思います。

**Comment by Winterkonig** [comment]
孤立無援で精神が焼けてきましたが、たとえ私の精神が焼け切れても「ヴィクトリア朝ヨーロッパの百姓」という言葉から違和感が消えることはありません。

英訳では問題ないでしょうがだからといって逆が成り立つわけではありません。
日本語版Wikipediaの百姓から英語版Wikipediaに飛ぶと"Baixing（百姓）"に飛びます。Peasantsには飛びません。
なお日本語版Wikipediaの百姓という項目には日本の百姓についての解説しかされていません。
ヨーロッパの”百姓”については別に「農民」という項目があり農民はPeasantsであると、百姓はPeasantsとは別のものとして項目が立てられています。
ヨーロッパの歴史について、あるいは人文社会科学についての本でPeasantsを百姓と訳した本には会ったことがありません。

そして何より、私は「ヴィクトリア朝ヨーロッパの百姓」という言葉に極めて強い違和感があります。
この違和感こそがこの問い掛けをしている最大の理由です。
語源にケチがつくなら語源のことなどどうでもいいです。

あとゲーム的にいうのならば、百姓が収納されている施設は「自給農家」なるものになっています。
でしたら、自給農家なるものにいるのは「自給農」が最適なのではないでしょうか。

**Comment by Winterkonig** [comment]
私が「百姓」なる翻訳に反対している最大の理由は、実際のところ、「百姓」という言葉が「ヴィクトリア朝ヨーロッパ」の「センス・オブ・ワンダー」を著しく阻害するからです。百姓という言葉は何度も書きましたが東洋史の用語です。Wikipediaの「百姓」の項目には「ヨーロッパの百姓」については一切書かれておらず、日本と中国の百姓について書かれています。「ヨーロッパの百姓（Peasants）」については別の項目が立てられています。そして英語版Wikipediaで「百姓」の項目を引けば「老百姓"Rao-Baixing"」のことしか書かれていません。百姓で構わないと考える方はそれは個々のセンスの問題かと思いますが百姓という言葉は東洋的すぎて中立的な言葉とは思えません。百姓で構わないと考える方はそれでなんの問題もないのでしょうが、百姓という言葉に違和感を覚える私などにとっては、大袈裟にいえば「百姓」という訳語は苦痛です。あなたにとってはどうでもいいことでしょうが私にとっては苦痛です。

英文学のPeasantsを百姓と訳すということについていうならば、訳者は文学者であり歴史学者でも社会科学者でもありません。「百姓」が学術的に農民のことを意味したのは日本でも20世紀末までです。網野善彦の『日本の歴史00巻「日本」とは何か』（126頁など）（講談社2000年10月24日）などに「百姓＝農民」というのが歴史学上の誤用である旨が書かれています。

「自作農」という言葉があります。農地法第4条第4項にもあります。これが中立的で適切な翻訳家と考えます。もしくは、彼らは「自給農家」なるもので仕事に従事しているのですから自給農でしょうか。

**Comment by inarizushi0309** [comment]
我々としましては熟議の結果、「百姓」という用語を使用しています。それを「苦痛」と感じるのであれば、当modの利用をしないことをお勧めいたします。幸いにも1.2では多くの誤訳が改善されておりますので無理に当modを使う必要性も薄れているかと思います。また、modの作成は簡単ですので、ご自分が気になるところを自作modで修正してはいかがでしょうか。

**Comment by Winterkonig** [comment]
著しい侮辱である。

私は「我々」が誰なのかは知らないし「熟議」もどこでどのようになされたのかも知らない。熟議というのならここですればよかったことではないか。要するに初戦出来レースで内密に決めていて意見の汲み上げなどする気など最初からなかったわけだ。なんのためのスレッドなのか。わざわざ百姓や農民という言葉の用法を調べたりしたのも全て無駄だったということではないか。人を馬鹿にするのにもいい加減にしてほしい。最初から決まっているのならそうと言えばいい。私はこんなにも無駄な言論をせねばならなかったのか。最後の最後に至って人の苦痛を馬鹿にした態度をとるとは侮辱もこの上ない。なんのために私がここで散々調べ物をして文章を書かなければならなかったのか。すべて最初から無駄なことではないか。

この著しい侮辱は忘れない。

**Comment by inarizushi0309** [comment]
「侮辱」したと思われようが、最後に一点だけ。このmodのフローについてはこのプロジェクトのトップにてmiroというホワイトボードの形で公開されています。それを見ずに一方的に言われては困ります。
