### ISSUE TITLE
予算支出水準のツールチップ

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#531]
### スクリーンショット

![level](https://user-images.githubusercontent.com/50406316/204121423-5c10a727-c560-4a67-bc94-41ecf39eb954.png)

### 問題のツールチップ

予算タブで税、政府給与、軍隊給与の支出レベルを変えるボタン

### 問題の表現

[非常に低い/低い/普通/高い/非常に高い]の[税金/政府賃金/軍隊の給与]

### 問題箇所の英文

[Vely low/Low/Medium/High/Very high] [Taxes等]

### 希望する変更

[非常に低い/低い/普通/高い/非常に高い]水準の[税金/政府賃金/軍隊の給与]

### 変更の理由（概要）

「高い/低いの税金」という表現の修正

### 変更の理由（詳細）

現行の表記だと「普通の税金」はよいが、「低いの税金」だとおかしな文章になる。
「普通」でも「高い/低い」でもどちらでも違和感のない表現にするために、「水準」の文字を加えて、「普通水準の税金」「高い/低い水準の税金」としたい。

### プレイ国家

どこでも

### ゲームバージョン

1.0.X

### MOD有無

翻訳改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
[最低水準/低水準/標準/高水準/最高水準]の[政府賃金/軍隊の給与]
となるよう、各ラベルと関連キーを修正しました

**Comment by clamm0363** [comment]
クローズします
