### ISSUE TITLE
家具工場の基礎方式

### ISSUE THREAD

**Issue by mochi115** [matanki-saito/vic3jpadvmod#533]
### スクリーンショット

![20221126182214_1](https://user-images.githubusercontent.com/117048815/204127152-43403f72-ce92-4943-80a1-b6214958db73.jpg)

### 問題の固有名詞：希望する変更

手織り(Handcrafted Furniture) : 手作業
旋盤類(Lathes) : 旋盤

### 変更の理由（概要）

複数

### 変更の理由（詳細）

誤訳かと思われます。原語を直訳するなら手作りの家具ですが、機械を使う他の方式と対比させて手作業と訳しました。

原語版では、方式は基本的に複数形になっています。わざわざ〜類と訳さなくてもいいと思います。

### ゲームバージョン

1.0.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
Handcrafted Furnitureを「手工芸」
Lathes/Lathを「旋盤加工」として修正しました

クローズします
