### ISSUE TITLE
古代ギリシャ

### ISSUE THREAD

**Issue by TdHskw** [matanki-saito/vic3jpadvmod#534]
### スクリーンショット

![201520116-10e8b8ce-b253-498e-ab52-d13b67ec8d4c](https://user-images.githubusercontent.com/108180041/204130552-1404d994-5283-4ba5-93de-8b6139299b35.jpg)

### 問題の固有名詞：希望する変更

古代ギリシャ：ギリシャ

### 変更の理由（概要）

現代の文化に古代という言葉は不要

### 変更の理由（詳細）

英語版が単にHellenicなので、英語版にない古代という言葉をわざわざ加える必要が無いため
#455で直っていなかったので再起票しました

### ゲームバージョン

1.0.X

### MOD有無

JapaneseLanguageAdvancedMod

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
修正しました。ご報告ありがとうございます。
