### ISSUE TITLE
陸軍偵察部隊PM一括決定

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#535]
### スクリーンショット

![199687970-0251f826-6f8d-4195-9594-aa3ee283d8a6](https://user-images.githubusercontent.com/43299334/204191816-a7df18f6-c8d6-4f25-b5e4-fc3d65d5d40d.jpg)

### 問題の用語

斥候騎兵/自転車伝令/自動偵察/航空偵察

### 英語版の表現

Cavalry Scouts/Bicycle Messengers/Motorized Reconnaisance/Aerial Reconnaisance

### 希望する変更

騎兵部隊/自転車部隊/自動車部隊/航空部隊

### 変更の理由（概要）

一部違和感があるため（特に自動偵察）

### ゲームバージョン

1.0.X

### MOD有無

日本語改善MOD、Japonism

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
騎兵斥候/自転車伝令/自動車偵察/航空偵察で修正
