### ISSUE TITLE
侍の落日

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#536]
### スクリーンショット

![20221128130910_1](https://user-images.githubusercontent.com/42687608/204195196-39c54598-9741-4e31-8224-42ea45a56f4f.jpg)

### 問題部分

本文

### 問題のイベントタイトル

侍の落日

### 問題のイベント本文（抜粋可）

将軍は大名に忠誠を誓い、大名は侍に頼って、奴隷となった農民の支配を強化した。

### 希望する変更（修正部分のみ）

大名は将軍に忠誠を誓い、侍は大名に頼って、奴隷となった農民の支配を強化した。

### 変更の理由（概要）

誤訳

### 変更の理由（詳細）

将軍と大名、大名と侍の関係がそれぞれ逆になっているため。

### プレイ国家

日本

### ゲームバージョン

1.0.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
```
[ROOT.GetCountry.GetName]は軍制改革に成功し、時代遅れとなった封建制のシステムに終止符を打ちました。近代化しつつあるこの社会において、もはや[SCOPE.gsInterestGroup('samurai_ig').GetName]階級には居場所がないようです。

将軍は大名たちに忠節を誓わせ、その大名たちは、配下の武士たちを使って小作人への支配を確固たるものとする。今や過去の遺物となった日本の封建制とは、こういったものであった。今でも、「武士道」として知られる武士の規範や美徳を重んじる者はいるし、それは伝統として人々の内に残り続けるだろう。武士の時代はしかし、再び巡り来ることはないはずだ。
```

**Comment by clamm0363** [comment]
上記のとおり修正しました。

クローズします
