### ISSUE TITLE
フランス系カナダ人の姓名

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#537]
### スクリーンショット

なし

### 問題の固有名詞：希望する変更

アレイン：アラン
オーギュスト・レアル：オーギュスト＝レアル
チャールス・セラフィン：シャルル＝セラファン
デニス・ベンジャミン：ドニ＝バンジャマン
エルゼアール：エルゼアル
エティエンネ・パスカル：エティエンヌ＝パスカル
フランソワ・エドアルド：フランソワ＝エドゥアール
ジョージ・エティエンネ：ジョルジュ＝エティエンヌ
ジローム・アルフォンス：ギヨーム＝アルフォンス
ヘクター・ルイス：エクトル＝ルイ
ハーメンギルデ：エルメネジルド
ホノーレ：オノレ
ジーン・バプティスト：ジャン＝バティスト
ジーン・ドシル：ジャン＝ドシル
ジーン・ポール：ジャン＝ポール
ジョセフ・オスカー：ジョゼフ＝オスカル
ジョセフ・レミ：ジョゼフ＝レミ
ローレント・オリヴィエ：ローラン＝オリヴィエ
リーンドル：レアンドル
ルイス・アデラード：ルイ＝アデラール
ルイス・ジョセフ：ルイ＝ジョゼフ
ルイス・オリヴィエ：ルイ＝オリヴィエ
ルイス・フィリッペ：ルイ＝フィリップ
ルイス・ロドリグ：ルイ＝ロドリグ
マシュー：マテュー
ナルキッス・フォーチュナト：ナルシス＝フォルテュナ
オリヴィア・ナポレオン：オリヴィエ＝ナポレオン
ピエール・オーレル：ピエール＝オーレル
ピエール・スタニスラス：ピエール＝スタニスラ
レネ・エドアルド：ルネ＝エドゥアール
シモン・ナポレオン：シモン＝ナポレオン
テレスフォア：テレスフォル
ウルリク・ジョセフ：ユルリク＝ジョゼフ

アンネ・マリー：アンヌ＝マリー
マリー・アメイブル：マリー＝アマブル
マリー・ルイス：マリー＝ルイーズ
マージョリン：マルジョレーヌ
ピエレッテ：ピエレット

ベダード：ベダール
ベルメア：ベルマール
カーティア：カルティエ
パピニュー：パピノー
スレッテ：シュレット

アレイン：アラン
アンガース：アンジェ
アセリン：アスラン
バビニュー：バビノー
ベリュー：ベロー
ブーラッサ：ブラサ
ブロッソー：ブロソー
コーチョン：コーション
ドゥモシェル：デュムシェル
ドゥバル：デュヴァル
ファウシャー：フォシェ
フレモント：フレモン
ガラント：ガラン
ガルニュー：ガルノー
ハメル：アメル
ヘーバート：エベール
ジャルバート：ジャルベール
ランジェリア：ランジュリエ
ランジェヴィン：ランジュヴァン
ラヴィオレッテ：ラヴィオレット
ルメシュリエール：ルムシュリエ
ロウリー：ルグリ
マーチャンド：マルシャン
メローシェ：メロシュ
メルシエ：メルシェ
モーリン：モラン
ウイメット：ウィメ
ペインショード：パンショー
パーレント：パラン
ペラデュー：ペラドー
ペラーリン：ペルラン
ロビテイル：ロビタイユ
シマード：シマール
タッシェ：タシェ
タイロン：テヨン
タングアイ：タンギュエ
テッシエール：テシエ
ヴァリエーレス：ヴァリエール
ヴィガー：ヴィジェ

### 変更の理由（概要）

日本語では一般的ではない表記であるため

### ゲームバージョン

1.0.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
