### ISSUE TITLE
補正「～承認していない。」

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#538]
### スクリーンショット

![image](https://user-images.githubusercontent.com/37979626/204457744-94f1d14e-bcb5-4334-ac3c-dd0fe2690875.png)

### 問題のツールチップ

イベント「決闘」>「決闘を禁止すべきだ。」マウスオーバー

### 問題の表現

決闘が禁止されることを承認していない。
決闘が禁止されることを承認している。

### 問題箇所の英文

Disapproves of duels being banned.
Approves of duels being banned.

### 希望する変更

決闘の禁止に不賛成
決闘の禁止に賛成

### 変更の理由（概要）

誤訳

### 変更の理由（詳細）

英語では
"get [補正名]"であるため、句点が含まれていても問題なかったが、日本語では「[補正名]を得ます」と語順が変わってしまう。

### プレイ国家

ロシア

### ゲームバージョン

1.0.X

### MOD有無

JapaneseLanguageAdvancedMod, Japanese Flavor, Universal Names

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通り修正しました。
