### ISSUE TITLE
これは○○を急進化します

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#539]
### スクリーンショット

![image](https://user-images.githubusercontent.com/37979626/204475362-e82a8a61-cbce-4060-9ce4-5fc50df92e65.png)

### 問題のツールチップ

法律画面>

### 問題の表現

@warning! これは[INTEREST_GROUP.GetName]を[Concept('concept_political_movement_radicalism', '$concept_political_movement_radicalize$')]します

### 問題箇所の英文

@warning! This will [Concept('concept_political_movement_radicalism', '$concept_political_movement_radicalize$')] the [INTEREST_GROUP.GetName]

### 希望する変更

@warning! これは[INTEREST_GROUP.GetName]を[Concept('concept_political_movement_radicalism', '$concept_political_movement_radicalize$')]させるでしょう

### 変更の理由（概要）

誤訳

### 変更の理由（詳細）

自然な日本語表現ではない

### プレイ国家

ロシア

### ゲームバージョン

1.0.X

### MOD有無

JapaneseLanguageAdvancedMod, Japanese Flavor, Universal Names

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
```@warning! これは[INTEREST_GROUP.GetName]を[Concept('concept_political_movement_radicalism', '$concept_political_movement_radicalize$')]させます```
以上で修正しました。
