### ISSUE TITLE
【修正提案】イニシエータと対象

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#54]
＜ゲームシステム用語＞

## スクリーンショット（任意）

![20221027065146_1](https://user-images.githubusercontent.com/43299334/198146264-ffc5b736-99b5-47e6-9645-a67bf68c933c.jpg)

## 問題の用語（必須）

イニシエータ、対象

## 英語版の表現（任意）

Initiator,Target

## 希望する変更（必須）

提唱国、対象国

## 変更の理由（必須）

イニシエータの表記以降、「あなた」の部分などが見切れている。
UIを調整してもよいが、InitiatorとTargetはセットの概念になっており、統一感のあるものとした方が良さそう。
ここでは直訳気味に提唱国、対象国とした。

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

無し

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1034950340887453738
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by oooFUNooo** [comment]
修正を完了しました。議論の結果、Initiatorは「先制国」、Targetは「標的国」となりました。
