### ISSUE TITLE
[補正一覧]を持っています

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#541]
### スクリーンショット

![image](https://user-images.githubusercontent.com/37979626/204503146-d78fbe6e-9dce-4174-8bb2-46b761d45e2e.png)

### 問題のツールチップ

人物画面>人気度マウスオーバー

### 問題の表現

```#header [Character.GetFullName]#!は#v [LabelingHelper.GetLabelForPopularityCFixedPoint(Character.GetPopularity)]#! ([Character.GetPopularity|0+=]) [concept_popularity][ConcatIfNeitherEmpty('\n$TOOLTIP_DELIMITER$\n', Character.GetPopularityDesc)]を持っています```

### 問題箇所の英文

```#header [Character.GetFullName]#! has #v [LabelingHelper.GetLabelForPopularityCFixedPoint(Character.GetPopularity)]#! ([Character.GetPopularity|0+=]) [concept_popularity][ConcatIfNeitherEmpty('\n$TOOLTIP_DELIMITER$\n', Character.GetPopularityDesc)]```

### 希望する変更

```#header [Character.GetFullName]#!は[concept_popularity]#v [LabelingHelper.GetLabelForPopularityCFixedPoint(Character.GetPopularity)]#! ([Character.GetPopularity|0+=]) [ConcatIfNeitherEmpty('\n$TOOLTIP_DELIMITER$\n', Character.GetPopularityDesc)]```

### 変更の理由（概要）

変数に対応できていないため

### 変更の理由（詳細）

最後の変数は補正内容をリスト表示させるもので、その後に「持っています」と来るのは不自然

### プレイ国家

ロシア

### ゲームバージョン

1.0.X

### MOD有無

JapaneseLanguageAdvancedMod, Japanese Flavor, Universal Names

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
> #header [Character.GetFullName]#!の[concept_popularity]: #v [LabelingHelper.GetLabelForPopularityCFixedPoint(Character.GetPopularity)]#! ([Character.GetPopularity|0+=]) [ConcatIfNeitherEmpty('\n$TOOLTIP_DELIMITER$\n', Character.GetPopularityDesc)]

**Comment by clamm0363** [comment]
上記のように修正するとともに、
Hated/大衆の敵
Disliked/嫌われ者
Neutral/普通
Liked/人気者
Loved/国民的人気
と各人気度の表現を修正しました。

**Comment by clamm0363** [comment]
クローズします
