### ISSUE TITLE
固有名詞の変更漏れとその他変更

### ISSUE THREAD

**Issue by 2022fff** [matanki-saito/vic3jpadvmod#543]
### スクリーンショット

![スクリーンショット (671)](https://user-images.githubusercontent.com/87253874/204544291-98b61527-5a50-442b-ab6e-1edf3fc63726.png)
![スクリーンショット (672)](https://user-images.githubusercontent.com/87253874/204544307-d3fc121e-8aa6-40c7-bfab-9ae0ac1e1afc.png)
![スクリーンショット (673)](https://user-images.githubusercontent.com/87253874/204544325-d8c688f6-ae17-4c55-8c61-a9dd53df69e9.png)
![スクリーンショット (674)](https://user-images.githubusercontent.com/87253874/204544337-c6466c24-7cc6-4349-889c-54f5df7c8230.png)
![スクリーンショット (676)](https://user-images.githubusercontent.com/87253874/204544571-4f989dbc-9d3d-4621-98dc-b1845485ccf7.png)
![スクリーンショット (677)](https://user-images.githubusercontent.com/87253874/204544259-39fd19be-4609-457e-9839-49483cf498b9.png)
![スクリーンショット (678)](https://user-images.githubusercontent.com/87253874/204544273-77e3ebac-f645-4caa-a565-4882797f1e2b.png)

### 問題の固有名詞：希望する変更

以前に変更された固有名詞が歴史概要に反映されていない。より一般的な呼び方への変更

国：ヒヴァ
ヒバ→ヒヴァ

国：ブハラ
ジンギスカン→チンギスハーン

国：コーカンド
コカンド→コーカンド

国：オマーン
サルタン→スルタン

国：ペルシア
ペルシャ→ペルシア

国：スペイン
女王イザベラ→女王イザベル

国：チュニス
チュニジア→チュニス

中央アジアの君主称号をカーンからハーンに

### 変更の理由（概要）

表記ゆれ、一般的呼称への変更

### ゲームバージョン

1.0.X

### MOD有無

JapaneseLanguageAdvancedMod

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
一旦、国名部分のみを過去の修正に合わせて修正しました。
残りの部分につきましては一旦保留します。

**Comment by clamm0363** [comment]
Genghis Khan/チンギス・ハン
Khan (Title)/ハン
Khannate/ハン国
Khan (人名)/ハーン
以上の修正を行いました

クローズします
