### ISSUE TITLE
【実績】アメリカの領土 / American Territory

### ISSUE THREAD

**Issue by ikabomb** [matanki-saito/vic3jpadvmod#545]
### スクリーンショット

![image](https://user-images.githubusercontent.com/84853597/204675928-a511671d-d493-435a-bc0e-c0f6b7f1250b.png)

### 問題の用語

アメリカの領土

### 英語版の表現

American Territory

### 希望する変更

アメリカ準州 / アメリカン・テリトリー

### 変更の理由（概要）

Indian Territoryに対する訳になっていないため

### ゲームバージョン

1.0.X

### MOD有無

JapaneseLanguageAdvancedMod

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
修正MODの「インディアン準州」に合わせて「アメリカン準州」と修正しました。

クローズします
