### ISSUE TITLE
【実績】American Territoryの条件文

### ISSUE THREAD

**Issue by ikabomb** [matanki-saito/vic3jpadvmod#546]
### スクリーンショット

![image](https://user-images.githubusercontent.com/84853597/204676557-24e3783b-459f-4b1a-8272-d24f841f9b3c.png)

### 問題の用語

インディアン準州としてスタートし、最大3つの州を所有しているアメリカ合衆国を従属国にする

### 希望する変更

インディアン準州として開始し、アメリカ合衆国の持つ州が3州以下になった状態でアメリカ合衆国を従属国にする

### 変更の理由（概要）

訳がこなれていないため

### ゲームバージョン

1.0.X

### MOD有無

JapaneseLanguageAdvancedMod

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
> インディアン準州でゲームを開始し、3州以下の領土しか支配していない状態のアメリカ合衆国を従属国として保有する

**Comment by clamm0363** [comment]
上記のように修正しました。あわせて、Starting as~ が使われている同様の実績の表現と、国名が修正前のものになっていた実績条件も修正しています。

クローズします
