### ISSUE TITLE
【実績】ペドロには投票しない / I didn't vote for Pedro

### ISSUE THREAD

**Issue by ikabomb** [matanki-saito/vic3jpadvmod#547]
### スクリーンショット

![image](https://user-images.githubusercontent.com/84853597/204678253-2f92811e-c7ad-4a81-872a-0212de18ff14.png)

### 問題の用語

ペドロには投票しない

### 英語版の表現

I didn't vote for Pedro

### 希望する変更

ペドルには投票していない

### 変更の理由（概要）

時制の不一致のため

### 変更の理由（詳細）

PedroについてはWiktionaryを参照したところ/ˈpe.dɾu/とあったのでペドルとしましたが、ポルトガル語には明るくないのでもしかすると不適切かもしれません

### ゲームバージョン

1.0.X

### MOD有無

JapaneseLanguageAdvancedMod

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
元ネタと思われるモンティパイソンの字幕翻訳に倣い、
「ペドロに票は入れてない」と修正しました

クローズします
