### ISSUE TITLE
大和言葉

### ISSUE THREAD

**Issue by TdHskw** [matanki-saito/vic3jpadvmod#548]
### スクリーンショット

![yamato](https://user-images.githubusercontent.com/108180041/204764882-6427bea1-2916-4f2e-8ba2-260cc7d1e8eb.jpg)

### 問題の固有名詞：希望する変更

大和言葉：大和（または日本語）

### 変更の理由（概要）

大和言葉を言語の意味で使うのは誤用であるため

### 変更の理由（詳細）

もとの英語ではおそらく大和民族の言語という意味で使っている特性でしょうが、大和言葉というのは日本語の中の漢語・外来語ではない固有の語彙（やま、かわ、うみなど）を指すものであり、言語の意味で使うのは誤用です。
英語ではYamatoなのでそのまま大和とするか、意訳して日本語と変更したいです。

### ゲームバージョン

1.0.X

### MOD有無

無

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Winterkonig** [comment]
思うに”Yamato"なる言葉には欧州人にある種のファンタジー、つまるところジャポニズムの響きを持った言葉なのではないでしょうか。
要するに彼らにとって「なんかそれっぽい」という気持ちを醸成する魔法の言葉なのでしょう。
別に日本人である我々が彼ら欧州人のファンタジーたるオリエンタリズム、ジャポニズムを共有する必要はないでしょう。
それとご指摘の通り大和言葉は明らかに誤用です。

ですので私としては「日本語」とすべきと考えます。

**Comment by Zousuikakka** [comment]
直訳である「大和」で修正しました。主な理由は以下の通りです。

- 文化特性には言語以外のものも含まれることがあり、明確に言語を意味する際には明記される傾向がある(例:Korean Language)
- 「日本語」を意味する場合は「Japanese」というより適した単語を選択できる
- アイヌ文化の人々は、Yamatoの文化特性を持たない
- 「大和民族」を意味する可能性など、複数の解釈が可能

参考)https://en.wikipedia.org/wiki/Yamato_people
