### ISSUE TITLE
ヨルバ州

### ISSUE THREAD

**Issue by ikabomb** [matanki-saito/vic3jpadvmod#549]
### スクリーンショット

![image](https://user-images.githubusercontent.com/84853597/205049946-d0a3388f-16b3-464b-a353-ce34adaec50e.png)

### 問題の固有名詞：希望する変更

ヨルバ州: ヨルバ

### 変更の理由（概要）

州の名前に州は不要なので

### ゲームバージョン

1.0.X

### MOD有無

JapaneseLanguageAdvancedMod

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
内部での議論の結果、「ヨルバ」で決しました。起票ありがとうございました。
