### ISSUE TITLE
【typo】チュートリアル説明文

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#55]
## スクリーンショット（必須）

![20221026234417_1](https://user-images.githubusercontent.com/42710893/198162339-025d4266-39ae-4108-906c-6692fbc2118a.jpg)

## 問題のあるインターフェイス（必須）

チュートリアル説明文（非生産施設の収益を改善する4/9）

## 問題のテキスト（必須）

下段2行目
「…貿易ルートを自由に確率して…」

## 希望する変更（必須）

「…貿易ルートを自由に確立して…」

## 変更の理由（必須）

誤字

## ゲームバージョン（必須）

1.0.3

## DLCの有無（必須）

なし

## MODの有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1034985429046407178
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。
