### ISSUE TITLE
選挙イベント文　「作戦」途中で予期せず天に召されました

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#552]
### スクリーンショット

![image](https://user-images.githubusercontent.com/37979626/205245532-3c34a71d-b625-443b-b654-c706e1410154.png)

### 問題部分

本文

### 問題のイベント本文（抜粋可）

[SCOPE.gsInterestGroup('decrepit_leader_ig').GetName]のリーダーである[SCOPE.sCharacter('decrepit_leader').GetFullName]老が、作戦途中で予期せず天に召されました。[SCOPE.sParty('decrepit_leader_party').GetName]の顔ともいえる政治家が失われてしまったのです。今では誰もが[SCOPE.sCharacter('decrepit_leader').GetHerHis]の後任に関心をよせています。

The aged [SCOPE.sCharacter('decrepit_leader').GetFullName], leader of the [SCOPE.gsInterestGroup('decrepit_leader_ig').GetName], has unexpectedly expired mid-campaign — robbing the [SCOPE.sParty('decrepit_leader_party').GetName] of a cornerstone politician. The question of [SCOPE.sCharacter('decrepit_leader').GetHerHis] replacement is now on everyone's lips.

### 希望する変更（修正部分のみ）

[SCOPE.gsInterestGroup('decrepit_leader_ig').GetName]のリーダーである[SCOPE.sCharacter('decrepit_leader').GetFullName]老が、選挙期間中で予期せず天に召されました。

### 変更の理由（概要）

誤訳に近いため

### 変更の理由（詳細）

選挙に関するイベントであることを考慮すると、campaign＝作戦と訳すのはよろしくないため。

### プレイ国家

ロシア

### ゲームバージョン

1.0.X

### MOD有無

JapaneseLanguageAdvancedMod, Japanese Flavor, Universal Names

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
[SCOPE.gsInterestGroup('decrepit_leader_ig').GetName]のリーダーである[SCOPE.sCharacter('decrepit_leader').GetFullName]老が、選挙期間中**に**予期せず天に召されました。
原案を微修正して確定しました
