### ISSUE TITLE
【誤訳】ロシアのために○○戦線に向かっています

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#553]
### スクリーンショット

![image](https://user-images.githubusercontent.com/37979626/205247152-267599e7-7690-4c37-ad98-1abad2ce877d.png)
![image](https://user-images.githubusercontent.com/37979626/205247180-3397629c-f71f-40e9-92e7-bd4d3d684e27.png)

### 問題のツールチップ

マップ上の戦線表示>移動中の大隊数マウスオーバー

### 問題の表現

```さらに[Country.GetName]のために@battalions!$NUM_UNITS|v$が[FRONT.GetName]に向かっています```

### 問題箇所の英文

```[Country.GetName] has @battalions! $NUM_UNITS|v$ more traveling towards [FRONT.GetName]```

### 希望する変更

```[Country.GetName]が@battalions!$NUM_UNITS|v$個大隊を[FRONT.GetName]に差し向けています```

### 変更の理由（概要）

誤訳

### プレイ国家

ロシア

### ゲームバージョン

1.0.X

### MOD有無

JapaneseLanguageAdvancedMod, Japanese Flavor, Universal Names

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通り修正しました。
