### ISSUE TITLE
アラート：非生産的な交易ルート

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#554]
### スクリーンショット

![20221201222656_1](https://user-images.githubusercontent.com/42710893/205288571-07d6c593-536d-4c1f-8ce4-0890ca106da4.jpg)

### 問題のあるインターフェイス

アラート：非生産的な交易ルート

### 問題のテキスト

alert_unproductive_trade_route_alert_name:0 "[concept_trade_route] [SCOPE.GetRootScope.GetTradeRoute.GetDescriptionForActingMarket]が非生産的になっています"

### 希望する変更

[SCOPE.GetRootScope.GetTradeRoute.GetDescriptionForActingMarket]の[concept_trade_route]が非生産的になっています　等

### 変更の理由（概要）

日本語として不自然なため

### ゲームバージョン

1.0.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
ご提案どおり修正いたしました

クローズします
