### ISSUE TITLE
ポルトガル人の姓名

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#556]
### スクリーンショット

なし

### 問題の固有名詞：希望する変更

アドリアノ：アドリアーノ
アクイリノ：アキリーノ
クリストヴァオ：クリストヴァン
ダミアオ：ダミアン
エステヴァオ：エステヴァン
ユーゲニオ：エウジェーニオ
フランシスコ・ザビエル：フランシスコ・シャヴィエル
ガスタオ：ガストン
ヘルメネジルド：エルメネジルド
ヨアキム：ジョアキン
ジョアオ：ジョアン
オーランド：オルランド
パスコール：パスコアル
セバスチャオ：セバスティアン
ヴィセント：ヴィセンテ
オスカー：オスカル

コレイア・デ・サ：コレイア・デ・サー
ダ・クンハ：ダ・クーニャ
デ・アルブクエルク：デ・アルブケルケ
デ・ブラガンサ・コブルゴ：デ・ブラガンサ＝コブルゴ
デ・ピーノ：デ・ピーニョ
ド・キュイロス：デ・ケイロース
デ・サウサ：デ・ソウザ
デ・サウサ・コウチニョ：デ・ソウザ・コウティーニョ
ドス・アンクソス：ドス・アンジョス
ランゲル：ランジェル

バレット：バレト
ブレック：ブレク
カペーロ：カペロ
コーティニョ：コウティーニョ
フィゲーラ：フィゲイラ
ヘルクラーノ：エルクラノ
マガルヘース：マガリャンイス
モニズ：モニス
ムーツィーニョ：モウジーニョ
ノゲーラ：ノゲイラ
オルティガオ：オルティガン
ピンヘイロ：ピニェイロ
ポマール：ポマル
プリード：プリド
ケーロズ：ケイロス
キンタニリャ：キンタニーリャ
テイクセイラ：テイシェイラ

デ・グスマオ：デ・グスマン
デ・ムーラ：デ・モウラ
デ・ノロンハ：デ・ノローニャ

### 変更の理由（概要）

日本語では一般的ではない表記であるため

### ゲームバージョン

1.0.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
