### ISSUE TITLE
陸軍基本編成PM　一括修正

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#557]
### スクリーンショット

![20221203212008_1](https://user-images.githubusercontent.com/43299334/205440797-70ebb74c-5157-49c9-9cdf-d4f9dec99836.jpg)
![20221203212012_1](https://user-images.githubusercontent.com/43299334/205440800-7c7ebfba-99fd-43df-93cb-4228b479717d.jpg)

### 問題の用語

上記

### 英語版の表現

上記

### 希望する変更

不正規歩兵/戦列歩兵/散開歩兵/塹壕歩兵/分隊歩兵/機械化歩兵

### 変更の理由（概要）

Infantryで統一されており、ユニット名生成に関わるため

### 変更の理由（詳細）

このPMはユニット名のテキストの一部として利用される。
英語版では「1st English Line Infantry」（常備軍）「1st English Line Infantry Conscripts」（徴募軍）などのようになる
日本語訳についてはISSUE-555を参照。

### ゲームバージョン

1.0.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。進捗がありましたら追記いたします。追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
非正規歩兵/戦列歩兵/散開歩兵/塹壕歩兵/分隊歩兵/機械化歩兵
で修正しました。
