### ISSUE TITLE
アイルの地名がおかしい

### ISSUE THREAD

**Issue by ikabomb** [matanki-saito/vic3jpadvmod#56]
## スクリーンショット（任意）

![image](https://user-images.githubusercontent.com/84853597/198163798-7fea491b-9f3b-4619-aea2-339a448fe194.png)

## 問題の固有名詞（必須）

エア

## 希望する変更（必須）

アイル

## 変更の理由（必須）

https://ja.wikipedia.org/wiki/%E3%82%A2%E3%82%A4%E3%83%AB%E5%B1%B1%E5%9C%B0, https://en.wikipedia.org/wiki/Sultanate_of_Agadez

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1034988925246246954
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by matanki-saito** [comment]
修正完了しました。
