### ISSUE TITLE
モンゴル・カルムイク人の姓名

### ISSUE THREAD

**Issue by awak1180** [matanki-saito/vic3jpadvmod#561]
### スクリーンショット

なし

### 問題の固有名詞：希望する変更

バダモドール：バダムドルジ
バリンジーン：バリンギーン
バトバイヤール：バトバヤル
バターデネ：バトエルデネ
ダムビアン：ダムビン
ゴンチグセレン：ゴンチグツェレン
インジナッシュ：インジャンナシ
コーローギーン：ホルローギーン
オツゴンバヤール：オトゴンバヤル
ペリディーン：ペルジディーン
バヤーセツェグ：バヤルツェツェグ
ドンドグドゥラム：ドンドグラム
イダー：イデル
カージヅレン：カジドスレン
ツヤー：トヤー
アマール：アマル
ボドゥー：ボドー
チャグダルジャフ：チャグダルジャブ
ダムディンバザール：ダムディンバザル
ジャムヤン：ジャミヤン
スクバータール：スフバータル
トモルバータール：トモルバータル
ヴァンシンバリン：バンチンバリン

### 変更の理由（概要）

[こちらのページ](https://bitbucket.org/awak1180/nmih-1180-scenario/wiki/Victoria3%20Mongol文化命名修正)で考証した通り、日本語で通用していない表記や実際の発音に沿わない表記(モンゴル語のVの音は日本語ではバ行音に相当)が多くみられるため、これの修正を提案する。

### ゲームバージョン

1.1.X

### MOD有無

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
