### ISSUE TITLE
Inactive 条約港

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#562]
### スクリーンショット

![inactive_ja](https://user-images.githubusercontent.com/50406316/206197098-92c46309-daa7-4164-abe7-4b8acffe07de.png)
![inactive_key](https://user-images.githubusercontent.com/50406316/206197122-a6f0ae1e-2777-437b-9761-5bdf40b7cc24.png)

### 問題のあるインターフェイス

無効な条約港の表示

### 問題のテキスト

Inactive 条約港

### 希望する変更

無効な条約港

### 変更の理由（概要）

未訳のため

### 変更の理由（詳細）

未訳であるが、該当するローカライゼーションキーが見つからず、パラドックス社でのエントリの追加忘れの可能性があるので備忘として起票しておく。

### ゲームバージョン

1.1.X

### MOD有無

翻訳改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
1.7.4でローカライゼーションキーが実装されて解決されたためにクローズします。
