### ISSUE TITLE
Venetia→ヴェネト

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#564]
### スクリーンショット

![20221208152922_1](https://user-images.githubusercontent.com/38329957/206375206-e9372c67-1cea-4f05-a5dc-08912cb111e4.jpg)

### 問題の固有名詞：希望する変更

ヴェネツィア：ヴェネト

### 変更の理由（概要）

ほぼ誤訳であるため

### 変更の理由（詳細）

州名で使われているVenetiaとは、ヴェネツィアのことではなくヴェネト州を意味している。
現にこの表記は、ロンバルド＝ヴェネト王国の英語表記（Kingdom of Lombardy–Venetia）等でも使用されている。

### ゲームバージョン

1.1.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Winterkonig** [comment]
VeneziaとVenetiaは違う単語ですね。
我が国では該当地域にあった墺帝国の下位国家は、
ロンバルド＝ヴェネト王国と呼ぶのが普通ですし、
現在の該当地域はヴェネト州と呼びますね。

**Comment by ChiefIdeologue** [comment]
内容通りに修正したため、クローズします。
