### ISSUE TITLE
transfer of powerのツールチップ

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#566]
### スクリーンショット

![TRANSFER_OF_POWER](https://user-images.githubusercontent.com/50406316/206531137-5fb8db7d-b395-4de7-911d-e751d4b4a261.png)

### 問題のツールチップ

政体ごとのtransfer of powerの説明

### 問題の表現

この[政府のタイプ]は、[〇〇]を採用します。[権力の移譲]

### 問題箇所の英文

This [Government Type] adopts a [〇〇] Transfer of Power

### 希望する変更

この[政府のタイプ]は[〇〇]により[権力の移譲]を行います

### 変更の理由（概要）

変数に対応した文章になっていないため

### プレイ国家

どこでも

### ゲームバージョン

1.1.X

### MOD有無

翻訳改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
希望案がtypoだったので訂正します。
誤：この[政府のタイプ]は[〇〇]により[権力の移譲]を行います
正：この[政府のタイプ]は[〇〇]による[権力の移譲]を行います

**Comment by starjard** [comment]
訂正後の提案通り修正を行いました。
