### ISSUE TITLE
Government Type

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#567]
### スクリーンショット

![TRANSFER_OF_POWER](https://user-images.githubusercontent.com/50406316/206532622-3e27240c-aea7-4b67-a484-a914ab7486b1.png)

### 問題の用語

政府のタイプ

### 英語版の表現

Government Type

### 希望する変更

政体

### 変更の理由（概要）

一般的で簡潔な表現に改訳

### 変更の理由（詳細）

一般的で簡潔な表現に改訳したいため。EU4和訳でもこれと同様に、Government Typeを政体と訳している。

### ゲームバージョン

1.1.X

### MOD有無

翻訳改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
提案通り修正しました。
