### ISSUE TITLE
モナン（州地域）

### ISSUE THREAD

**Issue by kurutto115** [matanki-saito/vic3jpadvmod#568]
### スクリーンショット

![Victoria 3 2022_12_09 15_52_20](https://user-images.githubusercontent.com/117251782/206679597-b2f2ff87-8e7b-462f-b5a0-c5457ea532bb.png)

### 問題の固有名詞：希望する変更

モナン：漠南

### 変更の理由（概要）

日本語では一般的でない表記のため

### 変更の理由（詳細）

「モナン」は恐らく「漠南」の中国語読みから来ている
漠南はゴビ砂漠の南側を意味し、内モンゴルと同義

### ゲームバージョン

1.1.X

### MOD有無

本プロジェクトMODのみ

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
起票ありがとうございます。ご提案の通り漠南に改訳しました。
