### ISSUE TITLE
外交戦での戦争目標追加の通知

### ISSUE THREAD

**Issue by kurutto115** [matanki-saito/vic3jpadvmod#569]
### スクリーンショット

![Victoria 3 2022_12_10 13_17_47](https://user-images.githubusercontent.com/117251782/206840872-5240bc68-353c-46ff-b091-9d42b58a0949.png)
（ロシアで外交戦を開始し、戦争目標を追加したところ）

### 問題のあるインターフェイス

戦争目標追加の通知の本文

### 問題のテキスト

ロシア**に向けて**戦争目標が追加されました。

### 希望する変更

ロシア**向けの**戦争目標が追加されました。

### 変更の理由（概要）

文章に実態と相違があるため

### 変更の理由（詳細）

ロシアがオランダから賠償金を受け取る戦争目標を追加したことによる通知だが、
本文はロシアが代償を支払う戦争目標が追加されたように読める。
実際はロシアが受け取る側なので、それが伝わる文章にしたい。
英文では"A War Goal has been added **for** Russia."

### ゲームバージョン

1.1.X

### MOD有無

無し

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。
