### ISSUE TITLE
【未訳】dictator

### ISSUE THREAD

**Issue by ikabomb** [matanki-saito/vic3jpadvmod#57]
## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/84853597/198165799-1ac5ae0b-7953-4c85-b40b-988d9ca01383.png)

## 問題のツールチップ（必須）

「軍事独裁制」のツールチップ

## 問題の表現（必須）

軍Dictatorが国を治める政府です。
軍[Concept('concept_ruler','Dictator')]が[concept_country]を治める[concept_government]です。

## 問題箇所の英文（任意）

This is a [concept_government] where the [concept_country] is ruled by a military [Concept('concept_ruler','Dictator')].

## 希望する変更（必須）

2バイト文字をここに入れても問題ないのなら、軍[Concept('concept_ruler','Dictator')]→軍事[Concept('concept_ruler','独裁者')]

## 変更の理由（必須）

未訳のため

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1034995078130831411
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by clamm0363** [comment]
ご提案どおりに修正いたしました。
なお、同様のストリングが他に2つありましたので、そちらも合わせて修正しています。

スレッドをクローズします。
