### ISSUE TITLE
マクロネシア海

### ISSUE THREAD

**Issue by kurutto115** [matanki-saito/vic3jpadvmod#570]
### スクリーンショット

![Victoria 3 2022_12_10 13_18_08](https://user-images.githubusercontent.com/117251782/206841230-ae1733ef-6a6c-439e-8b6b-1126d2063aa9.png)

### 問題の固有名詞：希望する変更

マクロネシア海：マカロネシア海

### 変更の理由（概要）

誤字

### 変更の理由（詳細）

（参考）[マカロネシア - Wikipedia](https://ja.wikipedia.org/wiki/%E3%83%9E%E3%82%AB%E3%83%AD%E3%83%8D%E3%82%B7%E3%82%A2)

### ゲームバージョン

1.1.X

### MOD有無

無し

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
ご提案どおり修正しました

クローズします
