### ISSUE TITLE
ドイツの州

### ISSUE THREAD

**Issue by kurutto115** [matanki-saito/vic3jpadvmod#571]
### 問題の固有名詞：希望する変更

ポメラニア：ポンメルン
北ライン：ノルトライン
シレジア：シュレージエン
ヘッセ：ヘッセン

### 変更の理由（概要）

他の州との整合性

### 変更の理由（詳細）

ドイツの他の州はヴェストファーレンや東プロイセンなどドイツ語名に由来する名称なのでそれに合わせる。
特にノルトラインとヘッセンはこちらの名称が日本では一般的と思われる。

### ゲームバージョン

1.1.X

### MOD有無

本プロジェクトMODのみ

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズします。
