### ISSUE TITLE
大隊/艦艇合計数のツールチップ

### ISSUE THREAD

**Issue by clamm0363** [matanki-saito/vic3jpadvmod#573]
### スクリーンショット

![image](https://user-images.githubusercontent.com/29382778/206891246-ea24596b-aff6-4825-8663-6dcd09b07f95.png)
![image](https://user-images.githubusercontent.com/29382778/206891254-9a8d32b0-7b09-446b-8e56-1a1d19a14607.png)

### 問題のツールチップ

軍事画面陸軍/海軍タブの総大隊数、総艦艇数のツールチップ

### 問題の表現

[STATE.GetName]による[GetUnitStrengthHeader( '(int32)$CURRENT$', '(int32)$MAX$', '$ICON$' )] $UNIT_NAME$

### 問題箇所の英文

[GetUnitStrengthHeader( '(int32)$CURRENT$', '(int32)$MAX$', '$ICON$' )] $UNIT_NAME$ from [STATE.GetName]

### 希望する変更

COMBAT_UNIT_SOURCES_BREAKDOWN_CLEAN:0 "[STATE.GetName]の$UNIT_NAME$[Nbsp][GetUnitStrengthHeader( '(int32)$CURRENT$', '(int32)$MAX$', '$ICON$' )]"

### 変更の理由（概要）

不自然な表現

### ゲームバージョン

1.1.X

### MOD有無

日本語修正MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
上記の通り修正しました

クローズします
