### ISSUE TITLE
形容詞形の処理

### ISSUE THREAD

**Issue by clamm0363** [matanki-saito/vic3jpadvmod#574]
### スクリーンショット

割愛

### 問題のツールチップ

全般

### 問題の表現

"[hogehoge.GetAdjective] fugafuga"のように、形容詞形の後ろにスペースを入れてあるもの

### 希望する変更

助詞「の」を補うなど、日本語として不自然でない表現にしたい

### 変更の理由（概要）

変数の処理が適切でないため

### ゲームバージョン

1.1.X

### MOD有無

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
上記の通り修正しました

クローズします
