### ISSUE TITLE
貿易ルートの競合（Trade Route Competitiveness）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#575]
### スクリーンショット

![20221211130106_1](https://user-images.githubusercontent.com/42687608/206893796-e04336a8-1659-4166-a11b-14c4e864c475.jpg)

### 問題の用語

貿易ルートの競合

### 英語版の表現

Trade Route Competitiveness

### 希望する変更

貿易ルートの競争力

### 変更の理由（概要）

実際のゲームメカニズムと異なっている

### 変更の理由（詳細）

このパラメーターは貿易競争力を表すため、誤訳である。

### ゲームバージョン

1.1.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
原案の通り確定し、修正を完了しました。
