### ISSUE TITLE
確率→確立

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#576]
### スクリーンショット

![20221210040656_1](https://user-images.githubusercontent.com/38329957/206889038-9df35563-d745-458f-8b7b-18c3212b22ad.jpg)

### 問題部分

本文

### 希望する変更（修正部分のみ）

評議会共和制を確率しました。
↓
評議会共和制を確立しました。

### 変更の理由（概要）

誤字

### プレイ国家

ロシア

### ゲームバージョン

1.1.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。
