### ISSUE TITLE
Platinean

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#578]
### スクリーンショット

![platinean](https://user-images.githubusercontent.com/50406316/206904839-11c3be94-3fa6-4b78-819b-34a1b8319c03.png)

### 問題の固有名詞：希望する変更

プラティニア：ラプラタ

### 変更の理由（概要）

形容詞から名詞への修正

### 変更の理由（詳細）

原文はPlatinean。
他の文化は英語では形容詞になっていても和訳では名詞（例：Frenchをフレンチではなくフランスとする）としているが、これは形容詞のままなので、名詞に修正したい。
なおPlatineanはスペイン語La Plataの英訳The Plateの形容詞。

### ゲームバージョン

None

### MOD有無

翻訳改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
提案通り修正を行いました。
