### ISSUE TITLE
資格取得（Qualifications、Qualifying）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#579]
### スクリーンショット

![20221211225716_1](https://user-images.githubusercontent.com/42687608/206908147-09184108-be7e-41db-8d64-844138c67cb7.jpg)
![20221211225750_1](https://user-images.githubusercontent.com/42687608/206908153-85ccc3ae-5a33-4a98-a2d2-02f532512f2d.jpg)

### 問題の用語

資格取得

### 英語版の表現

Qualifications / Qualifying

### 希望する変更

技能（取得）

### 変更の理由（概要）

日本語として自然な表現に変更

### 変更の理由（詳細）

ゲーム内の役割は「POPが特定の職業につくための条件」であり、識字率の向上などを通じて自動的に獲得する。
単語としてのqualificationsには「公的資格」という意味の他に「職業に必要な適性、技能」という意味があり、今回の場合はこちらの意味で訳すのが適当と思われる。

### ゲームバージョン

1.1.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
「職業要件」と修正し、関連するエントリも修正しました。

クローズします
