### ISSUE TITLE
【修正提案】Power Structure

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#58]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![power_structure](https://user-images.githubusercontent.com/50406316/198167954-315748ac-cd9c-49e9-86c3-5349223c2a43.png)

## 問題の用語（必須）
電力建造物

## 英語版の表現（任意）
Power Structure

## 希望する変更（必須）
権力構造

## 変更の理由（必須）
誤訳のため

## ゲームバージョン（必須）
1.0.3

## DLC有無（必須）
無し

## MOD有無（必須）
なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1034998189683646525
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by starjard** [comment]
権力構造に変更しました。クローズします。
