### ISSUE TITLE
◯年◯月月◯日（次の選挙の日付）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#580]
### スクリーンショット

![20221212150521_1](https://user-images.githubusercontent.com/42687608/206977298-b7766ed1-eddf-4dff-b3db-ff9446bbec81.jpg)

### 問題のあるインターフェイス

政策ウィンドウ

### 問題のテキスト

◯年◯月月◯日（次の選挙の日付を示すテキストで「月」が重複している）

### 希望する変更

◯年◯月◯日

### 変更の理由（概要）

インターフェイスの不備

### 変更の理由（詳細）

「月」が重複して表示されるのは不具合以外の何物でもない。

### ゲームバージョン

1.1.X

### MOD有無

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
修正済みの問題（Issue #162）が私のローカル環境でのみ再発していたようです。お騒がせしました。
