### ISSUE TITLE
incorporationのツールチップ

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#581]
### スクリーンショット

![incorporation](https://user-images.githubusercontent.com/50406316/207011242-76487488-eced-4db7-bd57-2883bed420f4.png)

### 問題のツールチップ

州をincorporateするときのツールチップ

### 問題の表現

１．主要文化
[(自国)]の[母国]であり、[(州の文化名)] [文化]である等の要因から、[(対象州)]の[(編入)]には計$XX$年の期間を要します。

２．主要文化と同系統の州
[(自国)]の[母国]であり、[(自国)]における他の$文化$と[系統文化特性] [(系統名)]を共有する[(州の文化名)] [文化]である等の要因から、[(対象州)]の[(編入)]には計$XX$年の期間を要します。

３．主要文化と非系統特性だけを共有する州
[(自国)]の[母国]であり、[(自国)]における他の$文化$と[文化特性] [(文化特性名)]を共有する[(州の文化名)] [文化]である等の要因から、[(対象州)]の[(編入)]には計$XX$年の期間を要します。

４．無関係文化の州
[(自国)]の[母国]であり、[(自国)]における他の$文化$と共有点がない等の要因から、[(対象州)]の[(編入)]には計$XX$年の期間を要します。

### 問題箇所の英文

１．主要文化
It takes $XX$ years in total to [Incorporate] [対象州] since it is a [Homeland] of [(自国)] due to its [(自国主要文化名)] [Culture].

２．主要文化と同系統の州
It takes $XX$ years in total to [Incorporate] [対象州] since it is a [Homeland] of the [(自国主要文化名)] [Culture], which shares the [Heritage Cultural Trait] [(系統名)] with another $Culture$ in [(自国)].

３．主要文化と非系統特性だけを共有する州
It takes $XX$ years in total to [Incorporate] [対象州] since it is a [Homeland] of the [(自国主要文化名)] [Culture], which shares the [Cultural Trait] [(系統名)] with another $Culture$ in [(自国)].

４．無関係文化の州
It takes $XX$ years in total to [Incorporate] [対象州] since its [Homeland] have nothing in common with any $concept_cultures$ in [(自国)].

### 希望する変更

１．主要文化
[(対象州)]は[(自国)]の文化である[(州の文化名)][文化]の[母国]であるため、[(編入)]には計$XX$年の期間を要します。

２．主要文化と同系統の州
[(対象州)]は[(州の文化名)][文化]の[母国]であり、[(自国)]の$文化$と[(系統名)]の[系統文化特性]を共有しているため、[(編入)]には計$XX$年の期間を要します。

３．主要文化と非系統特性だけを共有する州
[(対象州)]は[(州の文化名)][文化]の[母国]であり、[(自国)]の$文化$と[(文化特性名)]の[文化特性]を共有しているため、[(編入)]には計$XX$年の期間を要します。

４．無関係文化の州
[(対象州)]を[母国]とする$文化$と[(自国)]との間には共通点がないため、[(編入)]には計$XX$年の期間を要します。

### 変更の理由（概要）

変数に対応していない誤訳の修正

### 変更の理由（詳細）

変数に対応した文章になっておらず、誤訳でゲームルールに沿った説明になっていないため、正しい意味が通る文章に修正したい。

### プレイ国家

どこでも

### ゲームバージョン

1.1.X

### MOD有無

翻訳改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
ちなみに上のスクショの単語を当てはめると、改訳案ではこうなります。

１．主要文化
[ブルターニュ]は[フランス]の文化である[フランス][文化]の[母国]であるため、[編入]には計2年の期間を要します。

２．主要文化と同系統の州
[サント・ドミンゴ]は[カリベニョ][文化]の[母国]であり、[フランス]の文化と[ヨーロッパ系統]の[系統文化特性]を共有しているため、[編入]には計5年の期間を要します。

３．主要文化と非系統特性だけを共有する州
[ハイチ]は[アフリカ系アンティル][文化]の[母国]であり、[フランス]の文化と[フランス語圏]の[文化特性]を共有しているため、[編入]には計10年の期間を要します。

４．無関係文化の州
[アルジェ]を[母国]とする$文化$と[フランス]との間には共通点がないため、[編入]には計20年の期間を要します。

**Comment by starjard** [comment]
提案通り修正しました。
