### ISSUE TITLE
ブラジル人の姓名

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#582]
### スクリーンショット

なし

### 問題の固有名詞：希望する変更

オーレリオ：アウレーリオ
セルソー：セルソ
クストディオ：クストーディオ
デルフィム：デウフィン
エミリオ：エミーリオ
ゲトゥリオ：ジェトゥリオ
ヘンリケ：エンリケ
ヘルメス：エルメス
フムバート：ウンベルト
イサイアス：イザイアス
ジャスケリノ：ジュセリーノ
プルーデンテ：プルデンテ
タンクレド：タンクレード

デ・ボールペール・ロハン：ド・ボールペール＝ロアン
デ・アギアール：デ・アギアル
デ・サウザ・ネト：デ・ソウザ・ネト
デ・サラフ：デ・スルフ
ド・アルカンターラ：デ・アウカンタラ
ダ・シルヴァ・プラード：ダ・シウヴァ・プラド

ビッテンコート：ビタンクール
ブランダオ：ブランドン
カブラル・ダ・シルバ：カブラウ・ダ・シウヴァ
ダトラ：ドゥトラ
フラゴソ：フラゴーゾ
フロンティン：フロンタン
ガルヴァオ：ガウヴォン
ジョルダオ：ジョルドン
ラバトゥート：ラバテュ
マキエル：マシエウ
マレット：マレ
マルケス・デ・サウサ：マルケス・デ・ソウザ
モーリティ：マウリチ
オソリオ：オゾーリオ
ペイクスト：ペイショト
ペッソア：ペソア
サルダンハ・ダ・ガーマ：サルダーニャ・ダ・ガマ

アラガオ：アラガン
アサンカオ：アスンサン
バヒア：バイーア
バルボサ：バルボーザ
フィダルゴ：フィダウゴ
フィルホ：フィーリョ
オテロ：オテウォ
ペカンハ：ペサーニャ
シルヴァ：シウヴァ
デ・クルツ・エ・サウサ：デ・クルス・エ・ソウザ
デ・リマ・バレット：デ・リマ・バレト
デ・オーロ：デ・オウロ
デ・サウザ：デ・ソウザ

### 変更の理由（概要）

日本語では一般的ではない表記であるため

### ゲームバージョン

1.1.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
