### ISSUE TITLE
将軍同伴（With General）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#583]
### スクリーンショット

![20221213165023_1](https://user-images.githubusercontent.com/42687608/207289390-c78fc0ed-32d3-4670-a131-1a739728c544.jpg)

### 問題のあるインターフェイス

軍事ウィンドウ

### 問題のテキスト

将軍同伴

### 希望する変更

将軍指揮下

### 変更の理由（概要）

日本語として不自然な表現

### 変更の理由（詳細）

同伴は将軍に対して用いる日本語ではない。

### ゲームバージョン

1.1.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
将軍指揮下、で修正
