### ISSUE TITLE
ハンガリー人の姓名

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#584]
### スクリーンショット

なし

### 問題の固有名詞：希望する変更

アラジョス：アラヨシュ
アナスタズ：アナスターズ
アンドラス：アンドラーシュ
アリスティッド：アリスティド
オーレル：アウレール
バータラン：ベルタラン
ベラ：ベーラ
ベニ：ベーニ
ダニエル：ダーニエル
エドヴァード：エドヴァールド
フェレンズ：フェレンツ
ガイラ：ジュラ
ギョルギー：ジェルジ
ガボール：ガーボル
ガブリエル：ガーブリエル
ガスパー：ガーシュパール
イグナーク：イグナーツ
イストヴァン：イシュトヴァーン
イジドール：イズィドル
ジャノス：ヤーノシュ
ジョセフ：ヨージェフ
ジョゼフ・マネス：ヨージェフ・メネシュ
カルマン：カールマーン
カロリー：カーロイ
ラジョス：ラヨシュ
ラズロ：ラースロー
マノ：マノー
ミハリー：ミハーイ
ミクロス：ミクローシュ
ピーター：ペーテル
サンドール：シャーンドル
ティヴァダール：ティヴァダル
ヴィルモス：ヴィルモシュ
ヴィラグ：ヴィラーグ
シグモンド：ジグモンド
アルモス：アールモシュ
エリアス：エーリアーシュ
オドン：エデン

アマリア：アマーリア
フルツィーナ：フルズィナ
ジュディット：ユディト
コルネリア：コルネーリア
ポリクセニア：ポリクセーニア
テレズ：テレーズ
ツザンナ：ジュジャンナ

アンドラッシー：アンドラーシ
ディーク：デアーク
エレニー・ウルマン：エレーニ・ウッルマン
フラカシャツィ・フィッシャー：フラカシャーズィ・フィッシャー
ラクツォヴィクス：ラツコヴィチ
ライニンゲン・ヴェステルブルク：ライニンゲン＝ヴェスターブルク
ズリニー：ズリーニ
ステフィクス：シュテフィチ

アッポニー：アッポニ
オーリッヒ：アウリヒ
バッハー：バッヒャー
バロス：バロッシュ
バティヤニー：バッチャーニ
ビョーティ：ベエティ
ボスマー：ボトマー
フォン・ボスマー：フォン・ボトマー
ダムヤニフ：ダムヤニチ
デッセウフィ：デジェーフィ
エグレッシー：エグレッシ
ファルカス：ファルカシュ
ゴルドツィアー：ゴルトツィーエル
ホーツマン：ハウスマン
ホーシー：ホルティ
イズソ：イジョー
ジャスザイ：ヤーサイ
ジョセフィー：ヨシェッフィ
キスキッシ：キッシュ
ネツィヒ：クネズィチ
ケラー：ケーレル
リスツ：リスト
ラザール：ラーザール
ミクザス：ミクサート
ナギー・サンドール：ナジ＝シャーンドル
ペルツェル：ペルチェル
ポエルテンベルク：ペールテンベルク
レメニー：レメーニ
ロール：ローア
セーメア：セメレ
セラヴィク：スラーヴィツ
テルスティアンスキー：テルスチャーンシュキ
ヴェクセイ：ヴェーチェイ

### 変更の理由（概要）

日本語では一般的ではない表記であるため

### ゲームバージョン

1.1.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
