### ISSUE TITLE
法律改正のツールチップ

### ISSUE THREAD

**Issue by clamm0363** [matanki-saito/vic3jpadvmod#585]
### スクリーンショット

![image](https://user-images.githubusercontent.com/29382778/207472127-1cd9e680-fb2e-493f-9ac5-46cae58fd0c1.png)

### 問題のツールチップ

最近改正しようとした法律への改正ツールチップ

### 問題の表現

～日日待つ必要があります

### 希望する変更

～日待つ必要があります

### 変更の理由（概要）

不要な「日」が含まれているため

### ゲームバージョン

1.1.X

### MOD有無

日本語修正MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
上記の通り修正しました

クローズします
