### ISSUE TITLE
◯◯制度の無効化（Enables the Institution）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#587]
### スクリーンショット

![20221214135258_1](https://user-images.githubusercontent.com/42687608/207509273-27c52871-6e48-4928-b1bb-4112704b2264.jpg)

### 問題のあるインターフェイス

法律のポップアップウィンドウ

### 問題のテキスト

◯◯制度の無効化

### 希望する変更

◯◯制度の有効化

### 変更の理由（概要）

誤訳のため

### 変更の理由（詳細）

EnableとDisableを取り違えた純粋な誤訳。
該当するキーはPROVIDES_INSTITUTION。

### ゲームバージョン

1.1.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
原案の通り修正しました。
