### ISSUE TITLE
ポーランド人の姓名

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#588]
### スクリーンショット

なし

### 問題の固有名詞：希望する変更

アレクサンダー：アレクサンデル
アントーニ：アントニ
ボレスラウ：ボレスワフ
ボナウェントゥラ：ボナヴェントゥラ
ブロニスラウ：ブロニスワフ
デジデリー：デズィデリ
エウスタシー：エウスタヒ
フェリシャン：フェリツィアン
フランツィツェク：フランチシェク
グスタウ：グスタフ
ヘンリーク：ヘンリク
イグナシー：イグナツィ
ジャクブ：ヤクプ
ジャン：ヤン
ジェドレイ：イェンジェイ
ジュリウス：ユリウシュ
ジョゼフ：ユゼフ
キャロル：カロル
カジミエーズ：カジミェシュ
レック：レフ
ルシャン：ルツィアン
ルドウィク：ルドヴィク
マシェイ：マチェイ
マルセリ：マルツェリ
マリウス：マリウシュ
メルキオール：メルヒオール
ミカール：ミハウ
ミエシュスラウ：ミェチスワフ
ロマルド：ロムアルト
スタニスラウ：スタニスワフ
タデウス：タデウシュ
トマス：トマシュ
ウアクラウ：ヴァツワフ
ウィトルド：ヴィトルト
ウラディスラウ：ヴワディスワフ
ウォジェシュ：ヴォイチェフ

エルズビエタ：エルジュビェタ
フランシツカ：フランチシカ
ガートルーダ：ギェルトルーダ
ジョゼファ：ユゼファ
コンスタンツァ：コンスタンツィア

ボー・コモロフスキー：ブル＝コモロフスキ
ダニン：ドゥーニン
グロヴァキー：グウォヴァツキ
ハウケ・ボサック：ハウキェ＝ボサク
イワシェキーヴィッチ：イヴァシュキェヴィチ
ピルスドスキー：ピウスツキ
プラーター：プラテル
ポトキ：ポトツキ
ラドジウィル：ラジヴィウ
ローラ・ジミエルスキー：ロラ＝ジミェルスキ
リズ・スミグリー：リズ＝シミグウィ
サピーハ：サピェハ
ツツコウスキー：トゥトコフスキ
ウィーロポルスキー：ヴィエロポルスキ
ヴィエニアワ・ドルゴスゾウスキー：ヴィエニャヴァ＝ドゥウゴショフスキ

ベム：ベン
ブルゾスカ：ブズスカ
シャラシンスキー：ハワシニスキ
クラポウスキー：フワポフスキ
クロピッキ ：フウォピツキ
クラザノウスキー：フジャノフスキ
ダブロウスキー：ドンブロフスキ
デムビンスキー：デンビンスキ
ファブリシー：ファブリツィ
イスジコウスキー：イジコフスキ
ヤシンスキー：ヤシニスキ
クリッキ：クリツキ
コノプスジンスキー：コノプチニスキ
クルコヴィエキ：クルコヴィエツキ
クルシェヴスキー：クルシェフスキ
ランギエヴィチ：ランギェヴィチ
マダリンスキー：マダリニスキ
ミエロスラウスキー：ミェロスワフスキ
ミコラチェク：ミコワイチク
モクロンフスキー：モクロノフスキ
ニエポコルチェキ：ニェポクウチツキ
ノワク：ノヴァク
オストロフスキー：オストロフスキ
パク：パツ
ポニアトウスキー：ポニャトフスキ
プレアジンスキー：プロンズィニスキ
ロコソウスキー：ロコソフスキ
リビンスキー：リビニスキ
ロジッキー：ルジツキ
サングスコ：サングシュコ
スクルチェネク：スクジネツキ
ソルティク：ソウティク
ソウィンスキー：ソヴィニスキ
タクザネオフスキー：タチャノフスキ
ワオレチェキ：ヴァフジェツキ
ザヤチェク：ザヨンチェク
ザルスキー：ザウスキ
ザモイスキー：ザモイスキ
ゼリゴヴスキー：ジェリゴフスキ

### 変更の理由（概要）

日本語では一般的ではない表記であるため

### ゲームバージョン

1.1.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
