### ISSUE TITLE
州の固有補正名

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#589]
### スクリーンショット

なし

### 問題の固有名詞：希望する変更

ドラバ川：ドラーヴァ川
スコティッシュハイランド：スコットランド高地
シュバルツバルト：シュヴァルツバルト
ロシアのタイガ林：ロシアのタイガ森
ボルガ川：ヴォルガ川
イギリス石炭鉱床：ブリテンの石炭鉱床
ウクライナの黒土：チェルノーゼム
スカニアの土壌：スコーネの土壌
グレートディバイディング山脈：グレートディヴァイディング山脈
カスケード：カスケード山脈
アンデス：アンデス山脈
パンタナール：パンタナル
ナイアガラ滝：ナイアガラの滝
ニューヨーク湾：ニューヨーク港
ニューアーク湾：ニューアーク港
ノールパドカレー炭田：ノール＝パ・ド・カレー炭田
アッパーシレジア田：オーバーシュレージエン炭田
クルカ滝：クルカの滝
ウォーターバーグ炭田：ヴァーテルベルク炭田
ターコイズ鉱床：トルコ石鉱床
カーベリ・デルタ：カーヴィリ・デルタ
ビルマチーク：ビルマ産チーク
四川盆地：赤色盆地

### 変更の理由（概要）

一部の意味が分かりにくい

### ゲームバージョン

1.1.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズします。
