### ISSUE TITLE
【未訳】ツールチップ「主要文化」内のforms a different

### ISSUE THREAD

**Issue by 30denarius** [matanki-saito/vic3jpadvmod#59]
## スクリーンショット（必須）
![20221027101400_1](https://user-images.githubusercontent.com/105610712/198168147-ea3e511b-b558-4d01-9f5d-173059820b05.jpg)

## 問題のツールチップ（必須）

文化タブ内「主要文化」のツールチップ

## 問題の表現（必須）

forms a different

## 希望する変更（必須）

国家の形成

## 変更の理由（必須）

forms a differentはツールチップとして「国家の形成」に翻訳されているのでそちらに合わせるべき

## ゲームバージョン（必須）

1.0.1

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by clamm0363** [comment]
「主に[国民国家]と関係する[文化]のことです。ある[国]が[異なる国家を形成]すると、その[主要文化]が変わることもありますが、主要文化が変わらない場合はそれ以前の文化を維持します。[改行後割愛]」

以上のように修正しました。[国民国家]の部分は別のissueで起票しています。

クローズします。
