### ISSUE TITLE
世襲制/任命制/選挙制の官僚

### ISSUE THREAD

**Issue by nagi0330** [matanki-saito/vic3jpadvmod#590]
### スクリーンショット

![200175146-eba331d8-a795-40fd-ae88-037fd42e19f5](https://user-images.githubusercontent.com/6514922/208041950-43ae1bc8-65ce-4054-a871-1f1fa64510b4.png)

### 問題の固有名詞：希望する変更

世襲制の官僚：？？？？
任命制の官僚：官選知事
選挙制の官僚：民選知事

### 変更の理由（概要）

分かりやすさと歴史を重視

### 変更の理由（詳細）

世襲制の官僚の対案が思い浮かばないのですが、ツールチップを読む限りでは民選官選の話だと思うので、議論したいです。

### ゲームバージョン

1.2.X

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
内部での検討の結果、この文章はシステム的なものではないフレーバー文であり、原文の時点で知事を意味するものではないBureaucratsであるため、原文を尊重して修正はしないことが決定しました。

以上で議論をクローズします。
