### ISSUE TITLE
ロシアの人名（歴史人物）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#594]
### 問題の固有名詞：希望する変更

フィラレット・ドロズドフ：フィラレート・ドゥロズドフ
アレクサンドル・フォン・ベッケンドルフ：アレクサンドル・フォン・ベンケンドルフ

### 変更の理由（概要）

日本語では一般的でない表記であるため

### 変更の理由（詳細）

ランダム人名で使用されるキーは対象外。修正対象は以下の通り。
Filaret / Drozdov
von_Benckendorff

### ゲームバージョン

1.1.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
Filaret（フィラレート）とvon_Benckendorff（フォン・ベンケンドルフ）のみ修正しました。
