### ISSUE TITLE
中南米の人名（重要なランダム名）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#599]
### 問題の固有名詞：希望する変更

サンタ・クルツ：サンタ・クルス
デ・サンタ・クルツ：デ・サンタ・クルス
デ・ラ・サンタ・クルツ：デ・ラ・サンタ・クルス
ロペズ・デ・サンタ・アンナ：ロペス・デ・サンタ・アナ
ユアン・マニュエル：フアン・マヌエル
ユアン・ラモン：フアン・ラモン

### 変更の理由（概要）

日本語では一般的でない表記であるため

### 変更の理由（詳細）

ゲーム開始時の中南米の歴史人物に使用される。修正対象のキーは以下の通り。
Santa_Cruz
de_Santa_Cruz
de_la_Santa_Cruz
Lopez_de_Santa_Anna
Juan_Manuel
Juan_Ramon

### ゲームバージョン

1.1.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
原案の通り修正しました。
