### ISSUE TITLE
民衆の春（Springtime of the Peoples、ジャーナル）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#600]
### スクリーンショット

![20221220121722_1](https://user-images.githubusercontent.com/42687608/208573547-18fb684c-ce70-41de-a2d8-7cdd47705a87.jpg)

### 問題部分

タイトル

### 問題のイベントタイトル

民衆の春

### 希望する変更（修正部分のみ）

諸国民の春

### 変更の理由（概要）

日本語では一般的でない表記であるため

### 変更の理由（詳細）

Wikipediaによると「Springtime of the Peoples」は「Springtime of Nations」と同じく「Revolutions of 1848」の別名です。
これに該当する日本語の定訳は「諸国民の春」であり、この訳を外すと本来の意図が伝わらなくなります。

参考：
[英語版Wikipedia](https://en.wikipedia.org/wiki/Revolutions_of_1848)
[日本語版Wikipedia](https://ja.wikipedia.org/wiki/1848%E5%B9%B4%E9%9D%A9%E5%91%BD)

### プレイ国家

プロイセン

### ゲームバージョン

1.1.X

### MOD有無

自作Mod多数

**Comment by Winterkonig** [comment]
日本の教育における世界史でも「諸国民の春」と呼ぶのが定訳ですし、「諸国民の春」とすべきと考えます。

**Comment by oooFUNooo** [comment]
原案のとおりに修正しました。
