### ISSUE TITLE
"Electrics Industries"電気産業

### ISSUE THREAD

**Issue by Winterkonig** [matanki-saito/vic3jpadvmod#601]
### 問題の用語

電気産業

### 英語版の表現

Electrics Industries

### 希望する変更

電器産業

### 変更の理由（概要）

日本語の意味と違いがあるため

### 変更の理由（詳細）

電気産業は発電や送電の産業、つまり現代日本でいうところの関東電力や関西電力のことを指すと思います。
実際のElectrics Industriesは電話や無線機を生産する産業なので「電器」を生産する産業、つまり「電器産業」です。

### ゲームバージョン

1.1.X

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
お疲れ様です。内部でも意見が取り交わされましたが最終的に公式訳である「電気産業」を維持することになりました。
理由としては英語はElectricsとだけあり、そこに電器（電気機器）といった略語の意味を含んだ反映をさせるべきなのかという意見があります。

また下記の内容については、内部で疑問がつきました。このあたりの根拠などがありましたら示していただけると助かります。

> 電気産業は発電や送電の産業、つまり現代日本でいうところの関東電力や関西電力のことを指すと思います
