### ISSUE TITLE
Vatican City

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#602]
### スクリーンショット

![vatican](https://user-images.githubusercontent.com/50406316/209119249-d91ea300-b147-4e4c-9777-fa82f78b7d7f.png)

### 問題の固有名詞：希望する変更

バチカン市国：バチカン市

### 変更の理由（概要）

誤訳の修正

### 変更の理由（詳細）

ローマにあるモニュメントのこと。
バチカン市国はVatican City Stateだが、こちらは単にVatican Cityなので、市国ではなくバチカン市を指している。
Vatican Cityの略称でバチカン市国を指す用例もあるが、1836年時点でまだ教皇領が存在するこのゲームにおいてはバチカン市国の訳は適切ではない。

### ゲームバージョン

1.1.X

### MOD有無

翻訳改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
提案通り改訳しました。
