### ISSUE TITLE
従属国国

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#603]
### スクリーンショット

※上から翻訳改善MOD使用時、日バニラ、英バニラ
![subject_ja](https://user-images.githubusercontent.com/50406316/209124930-709d0aa1-376a-40f5-8c6b-b4cf91b88ef5.png)
![subject_ja_vanilla](https://user-images.githubusercontent.com/50406316/209124943-843af717-7f3f-4288-b1f3-8d41c759d691.png)
![subject_en](https://user-images.githubusercontent.com/50406316/209124954-b132a1a0-fe5c-49ef-8e14-6b934a36e1af.png)

### 問題のあるインターフェイス

ゲームルール設定画面

### 問題のテキスト

従属国国

### 希望する変更

従属国

### 変更の理由（概要）

「国」が二重になっていることの修正

### 変更の理由（詳細）

以前のissueでsubjectを家臣から従属国に改訳した影響で、この画面で従属国国と二重に出てしまっているので修正したい。

### ゲームバージョン

1.1.X

### MOD有無

翻訳改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
提案通り変更しました。
