### ISSUE TITLE
Raid Convoys 輸送船団の襲撃

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#604]
### スクリーンショット

![raid1](https://user-images.githubusercontent.com/50406316/209377837-7a7fcf6d-7985-4fa5-988b-060813c1b049.png)

### 問題のあるインターフェイス

提督の輸送船団の襲撃

### 問題のテキスト

輸送船団の襲撃

### 希望する変更

輸送船団襲撃

### 変更の理由（概要）

文字溢れしているため

### 変更の理由（詳細）

7文字だと文字溢れするが6文字だと収まるため、「の」を削りたい

### ゲームバージョン

1.1.X

### MOD有無

翻訳改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
議論の結果、「船団襲撃」と修正しました

クローズします
