### ISSUE TITLE
ザンジ（戦略的重要地域）

### ISSUE THREAD

**Issue by kurutto115** [matanki-saito/vic3jpadvmod#606]
### スクリーンショット

![Victoria 3 2022_12_24 21_46_53](https://user-images.githubusercontent.com/117251782/209467174-0740decf-9332-431d-b582-cb9b3f1d5a73.png)

### 問題の固有名詞：希望する変更

ザンジ：ザンジュ

### 変更の理由（概要）

日本語では一般的でない表記のため

### 変更の理由（詳細）

カナ表記では「ザンジュ」とするのが一般的なようです
（参考）[ザンジュ - Wikipedia](https://ja.wikipedia.org/wiki/%E3%82%B6%E3%83%B3%E3%82%B8%E3%83%A5)

### ゲームバージョン

1.1.X

### MOD有無

無し

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
チーム内での議論が長引いてしまい、回答が遅くなりすみません。
議論の結果、「ザンジ」「ザンジュ」ともに辞典で使用例があることと、日本語ではマイナーな地名であり何らかの一般的な表記が確立しているとは言い難いことから、現行訳の「ザンジ」でも誤りではないとして現状維持にすることとしました。
以下は辞典による使用例です。

ザンジ
https://kotobank.jp/word/%E3%82%B6%E3%83%B3%E3%82%B8%E3%81%AE%E4%B9%B1-70749
（ブリタニカ国際大百科事典）

ザンジュ
https://kotobank.jp/word/%E3%82%B6%E3%83%B3%E3%82%B8%E3%83%A5%E3%81%AE%E4%B9%B1-1170025
（平凡社世界大百科事典、小学館日本大百科全書、旺文社世界史事典）
