### ISSUE TITLE
Dai NamとAnnam

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#607]
### スクリーンショット

![Dai Nam](https://user-images.githubusercontent.com/50406316/209981131-685f9229-93da-4f2e-a604-da4102278b17.png)
![Annam](https://user-images.githubusercontent.com/50406316/209981511-006ee0fa-7a19-462b-9d1a-ad46da4c9e96.png)

### 問題の固有名詞：希望する変更

ベトナム：大南
アンナム：アンナン

### 変更の理由（概要）

誤訳（ベトナム）/日本語では一般的でない表記のため（アンナム）

### 変更の理由（詳細）

国名のほうは原文Dai Namで、当時の国号の大南国のこと。
州名のほうは原文Annamで、仏印時代の中部を指す名称として使われており、安南またはアンナンと書く。ゲームでは北のトンキンがカタカナ表記のため、こちらもカタカナとしたい。
https://ja.wikipedia.org/wiki/%E5%AE%89%E5%8D%97

### ゲームバージョン

1.1.X

### MOD有無

翻訳改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。
