### ISSUE TITLE
国名 Aussa オーッサ→アウサ

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#609]
### 問題の固有名詞：希望する変更

Aussa：アウサ
Aussan：アウサ

### 変更の理由（概要）

正確な音訳ではないため

### 変更の理由（詳細）

Aussaの音訳については日本語版wikipediaが「オーッサ」ではあるものの、参考文献に日本語資料がないことから英語版の翻訳記事であり、確証がない。一方でアフリカ史について造詣のある方のツイートでは「アウサ」表記がより正確な旨が書かれていることから、「アウサ」表記の方が妥当性が高いと判断。
https://twitter.com/koriuaca_USCA/status/1575057559639457792?s=20&t=9nXqeoQQzGmE_M8MgAPmzg
https://twitter.com/koriuaca_USCA/status/1612694713496395779?s=20&t=9nXqeoQQzGmE_M8MgAPmzg

### ゲームバージョン

1.2.X

### MOD有無

無し

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通り修正しました
