### ISSUE TITLE
【修正提案】戦争概要画面のタブ

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#61]
## スクリーンショット（必須）

![20221027131612_1](https://user-images.githubusercontent.com/42710893/198191045-b509fd09-40be-45c4-9aa9-809d7af3ba0d.jpg)

## 問題のあるインターフェイス（必須）

戦争概要画面のタブ

## 問題のテキスト（必須）

平和にする

## 希望する変更（必須）

英語版ではMake Peaceですが
タブの内容は和平協定に関する内容なので
和平協定 or 和平交渉で良いのではないかと思います。

## 変更の理由（必須）

平和にするでは意味がわかりにくい。

## ゲームバージョン（必須）

1.0.3

## DLCの有無（必須）

なし

## MODの有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1035047204802539551
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by Zousuikakka** [comment]
和平交渉で修正しました
