### ISSUE TITLE
タイトル画面でヴィキペディアを参照し、特定文字列にマウスを重ねるとゲームがクラッシュする

### ISSUE THREAD

**Issue by Nebimo** [matanki-saito/vic3jpadvmod#610]
### スクリーンショット

![2023_01_12_32_edit](https://user-images.githubusercontent.com/122381244/212083696-7922ca96-0282-4995-b163-ebb439a763ba.png)

### 問題のツールチップ

タイトル画面におけるヴィキペディアでの「貿易ルート」の黄色に近い色の「取引所」

### 問題の表現

concept_trade_route_desc:0 "$concept_trade_routes$がある[concept_market]で[Concept('concept_good','$concept_goods$')]を$concept_buy_order_short$、[concept_convoys]を使用して ($concept_markets$が隣接していれば陸路でも可) 他の場所へと運び、$concept_goods$を$concept_sell_order_short$し、[GetBuildingType('building_trade_center').GetName]で[concept_revenue] ([concept_tariffs]はここから差し引かれます) を稼ぎます。その過程で2つの$concept_markets$に[Concept('concept_buy_orders','$concept_buy_order_short$')]と[concept_sell_orders]が生まれ、一方では高く、一方では安くなります。$concept_goods$の量は、両方の$concept_market$の状況に合わせてそれぞれ独立して増減し、それに合わせて[concept_workforce]が雇用も増減します。各$concept_trade_route$は、維持するために一定量の[concept_bureaucracy]を消費します。"

### 問題箇所の英文

concept_trade_route_desc:4 "$concept_trade_routes$ $concept_buy_order_short$ [Concept('concept_good', '$concept_goods$')] on one [concept_market], transport it to another using [concept_convoys] (or overland, if the $concept_markets$ are adjacent), and $concept_sell_order_short$ the $concept_goods$ there in order to make [concept_revenue] (from which [concept_tariffs] are subtracted) for the [SelectLocalization(GetPlayer.IsValid,'concept_trade_route_desc_added','Trade Center')] managing it. In the process it creates [Concept('concept_buy_orders','$concept_buy_order_short$')] and [concept_sell_orders] on the two $concept_markets$, making it more expensive in one and less in the other. The volume of $concept_goods$ moved will independently scale up and down to meet the $concept_market$ conditions in both, employing more or less [concept_workforce] to match. Each $concept_trade_route$ costs a fixed amount of [concept_bureaucracy] to maintain."

### 希望する変更

 concept_trade_route_desc:0 "$concept_trade_routes$がある[concept_market]で[Concept('concept_good','$concept_goods$')]を$concept_buy_order_short$、[concept_convoys]を使用して ($concept_markets$が隣接していれば陸路でも可) 他の場所へと運び、$concept_goods$を$concept_sell_order_short$し、[SelectLocalization(GetPlayer.IsValid,'concept_trade_route_desc_added','Trade Center')]で[concept_revenue] ([concept_tariffs]はここから差し引かれます) を稼ぎます。その過程で2つの$concept_markets$に[Concept('concept_buy_orders','$concept_buy_order_short$')]と[concept_sell_orders]が生まれ、一方では高く、一方では安くなります。$concept_goods$の量は、両方の$concept_market$の状況に合わせてそれぞれ独立して増減し、それに合わせて[concept_workforce]が雇用も増減します。各$concept_trade_route$は、維持するために一定量の[concept_bureaucracy]を消費します。"

### 変更の理由（概要）

ゲームがクラッシュする為

### 変更の理由（詳細）

日本語バニラ環境の下記
[GetBuildingType('building_trade_center').GetName]

を英語版バニラ環境の下記
[SelectLocalization(GetPlayer.IsValid,'concept_trade_route_desc_added','Trade Center')]

に置き換えたら、クラッシュは回避できました。
なおどこでも良いのでどっかの国に入った状態だとクラッシュしません。(普通にプレイ中の国の取引所情報が抽出される)

### ゲームバージョン

1.2.X

**Comment by matanki-saito** [comment]
@Nebimo san
お疲れ様です。ご指摘の通り問題を確認したためMOD側は修正をしました。またお手数ですが、Paradoxフォーラムへ報告をお願い致します。よろしくお願い致します。

**Comment by Nebimo** [comment]
対応遅れすみませんが、先ほどForumの方に報告をしておきました。
