### ISSUE TITLE
好色的でモロッコな電車の車掌

### ISSUE THREAD

**Issue by WoodlandsGitHub** [matanki-saito/vic3jpadvmod#611]
### スクリーンショット

![image](https://user-images.githubusercontent.com/29177147/212534456-1c3d4a98-a13b-4a80-b8c9-4a2a803af942.png)

### 問題部分

本文

### 問題のイベントタイトル

放蕩文学

### 問題のイベント本文（抜粋可）

```
 free_speech_laws.5.f:0 "「[SCOPE.sCharacter('ruler_scope').GetPrimaryRoleTitle]は、我々の価値観の模範となるべき存在であり、[SCOPE.sCharacter('ruler_scope').GetSheHe]が、「[SCOPE.GetRootScope.GetCountry.GetCustom('horny_adjective')]で [SCOPE.sCountry('neighbour_country').GetAdjectiveNoFormatting]な[SCOPE.GetRootScope.GetCountry.GetCustom('job_title')]」などというハレンチな物を読んでいるという事実はまったくもって受け入れがたい」"
```

### 希望する変更（修正部分のみ）

書籍のタイトル部分のみ
```
「[SCOPE.GetRootScope.GetCountry.GetCustom('horny_adjective')]な [SCOPE.sCountry('neighbour_country').GetAdjectiveNoFormatting]人の[SCOPE.GetRootScope.GetCountry.GetCustom('job_title')]」
```

「（国名）人の」にするか「（国名）の」するかはお任せします。

### 変更の理由（概要）

自動生成の文章が不自然

### 変更の理由（詳細）

Victoriaシリーズの国内コミュニティのDiscordから
https://discord.com/channels/784400186054148096/845374848707854377/1064082644603764776

自動生成される本のタイトルで、2か所目の単語を形容詞扱いして訳されている。
しかし、そこには国名が必ず入るので、不自然な日本語になる。
タイトルとしてひねった表現であり面白いという判断はありそうだが、一応修正対象と考え報告を上げる。

### プレイ国家

不明

### ゲームバージョン

None

### MOD有無

不明

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
```「[SCOPE.GetRootScope.GetCountry.GetCustom('horny_adjective')]な[SCOPE.sCountry('neighbour_country').GetAdjectiveNoFormatting]人[SCOPE.GetRootScope.GetCountry.GetCustom('job_title')]」```
例）「破廉恥モロッコ人メイド」

同時に変数に入る形容詞・職業名も以下のように修正することになりました。
・形容詞
> Naughty 好き者
> Filthy 背徳
> Lusty 好色
> Cheeky 魔性の
> Promiscuous 淫乱
> Shameless 破廉恥

・職業
> Maid メイド
> Gardener 庭師
> Chimney Sweep 煙突掃除士→煙突掃除夫
> Train Conductor 列車の車掌→車掌
> Coal Miner 石炭労働者→炭鉱夫
> Plumber 配管工
> Smelter 製錬工
> Bureaucrat 官僚
> Professor 教授
> Nurse 看護師→看護婦

起票ありがとうございました。
