### ISSUE TITLE
実績名（Hegemon）

### ISSUE THREAD

**Issue by TdHskw** [matanki-saito/vic3jpadvmod#612]
### スクリーンショット

![jisseki](https://user-images.githubusercontent.com/108180041/212884803-13cb2ad3-cf02-4f6a-951c-f303e55bc38a.png)

### 問題の用語

覇権

### 英語版の表現

Hegemon

### 希望する変更

覇者

### 変更の理由（概要）

誤訳

### 変更の理由（詳細）

Hegemonは覇権そのものではなく、覇権を持つものを指す英語である。覇権にあたる英語はHegemony。

### ゲームバージョン

1.1.X

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通りで修正しました
