### ISSUE TITLE
実績名（The Western Protectorate）

### ISSUE THREAD

**Issue by TdHskw** [matanki-saito/vic3jpadvmod#613]
### スクリーンショット

![jisseki](https://user-images.githubusercontent.com/108180041/212885478-808770df-7284-4e34-80d9-de2318efe55c.png)

### 問題の用語

西部保護領

### 英語版の表現

The Western Protectorate

### 希望する変更

西域保護府

### 変更の理由（概要）

元の言葉遊びを生かした訳にしたいため

### 変更の理由（詳細）

英語のThe Western Protectorateとは古代中国にあった西域都護府のことで、これを保護国を意味する英語のProtectorateをかけた言葉遊びなので、日本語でもそれがわかるような訳語に変えたい。

### ゲームバージョン

1.1.X

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通りで修正しました
