### ISSUE TITLE
君主像イベントでの補正「～承認していない。」

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#614]
### スクリーンショット

![image](https://user-images.githubusercontent.com/37979626/213848132-069810b6-bb38-4898-9f46-c8bea984f4e7.png)

### 問題のツールチップ

イベント「[SCOPE.sCharacter('statue_ruler').GetPrimaryRoleTitle]の記念碑」>「誰もが[SCOPE.sCharacter('statue_ruler').GetPrimaryRoleTitle]を思い出したいわけではないのかもしれない。」マウスオーバー

### 問題の表現

君主像を承認していない
君主像を承認している。
君主像が建立されないことを承認していない。
君主像が建立されないことを承認している。
君主像の撤去を承認している。
君主像が撤去されないことを承認している。

### 問題箇所の英文

Disapproves of Monarch Statue
Approves of Monarch Statue
Disapproves of Monarch Statue Not Being Raised
Approves of Monarch Statue Not Being Raised
Approves of Monarch Statue Being Removed
Approves of Not Removing Monarch Statue

### 希望する変更

君主像に不賛成
君主像に賛成
君主像の建立反対に不賛成
君主像の建立反対に賛成
君主像の撤去に不賛成
君主像の撤去反対に賛成

### 変更の理由（概要）

誤訳

### 変更の理由（詳細）

#538 と同様で英語では"get [補正名]"であるため、句点が含まれていても問題なかったが、日本語では「[補正名]を得ます」と語順が変わってしまう。

### プレイ国家

ロシア

### ゲームバージョン

1.1.X

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
提起後にミスがあったため、修正案を一部変更しました。

君主像に不賛成
君主像に賛成
君主像の建立反対に不賛成
君主像の建立反対に賛成
君主像の撤去に不賛成
君主像の撤去反対に賛成

**Comment by inarizushi0309** [comment]
原案通りで修正しました
