### ISSUE TITLE
制限なき潜水艦戦

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#615]
### スクリーンショット

翻訳作業所内での発見のため、スクショ無し

### 問題のツールチップ

イベント「最新鋭の潜水艦」での補正

### 問題の表現

制限なき潜水艦戦

### 問題箇所の英文

Unrestricted Submarine Warfare

### 希望する変更

無制限潜水艦作戦

### 変更の理由（概要）

一般的な表現にするため

### 変更の理由（詳細）

これはWW1にドイツが実施した「無制限潜水艦作戦」のことを指しているため

### プレイ国家

どこでも

### ゲームバージョン

1.1.X

### MOD有無

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通りで修正しました
