### ISSUE TITLE
【誤訳】車両通行規制なしの非承認

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#616]
### スクリーンショット

翻訳作業所内での発見のため、スクショ無し

### 問題のツールチップ

不明

### 問題の表現

車両通行規制なしの非承認
車両通行規制の不承認

### 問題箇所の英文

Approve of cars being unrestricted.
Disapprove of cars being restricted.

### 希望する変更

自由な車両通行に賛成
車両通行規制に不賛成

### 変更の理由（概要）

誤訳

### 変更の理由（詳細）

一つ目は完全な誤訳
二つ目は一つ目の修正に合うようにするため

### プレイ国家

どこでも

### ゲームバージョン

1.1.X

### MOD有無

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通りで修正しました
