### ISSUE TITLE
法律制定イベント「反対派の謀反」

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#617]
### スクリーンショット

![image](https://user-images.githubusercontent.com/37979626/213858496-57a6894c-577a-4869-beca-0fd8d046e6e0.png)

### 問題部分

本文, 選択肢

### 問題のイベントタイトル

反対派の謀反

### 問題のイベント本文（抜粋可）

「我々はどのくらい一緒に活動している？我々が援助を惜しまなかったことが幾度ある？それでも我々の懸念には依然として答えが見えず、欲求が満たされることもない。この場において我々の声が響かないのであれば、別の場所で発信するだけだ」

### 問題のイベント選択肢

分離派め！悪魔に手に堕ちるがいい。

補正名
買収する

### 希望する変更（修正部分のみ）

「**どれほど長く一緒に活動してきた？我々が援助を惜しまなかったことがあるか？**それでも我々の懸念には依然として答えが見えず、欲求が満たされることもない。この場において我々の声が響かないのであれば、別の場所で発信するだけだ」

分離派め！悪魔**の**手に堕ちるがいい。

補正名
買収

### 変更の理由（概要）

自然な表現にするため

### 変更の理由（詳細）

選択肢の方は助詞がおかしく、補正名についてもここだけ動詞になっている。

### プレイ国家

ロシア

### ゲームバージョン

1.1.X

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
補正名に関するスクショ
![image](https://user-images.githubusercontent.com/37979626/213858786-cbd45513-07a5-4541-86b2-2f98400cb56c.png)

**Comment by inarizushi0309** [comment]
原案通りで修正しました
