### ISSUE TITLE
【誤訳】融和的（外交態度）の内訳「○○と仲裁したい」

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#618]
### スクリーンショット

![image](https://user-images.githubusercontent.com/37979626/214249872-b7141ad8-fcc0-4adc-8453-dd05c42ee286.png)

### 問題のツールチップ

国家画面>外交タブ>態度マウスオーバー

### 問題の表現

[COUNTRY.GetName]は[TARGET_COUNTRY.GetName]を仲裁したいと考えています
調停
[TARGET_COUNTRY.GetName]を仲裁します

### 問題箇所の英文

[COUNTRY.GetName] wants to reconcile with [TARGET_COUNTRY.GetName]
Reconcile
Reconcile with [TARGET_COUNTRY.GetName]

### 希望する変更

[COUNTRY.GetName]は[TARGET_COUNTRY.GetName]と和解したいと考えています
和解
[TARGET_COUNTRY.GetName]との和解

### 変更の理由（概要）

誤訳

### 変更の理由（詳細）

仲裁は第三者を介す行動なので

### プレイ国家

ロシア

### ゲームバージョン

1.1.X

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通りで修正しました
