### ISSUE TITLE
移住規制「移民が許されないPOP」

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#619]
### スクリーンショット

![image](https://user-images.githubusercontent.com/37979626/214539824-48f35f57-dfe3-4685-a31d-c3ebf9cc0778.png)
![image](https://user-images.githubusercontent.com/37979626/214541905-79eed6dc-5bf9-40af-9f54-86ce1cbc5988.png)

### 問題のツールチップ

法律画面>移住>移住規制マウスオーバー

### 問題の表現

移民が許されない差別POP
移民が許されないすべてのPOP

```[Concept('concept_migration', '$concept_migrating$')]が許されない[Concept('concept_discrimination', '$concept_discriminated$')] [Concept('concept_pop', '$concept_pops$')]```
```[Concept('concept_migration', '$concept_migrating$')]が許されないすべての[Concept('concept_pop', '$concept_pops$')]```

### 問題箇所の英文

```[Concept('concept_discrimination', '$concept_discriminated$')] [Concept('concept_pop', '$concept_pops$')] Disallowed from [Concept('concept_migration', '$concept_migrating$')]```
```All [Concept('concept_pop', '$concept_pops$')] Disallowed from [Concept('concept_migration', '$concept_migrating$')]```

### 希望する変更

差別POPの移民拒否
全POPの移民拒否

```[Concept('concept_migration', '$concept_migrating$')]が許されない[Concept('concept_discrimination', '$concept_discriminated$')] [Concept('concept_pop', '$concept_pops$')]```
```[Concept('concept_migration', '$concept_migrating$')]が許されないすべての[Concept('concept_pop', '$concept_pops$')]```

### 変更の理由（概要）

不自然な表現のため

### プレイ国家

ロシア

### ゲームバージョン

1.1.X

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
--------------------
現在の修正案

差別POPの移民拒否
全POPの移民拒否

```[Concept('concept_discrimination', '被差別')][Concept('concept_pop', '$concept_pops$')]の[Concept('concept_migration', '$concept_migrating$')]拒否
全[Concept('concept_pop', '$concept_pops$')]の[Concept('concept_migration', '$concept_migrating$')]拒否```

**Comment by matanki-saito** [comment]
--------------------
現在の修正案

被差別POPの移民拒否
全POPの移民拒否

```[Concept('concept_discrimination', '被差別')][Concept('concept_pop', '$concept_pops$')]の[Concept('concept_migration', '$concept_migrating$')]拒否```
```全[Concept('concept_pop', '$concept_pops$')]の[Concept('concept_migration', '$concept_migrating$')]拒否```

**Comment by inarizushi0309** [comment]
上記修正案で確定しました

**Comment by inarizushi0309** [comment]
原文変更に伴い、再開します

**Comment by inarizushi0309** [comment]
新原文
```[Concept('concept_discrimination', '$concept_discriminated$')] [Concept('concept_pop', '$concept_pops$')] Disallowed from [Concept('concept_migration', '$concept_migrating$')] internationally```
```All [Concept('concept_pop', '$concept_pops$')] Disallowed from [Concept('concept_migration', '$concept_migrating$')] internationally```
現行訳
```他国への[Concept('concept_migration', '$concept_migrating$')]が許されない[Concept('concept_discrimination', '$concept_discriminated$')]された[Concept('concept_pop', '$concept_pops$')]移民が許されない差別POP```
```他国への[Concept('concept_migration', '$concept_migrating$')]が許されないすべての[Concept('concept_pop', '$concept_pops$')]```

**Comment by inarizushi0309** [comment]
![image](https://github.com/user-attachments/assets/831db3e2-e6f5-44d3-99d0-d5b01889a0af)
![image](https://github.com/user-attachments/assets/d42a2885-381c-4b13-a2c6-279398373f1e)
