### ISSUE TITLE
【修正提案】軍事画面の動員済み表記

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#62]
## スクリーンショット（必須）

![20221027132001_1](https://user-images.githubusercontent.com/42710893/198192163-59c75c90-46dd-489a-bea3-706f1240dab7.jpg)

## 問題のあるインターフェイス（必須）

軍事画面

## 問題のテキスト（必須）

動員された

## 希望する変更（必須）

動員済み　等

## 変更の理由（必須）

英語版では
Mobilized @battalions![Country.GetBattalionsFullyMobilized|v0]/[Country.GetBattalionsWithGeneralRaw]
動員済み、等としたほうが日本語として自然かと思います。

## ゲームバージョン（必須）

1.0.3

## DLCの有無（必須）

なし

## MODの有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1035049387501559889
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by matanki-saito** [comment]
ここは語順を変えて
@battalions![Country.GetBattalionsFullyMobilized|v0]/[Country.GetBattalionsWithGeneralRaw] 動員中
という風にした方が見やすいかと思いますがどうでしょうか？

**Comment by matanki-saito** [comment]
あとここもそろえるべきかと

**Comment by inarizushi0309** [comment]
上記案に変更し修正しました
