### ISSUE TITLE
アイアンマンモード

### ISSUE THREAD

**Issue by mochi115** [matanki-saito/vic3jpadvmod#621]
### スクリーンショット

![20230122041004_1](https://user-images.githubusercontent.com/117048815/215234209-e9e455df-016d-4b28-b289-6442de06796b.jpg)

### 問題の用語

アイアンマンモード

### 希望する変更

鉄人モード

### 変更の理由（概要）

他のパラドゲーの訳に統一

### 変更の理由（詳細）

他のパラドゲーでは鉄人モードと訳されており、Vic3だけアイアンマンモードとする必要はないと思います。

### ゲームバージョン

1.1.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
起票ありがとうございます。提案通り修正しました。
