### ISSUE TITLE
従属国国 修正漏れ

### ISSUE THREAD

**Issue by mochi115** [matanki-saito/vic3jpadvmod#622]
### スクリーンショット

![20230122041107_1](https://user-images.githubusercontent.com/117048815/215234565-26450ffe-b516-4995-8bc2-20ab202e7cfb.jpg)

### 問題のあるインターフェイス

ゲームルールの設定

### 問題のテキスト

従属国国

### 希望する変更

従属国

### 変更の理由（概要）

#603の修正もれ

### ゲームバージョン

1.1.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
報告ありがとうございます。提案通り衍字を外して修正しました。
