### ISSUE TITLE
提督を雇用する

### ISSUE THREAD

**Issue by mochi115** [matanki-saito/vic3jpadvmod#623]
### スクリーンショット

![20230122041327_1](https://user-images.githubusercontent.com/117048815/215234893-a4b7a42a-4a7b-4710-be98-dbb5f0b3626c.jpg)

### 問題のあるインターフェイス

軍事レンズ 海軍タブ

### 問題のテキスト

提督を雇用する

### 希望する変更

提督の雇用

### 変更の理由（概要）

表記ゆれの修正

### ゲームバージョン

1.1.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。
