### ISSUE TITLE
行動力/外交手段

### ISSUE THREAD

**Issue by mochi115** [matanki-saito/vic3jpadvmod#624]
### スクリーンショット

![20230122041855_1](https://user-images.githubusercontent.com/117048815/215235309-788f3b55-4d90-463d-86cb-c8409498e932.jpg)

### 問題の用語

行動力/外交手段

### 英語版の表現

Maneuvers per Diplomatic Play

### 希望する変更

行動力/外交戦

### 変更の理由（概要）

Diplomatic Playの翻訳の修正

### 変更の理由（詳細）

外交戦当たりの行動力という訳の方が自然かもしれません。

### ゲームバージョン

1.1.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。
