### ISSUE TITLE
防御の成功と防御の失敗が逆に表示される

### ISSUE THREAD

**Issue by mochi115** [matanki-saito/vic3jpadvmod#625]
### スクリーンショット

![20230122044632_1](https://user-images.githubusercontent.com/117048815/215235982-9fa7a5ca-d578-4105-9059-ea31031bb276.jpg)
英語版
![20230122044635_1](https://user-images.githubusercontent.com/117048815/215236052-99608c85-0ba2-4980-af3d-ac4e06d00d99.jpg)

### 問題のあるインターフェイス

戦闘の勝利/敗北時のインターフェイス

### 問題のテキスト
```
BATTLE_END_RIGHT_SIDE:0 "[SelectLocalization( Battle.IsWinner( Battle.GetAttacker ), '$SUCCESSFUL_DEFENSE$', '$FAILED_DEFENSE$' )]"
```
### 希望する変更
```
BATTLE_END_RIGHT_SIDE:0 "[SelectLocalization( Battle.IsWinner( Battle.GetDefender ), '$SUCCESSFUL_DEFENSE$', '$FAILED_DEFENSE$' )]"
```
### 変更の理由（概要）

防御の成功と防御の失敗が逆に表示されるのを修正

### 変更の理由（詳細）

防衛側が攻撃側の結果を受け取ってしまい、その結果逆に表示されるみたいです。

### ゲームバージョン

1.1.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
起票ありがとうございます。起票通り修正しました。
