### ISSUE TITLE
合成繊維プラント

### ISSUE THREAD

**Issue by mochi115** [matanki-saito/vic3jpadvmod#626]
### スクリーンショット

![20230122042200_1](https://user-images.githubusercontent.com/117048815/215237730-66a51cfe-ef90-49ca-97f5-115f91197cec.jpg)

### 問題の用語

合成繊維プラント

### 希望する変更

合成プラント

### 変更の理由（概要）

合成繊維のみを製造しているわけでは無いため

### 変更の理由（詳細）

アイコンも染料なので結構違和感があります。

### ゲームバージョン

1.1.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
起票ありがとうございます。提案通り修正しました。
