### ISSUE TITLE
タイムアウトまで

### ISSUE THREAD

**Issue by mochi115** [matanki-saito/vic3jpadvmod#629]
### スクリーンショット

![20230122052631_1](https://user-images.githubusercontent.com/117048815/215240668-42790ec2-031f-4165-910f-fba9deb1dbfc.jpg)

### 問題のあるインターフェイス

ジャーナル記事

### 問題のテキスト

タイムアウトまで

### 希望する変更

時間切れまであと

### 変更の理由（概要）

日本語の表現に修正

### ゲームバージョン

1.1.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
起票ありがとうございます。提案通り修正しました。
