### ISSUE TITLE
strategic_regionsにおける固有名詞

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#63]
## 問題の固有名詞と希望する変更（必須）
バルティック：バルト
ペルシャ：ペルシア
中国北部：華北
中国南部：華南
マスカリン：マスカリン諸島
アダマン海：アンダマン海
シアム湾：シャム湾

## 変更の理由（必須）
日本語では一般的ではない表記であるため

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1035055611685113857
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。
