### ISSUE TITLE
実業家が非主流派であるではない

### ISSUE THREAD

**Issue by mochi115** [matanki-saito/vic3jpadvmod#630]
### スクリーンショット

![20230122045349_1](https://user-images.githubusercontent.com/117048815/215240958-c5fa783c-abbb-4131-b20e-7dbd984bb26f.jpg)

### 問題のあるインターフェイス

農場から工場へのトリガー

### 問題のテキスト

実業家が非主流派であるではない

### 希望する変更

実業家が非主流派ではない

### 変更の理由（概要）

表記ミスの修正

### ゲームバージョン

1.1.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
修正ミスですね。すぐ直します
