### ISSUE TITLE
実行中の外交アクション

### ISSUE THREAD

**Issue by mochi115** [matanki-saito/vic3jpadvmod#631]
### スクリーンショット

![20230122051934_1](https://user-images.githubusercontent.com/117048815/215241102-1b9dccf1-88d7-4ce7-b7c5-5da3528bfee1.jpg)

### 問題の用語

実行中の外交アクション

### 英語版の表現

Ongoing Diplomatic Action

### 希望する変更

継続外交アクション

### 変更の理由（概要）

誤訳の修正

### ゲームバージョン

1.1.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
起票ありがとうございます。提案通り修正しました。
