### ISSUE TITLE
イギリス人の姓名

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#632]
### スクリーンショット

なし

### 問題の固有名詞：希望する変更

アウグスタス：オーガスタス
アントニー：アンソニー
アイルマー：エールマー
オーステン：オースティン
ベウシャンプ：ビーチャム
ベルトラム：バートラム
シチェスター：チチェスター
コーリングウッド：コリンウッド
コルネリウス：コーネリアス
カレブ：ケイレブ
ダッドリー：ダドリー
エベネゼール：エベニーザー
エヴェリン：イヴリン
エウスタス：ユースタス
ギルドフォード：ギルフォード
ガソーン：ゲイソン
ジオッフレイ：ジェフリー
ゴッドフリー：ゴドフリー
フー：ヒュー
ホラティオ：ホレーショ
ヘドワース：ヘッドワース
ハンフレイ：ハンフリー
イサムバード：イザムバード
レオナルド：レナード
リオン：ライアン
モンタージュ：モンタギュー
マイルス：マイルズ
ムーラフ：マロー
オクタヴィウス：オクタヴィアス
ルドヤード：ラドヤード
ステファン：スティーヴン
セワリス：セウォリス
スーザーランド：サザーランド
テオドア：セオドア
テオバルド：シーオボルド
テイグンマウス：ティンマス

アダ：エイダ
アレテア：アリーシア
クリスティナ：クリスティーナ
エディス：イーディス
エレアノール：エレノア
フランセス：フランシス
ハンナ：ハナ
アイビー：アイヴィー
ラーティティア：リティーシャ
マリー：メアリー
ノナ：ノーナ
ノラ：ノーラ
ロシナ：ロジーナ
ロサライン：ロザライン
ルス：ルース

アンストルーサー：アンストラザー
アンネスレイ：アンズリー
アッシェトン：アシュトン
アミステッド：アーミステッド
アデール：アデイア
アイタウン：エイトン
アムハースト：アマースト
ベニョン：ベンヨン
ブリューワー：ブルーアー
ブールネ：ボーン
ブールケ：バーク
ビューモント：ボーモント
バイレイ：ベイリー
ビドゥルフ：ビダルフ
バーリング：ベアリング
バイネス：ベインズ
バズリー：ベイズリー
ビンハム：ビンガム
ボルカウ：ボルコー
バッジェ：バッゲ
ビーヴォア：ビーヴァー
バルフォー：バルフォア
バイリー：ベイリー
ベイリー：ベイリ
ビーアボーム：ビアボーム
ベラース：ベレアーズ
ベウィック：ビウィック
ブラーグデン：ブラグデン
ブローデリップ：ブロデリップ
ブロウトン：ブロートン
ブッデン：バドン
ビュークラーク：ボークラーク
ボサンケット：ボーザンケット
クラウファード：クローファード
ケイブ：ケイヴ
コリンス：コリンズ
チャンバー：チェインバーズ
カラーリッジ：コールリッジ
カーネジー：カーネギー
コルメリー：チャムリー
カスターロッセ：カッスルロス
コルトハースト：コルスハースト
コールブローク：コールブルック
ディルケ：ディルク
ディスダール：ディムズデール
ドウ：ダウ
ドゥンネル：ダネル
セリカーク：セルカーク
エルコー：エルホー
エドウス：エドウッズ
フォートスキュー：フォーテスキュー
フェロウス：フェローズ
フォーサーギル：フォザーギル
フェザーストンハウ：ファンショー
ファンシャウ：ファンショウ
フォロウス：フォローズ
グレスリー：グレズリー
グロスヴェノール：グロヴナー
ゴーシェン：ゴッシェン
ガーデナー：ガードナー
ヒューゲス：ヒューズ
ホアール：ホーア
ホルムス：ホームズ
ホームスダール：ホームズデール
ハイグ：ヘイグ
インチバルド：インチボールド
インギリス：イングリス
ジョリッフ：ジョリフ
ケンナード：ケナード
カヴァナ：カヴァナー
ケオウン：キーオン
キンナード：キナード
ラブレイス：ラヴレース
レイアード：レアード
レーグ：リー
レフロイ：ルフロイ
レーサム：リーザム
ローウェ：ロウ
レスリー：レズリー
マックラー：マクルーア
モンクライフ：モンクリフ
マクアーサー：マカーサー
マナース：マナーズ
マクラーガン：マクレガン
マケヴォイ：マクエヴォイ
マテソン：マシソン
ニューデガート：ニューデゲート
ナピエ：ネイピア
オギルヴィー：オグルヴィ
オンスロウ：オンズロー
プロムローズ：プリムローズ
ピース：ピーズ
ペルハム：ペラム
ポンスビー：ポンソンビー
プラムプター：プランプター
パルドン：パードゥン
ライケス：レイクス
ラムボルド：ランボールド
ライネス：レインズ
ラマージ：ラメージ
レディッシュ：レディシュ
ステファンソン：スティーヴンソン
ストロンジェ：ストロンジ
スリヴァン：サリヴァン
サルトリス：サートリス
サウンダーソン：サンダーソン
スタヴェリー：ステーヴリー
スタクプール：スタックプール
スタンフェルド：スタンフィールド
サンドバッハ：サンドバック
トールマッシェ：トルマッシュ
トレーホーク：トレホーク
タイラー：テイラー
ソーニークロフト：ソーニクロフト
トロウブリッジ：トラウブリッジ
ティースデール：ティーズデール
トッテンヘイム：トッテナム
ティトムス：ティットマス
ティルデスレー：ティルズリー
ヴェイチ：ヴィーチ
ヴァンセ：ヴァンス
ヴァンデロイアー：ヴァンデリュア
ウールコンブ：ウールコーム
ウィリアムス：ウィリアムズ
ウィットワース：ホイットワース
ウォーターロウ：ウォータールー
ウェザーレッド：ウェザード
ウィリー：ワイリー
ワルシュ：ウォルシュ
ウィンターボーサム：ウィンターボーザム
ホワイトロウ：ホワイトロー
ウィスデン：ウィズデン

アガー・エリス：エイガー＝エリス
アルトホープ：オールソープ
バーデン・ポーウェル：ベーデン＝パウエル
ブルーデネル・ブルース：ブルーデネル＝ブルース
ボーリングブローク：ボリングブルック
バトラー・ヘンダーソン：バトラー＝ヘンダーソン
ボーウェス・リオン：ボーズ＝ライアン
ブルワー・ライトン：ブルワー＝リットン
カベンディッシュ：キャヴェンディッシュ
クリッチトン・ステュアート：クライトン＝ステュアート
コウェル・ステファニー：コーウェル＝ステップニー
カウパー・テンプル：カウパー＝テンプル
クラム・エーウィング：クラム＝ユーイング
キャンプベル・バナーマン：キャンベル＝バナマン
コートネイ：コートニー
ドーソン・ダマー：ドーソン＝デイマー
ダリンプル・ヘイ：ダーリンプル＝ヘイ
ファーグソン・デイビー：ファーガソン＝デイヴィー
ファルマウス：ファルマス
フェーン：フェイン
フォリー：フォーリー
ゴードン・レノックス：ゴードン＝レノックス
グレヴィル・ヌーゲント：グレヴィル＝ニュージェント
グラハム・モントゴメリー：グラハム＝モントゴメリー
グリーン・プライス：グリーン＝プライス
ガソーン・ハーディ：ゲイソン＝ハーディ
ハヴィランド・バーク：ハヴィランド＝バーク
ヒル・トレヴァー：ヒル＝トレヴァー
ハンブリー・トレイシー：ハンベリー＝トレイシー
ハンプデン：ハムデン
ヒューム・キャンプベル：ヒューム＝キャンベル
ジョーンス・パリー：ジョーンズ＝パリー
ジャービス・ホワイト・ジャービス：ジャーヴィス＝ホワイト＝ジャーヴィス
ロイド・リンゼイ：ロイド＝リンジー
レベソン・ゴウアー：リューソン＝ゴール
ラウンセストン：ローンセストン
マニンガム・ビュラー：マニンガム＝ブラー
メイネル・イングラム：メイネル＝イングラム
モントゴメリー・カニンガム：モントゴメリー＝カニンガム
ミュア・キャンプベル：ミュア＝キャンベル
オール・エーウィング：オル＝ユーイング
オームスバイ・ゴア：オームズビー＝ゴー
プレイデール・バーバリー：プレイデル＝ブーヴェリー
ペラム・クリントン：ペラム＝クリントン
ラグルス・ブライス：ラグルズ＝ブライス
ラムゼイ・ギブソン・メイトランド：ラムゼイ＝ギブソン＝メイトランド
ラウドン・ヘイスティングス：ロードン＝ヘイスティングズ
サリスブリー：ソールズベリー
ソールズベリー・トレローニー：サルスベリー＝トレローニー
スミス・バリー：スミス＝バリー
セルウィン・イベートソン：セルウィン＝イベートソン
スクレイター・ブース：スクレイター＝ブース
ストップフォード・サックヴィル：ストップフォード＝サックヴィル
ショウ・レーフェブル：ショー＝レフィーヴァー
スペンサー・チャーチル：スペンサー＝チャーチル
ソロトン・ヒルドヤード：ソーントン＝ヒルドヤード
タッドキャスター：タドカスター
タウンセンド：タウンゼンド
ワルポール：ウォルポール
ウィリアムス・ウィン：ウィリアムズ＝ウィン
ウィングフィールド・ベイカー：ウィンフィールド＝ベイカー
ウィルソン・パッテン：ウィルソン＝パッテン
ウェルビー・グレゴリー：ウェルビー＝グレゴリー
ウィンドソール・クライヴ：ウィンザー＝クライヴ
ウェントワース・フィッツウィリアム：ウェントワース＝フィッツウィリアム
ワルドグレイヴ：ウォールグレイヴ
ウィットハース・ランカシャイア：ウィザズ＝ランカシャー

チャイルド・ヴィリアース：チャイルド・ヴィリアーズ

チャンバーレイン：チェンバレン

ディスラエリ：ディズレーリ

### 変更の理由（概要）

日本語では一般的ではない表記であるため

### ゲームバージョン

1.1.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
