### ISSUE TITLE
アヘン中毒イベントの不自然な翻訳

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#634]
### スクリーンショット

![image](https://user-images.githubusercontent.com/37979626/216493167-4781e6ee-240f-45bb-8440-b4c4c8233090.png)

### 問題部分

本文

### 問題のイベントタイトル

アヘン中毒

### 問題のイベント本文（抜粋可）

[SCOPE.sCulture('opium_addiction_pop').GetName]は、アヘン中毒の深刻な影響を経験しています。この物質の使用と乱用は[SCOPE.sState('opium_addiction_state').GetName]全体に広がっているのです。

### 希望する変更（修正部分のみ）

[SCOPE.sCulture('opium_addiction_pop').GetName]人は、アヘン中毒の深刻な影響を経験しています。

### 変更の理由（概要）

自然な表現にするため

### プレイ国家

ロシア

### ゲームバージョン

1.1.X

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
[SCOPE.sState('opium_addiction_state').GetName]ではアヘンが広く普及していますが、乱用も増加しており、[SCOPE.sCulture('opium_addiction_pop').GetName]文化の人々は中毒の深刻な脅威に直面しています。
で修正
