### ISSUE TITLE
【誤訳】征服からの急進「者」

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#635]
### スクリーンショット

![image](https://user-images.githubusercontent.com/37979626/216495361-80a14944-dec6-4f89-b488-d53eef1288b1.png)

### 問題のツールチップ

国家画面＞外交タブ＞悪名マウスオーバー

### 問題の表現

征服による急進者

### 問題箇所の英文

Radicals from Conquest

### 希望する変更

征服による急進派

### 変更の理由（概要）

表記ゆれ

### プレイ国家

ロシア

### ゲームバージョン

1.1.X

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通りで修正しました

**Comment by kurutto115** [comment]
![s-Victoria 3 2024_07_24 20_51_42](https://github.com/user-attachments/assets/35b6c18c-9f87-4a39-ae6a-5298df0e572b)
本件再発しているようです。ご確認ください

**Comment by inarizushi0309** [comment]
他「急進者」となっていた箇所含め修正しました。報告ありがとうございます。
