### ISSUE TITLE
市場商品ポリシーの設定

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#636]
### スクリーンショット

![image](https://user-images.githubusercontent.com/37979626/216527963-732d3bc9-e5c5-491f-bf95-6cd7a22f148d.png)

### 問題のツールチップ

市場画面＞詳細タブ＞商品右クリック

### 問題の表現

```$tariff_no_priority$に[concept_market_good_policy]を制定```
```$tariff_import_priority$に[concept_market_good_policy]を制定```
```$tariff_export_priority$に[concept_market_good_policy]を制定```

### 問題箇所の英文

```Set [concept_market_good_policy] to $tariff_no_priority$```
```Set [concept_market_good_policy] to $tariff_import_priority$```
```Set [concept_market_good_policy] to $tariff_export_priority$```

### 希望する変更

```[concept_market_good_policy]を$tariff_no_priority$に設定```
```[concept_market_good_policy]を$tariff_import_priority$に設定```
```[concept_market_good_policy]を$tariff_export_priority$に設定```

### 変更の理由（概要）

自然な表現にするため

### 変更の理由（詳細）

「何を」「どうする」の語順にした方が分かりやすい

### プレイ国家

ロシア

### ゲームバージョン

1.1.X

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通りで修正しました
