### ISSUE TITLE
【変数ミス】[COUNTRY.GetName]関連

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#637]
### スクリーンショット

作業所での発見のためなし

### 問題のツールチップ

外交関連

### 問題の表現

細かい修正なため、エントリ名のみに留める

alliance_effect_desc_third
alliance_trigger_desc_third
alliance_trigger_false_desc_third
defensive_pact_effect_desc_third
defensive_pact_trigger_desc_third
defensive_pact_trigger_false_desc_third
protectorate_effect_desc_third
protectorate_trigger_desc_third
protectorate_trigger_false_desc_third
puppet_effect_desc_third
tributary_effect_desc_third
tributary_trigger_desc_third
tributary_trigger_false_desc_third
dominion_effect_desc_third

例）
[AddTextIf(ObjectsEqual(GetMetaPlayer.GetPlayedOrObservedCountry.Self, TARGET_COUNTRY.Self),TARGET_COUNTRY.GetNameNoFlag)][AddTextIf(Not(ObjectsEqual(GetMetaPlayer.GetPlayedOrObservedCountry.Self, TARGET_COUNTRY.Self)),TARGET_COUNTRY.GetName)]が[COUNTRY.GetAdjectiveNoFlag]との[concept_alliance]に調印しました

### 問題箇所の英文

[AddTextIf(ObjectsEqual(GetMetaPlayer.GetPlayedOrObservedCountry.Self, TARGET_COUNTRY.Self),TARGET_COUNTRY.GetNameNoFlag)][AddTextIf(Not(ObjectsEqual(GetMetaPlayer.GetPlayedOrObservedCountry.Self, TARGET_COUNTRY.Self)),TARGET_COUNTRY.GetName)] enters into an [concept_alliance] with [COUNTRY.GetName]

### 希望する変更

[COUNTRY.GetAdjectiveNoFlag]　→　[COUNTRY.GetName]

[AddTextIf(ObjectsEqual(GetMetaPlayer.GetPlayedOrObservedCountry.Self, TARGET_COUNTRY.Self),TARGET_COUNTRY.GetNameNoFlag)][AddTextIf(Not(ObjectsEqual(GetMetaPlayer.GetPlayedOrObservedCountry.Self, TARGET_COUNTRY.Self)),TARGET_COUNTRY.GetName)]が[COUNTRY.GetName]との[concept_alliance]に調印しました

### 変更の理由（概要）

変数ミス

### ゲームバージョン

1.1.X

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
そうです。
変数の違いとしては、英語版では[国家名+国旗]で表示されるところが現状だと[国家名（形容詞系）]になってしまっています。

**Comment by inarizushi0309** [comment]
原案通りで修正しました
