### ISSUE TITLE
【文体統一】戦争目標の説明文

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#638]
### スクリーンショット

![image](https://user-images.githubusercontent.com/37979626/216555249-14947336-d9cd-4729-b031-b21fba6b7eac.png)
![image](https://user-images.githubusercontent.com/37979626/216561098-8d866e8a-7e05-4037-9580-37dd60974166.png)

### 問題のツールチップ

外交戦画面＞概要タブ＞戦争目標マウスオーバー

### 問題の表現

war_goal_conquer_state_desc
war_goal_return_state_desc
war_goal_revoke_claim_desc
war_goal_revoke_all_claims_desc
war_goal_annex_country_desc
war_goal_annex_native_desc
war_goal_secession_desc
war_goal_revolution_desc
war_goal_contain_threat_desc
war_goal_war_reparations_desc
war_goal_unification_leadership_desc
war_goal_humiliation_desc
war_goal_open_market_desc
war_goal_regime_change_desc
war_goal_ban_slavery_desc
war_goal_take_treaty_port_desc
war_goal_independence_desc
war_goal_liberate_subject_desc
war_goal_liberate_country_desc
war_goal_force_recognition_desc
war_goal_transfer_subject_desc
war_goal_make_puppet_desc
war_goal_make_dominion_desc
war_goal_make_vassal_desc
war_goal_unification_desc

### 問題箇所の英文

割愛

### 希望する変更

コメント欄にて

### 変更の理由（概要）

文体が揺れているため

### 変更の理由（詳細）

https://paratranz.cn/projects/5456/strings?key=war_goal_&key=_desc&key%21=_sway_desc&key%21=_type_desc&file=712157&advanced=1

句点の有無が分かれているのは、文末に変数が入っているときはなぜかピリオドが省略されているため。
方針としては基本、「常体で句点あり」で、体言止めにするなら句点なしがいいものの、補正とは違うので、わざわざ体言止めにする必要性はないか

### プレイ国家

ロシア

### ゲームバージョン

1.1.X

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
1. [提案国]が[対象国]から[対象州名]の[concept_state]を征服します。
　→[提案国]が[対象国]の[対象州名][concept_state]を征服する。

1. [対象国]が[対象州名]の[concept_state]を[提案国]に返還します
　→[対象国]が[対象州名][concept_state]を[提案国]に返還する。

1. [提案国]が、[対象国]による[対象地域名]への請求権を破棄するように強要する。
　→[提案国]が、[対象国]に[対象地域名]への請求権を破棄するよう強要する。

1. [対象国]は、[提案国]におけるすべての[Concept('concept_claim', '$concept_claims$')]の破棄を強要されました。
　→[対象国]は、[提案国]に対するすべての[Concept('concept_claim', '$concept_claims$')]を破棄させられる。

1. [提案国]が、[対象国]の国を併合
　→[提案国]が[対象国]を併合する。

1. [提案国]が、[対象国]の[concept_decentralized_nation]を併合
　→[提案国]が、[concept_decentralized_nation]である[対象国]を併合する。

1. 我が国から分離したすべての[対象国] [Concept('concept_state', '$concept_states$')]を返還しましょう。
　→我が国から分離した[対象国]の[Concept('concept_state', '$concept_states$')]をすべて取り戻す。

1. [対象国] [concept_revolution]を鎮圧せよ
　→[対象国]の[concept_revolution]を鎮圧する。

1. [対象国]が過去 #v [年数]#! 年間に行った征服で獲得した州や従属国をすべて解放するよう[提案国]が強要する。
　→[提案国]が、[対象国]に過去#v [年数]#!年間に行った征服で獲得した州や従属国をすべて解放するよう強要する。

1. [提案国]が、今後5年間税収の #variable 10%#! を[concept_war_reparations]として支払うよう[対象国]に強要する。
　→[提案国]が、[対象国]に[concept_war_reparations]として今後5年間税収の#variable 10%#!を支払うよう強要する。

1. [統一国家名]統一の野望を放棄するよう[対象国]に強要します。
　→[対象国]に[統一国家名]統一の野望を放棄するよう強要する。

1. 今後5年間[対象国]の威信を下げ、[Concept('concept_diplomatic_play', '$concept_diplomatic_plays$')]における[提案国]との対立を防止
　→今後5年間、[対象国]の威信を下げ、[Concept('concept_diplomatic_play', '$concept_diplomatic_plays$')]にて[提案国]と対立できなくする。

1. war_goal_open_market_descそのまま

1. [提案国]は[対象国]に彼らの[concept_government]や[Concept('concept_law', '$concept_laws$')]を自国の[concept_government]に沿ったものに変更するよう強要します。
　→[提案国]が、[対象国]に彼らの[concept_government]や[Concept('concept_law', '$concept_laws$')]を自国の[concept_government]に沿ったものに変更するよう強要する。

1. war_goal_ban_slavery_descそのまま
1. war_goal_take_treaty_port_descそのまま
1. war_goal_independence_descそのまま
1. war_goal_liberate_subject_descそのまま

1. [提案国]が、[対象国]に[WAR_GOAL.GetCountryCreation.GetName]を解放するよう強要する。
　→[提案国]が、[対象国]に[WAR_GOAL.GetCountryCreation.GetName]を国家として解放するよう強要する。

1. [提案国]が、[対象国]に[提案国]の未承認ステータスを取り除くよう強要する。
　→[提案国]が、[対象国]に[提案国]の未承認状態を止めさせるよう強要する。

1. war_goal_transfer_subject_descそのまま
1. war_goal_make_puppet_descそのまま
1. war_goal_make_dominion_descそのまま
1. war_goal_make_vassal_descそのまま

1. [提案国]が[WAR_GOAL.GetCountryFormation.GetAdjective]である劣等国すべての併合を試みます。
　→[提案国]が、[WAR_GOAL.GetCountryFormation.GetAdjective]の劣等国すべての併合を試みる。

**Comment by inarizushi0309** [comment]
現在の修正案

1. [提案国]が[対象国]から[対象州名]の[concept_state]を征服します。
　→[提案国]が[対象国]の[対象州名][concept_state]を征服する。

2. [対象国]が[対象州名]の[concept_state]を[提案国]に返還します
　→[対象国]が[対象州名][concept_state]を[提案国]に返還する。

3. [提案国]が、[対象国]による[対象地域名]への請求権を破棄するように強要する。
　→[提案国]が[対象国]に対し、[対象地域名]への請求権を破棄するよう強要する。

4. [対象国]は、[提案国]におけるすべての[Concept('concept_claim', '$concept_claims$')]の破棄を強要されました。
　→[対象国]は、[提案国]に対するすべての[Concept('concept_claim', '$concept_claims$')]を破棄させられる。

5. [提案国]が、[対象国]の国を併合
　→[提案国]が[対象国]を併合する。

6. [提案国]が、[対象国]の[concept_decentralized_nation]を併合
　→[提案国]が、[concept_decentralized_nation]である[対象国]を併合する。

7. 我が国から分離したすべての[対象国] [Concept('concept_state', '$concept_states$')]を返還しましょう。
　→我が国から[対象国]へと分離した[Concept('concept_state', '$concept_states$')]をすべて取り戻す。

8. [対象国] [concept_revolution]を鎮圧せよ
　→[対象国]の[concept_revolution]を鎮圧する。

9. [対象国]が過去 #v [年数]#! 年間に行った征服で獲得した州や従属国をすべて解放するよう[提案国]が強要する。
　→[提案国]が[対象国]に対し、過去#v [年数]#!年間に行った征服で獲得した州や従属国をすべて解放するよう強要する。

10. [提案国]が、今後5年間税収の #variable 10%#! を[concept_war_reparations]として支払うよう[対象国]に強要する。
　→[提案国]が[対象国]に対し、[concept_war_reparations]として今後5年間税収の#variable 10%#!を支払うよう強要する。

11. [統一国家名]統一の野望を放棄するよう[対象国]に強要します。
　→[対象国]に[統一国家名]統一の野望を放棄するよう強要する。

12. 今後5年間[対象国]の威信を下げ、[Concept('concept_diplomatic_play', '$concept_diplomatic_plays$')]における[提案国]との対立を防止
　→今後5年間、[対象国]の威信を下げ、[Concept('concept_diplomatic_play', '$concept_diplomatic_plays$')]にて[提案国]と対立できなくする。

14. [提案国]は[対象国]に彼らの[concept_government]や[Concept('concept_law', '$concept_laws$')]を自国の[concept_government]に沿ったものに変更するよう強要します。
　→[提案国]が[対象国]に対し、彼らの[concept_government]や[Concept('concept_law', '$concept_laws$')]を自国の[concept_government]に沿ったものに変更するよう強要する。

19. [提案国]が、[対象国]に[WAR_GOAL.GetCountryCreation.GetName]を解放するよう強要する。
　→[提案国]が[対象国]に対し、[WAR_GOAL.GetCountryCreation.GetName]を国家として解放するよう強要する。

20. [提案国]が、[対象国]に[提案国]の未承認ステータスを取り除くよう強要する。
　→[提案国]が[対象国]に対し、[提案国]の未承認状態を止めさせるよう強要する。

25. [提案国]が[WAR_GOAL.GetCountryFormation.GetAdjective]である劣等国すべての併合を試みます。
　→[提案国]が、[WAR_GOAL.GetCountryFormation.GetAdjective]の劣等国すべての併合を試みる。

**Comment by inarizushi0309** [comment]
上記修正案で確定しました
