### ISSUE TITLE
補正「ナイル川の水源を見つけること」

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#639]
### スクリーンショット

![image](https://user-images.githubusercontent.com/37979626/216764461-7011f6ea-6054-444d-a1af-e1e412574f75.png)

### 問題のツールチップ

ナイル川調査を実施した国家の国家画面＞情報タブ＞該当アイコンマウスオーバー

### 問題の表現

ナイル川の水源を見つけること

### 問題箇所の英文

Found the Source of the Nile

### 希望する変更

ナイル川の水源の発見

### 変更の理由（概要）

自然な表現にするため

### 変更の理由（詳細）

補正名として現行訳はダサい

### プレイ国家

ロシア

### ゲームバージョン

1.1.X

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通りで修正しました
