### ISSUE TITLE
【修正提案】飾り細工工房

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#64]
＜ゲームシステム用語＞

## スクリーンショット（任意）

![20221027081101_1](https://user-images.githubusercontent.com/43299334/198196681-0c502efa-e95a-4c5a-8ffe-7fd81a03dfd7.jpg)

## 問題の用語（必須）

飾り細工工房

## 英語版の表現（任意）

Tooling Workshops

## 希望する変更（必須）

工具工房

## 変更の理由（必須）

飾り細工の要素はないため。

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

無し

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1035057467995987978
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by Zousuikakka** [comment]
工具工房で修正

**Comment by matanki-saito** [comment]
## 英語版の表現（任意）

Tooling Workshops
