### ISSUE TITLE
「この相手方の沿岸部は提督が哨戒しています」

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#640]
### スクリーンショット

![image](https://user-images.githubusercontent.com/37979626/216770583-f49e1304-2bfb-44f0-af31-65361bbf80ea.png)

### 問題のあるインターフェイス

海域画面＞海軍タブ

### 問題のテキスト

この相手方の沿岸部は$concept_admirals$が哨戒しています

### 希望する変更

この沿岸部を哨戒中の$concept_admirals$

### 変更の理由（概要）

自然な表現にするため

### 変更の理由（詳細）

上の船団襲撃のと似た表記にすべき

### ゲームバージョン

1.1.X

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通りで修正しました
