### ISSUE TITLE
ウテ

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#641]
### スクリーンショット

![20230205201835_1](https://user-images.githubusercontent.com/38329957/216816130-25470c23-2c21-4de0-9abd-d630d32c60f4.jpg)

### 問題の固有名詞：希望する変更

ウテ：ユート

### 変更の理由（概要）

日本語では一般的ではない表記であるため

### 変更の理由（詳細）

発音記号的にも「ユート」と表記すべき。
https://ja.wikipedia.org/wiki/%E3%83%A6%E3%83%BC%E3%83%88%E6%97%8F

### ゲームバージョン

1.1.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
