### ISSUE TITLE
一部地名の誤訳修正

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#642]
### スクリーンショット

なし

### 問題の固有名詞：希望する変更

レオナルドタウン：レナードタウン
テグチガルパ：テグシガルパ
デイヴィド：ダビド
ラスタブラス：ラス・タブラス
ビジャビセンチオ：ビジャビセンシオ
ザカテコルカ：サカテコルカ

ジョクジャカルタ：ジョグジャカルタ

### 変更の理由（概要）

日本語では一般的ではない表記であるため

### ゲームバージョン

1.1.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
以下を追加
ジョクジャカルタ：ジョグジャカルタ

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
