### ISSUE TITLE
世界の労働者

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#643]
### スクリーンショット

なし

### 問題部分

タイトル, 選択肢

### 問題のイベントタイトル

世界の労働者

### 問題のイベント本文（抜粋可）

なし

### 問題のイベント選択肢

世界の労働者は団結せよ！失うものは足かせだけだ！

### 希望する変更（修正部分のみ）

世界の労働者　→　万国の労働者

世界の労働者は団結せよ！失うものは足かせだけだ！　→　万国の労働者よ団結せよ！鉄鎖の他に失うものは何もない！

### 変更の理由（概要）

定訳に変更

### 変更の理由（詳細）

共産党宣言に載っている有名な語句、すべて共産主義系の文章であることを確認済み。

### ゲームバージョン

1.1.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
