### ISSUE TITLE
法の進歩（Law Advancement）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#644]
### スクリーンショット

![Law](https://user-images.githubusercontent.com/42687608/217756623-e71918ff-6e94-427a-9cbe-bb5224861ab8.jpg)

### 問題のあるインターフェイス

法律制定のトースト

### 問題のテキスト

法の進歩

### 希望する変更

法律制定の進捗

### 変更の理由（概要）

実際のゲームメカニズムと異なっている

### 変更の理由（詳細）

このメッセージは法律の制定成功率が変動するタイミングで表示される。
成功率が上がる場合だけでなく、下がる場合にも表示されるので「法の進歩」という表現は明らかにおかしい。
advancementは「進展」「前進」くらいの意味だと思われるが、後退する場合もあるので「進捗」とした。

### ゲームバージョン

1.2.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
修正案の通り修正しました。
