### ISSUE TITLE
ニを二と誤字

### ISSUE THREAD

**Issue by 2022fff** [matanki-saito/vic3jpadvmod#645]
### スクリーンショット

![20230217130421_1](https://user-images.githubusercontent.com/87253874/220096369-332faed1-5b89-4e96-aafa-2a6b76b5564a.jpg)

### 問題の固有名詞：希望する変更

ペルテヴ二ヤル　→　ペルテヴニヤル

### 変更の理由（概要）

漢数字の二で誤記しているため

### ゲームバージョン

1.2.X

### MOD有無

JapaneseLanguageAdvancedMod

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
ありがとうございます。修正いたしました。
