### ISSUE TITLE
タンジマートイベント補正名ミス

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#648]
### スクリーンショット

![image](https://user-images.githubusercontent.com/37979626/229158899-e55ba5ca-7c9a-4358-94ca-fed7b7980ff3.png)

### 問題のツールチップ

イベント「忖度なしの記事」>「ペンは強し。」マウスオーバー

### 問題の表現

ジャーナリストに支払う。
記事が評判を傷つけた。

### 問題箇所の英文

Paying Journalist.
Article Damages Reputation.

### 希望する変更

ジャーナリストへの支払い
記事による評判悪化

### 変更の理由（概要）

誤訳

### 変更の理由（詳細）

#538 と同様で英語では"get [補正名]"であるため、句点が含まれていても問題なかったが、日本語では「[補正名]を得ます」と語順が変わってしまう。

### ゲームバージョン

1.2.X

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。
