### ISSUE TITLE
【助詞抜け】イベント「説得」の説明文

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#649]
### スクリーンショット

![image](https://user-images.githubusercontent.com/37979626/229160925-b4412dd4-a10b-403b-9146-b844312ce0a5.png)

### 問題部分

本文

### 問題のイベントタイトル

説得

### 問題のイベント本文（抜粋可）

[SCOPE.sCharacter('suppressed_leader').GetHerHis]生活に関する噂がすべての階級に到達し、[SCOPE.sCharacter('suppressed_leader').GetHerHis]の評判はがた落ちです。[SCOPE.gsInterestGroup('target').GetName]リーダーとしての[SCOPE.sCharacter('suppressed_leader').GetHerHis]役職から辞任するよう[SCOPE.sCharacter('suppressed_leader').GetFullName]を説得することができるはずです。

### 希望する変更（修正部分のみ）

[SCOPE.sCharacter('suppressed_leader').GetFullName]の生活に関する噂がすべての階級に広まり、[SCOPE.sCharacter('suppressed_leader').GetHerHis]の評判はがた落ちです。そのため[SCOPE.gsInterestGroup('target').GetName]リーダーとしての役職から辞任するよう[SCOPE.sCharacter('suppressed_leader').GetHerHis]を説得することができるはずです。

### 変更の理由（概要）

助詞抜け

### 変更の理由（詳細）

助詞抜け以外にも人物名を先出し、原文のWithを訳出したほうが適切と判断し修正
With the rumors about [GetHerHis] way of life reaching all social strata and [GetHerHis] reputation undermined, we can certainly persuade [GetFullName] to step down from [GetHerHis] position as the leader of [GetName].

### プレイ国家

オスマン

### ゲームバージョン

1.2.X

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通り修正しました
