### ISSUE TITLE
【修正提案】アグレアリアン党

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#65]
## スクリーンショット（任意）

![20221027091540_1](https://user-images.githubusercontent.com/43299334/198197166-604fe6ef-738b-4250-9e6c-5df3a2d08c3d.jpg)

## 問題の固有名詞（必須）

アグレアリアン党

## 希望する変更（必須）

農民党

## 変更の理由（必須）

原語Agrarian Partyの音写。Peasants（小作農）の政党。
特に音写する理由もなく翻訳可能と思われる。

## ゲームバージョン（必須）

（例）1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1035058581340422194
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by Zousuikakka** [comment]
農業党で修正
