### ISSUE TITLE
【改訳】外交戦の略称「プレイ」

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#650]
### スクリーンショット

![image](https://user-images.githubusercontent.com/37979626/229175957-d7d31b1e-798f-441d-aedc-0eaa42e87b96.png)

### 問題の用語

プレイ

### 英語版の表現

Play

### 希望する変更

外交戦

### 変更の理由（概要）

分かりにくい

### 変更の理由（詳細）

もともとはDiplomatic Play「外交プレイ」の略称Play「プレイ」となっていたが #52 でDiplomatic Playのみ改訳され、訳の統一性が失われいる。さらに「外交戦」に改訳したことで字数が略称のものと同じになったため、訳仕分ける必要性がなくなった。

### ゲームバージョン

1.2.X

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。
