### ISSUE TITLE
【改訳】「リーダーシップ」外交戦

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#651]
### スクリーンショット

![image](https://user-images.githubusercontent.com/37979626/229177639-a910b60f-eb20-4a70-a62b-c62cdbe42de6.png)
![image](https://user-images.githubusercontent.com/37979626/229181684-7ebb6ecd-c353-4d99-883e-60555bfc1059.png)

### 問題の用語

リーダーシップ

### 英語版の表現

Leadership

### 希望する変更

統一主導

### 変更の理由（概要）

文字溢れ

### 変更の理由（詳細）

地域統一に関する外交の主導権を指すゲーム用語だが、一部で文字溢れが発生しているため、字数削減する必要がある。

改訳に伴う影響エントリ：
ドイツのリーダーシップ→ドイツの統一主導
イタリアのリーダーシップ→イタリアの統一主導
スカンジナビアのリーダーシップ→スカンジナビアの統一主導
統一リーダーシップ→統一主導
[WAR_GOAL.GetCountryFormation.GetAdjective]のリーダーシップ→[WAR_GOAL.GetCountryFormation.GetAdjective]の統一主導
[Concept('concept_diplomatic_play', '$concept_diplomatic_play_short$')]リーダーシップを発足→統一主導[Concept('concept_diplomatic_play', '$concept_diplomatic_play_short$')]を開始

### ゲームバージョン

1.2.X

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通り修正しました
