### ISSUE TITLE
イベントの効果文がおかしい

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#654]
### スクリーンショット

![20230405134820_1](https://user-images.githubusercontent.com/38329957/230163405-75a80bdf-6402-4d5c-8bad-f9d56edc6c84.jpg)

### 問題部分

選択肢

### 問題のイベントタイトル

アールヌーボー

### 希望する変更（修正部分のみ）

フランスは、の美術品に執着になりました　→　フランス人は、美術品に執着する様になりました

### 変更の理由（概要）

表示がおかしい

### プレイ国家

フランス

### ゲームバージョン

1.2.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
