### ISSUE TITLE
国号と称号

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#656]
### スクリーンショット

なし

### 問題の固有名詞：希望する変更

へディーヴ国：副王領
大公国：公国
女王陛下の政府：陛下の政府
司教国：主教公国
司教：主教公
へディーヴ：副王
首席司教：大主教
バーゴマスター：市長

### 変更の理由（概要）

ほぼ誤訳であるため

### 変更の理由（詳細）

ヘディーヴ国→副王領　エジプトにしか使われておらず、一般にはヘディーヴ国よりも副王領の方が知名度が高いと思われる。なお、「へディーヴ」の「へ」がひらがなになっている。
ヘディーヴ→副王　同上

大公国→公国　前回のPrincipality修正時のミス、ワラキアやセルビアで使われている

女王陛下の政府→陛下の政府　国王の時でも使用されるため

司教国→主教公国　モンテネグロ独自のもの、主教が世俗の君主を務めていた。
司教→主教公　同上

首席司教→大主教　主席司教という称号は存在しない。

バーゴマスター→市長　ドイツの都市国家の元首の称号

### ゲームバージョン

1.2.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
