### ISSUE TITLE
アールヌーボー

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#657]
### スクリーンショット

なし

### 問題の固有名詞：希望する変更

アールヌーボー：アール・ヌーヴォー

### 変更の理由（概要）

一般的ではない表記であるため。

### 変更の理由（詳細）

Wikipediaの記事名がアール・ヌーヴォーだったのと、文化庁が出してる広報誌でアール・ヌーヴォー表記だったので、こっちの方が広まってそうだなと思って立てました。

### ゲームバージョン

1.2.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
