### ISSUE TITLE
チェックボックスマークがXや(*)に置き換わっている

### ISSUE THREAD

**Issue by mochi115** [matanki-saito/vic3jpadvmod#658]
### スクリーンショット

![20230328175621_1](https://user-images.githubusercontent.com/117048815/230413674-3451ee1e-69ae-4907-b22f-798989770166.jpg)

### 問題のあるインターフェイス

複数

### 問題のテキスト

X  (*)

### 希望する変更

MOD内のtrigger_system_l_japanese.ymlのキーを
```
TRIGGER_LINE_ACTIVE_PASSED:0"@green_checkmark_box! $TEXT$"
TRIGGER_LINE_ACTIVE_FAILED:0 "@simple_box! $TEXT$"
TRIGGER_LINE_ACTIVE_UNDEFINED:0 "  •  $TEXT$"
TRIGGER_LINE_INACTIVE_PASSED:0 "@green_checkmark_box! $TEXT$"
TRIGGER_LINE_INACTIVE_FAILED:0 "@simple_box! $TEXT$"
TRIGGER_LINE_INACTIVE_UNDEFINED:0 "   •  $TEXT$"
TRIGGER_LINE_BLOCKER:0 "@simple_box! #N #italic $TEXT$#!#!"
TRIGGER_LINE_UNEVALUATED:0 "  •  $TEXT$"
```
に変更する。

### 変更の理由（概要）

チェックボックスマークに変更

### 変更の理由（詳細）

Victoria3のtrigger_system_l_japanese.ymlはgameフォルダ内部とjominiフォルダ内部の両方に存在していて、MOD内のtrigger_system_l_japanese.ymlはおそらく前者のものを置き換えていると思われます。

### ゲームバージョン

1.2.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
MOD作成時にファイルを含めないようにしました

**Comment by matanki-saito** [comment]
修正されたことを確認したためCloseします
