### ISSUE TITLE
州立教会

### ISSUE THREAD

**Issue by mochi115** [matanki-saito/vic3jpadvmod#659]
### スクリーンショット

![20230328175008_1](https://user-images.githubusercontent.com/117048815/230425992-cf5c8323-da35-4526-91c6-ee9d26a1994d.jpg)

### 問題の用語

州立教会

### 希望する変更

国教会

### 変更の理由（概要）

より適切な語に変更

### 変更の理由（詳細）

自由教会は国教会と対になっているみたいです。
https://ja.wikipedia.org/wiki/%E8%87%AA%E7%94%B1%E6%95%99%E4%BC%9A

### ゲームバージョン

1.2.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
修正対応いたしました
