### ISSUE TITLE
【修正提案】名誉回復（維新ジャーナル）

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#66]
## スクリーンショット（任意）

![20221027093654_1](https://user-images.githubusercontent.com/43299334/198197604-2db75a93-5f6e-4422-9688-faf8c55c2c00.jpg)

##　問題部分（タイトル・本文・選択肢）

名誉回復

## 問題のイベントタイトル（必須）

名誉回復

## 問題のイベント本文（任意・抜粋可）

-

## 問題のイベント選択肢（任意）

-

## 希望する変更（必須・修正部分のみ）

栄えある維新

## 変更の理由（必須）

原語Honorable Restorationの直訳。明治維新はMeiji Restorationが定訳であり、原語は明らかにこれを念頭においている。
また、このジャーナルを完了すると、その後「維新：～」というジャーナルが複数出現し、ここではRestorationが維新と訳されているため、表記ゆれを起こしている場所でもある。
余談だが、天皇の名前が入るべき「～の復権」に現在の指導者の名前が入るミスがみられるが、これはローカライズではなく本体側のミスと思われる。

## プレイ国家

日本

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1035060232008765520
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by Zousuikakka** [comment]
大政奉還で修正
