### ISSUE TITLE
No Goods

### ISSUE THREAD

**Issue by mochi115** [matanki-saito/vic3jpadvmod#660]
### スクリーンショット

![20230328175318_1](https://user-images.githubusercontent.com/117048815/230433887-e9938de3-8d99-416a-a8b5-e4e81842c999.jpg)

### 問題のあるインターフェイス

方式変更時のインターフェース

### 問題のテキスト

No Goods

### 希望する変更

商品なし

### 変更の理由（概要）

未翻訳

### ゲームバージョン

1.2.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
ご指摘ありがとうございます。修正しました。
