### ISSUE TITLE
○○産業界の苦境イベント

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#663]
### スクリーンショット

![Victoria 3 Screenshot 2023 04 09 - 21 26 09 15](https://user-images.githubusercontent.com/42710893/230776235-5d162a2f-c2f8-4b0c-9737-528bd4d822c7.png)

### 問題部分

選択肢

### 問題のイベントタイトル

○○産業界の苦境

### 問題のイベント選択肢

選択肢B
```我々改革計画による恩恵を[SCOPE.sState('industrial_protectionist_state').GetName]に納得してもらわねば。```

### 希望する変更（修正部分のみ）

```我々の改革計画による恩恵を[SCOPE.sState('industrial_protectionist_state').GetName]に納得してもらわねば。```

### 変更の理由（概要）

助詞抜け

### プレイ国家

アルゼンチン

### ゲームバージョン

1.2.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。
