### ISSUE TITLE
【誤訳・表記ゆれ】急進派・体制派の内訳ポップアップ

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#664]
### スクリーンショット

![image](https://user-images.githubusercontent.com/37979626/231218434-2571b755-c9c8-49c5-9db6-e60c0644ee9e.png)
![image](https://user-images.githubusercontent.com/37979626/231218531-e8a4d2e7-9585-41b4-a9bd-207ea73561a1.png)

### 問題のあるインターフェイス

急進派・体制派の内訳ポップアップ

### 問題のテキスト

```\n\n[concept_interest_group]による$concept_radicals$:```
```\n\n[concept_interest_group]による$concept_loyalists$:```
```\n$TAB$[InterestGroup.CalcNumRadicals|vD]人の[InterestGroup.GetName]```
```\n$TAB$[InterestGroup.CalcNumLoyalists|vD]人の[InterestGroup.GetName]```
```\n[InterestGroup.CalcNumRadicals|vD]人の[InterestGroup.GetName]```
```\n[InterestGroup.CalcNumLoyalists|vD]人の[InterestGroup.GetName]```
```\n$TAB$その他の[Concept('concept_interest_group', '$concept_interest_groups$')]内に#tooltippable #tooltip:[GetRawTextTooltipTag('$BREAKDOWN$')] $VAL|vD$#!#!```
```[concept_profession]による$concept_radicals$:```
```[concept_profession]による$concept_loyalists$:```
```\n$TAB$その他の[Concept('concept_profession','$concept_professions$')]内に#tooltippable #tooltip:[GetRawTextTooltipTag('$BREAKDOWN$')] $VAL|vD$#!#!```

### 希望する変更

![image](https://user-images.githubusercontent.com/37979626/231222599-2500fd09-bdaf-4a5e-b17c-dcdf95dbd15a.png)
```\n\n[concept_interest_group]ごとの$concept_radicals$:```
```\n\n[concept_interest_group]ごとの$concept_loyalists$:```
```\n$TAB$[InterestGroup.CalcNumRadicals|vD] [InterestGroup.GetName]```
```\n$TAB$[InterestGroup.CalcNumLoyalists|vD] [InterestGroup.GetName]```
```\n[InterestGroup.CalcNumRadicals|vD] [InterestGroup.GetName]```
```\n[InterestGroup.CalcNumLoyalists|vD] [InterestGroup.GetName]```
```\n$TAB$#tooltippable #tooltip:[GetRawTextTooltipTag('$BREAKDOWN$')] $VAL|vD$#!#!その他の[Concept('concept_interest_group', '$concept_interest_groups$')]```
```[concept_profession]ごとの$concept_radicals$:```
```[concept_profession]ごとの$concept_loyalists$:```
```\n$TAB$#tooltippable #tooltip:[GetRawTextTooltipTag('$BREAKDOWN$')] $VAL|vD$#!#!その他の[Concept('concept_profession','$concept_professions$')]```

### 変更の理由（概要）

表記統一

### 変更の理由（詳細）

職業ごとの内訳と利益集団ごとの内訳で表記が違うので、職業の方に合わせる形で修正。

### ゲームバージョン

1.2.X

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
「その他の○○」の部分は「その他○○」になるように、その他は原案通り修正しました。
