### ISSUE TITLE
【体裁統一】行政力使用量ポップアップ

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#665]
### スクリーンショット

![image](https://user-images.githubusercontent.com/37979626/231747641-276cd836-ebbf-4eab-981f-9f320a9dfd66.png)
![image](https://user-images.githubusercontent.com/37979626/231747695-98f5e23f-1db9-4a34-86ce-b1f937a7ff8c.png)
![image](https://user-images.githubusercontent.com/37979626/231750788-0a0987c2-13d6-4694-8c6b-9ec154b22538.png)
![image](https://user-images.githubusercontent.com/37979626/231750826-5aa08cf4-ed43-4063-b704-32a06872b6d5.png)
![image](https://user-images.githubusercontent.com/37979626/231750875-a5638f6a-e9ce-4173-ab22-dfacdc8773ac.png)
![image](https://user-images.githubusercontent.com/37979626/231750927-294527a2-b2d0-4351-b0cf-ce802a17852d.png)

### 問題のあるインターフェイス

行政力ポップアップ

### 問題のテキスト

```#tooltippable #tooltip:$BREAKDOWN_TAG$ $NUM_INCORPORATED_STATES|v$個の[Concept('concept_incorporated_state', '$concept_incorporated_states$')]内の$POPULATION|Kv$人から$COST|+=0$#!#!```
```#tooltippable #tooltip:$BREAKDOWN_TAG$ $NUM_INCORPORATED_STATES|v$ [Concept('concept_incorporated_state', '$concept_incorporated_states$')]全体の[Concept('concept_institution', '$concept_institutions$')]から$COST|+=0$#!#!```
```#tooltippable #tooltip:$BREAKDOWN_TAG$ $NUM_TRADE_ROUTES|v$の[Concept('concept_trade_route', '$concept_trade_routes$')]から$COST|+=0$#!#!```
```#tooltippable #tooltip:$BREAKDOWN_TAG$ $NUM_GENERALS|v$人の[Concept('concept_general', '$concept_generals$')]と$NUM_ADMIRALS|v$人の[Concept('concept_admiral', '$concept_admirals$')]から$COST|+=0$#!#!```

```[INSTITUTION.GetName] ([INSTITUTION.GetInvestmentLevel|v])から$COST|+=0$```
```[State.GetName]から$TOTAL_COST|+=0$（基礎 $STATE_COST|+=0$、$POPULATION|Kv$人から$POPULATION_COST|+=0$）```
```#header @bur![Concept('concept_incorporated_state', '$concept_incorporated_states$')]内の[Concept('concept_pop', '$concept_pops$')]における[concept_bureaucracy]コスト: $COST|+=0$#!\n$TOOLTIP_DELIMITER$\n$BREAKDOWN$```
```[TradeRoute.GetName]から$COST|+=0$```
```[Character.GetCombatUnitsTypeIcon] [Character.GetFullName]から$COST|+=0$```

### 希望する変更

![image](https://user-images.githubusercontent.com/37979626/231751004-91c177d8-9f13-4d05-ac26-0f02c084b8d8.png)
![image](https://user-images.githubusercontent.com/37979626/231753837-af1c1f49-4751-4118-ae17-609180c0e6cb.png)
![image](https://user-images.githubusercontent.com/37979626/231753884-fb84bb5e-23bf-46bb-b02b-e9a390792ffb.png)
![image](https://user-images.githubusercontent.com/37979626/231753932-43f2fb80-1724-44ae-ab45-4fad8c1c106c.png)
![image](https://user-images.githubusercontent.com/37979626/231753972-77bfa034-afb2-408c-aab4-c75dd3ddcf22.png)

```#tooltippable #tooltip:$BREAKDOWN_TAG$ $COST|+=0$#!#!（[Concept('concept_incorporated_state', '$concept_incorporated_states$')]$NUM_INCORPORATED_STATES|v$州の人口$POPULATION|Kv$）```
```#tooltippable #tooltip:$BREAKDOWN_TAG$ $COST|+=0$#!#!（[Concept('concept_incorporated_state', '$concept_incorporated_states$')]$NUM_INCORPORATED_STATES|v$州に対する[Concept('concept_institution', '$concept_institutions$')]）```
```#tooltippable #tooltip:$BREAKDOWN_TAG$ $COST|+=0$#!#!（[Concept('concept_trade_route', '$concept_trade_routes$')]$NUM_TRADE_ROUTES|v$本）```
```#tooltippable #tooltip:$BREAKDOWN_TAG$ $COST|+=0$#!#!（[Concept('concept_general', '$concept_generals$')]$NUM_GENERALS|v$名・[Concept('concept_admiral', '$concept_admirals$')]$NUM_ADMIRALS|v$名）```

```$COST|+=0$（[INSTITUTION.GetName] ([INSTITUTION.GetInvestmentLevel|v])）```
```$TOTAL_COST|+=0$ [State.GetName]（基礎 $STATE_COST|+=0$、人口$POPULATION|Kv$ $POPULATION_COST|+=0$）```
```#header @bur![Concept('concept_incorporated_state', '$concept_incorporated_states$')]にいる[Concept('concept_pop', '$concept_pops$')]の[concept_bureaucracy]コスト: $COST|+=0$#!\n$TOOLTIP_DELIMITER$\n$BREAKDOWN$```
```$COST|+=0$（[TradeRoute.GetName]）```
```$COST|+=0$（[Character.GetCombatUnitsTypeIcon] [Character.GetFullName]）```

### 変更の理由（概要）

変数ミス

### 変更の理由（詳細）

・下線を指定する変数が英語版に比べ、長く設定されており、視認性が悪化している
・「○○から数値」と英語版と語順が逆になっていることから、重要な数値の情報が確認しづらくなっている

### ゲームバージョン

1.2.X

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通り修正しました
