### ISSUE TITLE
【体裁統一】予算内訳ポップアップ

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#668]
### スクリーンショット

![image](https://user-images.githubusercontent.com/37979626/231815144-9afc1dbd-af21-4449-b07c-abd438a9ceef.png)
![image](https://user-images.githubusercontent.com/37979626/231815195-5af8bba1-0217-4011-a5c0-77eb36376883.png)
![image](https://user-images.githubusercontent.com/37979626/231815252-2936ef88-cad6-4b5b-b4ad-d8b670fc7c88.png)
![image](https://user-images.githubusercontent.com/37979626/231817966-cdc2e53f-4e74-4ef7-a480-711e8656d13c.png)

### 問題のあるインターフェイス

予算ポップアップ

### 問題のテキスト

```[BuildingType.GetName]による#N #variable @money!$VAL|D+$#!#!```

```[Goods.GetName]の輸入による#N #variable @money!$VAL|D+$#!#!```
```[Goods.GetName]の輸出による#N #variable @money!$VAL|D+$#!#!```

```[BUILDING_TYPE.GetName]による#N #variable @money!$EXPENSE|D-$#!#!```

```[BuildingType.GetName]の[Concept('concept_government_ownership_share', '$concept_government_ownership_shares$')]による#N #variable @money!$VAL|D+$#!#!```

### 希望する変更

![image](https://user-images.githubusercontent.com/37979626/231815046-2d4403ab-ec82-4dae-8cb5-ba4f1231d7cc.png)
![image](https://user-images.githubusercontent.com/37979626/231814925-f4a7e610-10c0-4489-ae10-94a20226f5a2.png)
![image](https://user-images.githubusercontent.com/37979626/231814981-fa8412b9-280a-49ac-9444-e2e2ba9e9132.png)
![image](https://user-images.githubusercontent.com/37979626/231818857-7a4d7142-c84c-452b-95e8-6b9c8f679dfd.png)

```#N #variable @money!$VAL|D+$#!#!:[BuildingType.GetName]```

```#N #variable @money!$VAL|D+$#!#!:[Goods.GetName]の輸入``
```#N #variable @money!$VAL|D+$#!#!:[Goods.GetName]の輸出```

```#N #variable @money!$EXPENSE|D-$#!#!:[BUILDING_TYPE.GetName]```

```#N #variable @money!$VAL|D+$#!#![BuildingType.GetName]の[Concept('concept_government_ownership_share', '$concept_government_ownership_shares$')]```

### 変更の理由（概要）

数値を見やすくするため

### 変更の理由（詳細）

「○○から数値」と英語版と語順が逆になっていることから、重要な数値の情報が確認しづらくなっている
#665 と類似しているが、 #519 との関連が深いため、表記は後者に寄せた

### ゲームバージョン

1.2.X

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通り修正しました

**Comment by inarizushi0309** [comment]
施設まわりのシステム変更に伴い以下エントリを再度修正しました。
```#N #variable @money!$VAL|D+$#!#! [BuildingType.GetName]の[concept_nationally_owned]```
→　```#N #variable @money!$VAL|D+$#!#! : [concept_nationally_owned]の[BuildingType.GetName]```
