### ISSUE TITLE
【修正提案】動揺度が高い状態のサジェスチョン、ツールチップ

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#67]
## スクリーンショット（必須）

![20221027101936_1](https://user-images.githubusercontent.com/43299334/198198633-1b314ccc-1a32-44c6-8592-f137fc64d30e.jpg)

## 問題のツールチップ（必須）

サジェスチョン「州は動揺度状態です」のツールチップ

## 問題の表現（必須）

（州）は動揺度状態です

## 問題箇所の英文（任意）

[SCOPE.GetRootScope.GetState.GetName] is in [concept_turmoil]

## 希望する変更（必須）

[SCOPE.GetRootScope.GetState.GetName]は[concept_turmoil]の高い状態です

## 変更の理由（必須）

日本語の文法として不自然なため。
動揺度の訳を変更しない場合は上記がよいと思われる。
サジェスチョンのタイトルにも同様の問題がある。

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1035061988683939880
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by Zousuikakka** [comment]
[SCOPE.GetRootScope.GetState.GetName]は[concept_turmoil]が高い状態です
で修正
