### ISSUE TITLE
【体裁統一】影響力内訳ポップアップ

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#670]
### スクリーンショット

![image](https://user-images.githubusercontent.com/37979626/231829118-1549d554-e4ef-4015-a22a-34f671de11f8.png)

### 問題のあるインターフェイス

影響力ポップアップ

### 問題のテキスト

```[Country.GetName]との$PACT$により#tooltippable #tooltip:$BREAKDOWN_TAG$ #variable $COST|+=0$#!#!#!```

### 希望する変更

![image](https://user-images.githubusercontent.com/37979626/231831794-0b39c6ad-6e11-48bd-8649-6f2943892f9d.png)
![image](https://user-images.githubusercontent.com/37979626/231831841-4ce9b318-9c42-4a02-9381-8234b9379cc3.png)
```#tooltippable #tooltip:$BREAKDOWN_TAG$ #variable $COST|+=0$#!#!#!（$PACT$ : [Country.GetName]）```

### 変更の理由（概要）

数値を見やすくするため

### 変更の理由（詳細）

英語は`from $PACT$ with [Country.GetName]`で$PACT$には様々な外交コマンドが入るため単に「○○との$PACT$」と訳すには限界があるため上記訳を提案

### ゲームバージョン

1.2.X

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通り修正しました
