### ISSUE TITLE
修正が反映されなくなった箇所がある

### ISSUE THREAD

**Issue by mochi115** [matanki-saito/vic3jpadvmod#671]
### スクリーンショット

![20230414183929_1](https://user-images.githubusercontent.com/117048815/232320769-3ff5fc67-66ff-4b10-9c2e-50cad6fd1dd6.jpg)

### 問題の用語

他多数

### 希望する変更

modifiers_l_japanese.ymlの復活。

### 変更の理由（概要）

modifiers_l_japanese.ymlがこのMODから消去されているのが原因みたいです。

### ゲームバージョン

1.2.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
修正を確認したためCloseしています
