### ISSUE TITLE
共和主義者(知識人のイデオロギー)

### ISSUE THREAD

**Issue by mochi115** [matanki-saito/vic3jpadvmod#672]
### スクリーンショット

![20230406223037_1](https://user-images.githubusercontent.com/117048815/232321156-83157f4f-e767-44a7-8055-ee5010981e27.jpg)

### 問題の用語

共和主義者

### 希望する変更

共和主義

### 変更の理由（概要）

用語の統一

### 変更の理由（詳細）

利益集団のイデオロギーは～主義、リーダーのイデオロギーは～主義者と分けられているため。

### ゲームバージョン

1.2.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
