### ISSUE TITLE
複合姓および複合名の人名

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#673]
### 問題の固有名詞：希望する変更

ド・サン・タンドレ：ド・サン＝タンドレ

コート・ハイリガース：コルト＝ヘイリヘルス
ファン・ザクセン・ワイマール：ファン・サクセン＝ヴァイマル
ファン・オラニエ・ナッサウ：ファン・オラニエ＝ナッサウ

フォン・ザリス・ゾギロ：フォン・ザリス＝ソーリオ
フォン・ホルシュタイン・グリュックスブルク：フォン・ホルシュタイン＝グリュックスブルク
フォン・ヘッセ・カッセル：フォン・ヘッセン＝カッセル

オブ・ザクセン・コーブルク・ゴータ：サクス＝コブール・エ・ゴータ

フォン・ミットロヴィッツ・ネットリツキー：フォン・ミットロヴィッツ＝ネットリツキー
ブラク・バラホーヴィッチ：ブワク＝バワホヴィチ

ド・サン・ジュスト：ド・サン＝ジュスト
フルーリー・ドゥベイ：フルーリー＝デュベ

ジーグヴァルト・ミュラー：ジークヴァルト＝ミュラー

アスプ・ペルソン：アスプ＝ピアソン
ダンネスコルド・サムソ：ダネスキョル＝サムスー
シャック・シャッケンボルク：シャク＝シャケンボー
ヴェーデル・ハイエン：ヴィーゼル＝ハイネン
ジトフェン・アデラー：ズトフェン＝エーゼラ

ヴェーデル・ヤールスベルク：ヴェーデル＝ヤールスベルグ
ツァイナー・グンダーセン：ツェイナー＝グンデルセン
コシェロン・アーモット：コウヘロン＝アーモト

スミス・ドリエン：スミス＝ドリエン

ダズブルゴ・トスカーナ：ダズブルゴ＝トスカーナ
オーストリア・エステ：ダウストリア＝エステ

アル・アルバーニ：アル＝アルバーニ
メルリカ・クルジャ：メルリカ＝クルヤ

フィグス・ビストリー：フィグシュ＝ビストリー
ハーバン・ファヤンスキー：フルバン＝ヴァヤンスキー
スカルテティ・ゲブリス：シュクルテーティ＝ガーブリシュ

クリスタキス・ゾグラフォス：フリスタキス＝ゾグラフォス
ティパルドス・アルフォンサトス：ティパルドス＝アルフォンサトス
ピエラコス・マヴロミカリス：ピエラコス＝マヴロミハリス
トライフィアティス・トリピアリス：トリフィアティス＝トリピアリス

メリーク・アグハマリアン：メリク＝アガマリャン
ター・サルカイアン：テル＝サルキシャン

コーピエタース・ワラント：コーピーテルス＝ト・ワラント
メリー・アリックス：マリー＝アリックス

アフ・ダンネスキョルド・サムソー：ア・ダネスキョル＝サムスー

アレニー・プランドリット：ダレニ＝プランドリト

ベイン・テンペスト：ヴェイン＝テンペスト
ドレイク・ブロックマン：ドレイク＝ブロックマン

アウグスト・マリー：オーギュスト＝マリー
エドアルド・マリー：エドゥアール＝マリー
レイモンド・マリー：レーモン＝マリー
デスピネイ：デスピネ
ジーン・デニス：ジャン＝ドニ
ミッチェル・オーギュスティン：ミシェル＝オーギュスタン
プルーデンス・ジュラウム：プリュダンス＝ギヨーム

フォン・ツア・ミューレン：フォン・ツア＝ミューレン

ド・ルス・ミルザ：デ・レウス＝ミルザ
ディノット・ガスティ：ディノット＝グスティ

コロレード・マンスフェルド：コッロレード＝マンスフェルト
スン・ホーエンスタイン：トゥーン＝ホーエンシュタイン

ホイニンゲン・ヒューネ：ホイニンゲン＝ヒューネ
ベレフスキー・ズコフスキー：ベリョーフスキー＝ジュコフスキー

マリー・クレア：マリー＝クレール
マリー・マデライン：マリー＝マドレーヌ
マリー・ローズ：マリー＝ローズ

オーギュスト・レアル：オーギュスト＝レアル
フランソワ・レアル：フランソワ＝レアル

ハミルトン・テンプル・ブラックウッド：ハミルトン＝テンプル＝ブラックウッド
ホイットワース・アイルマー：ホイットワース＝アイルマー
ペティ・フィッツモーリス：ペティ＝フィッツモーリス
ダグラス・ホーム：ダグラス＝ホーム
モンタギュ・スコット：モンタギュー＝スコット
ロイド・モスティン：ロイド＝モスティン

バート・シシンスキー：バルト＝チシンスキ

ルイズ・ターグル：ルイス＝タグレ

ボイスロンド・カナル：ボワロン＝カナル
プライス・マーズ：プリス＝マルス
リヴィーレ・ヘラルド：リヴィエール＝エラール
ルイス・ユーゲネ：ルイ＝ウジェーヌ
ルイス・ジョセフ：ルイ＝ジョゼフ

ジョージ・ヴィクトール：ゲオルク・ヴィクトル
チャールズ・フレデリック：カール・フリードリヒ
チャールズ・アレキサンダー：カール・アレクサンダー

カール・アントン：カール＝アントン
フレデリック・ウィリアム：フリードリヒ＝ヴィルヘルム

ジーン・フランソワ：ジャン＝フランソワ
ジーン・ルイス：ジャン＝ルイ
ジーン・ジャッケス：ジャン＝ジャック
フィリップ・ジョセフ：フィリップ＝ジョゼフ
ピエール・ジローム：ピエール＝ギヨーム

アムロイス・ディディム：アンブロワーズ＝ディディム

ルイス・フィリッペ：ルイ＝フィリップ

ジーン・ピエール：ジャン＝ピエール

ジャン・リュック：ジョアン＝リュク
ジャン・マルク：ジョアン＝マルク

カルネ・ロス：カルネ＝ロス

フォン・ビッシンゲン・ニッペンブルク：フォン・ビッシンゲン＝ニッペンブルク
ツ・シュトルベルグ・ヴェルニゲローデ：ツー・シュトルベルク＝ヴェルニゲローデ
フォン・ヘグネンベルグ・デュクス：フォン・ヘグネンベルク＝ドゥクス
フォン・シェーンボルン・ヴィーゼンハイト：フォン・シェーンボルン＝ヴィーゼンタイト
フォン・エッティンゲン・ヴァラーシュタイン：フォン・エッティンゲン＝ヴァラーシュタイン
フォン・ホーエンローエ・ランゲンブルク：フォン・ホーエンローエ＝ランゲンブルク
フォン・ホルンシュタイン・ブスマンスハウゼン：フォン・ホルンシュタイン＝ブスマンスハウゼン
フォン・ヴェヒター・シュピットラー：フォン・ヴェヒター＝シュピットラー
フォン・ホーエンローエ・エーリンゲン：フォン・ホーエンローエ＝エーリンゲン
フォン・クアド・ヴァクラド・イスニー：フォン・クヴァト＝ヴィクラト＝イスニー
フォン・ヴァルトブルク・ザイル：フォン・ヴァルトブルク＝ツァイル
フォン・アンドロー・ビールゼック：フォン・アンドラウ＝ビルゼク
フォン・ラ・ロッシュ・スターケンフェルス：フォン・ラ・ロシュ＝シュタールケンフェルス
フォン・シュトックホーナー・シュトライン：フォン・シュトックホーナー＝シュタライン
フォン・ボインブルク・レングスフェルト：フォン・ボイネブルク＝レングスフェルト
フォン・イゼンブルク・ブーディンゲン・ミーアホルツ：フォン・イーゼンブルク＝ビューディンゲン＝メーアホルツ
フォン・ゾルムス・ラウバッハ：フォン・ゾルムス＝ラウバッハ
フォン・ブライドバッハ・ビュレスハイム：フォン・ブライトバッハ＝ビュレスハイム
フォン・デュルクハイム・モントマルティン：フォン・デュルクハイム＝モンマルタン
フォン・フレイエン・ザイボルシュトルフ：フォン・フライエン＝ザイボルツトルフ
フォン・シュトクム・シュターンフェルス：フォン・シュトクム＝シュターンフェルス
フォン・ネゼローデ・フーゲンポエト：フォン・ネッセルローデ＝フーゲンポエート
フォン・フロバーグ・モントイエ：フォン・フローベルク＝モンジョワ
フォン・フライバーグ・アイゼンバーグ：フォン・フライベルク＝アイゼンベルク
フォン・リ・ブレト・ヌコート：フォン・ル・ブレ＝ニュクール
フォン・フェッテン・アーンバッハ：フォン・プフェッテン＝アーンバッハ
フォン・プライジング・ムース：フォン・プライジンク＝モース
フォン・デア・タン・ラッサムハウゼン：フォン・デア・タン＝ラートザムハウゼン
フォン・ライヒリン・メルデッグ：フォン・ライヒリン＝メルデック
フォン・ホイオス・シュプリンツェンシュタイン：フォン・ホヨス＝シュプリンツェンシュタイン
ヴァイス・ヨナク：ヴァイス＝ヨナク

### 変更の理由（概要）

日本語では一般的ではない表記であるため

### ゲームバージョン

1.2.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
以下を追加

フォン・ビッシンゲン・ニッペンブルク：フォン・ビッシンゲン＝ニッペンブルク
ツ・シュトルベルグ・ヴェルニゲローデ：ツー・シュトルベルク＝ヴェルニゲローデ
フォン・ヘグネンベルグ・デュクス：フォン・ヘグネンベルク＝ドゥクス
フォン・シェーンボルン・ヴィーゼンハイト：フォン・シェーンボルン＝ヴィーゼンタイト
フォン・エッティンゲン・ヴァラーシュタイン：フォン・エッティンゲン＝ヴァラーシュタイン
フォン・ホーエンローエ・ランゲンブルク：フォン・ホーエンローエ＝ランゲンブルク
フォン・ホルンシュタイン・ブスマンスハウゼン：フォン・ホルンシュタイン＝ブスマンスハウゼン
フォン・ヴェヒター・シュピットラー：フォン・ヴェヒター＝シュピットラー
フォン・ホーエンローエ・エーリンゲン：フォン・ホーエンローエ＝エーリンゲン
フォン・クアド・ヴァクラド・イスニー：フォン・クヴァト＝ヴィクラト＝イスニー
フォン・ヴァルトブルク・ザイル：フォン・ヴァルトブルク＝ツァイル
フォン・アンドロー・ビールゼック：フォン・アンドラウ＝ビルゼク
フォン・ラ・ロッシュ・スターケンフェルス：フォン・ラ・ロシュ＝シュタールケンフェルス
フォン・シュトックホーナー・シュトライン：フォン・シュトックホーナー＝シュタライン
フォン・ボインブルク・レングスフェルト：フォン・ボイネブルク＝レングスフェルト
フォン・イゼンブルク・ブーディンゲン・ミーアホルツ：フォン・イーゼンブルク＝ビューディンゲン＝メーアホルツ
フォン・ゾルムス・ラウバッハ：フォン・ゾルムス＝ラウバッハ
フォン・ブライドバッハ・ビュレスハイム：フォン・ブライトバッハ＝ビュレスハイム
フォン・デュルクハイム・モントマルティン：フォン・デュルクハイム＝モンマルタン
フォン・フレイエン・ザイボルシュトルフ：フォン・フライエン＝ザイボルツトルフ
フォン・シュトクム・シュターンフェルス：フォン・シュトクム＝シュターンフェルス
フォン・ネゼローデ・フーゲンポエト：フォン・ネッセルローデ＝フーゲンポエート
フォン・フロバーグ・モントイエ：フォン・フローベルク＝モンジョワ
フォン・フライバーグ・アイゼンバーグ：フォン・フライベルク＝アイゼンベルク
フォン・リ・ブレト・ヌコート：フォン・ル・ブレ＝ニュクール
フォン・フェッテン・アーンバッハ：フォン・プフェッテン＝アーンバッハ
フォン・プライジング・ムース：フォン・プライジンク＝モース
フォン・デア・タン・ラッサムハウゼン：フォン・デア・タン＝ラートザムハウゼン
フォン・ライヒリン・メルデッグ：フォン・ライヒリン＝メルデック
フォン・ホイオス・シュプリンツェンシュタイン：フォン・ホヨス＝シュプリンツェンシュタイン
ヴァイス・ヨナク：ヴァイス＝ヨナク

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
