### ISSUE TITLE
国家の形成ツールチップ

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#674]
### スクリーンショット

![Victoria 3 Screenshot 2023 04 21 - 22 38 34 79](https://user-images.githubusercontent.com/42710893/233681996-03feb1fa-1d83-4328-80d3-f8cfc130eab4.png)

### 問題のツールチップ

国家の形成（この場合はイタリアを形成）マウスオーバー時のツールチップ

### 問題の表現

```CANNOT_FORM_COUNTRY_NOT_ENOUGH_STATES:2 "#v [COUNTRY_FORMATION.GetName]#!形成に必要な[Concept('concept_state_region', '$concept_state_regions$')]#v [COUNTRY_FORMATION.GetNumControlledStates(GetPlayer)]#!州の内#v [COUNTRY_FORMATION.GetNumRequiredStates]#!州しか支配していません：\n[COUNTRY_FORMATION.ListRequiredStates(GetPlayer)]"```

### 問題箇所の英文

```CANNOT_FORM_COUNTRY_NOT_ENOUGH_STATES:2 "We only control #v [COUNTRY_FORMATION.GetNumControlledStates(GetPlayer)]#! out of #v [COUNTRY_FORMATION.GetNumRequiredStates]#! required [Concept('concept_state_region', '$concept_state_regions$')] to form #v [COUNTRY_FORMATION.GetName]#!:\n[COUNTRY_FORMATION.ListRequiredStates(GetPlayer)]"```

### 希望する変更

```CANNOT_FORM_COUNTRY_NOT_ENOUGH_STATES:2 "#v [COUNTRY_FORMATION.GetName]#!形成に必要な[Concept('concept_state_region', '$concept_state_regions$')]#v [COUNTRY_FORMATION.GetNumRequiredStates]#!の内#v [COUNTRY_FORMATION.GetNumControlledStates(GetPlayer)]#!しか支配していません：\n[COUNTRY_FORMATION.ListRequiredStates(GetPlayer)]"```

など

### 変更の理由（概要）

変数が逆になっている

### 変更の理由（詳細）

[COUNTRY_FORMATION.GetNumControlledStates(GetPlayer)]と[COUNTRY_FORMATION.GetNumRequiredStates]の位置が逆だと思われます

### プレイ国家

両シチリア

### ゲームバージョン

1.2.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
#293 での修正ミスですね。ご報告ありがとうございます。
