### ISSUE TITLE
威信：主要な商品生産者の内訳のツールチップ

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#675]
### スクリーンショット

![Victoria 3 Screenshot 2023 04 21 - 23 07 32 32](https://user-images.githubusercontent.com/42710893/233684570-1559bb5f-3c3c-4678-86bc-c309d29bfe18.png)

### 問題のツールチップ

威信：主要な商品生産者マウスオーバー時のツールチップ

### 問題の表現

```GOODS_PRESTIGE_AWARD:0 "[Goods.GetTextIcon][Goods.GetName]の生産者よりの#v $VAL|=+$#! [concept_prestige]#v ##$SPOT|v$#!"```

### 問題箇所の英文

```GOODS_PRESTIGE_AWARD:0 "#v $VAL|=+$#! [concept_prestige] from #v ##$SPOT|v$#! producer of [Goods.GetTextIcon][Goods.GetName]"```

### 希望する変更

```GOODS_PRESTIGE_AWARD:0 "[Goods.GetTextIcon][Goods.GetName]の#v ##$SPOT|v$#!の生産者より[concept_prestige]#v $VAL|=+$#!"```

など

### 変更の理由（概要）

構文ミス

### 変更の理由（詳細）

変数の位置がおかしいため

### プレイ国家

両シチリア

### ゲームバージョン

1.2.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
こちらのISSUEでもって威信の内訳ポップアップの体裁統一をまとめて行いたいと思います

**Comment by matanki-saito** [comment]
変更予想

**Comment by matanki-saito** [comment]
対象キー`PRESTIGE_FROM_`から始まるキー
`[concept_gdp]から#variable $VALUE|+=$#!`　→　`#variable $VALUE|+=$#!（[concept_gdp]）`
`陸軍[concept_power_projection]から#variable $VALUE|+=$#!`　→　`#variable $VALUE|+=$#!（陸軍[concept_power_projection]）`
`海軍[concept_power_projection]から#variable $VALUE|+=$#!`　→　`#variable $VALUE|+=$#!（海軍[concept_power_projection]）`
`$TIER|v$の[concept_country_tier]から#variable $VALUE|+=$#!`　→　`#variable $VALUE|+=$#!（[concept_country_tier] : $TIER|v$）`
`[Concept('concept_subject', '$concept_subjects$')]の[concept_gdp]から#variable $VALUE|+=$#!`　→　`#variable $VALUE|+=$#!（[Concept('concept_subject', '$concept_subjects$')]の[concept_gdp]）`
`[Concept('concept_subject', '$concept_subjects$')]の陸軍[concept_power_projection]から#variable $VALUE|+=$#!`　→　`#variable $VALUE|+=$#!（[Concept('concept_subject', '$concept_subjects$')]の陸軍[concept_power_projection]）`
`[Concept('concept_subject', '$concept_subjects$')]の海軍[concept_power_projection]から#variable $VALUE|+=$#!`　→　`#variable $VALUE|+=$#!（[Concept('concept_subject', '$concept_subjects$')]の海軍[concept_power_projection]）`
`主要な商品生産者である事から#tooltippable #tooltip:[Country.GetTooltipTag],PRESTIGE_FROM_GOODS_LEADERBOARDS_BREAKDOWN #v $VAL|+=$#!#!#!`　→　`#tooltippable #tooltip:[Country.GetTooltipTag],PRESTIGE_FROM_GOODS_LEADERBOARDS_BREAKDOWN #v $VAL|+=$#!#!#!（主要生産国）`

**Comment by inarizushi0309** [comment]
![image](https://user-images.githubusercontent.com/37979626/234311273-d26cbd34-73ab-4afd-af70-48d73de1b5d5.png)
このように数値（理由）となるように修正します。起票ありがとうございました。
