### ISSUE TITLE
オランダ領東インドのディシジョン

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#676]
### スクリーンショット

![20230419024614_1](https://user-images.githubusercontent.com/38329957/233775763-3819996d-0914-4e7f-a544-d8578609aeb9.jpg)

### 問題のあるインターフェイス

オランダ領東インドを属国にしている時のディシジョン

### 問題のテキスト

東インド諸島の政権を拡張しよう。

我々は自国の植民地の臣下による統治の方が相応しい領土を現在東インド諸島に有しています。

東インド諸島の所有物や家臣のすべての管理権を我々の植民地に移譲しよう。

世界中のいずれかの州

### 希望する変更

東インド諸島の統治権を拡大する

我が国は現在、東インド諸島に領土を保有しており、植民地属国による統治の方が適しています。

東インド諸島に属している全ての領土、および属国の統治権を植民地に委譲する。

世界中のすべての州

### 変更の理由（概要）

意味が分からないため

### 変更の理由（詳細）

文章を読んでもどの様な効果があるのか全く分からない。
実際の効果は「オランダ領東インドを属国にしているとき、インドネシア戦略地域に含まれる州を全てオランダ領東インドに割譲する、あるいはインドネシア戦略地域に首都がある属国を、全てオランダ領東インドの属国にする」というものだった。

### ゲームバージョン

1.2.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
