### ISSUE TITLE
【体裁統一】急進派・体制派の増減要因ポップアップ

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#678]
### スクリーンショット

![image](https://user-images.githubusercontent.com/37979626/233820539-f6abdd65-35ca-44ef-b26d-aea117c83293.png)

### 問題のあるインターフェイス

急進派・体制派ポップアップ＞増加数マウスオーバー

### 問題のテキスト

長いので後述

### 希望する変更

長いので後述

### 変更の理由（概要）

数値を見やすくするため

### 変更の理由（詳細）

「○○から数値」と英語版と語順が逆になっていることから、重要な数値の情報が確認しづらくなっている
https://github.com/matanki-saito/vic3jpadvmod/issues/665 と類似

特に
外国[concept_country]による制圧により○○
のところは「外国国による制圧により」と表示されてしまっているので修正必須

### ゲームバージョン

1.2.X

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通り修正しました
