### ISSUE TITLE
【体裁統一】大隊/艦艇合計数のツールチップ

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#679]
### スクリーンショット

![image](https://user-images.githubusercontent.com/37979626/233850349-90aa93d3-29fd-48e0-88bd-a1e699f51fb0.png)
![image](https://user-images.githubusercontent.com/37979626/233850330-4c382b36-fc0a-494f-a026-04f4d20b347f.png)

### 問題のツールチップ

軍事画面陸軍/海軍タブの総大隊数、総艦艇数のツールチップ

### 問題の表現

```[STATE.GetName]の$UNIT_NAME$[Nbsp][GetUnitStrengthHeader( '(int32)$CURRENT$', '(int32)$MAX$', '$ICON$' )]```

### 問題箇所の英文

```[GetUnitStrengthHeader( '(int32)$CURRENT$', '(int32)$MAX$', '$ICON$' )] $UNIT_NAME$ from [STATE.GetName]```

### 希望する変更

```[GetUnitStrengthHeader( '(int32)$CURRENT$', '(int32)$MAX$', '$ICON$' )][Nbsp][STATE.GetName]の$UNIT_NAME$```

### 変更の理由（概要）

数値を見やすくするため

### 変更の理由（詳細）

#573 で日本語として不自然な表現が修正されたが、[場所] [数値]の語順は変更されていないため、起票。
他同様、[数値] [場所]の順にする

### ゲームバージョン

1.2.X

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。
