### ISSUE TITLE
【修正提案】補給艦

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#68]
＜ゲームシステム用語＞

## スクリーンショット（任意）

![20221027103400_1](https://user-images.githubusercontent.com/43299334/198199487-15bb22fb-c514-43df-bfd1-1dcfa9a7cec4.jpg)

## 問題の用語（必須）

補給艦

## 英語版の表現（任意）

Flotilla

## 希望する変更（必須）

小艦隊

## 変更の理由（必須）

誤訳。特に補給艦という意味はないので意訳を試みたものと思われる。
ゲーム的には海軍基地（恐らく）１単位と紐付けられた海軍の最小戦力単位。
艦名もついているようなので１軍艦の可能性もあるが、production methodの内容などから旗艦１隻に駆逐艦等の補助艦が随伴しているものと解釈して上記の訳としている。

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1035063665986125876
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by Zousuikakka** [comment]
艦艇で修正
