### ISSUE TITLE
平和的な意図

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#680]
### スクリーンショット

![Victoria 3 Screenshot 2023 04 24 - 20 19 35 67](https://user-images.githubusercontent.com/42710893/234011505-6a353142-ac2c-4c04-b92f-478770ea0581.png)

### 問題部分

選択肢

### 問題のイベントタイトル

平和的な意図

### 問題のイベント選択肢

我々の案内人に慣れるような人物はいるのか？

### 希望する変更（修正部分のみ）

我々の案内人になれるような人物はいるのか？

### 変更の理由（概要）

誤字の修正

### プレイ国家

イタリア

### ゲームバージョン

1.2.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。
