### ISSUE TITLE
イタリア統一運動

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#681]
### スクリーンショット

![Victoria 3 Screenshot 2023 04 24 - 22 23 32 01](https://user-images.githubusercontent.com/42710893/234013866-6040a27c-8465-4ef8-ae3d-2782b8685e26.png)

### 問題部分

本文

### 問題のイベントタイトル

イタリア統一運動

### 問題のイベント本文（抜粋可）

…そう、征服したのも、これから整復するのも諸君らなのだ。…

### 希望する変更（修正部分のみ）

…そう、征服したのも、これから征服するのも諸君らなのだ。…

### 変更の理由（概要）

誤字の修正

### プレイ国家

イタリア

### ゲームバージョン

1.2.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
報告ありがとうございます。提案通り修正しました。
