### ISSUE TITLE
Acceptanceが訳されていない

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#682]
### スクリーンショット

![20230425151107_1](https://user-images.githubusercontent.com/38329957/234192566-e8f48c8a-c09a-4e28-902c-36d4ec330ee8.jpg)

### 問題の用語

Acceptance

### 英語版の表現

Acceptance

### 希望する変更

受容

### 変更の理由（概要）

訳されていない

### ゲームバージョン

1.2.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
STATUS_TITLEにあるAcceptanceを受容状況で修正いたしました。完了したためCloseいたします
