### ISSUE TITLE
【体裁統一】インフラ収支内訳

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#683]
### スクリーンショット

![image](https://user-images.githubusercontent.com/37979626/234890959-1cda4f8d-4651-4945-9bbf-b905512c81c8.png)
![image](https://user-images.githubusercontent.com/37979626/234910173-c62144d3-00a2-4d44-b27c-1382fc268b9a.png)

### 問題のあるインターフェイス

州画面＞インフラマウスオーバー

### 問題のテキスト

```[BUILDING.GetName]による#v $VALUE|0-$#!```
```[Concept('concept_pop', '$concept_pops$')]由来の$VALUE|+=1$\n$BREAKDOWN$[ConcatIfNeitherEmpty('\n','$CAP_BREAKDOWN$')]```
```[concept_state]由来の$VALUE|+=1$\n$BREAKDOWN$```

### 希望する変更

```#v $VALUE|0-$#! ([BUILDING.GetName])```
```$VALUE|+=1$ ([Concept('concept_pop', '$concept_pops$')])\n$BREAKDOWN$[ConcatIfNeitherEmpty('\n','$CAP_BREAKDOWN$')]```
```$VALUE|+=1$ ([concept_state])\n$BREAKDOWN$```

### 変更の理由（概要）

数値を見やすくするため

### 変更の理由（詳細）

「○○から数値」と英語版と語順が逆になっていることから、重要な数値の情報が確認しづらくなっている
https://github.com/matanki-saito/vic3jpadvmod/issues/665 と類似

### ゲームバージョン

1.2.X

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通り修正しました
