### ISSUE TITLE
【誤訳】清ジャーナル「脆い団結」条件

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#684]
### スクリーンショット

![image](https://user-images.githubusercontent.com/37979626/235311493-68e96258-1d49-4aef-b19b-9e1925706e4b.png)

### 問題のツールチップ

ジャーナル「脆い団結」条件

### 問題の表現

- #BOLD 根絶君主制#![concept_journal_entry]を終える

### 問題箇所の英文

- Finishing the #BOLD Stamp Out Monarchism#! [concept_journal_entry]

### 希望する変更

- #BOLD 君主主義の廃絶#![concept_journal_entry]を終える

### 変更の理由（概要）

誤訳

### プレイ国家

清

### ゲームバージョン

1.2.X

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
ご指摘のとおりに修正をいたしました
