### ISSUE TITLE
貿易ルート管理画面

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#685]
### スクリーンショット

![image](https://user-images.githubusercontent.com/37979626/235340073-5d52f8e6-808b-4f08-8f40-c7eec63e18d6.png)
![image](https://user-images.githubusercontent.com/37979626/235340097-88afed9d-56f3-4193-b256-c5b58c17dd6e.png)

### 問題のあるインターフェイス

市場画面＞貿易ルートタブ

### 問題のテキスト

【フィルターボタン名】
所有者でフィルター

商品で
国で
自分の物のみ

【フィルター名】
[全て / あなたの]ルート[商品ごとにグループ化 / 、国ごとにグループ化]

【グループ名表記】
```#header [Country.GetNameNoFormatting]#! （[Country.GetNumTradeRoutesOnMarket(Market.Self)|v] [SelectLocalization(EqualTo_int32(Country.GetNumTradeRoutesOnMarket(Market.Self), '(int32)1'), 'route', 'routes')]）```
```([MarketGoods.GetNumPlayerOwnedTradeRoutes|v] [GetPlayer.GetAdjectiveNoFormatting] [SelectLocalization(EqualTo_int32(MarketGoods.GetNumPlayerOwnedTradeRoutes, '(int32)1'), 'ルート', '複数ルート')])```

```[MarketGoods.GetMarket.GetOwner.GetName] ([MarketGoods.GetNumOthersOwnedTradeRoutes]) に繋がる他国の貿易ルート:```

### 希望する変更

【フィルターボタン名】
所有国でフィルター

商品ごと
国ごと
自国のみ

【フィルター名】
[全ての / 自国の]ルート[、商品ごとにグループ化 / 、国ごとにグループ化]

【グループ名表記】
```#header [Country.GetNameNoFormatting]#! （[Country.GetNumTradeRoutesOnMarket(Market.Self)|v] [SelectLocalization(EqualTo_int32(Country.GetNumTradeRoutesOnMarket(Market.Self), '(int32)1'), '本', '本')]）```
```(内[GetPlayer.GetAdjectiveNoFormatting]による[SelectLocalization(EqualTo_int32(MarketGoods.GetNumPlayerOwnedTradeRoutes, '(int32)1'), 'ルート', 'ルート')] [MarketGoods.GetNumPlayerOwnedTradeRoutes|v])```

```[MarketGoods.GetMarket.GetOwner.GetName]に繋がる他国の貿易ルート ([MarketGoods.GetNumOthersOwnedTradeRoutes]) :```

### 変更の理由（概要）

日本語として不自然

### ゲームバージョン

1.2.X

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
「内」の部分を下記のように変更して修正いたしました。
```([GetPlayer.GetAdjectiveNoFormatting]の[SelectLocalization(EqualTo_int32(MarketGoods.GetNumPlayerOwnedTradeRoutes, '(int32)1'), '貿易路', '貿易路')]：[MarketGoods.GetNumPlayerOwnedTradeRoutes|v])```
