### ISSUE TITLE
【誤訳】ヴィキペディアの検索ボックス

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#686]
### スクリーンショット

![image](https://user-images.githubusercontent.com/37979626/235346657-e2c35be7-2ec9-4967-bb12-1b9d768f0bac.png)

### 問題のツールチップ

ヴィキペディア＞検索ボックスマウスオーバー

### 問題の表現

```#T $SEARCH_ENCYCLOPEDIA$\n#!は、「[EncyclopediaPage.GetTitle]」で入力したテキストに合致する見出しを持つエントリーを見つけました```

### 問題箇所の英文

```#T $SEARCH_ENCYCLOPEDIA$\n#!Find entries in '[EncyclopediaPage.GetTitle]' whose headings match the text entered```

### 希望する変更

```#T $SEARCH_ENCYCLOPEDIA$\n#!「[EncyclopediaPage.GetTitle]」で、入力されたテキストと見出しが一致するエントリを検索します```

### 変更の理由（概要）

誤訳

### 変更の理由（詳細）

検索システムの説明に関する文章なのに「」内のワードを探したとなるのはおかしい
なお、変更案はCK3のものを引用

### ゲームバージョン

1.2.X

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通り修正しました
