### ISSUE TITLE
情報の年齢

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#688]
### スクリーンショット

![20230429155009_1](https://user-images.githubusercontent.com/38329957/235347459-da1beead-280c-40fc-ad1e-3007a2bd15de.jpg)

### 問題部分

タイトル, 本文

### 問題のイベントタイトル

情報の年齢

### 問題のイベント本文（抜粋可）

「私には存在しない権利がある」不安に駆られた市民が```[SCOPE.GetRootScope.GetCountry.GetCustom('generic_newspaper_type')]```へ駆け込んだ。「こんなことは前代未聞だ！情報精度の欠如によって何が起きるか... 考えてみて欲しい。自分の名前が間違ったリスト、間違ったイデオロギー、間違った経歴に載せられるだけで、関与していない犯罪の罪を問われることになるかもしれないのだ」

### 問題のイベント選択肢

なし

### 希望する変更（修正部分のみ）

情報化時代

不安に感じた市民が「私には存在しない権利がある！」と```[SCOPE.GetRootScope.GetCountry.GetCustom('generic_newspaper_type')]```紙に寄せている。

### 変更の理由（概要）

誤訳修正

### プレイ国家

ロシア

### ゲームバージョン

1.2.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
