### ISSUE TITLE
大量消費の街

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#689]
### スクリーンショット

![20230429213030_1](https://user-images.githubusercontent.com/38329957/235350233-951d51ae-668d-494a-b926-4ec5f8683928.jpg)

### 問題部分

本文

### 問題のイベントタイトル

大量消費の街

### 問題のイベント本文（抜粋可）

```[SCOPE.sState('urbanization_state').GetName]```の最有力メンバーが属する社交界が、近頃建設された都会的で豪華な建物で豪勢なパーティーを催しているようだ。

### 問題のイベント選択肢

なし

### 希望する変更（修正部分のみ）

```[SCOPE.sState('urbanization_state').GetName]```で最高位の著名人たちが属する社交界が、近頃建設された都会的で豪華な建物で豪勢なパーティーを催しているようだ。

イベント効果：政府体制支持寄りになります　→　体制派寄りになります

イベント効果：豪奢なる政党　→　豪勢なパーティー

### 変更の理由（概要）

誤訳修正

### プレイ国家

ロシア

### ゲームバージョン

1.2.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
