### ISSUE TITLE
【修正提案】海軍の侵略

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#69]
＜ゲームシステム用語＞

## スクリーンショット（任意）

![20221027070750_1](https://user-images.githubusercontent.com/43299334/198200563-a0bb9198-bd63-4cb2-8765-761e1045bcd3.jpg)

## 問題の用語（必須）

海軍の侵略

## 英語版の表現（任意）

Naval Invasion

## 希望する変更（必須）

上陸作戦

## 変更の理由（必須）

実際のゲームメカニズムと異なっているため

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1035064881709318144
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by Zousuikakka** [comment]
上陸作戦で修正
