### ISSUE TITLE
施設建設タブのツールチップ

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#690]
### スクリーンショット

![Victoria 3 Screenshot 2023 05 04 - 16 13 00 56](https://user-images.githubusercontent.com/42710893/236157769-e01f6352-1b90-4e95-8bfc-a956cb88a67c.png)

### 問題のツールチップ

施設建設タブのツールチップ

### 問題の表現

```CONSTRUCTION_QUEUE_ITEM_VALID:5 "#header [State.GetName]の[Building.GetName]拡張中#!\n[AddTextIf( ConstructionQueueElement.IsCurrentlyUnderConstruction, '完成まで残り$WEEKS|v$週\n')]$TOOLTIP_DELIMITER$\n#v $PROGRESS|0$#!/#v $REQUIRED|0$#! [concept_construction] 進行度 (#v $PERCENT_COMPLETE|%$#!)\n#v [ConstructionQueueElement.GetBaseConstructionSpeed|2]#![Building.GetOwner.GetName]で提供される$concept_construction$の結果#v #tooltippable #tooltip:[ConstructionQueueElement.GetTooltipTag],CONSTRUCTION_QUEUE_SPEED_TOOLTIP $SPEED$#!#!#! 週あたりの進捗が[SelectLocalization( NotEqualTo_CFixedPoint(State.GetConstructionEfficiency, '(CFixedPoint)0'), 'CONSTRUCTION_QUEUE_STATE_CONSTRUCTION_EFFICIENCY_LINE_BREAK', '')]"```

### 問題箇所の英文

```CONSTRUCTION_QUEUE_ITEM_VALID:5 "#header Expanding [Building.GetName] in [State.GetName]#!\n[AddTextIf( ConstructionQueueElement.IsCurrentlyUnderConstruction, '$WEEKS|v$ week(s) until complete\n')]$TOOLTIP_DELIMITER$\n#v $PROGRESS|0$#!/#v $REQUIRED|0$#! [concept_construction] progress (#v $PERCENT_COMPLETE|%$#!)\n#v [ConstructionQueueElement.GetBaseConstructionSpeed|2]#! $concept_construction$ provided by [Building.GetOwner.GetName] results in a total of #v #tooltippable #tooltip:[ConstructionQueueElement.GetTooltipTag],CONSTRUCTION_QUEUE_SPEED_TOOLTIP $SPEED$#!#!#! progress each week[SelectLocalization( NotEqualTo_CFixedPoint(State.GetConstructionEfficiency, '(CFixedPoint)0'), 'CONSTRUCTION_QUEUE_STATE_CONSTRUCTION_EFFICIENCY_LINE_BREAK', '')]"```

### 希望する変更

進捗が　で止まっており不自然なので正しい表示に

### 変更の理由（概要）

日本語として不自然なため

### 変更の理由（詳細）

進捗が　で止まっており表現が不自然
（バグかもしれないですが一応ご報告します）

### プレイ国家

ペルシア

### ゲームバージョン

1.2.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by Zousuikakka** [comment]
該当部分を
「(国名)が建設(数値1)割り振っているため、週ごとの進捗は(数値2)となります」
と表示されるよう修正しました
