### ISSUE TITLE
ヴィキペディアの準主流派の説明文

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#691]
### スクリーンショット

![Victoria 3 Screenshot 2023 05 05 - 02 09 48 90](https://user-images.githubusercontent.com/42710893/236302862-ea1bc3e9-7a11-4bdb-a85b-1a53bf3b88d8.png)

### 問題のあるインターフェイス

ヴィキペディアの準主流派の説明文

### 問題のテキスト

…主流派である場合よりも硬貨が小さくなります。

### 希望する変更

…主流派である場合よりも効果が小さくなります。

### 変更の理由（概要）

誤字の修正

### ゲームバージョン

1.2.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
ご指摘の通り、誤字を修正しました。
