### ISSUE TITLE
徴兵開始フィード

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#692]
### スクリーンショット

![Victoria 3 Screenshot 2023 05 06 - 23 44 04 06](https://user-images.githubusercontent.com/42710893/236633277-b8bee1bb-81db-4ea7-a345-6091d811ad57.png)

### 問題のあるインターフェイス

徴兵開始フィードの文章

### 問題のテキスト

```notification_country_conscription_desc:0 "我が国の[SelectLocalization( SCOPE.sDiplomaticPlay('diplomatic_play').AreOnSameSide( GetPlayer , SCOPE.sCountry('actor') ), '同盟', '敵' )] [SCOPE.sCountry('actor').GetName]が[Concept('concept_conscription_center', '$concept_conscription_centers$')]の始動を開始しました。"```

### 希望する変更

```notification_country_conscription_desc:0 "我が国の[SelectLocalization( SCOPE.sDiplomaticPlay('diplomatic_play').AreOnSameSide( GetPlayer , SCOPE.sCountry('actor') ), '同盟国', '敵' )] [SCOPE.sCountry('actor').GetName]が[Concept('concept_conscription_center', '$concept_conscription_centers$')]の始動を開始しました。"```

### 変更の理由（概要）

日本語として不自然なため

### 変更の理由（詳細）

同盟国のほうが自然だと感じたため

動員開始時のフィードnotification_country_mobilization_desc:1にも同様の部分があり、修正が必要と思われます。

### ゲームバージョン

1.2.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
ご指摘の部分の「始動を開始しました。」を「始動しました」に一部変更を入れて修正をいたしました。よろしくお願いします。
