### ISSUE TITLE
死亡数

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#693]
### スクリーンショット

![Victoria 3 Screenshot 2023 05 06 - 18 51 15 57](https://user-images.githubusercontent.com/42710893/236660383-f6f2c9f9-171a-4700-ab79-ea05f144284e.png)

### 問題の用語

死亡数

### 英語版の表現

Dead

### 希望する変更

死者数

### 変更の理由（概要）

日本語として不自然なため

### 変更の理由（詳細）

死者数のほうが日本語としてしっくり来ると思います。

また、死亡数の説明文について、現状、
concept_dead_desc:2 "[concept_battle]や[concept_attrition]によって$concept_dead$になった[concept_casualties]です。
となっていますが、これも不自然な表現なので

concept_dead_desc:2 "[concept_battle]や[concept_attrition]による[concept_casualties]のうち$concept_dead$の合計です。
等にしたほうが自然かと思います。

### ゲームバージョン

1.2.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
ありがとうございます。ご指摘の2箇所について修正完了したためCloseいたします。
