### ISSUE TITLE
【誤訳】アフリカの国家Benin

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#694]
### スクリーンショット

作業所での発見のため、スクショなし

### 問題の固有名詞：希望する変更

ベナン：ベニン

### 変更の理由（概要）

誤訳

### 変更の理由（詳細）

現代のアフリカにあるベナン共和国はRépublique du Bénin（フランス語）であるが、この時代におけるBeninとは直接的なつながりはなく、Benin Empire「ベニン王国」が一般的名称である。

### ゲームバージョン

1.2.X

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。
