### ISSUE TITLE
将軍選択時のツールチップ

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#695]
### スクリーンショット

![Victoria 3 Screenshot 2023 05 07 - 16 21 18 81](https://user-images.githubusercontent.com/42710893/236674043-803f9087-291f-4836-99a5-4c6d7cb6081f.png)

### 問題のツールチップ

将軍選択時のツールチップ

### 問題の表現

```COMMANDER_CURRENT_ORDERS:0 "現在地: [Character.GetLocationFormatted]"```

### 問題箇所の英文

```COMMANDER_CURRENT_ORDERS:0 "Location: [Character.GetLocationFormatted]"```

### 希望する変更

最後に]が入ってしまっているので除去したい

### 変更の理由（概要）

変数の不具合？

### 変更の理由（詳細）

最後に]が入ってしまっている

### プレイ国家

ペルシア

### ゲームバージョン

1.2.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
英語では問題なく表示されるものでしょうか？確認していただけると幸いです。

**Comment by wakkunteitoku** [comment]
![Victoria 3 Screenshot 2023 05 07 - 21 35 08 53](https://user-images.githubusercontent.com/42710893/236678083-341d590b-233a-4832-a0b6-df3e9fedefeb.png)

**Comment by wakkunteitoku** [comment]
英語にしてみましたが]は表示されませんでした

**Comment by mochi115** [comment]
```
DATA_CHARACTER_COMMANDER_LOCATION_TOOLTIP:0 "\n\n本拠地の司令本部 : [Character.GetHomeHQ.GetNameNoFlag|v][AddTextIf(And(Character.GetHomeHQ.IsValid,Not(Character.IsOffer)),'\n現在地:')][AddTextIf(And(Character.GetHomeHQ.IsValid,Not(Character.IsOffer)),Character.GetLocationFormatted)]]"
```
おそらく原因はこれです。余計な]が入っています。

**Comment by matanki-saito** [comment]
ご指摘のとおりに変数の修正を行いました。ありがとうございます。
