### ISSUE TITLE
和平交渉画面のツールチップ

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#696]
### スクリーンショット

![Victoria 3 Screenshot 2023 05 07 - 19 40 26 15](https://user-images.githubusercontent.com/42710893/236674536-962de015-0830-44bc-ac3e-ffc677abe923.png)

### 問題のツールチップ

和平交渉タブ：死亡数マウスオーバー時のツールチップ

### 問題の表現

```WAR_PANEL_PARTICIPANT_DEAD_TOOLTIP:1 "#header [concept_dead]#!\n#v [War.GetName]戦争#!で[WarParticipant.GetNumDead|K-]名の[WarParticipant.GetCountry.GetAdjectiveNoFormatting]が死亡:\n$TAB$[concept_battle]での[WarParticipant.GetNumDeadFromBattle|-]\n$TAB$[concept_attrition]による[WarParticipant.GetNumDeadFromAttrition|-]"```

### 問題箇所の英文

```WAR_PANEL_PARTICIPANT_DEAD_TOOLTIP:1 "#header [concept_dead]#!\n[WarParticipant.GetNumDead|K-] [WarParticipant.GetCountry.GetAdjectiveNoFormatting] have died in the #v [War.GetName] War#!:\n$TAB$[WarParticipant.GetNumDeadFromBattle|-] in [concept_battle]\n$TAB$[WarParticipant.GetNumDeadFromAttrition|-] due to [concept_attrition]"```

### 希望する変更

```WAR_PANEL_PARTICIPANT_DEAD_TOOLTIP:1 "#header [concept_dead]#!\n#v [War.GetName]戦争#!で[WarParticipant.GetNumDead|K-]名の[WarParticipant.GetCountry.GetAdjectiveNoFormatting]兵が死亡:\n$TAB$[concept_battle]により[WarParticipant.GetNumDeadFromBattle|-]\n$TAB$[concept_attrition]により[WarParticipant.GetNumDeadFromAttrition|-]"```

※負傷者数マウスオーバー時のツールチップWAR_PANEL_PARTICIPANT_WOUNDED_TOOLTIP:1も同様の修正が必要

### 変更の理由（概要）

日本語として不自然なため

### 変更の理由（詳細）

自然な表現に修正

### プレイ国家

ペルシア

### ゲームバージョン

1.2.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
WAR_PANEL_PARTICIPANT_DEAD_TOOLTIPとWAR_PANEL_PARTICIPANT_WOUNDED_TOOLTIPの２つをご指摘のとおりに修正いたしました。ありがとうございました。
