### ISSUE TITLE
手動吹きガラス

### ISSUE THREAD

**Issue by mochi115** [matanki-saito/vic3jpadvmod#697]
### スクリーンショット

![20230427153800_1](https://user-images.githubusercontent.com/117048815/236677551-4576a5a4-d796-4ba6-91ed-c08bf6adacc5.jpg)

### 問題の用語

手動吹きガラス

### 希望する変更

手吹きガラス

### 変更の理由（概要）

より自然な語に

### ゲームバージョン

1.2.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
ご指摘のとおりに修正しました。ありがとうございます。
