### ISSUE TITLE
生活水準の最低予想値です

### ISSUE THREAD

**Issue by mochi115** [matanki-saito/vic3jpadvmod#698]
### スクリーンショット

![20230427115608_1](https://user-images.githubusercontent.com/117048815/236677893-5311aea4-616c-4a9b-a3cf-475e59ae1a6b.jpg)

### 問題の用語

生活水準の最低予想値です

### 希望する変更

生活水準の最低期待値

### 変更の理由（概要）

誤訳の修正

### ゲームバージョン

1.2.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
#488 でexpectedを許容としたのに合わせて`許容生活水準` と修正させていただきました。
