### ISSUE TITLE
州は編入済中です

### ISSUE THREAD

**Issue by mochi115** [matanki-saito/vic3jpadvmod#699]
### スクリーンショット

![20230427115608_1](https://user-images.githubusercontent.com/117048815/236678045-88a76f85-5553-4168-9118-690f7112e474.jpg)

### 問題の用語

州は編入済中です、編入済が～%まで

### 希望する変更

州は編入中です、編入が～%まで

### 変更の理由（概要）

不自然な語を修正

### ゲームバージョン

1.2.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
起票内容を踏まえ、該当箇所を以下のように修正しました。起票ありがとうございました。
```#header 州は[Concept('concept_incorporated_state', '編入')]中です#!\n$TOOLTIP_DELIMITER$\n残り時間: [State.GetIncorporationTimeLeft]\n\n[State.GetIncorporationTimeDesc]\n\n[State.GetIncorporationPartialEffectsDesc]\n$TOOLTIP_DELIMITER$\n[concept_unincorporated_state_desc]```
```[Concept('concept_incorporated_state', '編入')]が[State.GetIncorporationProgress|v%0]まで進んでおり、[State.GetName]は次の効果の対象となります:\n[Modifier.GetDesc]```
