### ISSUE TITLE
【修正提案】ロウ（法律）

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#70]
＜ゲームシステム用語＞

## スクリーンショット（任意）

![20221027144328_1](https://user-images.githubusercontent.com/43299334/198201578-e1b3bbfe-cd49-4ebf-bbf9-cebb28544e98.jpg)

## 問題の用語（必須）

ロウ

## 英語版の表現（任意）

Law

## 希望する変更（必須）

法律

## 変更の理由（必須）

なぜか音写されている。ちなみにLawsは法律と訳されている。

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1035067021349638194
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by Zousuikakka** [comment]
法律で修正
