### ISSUE TITLE
史実の政治家と将軍の人名

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#700]
### 問題の固有名詞：希望する変更

フェアガス：ファーガス
スヴェトザール：スヴェトザル
マナーハイム：マンネルヘイム
ジョルジュ・エルネス：ジョルジュ・エルネスト
ベティ：ビーティー
フランス：フレンチ
カラーギス：カレルギス
ド・リイク：デ・レイク
ダーヴィド・フェレンツ：フランス・ダヴィト
ド・コック：デ・コック
ミシェル：ミヒールス

シャー：シェール

クルーガー：クリュヘル

ジュアレズ：フアレス
アルトゥーロ：アルトゥロ
プラット：プラト
ポリフィリオ：ポルフィリオ
ザラゴザ：サラゴサ

ジェスプ：ジェサップ
ブチャナン：ブキャナン
チャフィー：チャーフィー
ウリッセス：ユリシーズ

### 変更の理由（概要）

一般的ではない表記であるため。

### ゲームバージョン

1.2.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
