### ISSUE TITLE
行政府の方式

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#701]
### スクリーンショット

![20230506032419_1](https://github.com/matanki-saito/vic3jpadvmod/assets/38329957/aee52e87-7601-4675-9be8-f71cb8647b7d)

### 問題の用語

プロフェッショナリズム　世襲制の官僚　職業的官僚

### 英語版の表現

Professionalism　Hereditary Bureaucrats　Professional Bureaucrats

### 希望する変更

職業化　世襲官僚　職業官僚

### 変更の理由（概要）

意味が分かりにくいため。

### ゲームバージョン

1.2.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
