### ISSUE TITLE
負傷者数の解説文

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#702]
### スクリーンショット

![20230508153737_1](https://github.com/matanki-saito/vic3jpadvmod/assets/38329957/c446fe28-7d6a-47b0-91fb-0e9f5258bb52)

### 問題のツールチップ

戦闘時の負傷者数のマウスオーバーでの解説文

### 問題の表現

戦闘または損耗によって単に負傷者数の死傷者です。負傷者数 死傷者数の中には、しばらくすると回復して現役に戻るものもあれば、あなたの国にある他のPOP の被扶養者として終わってしまうものもあります。

### 問題箇所の英文

```[concept_casualties]``` that are merely ```$concept_wounded$``` in ```[concept_battle]``` or due to ```[concept_attrition]```. Some ```$concept_wounded$``` ```$concept_casualties$``` recover and return to active service after some time, while others end up as ```[concept_dependents]``` of other ```[Concept('concept_pop','$concept_pops$')]``` in your ```[concept_country]```.

### 希望する変更

戦闘または消耗による負傷しただけの死傷者です。 負傷した死傷者の中には、しばらくすると回復して現役に戻る者もいれば、自国のPOPの被扶養者として終わってしまう者もいます。

### 変更の理由（概要）

意味が分かりにくいため。

### プレイ国家

日本

### ゲームバージョン

1.2.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
[concept_battle]または[concept_attrition]に遭ったものの、死を免れた[Concept('concept_casualties','負傷者')]の数です。負傷者の一部はしばらくすると回復して現役に復帰しますが、自[concept_country]の[Concept('concept_pop', '$concept_pop$')] の[concept_dependents]として終わってしまう者もいます。

で修正しました
