### ISSUE TITLE
ベトナム人の姓名

### ISSUE THREAD

**Issue by awak1180** [matanki-saito/vic3jpadvmod#705]
### 問題の固有名詞：希望する変更

トン・ハット：トン・タット
トロン・ヒエ：チョン・ヒエプ
ミエン・トリン：ミエン・チン
ンゴ・ディン：ゴ・ディン
トルオン・ミン：チュオン・ミン
ヌグーイェン：グエン
トルオング：チュオン
トラン：チャン

### 変更の理由（概要）

グエン(阮)・ゴ(呉)など、日本語で定着している表記と異なるため。

### 変更の理由（詳細）

また、trはおおむねチャ行、thはタ行に近い発音のため、それに即した表記に修正する　[参考](https://ja.wikipedia.org/wiki/%E3%83%99%E3%83%88%E3%83%8A%E3%83%A0%E8%AA%9E#%E9%9F%B3%E9%9F%BB)

### ゲームバージョン

1.2.X

### MOD有無

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
