### ISSUE TITLE
チベット人の姓名

### ISSUE THREAD

**Issue by awak1180** [matanki-saito/vic3jpadvmod#706]
### 問題の固有名詞：希望する変更

ザーサ：ツァサ
ワンギアル：ワンギャル
ラングシャール：ルンシャル
リンポシェ：リンポチェ
シェフェル：チョペル
シャカブパ：シャカパ
ツサロン：ツァロン
チャンバ：チャンパ
トリモン：ティモン
ペノール：ペノル
ゲンダン：ゲンドゥン
ジャンフェル：ジャムペル
ノルブー：ノルプ
ミファム：ミパム
アンドルーク：アンドゥク
ラークパ：ラクパ
ファンツォグ：プンツォク
ラール：ラル
ンガポイ：ンガプー

### 変更の理由（概要）

日本語で定着している、または用例のある表記と異なるため。

### 変更の理由（詳細）

また、チベット語のアルファベット表記は実際の発音と異なることがあるため、実際の発音に即した表記に修正する　[参考](https://ja.wikipedia.org/wiki/%E3%83%81%E3%83%99%E3%83%83%E3%83%88%E8%AA%9E%E3%81%AE%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A%E8%A1%A8%E8%A8%98%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6)

### ゲームバージョン

1.2.X

### MOD有無

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
