### ISSUE TITLE
ヴィキペディアの文章が多数未翻訳になっている

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#707]
### スクリーンショット

![20230520174849_1](https://github.com/matanki-saito/vic3jpadvmod/assets/38329957/9ba61de5-d43b-49ee-b173-81976ae9b86a)
![20230520174915_1](https://github.com/matanki-saito/vic3jpadvmod/assets/38329957/a5c788d0-dc40-4f12-859d-98d0fbe7798b)
![20230520174934_1](https://github.com/matanki-saito/vic3jpadvmod/assets/38329957/c024b1eb-f4c8-4743-a4fc-796247e0b591)
![20230520174944_1](https://github.com/matanki-saito/vic3jpadvmod/assets/38329957/b74e80f0-9263-45db-bd99-28ce42ccffa0)
![20230520174955_1](https://github.com/matanki-saito/vic3jpadvmod/assets/38329957/81c179df-5e2a-4b32-8f8d-47e08c11dbf5)

### 問題の用語

Railway・Port・Soldiers・Officers・Economic System・Home Affairs・Peasants

### 英語版の表現

Railway・Port・Soldiers・Officers・Economic System・Home Affairs・Peasants

### 希望する変更

鉄道・港・兵士・将校・経済制度・治安維持・農家

### 変更の理由（概要）

未翻訳

### 変更の理由（詳細）

他にも残っている可能性あり。
初心者が混乱すると思われる深刻な問題であるため、できれば一括で全部直したい。

### ゲームバージョン

1.2.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
確認できた分だけ修正しました。
未修正のものを確認し次第、随時修正します。
