### ISSUE TITLE
Stratocratic

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#708]
### スクリーンショット

![20230523002132_1](https://github.com/matanki-saito/vic3jpadvmod/assets/38329957/21da97f5-94c2-4370-8cfe-cedded327811)

### 問題の固有名詞：希望する変更

権威主義：階級主義

### 変更の理由（概要）

意味が分かりにくいため。

### 変更の理由（詳細）

以前の訳では軍政主義と訳されていたが、軍事とは一切関係のない主義である（実際のStratocraticは軍政という意味が強い単語だが、ゲーム内ではそのニュアンスが全くない）ため、より適していると思われる訳として権威主義にするよう提案して、その様に修正されたが1.3から新たにAuthoritarianが追加されたため、代わりにこちらの訳語を再度変えることを提案した。

### ゲームバージョン

1.3.X

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
身分主義　→　階級主義に変更
アイコンが階層に分かれている様に見える点と、Stratocraticという（本来なら）軍事的ニュアンスが含まれる単語の利用をしており、なおかつ「階級主義」に該当する英語はないと考えられ、より適訳である思えるため。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
