### ISSUE TITLE
法律と方式の「入植」

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#709]
### スクリーンショット

![20230523001737_1](https://github.com/matanki-saito/vic3jpadvmod/assets/38329957/4dc83d4e-e2b5-4c02-b9da-829ab3d2656c)
![20230523001746_1](https://github.com/matanki-saito/vic3jpadvmod/assets/38329957/d8e69504-6ca2-4b29-8af0-5363958f54fe)

### 問題の用語

入植

### 英語版の表現

Homesteading

### 希望する変更

自営農地

### 変更の理由（概要）

誤訳

### 変更の理由（詳細）

アメリカのホームステッド法が元ネタと思われるため、その日本語訳の自営農地にしたい。

### ゲームバージョン

1.3.X

### MOD有無

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
議論の結果「自営農」に決定し、修正を完了しました。
