### ISSUE TITLE
【修正提案】製法

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#71]
＜ゲームシステム用語＞

## スクリーンショット（任意）

![20221027145601_1](https://user-images.githubusercontent.com/43299334/198203237-83687da9-61ff-4f48-91d1-3f23e83ea7c3.jpg)

## 問題の用語（必須）

製法

## 英語版の表現（任意）

Production Method

## 希望する変更（必須）

生産方式、仕様など

## 変更の理由（必須）

画像のように、製造業以外の施設にも適用されるため。
Production Methodの定訳としては生産方式だが、どちらにしてもユニットの性質などの話になってくると違和感が強いため、別の案としてとりあえず「仕様」を挙げておく。

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1035069861803589652
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by Zousuikakka** [comment]
方式で修正
