### ISSUE TITLE
チェックサムに続く「修正済」

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#710]
### スクリーンショット

![20230601220714_1](https://github.com/matanki-saito/vic3jpadvmod/assets/42687608/de834281-a891-4cf9-9de4-1b91cab3bfd7)
![20230601220802_1](https://github.com/matanki-saito/vic3jpadvmod/assets/42687608/d3ea383d-7d67-42ea-9b1a-fc4ea116287e)

### 問題のあるインターフェイス

タイトル画面、メニュー画面

### 問題のテキスト

修正済

### 希望する変更

MOD有効

### 変更の理由（概要）

実際のゲームメカニズムを正確に反映していないため

### 変更の理由（詳細）

原文はModifiedで、これは「MODによりチェックサムが変更されている」ことを表す。
バニラのファイルを直接修正した場合も同じ表示になるが、発生頻度は低い。
変更案を「MOD有効」としたのはランチャーの表記と統一したため。

### ゲームバージョン

1.3.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
変更案の通り修正しました。
