### ISSUE TITLE
現在の状況の「決断」

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#711]
### スクリーンショット

![20230602084603_1](https://github.com/matanki-saito/vic3jpadvmod/assets/42687608/861ca351-5a6d-4580-aade-6816ca22fb00)

### 問題のあるインターフェイス

現在の状況

### 問題のテキスト

利用可能な決断

### 希望する変更

利用可能なディシジョン

### 変更の理由（概要）

用語を統一するため

### 変更の理由（詳細）

Issue #154 でDecisionの訳語は「ディシジョン」に確定している。

### ゲームバージョン

1.3.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
「ディシジョンが利用可能」に修正しました。
