### ISSUE TITLE
技術家政治

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#712]
### スクリーンショット

![20230602100407_1](https://github.com/matanki-saito/vic3jpadvmod/assets/42687608/cd712e20-276c-4106-b093-59d1c080be06)

### 問題の用語

技術家政治

### 英語版の表現

Technocracy

### 希望する変更

テクノクラシー

### 変更の理由（概要）

日本語では一般的でない表記であるため

### 変更の理由（詳細）

Technocracyの訳語として「技術家政治」や「技術家主義」といった日本語が存在するので誤訳ではありませんが、「テクノクラシー」とカタカナ表記する方が一般的ではないでしょうか。
「レッセフェール」を「自由放任主義」と翻訳していないのと同じ理由でカタカナ表記を提案します。

### ゲームバージョン

1.3.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
最終的に投票を実施した結果、テクノクラシーに修正することに決定しました。
