### ISSUE TITLE
イベントのサブタイトルが正しく表示されていない

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#713]
### スクリーンショット

![20230602111826_1](https://github.com/matanki-saito/vic3jpadvmod/assets/42687608/12a840ea-7439-41d4-82e1-aff7023cc334)

### 問題部分

タイトル

### 問題のイベントタイトル

```GetPlayer.GetLawBeingEnacted.GetName]の制定の前進 イベント```

### 希望する変更（修正部分のみ）

正しく表示されていない部分を修正し、末尾の「イベント」の前にある空白を削除する。

### 変更の理由（概要）

翻訳時に発生した不具合

### 変更の理由（詳細）

正しく表示されていない原因は文頭の `[` が欠落しているため。
末尾の「イベント」の前にある空白は分かち書きする言語のためにあるもので、日本語には不要。

### プレイ国家

ハワイ

### ゲームバージョン

1.3.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
変更案の通り修正しました。
