### ISSUE TITLE
イベント「条項なし」

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#714]
### スクリーンショット

![20230602155410_1](https://github.com/matanki-saito/vic3jpadvmod/assets/42687608/bb79550b-54a5-4541-ba61-8b5934287a34)

### 問題部分

本文

### 問題のイベントタイトル

条項なし

### 問題のイベント本文（抜粋可）

と政治的に同調していないはに関する条項の意味論で分断されている。

### 希望する変更（修正部分のみ）

（利益集団名）と（利益集団名）は（法律名）に関する条項の意味論で分断されている。

### 変更の理由（概要）

翻訳時に発生した不具合

### 変更の理由（詳細）

日本語に翻訳する過程で変数の処理を誤ったことが原因。間違いは2箇所ある。

### プレイ国家

ハワイ

### ゲームバージョン

1.3.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
修正しました。
間違いは2箇所ではなく3箇所ありました。
