### ISSUE TITLE
◯◯日日後に自動解決

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#716]
### スクリーンショット

![20230602195946_1](https://github.com/matanki-saito/vic3jpadvmod/assets/42687608/e6984394-390d-42c3-a37c-20d482b963aa)

### 問題のあるインターフェイス

イベントのツールチップ

### 問題のテキスト

◯◯日日後に自動解決

### 希望する変更

◯◯日後に自動解決

### 変更の理由（概要）

日本語として自然な表現に変更

### 変更の理由（詳細）

変数部分に「日」が含まれているため、「日」が二重になってしまっている。
なお、原文は Will auto resolve in: ◯◯ で、日に相当する単語は含まれていない。

### ゲームバージョン

1.3.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
変更案通りに修正しました。
