### ISSUE TITLE
法案支持の草の根運動（不要なスペース）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#717]
### スクリーンショット

![20230602204603_1](https://github.com/matanki-saito/vic3jpadvmod/assets/42687608/fc399f3b-5627-4c5c-b2aa-22da288efd05)

### 問題部分

本文

### 問題のイベントタイトル

法案支持の草の根運動

### 問題のイベント本文（抜粋可）

三流社交クラブにおける活発な議論によって、　国民衛兵を指示する声がまるで野火のように

### 希望する変更（修正部分のみ）

三流社交クラブにおける活発な議論によって、国民衛兵を指示する声がまるで野火のように

### 変更の理由（概要）

不要なスペースが存在するため

### 変更の理由（詳細）

法律名（上の例では国民衛兵）の前に不要な全角スペースが存在するので、これを削除する。

### プレイ国家

ハワイ

### ゲームバージョン

1.3.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
変更案のとおりに修正しました。
