### ISSUE TITLE
高圧的な姿勢

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#718]
### スクリーンショット

![20230603191809_1](https://github.com/matanki-saito/vic3jpadvmod/assets/42687608/0ae1983d-6cd1-4fa4-a5ff-2fe5e2673bee)

### 問題部分

本文

### 問題のイベントタイトル

高圧的な姿勢

### 問題のイベント本文（抜粋可）

が労働組合の敵を見間違えた。

### 希望する変更（修正部分のみ）

（人名）が労働組合の敵を見間違えた。

### 変更の理由（概要）

翻訳時に発生した不具合

### 変更の理由（詳細）

翻訳時の不具合で変数が正しく表示されていない。

### プレイ国家

ハワイ

### ゲームバージョン

1.3.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
変数の修正、および「見間違った」を「見誤った」に修正しました。
