### ISSUE TITLE
請願行進

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#719]
### スクリーンショット

![20230603193548_1](https://github.com/matanki-saito/vic3jpadvmod/assets/42687608/4833e283-caaa-4fe3-9729-b858e17ce11c)

### 問題部分

本文

### 問題のイベントタイトル

請願行進

### 問題のイベント本文（抜粋可）

（利益集団リーダー）が率いる（利益集団）を代表する請願者の集団は、（支配者）に率いられて、（都市）の現在空家となっている住宅を行進している。

### 希望する変更（修正部分のみ）

（利益集団リーダー）に率いられた（利益集団）を代表する請願者の集団は、（都市）にある現在使われていない（支配者）の公邸を行進している。

### 変更の理由（概要）

誤訳のため

### 変更の理由（詳細）

誤訳なのは支配者の名前がresidenceの所有者ではなく、まったく無関係の意味で使われているところ。

### プレイ国家

ハワイ

### ゲームバージョン

1.3.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
（都市）にある（統治者）の邸宅を目指して行進を始めた（利益集団）の請願隊は、（リーダー）の先導の下、今やもぬけの殻となった邸宅を占拠した。彼らは「（支配者）との面談が叶わない限り邸宅からは退去しない」と強硬な姿勢を見せている。
で更新しました
