### ISSUE TITLE
【修正提案】トリガーの条件文

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#72]
＜ゲームシステム用語＞

## スクリーンショット（任意）

![20221027163401_1](https://user-images.githubusercontent.com/42710893/198226431-d8ddfb60-64b8-472f-9bf2-8f3daf0fa6d7.jpg)

## 問題の用語（必須）

手元資金は以上25％です
週次利益以上0.00
労働者稼働率は以上75％です

スクショではこれだけですが、他にも同様な箇所が多数あります

## 英語版の表現（任意）

`The [concept_cash_reserves] is $COMPARATOR$ $NUM|%0v$`
`Weekly profit $COMPARATOR$ #variable $NUM$#!`
`The workforce [concept_occupancy] is $COMPARATOR$ #variable $NUM|%0v$#!`

## 希望する変更（必須）

手元資金は25％以上です
週次利益**は**0.00以上です
労働者稼働率は75％以上です　等

あるいは、トリガー条件文のため、文体は
○○○○**が**△△以上**である**　とした方が良いかもしれません。

## 変更の理由（必須）

日本語として不自然なため

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

無し

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1035106878897782806
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by SHI-ZU-KU** [comment]
当件について確認したいのですが、進捗はどうなっていらっしゃいますか？
というのは、原因となっている「triggers_l_japanese.yml」を個人的に修正したので、よければこのMODに反映していただければと。
ただし、修正が広範にわたるので現状確認が完全ではありません。
可能であれば、関係者の方に共有して多人数でチェックもしていただければと思っています。

**Comment by inarizushi0309** [comment]
> 当件について確認したいのですが、進捗はどうなっていらっしゃいますか？ というのは、原因となっている「triggers_l_japanese.yml」を個人的に修正したので、よければこのMODに反映していただければと。 ただし、修正が広範にわたるので現状確認が完全ではありません。 可能であれば、関係者の方に共有して多人数でチェックもしていただければと思っています。

条件文ファイルは一括して私が担当しています。文体統一ルールの確定に時間をかけていたので、更新できていませんでしたが、今日から修正作業が本格化しています。
基本ルールとしては #193 に記載しているものになります。もし、このルールに合致する状態で修正されていましたら、是非参考にしたいです。

**Comment by SHI-ZU-KU** [comment]
情報ありがとうございます。
基本的にこのルールに従っているつもりで修正しています。
また、conceptから持ってこれる単語は直書きせずにそっちから参照するようにもしたつもりです。
一度見ていただきたいのですが、共有はどうすればいいですか？

**Comment by inarizushi0309** [comment]
こちらにファイルを添付できませんでしょうか？できない場合は別途方法を考えます

**Comment by SHI-ZU-KU** [comment]
よろしくお願いいたします。

**Comment by SHI-ZU-KU** [comment]
[triggers_l_japanese.zip](https://github.com/matanki-saito/vic3jpadvmod/files/9929740/triggers_l_japanese.zip)
よろしくお願いします。

**Comment by inarizushi0309** [comment]
ファイル受領しました。簡単に確認させていただきましたが、かなり良い出来ですね。一部、議論の都合上、まだ反映できないものもあるのですが、これも使って条件文の修正を済ませたいと思います。ご協力ありがとうございます！

**Comment by SHI-ZU-KU** [comment]
了解です。どう取り込んだかの結果は教えていただけますか？
別MODの「Japanese Replace Patch」で公開してしまってるものなので、取り込まれ方次第でそっちをどうするか考えたいので。
申し訳ありませんがよろしくお願いします。

**Comment by inarizushi0309** [comment]
こちらの修正状況は以下Modにて毎日更新されています。ファイルの修正については文体の統一は週末には完了しますが、各条件文内の用語などは個々に起票→修正になりますので、さらに時間を要しますことをご了承ください。
https://steamcommunity.com/sharedfiles/filedetails/?id=2881605374

**Comment by SHI-ZU-KU** [comment]
了解しました。確認しておきます。

**Comment by matanki-saito** [comment]
メモ：$FILTER$変数は後ろに「の」を付けることにする

**Comment by inarizushi0309** [comment]
$FILTER$関連については #361 にて扱うことになりました

**Comment by inarizushi0309** [comment]
```$FILTER$```関連以外はあらかた修正が完了したのでクローズとします。以後、修正箇所が見つかった場合は、都度起票することにします。
