### ISSUE TITLE
法律制定時のツールチップ（アウトライナー）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#720]
### スクリーンショット

![20230603204106_1](https://github.com/matanki-saito/vic3jpadvmod/assets/42687608/8c7c9e78-96cb-43e9-86cd-07e140b1d842)
![20230603205248_1](https://github.com/matanki-saito/vic3jpadvmod/assets/42687608/ef235da8-ad45-485a-918a-eb426453f7d3)

### 問題のあるインターフェイス

法律制定時のツールチップ（アウトライナー）

### 問題のテキスト

（日付）にへと進む確率◯◯%

### 希望する変更

（日付）に（法律制定のフェーズ）へと進む確率◯◯%

### 変更の理由（概要）

バニラの不具合

### 変更の理由（詳細）

スクリーンショットの通り、英語版でも正常に表示されておらず、バニラの不具合だと思われる。

### ゲームバージョン

1.3.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
問題に再現性がないので取り下げます。
