### ISSUE TITLE
アリイ・ヌイの運命

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#721]
### スクリーンショット

![20230604133916_1 2](https://github.com/matanki-saito/vic3jpadvmod/assets/42687608/9eba8f81-0283-4ec4-8652-ee9588760f6e)

### 問題部分

選択肢

### 問題のイベントタイトル

アリイ・ヌイの運命

### 問題のイベント選択肢

アリイ・ヌイと追放する。

### 希望する変更（修正部分のみ）

アリイ・ヌイを追放する。

### 変更の理由（概要）

誤訳のため

### 変更の理由（詳細）

単純な誤訳。アリイ・ヌイはハワイの支配者の称号（王に相当）。
原文は Send the ◯◯ into exile.

### プレイ国家

ハワイ

### ゲームバージョン

1.3.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
変更案の通りに修正しました。
