### ISSUE TITLE
外交行動のツールチップの「恩義を負っている」

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#722]
### スクリーンショット

![20230605130935_1](https://github.com/matanki-saito/vic3jpadvmod/assets/42687608/a2b64bff-4d25-41a2-bd58-f13e998042f7)

### 問題のあるインターフェイス

外交行動のツールチップ

### 問題のテキスト

〇〇に対し恩義を負っているのであれば、彼らは受け入れるでしょう

### 希望する変更

〇〇に対し恩義を負うならば、彼らは受け入れるでしょう

### 変更の理由（概要）

実際のゲームメカニズムと異なっている

### 変更の理由（詳細）

「自国が恩義を負うことを申し出れば、相手国が交渉を承諾する」という意味なので、現在の訳は正しくない。
原文は「◯◯ would accept, if we owe them an obligation」。

### ゲームバージョン

1.3.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
変更案の通り修正しました。
