### ISSUE TITLE
開放◯◯市場（戦争目標）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#723]
### スクリーンショット

![20230605160650_1](https://github.com/matanki-saito/vic3jpadvmod/assets/42687608/b9940e77-d1eb-4efc-858c-8c56165928d2)

### 問題のあるインターフェイス

外交戦ウィンドウ

### 問題のテキスト

開放◯◯市場

### 希望する変更

◯◯市場の開放

### 変更の理由（概要）

日本語として自然な表現に変更

### 変更の理由（詳細）

「開放」自身が変数なので訳すのが困難だったと思われる。
「の」を補ったのは他の戦争目標と揃えるため。

### ゲームバージョン

1.3.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
変更案の通り修正しました。
