### ISSUE TITLE
アウトライナー「◯個がピン止め解除」

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#725]
### スクリーンショット

![20230608000718_1](https://github.com/matanki-saito/vic3jpadvmod/assets/42687608/063bd1a0-fb29-4678-882a-a0b1bc90e933)

### 問題のあるインターフェイス

アウトライナー

### 問題のテキスト

ジャーナル記事　◯個がピン止め解除

### 希望する変更

ジャーナル記事　他◯個

### 変更の理由（概要）

実際のゲームメカニズムと異なっている

### 変更の理由（詳細）

原文は「◯ unpinned」。

直訳としては正しいが、「現在ピン止めされていないジャーナル記事が◯個あり、いつでもピン止めできる状態にある」というゲーム上の意味がまったく伝わっていない。
また、このエントリはキーの末尾がSHORTであり、可能な限り説明を省いた短縮版であることがわかる。そのため、長文で翻訳するのは本末転倒と言える。

### ゲームバージョン

1.3.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
変更案の通り修正しました。
