### ISSUE TITLE
イベント「革命の道」

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#726]
### スクリーンショット

![20230608003233_1](https://github.com/matanki-saito/vic3jpadvmod/assets/42687608/0c1f89c3-8a94-456c-ba56-bcff678da80a)

### 問題部分

本文

### 問題のイベントタイトル

革命の道

### 問題のイベント本文（抜粋可）

我々の勝利の後にクーデターが怒ることは不可避であり、

### 希望する変更（修正部分のみ）

我々の勝利の後にクーデターが起こることは不可避であり、

### 変更の理由（概要）

単純な誤字

### 変更の理由（詳細）

原文を見る限り、「起こる」を「怒る」と打ち間違えた単純な誤字だと思われる。

### プレイ国家

ハワイ

### ゲームバージョン

1.3.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
変更案の部分を修正し、さらに指摘を受けた選択肢部分の「紅衛兵」を「赤衛軍」に修正しました。
