### ISSUE TITLE
イベント「老人への暴言」

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#727]
### スクリーンショット

![20230608124004_1](https://github.com/matanki-saito/vic3jpadvmod/assets/42687608/5d84d486-eda9-4d98-99c4-559dc281b36d)

### 問題部分

本文

### 問題のイベントタイトル

老人への暴言

### 問題のイベント本文（抜粋可）

現在の法文書上ではは、

### 希望する変更（修正部分のみ）

現在の法文書上では、

### 変更の理由（概要）

単純なミスタイプ

### 変更の理由（詳細）

単純なミスタイプ。

### プレイ国家

ハワイ

### ゲームバージョン

1.3.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
変更案の通り修正しました。
