### ISSUE TITLE
アクティブなジャーナル記事

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#728]
### スクリーンショット

![20230608173441_1](https://github.com/matanki-saito/vic3jpadvmod/assets/42687608/4c51add9-eaa6-4b0d-a0f2-4460bce34265)

### 問題のあるインターフェイス

ジャーナルウインドウ（左）とアウトライナー（右）

### 問題のテキスト

現在、アクティブなジャーナル記事がありません

### 希望する変更

現在有効なジャーナル記事がありません

### 変更の理由（概要）

テキストが文字あふれを起こしているため

### 変更の理由（詳細）

訳文が長すぎて表示が2行になってしまっている。
ジャーナルウインドウはともかくアウトライナーは貴重な表示行数を圧迫しており、修正が必要だと思われる。
また、それぞれ「ジャーナル記事が」と「ジャーナル記事は」で表記ゆれを起こしているので、同時に統一する。

### ゲームバージョン

1.3.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
変更案の通り修正しました。
