### ISSUE TITLE
【修正提案】旅行馬車　Passenger Carriages

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#73]
## 問題の固有名詞と希望する変更（必須）
木製の旅行馬車：木製客車
鉄製の旅行馬車：鋼製客車

## 変更の理由（必須）

鉄道用車両の話なので、明らかな誤訳
![image](https://user-images.githubusercontent.com/37979626/198259174-bece5056-338f-4f3e-93c7-6400cf6db48d.png)

## ゲームバージョン（必須）

1.0.1

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1035135474878120026
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by inarizushi0309** [comment]
原案どおりに修正
