### ISSUE TITLE
「失敗した計画、計画された失敗」の本文

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#730]
### スクリーンショット

![20230524205119_1](https://github.com/matanki-saito/vic3jpadvmod/assets/38329957/d4c170c1-5243-45a6-a479-09658402d52c)

### 問題部分

本文

### 問題のイベント本文（抜粋可）

キルギスでの飢饉は、ソビエト連邦の経済政策の批判に火をつけました

政府の計画に依存した指令経済

### 希望する変更（修正部分のみ）

``[SCOPE.sState('famine_state').GetName]``での飢饉は、``[ROOT.GetCountry.GetName]``の経済政策であり政府の計画に依存する

``$famine_political.d$``への批判を巻き起こした。

### 変更の理由（概要）

意味が分かりにくいため。

### 変更の理由（詳細）

この文章は二つの文章によって組み合わさっており、繋げて訳すべきところを別々に訳してしまっており、意味が分からなくなってしまっている。

### プレイ国家

ロシア

### ゲームバージョン

1.3.X

### MOD有無

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。

**Comment by oooFUNooo** [comment]
議論の結果、バージョンアップに対応した再修正が完了しました。クローズします。
