### ISSUE TITLE
「隠されたナイフ」の誤訳修正

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#731]
### スクリーンショット

![20230524021725_1](https://github.com/matanki-saito/vic3jpadvmod/assets/38329957/f2eaee42-42dc-4c1e-8a2e-c2ecded465c7)

### 問題部分

タイトル, 本文, 選択肢

### 問題のイベントタイトル

隠されたナイフ

### 問題のイベント本文（抜粋可）

最近の軍事的敗北による屈辱を受けた多くの人々は、[ROOT.GetCountry.GetName]の[SCOPE.sPop('discriminated_culture_pop').GetCulture.GetName]が戦線で戦争努力を裏切っていると主張し、その責任を追及しています。

最近の軍事的敗北による屈辱を受けた多くの人々は、[ROOT.GetCountry.GetName]の[SCOPE.sPop('discriminated_religion_pop').GetReligion.GetName]が戦線で戦争努力を裏切っていると主張し、その責任を追及しています。

### 問題のイベント選択肢

そうに違いない！[ROOT.GetCountry.GetName]は公平な戦いで 決して負けることはないはずだ。

### 希望する変更（修正部分のみ）

背後のナイフ

昨今の軍事的敗北に屈辱を感じた多くの人々は、[ROOT.GetCountry.GetName]国内の[SCOPE.sPop('discriminated_culture_pop').GetCulture.GetName]人が銃後で我々の戦争努力を裏切ったからだと主張し、責任を転嫁しています。

昨今の軍事的敗北に屈辱を感じた多くの人々は、[ROOT.GetCountry.GetName]国内の[SCOPE.sPop('discriminated_religion_pop').GetReligion.GetName]信者が銃後で我々の戦争努力を裏切ったからだと主張し、責任を転嫁しています

そうに違いない！公平な戦いなら[ROOT.GetCountry.GetName]は 決して負けることはないはずだ。

### 変更の理由（概要）

誤訳の修正、一部定訳に近い形に修正

### プレイ国家

ロシア

### ゲームバージョン

1.3.X

### MOD有無

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
文化ではなく宗教を指定している本文もあったので追加。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
