### ISSUE TITLE
地主階級名「公職による貴族政治」

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#733]
### スクリーンショット

![20230608134642_1](https://github.com/matanki-saito/vic3jpadvmod/assets/38329957/6c1bbfd1-446e-4110-a1ff-8056ae7b26a1)

### 問題の固有名詞：希望する変更

公職による貴族政治：貴族的公務員

### 変更の理由（概要）

意味が分かりにくいため。

### 変更の理由（詳細）

ノルウェーの地主名、ゲーム内テキストでの解説によると、貴族制度が廃止されるも公務員がそれに成り代わったとのこと。

### ゲームバージョン

1.3.X

### MOD有無

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
