### ISSUE TITLE
扇動者名の修正案

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#735]
### スクリーンショット

なし

### 問題の固有名詞：希望する変更

ピサレフ：ピーサレフ
エミリアノ：エミリアーノ
ザパタ：サパタ
アハメド：アフマド
ウラビ：オラービー
ジェンタイル：ジェンティーレ
ビョルンストイェルン：ビョルンスティエルネ
アラディン：アラーディン
サバハディーン：サバハッディン
ヴィーゴ：ヴィゴ
ヒュロップ：フーロプ
ブランズ：ブランデス
ルイズ・ソリーリャ：ルイス・ソリーリャ
ドゥ・ラ・トゥール・デュ・パン・シャンブリー：ド・ラ・トゥール・デュ・パン・シャンブリ
ドラグーミス：ドラグミス
ドゥ・ボア：デュボイス
ブルネット：ブリュネ
エメライン：エメリン
ラサール：ラッサール
ヤット＝セン：文

### 変更の理由（概要）

日本語では一般的ではない表記であるため

### ゲームバージョン

1.3.X

### MOD有無

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
