### ISSUE TITLE
アンガース（フランスの地名）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#736]
### スクリーンショット

![20230611141554_1](https://github.com/matanki-saito/vic3jpadvmod/assets/42687608/8ad6c2e8-abc8-49ee-bde9-d84e00daca81)

### 問題の固有名詞：希望する変更

アンガース：アンジェ

### 変更の理由（概要）

日本語では一般的でない表記であるため

### 変更の理由（詳細）

原文はAngers。フランスはロワール地方の都市（スクショ中央）。
検索してもアンガースという読みはヒットせず、単なる読み間違いだと思われる。

### ゲームバージョン

1.3.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
変更案の通り修正しました。
