### ISSUE TITLE
The Enabling Acts

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#739]
### スクリーンショット

なし

### 問題部分

タイトル, 本文

### 問題のイベントタイトル

権限を与える法

### 問題のイベント本文（抜粋可）

```[SCOPE.sParty('ruling_party').GetName]```が議事堂の扉の鍵を閉めて議員を閉じ込め、直ちに現政府の権限を大幅に拡大する動議を提出しました。ギャラリーにいる反対派は、茶色の服を着たファシストの民兵によって沈黙させられています。

第1項:
憲法に定められた手続きに加え、```[ROOT.GetCountry.GetNameNoFormatting]```政府も```[ROOT.GetCountry.GetNameNoFormatting]```の法律を制定できるものとする。

第2項:
```[ROOT.GetCountry.GetNameNoFormatting]```政府が制定した法律は議会の精度に影響を与えない範囲で、憲法から逸脱してもよいものとする。```[ROOT.GetCountry.GetRuler.GetPrimaryRoleTitle]```の権利は影響を受けない。

### 希望する変更（修正部分のみ）

全権委任法

```[SCOPE.sParty('ruling_party').GetName]```が国会の扉を施錠し議員を閉じ込め、直ちに現政府の権限を大幅に拡大する動議を提出しました。廊下にいる反対派は、褐色の制服を着たファシストの私兵によって沈黙させられています。

第1条:
憲法に定められた手続きに加え、憲法に規定されている手続き以外に、```[ROOT.GetCountry.GetNameNoFormatting]```政府によっても```[ROOT.GetCountry.GetNameNoFormatting]```の法律は制定されうる。

第2条:
```[ROOT.GetCountry.GetNameNoFormatting]```政府によって制定された法律は、国会制度そのものに関わるものでない限り、憲法に違反することができる。```[ROOT.GetCountry.GetRuler.GetPrimaryRoleTitle]```の権限は影響を受けない。

### 変更の理由（概要）

定訳に近い形に修正

### ゲームバージョン

1.3.X

### MOD有無

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
