### ISSUE TITLE
【修正提案】電車　Electric Trains

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#74]
## スクリーンショット（任意）
![image](https://user-images.githubusercontent.com/37979626/198259627-c86c4dc1-a569-4d1b-9319-83f639c06174.png)

## 問題の固有名詞（必須）

電車

## 希望する変更（必須）

電気機関車

## 変更の理由（必須）

スクショからも分かるように前後が「～機関車」である以上、こちらもあわせるべき
また、アイコンからも列車全体を一般的に指す「電車」ではなく、機関車のみを指していることからも同様である

## ゲームバージョン（必須）

1.0.1

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1035136221854306354
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by inarizushi0309** [comment]
修正
