### ISSUE TITLE
「Franco-Provençal」文化

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#740]
### スクリーンショット

![20230612202033_1](https://github.com/matanki-saito/vic3jpadvmod/assets/38329957/e8276767-e5eb-4875-bd4e-56b97dfd563f)

### 問題の固有名詞：希望する変更

フランコ・プロヴァンサル：アルピタン

### 変更の理由（概要）

意味が分かりにくいため。

### 変更の理由（詳細）

長すぎて正しく表示されないことが多く、なおかつ文化名としてはふさわしくないため。

### ゲームバージョン

1.3.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
内部での検討の結果「アルピタン」は根拠薄弱であるとされたため、代わりに「フランス・プロヴァンス」に修正しました。

**Comment by ChiefIdeologue** [comment]
クローズします。
