### ISSUE TITLE
誉れある（特性）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#741]
### スクリーンショット

![20230613113135_1](https://github.com/matanki-saito/vic3jpadvmod/assets/42687608/29970ac3-6bce-4ba8-90cd-6443ac6c3033)

### 問題の用語

誉れある

### 英語版の表現

Honorable

### 希望する変更

高潔

### 変更の理由（概要）

日本語として自然な表現に変更

### 変更の理由（詳細）

性格を表す特性の名称なので、他の特性に合わせて名詞にするべきだと考えます。

### ゲームバージョン

1.3.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
提案の通り修正しました。
