### ISSUE TITLE
ランダム人名（Iosif, Stevenson）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#742]
### 問題の固有名詞：希望する変更

イオシフ：ヨシフ
ステファンソン：スティーブンソン

### 変更の理由（概要）

日本語では一般的でない表記であるため

### 変更の理由（詳細）

Iosifはルーマニア文化のランダム名候補。
Stevensonはヤンキー文化とスコットランド文化のランダム名候補。
いずれも日本で一般的な表記に改める。

### ゲームバージョン

1.3.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
スティーブンソンはスティーヴンソンに変更し、ヨシフは提案通りに修正しました。
