### ISSUE TITLE
北アンデス文化の姓名

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#745]
### スクリーンショット

なし

### 問題の固有名詞：希望する変更

キプリアノ：シプリアーノ
エウゼビオ：エウセビオ
エウストロジオ：エウストルヒオ
エゼキエル：エセキエル
フランシスコ・ジョゼ：フランシスコ・ホセ
ジレールモ：ギジェルモ
グスタフォ：グスタボ
ヒラリオ：イラリオ
ユアン・ジョゼ：フアン・ホセ
ジュリアン：フリアン

ヒパティア：イパティア
ローレンツァ：ロレンサ
ゾイラ：ソイラ

デ・ヘレーラ：デ・エレーラ
デ・ヴェインテミラ：デ・ベインテミージャ
デ・ヴィラミル：デ・ビジャミル

アルファーロ：アルファロ
アンデューザ：アンドゥエサ
ボネット：ボネ
カーマノ：カーマーニョ
カレーノ：カレーニョ
キアリ：チアリ
ダーザ：ダーサ
ガティアレズ：グティエレス
ヘラン：エラン
フルタード：ウルタード
マラーリノ：マジャリーノ
マンジャレス：マンハレス
マリーノ：マリーニョ
モレーノ：モレノ
ヌネズ：ヌーニェス
パエズ：パエス
ロカフールト：ロカフエルテ
サルガー：サルガル
ソーブレット：ソウブレッテ
ヴィレガス：ビジェガス
ザルドゥア：サルドゥア

### 変更の理由（概要）

スペイン語の表記法に合わないため

### ゲームバージョン

1.3.X

### MOD有無

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
