### ISSUE TITLE
スウェーデン共産党（SKP）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#746]
### 問題の固有名詞：希望する変更

スウェーデン共産党：スウェーデン／フィンランド共産党

### 変更の理由（概要）

元の略称が複数の政党に使われるため

### 変更の理由（詳細）

英語版の表記はSKPと略称だが、Issue #487 で他の政党名とあわせて「スウェーデン共産党」と修正された。
ところが、このエントリはゲーム内で「フィンランド共産党」にも流用されていることが判明した。
スウェーデン共産党とフィンランド共産党の略称はともにSKPであり、このままでは不適当なので改訳が必要だと思われる。

提案した改訳案「スウェーデン／フィンランド共産党」はあくまで叩き台で、議論で最適な訳を決めて欲しい。

### ゲームバージョン

1.3.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
「共産党」で修正しました
