### ISSUE TITLE
南アンデス文化の姓名

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#747]
### スクリーンショット

なし

### 問題の固有名詞：希望する変更

ゲルマン：ヘルマン
ヘルナンド：エルナンド
ヒラリオン：イラリオン
ジョゼ・ミゲル：ホセ・ミゲル
ユアン・フランシスコ：フアン・フランシスコ
ナリキソ：ナルシソ
ルフィノ：ルフィーノ
ルパート：ルペルト
セヴェリノ：セベリーノ

ヘルシリア：エルシリア

ド・ヴェラスコ：デ・ベラスコ
ド・ヴィダル：デ・ビダル
デ・ラ・クルツ：デ・ラ・クルス

アルタミラノ：アルタミラーノ
バリヴィアン：バリビアン
ベルズ：ベルス
バルネス：ブルネス
カルヴォ：カルボ
カスティーラ：カスティーリャ
コリッコ：コリコ
エシェニーク：エチェニケ
エランズリズ：エラスリス
ジラルテ：ギラルテ
ラトッレ：ラトーレ
マルガレホ：メルガレホ
モンジェ：モンヘ
ペゼ：ペセト
レベレード：レボリェード
サラヴェリー：サラベリ
サイルス：シレス
ソトメイヤー：ソトマヨル
ザナルトゥ：サニャルトゥ

### 変更の理由（概要）

スペイン語の表記法に合わないため

### ゲームバージョン

1.3.X

### MOD有無

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
南アンデス文化の地域では、ジェイスモが適用されないことを踏まえ以下を修正。

バリヴィアン：バジビアン　→　バリビアン
カスティーラ：カスティージャ　→　カスティーリャ
レベレード：レボジェード　→　レボリェード

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
