### ISSUE TITLE
ラプラタ文化の姓名

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#748]
### スクリーンショット

なし

### 問題の固有名詞：希望する変更

キャンディード：カンディド
エヴァリスト：エバリスト
マーシャル：マルシアル
ローク：ロケ
ヴェナンシオ：ベナンシオ

エンカーナシオン：エンカルナシオン

デ・アルヴェール：デ・アルベアル
ド・ゴイェネシェ：デ・ゴジェネチェ
ド・ラマドリッド：デ・ラマドリード
ピューイレドン：プエイレドン
デ・ロザス：デ・ロサス
デ・ウルキーツァ：デ・ウルキサ
デ・ラ・プラザ：デ・ラ・プラサ
リヴァダヴィア：リバダビア

アヴェラネダ：アベジャネーダ
ベッロ：ベロ
バエズ：バエス
カバレロ：カバリェロ
クルツ：クルス
デルクイ：デルキ
エラウリ：エジャウリ
エスコバール：エスコバル
ジョヴェラノス：ホベジャーノス
マケイン：マチャイン
マザ：マサ
メザ：メサ
パズ：パス
ペレグリニ：ペジェグリーニ
リヴァロラ：リバロラ
リヴェラ：リベラ
ロンデュー：ロンドー
ソラノ：ソラーノ
サエンズ：サエンス
タジェス：タヘス
ワイズナー：ビスネル
イリゴーイェン：イリゴージェン

### 変更の理由（概要）

スペイン語の表記法に合わないため

### ゲームバージョン

1.3.X

### MOD有無

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
