### ISSUE TITLE
【修正提案】稲畑 Rice Farms

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#75]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![inebatake](https://user-images.githubusercontent.com/50406316/198260001-0c939942-a515-4b7c-ac98-321e7154109f.png)

## 問題の用語（必須）
稲畑

## 英語版の表現（任意）
Rice Farms

## 希望する変更（必須）
田

## 変更の理由（必須）
日本語として通常使う呼び名ではなく、誤訳であるため

## ゲームバージョン（必須）
1.0.3

## DLC有無（必須）
無し

## MOD有無（必須）
なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1035136550838730783
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by matanki-saito** [comment]
稲田票が最多ですかね。あんまりこだわって長引かせるのもなんなので、稲田にしたいと思います。
