### ISSUE TITLE
ブルトン文化の姓名

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#750]
### スクリーンショット

なし

### 問題の固有名詞：希望する変更

アイメリー：エメリ
オーギュスト・ヒラリオン：オーギュスト・イラリオン
フェリシテ・ピエーレ：フェリシテ・ピエール
ジャコウ：ジャク
モリデルン：モルディルン

エリザベス：エリザベート
ティファニー：ティフェンヌ

オードレン・デ・カードレル：オドラン・ド・ケルドレル
ベルトイス：ベルトワ
ドゥイリアムソン：ドゥイヤムソン
デ・ベクデリーベ：ド・ベクドリエーヴル
デ・ボイスゲリン：ド・ボワジュラン
デ・チンター：ド・サントレ
デ・コーヌリア：ド・コルニュリエ
デ・ボセレル：ド・ボトレル
デ・ディエウレヴェルト：ド・デュルヴ
デ・ファーシー：ド・ファルシ
デ・ゴースブリアンド：ド・ゴエスブリアン
デ・ゴーレイン：ド・グーレーヌ
デ・ゲーヘネック：ド・ギュエエナク
デ・カーガリオウ：ド・ケルガリウ
デ・ケラトリー：ド・ケラトリ
デ・カーゴレイ：ド・ケルゴレ
デ・カーサウソン：ド・ケルソゾン
デ・ランジェ・デ・ビューマノール：ド・ラングル・ド・ボーマノワール
デ・ルージュクス：ド・ルジュー
デス・ノス：デ・ノ
ドゥ・プルスケレク：デュ・プリュスケレク
エスピヴェント・デ・ラ・ヴィレスボイスネット：エスピヴァン・ド・ラ・ヴィルボワネ
ジュシャルト：ジュショー
ランジュイナス：ランジュイネ

ベデュー：ブドー
ドッセール：ドセ
ガーランド：ガラン
ル・ブリス：ル・ブリ
ル・ミュール：ル・ムエル
ケルフェテール：ケルフテ
ロペール：ロペ
ヴァリー：ヴァレ

### 変更の理由（概要）

フランス語の表記法に合わないため

### ゲームバージョン

1.3.X

### MOD有無

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
