### ISSUE TITLE
政府所有物として制定する法的な許可

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#751]
### スクリーンショット

ゲーム内の使用箇所を確認できず。

### 問題のあるインターフェイス

補正

### 問題のテキスト

◯◯を政府所有物として制定する法的な許可です

### 希望する変更

◯◯の政府助成を制定する法的な許可です

### 変更の理由（概要）

誤訳のため

### 変更の理由（詳細）

原文はLegal permission to enact government subsidies of ◯◯
隣のエントリに「◯◯の助成を許可」という補正名があることから、誤訳だと考えられる。
誤訳の影響は12エントリに及ぶ。

### ゲームバージョン

1.3.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
議論の結果、「◯◯の政府助成を可能にする法的な許可です」と修正しました。
