### ISSUE TITLE
ジャーナル「樹脂生産」

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#752]
### スクリーンショット

![20230618075611_1](https://github.com/matanki-saito/vic3jpadvmod/assets/42687608/56ab5288-45fb-4c23-9e12-c1ae9a5043ac)

### 問題部分

タイトル

### 問題のイベントタイトル

樹脂生産

### 問題のイベント本文（抜粋可）

樹脂の利用用途はガラスのそれをはるかに上回っている。

### 希望する変更（修正部分のみ）

プラスチックの用途はガラスをはるかに上回っている。

### 変更の理由（概要）

日本語では一般的でない表記であるため

### 変更の理由（詳細）

単に「樹脂」と表記すると、天然樹脂のことか合成樹脂のことか分かりにくい（この場合は合成樹脂）。
なお、ゲーム中に登場する商品のplasticは「プラスチック」と翻訳されている。

### プレイ国家

イギリス

### ゲームバージョン

1.3.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
関連イベントも含め、提案通り「プラスチック」に修正しました。
