### ISSUE TITLE
太平天国の利益集団「神を崇める社会」

### ISSUE THREAD

**Issue by awak1180** [matanki-saito/vic3jpadvmod#753]
### 問題の固有名詞：希望する変更

神を崇める社会：拝上帝会

### 変更の理由（概要）

日本語では一般的ではない表記のため。

### 変更の理由（詳細）

「神を崇める社会」は英語では God-Worshipping Society となっているが、これは「拝上帝会」と表記するのが正しいと考えられる。 [参考](https://en.wikipedia.org/wiki/God_Worshipping_Society)

### ゲームバージョン

1.3.X

### MOD有無

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
確認したところ、神を崇める社会はすべて拝上帝会に修正してありました。
対応遅くなり申し訳ございませんでした。
