### ISSUE TITLE
国家名「利己主義者連合」とその形容詞形

### ISSUE THREAD

**Issue by awak1180** [matanki-saito/vic3jpadvmod#754]
### 問題の固有名詞：希望する変更

利己主義者連合：エゴイスト連合
利後主義者：エゴイスト

### 変更の理由（概要）

下記の理由から、より正確と思われる訳への変更を希望する。

### 変更の理由（詳細）

「利己主義者連合」とは、[ドイツが虚無主義者率いる無神論国家となった場合](https://vic3.paradoxwikis.com/Dynamic_country_names)の国名である。英語では、"[Union of egoists](https://en.wikipedia.org/wiki/Union_of_egoists)"となっているが、これは哲学者[マックス・シュティルナー](https://ja.wikipedia.org/wiki/%E3%83%9E%E3%83%83%E3%82%AF%E3%82%B9%E3%83%BB%E3%82%B7%E3%83%A5%E3%83%86%E3%82%A3%E3%83%AB%E3%83%8A%E3%83%BC)の思想が出典と考えられる。

筆者が調べた範囲では、シュティルナーの思想としての"egoism/egoist"は一般的な意味での利己主義・自己中心主義とは異なっており、日本語の文章でも漢語に訳さない「エゴイズム/エゴイスト」が定訳と思われる。(先述の、"Union of egoists"も「エゴイストの連合」で検索すると複数ヒットする)

よって、国家名を「エゴイスト連合」に、形容詞形を「エゴイスト」にすることを提案する。

### ゲームバージョン

1.3.X

### MOD有無

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
起票ありがとうございます。国名は提案通り「エゴイスト連合」に修正しました。
形容詞形についてはissue166の議論の際に、基本的には国名と同じ名前に揃えるという方針になっていたため、それを準用して形容詞形も国名と同様に「エゴイスト連合」としています。

**Comment by awak1180** [comment]
承知しました。ご対応ありがとうございます。
