### ISSUE TITLE
所有権PMの和訳

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#755]
### スクリーンショット

![owner_ja](https://github.com/matanki-saito/vic3jpadvmod/assets/50406316/643b731e-79b6-4914-a425-b81dc2e4d851)
![owner_en](https://github.com/matanki-saito/vic3jpadvmod/assets/50406316/61402d91-1987-4e05-8d29-afacb8ab3c8a)

### 問題の用語

個人所有/公開企業

### 英語版の表現

Privately Owned/Publicly Traded

### 希望する変更

非公開/公開取引

### 変更の理由（概要）

ゲーム中の意味に沿う用語に改訳

### 変更の理由（詳細）

Privately Ownedはゲーム中ではPublicly Tradedの対比で使われているので、個人所有ではなく非公開という意味になる。用例を考えると個人所有だけではなく、集団所有や非公開企業の場合もこちらに含まれるので、「個人所有」の訳はスコープを狭くしすぎている。
Publicly Tradedは原文に「企業」の用語が無く、ゲーム中でも必ずしも企業だけを意味するとは限らないので、企業の単語は外して原文の逐語訳に変更したい。

### ゲームバージョン

1.3.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
※参考
https://gogakuru.com/english/phrase/81943
>" privately held company " は「私企業、株式非公開の会社」という意味ですが、 " privately owned company [corporation] " とも言います。
