### ISSUE TITLE
Zeppelins

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#756]
### スクリーンショット

![Zeppelins](https://github.com/matanki-saito/vic3jpadvmod/assets/50406316/09159252-ff9b-451e-8aca-8631d892addd)

### 問題の用語

飛行船

### 英語版の表現

Zeppelins

### 希望する変更

ツェッペリン（または硬式飛行船）

### 変更の理由（概要）

原文と訳語の非対応

### 変更の理由（詳細）

原文がZeppelinなので、飛行船の中でも特に外殻を金属化した硬式飛行船のことを指しているため。
ゲーム中でもTier4の技術であるが、軟式飛行船はそれ以前の史実の年代で既に開発されている。

### ゲームバージョン

1.3.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
チーム内での議論の結果、「硬式飛行船」に決定しました。なお技術の説明文についてもこの変更に準じて硬式飛行船の説明になるよう改訳を行っています。
