### ISSUE TITLE
Central Plannning

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#757]
### スクリーンショット

![planning](https://github.com/matanki-saito/vic3jpadvmod/assets/50406316/60340abf-a638-44bf-b9f6-6c105782a8a4)

### 問題の用語

中央指令型経済

### 英語版の表現

Central Planning

### 希望する変更

中央計画経済

### 変更の理由（概要）

定訳への変更

### 変更の理由（詳細）

Planned economyの定訳が計画経済であるため。
なお法律ではこれとは別に「Commanded Economy/指令経済」があるが、こちらとは原文がCommandedとPlanningで異なっているため、訳語も変えたほうがいいと思います。

### ゲームバージョン

1.3.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
提案通り修正しました。
