### ISSUE TITLE
ゲーム開始時の蘭芳の指導者「劉タイジ」

### ISSUE THREAD

**Issue by awak1180** [matanki-saito/vic3jpadvmod#758]
### スクリーンショット

![20230708](https://github.com/matanki-saito/vic3jpadvmod/assets/43375638/e3cd00be-c9a9-4107-8693-dda92b650120)

### 問題の固有名詞：希望する変更

タイジ：台二

### 変更の理由（概要）

漢字表記されるべき所がカナ表記になっているため。

### 変更の理由（詳細）

ゲーム開始時の蘭芳の指導者Liu Taijiとは、1836年時点の総長の劉台二のことと思われる。[参考](https://ja.wikipedia.org/wiki/%E8%98%AD%E8%8A%B3%E5%85%AC%E5%8F%B8)

### ゲームバージョン

1.3.X

### MOD有無

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
起票ありがとうございます。提案通り修正しました。
