### ISSUE TITLE
Prince/王子

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#759]
### スクリーンショット

![india](https://github.com/matanki-saito/vic3jpadvmod/assets/50406316/79feeff1-aabf-43ed-ae8b-bd7a0e24b96b)

### 問題部分

選択肢

### 問題のイベントタイトル

イギリスによる支配の終焉？

### 問題のイベント本文（抜粋可）

（省略）

### 問題のイベント選択肢

インドは王子たちの間で分割される。

### 希望する変更（修正部分のみ）

インドは諸侯の間で分割される。

### 変更の理由（概要）

Princeの誤訳

### 変更の理由（詳細）

東インド会社がイギリスから独立した場合に起きるイベント。
原文Princesを王子と訳しているが、これはインドの諸侯（藩王）のことなので誤訳であるため。

### プレイ国家

東インド会社

### ゲームバージョン

1.3.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。
