### ISSUE TITLE
【修正提案】電軌鉄道　Electric Railways

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#76]
## スクリーンショット（任意）
![image](https://user-images.githubusercontent.com/37979626/198260303-a7273ea9-11df-40c2-b444-760273a36961.png)

## 問題の固有名詞（必須）

電軌鉄道

## 希望する変更（必須）

電気鉄道

## 変更の理由（必須）

誤字

## ゲームバージョン（必須）

1.0.1

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1035136835053170698
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by matanki-saito** [comment]
この時代に一般的なのは客車や貨物車に電動モーターが付いて自走できるタイプじゃなく、電気機関車で牽引する方式がほぼ大半だと思うので、電車よりは当初案通りそのまま電気鉄道に変更のほうが適切かと思います
