### ISSUE TITLE
Two Californias

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#760]
### スクリーンショット

![cal](https://github.com/matanki-saito/vic3jpadvmod/assets/50406316/930ae12a-f47c-4b62-b785-d67ae04dc667)

### 問題の固有名詞：希望する変更

ラス・カリフォルニアス：両カリフォルニア
カリフォルニアス：両カリフォルニア
※二段目は形容詞形

### 変更の理由（概要）

誤訳の修正

### 変更の理由（詳細）

カリフォルニアがカリフォルニア州及びバハ・カリフォルニア州の両方を支配した場合に変化する架空の国名。
英語名はTwo Californiasで、アメリカ側の上カリフォルニアとメキシコ側の下カリフォルニア二つを領有していることを意味し、両シチリア（Two Sicilies）をもじった名前と思われるので訳語もそれに合わせたい。
現行訳のラス・カリフォルニアスはニュースペイン植民地時代の旧名であり、Two Californiasに直接対応する訳語ではない。またゲーム中のこの国はスクショの通りヤンキー＋メキシコ文化＆プロテスタントの国で、国教を考えるとヤンキー文化が優位と思われるのでスペイン語名にすることもあまり適切ではないように思われる。

### ゲームバージョン

1.3.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
提案通り修正しました。
