### ISSUE TITLE
革命イベント「陸上の船員」にて州名が NULL_STATE となってしまう

### ISSUE THREAD

**Issue by proudust** [matanki-saito/vic3jpadvmod#761]
### スクリーンショット

![20230624185116_1](https://github.com/matanki-saito/vic3jpadvmod/assets/20186429/d79c6ace-bde6-45b6-99f7-83272f2f6276)

### 問題部分

本文, 選択肢

### 問題のイベントタイトル

陸上の船員

### 問題のイベント本文（抜粋可）

NULL_STATEの船員は、航海のための乗船を拒否している。反乱の範囲が広いため、状況に応じた繊細なアプローチが必要だ。

### 問題のイベント選択肢

男たちを拘束し、事件をNULL_STATEに封じ込めよ。

### 希望する変更（修正部分のみ）

```diff
- revolution_pulse1_events.8.d:0 "[SCOPE.sState('coreast_navy_state').GetName]の船員は、航海のための乗船を拒否している。反乱の範囲が広いため、状況に応じた繊細なアプローチが必要だ。"
+ revolution_pulse1_events.8.d:0 "[SCOPE.sState('coastal_navy_state').GetName]の船員は、航海のための乗船を拒否している。反乱の範囲が広いため、状況に応じた繊細なアプローチが必要だ。"
- revolution_pulse1_events.8.a:0 "男たちを拘束し、事件を[SCOPE.sState('coreast_navy_state').GetName]に封じ込めよ。"
+ revolution_pulse1_events.8.a:0 "男たちを拘束し、事件を[SCOPE.sState('coastal_navy_state').GetName]に封じ込めよ。"
```

### 変更の理由（概要）

表示異常のため

### 変更の理由（詳細）

NULL_STATE は `agitators_1_l_japanese.yml` ファイル内では `[SCOPE.sState('coreast_navy_state').GetName]` となっているが、`game\events\agitators_events\revolution_events_01.txt` を読む限り `coreast_navy_state` ではなく `coastal_navy_state` が正しい。

### プレイ国家

ブラジル

### ゲームバージョン

1.3.X

### MOD有無

Cities: Skylines, Dense Market Details, Extra Topbar Info, State traits at helpful locations!

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通り修正しました。遅くなりましたが、起票ありがとうございました。
