### ISSUE TITLE
アップデートで追加されたイタリア人名

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#764]
### スクリーンショット

なし

### 問題の固有名詞：希望する変更

アファン・デ・リヴェラ：アーファン・デ・リヴェーラ
カラ・ウロア：カラー・ウローア
モンターニ・デ・ペザロ：モンターニ・ダ・ペーザロ
デ・サムエレ・カニャーツィ：デ・サムエーレ・カニャッツィ
ディ・クロラランザ：ディ・クロラランツァ
パテルノ：パテルノー
デ・トマシス：デ・トマージス
ディ・ブロケッティ：ディ・ブロッケッティ

アゲシラオ：アジェジラーオ
チェシディオ：チェジーディオ
コラディーノ：コッラディーノ
クロストフォロ：クリストーフォロ
イグナツィオ：イニャーツィオ
サルバトーレ：サルヴァトーレ

アサンティ：アッサンティ
アクラヴィオ：アックラーヴィオ
ボゼッリ：ボッゼリ
チャンチューリ：チャンチュリ
キャンパーニャ：カンパーニャ
キャポッチ：カポッチ
フォルテゲーリ：フォルテグエーリ
ジャヌッツィ：ジャンヌッツィ
メッザカーポ：メッツァカーポ
ペペ：ペーペ
パルミエリ：パルミエーリ
クアンデル：クァンデル
リチャルディ：リッチャルディ
サムソーネ：サンソーネ
サニア：サンニア
トマジ：トンマージ

ブファラリ：ブファラーリ
オズマニ：オスマーニ
スガリリア：スガリーリャ
ズメドゥッチ：スメドゥッチ
ボイリ・ディ・プティフィガリ：ボイル・ディ・プティフィーガリ
コスタ・デ・ベアリガード：コスタ・デ・ボルガール
ダルカイス：ダルセ
デ・シャンボスト：ド・シャンボ
ジュベ・デ・ソナズ：ジェルベ・デ・ソンナズ
ファルクイ・ペス：ファルクィ・ペス
フェチア・ディ・コサート：フェーチャ・ディ・コッサート
ジロー・デ・モントファルコン：ジロー・ド・モンファルコン
ペティッティ・バリアーニ・ディ・ロレト：ペティッティ・バリャーニ・ディ・ロレート
ディ・サルモア：ディ・サルムール
サンタ・クローチェ・ヴィラヘルモーサ：サンタ・クローチェ・ヴィラエルモーザ
ソミス・ディ・シャヴリエ：ソミス・ディ・シャヴリー

オッタヴィオ：オッターヴィオ
トマッゾ：トンマーゾ
アルミニョン：アルマンジョン
アスプロニ：アスプローニ
バイノ：バイーノ
ベロノ：ベローノ
ベルッティ：ベルティ
ベツィ：ベッツィ
ビアンケリ：ビアンケーリ
ボナ：ボーナ
ボッテロ：ボッテーロ
ブロフェリオ：ブロッフェーリオ
ブルナティ：ブルナーティ
ブルニエ：ブリュニエ
カボニ：カボーニ
カンビエリ：カンビエーリ
カンタラ：カンターラ
カプリオロ：カプリオーロ
カッシーニ：カッシーニス
クロザ：クローザ
クジャ：クージャ
デフィーノ：デルフィーノ
フェラシウ：フェラーチュ
ジェルボレ：ジェルボーレ
フェスコ：フェスコト
ジェイメット：ジェイメト
ジグリーニ：ギリーニ
ジャノリオ：ジャノーリオ
ジネット：ジネート
ジョバノーラ：ジョヴァノーラ
グラフィーニャ：グラッフィーニャ
グリクソニ：グリクソーニ
グリアネッティ：グリャネッティ
ギリエ：グイレト
ラキーナル：ラケーナル
マメリ：マメーリ
マミアニ：マミアーニ
メレガリ：メレガーリ
メラナ：メッラーナ
メッゼーナ：メッツェーナ
ミリオレッティ：ミリョレッティ
ミノーリオ：ミノーリョ
ナイタナ：ナイターナ
オイタナ：オイターナ
パレオキャパ：パレオカパ
パリエリ：パッリエーリ
パテリ：パテーリ
ピチネリ：ピチネッリ
ポレリ：ポッレーリ
ポルケドゥ：ポルケッドゥ
クアリア：クァーリャ
ラタッツィ：ラッタッツィ
リカルディ：リッカルディ
サンギネッティ：サングイネーティ
スピノーラ：スピノラ
トラ：トーラ
トゥヴェリ：トゥヴェーリ
ヴァルバッソーリ：ヴァルヴァッソーリ
ヴィカリ：ヴィカーリ
ジリオ：ジーリオ

### 変更の理由（概要）

イタリア語の表記法に合わないため

### ゲームバージョン

1.4.X

### MOD有無

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
