### ISSUE TITLE
アップデートで追加されたスイス人名

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#765]
### スクリーンショット

なし

### 問題の固有名詞：希望する変更

ベヒトールド：ベヒトルト
ヴァラー：ファレール
フォン・ビュレン：フォン・ビューレン
フォン・フリッシング：フォン・フリッシンク
ステンフリ：シュテンプフリ
レズ：レーツ
フォン・バーグマン：フォン・ベルクマン
フォン・レディンク：フォン・レディンク＝ビーバーエック
クンディヒ：キュンディヒ
デュゲリン：デューゲリン
フォン・ウェーバー：フォン・ヴェーバー
モリコファー：メリコーファー

ヨハン・コンラッド：ヨハン・コンラート
ヤーコブ・クリストフ：ヤーコプ・クリストフ
ゴットリーブ：ゴットリープ
ナザール：ナツァー
プラシダス：プラシドゥス
ステファン：シュテファン
シルヴァン：ジルヴァン

アンデルワルト：アンダーヴァート
アウトヴェグ：アルトヴェグ
エプリ：エープリ
ベンジンガー：ベンツィンガー
ベットシャート：ベッチャート
ビンツェガー：ビンツェッガー
カメンジンド：カーメンツィント
エンダリン：エンダーリン
エッゲンシュワイラー：エッゲンシュヴァイラー
エベール：エバーレ
ファスビンド：ファスビント
イテン：イーテン
クオニ：クオーニ
リンツ：リント
リエンハルト：リーンハルト
リッチ：リッチー
ラブハルト：ラープハルト
ロイテネガー：ロイテネッガー
オエティカー：エーティカー
リチャード：リチャート
ラックシュトゥール：ルックシュトゥール
シモニン：シモナン
スタイガー：シュティガー
シードラー：ジドラー
ズルツバーガー：ズルツベルガー
シャーブ：シャープ
ツィエマー：チーマー
ヴィリガー：フィリガー
ヴィニストフ：ヴィニストルフ
ウィネト：ヴィネト
ゼアレッダー：ツェーアレダー
ジルテナー：ツィルテナー

カール・フリードリヒ：カール＝フリードリヒ

### 変更の理由（概要）

ドイツ語あるいはフランス語の表記法に合わないため

### ゲームバージョン

1.4.X

### MOD有無

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
