### ISSUE TITLE
称号名と政府名

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#767]
### スクリーンショット

なし

### 問題の固有名詞：希望する変更

主席：議長
第一王子：王太子（あるいはプランス・ロワイヤル）
第一王女：王太女（あるいはプランセス・ロワイヤル）
王太子妃：王太女
技師長：主任技術長
大神官：大司祭
神官：司祭
男主任：職工長
女主任：職工長

神権的政権：神権政府
コンテクネ：操舵技術国
技術家主義：技術家国家
サイバネティック国家：操舵手国家

### 変更の理由（概要）

誤訳の修正

### 変更の理由（詳細）

主席：議長　現在の訳語の主席は以前に改訳されたものだが、Victoriaの時代的にはレーニンが人民委員会議議長（Chairman of the Council of People's Commissars）に就任しており、こちらを意味していると思われるため議長が適訳であると考えられる。
第一王子：王太子（あるいはプランス・ロワイヤル）　オルレアニストが元首の際の後継者名
第一王女：王太女（あるいはプランセス・ロワイヤル）　同上
王太子妃：王太女　後継者の称号名であるため誤訳
技師長：主任技術長　技術家主義＋議会共和制の時の称号名。
大神官：大司祭　技術家主義＋神権制の時の称号名。　Warhammer 40000のオマージュである可能性がある。
神官：司祭　同上
男主任：職工長　技術家主義＋評議会共和制の時の称号名
女主任：職工長　同上

神権的政権：神権政府
コンテクネ：操舵技術国　技術家主義＋神権制の時の政府名。
技術家主義：科学技術国　政府名であるため誤訳
サイバネティック国家：操舵手国家　技術家主義＋評議会共和制の時の政府名。時代的に現代のコンピューター的なニュアンスではなく、ギリシャ語の原義「（船の）舵を取る者」を意味するキュベルネーテース的な意味と思われるため。

### ゲームバージョン

1.4.X

### MOD有無

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
議論の余地がある「コンテクネ」と「サイバネティック国家」を保留とし、この二つ以外を修正しました。
