### ISSUE TITLE
法律制定時の「後退」選択時のツールチップ文

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#768]
### スクリーンショット

![image](https://github.com/matanki-saito/vic3jpadvmod/assets/37979626/2a93efec-98fb-43c0-b62b-f4b10d58397b)

### 問題のツールチップ

法律制定イベント>後退選択肢マウスオーバー

### 問題の表現

ADD_ENACTMENT_SETBACK_FIRST
```[COUNTRY.GetNameNoFlag]における[COUNTRY.GetLawBeingEnacted.GetName]の[Concept('concept_enactment_of_laws','$concept_enactment_of_laws_enactment$')]が$VALUE|v0$ポイントを獲得します [Select_CString( EqualTo_CFixedPoint( '(CFixedPoint)$VALUE$', '(CFixedPoint)1' ), Concept('concept_enactment_setback', '$concept_enactment_setback_short$'), Concept('concept_enactment_setback', '$concept_enactment_setbacks_short$') )]```

ADD_ENACTMENT_SETBACK_THIRD
```[COUNTRY.GetName]における[COUNTRY.GetLawBeingEnacted.GetName]の[Concept('concept_enactment_of_laws','$concept_enactment_of_laws_enactment$')]が$VALUE|v0$ポイントを獲得します [Select_CString( EqualTo_CFixedPoint( '(CFixedPoint)$VALUE$', '(CFixedPoint)1' ), Concept('concept_enactment_setback', '$concept_enactment_setback_short$'), Concept('concept_enactment_setback', '$concept_enactment_setbacks_short$') )]```

ADD_ENACTMENT_SETBACK_GLOBAL
```[Concept('concept_enactment_of_laws','$concept_enactment_of_laws_enactment$')]が$VALUE|v0$ポイントを獲得します [Select_CString( EqualTo_CFixedPoint( '(CFixedPoint)$VALUE$', '(CFixedPoint)1' ), Concept('concept_enactment_setback', '$concept_enactment_setback_short$'), Concept('concept_enactment_setback', '$concept_enactment_setbacks_short$') )]```

### 問題箇所の英文

ADD_ENACTMENT_SETBACK_FIRST
```[Concept('concept_enactment_of_laws','$concept_enactment_of_laws_enactment$')] of [COUNTRY.GetLawBeingEnacted.GetName] in [COUNTRY.GetNameNoFlag] gains $VALUE|v0$ [Select_CString( EqualTo_CFixedPoint( '(CFixedPoint)$VALUE$', '(CFixedPoint)1' ), Concept('concept_enactment_setback', '$concept_enactment_setback_short$'), Concept('concept_enactment_setback', '$concept_enactment_setbacks_short$') )]```

ADD_ENACTMENT_SETBACK_THIRD
```[Concept('concept_enactment_of_laws','$concept_enactment_of_laws_enactment$')] of [COUNTRY.GetLawBeingEnacted.GetName] in [COUNTRY.GetName] gains $VALUE|v0$ [Select_CString( EqualTo_CFixedPoint( '(CFixedPoint)$VALUE$', '(CFixedPoint)1' ), Concept('concept_enactment_setback', '$concept_enactment_setback_short$'), Concept('concept_enactment_setback', '$concept_enactment_setbacks_short$') )]```

ADD_ENACTMENT_SETBACK_GLOBAL
```[Concept('concept_enactment_of_laws','$concept_enactment_of_laws_enactment$')] gains $VALUE|v0$ [Select_CString( EqualTo_CFixedPoint( '(CFixedPoint)$VALUE$', '(CFixedPoint)1' ), Concept('concept_enactment_setback', '$concept_enactment_setback_short$'), Concept('concept_enactment_setback', '$concept_enactment_setbacks_short$') )]```

### 希望する変更

ADD_ENACTMENT_SETBACK_FIRST
```[COUNTRY.GetNameNoFlag]における[COUNTRY.GetLawBeingEnacted.GetName]の[Concept('concept_enactment_of_laws','$concept_enactment_of_laws_enactment$')]が$VALUE|v0$ポイント[Select_CString( EqualTo_CFixedPoint( '(CFixedPoint)$VALUE$', '(CFixedPoint)1' ), Concept('concept_enactment_setback', '$concept_enactment_setback_short$'), Concept('concept_enactment_setback', '$concept_enactment_setbacks_short$') )]します ```

ADD_ENACTMENT_SETBACK_THIRD
```[COUNTRY.GetName]における[COUNTRY.GetLawBeingEnacted.GetName]の[Concept('concept_enactment_of_laws','$concept_enactment_of_laws_enactment$')]が$VALUE|v0$ポイント[Select_CString( EqualTo_CFixedPoint( '(CFixedPoint)$VALUE$', '(CFixedPoint)1' ), Concept('concept_enactment_setback', '$concept_enactment_setback_short$'), Concept('concept_enactment_setback', '$concept_enactment_setbacks_short$') )]します```

ADD_ENACTMENT_SETBACK_GLOBAL
```[Concept('concept_enactment_of_laws','$concept_enactment_of_laws_enactment$')]が$VALUE|v0$ポイント[Select_CString( EqualTo_CFixedPoint( '(CFixedPoint)$VALUE$', '(CFixedPoint)1' ), Concept('concept_enactment_setback', '$concept_enactment_setback_short$'), Concept('concept_enactment_setback', '$concept_enactment_setbacks_short$') )]します```

### 変更の理由（概要）

変数に対応できていないため

### プレイ国家

スウェーデン

### ゲームバージョン

1.4.X

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通り修正しました。
