### ISSUE TITLE
政治運動ツールチップ

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#769]
### スクリーンショット

![Victoria 3 Screenshot 2023 10 07 - 22 11 38 83](https://github.com/matanki-saito/vic3jpadvmod/assets/147261526/1423c7ce-2f9a-43e8-a3a4-cbce94228396)

### 問題のツールチップ

政治運動のツールチップ

### 問題の表現

```POLITICAL_MOVEMENT_SUPPORTING_AGITATORS: "#title [Concept('concept_agitator', '$concept_agitators$')]を支持しています#!"```

### 問題箇所の英文

```POLITICAL_MOVEMENT_SUPPORTING_AGITATORS: "#title Supporting [Concept('concept_agitator', '$concept_agitators$')]#!"```

### 希望する変更

[Concept('concept_agitator', '$concept_agitators$')]が支持しています
[Concept('concept_agitator', '$concept_agitators$')]が支持中　等

### 変更の理由（概要）

助詞の誤り

### 変更の理由（詳細）

助詞の誤り

### プレイ国家

スウェーデン

### ゲームバージョン

1.4.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
すぐ上の表記に合わせて「支持している扇動者」に修正しました。
同様に、「利益集団を支持しています」も「支持している利益集団」に変更しました。
