### ISSUE TITLE
【修正提案】ファインアート　Fine Art

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#77]
## スクリーンショット（任意）
![image](https://user-images.githubusercontent.com/37979626/198262526-8ed17a06-078e-475f-b2ba-10c317b914a7.png)

## 問題の固有名詞（必須）

ファインアート

## 希望する変更（必須）

美術品

## 変更の理由（必須）

wikiでもファインアートとの表現はあるが、概念的表現で生産品として表現するのであれば「美術品」の方が分かりやすい
また他の生産品と違い、ここだけ音訳にする特別性も感じられない
https://ja.wikipedia.org/wiki/%E3%83%95%E3%82%A1%E3%82%A4%E3%83%B3%E3%82%A2%E3%83%BC%E3%83%88#:~:text=%E3%83%95%E3%82%A1%E3%82%A4%E3%83%B3%E3%82%A2%E3%83%BC%E3%83%88%EF%BC%88fine%20art%2C%20fine,%E5%AF%BE%E3%81%97%E3%81%A6%E7%B4%94%E7%B2%8B%E7%BE%8E%E8%A1%93%E3%81%A8%E3%82%82%E3%80%82

## ゲームバージョン（必須）

1.0.1

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1035140340123963453
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。
