### ISSUE TITLE
檍

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#770]
### スクリーンショット

![Victoria 3 Screenshot 2023 10 07 - 21 58 46 01](https://github.com/matanki-saito/vic3jpadvmod/assets/147261526/6d5860c6-94d8-4575-8f90-428a50be6585)

### 問題のあるインターフェイス

確認画面等　多数

### 問題のテキスト

```OK: "檍"```

### 希望する変更

OK

### 変更の理由（概要）

誤訳

### 変更の理由（詳細）

誤訳のため

### ゲームバージョン

1.4.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
Mod有無欄に「日本語改善Mod」と記載されていますが、こちらの問題は既に修正されています。
modの更新が正しく行われているかご確認をお願いいたします。（毎日更新されています）

**Comment by matanki-saito** [comment]
なお、本修正内容はまだParadoxに通知されておらず、公式翻訳には反映されていません
日本語改善Modを導入していない環境でこの問題が発生するのはその通りです

**Comment by wakkunteitoku2** [comment]
こちらのミスでMODが適用されていなかったようです。
設定し直したところ、正しく表示できました。大変失礼しました。

**Comment by matanki-saito** [comment]
@.inarizushi @f_u_n 
確認しました。これは3/14の取り込みでok: okで記載されていたものが、ok: 檍になったのだともいます。デンマークの問題と同じですね。なので報告していなかったのではなく、おかしくなったので再度報告で良いと思います。
https://github.com/matanki-saito/vic3jpadvmod/commit/3dd57b9cd8fc32ea6be7c9558857321da2b0bf92#diff-85b2cee374cb1844ef8d395abbfb53f6b70b4213c8d329c3d2741790b690126cL73

**Comment by matanki-saito** [comment]
通常通りクローズし、デグレとして報告します
