### ISSUE TITLE
戦線の進行ツールチップ

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#771]
### スクリーンショット

![Victoria 3 Screenshot 2023 10 13 - 20 34 28 63](https://github.com/matanki-saito/vic3jpadvmod/assets/147261526/d26a4867-3ce6-4031-be05-8dad23f0d7d2)

### 問題のツールチップ

戦線の進行ツールチップ

### 問題の表現

移動には○かかります 日

### 希望する変更

移動には○日かかります

### 変更の理由（概要）

構文ミス

### 変更の理由（詳細）

構文ミス

### プレイ国家

スウェーデン

### ゲームバージョン

1.4.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
報告ありがとうございます。該当エントリを見てみたところ、「日」が最後に来るのがハードコーディングされて変更できなかったため、「所要移動日数 〇 日」という形式に変更しました。
