### ISSUE TITLE
外交画面ツールチップ

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#772]
### スクリーンショット

![Victoria 3 Screenshot 2023 10 16 - 18 00 24 99](https://github.com/matanki-saito/vic3jpadvmod/assets/147261526/6a6de251-5448-401d-9939-b1abc66841be)

### 問題のツールチップ

外交画面ツールチップ

### 問題の表現

```DIPLOMATIC_ACCEPTANCE_ALLIED_TO_RIVALS: "[SCOPE.GetRootScope.GetCountry.GetAdjectiveNoFormatting] [Concept('concept_rivalry','$concept_rivals$')]と我が国は、[Concept('concept_alliance','$concept_alliances$')]または[Concept('concept_defensive_pact','$concept_defensive_pacts$')]の関係です"```

### 問題箇所の英文

```DIPLOMATIC_ACCEPTANCE_ALLIED_TO_RIVALS:1 "We have [Concept('concept_alliance','$concept_alliances$')] or [Concept('concept_defensive_pact','$concept_defensive_pacts$')] with [SCOPE.GetRootScope.GetCountry.GetAdjectiveNoFormatting] [Concept('concept_rivalry','$concept_rivals$')]"```

### 希望する変更

```DIPLOMATIC_ACCEPTANCE_ALLIED_TO_RIVALS: "[SCOPE.GetRootScope.GetCountry.GetAdjectiveNoFormatting]の[Concept('concept_rivalry','$concept_rivals$')]と我が国は、[Concept('concept_alliance','$concept_alliances$')]または[Concept('concept_defensive_pact','$concept_defensive_pacts$')]の関係です"```

### 変更の理由（概要）

助詞もれ

### 変更の理由（詳細）

助詞もれ
条件文なので語尾は他条件も含めて「～である」等で統一したほうが良い気もしますが、修正箇所が多岐にわたると思うので、判断はお任せします

### プレイ国家

スウェーデン

### ゲームバージョン

1.4.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
（国名）のライバル国との同盟ないし防衛協定
で修正しました。他の外交ツールチップについては別のISSUEで対応いたします
