### ISSUE TITLE
汎用Formation（編隊）名

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#773]
### スクリーンショット

![formations_name](https://github.com/matanki-saito/vic3jpadvmod/assets/43299334/8a1220fd-e70f-4213-b6df-f87154035963)

### 問題のあるインターフェイス

汎用の編隊名

### 問題のテキスト

1. ズールー 陸軍
FORMATIONS_NAME: "$NUM|O$ $COUNTRY_ADJECTIVE$ $TYPE$"

### 希望する変更

第1ズールー陸軍
FORMATIONS_NAME: "$NUM$$COUNTRY_ADJECTIVE$$TYPE$"

### 変更の理由（概要）

不自然な名称であるため

### 変更の理由（詳細）

$NUM|O$は$NUM$とすることで数字のみとすることができる（「.」を無くせる）。

### ゲームバージョン

1.5.X

### MOD有無

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
議論の結果、
ズールー第1軍、ズールー第1艦隊
などのように修正しました。
