### ISSUE TITLE
（Formation；編隊の名称としての）陸軍（Army）/海軍（Fleet)

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#774]
### スクリーンショット

![formations_name](https://github.com/matanki-saito/vic3jpadvmod/assets/43299334/92e7a4b3-4cbc-491b-831e-a41bf5af36a6)
![fleets](https://github.com/matanki-saito/vic3jpadvmod/assets/43299334/3072f6be-e86f-4649-a8de-db414f5c5980)

### 問題のあるインターフェイス

編隊アウトライナーなど

### 問題のテキスト

concept_army: "陸軍"
concept_fleet: "海軍"ほか

### 希望する変更

陸軍→軍
海軍→艦隊

### 変更の理由（概要）

普通名詞の陸軍/海軍と訳が重複しているため

### 変更の理由（詳細）

1.5から追加されたFormation;編隊の、陸軍、海軍における名前。原文では陸軍;Army、海軍;Fleetとなっている。
要するに陸軍の編隊がArmy、海軍の編隊がFleetなのだが、この説明からも分かる通り現行訳ではかなり紛らわしい。
issue773で提案する修正を施せば自動生成される名前が「第1イギリス陸軍/海軍」などにもなり、この点でも不適当と思われるため、これと同時に改訳しておきたい。

### ゲームバージョン

1.5.X

### MOD有無

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
軍/艦隊で修正
