### ISSUE TITLE
形容詞形になっている南米の追加文化

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#775]
### スクリーンショット

![sa](https://github.com/matanki-saito/vic3jpadvmod/assets/50406316/ac42f503-71eb-4d91-99a9-ab31ea62d905)

### 問題の固有名詞：希望する変更

ボリビアン：ボリビア
エクアドリアン：エクアドル
チリアン：チリ
ベネズエラン：ベネズエラ
アルジェンティーネ：アルゼンチン
ウルグアイアン：ウルグアイ
パラグアイアン：パラグアイ
コロンビアン：コロンビア

### 変更の理由（概要）

名詞形の訳語に統一

### 変更の理由（詳細）

文化名は英語版で形容詞形になっているものも日本語では名詞形で訳すが、1.5で追加された上記の文化名は形容詞形のまま音訳されているため。

### ゲームバージョン

1.5.X

### MOD有無

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
提案通り修正しました。
