### ISSUE TITLE
Caudillo/Caudillismoの訳語揺れ

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#776]
### スクリーンショット

![cd_ja](https://github.com/matanki-saito/vic3jpadvmod/assets/50406316/806cba33-c4e4-4297-9856-a77cad2d51ab)

### 問題の用語

カウディーリョ（主義）、軍事独裁者など

### 英語版の表現

Caudillo/Caudillismo

### 希望する変更

カウディーリョ/カウディーリョ主義

### 変更の理由（概要）

訳語揺れの統一

### 変更の理由（詳細）

Caudillo/Caudillismoがカウディーリョ（主義）、軍事独裁者などと訳語揺れしているので、カウディーリョ/カウディーリョ主義に統一したい。

### ゲームバージョン

1.5.X

### MOD有無

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
提案通り訳語統一しました。
