### ISSUE TITLE
汎用企業の自動生成名

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#778]
### スクリーンショット

<img width="264" alt="image" src="https://github.com/matanki-saito/vic3jpadvmod/assets/43299334/1a896f23-455a-4c60-9b9b-a9c494f01989">

### 問題の固有名詞：希望する変更

※現在の案の例
![image](https://github.com/matanki-saito/vic3jpadvmod/assets/43299334/dd927b20-bab3-42cd-866b-980bfb809384)

### 変更の理由（概要）

不自然な社名が多く、没入感を削ぐ。また「企業連合 連合」など破綻しているものも存在するため。

### 変更の理由（詳細）

訳し分けの困難な単語も多く含まれるため、一部は原文の生成ルールには存在しない地域名や都市名を利用するなどして差別化を図っている。

### ゲームバージョン

1.5.X

### MOD有無

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
内部で話し合った結果、原文をそのまま和訳しようとするとどうしても日本語としては不自然な名前になるため、抜本的にロジックを変更して自然な企業名にするための対応を行いました。誤訳修正を越えてこの改善MODのオリジナル要素に近くなったため、パラドックスへの誤訳修正の提案は行わず、当MODのオリジナル扱いのままとします
