### ISSUE TITLE
州名の固有名詞

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#78]
## 問題の固有名詞と希望する変更（必須）
アーカンサス：アーカンソー
ブリティッシュ・コロンビア：ブリティッシュコロンビア
アルベルタ：アルバータ
スカニア：スコーネ
ペロポネーゼ：ペロポネソス
カタロニア：カタルーニャ
ニュー・サウス・ウェールズ：ニューサウスウェールズ
ノースアイランド：北島
サウスアイランド：南島
ウリャスタイ：ウリヤスタイ
休戦沿岸：休戦海岸
シフアフア：チワワ
グエレッロ：ゲレーロ
ザカテカス：サカテカス
パスターサ：パスタサ
マト・グロッソ：マットグロッソ
サオ・パウロ：サンパウロ
ミナス・ジェライス：ミナスジェライス
バヒア：バイーア
ペルナムブコ：ペルナンブーコ
マランハオ：マラニョン
パーラ：パラー
メンドーザ：メンドーサ
シャコ：チャコ
ジュジュイ：フフイ
サンタ・クルツ：サンタクルス
アルリフ：アル・リーフ
コンスタンティン：コンスタンティーヌ
リビヤ砂漠：リビア砂漠
リビヤ：リビア
ブルーナイル：青ナイル
モカンビーク：モザンビーク
ラインスター：レンスター
ローン：ローヌ
アルザス・ロレーヌ：アルザス＝ロレーヌ
リムジン：リムーザン
バーガンディー：ブルゴーニュ
フランシュ・コンテ：フランシュ＝コンテ
オーベルジュ：オーヴェルニュ
イル・ド・フランス：イル＝ド＝フランス
ケープ・ヴェルデ：カーボベルデ
ワロニア：ワロン
ホランド：ホラント
ジーランド：ゼーラント
バルチスタン：バルーチスターン
マイスール：マイソール
ペグ：ペグー
ヴィサヤ：ビサヤ
アティッカ：アッティカ
コンゴ・オレエンタル：コンゴ・オリエンタル
コートジボワール：象牙海岸
ヴリスタート：フレイスタート
ハイル：ハーイル
ネジド：ナジュド
バグダッド：バグダード
モスル：モースル
シスタン：スィースターン
コーラサン：ホラーサーン
ラリスタン：ラーレスターン
クーゼスタン：フーゼスターン
ファルス：ファールス
イスファハン：エスファハーン
マザンダラン：マーザンダラーン
イラケジェミ：エラーケ・アジャム
タブリズ：タブリーズ
ルリスタン：ロレスターン
ヒュダヴェンディガル：ヒュダヴェンディギャール
アイディン：アイドゥン
コニャ：コンヤ
ヤンセオ：両西
ヤンホ：両湖
ラーサ：ラサ
ンガリ：ガリ
オストロボスニア：ポフヤンマー
ネネシア：ネネツ
ヒバ：ヒヴァ
キルギスタン：キルギス
オラル：ウラリスク
トルクメニア：トルクメン
オブ：オビ
サマラ：サマーラ
クバ：クバーニ
アストラカーン：アストラハン
ルハンスク：ルハンシク
アプリア：プッリャ
西ガリシア：西ガリツィア
東ガリシア：東ガリツィア
ベーケシ：ベーケーシュ
トランスダヌビア：ドゥナーントゥール
スティリア：シュタイアーマルク
デルビデク：デールヴィデーク
ポーセン：ポーゼン
ウェストファリア：ヴェストファーレン
シュレースウィヒ・ホルシュタイン：シュレースヴィヒ＝ホルシュタイン
ブランズウィック：ブラウンシュヴァイク
サルディーニャ：サルデーニャ
キーウ：キエフ
アンブリア：ウンブリア
ウター：ユタ
ガラパゴスライズ：ガラパゴス海膨
ナタル沿岸：ナタール沿岸
パタゴニアレイク：パタゴニア湖
パライーバ：パライバ
サンタ・カタリーナ：サンタカタリーナ
ヴェラクルズ：ベラクルス

クァシム系国家：カーシム
クァシム系：カーシム

## 変更の理由（必須）
日本語では一般的ではない表記であるため

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1035144395869126677
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by ChiefIdeologue** [comment]
新規修正案を追加しました。
クァシム系国家：カーシム
クァシム系：カーシム

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
