### ISSUE TITLE
現地価格タブ:市場価格との比較ツールチップの「プライス」

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#781]
### スクリーンショット

![Victoria 3 Screenshot 2023 11 17 - 21 47 23 35](https://github.com/matanki-saito/vic3jpadvmod/assets/147261526/2fed3571-fbe2-4686-a33d-2e8013b29bc9)

### 問題のツールチップ

現地価格タブ:市場価格との比較ツールチップ

### 問題の表現

```GOODS_LOCAL_PRICE_DIFF: "[Goods.GetStateToMarketPriceDiff|%0=-]（[Goods.GetMarket.GetName] [Concept('concept_market_price', '$MARKET_PRICE$')]と比較して）\n"```
```MARKET_PRICE: "プライス"```

### 問題箇所の英文

```GOODS_LOCAL_PRICE_DIFF: "[Goods.GetStateToMarketPriceDiff|%0=-] compared to [Goods.GetMarket.GetName] [Concept('concept_market_price', '$MARKET_PRICE$')]\n"```

### 希望する変更

MARKET_PRICE: "価格"

### 変更の理由（概要）

日本語として不自然なため

### 変更の理由（詳細）

カタカナにする意味を感じないので「価格」で良いのではないかと思います

### プレイ国家

アルゼンチン

### ゲームバージョン

1.5.X

### MOD有無

フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
報告ありがとうございます。提案通り修正しました。
