### ISSUE TITLE
外交戦の支援申し出（州の移譲）

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#782]
### スクリーンショット

![Victoria 3 Screenshot 2023 11 17 - 22 31 12 08](https://github.com/matanki-saito/vic3jpadvmod/assets/147261526/7b4922a4-1440-4861-9643-73b69807d660)

### 問題のあるインターフェイス

外交戦の支援申し出（州の移譲）

### 問題のテキスト

(州名)を移譲を求める

ツールチップ
(州名)を移譲への支援の申し出

### 希望する変更

(州名)の移譲を求める

ツールチップ
(州名)の移譲への支援の申し出
あるいは
(州名)の移譲に対する支援の申し出
(州名)の移譲による支援の申し出　等

### 変更の理由（概要）

日本語として不自然なため

### ゲームバージョン

1.5.X

### MOD有無

フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
REVERSE_SWAY_OFFER_TYPE: "[SwayOfferType.GetName]"
 SWAY_TYPE_TRANSFER_STATE: "[Concept('concept_state', '$concept_states$')]の割譲"
 SWAY_OFFER_TRANSFER_STATE: "[STATE.GetName]割譲"
 SWAY_TYPE_TRANSFER_SUBJECT: "[Concept('concept_subject', '$concept_subjects$')]の移譲"
 SWAY_OFFER_TRANSFER_SUBJECT: "[COUNTRY_THIRD_PARTY.GetName]の移譲"
 DIPLO_PLAY_REVERSE_SWAY_OFFER_DESC: "#header [concept_offer_support]の対価として$SWAY_OFFER|v$を要求#![ConcatIfNeitherEmpty('\n', AddLocalizationIf( And(SwayOffer.GetOfferedWarGoal.IsValid,GreaterThan_CFixedPoint(SwayOffer.GetOfferedWarGoal.GetInfamyAmount, '(CFixedPoint)0')), 'SWAY_OFFER_INFAMY_COST_ONLY'))][ConcatIfNeitherEmpty( '\n\n', '$ERRORS$' )]"
 SWAY_OFFER_WARGOAL_TYPE: "[WarGoalType.GetName]"
 SWAY_OFFER_TYPE: "[SwayOfferType.GetName]"
 SWAY_OFFER_NAME: "$NAME|v$"
 SWAY_COUNTRY_HEADER: "#bold[SwayCountryPanel.GetCountry.GetName]の[concept_sway]#!"
 REVERSE_SWAY_OFFER_OBLIGATION: "[concept_obligation]"
 REVERSE_SWAY_OFFER_WARGOAL_TYPE: "[WarGoalType.GetName]"
 REVERSE_SWAY_OFFER_TYPE: "[SwayOfferType.GetName]"
 REVERSE_SWAY_OFFER_NAME: "$NAME|v$"
 concept_offer_support: "支援"
 concept_offer_of_support: "支援"
 proposal_reverse_sway_offer_name: "支援"
 REVERSE_SWAY_OFFER_TITLE: "支援"
 OFFER_SUPPORT: "支援条件"
 SWAY_TYPE_BECOME_SUBJECT: "[concept_subject]化"
 SWAY_OFFER_BECOME_SUBJECT: "#v $SUBJECT_TYPE$化#!"
 war_goal_ban_slavery_type_name: "奴隷制の禁止"
 DIPLO_PLAY_CLICK_TO_SWAY: "#instruction クリックで[concept_sway]#!"
以上で修正しました
