### ISSUE TITLE
Cuencas Mineras

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#783]
### スクリーンショット

![cuencas_mineras](https://github.com/matanki-saito/vic3jpadvmod/assets/50406316/2547a506-a448-4572-8f72-f37b49b9c0cf)

### 問題の固有名詞：希望する変更

鉱山：クエンカス・ミネラス

### 変更の理由（概要）

誤訳の修正

### 変更の理由（詳細）

スペインのアストゥリアスにあるクエンカス・ミネラスのこと。
英語版ではスペイン語表記であるため、日本語でも音訳としたい。
なお英語で直訳するとMining Basinsであり、山ではなく盆地の意味である。
参考：https://es.wikipedia.org/wiki/Cuencas_Mineras_(Asturias)

### ゲームバージョン

1.5.X

### MOD有無

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
提案通り修正しました。
