### ISSUE TITLE
人口ビュー

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#784]
### スクリーンショット

![population](https://github.com/matanki-saito/vic3jpadvmod/assets/50406316/7dd81e50-e0fa-4699-ac9a-e0c9350b9e9d)

### 問題のあるインターフェイス

税金・需要

### 問題のテキスト

中産階級だけ「XX%税金」となり、「の」が抜けていて統一されていない

### 希望する変更

税金 XX%
需要 XX%

### 変更の理由（概要）

下記

### 変更の理由（詳細）

収入のうちXX%を税金や需要消費に充てていることの説明であるが、「XX%の需要」とすると需要のうちXX%だけが満たされているようにも受け取れて紛らわしいので、ゲーム上での意味が分かるような記載に変更したい。

### ゲームバージョン

1.5.X

### MOD有無

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。
