### ISSUE TITLE
Corporatism

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#785]
### スクリーンショット

![corporatism](https://github.com/matanki-saito/vic3jpadvmod/assets/50406316/051e366e-aaba-4265-a7b8-a0ca586b1c52)

### 問題の用語

協調組合主義

### 英語版の表現

Corporatism

### 希望する変更

コーポラティズム

### 変更の理由（概要）

より一般的な訳語に変更

### 変更の理由（詳細）

技術やイデオロギーに登場する名前。
コーポラティズムのほうが一般的な訳語であるため。
宗教IGに付くイデオロギーであり、corporationsが指す内容は組合だけではないため、協調組合主義と訳すのはゲーム内での用法ではあまり適していない。

参考：wikipedia
https://ja.wikipedia.org/wiki/%E3%82%B3%E3%83%BC%E3%83%9D%E3%83%A9%E3%83%86%E3%82%A3%E3%82%BA%E3%83%A0

また、説明文の「（前略）企業グループ間の（後略）」も誤訳で、ここでのcorporate groupsは共同体の意味で使っているため、「共同体の」と改訳したい。

### ゲームバージョン

1.5.X

### MOD有無

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
提案通り修正しました。また、あわせてCorporatistも同様の理由で「コーポラティスト」に修正しました。
