### ISSUE TITLE
POPの統合（積極的）

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#786]
### スクリーンショット

![pic](https://github.com/matanki-saito/vic3jpadvmod/assets/50406316/fa49927f-9337-4a19-95e0-eac1d6e0b617)

### 問題のあるインターフェイス

POPの統合（積極的）

### 問題のテキスト

上記スクリーンショットで行数溢れしている

### 希望する変更

「それなりの規模の～～」の行の読点を削り、1行に収める

### 変更の理由（概要）

行数溢れしているため

### 変更の理由（詳細）

同上

### ゲームバージョン

1.5.X

### MOD有無

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
他と合わせて、読点ではなく、末尾の句点を消して1行に収めることにしました。
