### ISSUE TITLE
[不具合報告]国名が表示されない

### ISSUE THREAD

**Issue by akaitori1972** [matanki-saito/vic3jpadvmod#787]
### スクリーンショット

![vic3不具合画面](https://github.com/matanki-saito/vic3jpadvmod/assets/151358182/8797668d-4236-4492-8517-6552c0ff870a)

### 問題のあるインターフェイス

国名が表示される箇所すべて

### 問題のテキスト

COUNTRY_NAME

### 希望する変更

国名の表示

### 変更の理由（概要）

国名が表示されないため

### 変更の理由（詳細）

すべてのインターフェースで画面上に国名が表示されないため

### ゲームバージョン

1.5.X

### MOD有無

MODなし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
日本語改善Modはまだ最新版の『Victoria 3』に対応しておりません。
ご指摘の「国名が正しく表示されない」問題は承知しており、すでに解決策も判明しておりますので、今しばらくお待ちいただけますと幸いです。

**Comment by oooFUNooo** [comment]
Modのアップデートにより問題は解決しましたので、クローズさせていただきます。
