### ISSUE TITLE
企業の設立ツールチップ

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#788]
### スクリーンショット

![Victoria 3 Screenshot 2023 11 17 - 21 42 20 52](https://github.com/matanki-saito/vic3jpadvmod/assets/147261526/5c61a79b-e95d-46cb-b19f-7491b1725bbf)

### 問題のツールチップ

企業の設立ボタンマウスオーバー時のツールチップ

### 問題の表現

追加の企業を設立できますを設立します

### 問題箇所の英文

```CAN_ESTABLISH_ADDITIONAL_COMPANY: "We can establish additional $COMPANIES$"```

### 希望する変更

追加の企業を設立可能である

### 変更の理由（概要）

構文ミス

### 変更の理由（詳細）

CAN_ESTABLISH_ADDITIONAL_COMPANYの条件文だけを表示すれば良いと思われるが、なぜか後ろに「を設立します」という文章がくっついてしまっているので修正したい

### プレイ国家

アルゼンチン

### ゲームバージョン

1.5.X

### MOD有無

フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
議論の結果、対になるエントリも併せて以下のように修正することになりました。
```We can establish additional $COMPANIES$```　追加の$COMPANIES$が設立可能
```We cannot establish additional $COMPANIES$```　追加の$COMPANIES$は設立不可能

起票に感謝するとともに反映までお時間おかけして申し訳ありませんでした。
