### ISSUE TITLE
【修正提案】動員確認画面

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#79]
## スクリーンショット（必須）

![20221027205805_1](https://user-images.githubusercontent.com/42710893/198281940-3af70fce-fe0d-4cd9-8fb6-16f5a6ac61e9.jpg)

## 問題のあるインターフェイス（必須）

動員確認画面

## 問題のテキスト（必須）

・これは動員3将軍です
・現在、0将軍はすでに動員です
・現在の戦争がすべて集結するまで…

## 希望する変更（必須）

・これは動員**可能な**3将軍です
・現在、0将軍**が**すでに**動員済み**です
・現在の戦争がすべて**終結**するまで…

## 変更の理由（必須）

日本語として不自然なため、及び誤字の修正

## ゲームバージョン（必須）

1.0.3

## DLCの有無（必須）

なし

## MODの有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1035166556793085962
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by clamm0363** [comment]
以下のように修正しました。
> これにより、次の[数字]名の[将軍]が[動員]されます：
 [動員]される[大隊]は[アイコン+数字]です。
現在、[数字]名の[将軍]がすでに[動員]されています。
このアクションは、参戦中の戦争がすべて終結するまで取り消せません

クローズします。
