### ISSUE TITLE
編隊(Formation)の訳語変更

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#790]
### スクリーンショット

![formation_name](https://github.com/matanki-saito/vic3jpadvmod/assets/43299334/513b0ab6-321a-4c01-bedc-2b216ae91327)

### 問題の用語

編隊

### 英語版の表現

Formation

### 希望する変更

編制

### 変更の理由（概要）

ゲーム内の実態と乖離しているため

### 変更の理由（詳細）

「編隊」は航空機や艦船からなる集団をさすが、下記のようにFormationはもっと大きな概念であり、訳語としてふさわしくないため、「編制」を提案する。
解説：Formationは1.5から導入された概念で、軍事ユニットを収める箱であり、プレイヤーが操作できる軍事単位でもある。陸軍ではArmy、海軍ではFleetとそれぞれ呼び分けられる。
全てのユニットはFormationを通じて作成され、命令を受ける仕様になっているが、これと逆に、一つのユニットも含まない「空の」Formationも存在しうる。

### ゲームバージョン

1.5.X

### MOD有無

日本語改善MOD（仮対応）

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
編制で統一しました
