### ISSUE TITLE
海軍ユニット種別、軽巡洋艦と補助艦

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#792]
### スクリーンショット

<img width="272" alt="fleet2" src="https://github.com/matanki-saito/vic3jpadvmod/assets/43299334/38419571-ecec-4747-aeb2-f00586b40575">

### 問題の用語

軽巡洋艦、補助艦

### 英語版の表現

Light Ships/Support Vessels

### 希望する変更

軽量艦/支援艦

### 変更の理由（概要）

誤訳、より適切な訳への変更

### 変更の理由（詳細）

軽巡洋艦は誤訳。その前身であるScout Cruisersがゲームの最終ユニットであり、意訳としてもおかしい。
補助艦については支援艦としたほうが適当と思われる。

### ゲームバージョン

1.5.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。
