### ISSUE TITLE
偵察艦の修正

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#793]
### スクリーンショット

![scoutcruisers](https://github.com/matanki-saito/vic3jpadvmod/assets/43299334/0c5a0101-713d-4498-8128-59614fff28e1)

### 問題の固有名詞：希望する変更

Scout Cruisers;偵察艦/偵察巡洋艦

### 変更の理由（概要）

誤訳

### ゲームバージョン

1.5.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
偵察巡洋艦に修正しました
