### ISSUE TITLE
企業ウィンドウの「個の」

### ISSUE THREAD

**Issue by clamm0363** [matanki-saito/vic3jpadvmod#795]
### スクリーンショット

![bcf04d731572c7d124f88e9bb151794f](https://github.com/matanki-saito/vic3jpadvmod/assets/29382778/08fc1306-38bf-41fe-8c31-f52bcf06068b)

### 問題のあるインターフェイス

企業ウィンドウ

### 問題のテキスト

個の

### 希望する変更

「個の」を削除

### 変更の理由（概要）

不要であるため

### ゲームバージョン

1.5.X

### MOD有無

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
修正しました。クローズします
