### ISSUE TITLE
企業ウィンドウ「一流企業」

### ISSUE THREAD

**Issue by clamm0363** [matanki-saito/vic3jpadvmod#796]
### スクリーンショット

![bcf04d731572c7d124f88e9bb151794f](https://github.com/matanki-saito/vic3jpadvmod/assets/29382778/c9ec1fdc-c930-4a6d-967b-b3c30226bd2e)

### 問題の用語

一流企業

### 英語版の表現

Established Companies

### 希望する変更

設立済の企業

### 変更の理由（概要）

誤訳

### ゲームバージョン

1.5.X

### MOD有無

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
「設立済み企業」と修正しました。クローズします。
