### ISSUE TITLE
カウディーリョジャーナルの変数

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#797]
### スクリーンショット

![cd_ja](https://github.com/matanki-saito/vic3jpadvmod/assets/50406316/f8779c81-94e7-4eef-8714-14f8e19577c3)
![cd_en](https://github.com/matanki-saito/vic3jpadvmod/assets/50406316/9c9a4934-4e6e-418c-a51c-873c82471fb8)

### 問題部分

本文

### 問題のイベントタイトル

軍事独裁者の時代

### 問題のイベント本文（抜粋可）

政治的に同調していない

### 希望する変更（修正部分のみ）

軍部

### 変更の理由（概要）

変数のミス

### 変更の理由（詳細）

英語では「ig_armed_forces」となっている変数を日本語では「ig_armed_force」と間違えているため、軍部の名前が正しく読み込まれていない

### プレイ国家

南米諸国

### ゲームバージョン

1.5.X

### MOD有無

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
提案通り修正しました。
