### ISSUE TITLE
レンズ各項目の表記

### ISSUE THREAD

**Issue by clamm0363** [matanki-saito/vic3jpadvmod#798]
### スクリーンショット

![image](https://github.com/matanki-saito/vic3jpadvmod/assets/29382778/fced8415-50a8-46df-9e2c-1803cb3e9a64)
![image](https://github.com/matanki-saito/vic3jpadvmod/assets/29382778/023d0f14-c312-454a-9876-182234a2d20e)
![image](https://github.com/matanki-saito/vic3jpadvmod/assets/29382778/5c38f835-3b12-4f1e-9f50-be15a2d54275)

### 問題のあるインターフェイス

レンズアイコン

### 問題のテキスト

製法をリセットする
戦略的目標を指定
陸軍を作成
上陸作戦を計画
艦隊を作成

### 希望する変更

製法のリセット
戦略的目標の指定
陸軍の作成
上陸作戦の計画
艦隊の作成

### 変更の理由（概要）

これまでレンズでは一貫して「○○を△△」の表記を採用していないため

### ゲームバージョン

1.5.X

### MOD有無

日本語修正MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
修正しました。クローズします。
