### ISSUE TITLE
「アレキパの盟約」イベントタイトル

### ISSUE THREAD

**Issue by clamm0363** [matanki-saito/vic3jpadvmod#799]
### スクリーンショット

![image](https://github.com/matanki-saito/vic3jpadvmod/assets/29382778/932a33b2-208f-47cf-b7b7-9a873c589b5f)

### 問題部分

タイトル

### 問題のイベントタイトル

アレキパの盟約。

### 希望する変更（修正部分のみ）

アレキパの盟約

### 変更の理由（概要）

不要な句点が入っているため

### プレイ国家

ボリビア

### ゲームバージョン

1.5.X

### MOD有無

日本語修正MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
修正しました。クローズします。
