### ISSUE TITLE
政党名の固有名詞

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#80]
## 問題の固有名詞と希望する変更（必須）
ボリシェビキ党：ボリシェヴィキ党
イギリスファシスト連合：イギリス・ファシスト連合
シルバーレギオン：白銀軍団
文民党：市民党
国家文民同盟：国家市民同盟
国家戦線：国民戦線
ノルウェー国民連合：国民連合
全ロシアファシスト党：全ロシア・ファシスト党
スウェーデン民主連盟：スウェーデン民族同盟
国家統一党：国民連合
ズボール：ズボル
イラン-e-No党：新イラン党
全国社会キリスト教党：国家社会キリスト党
全国ファシスト党：国家ファシスト党
ギリシャ国家統一党：ギリシャ国民連合
ノルウェー右翼党：右翼党
デンマーク右翼党：右翼党
リベラル保守党：自由主義保守党
右派政党：右翼党
制憲連盟：制憲協会
奔放ヴェンスタ：ヴェンスタ自由思想家派
古ラントマンナ党：旧ラントマンナ党
リベラル民主：自由民主派
リベラルユニオン：自由主義連合
自由連合：自由連盟
全国リベラル党：国民自由党
帝国改革協会：保皇会
立憲改進党：立憲改革党
進歩ソサエティ：社会進歩派
自由合意党：自由調和党
グレートリベラル党：大自由党
ロシア民主労働党：カデット党
英国党：イングランド党
愛国統一党：愛国同盟
民族人民党：国家人民党
帝国氏族党：皇族党
帝道党：皇道党
ロシア全軍事統一党：ロシア全軍連合
進歩の相違：進歩異議派
社会リベラル党：社会自由党
自由発想民主連合：自由思想家民主同盟
急進リベラル党：急進自由党
奔放人民党：自由思想家人民党
メキシコリベラル党：メキシコ自由党
ポルトガルカトリックセンター：ポルドガル・カトリック中央
穏健ヴェンスタ：ヴェンスタ穏健派
ゼントルム：中央党
諸学会評議会：有識者評議会
ロシア人民統一党：ロシア人民同盟
無知党：ノウ・ナッシング党
保守派カトリック：カトリック保守派
伝統主義者コミュニオン：伝統主義コミュニオン
メンシェビキ党：メンシェヴィキ党
タイ民主党：民主党
社会主義労働者同盟：社会主義労働者連合
メキシコ労働党：労働者党
社会労働党：社会主義労働党
南軍社会主義者協会：連合国社会主義協会
農耕同盟：農業同盟
全国農民協定：全国農民合意
国家農耕連合：農業国民連合
小作農党：農民党
全国農民党：国家農民党
社会主義同盟：社会主義者同盟
イタリア労働組合：イタリア組合主義連合

## 変更の理由（必須）
日本語では一般的ではない表記であるため

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1035167899477876777
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by ChiefIdeologue** [comment]
修正内容にミスがあったため、再オープンしました。

立憲改進党：立憲改革党
上記は日本固有の政党名であり、元の訳が正しかったです。

**Comment by ChiefIdeologue** [comment]
ミスした修正内容の修正が完了したため、クローズしました。
