### ISSUE TITLE
駐在の訳語変更

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#805]
### スクリーンショット

![tyuuryuu](https://github.com/matanki-saito/vic3jpadvmod/assets/43299334/82662268-f27f-44ed-a68c-c528e8bad9f3)

### 問題の用語

駐在

### 英語版の表現

Stationed

### 希望する変更

駐留

### 変更の理由（概要）

駐在は一般に個人の在留を表し、軍隊の場合は駐留が相応しい

### 変更の理由（詳細）

軍や艦隊がある場所に留まること。ゲーム内では一時的な在留だけでなく、本拠にとどまることもさす。

### ゲームバージョン

1.5.X

### MOD有無

日本語改善MOD,フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
駐留に修正しました
