### ISSUE TITLE
現地価格のツールチップ

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#806]
### スクリーンショット

![price_ja](https://github.com/matanki-saito/vic3jpadvmod/assets/50406316/0c0626e5-abf3-4788-a763-9c267eaf60e6)
![price_en](https://github.com/matanki-saito/vic3jpadvmod/assets/50406316/574508fd-0927-4e7f-ab5b-de5bf7324238)

### 問題のツールチップ

現地価格ツールチップの価格設定の文章

### 問題の表現

```
PRICE_SETTING_INFO: "#title 価格設定#!\n[Goods.GetState.GetName]における $PRODUCTION$ と $CONSUMPTION$ から[SelectLocalization(GreaterThan_CFixedPoint(Goods.GetMarketPriceShare, '(CFixedPoint)0'), 'MARKET_PRICE_SHARE_DESC', '')][Goods.GetLocalPriceShare|%v0]\n[SelectLocalization(Goods.IsLocal,'','GOODS_LOCAL_PRICE_DIFF')]\n"
 MARKET_PRICE_SHARE_DESC: "#tooltippable #tooltip:[Goods.GetTooltipTag],GOODS_MARKET_PRICE_SHARE_TOOLTIP [Goods.GetMarket.GetName])にある[concept_market_price] ([Goods.GetMarketPriceWithTooltip]から[Goods.GetMarketPriceShare|%v0]#!#! \n"
MARKET_PRICE_SHARE_DESC: "#tooltippable #tooltip:[Goods.GetTooltipTag],GOODS_MARKET_PRICE_SHARE_TOOLTIP [Goods.GetMarket.GetName])にある[concept_market_price] ([Goods.GetMarketPriceWithTooltip]から[Goods.GetMarketPriceShare|%v0]#!#! \n"
```

### 問題箇所の英文

上記の画像参照

### 希望する変更

以下画像参照
![proposal](https://github.com/matanki-saito/vic3jpadvmod/assets/50406316/7e0fe5cd-064e-49b4-93b3-b2e610c4358e)

### 変更の理由（概要）

変数を考慮した文章になっていないため

### 変更の理由（詳細）

変数を考慮した文章になっていないため、正しい構文に修正。
75%/25%の数字は、他と合わせるために先頭に置くことにする

### プレイ国家

どこでも

### ゲームバージョン

1.5.X

### MOD有無

翻訳改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
修正提案の画像がうまく貼れていないので再度
![proposal](https://github.com/matanki-saito/vic3jpadvmod/assets/50406316/5b6a8c0b-bb40-43be-8f21-3f3552f91434)

**Comment by starjard** [comment]
提案通り修正しました。
