### ISSUE TITLE
compared toが未翻訳

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#807]
### スクリーンショット

![untranslated](https://github.com/matanki-saito/vic3jpadvmod/assets/50406316/aad07d41-2fd3-435d-8f34-86cb7e392e63)

### 問題のあるインターフェイス

市場価格のツールチップ等

### 問題のテキスト

compared to

### 希望する変更

と比較して

### 変更の理由（概要）

未訳であるため

### 変更の理由（詳細）

複数エントリで「compared to」が未訳である箇所が存在するため修正。他のcompared toが「と比較して」とされているので合わせる。

### ゲームバージョン

1.5.X

### MOD有無

翻訳改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
提案通り修正しました。
