### ISSUE TITLE
【修正提案】州画面概要タブ、インフラ等の使用状況

### ISSUE THREAD

**Issue by wakkunteitoku** [matanki-saito/vic3jpadvmod#81]
## スクリーンショット（必須）

![20221027205655_1](https://user-images.githubusercontent.com/42710893/198284219-f13fef98-96b3-4d95-91ad-4d348012939c.jpg)

## 問題のあるインターフェイス（必須）

州画面の概要タブ

## 問題のテキスト（必須）

2の2を使用中です

## 希望する変更（必須）

2のうち2を使用中です　等

## 変更の理由（必須）

日本語として不自然なため。

## ゲームバージョン（必須）

1.0.3

## DLCの有無（必須）

なし

## MODの有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1035168725931925544
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by inarizushi0309** [comment]
![image](https://user-images.githubusercontent.com/37979626/199233492-8ce77f8c-962a-42b3-9366-59a41a49f897.png)
横幅がそんなにない場所に表示させることを考慮し、このように修正しました。起票ありがとうございました。

**Comment by inarizushi0309** [comment]
修正したエントリ
STATE_INFRASTRUCTURE_CONDENSED
STATE_TAX_CAPACITY_CONDENSED

**Comment by WoodlandsGitHub** [comment]
![image](https://user-images.githubusercontent.com/29177147/199501064-efceb69b-17d9-4589-9f74-4f6c71d90949.png)
課税キャパシティの方ですが、超過した際に崩れてしまっています。確認をお願いします。

**Comment by inarizushi0309** [comment]
> ![image](https://user-images.githubusercontent.com/29177147/199501064-efceb69b-17d9-4589-9f74-4f6c71d90949.png) 課税キャパシティの方ですが、超過した際に崩れてしまっています。確認をお願いします。

確認しました。修正いたしました。ご報告ありがとうございます。
