### ISSUE TITLE
上陸作戦ウィンドウのタイトル

### ISSUE THREAD

**Issue by clamm0363** [matanki-saito/vic3jpadvmod#810]
### スクリーンショット

![image](https://github.com/matanki-saito/vic3jpadvmod/assets/29382778/7f77db2b-e704-47e0-9dbd-dca7a9b5d825)

### 問題のあるインターフェイス

上陸作戦ウィンドウ

### 問題のテキスト

上陸作戦[地名]で

### 希望する変更

[地名]上陸作戦

### 変更の理由（概要）

不要な「で」の削除と不自然な語順の修正

### ゲームバージョン

1.5.X

### MOD有無

日本語修正MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
修正案通り修正しました。クローズします。
