### ISSUE TITLE
(役職)of(国名)

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#811]
### スクリーンショット

![of](https://github.com/matanki-saito/vic3jpadvmod/assets/50406316/aa8abd35-cf56-495c-9d20-104b3d09be89)

### 問題のあるインターフェイス

人物の役職欄

### 問題のテキスト

国王ofフランス

### 希望する変更

フランスの国王

### 変更の理由（概要）

未訳のため

### 変更の理由（詳細）

未訳のため

### ゲームバージョン

1.5.X

### MOD有無

翻訳改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
提案通り修正しました。
