### ISSUE TITLE
貿易ルート廃止フィード

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#812]
### スクリーンショット

![Victoria 3 Screenshot 2023 11 23 - 20 11 45 36](https://github.com/matanki-saito/vic3jpadvmod/assets/147261526/3e26910c-f858-4043-bb4f-8b2ba88cf5b3)

### 問題のあるインターフェイス

貿易ルート廃止フィード

### 問題のテキスト

[国旗1][国名1]に到達可能な港がないため、[市場名]に至る[国旗2]の[商品アイコン][商品名]貿易ルートが削除されました。

### 希望する変更

[国旗1][国名1]に到達可能な港がないため、[市場名]に至る[国旗2][国名2]の[商品アイコン][商品名]貿易ルートが削除されました。

### 変更の理由（概要）

対象国がわかりにくいため

### 変更の理由（詳細）

相手国の部分について国旗のみが表示され、国名が表示されないのでどこの国との貿易ルートが廃止されたのかがわかりにくい。

### ゲームバージョン

1.5.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
![image](https://github.com/matanki-saito/vic3jpadvmod/assets/29382778/b7dc34f6-f415-4095-97ad-bf3a22a8da48)
文言を少し修正し、国名が表示されるように修正しました。クローズします。
