### ISSUE TITLE
人口タブ：POPの説明ツールチップ（資本家）

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#813]
### スクリーンショット

![Victoria 3 Screenshot 2023 11 24 - 17 45 05 85](https://github.com/matanki-saito/vic3jpadvmod/assets/147261526/3f01e43d-28ad-4b5b-b47a-f774108b4f83)

### 問題のツールチップ

人口タブ：POPの説明ツールチップ（資本家）

### 問題の表現

```CAPITALISTS_QUALIFICATIONS_DESC: "十分な[concept_wealth]を持つPOPだけが #v $capitalists$#! になれます。[concept_literacy]と[concept_wealth]と[concept_literacy]が大きいほど、その可能性は高まります。[concept_culture]が[concept_discrimination]に直面しているPOPは、より長い時間がかかります。 #v $shopkeepers$#! と #v $engineers$#! は、特に簡単に #v $capitalists$#! になれます。"```

### 問題箇所の英文

```CAPITALISTS_QUALIFICATIONS_DESC:0 "Only pops with adequate [concept_wealth] can become #v $capitalists$#!. Potential increases with greater [concept_wealth] and [concept_literacy]. Pops whose [concept_culture] faces [concept_discrimination] take a much longer time. #v $shopkeepers$#! and #v $engineers$#! have a particularly easy time becoming #v $capitalists$#!."```

### 希望する変更

```CAPITALISTS_QUALIFICATIONS_DESC: "十分な[concept_wealth]を持つPOPだけが #v $capitalists$#! になれます。[concept_literacy]と[concept_wealth]が大きいほど、その可能性は高まります。[concept_culture]が[concept_discrimination]されているPOPは、より長い時間がかかります。 #v $shopkeepers$#! と #v $engineers$#! は、特に簡単に #v $capitalists$#! になれます。"```

### 変更の理由（概要）

余計な変数が入っている、他

### 変更の理由（詳細）

2文目の[concept_literacy]が一つ余計です。

3文目は「差別に直面している」よりは「差別されている」の方が自然と思われます。
※これについては、聖職者・公務員・学者・貴族の説明文でも同様の記述があるので修正する場合は統一したほうが良いと思います

### プレイ国家

アルゼンチン

### ゲームバージョン

1.5.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
若干の修正を加えましたが、おおむねご提案通りに修正しました。クローズします。
