### ISSUE TITLE
大国の説明文

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#815]
### スクリーンショット

![Victoria 3 Screenshot 2023 11 26 - 00 46 39 04](https://github.com/matanki-saito/vic3jpadvmod/assets/147261526/ee971aab-35f2-4549-967d-afc2ce24b329)

### 問題のあるインターフェイス

大国の説明文

### 問題のテキスト

～地位を獲得することを臨んでいるかもしれません。

### 希望する変更

～地位を獲得することを望んでいるかもしれません。

### 変更の理由（概要）

誤字の修正

### ゲームバージョン

1.5.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。
