### ISSUE TITLE
医師の指示

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#817]
### スクリーンショット

![20231125215803_1](https://github.com/matanki-saito/vic3jpadvmod/assets/42687608/9e6f642a-b637-4ae5-b650-d73ced3e8c1c)

### 問題部分

本文

### 問題のイベントタイトル

医師の指示

### 問題のイベント本文（抜粋可）

痘のような病気

### 希望する変更（修正部分のみ）

天然痘のような病気

### 変更の理由（概要）

日本語では一般的でない表記であるため

### 変更の理由（詳細）

原文は「the pox」。辞書でpoxの意味を調べると水疱性疾患全般を指すとある。
一方、日本語の「痘」を検索しても天然痘以外の用例が見当たらず、「痘」単独で使われる例もほとんど見られない。
イベントの文脈上、このpoxは天然痘を指すと考えられるため、日本語として自然な「天然痘」に改める。

### プレイ国家

パラグアイ

### ゲームバージョン

1.5.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
diseases like the poxについて「天然痘をはじめとする種々の病」と翻訳する修正を行いました。クローズします。
