### ISSUE TITLE
艦隊の存在感の訳語

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#818]
### スクリーンショット

![sonzaikan](https://github.com/matanki-saito/vic3jpadvmod/assets/43299334/efae324c-c6d0-4030-8ff7-aa52ec14936c)

### 問題の用語

存在感

### 英語版の表現

Presence

### 希望する変更

展開度

### 変更の理由（概要）

実際のゲームメカニズムとかけ離れた用語のため

### 変更の理由（詳細）

艦隊を海上ノードに駐留させた後、動かさないでいると徐々に上昇していく値。
艦隊の作戦効率に影響する様だが具体的なメカニクスは不明。
ツールチップの文章も誤訳であり、同時に修正したい。
修正案：提督が命令をどれほど効率的に遂行できるかは、展開度によって決まります。艦隊が海上ノードに駐留していれば、展開度は時間とともに上昇していきます。

### ゲームバージョン

1.5.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
展開度で修正しました
