### ISSUE TITLE
アウトライナー「活動していない」

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#819]
### スクリーンショット

![20231126134711_1](https://github.com/matanki-saito/vic3jpadvmod/assets/42687608/c49137ba-3dff-4897-8c8e-af7efb1e76fc)

### 問題のあるインターフェイス

アウトライナー

### 問題のテキスト

活動していない

### 希望する変更

なし

### 変更の理由（概要）

誤訳のため

### 変更の理由（詳細）

原文は「None Active」で「現在有効なジャーナル記事が存在しない」の意。
長文で翻訳するとインターフェイス上見切れてしまうため、短めに訳す必要がある。

### ゲームバージョン

1.5.X

### MOD有無

フォント変更Mod

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
提案の通り修正しました。クローズします。
