### ISSUE TITLE
【修正提案】フリゲート艦の護衛　Escort Frigates

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#82]
## スクリーンショット（任意）
![image](https://user-images.githubusercontent.com/37979626/198286277-62155d1f-d5d6-4942-994b-9f579695a107.png)

## 問題の固有名詞（必須）

フリゲート艦の護衛

## 希望する変更（必須）

護衛フリゲート艦

## 変更の理由（必須）

船の種類を指しているため

## ゲームバージョン（必須）

1.0.1

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1035170614262120509
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by matanki-saito** [comment]
他のissueで「艦」でそろえた方がおさまりが良いという意見がありましたが、ないほうが良いですかね？

**Comment by matanki-saito** [comment]
フリゲートはなくてもいい気がしますね。「デストロイヤー艦」のようなものなので不自然さがあります

**Comment by matanki-saito** [comment]
良い例えありがとうございます。「護衛フリゲート」でもう1日待って異論なければ確定とします
