### ISSUE TITLE
〇〇東インド会社／〇〇領東インド（国名の使い分け）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#820]
### スクリーンショット

![20231126140422_1](https://github.com/matanki-saito/vic3jpadvmod/assets/42687608/6b7bea1d-751d-4fcf-9b79-e477fbcda8e7)
![20231126140433_1](https://github.com/matanki-saito/vic3jpadvmod/assets/42687608/56820572-1341-4444-a6b7-4a83c1ed045b)

### 問題のあるインターフェイス

国名全般

### 問題のテキスト

〇〇 東インド会社 ……「イギリス 東インド会社」等
〇〇 （植民地名） ……「オランダ 東インド諸島」等

### 希望する変更

〇〇東インド会社　 ……「イギリス東インド会社」等
〇〇領（植民地名） ……「オランダ領東インド」等
```
COUNTRY_NAME: "[SelectLocalization( EqualTo_string( '$PREFIX$', '' ), '$NAME$', Concatenate( SelectLocalization( EqualTo_string( '$NAME$', '$dyn_c_east_india_company$' ), '$PREFIX$', '$PREFIX$領' ), '$NAME$' ) )]"
COUNTRY_ADJECTIVE: "[SelectLocalization( EqualTo_string( '$PREFIX$', '' ), '$ADJECTIVE$', Concatenate( SelectLocalization( EqualTo_string( '$ADJECTIVE$', '$dyn_c_east_india_company_adj$' ), '$PREFIX$', '$PREFIX$領' ), '$ADJECTIVE$' ) )]"
```

### 変更の理由（概要）

日本語では一般的でない表記であるため

### 変更の理由（詳細）

植民地国家の表記としては、国名と植民地名（東インド等）を「領」でつなぐのが日本語として一般的である。
ただし、植民地名が「東インド会社」の場合は慣例として「領」を省く必要がある。
そこで、植民地国家の名前を定義している部分を調整することにより、上の出し分けを実現する。
同時に、国名と植民地名の間にある不要な半角スペースを削除し、「東インド諸島」は定訳である「東インド」に変更する。

### ゲームバージョン

1.5.X

### MOD有無

フォント変更Mod

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
提案の通り修正しました。クローズします。
