### ISSUE TITLE
軍事ウィンドウの「引き上げ」

### ISSUE THREAD

**Issue by clamm0363** [matanki-saito/vic3jpadvmod#822]
### スクリーンショット

![image](https://github.com/matanki-saito/vic3jpadvmod/assets/29382778/ad5bcaed-ee80-41fd-80bf-b00351ea488c)

### 問題のあるインターフェイス

軍事ウィンドウ

### 問題のテキスト

```@conscripts![MilitaryFormation.GetMaxConscripts|v] [Concept('concept_conscript_battalion','$concept_conscript_battalions_short$')]を引き上げ```

### 希望する変更

[数値]徴兵大隊を動員

### 変更の理由（概要）

「引き上げ」が徴兵大隊の動員の意味で読めないため

### ゲームバージョン

1.5.X

### MOD有無

日本語修正MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
「[数値]個[徴兵]大隊を動員」と表示されるように修正しました。クローズします。
