### ISSUE TITLE
飢餓への自由

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#824]
### スクリーンショット

![20231127154754_1](https://github.com/matanki-saito/vic3jpadvmod/assets/42687608/79b081e0-b5ff-4492-bddc-e9565f296ce0)

### 問題部分

タイトル

### 問題のイベントタイトル

飢餓への自由

### 希望する変更（修正部分のみ）

餓死の自由

### 変更の理由（概要）

日本語として自然な表現に変更

### 変更の理由（詳細）

原文は「Freedom to Starve」で、本文の Freedom of trade, freedom of the markets（貿易の自由、市場の自由）と対比する内容になっているが、公式訳ではそのニュアンスが伝わりにくい。
直訳すれば「飢える自由」となるが、「〇〇の自由」で統一するため「餓死の自由」を提案する。

### プレイ国家

パラグアイ

### ゲームバージョン

1.5.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
原案の通り修正しました。クローズします。
