### ISSUE TITLE
「パラグアイの国」イベントの選択肢ツールチップ

### ISSUE THREAD

**Issue by clamm0363** [matanki-saito/vic3jpadvmod#826]
### スクリーンショット

![image](https://github.com/matanki-saito/vic3jpadvmod/assets/29382778/276f09d1-c0e2-4555-af08-7b75692937e7)

### 問題部分

選択肢

### 問題のイベントタイトル

```[SCOPE.sCulture('new_national_culture').GetName]の国```

### 問題のイベント本文（抜粋可）

```いたるところで人々は自分たちの[SCOPE.sCulture('new_national_culture').GetName]の故郷のことを口にする。[SCOPE.sCulture('old_national_culture').GetName]のアイデンティティはもうない。```

### 問題のイベント選択肢

```この国のすべての[SCOPE.sCulture('old_national_culture').GetName][concept_pop]は[SCOPE.sCulture('new_national_culture').GetName]を取り入れる```

### 希望する変更（修正部分のみ）

この国のすべての[旧文化][POP]は[新文化]に[同化]する

### 変更の理由（概要）

公式翻訳がコンセプト「同化」を呼ぶ変数を削っており、実際の効果が分かりにくいため

### プレイ国家

パラグアイ

### ゲームバージョン

1.5.X

### MOD有無

日本語修正MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
修正しました。クローズします。
