### ISSUE TITLE
南部の巨像（DLCタイトル）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#827]
### スクリーンショット

![20231129141709_1](https://github.com/matanki-saito/vic3jpadvmod/assets/42687608/98d05977-083c-4a63-945a-5184b78d590e)

### 問題のあるインターフェイス

タイトル画面左下のDLCツールチップ

### 問題のテキスト

南部の巨像

### 希望する変更

Colossus of the South

### 変更の理由（概要）

統一性を確保するため

### 変更の理由（詳細）

同じ画面に表示される他のDLCはすべて英語表記となっており、Steamストアページの商品名も英語表記である。
したがって、統一性の観点からも、商標としての観点からも、DLCのタイトルは英語表記とするのが望ましい。

### ゲームバージョン

1.5.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
原案の通り修正しました。以後、同様のDLC名表記があった場合も同じく修正します。
