### ISSUE TITLE
戦闘状況補正「追跡」ツールチップ

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#829]
### スクリーンショット

![Victoria 3 Screenshot 2023 11 29 - 22 33 48 81](https://github.com/matanki-saito/vic3jpadvmod/assets/147261526/97402769-33a5-4a84-86f1-18426e9ef65a)

### 問題のツールチップ

戦闘状況補正「追跡」ツールチップ

### 問題の表現

圧倒的な数的優位のため、指揮官は敵の包囲し～

### 希望する変更

圧倒的な数的優位のため、指揮官は敵を包囲し～

### 変更の理由（概要）

日本語として不自然なため

### プレイ国家

エジプト

### ゲームバージョン

1.5.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。
