### ISSUE TITLE
清のIG特性名

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#831]
### スクリーンショット

![qing_army](https://github.com/matanki-saito/vic3jpadvmod/assets/50406316/7ee5257a-2c19-44db-80e0-aa2b6738f44e)

### 問題の用語

新設軍/自己強化

### 英語版の表現

Newly-Created Army/Self-Strengthening

### 希望する変更

新建陸軍/自強

### 変更の理由（概要）

史実の用語に準拠したい

### 変更の理由（詳細）

Newly-Created Army/Self-Strengtheningはそれぞれ中国語の新建陸軍/自強のこと。
中国語による史実の漢字表記があるため、和訳でもそれに準拠したい。

※参考
Newly-Created Army（新建陸軍）
https://zh.wikipedia.org/wiki/%E6%96%B0%E8%BB%8D

Self-Strengthening（自強）
https://zh.wikipedia.org/wiki/%E6%B4%8B%E5%8A%A1%E8%BF%90%E5%8A%A8
（movementが入っていないため、自強運動ではなく単に自強としました）

### ゲームバージョン

1.5.X

### MOD有無

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
提案通り修正しました。
