### ISSUE TITLE
輸送船団襲撃フィードの「輸送船団レイダー」

### ISSUE THREAD

**Issue by clamm0363** [matanki-saito/vic3jpadvmod#833]
### スクリーンショット

![image](https://github.com/matanki-saito/vic3jpadvmod/assets/29382778/b09daf20-aac5-47f7-b81b-5586eada50f2)

### 問題のあるインターフェイス

輸送船団襲撃フィード

### 問題のテキスト

我々の輸送船団レイダーが西カリブ海にて、10の敵輸送船団を破壊しました。

輸送船団の損失を軽減できる護衛海軍が存在しませんでした。

### 希望する変更

西カリブ海にて、我々の船団襲撃により10隻の敵輸送船団を撃沈しました。

輸送船団の損失を軽減できる護衛船団は存在しませんでした。

### 変更の理由（概要）

一般的な用語ではないため

### ゲームバージョン

1.5.X

### MOD有無

日本語修正MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
修正しました。クローズします。
