### ISSUE TITLE
IG・リーダーイデオロギー名の修正

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#834]
### スクリーンショット

なし

### 問題の固有名詞：希望する変更

東洋正教会家父長主義：東方諸教会家父長主義
神の崇拝者：拝上帝会
バロニアル：貴族主義
ジャクソン流民主主義：ジャクソン流民主主義者
啓蒙専制君主：啓蒙王党派

### 変更の理由（概要）

誤訳の修正

### 変更の理由（詳細）

バロニアル除いて誤訳である、バロニアルは1.5でPontificalからBaronialへと原文が変更された。
Pontificalは元々は司教主義と訳されていたが、後にMODで教皇主義に修正された。

Baronialは「貴族風・貴族的」の様なニュアンスを持っているが、このイデオロギーを持つのは教皇領であるため貴族は存在せず、微妙な訳だと感じるため他の案も考えたい。

### ゲームバージョン

1.5.X

### MOD有無

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
バロニアルは議論の結果「男爵」になりました。
以上の修正が完了したため、クローズしました。
