### ISSUE TITLE
連邦（Polish–Lithuanian Commonwealth）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#836]
### スクリーンショット

![20231202191822_1](https://github.com/matanki-saito/vic3jpadvmod/assets/42687608/47a1bc76-ab65-45e5-86d0-922daa7b5c41)

### 問題の固有名詞：希望する変更

連邦：コモンウェルス

### 変更の理由（概要）

日本語では一般的でない表記であるため

### 変更の理由（詳細）

スクリーンショットの「英連邦」は文脈上「ポーランド・リトアニア共和国」（Polish–Lithuanian Commonwealth）のことであり、完全な誤訳である。
他にも、ポーランド・リトアニア共和国を指すCommonwealthが多数「連邦」と翻訳されているため、これを一括して修正したい。
他のParadox作品では従来ポーランド・リトアニア共和国を「コモンウェルス」と翻訳してきたため、これに準じることを提案する。

### ゲームバージョン

1.5.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
議論の結果、ポーランド・リトアニア共和国を表すCommonwealthについては、英連邦と紛らわしい「コモンウェルス」ではなく、歴史用語として使用される「ジェチュポスポリタ」と翻訳することに決まりました。

**Comment by oooFUNooo** [comment]
「Polish-Lithuanian Commonwealth」「Commonwealth of Polish-Lithuania」という表現が見つかったため、議論を再オープンします。

**Comment by oooFUNooo** [comment]
議論の結果、上記の2つの表現を「ポーランド・リトアニア共和国」に再修正しました。
