### ISSUE TITLE
【修正提案】魚雷ボート　Torpedo Boats

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#84]
## スクリーンショット（任意）
![image](https://user-images.githubusercontent.com/37979626/198297545-761cfd55-8a9d-4de4-aa5e-2ee3932c4b6a.png)

## 問題の固有名詞（必須）

魚雷ボート

## 希望する変更（必須）

水雷艇

## 変更の理由（必須）

https://ja.wikipedia.org/wiki/%E6%B0%B4%E9%9B%B7%E8%89%87

## ゲームバージョン（必須）

1.0.1

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1035183208255467540
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。
