### ISSUE TITLE
【表記変更】年齢条件の表記

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#840]
### スクリーンショット

![image](https://github.com/matanki-saito/vic3jpadvmod/assets/37979626/4451fbc6-b1d2-43ce-8c9f-5cd0e3e7a420)

### 問題のツールチップ

政府画面>指導者3Dモデル左上「○○と交流する」

### 問題の表現

ニコライ・ロマノフの年齢が75以上
```[CHARACTER.GetFullNamePossessive]の年齢が$NUM|v$$COMPARATOR$```
```[CHARACTER.GetFullNamePossessive]の年齢が$NUM|v$$COMPARATOR$#bold ではない#!```

### 問題箇所の英文

```[CHARACTER.GetFullNamePossessive] age is $COMPARATOR$ $NUM|v$```
```[CHARACTER.GetFullNamePossessive] age is #bold not #!$COMPARATOR$ $NUM|v$```

### 希望する変更

ニコライ・ロマノフが75歳以上
```[CHARACTER.GetFullNamePossessive]が$NUM|v$歳$COMPARATOR$```
```[CHARACTER.GetFullNamePossessive]が$NUM|v$歳$COMPARATOR$#bold ではない#!```

### 変更の理由（概要）

日本語として自然な表現にするため

### 変更の理由（詳細）

単位を補うだけでもいいが、「歳」＝年齢と分かることから「年齢」を無くした方がよりスマートな表現になるかと

### プレイ国家

ロシア

### ゲームバージョン

1.5.X

### MOD有無

日本語mod

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通りで確定します。
