### ISSUE TITLE
上陸作戦ツールチップ「上陸作戦が実施されたされています」

### ISSUE THREAD

**Issue by clamm0363** [matanki-saito/vic3jpadvmod#844]
### スクリーンショット

![image](https://github.com/matanki-saito/vic3jpadvmod/assets/29382778/37516898-1fee-4e05-9770-ede68702a628)

### 問題のツールチップ

上陸作戦ツールチップ

### 問題の表現

現在、シェランのプロイセンによって上陸作戦が実施されたされています。

### 問題箇所の英文

```You are currently being [Concept('concept_naval_invasion','$concept_naval_invaded$')] by [SCOPE.GetRootScope.GetNavalInvasion.GetInvaderCountry.GetName] in [SCOPE.GetRootScope.GetNavalInvasion.GetEnemyState.GetName].```

### 希望する変更

現在、シェランにおいてプロイセンによる上陸作戦が行われています。

### 変更の理由（概要）

変数の取扱いが誤っているため

### プレイ国家

プロイセン

### ゲームバージョン

1.5.X

### MOD有無

日本語修正MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
修正しました。クローズします。
