### ISSUE TITLE
アレクサンドル・ロマノフ即位時のツールチップ

### ISSUE THREAD

**Issue by clamm0363** [matanki-saito/vic3jpadvmod#845]
### スクリーンショット

![image](https://github.com/matanki-saito/vic3jpadvmod/assets/29382778/d783e336-bfb7-4312-b109-b0aa1c1c64a2)

### 問題のツールチップ

アレクサンドル・ロマノフ即位時のツールチップ

### 問題の表現

市場リベラルのキャラクターがアレクサンドル・ロマノフが統治している間、ロシアに出現しやすくなる。

### 問題箇所の英文

```Market Liberal characters will be more likely to appear in [SCOPE.sCountry('russia_scope').GetName] for the duration of [SCOPE.sCharacter('tsar_scope').GetFullName]'s reign```

### 希望する変更

```[SCOPE.sCharacter('tsar_scope').GetFullName]の統治期間中、[SCOPE.sCountry('russia_scope').GetName]に市場自由主義者のキャラクターが登場しやすくなります。```

### 変更の理由（概要）

イデオロギー名と一貫性を得るため

### プレイ国家

ロシア

### ゲームバージョン

1.5.X

### MOD有無

日本語修正MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
修正しました。クローズします。
