### ISSUE TITLE
追跡（戦闘状況）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#846]
### スクリーンショット

![20231210083522_1](https://github.com/matanki-saito/vic3jpadvmod/assets/42687608/34c79c9d-32a6-420f-acc5-bc79b90dfae9)

### 問題のあるインターフェイス

戦闘状況ウィンドウ

### 問題のテキスト

追跡

### 希望する変更

追撃

### 変更の理由（概要）

日本語として自然な表現に変更

### 変更の理由（詳細）

原文はPursuit
誤訳ではないが、戦闘結果なので「追撃」とする方が自然である

### ゲームバージョン

1.5.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
原案の通り修正しました。クローズします。
