### ISSUE TITLE
Rank、Power Rank、Tier

### ISSUE THREAD

**Issue by clamm0363** [matanki-saito/vic3jpadvmod#847]
### スクリーンショット

![image](https://github.com/matanki-saito/vic3jpadvmod/assets/29382778/3d9e35f7-b808-42f1-9944-081a75a3c3ac)
![image](https://github.com/matanki-saito/vic3jpadvmod/assets/29382778/261c43b3-6b70-4027-9be7-325938bc7cfc)
![image](https://github.com/matanki-saito/vic3jpadvmod/assets/29382778/9d2b4c1e-af98-463d-a9f3-ea7d7f4912ce)

### 問題の用語

ランク、戦力ランク、パワーランク、ティア、国のティア

### 英語版の表現

Rank, Power Rank, Tier, Country Tier

### 希望する変更

未定

### 変更の理由（概要）

用語不統一、また似たような単語で違う意味で定義されているため

### ゲームバージョン

1.5.X

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。
