### ISSUE TITLE
長い行でツールチップが表示されない問題

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#849]
### スクリーンショット

![ja](https://github.com/matanki-saito/vic3jpadvmod/assets/50406316/9a69113e-7c91-43d1-8718-b43e651d19c8)
![en](https://github.com/matanki-saito/vic3jpadvmod/assets/50406316/b85220ef-dca8-4420-b041-9756bb4102c6)

### 問題のツールチップ

投資プール再投資額の内訳ツールチップ

### 問題の表現

上記画像のように、日本語環境では下に1行で収まりきらないテキストがあるとツールチップのポップアップが表示されない。
このツールチップに限らず、同種の問題を包括的に処理するissueとする。

### 問題箇所の英文

上記画像

### 希望する変更

画像参照
![proposal](https://github.com/matanki-saito/vic3jpadvmod/assets/50406316/37547925-e1aa-40a5-8103-25e84c3a9cbf)

### 変更の理由（概要）

ポップアップを表示させるために改行

### 変更の理由（詳細）

上記画像のように、1行で収まらない場合は途中で文章を切り、複数行に改行して枠内に収まるようにする。

### プレイ国家

どこでも

### ゲームバージョン

1.5.X

### MOD有無

翻訳改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
提案通り修正しました。加えて、日本語で表示する場合の不具合としてParadoxに報告予定です。
