### ISSUE TITLE
【修正提案】教化ミッション

### ISSUE THREAD

**Issue by saarland68** [matanki-saito/vic3jpadvmod#85]
## スクリーンショット（任意）
![image](https://user-images.githubusercontent.com/70930137/198306961-0f9fa5d5-8676-40bc-aad2-500ef959365e.png)

## 問題の固有名詞（必須）

教化ミッション
## 希望する変更（必須）

文明化の使命
## 変更の理由（必須）
https://en.wikipedia.org/wiki/Civilizing_mission
## ゲームバージョン（必須）

1.0.1

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1035192635842908221
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by saarland68** [comment]
修正しました
「教化ミッション」→「文明化の使命」

**Comment by saarland68** [comment]
この起票は閉じます
