### ISSUE TITLE
国名：アンコール（Ankole）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#850]
### スクリーンショット

![20231217230255_1](https://github.com/matanki-saito/vic3jpadvmod/assets/42687608/a6356fae-5802-4836-acc2-acacc6c22481)

### 問題の固有名詞：希望する変更

アンコール：アンコーレ

### 変更の理由（概要）

日本語では一般的でない表記であるため

### 変更の理由（詳細）

ウィキペディアの記述では「アンコーレ」または「ンコレ」とあり、語尾を「ル」と読むのは正しくない可能性がある。
また、学術論文には「アンコレ」と表記しているものも見られる。

### ゲームバージョン

1.5.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
議論の結果、アンコーレに修正しました。クローズします。
