### ISSUE TITLE
◯◯のインフルエンザ（スペイン風邪）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#852]
### スクリーンショット

![20231222202516_1](https://github.com/matanki-saito/vic3jpadvmod/assets/42687608/bcfe8d96-5a02-4385-93c9-9236a41e07e7)

### 問題部分

タイトル

### 問題のイベントタイトル

（国名）のインフルエンザ

### 希望する変更（修正部分のみ）

（国名）風邪

### 変更の理由（概要）

日本語では一般的でない表記であるため

### 変更の理由（詳細）

このイベントは歴史上の「スペイン風邪」（Spanish Flu）のパロディであり、fluをインフルエンザと訳すとパロディであることがプレイヤーに伝わらなくなるため。
イベント本文中でも大流行そのものへの言及がある場合は「〇〇風邪」へ修正する。

### プレイ国家

クラクフ

### ゲームバージョン

1.5.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
原案の通り修正しました。クローズします。
