### ISSUE TITLE
外交タブ：態度のツールチップ

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#853]
### スクリーンショット

![Victoria 3 Screenshot 2023 12 26 - 22 57 37 68](https://github.com/matanki-saito/vic3jpadvmod/assets/147261526/5c39c4f4-3c49-4ad4-8e41-1ea882e9a47c)
![Victoria 3 Screenshot 2023 12 26 - 22 57 54 04](https://github.com/matanki-saito/vic3jpadvmod/assets/147261526/e8e5de8a-6a0a-4180-9f70-7b194968a77b)

### 問題のツールチップ

外交タブ：態度のツールチップ

### 問題の表現

（1枚目の画像）〇〇は△△の悪名を驚異に感じています
（2枚目の画像）〇〇は△△を軍事的に驚異的な隣国であると見なしています

### 希望する変更

（1枚目の画像）〇〇は△△の悪名を脅威に感じています
（2枚目の画像）〇〇は△△を軍事的に脅威な隣国であると見なしています

### 変更の理由（概要）

日本語のミス

### 変更の理由（詳細）

悪名や軍事力に脅かされているという意味なので脅威が正しい

### プレイ国家

メキシコ

### ゲームバージョン

1.5.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。
