### ISSUE TITLE
汚染の影響のツールチップ

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#854]
### スクリーンショット

![pollution](https://github.com/matanki-saito/vic3jpadvmod/assets/50406316/2bed1c80-4b76-4b79-bbcd-6f416eed6d3e)

### 問題のツールチップ

汚染の影響のツールチップ

### 問題の表現

上記の公衆衛生への影響は、(state)におけるXX%によってさらに減少している

### 問題箇所の英文

The above effects on public health are being further reduced by XX% in (state)

### 希望する変更

(state)における上記の公衆衛生への影響はXX%減少

### 変更の理由（概要）

変数に対応した語順になっていないため

### 変更の理由（詳細）

同上

### プレイ国家

どこでも

### ゲームバージョン

1.5.X

### MOD有無

翻訳改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
提案通り修正しました。
