### ISSUE TITLE
選挙までの残り日数表記「($NUM_DAYS$日以内)」

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#855]
### スクリーンショット

![image](https://github.com/matanki-saito/vic3jpadvmod/assets/37979626/bee85873-38b7-4a2e-9fde-52a00182c315)

### 問題のあるインターフェイス

選挙ウィンドウ

### 問題のテキスト

$DATE$ (in $NUM_DAYS$ days)
$DATE$ (in one day)

### 希望する変更

$DATE$(残り$NUM_DAYS$日)
$DATE$(残り1日)

### 変更の理由（概要）

自然な表現にするため

### ゲームバージョン

1.5.X

### MOD有無

日本語修正mod

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
議論の結果
```$DATE$($NUM_DAYS$日後)```
```$DATE$(1日後)```
に修正することで確定しました
