### ISSUE TITLE
国民皆兵の説明文（volunteer）

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#856]
### スクリーンショット

![20240215220130_1](https://github.com/matanki-saito/vic3jpadvmod/assets/42687608/4ad0d9ad-7530-4f0c-873b-5041871f3a48)

### 問題のあるインターフェイス

技術「国民皆兵」の説明文

### 問題のテキスト

ボランティアや傭兵では近代の軍事力に

### 希望する変更

志願兵や傭兵では近代の軍事力に

### 変更の理由（概要）

誤訳のため

### 変更の理由（詳細）

この文脈におけるvolunteerは日本で一般に使われる「無償奉仕者」の意味ではなく「志願兵、義勇兵」の意味であるため

### ゲームバージョン

1.5.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
議論の結果、原案通り「志願兵」に修正しました。クローズします
