### ISSUE TITLE
動員オプション「強制行進」に関して

### ISSUE THREAD

**Issue by Nebimo** [matanki-saito/vic3jpadvmod#857]
### スクリーンショット

![vic3-240324](https://github.com/matanki-saito/vic3jpadvmod/assets/122381244/88287808-955f-4c22-8fe5-efa22c130022)

### 問題のあるインターフェイス

軍事ウィンドウ

### 問題のテキスト

 mobilization_option_forced_march: "強制行進"

### 希望する変更

 mobilization_option_forced_march: "強行軍"

### 変更の理由（概要）

ゲーム内及び現実世界における用法と相違していると考えられる為

### 変更の理由（詳細）

本件は動員のオプションかつ移動速度の向上等のニュアンスであり、到達時間をより早める目的で将兵へ負担を強いる内容なので「強行軍」が妥当と考えられます。

下記はgoo国語辞書の強行軍のページです。下記における1が今回該当すると考えられます。
https://dictionary.goo.ne.jp/word/%E5%BC%B7%E8%A1%8C%E8%BB%8D/

軽くネットサーフィンしましたが、強制行進の場合は捕虜や人種隔離政策に伴う移動に対して使われる傾向にある印象がありました。一部には強行軍の同義として用いているページもありましたが、

### ゲームバージョン

None

### MOD有無

null

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
報告ありがとうございます。提案通り反映しました。
