### ISSUE TITLE
ユニットのアップグレード

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#858]
### スクリーンショット

![20240326172507_1](https://github.com/matanki-saito/vic3jpadvmod/assets/42687608/b3dfe099-d3ae-4790-94df-34c0f3da5e2c)

### 問題のあるインターフェイス

軍事パネル内のユニットのアップグレードボタン

### 問題のテキスト

すべての◯◯をアップグレード

### 希望する変更

全◯◯アップグレード

### 変更の理由（概要）

テキストが見切れて読めないため

### 変更の理由（詳細）

ボタン上のテキストが文字あふれを起こして見切れているため
手元で実験したところ、「全〇〇をアップグレード」と助詞を追加するだけで文字あふれを起こしてしまう
この種の問題を根本的に解決するには「アップグレード」という用語の変更が必要

### ゲームバージョン

1.5.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
議論の結果、原文が原因で見切れているため、今後の原文修正に期待することで決しました
