### ISSUE TITLE
西オーストラリアの国家説明文

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#859]
### スクリーンショット

![Victoria 3 Screenshot 2024 03 31 - 17 52 14 02](https://github.com/matanki-saito/vic3jpadvmod/assets/147261526/2e19d073-9db4-4983-910b-877caab5a793)

### 問題部分

本文

### 問題のイベントタイトル

西オーストラリアの国家説明文

### 問題のイベント本文（抜粋可）

WAS_FLAVOR_TEXT: "スワンリバーの入植者たちがアボリジニによって代々受け継がれる土地に税を課し、そこ結果ピンジャラの虐殺へと発展したのはわずか2年前のこと。植民地におけるこの抗争はどうすれば沈静化できるのだろうか？"

### 希望する変更（修正部分のみ）

WAS_FLAVOR_TEXT: "スワンリバーの入植者たちがアボリジニによって代々受け継がれる土地に税を課し、その結果ピンジャラの虐殺へと発展したのはわずか2年前のこと。植民地におけるこの抗争はどうすれば沈静化できるのだろうか？"

### 変更の理由（概要）

誤字の修正

### 変更の理由（詳細）

誤字の修正　
「そこ結果…」→「その結果…」

### プレイ国家

西オーストラリア

### ゲームバージョン

1.6.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
提案通り修正しました。あわせて、一般的に海外の川は〇〇リバーではなく〇〇川と訳すことが多いと思いため、「スワンリバー」→「スワン川」も修正しています。
