### ISSUE TITLE
【修正】「敵である州の上陸作戦」

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#861]
### スクリーンショット

![image](https://github.com/matanki-saito/vic3jpadvmod/assets/37979626/b89fcef2-c68d-4e90-b6c7-43fda9af6577)

### 問題のあるインターフェイス

海軍ウィンドウ

### 問題のテキスト

```#header Plan a Naval Invasion of an enemy [concept_state]#![ConcatIfNeitherEmpty('\n', MilitaryFormation.GetNavalInvasionTooltip )]```
```#header 敵である[concept_state]の上陸作戦を計画#![ConcatIfNeitherEmpty('\n', MilitaryFormation.GetNavalInvasionTooltip )]```

### 希望する変更

```#header 敵[concept_state]への上陸作戦を計画する#![ConcatIfNeitherEmpty('\n', MilitaryFormation.GetNavalInvasionTooltip )]```

### 変更の理由（概要）

日本語として自然な表現にするため

### ゲームバージョン

1.7.X

### MOD有無

日本語改善Mod

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
議論の結果、「敵国の州に上陸作戦を計画する」という表現になりました
クローズします
