### ISSUE TITLE
【修正】海軍の作戦「護衛船団」

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#862]
### スクリーンショット

![image](https://github.com/matanki-saito/vic3jpadvmod/assets/37979626/3e6dc2b3-b230-4457-9612-7e87f863c580)

### 問題の用語

護衛船団

### 英語版の表現

Escort Convoys

### 希望する変更

船団護衛

### 変更の理由（概要）

誤訳

### ゲームバージョン

1.7.X

### MOD有無

日本語改善Mod

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。
