### ISSUE TITLE
【一括修正】法律/技術によるアンロックの効果文

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#864]
### スクリーンショット

![image](https://github.com/matanki-saito/vic3jpadvmod/assets/37979626/9a6c291d-3f84-4952-a798-0e0c88fe8a6c)
![image](https://github.com/matanki-saito/vic3jpadvmod/assets/37979626/28e74088-684d-401b-a264-ae476d092532)

### 問題のあるインターフェイス

法律画面/研究画面 マウスオーバー

### 問題のテキスト

```$BUILDING_TYPE$ 用 $PRODUCTION_METHOD$ をアンロックします ([concept_production_method])```
```$BUILDING_TYPE$ 用 $PRODUCTION_METHOD$ の許可を取り消します ([concept_production_method])```
```$BUILDING_TYPE$ をアンロックします ([concept_building])```
```[DECREE_TYPE.GetName]をアンロックします ([concept_decree])```
```[DIPLOMATIC_ACTION_TYPE.GetName]をアンロックします ([concept_diplomatic_action])```
```$TECH_TYPE$の研究を可能にします ([concept_technology])```
```$LAW$の許可を取り消します```
```$LAW$によってアンロックされます```
```$LAW$によって許可が取り消されます```
```#tooltippable #tooltip:$BREAKDOWN_TAG$ $UNLOCKED_CATEGORIES_LIST$#!#!をアンロックします```
```#tooltippable #tooltip:$BREAKDOWN_TAG$ $DISALLOWED_CATEGORIES_LIST$#!#! の許可を取り消します```

### 希望する変更

```$BUILDING_TYPE$用$PRODUCTION_METHOD$([concept_production_method])を解禁します```
```$BUILDING_TYPE$用$PRODUCTION_METHOD$([concept_production_method])を禁止します```
```$BUILDING_TYPE$([concept_building])を解禁します```
```[DECREE_TYPE.GetName]([concept_decree])を解禁します```
```[DIPLOMATIC_ACTION_TYPE.GetName]([concept_diplomatic_action])を解禁します```
```$TECH_TYPE$([concept_technology])の研究を可能にします```
```$LAW$を禁止します```
```$LAW$によって解禁されます```
```$LAW$によって禁止されます```
```#tooltippable #tooltip:$BREAKDOWN_TAG$ $UNLOCKED_CATEGORIES_LIST$を解禁します#!#!```
```#tooltippable #tooltip:$BREAKDOWN_TAG$ $DISALLOWED_CATEGORIES_LIST$を禁止します#!#!```

### 変更の理由（概要）

括弧の位置を自然な位置にするため

### 変更の理由（詳細）

Disallowsを「許可を取り消し」では冗長なので「禁止」をしたい。その場合、「アンロック」ではつり合いが取れないかと思い「解禁」への改訳を提案。そこまで問題ないのであれば「アンロック」のままでも可。

### ゲームバージョン

1.7.X

### MOD有無

日本語改善Mod

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
議論の結果、以下のように修正しました
```$BUILDING_TYPE$用$PRODUCTION_METHOD$([concept_production_method])をアンロックします ```
```$BUILDING_TYPE$用$PRODUCTION_METHOD$([concept_production_method])を禁止します```
```$BUILDING_TYPE$([concept_building])をアンロックします```
```[DECREE_TYPE.GetName]([concept_decree])をアンロックします```
```[DIPLOMATIC_ACTION_TYPE.GetName]([concept_diplomatic_action])をアンロックします```
```$TECH_TYPE$([concept_technology])の研究を可能にします```
```$LAW$を禁止します```
```$LAW$を採用している```
```$LAW$を採用していない```
```#tooltippable #tooltip:$BREAKDOWN_TAG$ $UNLOCKED_CATEGORIES_LIST$をアンロックします#!#!```
```#tooltippable #tooltip:$BREAKDOWN_TAG$ $DISALLOWED_CATEGORIES_LIST$を禁止します#!#!```
