### ISSUE TITLE
採金地の枯渇

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#865]
### スクリーンショット

![20240403191055_1](https://github.com/matanki-saito/vic3jpadvmod/assets/42687608/71a2e419-480d-459c-aac7-252bfba5548b)

### 問題部分

本文

### 問題のイベントタイトル

採金地の枯渇

### 問題のイベント本文（抜粋可）

干上がった砂金：自宅に帰る探鉱者

### 希望する変更（修正部分のみ）

干上がった砂金：故郷に帰る探鉱者

### 変更の理由（概要）

誤訳のため

### 変更の理由（詳細）

原文は Alluvial Gold Dried Up: Miners Go Home
イベントの内容は、「ゴールドラッシュが終わり、金目当てで集まった移住者が再移住を始めた」というものであり、Homeの訳としては「自宅」より「故郷」の方がふさわしい

### プレイ国家

タスマニア（ヴァン・ディーメンズ・ランド）

### ゲームバージョン

1.6.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by clamm0363** [comment]
イベント本文も含め、下記のように修正しました

#bold 砂金はもう枯渇した！鉱夫は故郷に帰れ！#!

採鉱のせいで川は干上がった。鉱山は健康被害をもたらしている。

#italic 立ち入ったら命の保証はない。不法侵入者は射殺される。一発で足りなければもう一発だ。#!

クローズします
