### ISSUE TITLE
外交アクション時に表示されるツールチップの受諾/条件の最後に「への」が表示される

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#867]
### スクリーンショット

![image](https://github.com/matanki-saito/vic3jpadvmod/assets/43299334/52b40ee3-2936-4ec3-aa64-a9f578a66d8e)
![image](https://github.com/matanki-saito/vic3jpadvmod/assets/43299334/631bfa48-1954-4eb1-9009-7ae1bd308088)
![image](https://github.com/matanki-saito/vic3jpadvmod/assets/43299334/fbf34758-e6b6-4ff9-80bb-fd0756b67fef)

### 問題のあるインターフェイス

外交アクションツールチップ

### 問題のテキスト

「～への」

### 希望する変更

「への」の削除

### 変更の理由（概要）

表示の不具合

### 変更の理由（詳細）

まずは原因究明をする必要がありそう。

### ゲームバージョン

1.7.X

### MOD有無

Japonismなどいろいろ

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
こちら再現性がなくクローズします
