### ISSUE TITLE
ランク(司令官階級の短縮語)

### ISSUE THREAD

**Issue by mochi115** [matanki-saito/vic3jpadvmod#868]
### スクリーンショット

![20240406181338_1](https://github.com/matanki-saito/vic3jpadvmod/assets/117048815/60c5a558-d46a-41f1-b2ff-fb67e225722b)

### 問題の用語

concept_commander_rank_short:0 "ランク"

### 希望する変更

concept_commander_rank_short:0 "階級"

### 変更の理由（概要）

日本語に修正

### ゲームバージョン

1.7.X

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
ご指摘の通り修正しました。
