### ISSUE TITLE
【修正提案】戦争宣伝

### ISSUE THREAD

**Issue by saarland68** [matanki-saito/vic3jpadvmod#87]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![image](https://user-images.githubusercontent.com/70930137/198313322-9b886dc8-3bf2-49b4-afae-5537194bb4cd.png)

## 問題の用語（必須）
戦争宣伝

## 英語版の表現（任意）
War Propaganda

## 希望する変更（必須）
戦争プロパガンダ

## 変更の理由（必須）
こちらのほうが馴染みのある表現だと思われます

## ゲームバージョン（必須）

1.0.1

## DLC有無（必須）

無し

## MOD有無（必須）
なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1035197907768455250
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by saarland68** [comment]
修正しました
「戦争宣伝」→「戦争プロパガンダ」

**Comment by saarland68** [comment]
クローズします
