### ISSUE TITLE
企業の生産量ボーナス

### ISSUE THREAD

**Issue by mochi115** [matanki-saito/vic3jpadvmod#871]
### スクリーンショット

![20240406185606_1](https://github.com/matanki-saito/vic3jpadvmod/assets/117048815/dedbbd51-660f-4790-86ae-62f2e3e8cd47)

### 問題の用語

企業の生産量ボーナス

### 希望する変更

企業の処理量ボーナス

### 変更の理由（概要）

修正訳に統一

### ゲームバージョン

1.7.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
報告ありがとうございます。#498で同じissueを決定しているため、同様にこちらも改訳して用語統一させました。
