### ISSUE TITLE
利益集団の支持の段階

### ISSUE THREAD

**Issue by mochi115** [matanki-saito/vic3jpadvmod#872]
### 問題の用語

怒り/不幸/幸福

### 英語版の表現

Angry/Unhappy/Happy

### 希望する変更

激怒/不満/満足

### 変更の理由（概要）

適切な語に変更

### 変更の理由（詳細）

不満、満足としたほうが利益集団の態度を表すものとして適切だと思われます。
Angryを激怒とした理由は、支持の段階を漢字2文字に統一するためです。

### ゲームバージョン

1.7.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通り以下のエントリを修正しました。
ig_approval_happy
ig_approval_unhappy
ig_approval_angry

起票ありがとうございました。
