### ISSUE TITLE
ハンドアセンブリ

### ISSUE THREAD

**Issue by mochi115** [matanki-saito/vic3jpadvmod#873]
### スクリーンショット

![20240407153839_1](https://github.com/matanki-saito/vic3jpadvmod/assets/117048815/70d8c825-bc17-4507-87e6-48b54dd4f41f)

### 問題の用語

ハンドアセンブリ

### 希望する変更

手作業による組立

### 変更の理由（概要）

日本語の表現に修正

### ゲームバージョン

1.7.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
提案ありがとうございます。チーム内の話し合いの結果、他のPMと表現を合わせて文章ではなく単語にして「手作業」とすることにしました。
