### ISSUE TITLE
製法のリセット

### ISSUE THREAD

**Issue by mochi115** [matanki-saito/vic3jpadvmod#874]
### スクリーンショット

![20240407154550_1](https://github.com/matanki-saito/vic3jpadvmod/assets/117048815/61f87ed6-d042-4ada-a23d-1fbc97d7c361)

### 問題の用語

製法のリセット

### 希望する変更

方式のリセット

### 変更の理由（概要）

修正訳に統一

### ゲームバージョン

1.7.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
ご指摘どおりに修正しました。
