### ISSUE TITLE
予備現金

### ISSUE THREAD

**Issue by mochi115** [matanki-saito/vic3jpadvmod#875]
### スクリーンショット

![20240407155142_1](https://github.com/matanki-saito/vic3jpadvmod/assets/117048815/10334592-2b7d-4e9d-8fce-29efae1c0eb9)

### 問題の用語

予備現金

### 希望する変更

手元資金

### 変更の理由（概要）

訳の統一

### ゲームバージョン

1.7.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
ご指摘どおりに修正しました。
