### ISSUE TITLE
企業チャーター

### ISSUE THREAD

**Issue by mochi115** [matanki-saito/vic3jpadvmod#876]
### スクリーンショット

![20240406181038_1](https://github.com/matanki-saito/vic3jpadvmod/assets/117048815/98ba9633-4b8f-47f1-a60b-f28e893f5640)

### 問題の用語

企業チャーター

### 英語版の表現

Corporate Charters

### 希望する変更

会社定款

### 変更の理由（概要）

辞典の訳に修正

### ゲームバージョン

1.7.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通り修正しました。起票ありがとうございました。
