### ISSUE TITLE
自給農家

### ISSUE THREAD

**Issue by mochi115** [matanki-saito/vic3jpadvmod#877]
### スクリーンショット

![20240407160300_1](https://github.com/matanki-saito/vic3jpadvmod/assets/117048815/49c41dc7-dc3e-4345-b6f8-f46ea04caa1b)

### 問題の用語

自給農家

### 希望する変更

自給農場

### 変更の理由（概要）

施設であるため農家ではなく農場とした方が適切だと思います。

### ゲームバージョン

1.7.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
こちらチーム内で議論しましたが、農場とすると自給自足を越えて商業化しているような語感があるため、ゲーム内で意味するところへの近さでは現状の「自給農場」のほうが近いという結論になりました。すみませんが現状維持といたします。
