### ISSUE TITLE
生活水準の期待値(最小)

### ISSUE THREAD

**Issue by mochi115** [matanki-saito/vic3jpadvmod#879]
### スクリーンショット

![20240406182625_1](https://github.com/matanki-saito/vic3jpadvmod/assets/117048815/a92d93ab-e0e3-4dfa-8a3a-c74cf43d7aed)

### 問題の用語

生活水準の期待値(最小)

### 希望する変更

許容生活水準

### 変更の理由（概要）

修正訳に統一

### 変更の理由（詳細）

#488 の修正に合わせました

### ゲームバージョン

1.7.X

### MOD有無

日本語改善MOD

**Comment by Zousuikakka** [comment]
ご指摘どおりに修正しました。
