### ISSUE TITLE
【修正提案】エンクロージャー

### ISSUE THREAD

**Issue by saarland68** [matanki-saito/vic3jpadvmod#88]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![image](https://user-images.githubusercontent.com/70930137/198315130-8df2f97b-3017-498f-8aa7-b114ea574452.png)

## 問題の用語（必須）
エンクロージャー

## 英語版の表現（任意）
Enclosure

## 希望する変更（必須）
囲い込み

## 変更の理由（必須）
https://ja.wikipedia.org/wiki/%E5%9B%B2%E3%81%84%E8%BE%BC%E3%81%BF#:~:text=%E5%9B%B2%E3%81%84%E8%BE%BC%E3%81%BF%EF%BC%88%E3%81%8B%E3%81%93%E3%81%84%E3%81%93%E3%81%BF%E3%80%81%E8%8B%B1%E8%AA%9E%3A,%E3%82%8F%E3%82%8C%E3%81%9F%E3%82%82%E3%81%AE%E3%82%92%E6%8C%87%E3%81%99%E3%80%82

## ゲームバージョン（必須）

1.0.1

## DLC有無（必須）

無し

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1035199215497920562
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by saarland68** [comment]
修正しました
「エンクロージャー」→「囲い込み」

**Comment by saarland68** [comment]
この起票は閉じます
