### ISSUE TITLE
毎週、陸軍および海軍のユニット経験を獲得

### ISSUE THREAD

**Issue by mochi115** [matanki-saito/vic3jpadvmod#880]
### スクリーンショット

![20240406182318_1](https://github.com/matanki-saito/vic3jpadvmod/assets/117048815/ac06f226-e15c-4ba0-a1a5-a3781c96cfd4)

### 問題の用語

毎週、陸軍および海軍のユニット経験を獲得

### 希望する変更

毎週ごとの陸軍および海軍のユニット経験値の獲得量

### 変更の理由（概要）

不自然な訳の修正

### ゲームバージョン

1.7.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
議論の結果、関連するエントリも併せて以下のように修正することで決しました。起票ありがとうございました。
```Unit Experience```
→```ユニット経験値```
```Weekly $concept_unit_experience$ Gain for Armies```
→```週ごとの陸軍の$concept_unit_experience$獲得量```
```Weekly $concept_unit_experience$ Gain for Navies```
→```週ごとの海軍の$concept_unit_experience$獲得量```
```Weekly $concept_unit_experience$ Gain for Armies & Navies```
→```週ごとの陸海軍の$concept_unit_experience$獲得量```
