### ISSUE TITLE
アイルランド人の人名

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#882]
### スクリーンショット

なし

### 問題の固有名詞：希望する変更

カタール：カハル
デスモンド：デズモンド
エルネス：アーネス
ライアム：リーアム
シーン：ショーン
イーアモン：エイモン

アデーラ：アデラ
ブリジェット：ブリジット
エリース：エリス

カストラーグ：カースルレー
コニンガム：カニンガム
モーニングトン：モーニントン

アイケン：エイケン
ブラディー：ブレイディ
ブルーガ：ブルハ
ブルケ：バーク
ビルネ：バーン
キャンプベル：キャンベル
キャロール：キャロル
クラーケ：クラーク
コノール：コナー
コスグラーヴ：コスグレイヴ
ダリー：デイリー
ドゥンネ：ダン
ファーレル：ファレル
ガラグハー：ガラハー
ヘイス：ヘイズ
ヘーリー：ヒーリー
マクカータン：マッカータン
マククルーグ：マカルー
ムルカヒ：マルカヒー
マーレイ：マリー
オヒギンス：オイギンス
レイリー：ライリー
リアン：ライアン
スミス：スマイス

### 変更の理由（概要）

日本語では一般的ではない表記であるため

### ゲームバージョン

1.6.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
