### ISSUE TITLE
技術「戦闘作戦」

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#883]
### スクリーンショット

![20240421161435_1](https://github.com/matanki-saito/vic3jpadvmod/assets/42687608/eec82eab-c715-4bf0-96a1-59ceda8c1db4)

### 問題の用語

戦闘作戦

### 英語版の表現

Wargaming

### 希望する変更

兵棋演習 / 図上演習 / 机上演習

### 変更の理由（概要）

日本語では一般的でない表記であるため

### 変更の理由（詳細）

Weblioがwargamingに対して「戦闘作戦」の訳語を掲載しているが、フレーバーテキストに適合する日本語訳とは思えないため。

### ゲームバージョン

1.6.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。
