### ISSUE TITLE
鉄骨施設/鋼鉄フレーム建築物に関して

### ISSUE THREAD

**Issue by Nebimo** [matanki-saito/vic3jpadvmod#885]
### スクリーンショット

![スクリーンショット 2024-05-03 004053](https://github.com/matanki-saito/vic3jpadvmod/assets/122381244/5f2ad75e-6d71-43bd-a659-085a979f00f9)

### 問題のあるインターフェイス

施設ウィンドウ内の建設タブ

### 問題のテキスト

◆バニラ英語
 pm_iron_frame_buildings:0 "Iron-Frame Buildings"
 pm_steel_frame_buildings:0 "Steel-Frame Buildings"

◆バニラ日本語訳
 pm_iron_frame_buildings: "鉄骨施設"
 pm_steel_frame_buildings: "鋼鉄フレーム建築物"

### 希望する変更

 pm_iron_frame_buildings: "鋳鉄施設"
 pm_steel_frame_buildings: "鉄骨施設"

### 変更の理由（概要）

判別のできる訳になっていないと思われる為

### 変更の理由（詳細）

1.鉄骨はSteelを用いた建築物であるのが一般的である。

https://www.roomselect.jp/info/detail_0060/
>鉄骨造とは、柱や梁などを鉄骨で作った物の事です。鉄骨は鉄という字が使われていますが、実際は鉄(Iron)の合金である鋼(Steel)で作られています。鋼は鉄よりも強度が強く、丈夫です。鉄骨造では、鉄骨で柱や壁などを作っていきます。

英語版環境ではIronが使われているのにも関わらず、pm_iron_frame_buildingsに対し「鋼鉄」の単語を用いるのは不適切であると読み取れる。

2.希望する変更として出している「鋳鉄が妥当か」に関しては下記2種のHPより建築方面で用いられている言い回しと読み取れる。

https://e-takken.tv/h12-50/
>鋳鉄は軟鋼に比べると含有炭素量が多く、粘りが少なくもろいのが特徴である。
>圧縮応力又は接触応力以外の応力が存在する部分には使用してはならないが（建築基準法施行令64条２項）、建築材として一切使用してはならないわけではない。

https://www.token.co.jp/estate/useful/archipedia/word.php?jid=00016&wid=29841&wdid=01
>理想的な鋳造材料として使われ続けており、現在でも巨大構造物に利用されている。炭素が一定量以下の場合には、鋳鉄とは呼ばずに鋳鋼と呼ぶ。

3.下記2種の英語版Wikipediaより、SteelではなくIronを用いての建築に関する記事が設けられている。

https://en.wikipedia.org/wiki/Cast-iron_architecture
18世紀から19世紀にかけて用いられていたが、鉄骨建築の実用化に伴い陳腐化していると読み取れる記載。
https://en.wikipedia.org/wiki/The_Crystal_Palace
ロンドンのクリスタルパレスでも鋳鉄(Cast-Iron)が用いられている記載。

4.鉄骨そのものがSteelを用いた建築である。その為、pm_steel_frame_buildingsに対しては鉄鋼ではなく鉄骨の言い回しで十分だと思われる。

5.Buildingsの訳に対し、施設と建築物が混在している。

以上よりpm_iron_frame_buildingsが「鋼」ではなく「鉄」を用いている事が直感的に判別できる、希望変更案にて打診を致します。

### ゲームバージョン

1.6.X

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。
