### ISSUE TITLE
Modバージョンが古い場合の警告ポップ

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#887]
### スクリーンショット

![image](https://github.com/matanki-saito/vic3jpadvmod/assets/37979626/8542045a-aad5-4a2c-92d3-d77f38a3b263)

### 問題部分

本文

### 問題のイベント本文（抜粋可）

```あなたのMODの一部が、異なるバージョンの$GAME$です。このMODが正しく動作せずにゲームに問題が発生する可能性があります。安定させるために、更新すまでこのMODを無効にすることをお勧めします。\n\n以下のMODが最新ではありません:\n$MODS_OUTDATED_LIST$```
```• $MOD_NAME$（$MOD_VERSION$をサポート）```

### 希望する変更（修正部分のみ）

```MODの中に、 $GAME$ の別バージョン用のものがあります。このMODが正しく動作せずにゲームに問題を引き起こす可能性があります。安定させるために、更新されるまでこのMODを無効にすることをお勧めします。\n\n以下のMODが最新ではありません:\n$MODS_OUTDATED_LIST$```
```• $MOD_NAME$（$MOD_VERSION$）```

### 変更の理由（概要）

不自然な表現

### ゲームバージョン

1.7.X

### MOD有無

日本語改善Modなど

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通り修正しました。
