### ISSUE TITLE
POPの自動車消費によるインフラ補正のテキストに関して

### ISSUE THREAD

**Issue by Nebimo** [matanki-saito/vic3jpadvmod#888]
### スクリーンショット

![スクリーンショット 2024-05-13 184828](https://github.com/matanki-saito/vic3jpadvmod/assets/122381244/21922430-b864-40f8-8f46-a0de885fd0ea)

### 問題のあるインターフェイス

州ウィンドウ情報タブ

### 問題のテキスト

 modifier_state_infrastructure_from_automobiles_consumption_add: "POPからのインフラ@automobiles!$automobiles$消費"

### 希望する変更

 modifier_state_infrastructure_from_automobiles_consumption_add: "POPの@automobiles!$automobiles$消費によるインフラ"

### 変更の理由（概要）

日本語として不自然な為

### 変更の理由（詳細）

現状のテキストではDESC側の内容を読み取らないと意味が読み取れない内容となっておりますので、修正を希望致します

### ゲームバージョン

1.6.X

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通り修正しました。起票ありがとうございました。
