### ISSUE TITLE
ヤンキー文化・ディキシー文化の姓名

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#889]
### スクリーンショット

なし

### 問題の固有名詞：希望する変更

アエネアス：イーニアス
アサ：エイサ
アビジャー：アバイジャ
バルナバス：バーナバス
ビルダッド：ビルダド
カシウス：カシアス
ケルヴィン：カルヴィン
コンラード：コンラッド
セファス：シーファス
エゼキエル：イジーキエル
エノク：イーノック
ユーゲネ：ユージーン
エラム：イーラム
エリヤ：イライジャ
エフライム：イーフレイム
エラスタス：イラスタス
ホラス：ホレス
ヒラム：ハイラム
ハゼン：ヘイズン
イサイア：アイザイア
イルヴィン：アーヴィング
イチャボッド：イカボド
ジェッセ：ジェシー
ジェレミア：ジェレマイア
ジェフレイ：ジェフリー
ユダ：ジュダ
ジェデディア：ジェディダイア
ジョシア：ジョサイア
ケルミット：カーミット
レーランド：リーランド
レヴィ：リーヴァイ
ルシウス：ルーシャス
ミカー：マイカ
マティアス：マサイアス
オバディア：オバダイア
オルヴィル：オーヴィル
オティス：オーティス
オームスバイ：オームズビー
フィネアス：フィニアス
タデウス：サディアス

アダライン：アデライン
アリダ：アライダ
アルミラ：アルマイラ
アズバー：アズバ
シンティア：シンシア
デリーマ：デリマ
エヴェリナ：イヴリーナ
エリューラ：エルーラ
エリダ：イライダ
フローレナ：フロリーナ
グラセアナ：グレイサナ
グラティア：グラシア
ヘフジバー：ヘプジバ
フルダー：ハルダー
ジョセフィン：ジョゼフィン
ルクレツィア：ルクレティア
マーベル：メイベル
ミネルヴァ：ミナーヴァ
マチルダ：マティルダ
マルヴィナ：マルヴィーナ

カボ：カボット
クローニンシールド：クラウニンシールド
カッシング：クッシング
ダナ：デーナ
グラジア：グレイザー
ミノット：マイノット
マククーン：マッキューン
マッカルム：マッカラム
プトナム：パットナム
シアース：シアーズ
セドグウィック：セジウィック
シュイラー：スカイラー
ウィンスロウ：ウィンズロウ

アンドリュー：アンドリューズ
アイレス：エアーズ
アガシズ：アガシー
バフォード：ビュフォード
ベルクナップ：ベルナップ
バルナム：バーナム
バロウ：バルー
バーレイ：バーリー
カス：キャス
クラーフリン：クラフリン
キャシー：ケイシー
シェウッド：チェトウッド
キャンブレレング：カンブルレン
コン：コンク
コルビン：コービン
クレベンジャー：クレヴェンジャー
ダニエルス：ダニエルズ
ドゥン：ダン
ドティ：ドーティー
ドーンブレイサー：ドーンブレイザー
ドウェル：ディウェル
ドゥセアン：デュショーン
イングランド：イングリッシュ
エーウィング：ユーイング
フレインギューセン：フリーリングハイゼン
ファーンスワース：ファーンズワース
フレーサー：フレイザー
フュラー：フラー
フィフィールド：ファイフィールド
ガーセロン：ガースロン
ギブス：ギブズ
ゴールズビュロー：ゴールズボロー
グラスコク：グラスコック
ガウルド：グールド
グリムス：グライムス
ハマット：ハーミット
ハンマースラフ：ハマースラフ
ハンマー：ハマー
ハガマン：ヘイガマン
ホルデン：ホールデン
ヘッファーナン：ヘファーナン
ハールブット：ハルバット
イリオン：アイリーオン
イスベル：イズベル
ジュエル：ジュウェル
ジュドキンス：ジャドキンズ
ケアニー：カーニー
カーン：ケーン
キッドー：キドゥー
ケイエス：キーズ
キンナード：キナード
ケンノン：ケノン
ラシー：レイシー
レジット：レゲット
ロン：ロング
ラサリエ：ラザリエール
ロベリン：ラヴリン
マククレーラン：マクレラン
マーティンダール：マーティンデール
マクコール：マッコール
マククラーナンド：マクラーナンド
メーデ：ミード
マイグス：メグズ
マイルス：マイルズ
モーリス：モリス
マッケオン：マキーオン
ノーリス：ノリス
ナーグル：ネイグル
ネイル：ニール
ノイエス：ノイズ
ヌーゲン：ヌージェン
ナピレ：ネイピア
ニケッテ：ニケット
ヌッド：ナッド
オーメ：オーム
オグレヴィー：オグルヴィー
オチルツリー：オキルトリー
ポメルネ：ポメリン
パルマー：パーマー
ペッテンジル：ペテンギル
ラムセイ：ラムゼイ
リケット：リケッツ
セウォール：シューアル
セワード：スワード
シックルス：シックルズ
スロカム：スローカム
スタンナード：スタナード
スターギス：スタージス
サダバイ：サダビー
シッソンス：シッソンズ
トーベルト：トーバート
タットル：タトル
トールメッジ：タルミジ
タチャー：サッチャー
トゥルースダール：トゥルーズデール
アルマン：ウルマン
ヴァンデヴェール：ヴァンダーヴィア
ヴァンデヴァール：ヴァンデヴァー
ヴォッジェス：ヴォグデス
ワード：ウォード
ワッヅワース：ワズワース
ウォールエース：ウォーレス
ワッシュバーン：ウォッシュバーン
ウェルス：ウェルズ
ウッドビュリー：ウッドベリー
ウィットルセイ：ウィットルジー
ウェン：ウェンク
ウィットコン：ウィットコム
ズック：ズーク

アティクス：アッティカス
アルフェウス：アルフィーアス
アウバーン：オーバーン
バシル：バジル
キスウェル：チズウェル
ケイテスバイ：ケイツビー
エリー：イーライ
エヴァンデール：イヴェンダー
グスタヴス：ガスターヴァス
ハウウェル：ハウエル
イシャム：アイシャム
ジャベズ：ジェイブズ
モーゼス：モージズ
マルクス：マーカス
ラレイグ：ローリー
ティルグマン：ティルマン
ウィラフバイ：ウィラビー
ザカリア：ザカライア

アンナベル：アナベル
ユーゲニア：ユージェニア
エメライン：エメリン
エルネスティン：アーネスティン
ヘッティ：ヘティー
イゾラ：アイゾラ
パウライン：ポーリーン
ペネロープ：ペネロピ
レウテリア：ルーティリア
ヴィオラ：ヴァイオラ

バイルド：バード
バヴァリー：ビヴァリー
ビリングスレイ：ビリングズリー
ボーリング：ボリング
ベアリガード：ボーリガード
キャリー：ケリー
チリス：チリズ
カルバート：カルヴァート
ドゥヴァル：デュヴァル
エデン：イーデン
フィズハグ：フィッツヒュー
ラッドソン：ラドソン
マシュース：マシューズ
リジン：リギン
ラットレッジ：ラトリッジ
サウンダース：サンダース
タリアフェッロ：トリヴァー
タロエ：タロー
ウォーラー：ワラー

アッシュビー：アシュビー
ブロッホ：ブロック
バットル：バテル
ボグス：ボッグズ
ブラントレイ：ブラントリー
バッジャー：バジャー
バクスレイ：バクスリー
カットショー：カッチョー
クロンプトン：クロプトン
コールス：コールズ
カージル：カーガイル
ディアス：ディーズ
ドロムグール：ドロングール
エヴァンス：エヴァンズ
エウェル：ユーエル
ファインガン：フィネガン
フリリー：フリーリー
フラワーノイ：フロールノイ
グリムスレイ：グリムズリー
ガンツ：ガント
グラジエ：グレイシー
ゲッティス：ゲティス
ゴッギン：ゴギン
ハッバード：ハバード
ハーガン：ヘーガン
ホーヘイ：ホーヒー
ヘイス：ヘイズ
キロウフ：キロー
ラニエール：ラニアー
ロウ：ロー
リードベター：レッドベター
ロヤール：ロヤル
ラマール：ラマー
マヨ：メイヨー
マクカウスランド：マコーズランド
マウリー：モーリー
マームデューク：マーマデューク
マクラーエ：マクレー
マッコマス：マコーマス
マウリン：マフリン
オーテス：オーツ
オグレットリー：オグルトリー
フレガール：フレガー
ペッタス：ペタス
ポセイ：ポージー
ラッドフォード：ラドフォード
ロドス：ローズ
ラグルス：ラグルズ
ラピアー：レイピア
シムス：シムズ
スザーリン：サザーリン
セメス：セムズ
シャリー：シェリー
スプラッドリー：スプラドリー
タウリン：トゥーリン
アプシュア：アップシャー
ヴォーガン：ヴォーン
ヴァン・ドルン：ヴァン・ドーン
ヴァン・ブランケン：ヴァン・ヴランケン
ヴィーゼイ：ヴィージー
ウィザース：ウィザーズ
ワイス：ワイエス

### 変更の理由（概要）

日本語では一般的ではない表記であるため

### ゲームバージョン

1.6.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
