### ISSUE TITLE
日本の史実人物の名前

### ISSUE THREAD

**Issue by awak1180** [matanki-saito/vic3jpadvmod#89]
## 問題の固有名詞と希望する変更（必須）

names_l_japanese.yml
オシオ：大塩
コアン：洪庵
森：毛利
忍子：仁孝
長人：統仁
秀龍：英龍
庸三：耀蔵

## 変更の理由（必須）

上記の翻訳が使われた人物は、明らかに大塩平八郎、緒方洪庵、毛利敬親、仁孝天皇、統仁親王(孝明天皇)、江川英龍、鳥居耀蔵をさしている。
https://ja.wikipedia.org/wiki/%E5%A4%A7%E5%A1%A9%E5%B9%B3%E5%85%AB%E9%83%8E
https://ja.wikipedia.org/wiki/%E7%B7%92%E6%96%B9%E6%B4%AA%E5%BA%B5
https://ja.wikipedia.org/wiki/%E6%AF%9B%E5%88%A9%E6%95%AC%E8%A6%AA
https://ja.wikipedia.org/wiki/%E4%BB%81%E5%AD%9D%E5%A4%A9%E7%9A%87
https://ja.wikipedia.org/wiki/%E5%AD%9D%E6%98%8E%E5%A4%A9%E7%9A%87
https://ja.wikipedia.org/wiki/%E6%B1%9F%E5%B7%9D%E8%8B%B1%E9%BE%8D
https://ja.wikipedia.org/wiki/%E9%B3%A5%E5%B1%85%E8%80%80%E8%94%B5

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by awak1180** [comment]
よろしくお願いします。何卒ご検討をお願いします。

**Comment by kecy3** [comment]
下の名前がまとまっている部分にある
Samata:0 "佐俣"　
は佐久間左馬太の左馬太なのかなと思いました（汎用ネームとしては使いにくいかもですが）

アクセス権、何卒よろしくお願い致します

**Comment by awak1180** [comment]
お疲れ様です。このページを作成したawakと申します。
今回はプレイヤーから見た優先順位を考慮して史実人物のみで課題作成しましたが、ランダム生成キャラクター含めて私の方でも調査は行いました(下記リンク参照)。Samataについてはランダム生成キャラクターでのみ使われる名前ですが、仰る通り佐久間左馬太を元にしたかと思います。
https://bitbucket.org/awak1180/nmih-1180-scenario/wiki/Victoria3%E3%81%AE%E6%97%A5%E6%9C%AC%E8%AA%9E%E4%BF%AE%E6%AD%A3%E3%81%AE%E3%81%9F%E3%82%81%E3%81%AE%E3%83%A1%E3%83%A2

**Comment by inarizushi0309** [comment]
Samata:0 "佐俣"
含め提案された該当箇所修正しました
起票ありがとうございました
