### ISSUE TITLE
私有化のテキスト

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#890]
### スクリーンショット

![enjp](https://github.com/matanki-saito/vic3jpadvmod/assets/50406316/8d503ee6-0d42-4e2c-8c01-55b4bfd8495b)

### 問題のあるインターフェイス

私有化中の州と建物を示すテキスト

### 問題のテキスト

「 [TARGET_STATE.GetName]における[STATE.GetName] [Concept('concept_privatize', '$concept_privatizing$')] [TARGET_BUILDING_TYPE.GetName]の[BUILDING_TYPE.GetName]」
（スコーネにおけるスヴェアランド 私有化 工具工房の金融街）
「[STATE.GetName]の[Concept('concept_privatize', '$concept_privatizing$')] [BUILDING_TYPE.GetName]」
（スコーネの私有化 工具工房）

### 希望する変更

「[STATE.GetName]の[BUILDING_TYPE.GetName]が [TARGET_STATE.GetName]の[TARGET_BUILDING_TYPE.GetName]を[Concept('concept_privatize', '$concept_privatizing$')]」
（スヴェアランドの金融街がスコーネの工具工房を私有化 ）
「[STATE.GetName]の[BUILDING_TYPE.GetName]を[Concept('concept_privatize', '$concept_privatizing$')] 」
（スコーネの工具工房を私有化）

### 変更の理由（概要）

変数に対応した訳文になっていないため

### 変更の理由（詳細）

変数に対応した訳文になっていないため

### ゲームバージョン

1.7.X

### MOD有無

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
「私有化」ではなく「私有化中」のほうがよいという意見が出たため、その部分だけ変更してあとは提案通り修正しました。
