### ISSUE TITLE
Zollverein

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#891]
### スクリーンショット

![zollverein](https://github.com/matanki-saito/vic3jpadvmod/assets/50406316/1852c9d8-95d5-44f6-b4a9-ba56491e7d1e)

### 問題の固有名詞：希望する変更

関税同盟：ツォルフェライン（またはドイツ関税同盟）

### 変更の理由（概要）

後述

### 変更の理由（詳細）

プロイセンの初期パワーブロック。史実のプロイセン主導でドイツ連邦内に結成された関税同盟のこと。
原文のZollvereinはドイツ語でzoll(toll)+verein(union)の意味の一般名詞であるが、英語でZollvereinと記す場合は史実のプロイセンの関税同盟を指す固有名詞扱いとなる。
ゲーム中でも途中から作成できる汎用の関税同盟と紛らわしいので、史実のものと分かる固有名詞的に訳したい。
音訳してツォルフェラインとするか、意訳してドイツ関税同盟とするかのどちらか。

### ゲームバージョン

1.7.X

### MOD有無

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
チーム内で議論したところ、ツォルフェラインよりはドイツ関税同盟のほうが賛同が多かったため、ドイツ関税同盟に変更しました。
