### ISSUE TITLE
固有・汎用Power bloc名

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#892]
### スクリーンショット

なし

### 問題の固有名詞：希望する変更

君主制帝国：主権帝国
宗教招集：宗教会議

イギリス帝国：大英帝国
メッテルニヒシステム：メッテルニヒ体制　or　ウィーン体制
ロシースカヤ・インペリヤ：ロシア帝国
オスマン帝国：崇高なる国家
連合戦線：統一戦線
中欧：ミッテルオイローパ　or　中央ヨーロッパ
列強：ストルマクト
ゴールデンサークル：黄金圏
中国：大中国
大いなる聖戦：大十字軍
道理の同盟：道理同盟
融和同盟：調和同盟
相互協定組織：相互条約機構
連合州同盟：同盟国家連合
州議会：諸国会議
ベルサイユ同盟：ヴェルサイユ同盟
ベルリン議会：ベルリン会議
ウィーン議会：ウィーン会議
ローマ協定：ローマ条約
ベラクルス協定：ベラクルス条約
カルカッタ協定：カルカッタ条約
中央列強：中央同盟国
協商：協商国
不道徳な同盟：非神聖同盟
シンジケート協会：企業連合協会
特恵同盟：特恵国家同盟
税理士会：租税同盟
関税同盟：商業同盟
帝国優先：帝国特恵
ボリバル主義グループ：ボリバル派
ウォール街協定：ウォール街条約
ブロック・ブロニャート：ブロニャール圏
モラル国際組織：道徳国際組織
共産主義国際組織：共産主義インターナショナル
社会主義国際組織：社会主義インターナショナル
ワーキングマン国際組織：職人インターナショナル
労働者国際組織：労働者インターナショナル
無政府主義国際組織：無政府主義インターナショナル
無政府主義議会：無政府主義者総会
大陸制度：大陸体制
ローンスター同盟：ローンスターリーグ
パン・アフリカ連合：汎アフリカ連合
ラテンブロック：ラテン圏
中立主義会議：非同盟会議
自由主義国機構：自由国家機構
シンガポール協定：シンガポール条約
アマゾン協定：アマゾン条約
無実の者連合：無辜連合
聖ステファンの息子たち：聖ステファノの息子たち
崇高な同盟：崇高同盟
民主主義リング：民主主義の輪
ワーテルロー協定：ワーテルロー条約

### 変更の理由（概要）

誤訳あるいは定訳に沿っていないため

### 変更の理由（詳細）

君主制帝国：主権帝国　→　誤訳
宗教招集：宗教会議　→誤訳

イギリス帝国：大英帝国　→定訳
メッテルニヒシステム：メッテルニヒ体制　or　ウィーン体制　→定訳ではないため
ロシースカヤ・インペリヤ：ロシア帝国　→見栄えが悪いので日本語表記に変更
オスマン帝国：崇高なる国家　→国名の方と紛らわしい
連合戦線：統一戦線　→誤訳
中欧：ミッテルオイローパ　or　中央ヨーロッパ
列強：ストルマクト　→見栄えが悪く意味がわかりにくいのでカタカナ表記に変更
ゴールデンサークル：黄金圏　→見栄えが悪いので日本語表記に変更
中国：大中国　→大が抜けてる
大いなる聖戦：大十字軍　→誤訳
道理の同盟：道理同盟　→のはいらない
融和同盟：調和同盟　→誤訳
相互協定組織：相互条約機構　→誤訳
連合州同盟：同盟国家連合　→誤訳
州議会：諸国会議　→誤訳
ベルサイユ同盟：ヴェルサイユ同盟　→表記揺れ
ベルリン議会：ベルリン会議　→誤訳
ウィーン議会：ウィーン会議　→誤訳
ローマ協定：ローマ条約　→Pactは主に条約と訳される
ベラクルス協定：ベラクルス条約　→Pactは主に条約と訳される
カルカッタ協定：カルカッタ条約　→Pactは主に条約と訳される
中央列強：中央同盟国　　→誤訳
協商：協商国　→正式名に変更
不道徳な同盟：非神聖同盟　→誤訳
シンジケート協会：企業連合協会　→Power bloc名らしくない
特恵同盟：特恵国同盟　→Statesの意味が抜けてる
税理士会：租税同盟　→誤訳
関税同盟：商業同盟　→誤訳
帝国優先：帝国特恵　→誤訳
ボリバル主義グループ：ボリバル派　→ボリバル主義ではない＆見栄えが悪いので日本語表記に変更
ウォール街協定：ウォール街条約　→Pactは主に条約と訳される
ブロック・ブロニャート：ブロニャール圏　→見栄えが悪いので日本語表記に変更
モラル国際組織：道徳国際組織　→誤訳
共産主義国際組織：共産主義インターナショナル　→定訳
社会主義国際組織：社会主義インターナショナル　→上記に合わせる
ワーキングマン国際組織：職人インターナショナル　→上記に合わせる
労働者国際組織：労働者インターナショナル　→上記に合わせる
無政府主義国際組織：無政府主義インターナショナル　→上記に合わせる
無政府主義議会：無政府主義者総会　→ConferenceとMeetingよりも上位の規模を想定
大陸制度：大陸体制　→誤訳
ローンスター同盟：ローンスターリーグ　→アメフトのリーグに由来するであろうダジャレ
パン・アフリカ連合：汎アフリカ連合　→日本語表記に変更
ラテンブロック：ラテン圏　→見栄えが悪いので日本語表記に変更
中立主義会議：非同盟会議　→誤訳
自由主義国機構：自由国家機構　→誤訳
シンガポール協定：シンガポール条約　→Pactは主に条約と訳される
アマゾン協定：アマゾン条約　→Pactは主に条約と訳される
無実の者連合：無辜連合　→誤訳
聖ステファンの息子たち：聖ステファノの息子たち
崇高な同盟：崇高同盟　→なはいらない
民主主義リング：民主主義の輪　→見栄えが悪いので日本語表記に変更
ワーテルロー協定：ワーテルロー条約　→Pactは主に条約と訳される

### ゲームバージョン

1.7.X

### MOD有無

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
「君主制帝国」の変更案を「至高帝国」から「主権帝国」に変更

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
