### ISSUE TITLE
私有（建設）

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#893]
### スクリーンショット

![image](https://github.com/matanki-saito/vic3jpadvmod/assets/43299334/18ff7434-2616-4b31-bcf3-c4d0e6f452ce)

### 問題のあるインターフェイス

建設画面のフィルタ

### 問題のテキスト

私有

### 希望する変更

民間

### 変更の理由（概要）

民間の建設の表記揺れ

### ゲームバージョン

1.7.X

### MOD有無

フォントMODなど

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
民間で修正しました
