### ISSUE TITLE
私有レベル、全体の割合

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#894]
### スクリーンショット

![image](https://github.com/matanki-saito/vic3jpadvmod/assets/43299334/0cf20244-aa8d-42a7-88a5-341db7952cd2)

### 問題のツールチップ

所有者欄のツールチップ

### 問題の表現

私有◯レベル(◯% of total)

### 希望する変更

◯レベル：民間(全体の◯%)

### 変更の理由（概要）

訳し漏れなど

### プレイ国家

日本

### ゲームバージョン

1.7.X

### MOD有無

フォントMODなど

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
提案通りに修正しました。
