### ISSUE TITLE
マナーハウスなどによる投資のテキスト

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#895]
### スクリーンショット

![image](https://github.com/matanki-saito/vic3jpadvmod/assets/43299334/b737de52-0483-4c79-b313-a72963d214a2)

### 問題のあるインターフェイス

施設メニュー、投資プールの下の欄

### 問題のテキスト

AにおけるB私有化cのd
A,B:州名　c,d:施設名　cはAにあり、dはBにある

### 希望する変更

BのdがAのcを民営化

### 変更の理由（概要）

意味が通らないため

### ゲームバージョン

1.7.X

### MOD有無

フォントMODなど

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。
