### ISSUE TITLE
マナーハウス

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#896]
### スクリーンショット

![image](https://github.com/matanki-saito/vic3jpadvmod/assets/43299334/d3ce636b-9528-45c0-821c-c1d62e6dcc70)

### 問題の用語

マナーハウス

### 英語版の表現

Manor house

### 希望する変更

領主館

### 変更の理由（概要）

全世界に存在する状況に合わせて

### 変更の理由（詳細）

誤訳ではないが、敢えて音訳するとヨーロッパのものを指すため、アジアなどにも初期から建っているものであり、もっと一般化した名称のほうがよい。
「領主館」は辞書にある定訳のひとつ。

### ゲームバージョン

1.7.X

### MOD有無

フォントMODなど

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
領主館で修正しました
