### ISSUE TITLE
階

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#897]
### スクリーンショット

![image](https://github.com/matanki-saito/vic3jpadvmod/assets/43299334/8f5e39ac-ec9b-4244-8f4a-c8ae388544f9)

### 問題の用語

階

### 英語版の表現

levels

### 希望する変更

レベル

### 変更の理由（概要）

不自然な翻訳

### 変更の理由（詳細）

表記揺れの感があるが、一応階層という解釈も不可能ではないため、ISSUEに立てておく

### ゲームバージョン

1.7.X

### MOD有無

フォントMODなど

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
レベルに修正
