### ISSUE TITLE
財産ポートフォリオ

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#898]
### スクリーンショット

![image](https://github.com/matanki-saito/vic3jpadvmod/assets/43299334/1abc689e-b6d6-427e-9190-401311578484)

### 問題の用語

財産ポートフォリオ

### 英語版の表現

property portfolio

### 希望する変更

資産ポートフォリオ

### 変更の理由（概要）

定訳に合わせる

### 変更の理由（詳細）

portfolioについてももう少し良い訳があったほうが良さそう

### ゲームバージョン

None

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
チーム内での議論の結果、「総保有物件」とすることにしました。
