### ISSUE TITLE
財産ポートフォリオのツールチップ

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#899]
### スクリーンショット

![image](https://github.com/matanki-saito/vic3jpadvmod/assets/43299334/e7b76647-5ba3-406a-8b48-a62e57c4fdb6)

### 問題のツールチップ

財産ポートフォリオのツールチップ下部

### 問題の表現

これはAの総財産ポートフォリオにおいてaの◯%に相当します
A：州　a：建物

### 問題箇所の英文

That is ◯% of a in A's total property portfolio.

### 希望する変更

これはAにあるaの総資産ポートフォリオの◯%です。

### 変更の理由（概要）

意味が通らないため

### ゲームバージョン

1.7.X

### MOD有無

フォントMODなど

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
提案通りに修正しました
