### ISSUE TITLE
【修正提案】官僚制

### ISSUE THREAD

**Issue by clamm0363** [matanki-saito/vic3jpadvmod#90]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![image](https://user-images.githubusercontent.com/29382778/198324882-f4044cb3-8c50-4895-a683-d04767466321.png)

## 問題の用語（必須）

官僚制

## 英語版の表現（任意）

Bureaucracy

## 希望する変更（必須）

行政力

## 変更の理由（必須）

制度の名称ではないため

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

Grand Edition

## MOD有無（必須）

フォント置き換えMOD

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1035206384091930755
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by clamm0363** [comment]
「行政力」となりました。

クローズします。
