### ISSUE TITLE
私有化

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#900]
### スクリーンショット

![image](https://github.com/matanki-saito/vic3jpadvmod/assets/43299334/ab6e5c34-758c-410c-9230-20e6ff0e3ef3)

### 問題の用語

私有化

### 英語版の表現

Privatize/Privatization

### 希望する変更

民営化

### 変更の理由（概要）

定訳

### ゲームバージョン

1.7.X

### MOD有無

フォントMODなど

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
民営（化）で修正しました
