### ISSUE TITLE
勢力ブロック

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#901]
### スクリーンショット

![image](https://github.com/matanki-saito/vic3jpadvmod/assets/43299334/833aa8ac-ef57-4d11-9ca3-8d746e089eed)

### 問題の用語

勢力ブロック

### 英語版の表現

Power Bloc

### 希望する変更

国家陣営

### 変更の理由（概要）

後述する訳し分けのため

### 変更の理由（詳細）

各Power Blocが中立国家に及ぼすLeverageも「勢力」と訳されており、ツールチップなどで見分けがつかない場合がある。
別の用語にしたほうが無難。

### ゲームバージョン

1.7.X

### MOD有無

フォントMODなど

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
勢力圏で確定しました
