### ISSUE TITLE
チェックボックスからズレている

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#903]
### スクリーンショット

![image](https://github.com/matanki-saito/vic3jpadvmod/assets/43299334/dee07fa7-ef47-4cce-83b4-46a5c37ae05e)

### 問題のツールチップ

さまざまなツールチップ

### 問題の表現

チェックボックス語の不要な改行

### 希望する変更

改行をなくす

### 変更の理由（概要）

見た目が良くなく、密集していると読みにくい

### ゲームバージョン

1.7.X

### MOD有無

フォントMODなど

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
対応可能であることが確認できたため今週末対応いたします

**Comment by matanki-saito** [comment]
こちら修正しています
