### ISSUE TITLE
関係改善/破壊などのツールチップ

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#904]
### スクリーンショット

![image](https://github.com/matanki-saito/vic3jpadvmod/assets/43299334/16f1922c-8ef2-47fb-be65-665775acbc96)

### 問題のツールチップ

関係改善/破壊などのツールチップ

### 問題の表現

毎◯日±1改善/悪化します

### 希望する変更

◯日ごとに±1ずつ改善/悪化させます

### 変更の理由（概要）

不自然な翻訳

### ゲームバージョン

1.7.X

### MOD有無

フォントMODなど

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
◯日ごとに±1ずつ改善/悪化させます　などのように修正
