### ISSUE TITLE
Power Blocsの像の部品に対する翻訳の一括改善

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#905]
### スクリーンショット

![image](https://github.com/matanki-saito/vic3jpadvmod/assets/43299334/4d1813bf-7a37-4d31-8dd5-c2d0afb530dc)

### 問題の固有名詞：希望する変更

ヒーロー：
指を差す男性→指し示す男
騎手→馬上の人
走っている男性→走る男
座っている男性→座る男
太陽→太陽（変更なし）
手を振る男性→手を振る男
エンジェル→天使
ブルジョア・マン→資産家の男
躍る女性→踊る淑女
ドラゴン→龍（東洋風の竜のため）
ゾウ→象
パワー・フィッシュ→パワーフィッシュ（文字溢れのため）
ガーディアン→狛犬
ライオン→獅子
オクトパス→蛸
エジプトのオベリスク→エジプトの方尖塔（文字溢れのため）
エチオピアのオベリスク→エチオピアの方尖塔（同上）

その他：
バナー→旗
ワシ→鷲
粗製鍬→粗末な鍬

### 変更の理由（概要）

簡潔かつ一般的な訳に。文字溢れの防止に。

### ゲームバージョン

1.7.X

### MOD有無

フォントMODなど

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
提示どおりに修正
