### ISSUE TITLE
外交カタリスト

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#906]
### スクリーンショット

![image](https://github.com/matanki-saito/vic3jpadvmod/assets/43299334/1a95eda6-b0fa-4635-9922-238728592914)

### 問題の用語

外交カタリスト

### 英語版の表現

Diplomatic Catalyst

### 希望する変更

外交事件

### 変更の理由（概要）

無意味に長く分かりにくい

### ゲームバージョン

1.7.X

### MOD有無

フォントMODなど

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
外交事件で統一しました
