### ISSUE TITLE
施設登記簿のフィルターのツールチップ

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#907]
### スクリーンショット

![image](https://github.com/matanki-saito/vic3jpadvmod/assets/43299334/84bb2bb7-60d9-451c-9676-0966a3509613)
![image](https://github.com/matanki-saito/vic3jpadvmod/assets/43299334/62eb8681-0d4a-4df0-829f-8219278c71b1)
![image](https://github.com/matanki-saito/vic3jpadvmod/assets/43299334/b101355b-a20c-470c-9ccf-04f5a02144b4)

### 問題のツールチップ

国営、民営、その他のフィルタのツールチップ

### 問題の表現

画像参照

### 問題箇所の英文

![image](https://github.com/matanki-saito/vic3jpadvmod/assets/43299334/28aeb64b-eb69-4b36-bdb8-7f6343513609)
![image](https://github.com/matanki-saito/vic3jpadvmod/assets/43299334/14137d43-a481-4ff8-9829-db5795cd4b36)
![image](https://github.com/matanki-saito/vic3jpadvmod/assets/43299334/c10647cf-2ec5-4f56-b533-0bc1cea5704f)

### 希望する変更

～が国有化している施設レベル
～のPOPが民営化している施設レベル
～以外が所有する施設レベル

### 変更の理由（概要）

誤訳

### ゲームバージョン

1.7.X

### MOD有無

フォントMODなど

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
提案通りに修正しました
