### ISSUE TITLE
非同調

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#909]
### スクリーンショット

![image](https://github.com/matanki-saito/vic3jpadvmod/assets/43299334/017e967e-b882-46b4-a851-49c3a7b8ff0f)

### 問題の用語

非同調

### 英語版の表現

Unaligned

### 希望する変更

未提携

### 変更の理由（概要）

不自然な訳のため

### 変更の理由（詳細）

どのPower Blocにも属していない国家をさす。特定の陣営へのLeverageが高まることで、その陣営に所属するため、まだ加入していないというニュアンスで「未提携」とした。

### ゲームバージョン

1.7.X

### MOD有無

フォントMODなど

**Comment by starjard** [comment]
チーム内の議論の結果、Non-Alignedの英訳が非同盟であること、姉妹タイトルのHoI4でもNon-Alignedを非同盟と訳していることから、こちらのUnalignedもNon-Alignedと同様の単語として同じく非同盟とすることにしました。
