### ISSUE TITLE
【修正提案】活動休止

### ISSUE THREAD

**Issue by saarland68** [matanki-saito/vic3jpadvmod#91]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![image](https://user-images.githubusercontent.com/70930137/198326573-25a678fb-2187-4035-ae5a-e1de92791d0c.png)

## 問題の用語（必須）
活動休止

## 英語版の表現（任意）
(Inactive)

## 希望する変更（必須）
非アクティブ

## 変更の理由（必須）
有効なものをアクティブ、有効でないものを非アクティブとした方が分かりやすいと思われます

## ゲームバージョン（必須）

1.0.1

## DLC有無（必須）

無し

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1035207763795652718
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by saarland68** [comment]
修正しました
「有効」「無効」に修正
クローズします
