### ISSUE TITLE
政治ロビーの汎用名

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#912]
### スクリーンショット

なし

### 問題の固有名詞：希望する変更

[COUNTRY.GetAdjectiveNoFormatting]-[TARGET_COUNTRY.GetAdjectiveNoFormatting] $CUSTOM_NAME$：[COUNTRY.GetAdjectiveNoFormatting]・[TARGET_COUNTRY.GetAdjectiveNoFormatting]$CUSTOM_NAME$
[TARGET_COUNTRY.GetAdjectiveNoFormatting]に反対する$CUSTOM_NAME$：反[TARGET_COUNTRY.GetAdjectiveNoFormatting]$CUSTOM_NAME$

結社：会
共同体：親睦会
同盟：連盟
圧力団体：ロビー
体制支持者協会：忠誠者協会
連合党：連合派
体制支持団：忠誠隊
体制支持者の同盟：忠誠派連盟

### 変更の理由（概要）

誤訳であるため

### 変更の理由（詳細）

現在の表記では「イギリス-アメリカ 協会」「アメリカに反対する 協会」の様に表記されるため、これを「イギリス・アメリカ協会」「反アメリカ協会」の様にしたい。

結社：会　→　団体名に「結社」はあまり使わない
共同体：親睦会　→　団体名に「共同体」はあまり使わず、意味が重すぎる
同盟：連盟　→　本格的な国家間同盟と勘違いするのを避けるため
圧力団体：ロビー　→　団体名に「圧力団体」は使わない
体制支持者協会：忠誠者協会　→　ここで使われる「Loyalist」は体制支持という意味ではなく、宗主国を支持するというもののため不適切
連合党：連合派　→　政党名ではないため
体制支持団：忠誠隊　→　二つ上と同じ
体制支持者の同盟：忠誠派連盟　→　上と同じ

### ゲームバージョン

1.7.X

### MOD有無

なし

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
