### ISSUE TITLE
勢力の優位性/不利な状況の活用

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#914]
### スクリーンショット

![image](https://github.com/matanki-saito/vic3jpadvmod/assets/43299334/2aeb800e-b4bd-4bd7-8ddf-f04b21d4f106)
![image](https://github.com/matanki-saito/vic3jpadvmod/assets/43299334/ce474d79-79dd-4b16-8f02-95d655573465)
![image](https://github.com/matanki-saito/vic3jpadvmod/assets/43299334/b3f13ae6-53ef-4ec4-9787-5ccea76135f2)
![image](https://github.com/matanki-saito/vic3jpadvmod/assets/43299334/4d643cad-fe99-4223-9b33-1fff53a62cf0)

### 問題の用語

勢力の優位性/不利な状況の活用

### 英語版の表現

Leverage Advantage/Leverage Disadvantage

### 希望する変更

(Leverage)の優位/劣位

### 変更の理由（概要）

ゲーム内の意味を把握できていない翻訳（特に後者）

### 変更の理由（詳細）

自国のPower Blocが、他国に対して有しているLeverageが、自国を除く最大の保有者に対して相対的にどの程度優劣があるかを表す値。たとえば画像の場合、アメリカ合衆国に対して最大のLeverageを有するのは合衆国自身（Unclaimed Leverage）であり、これが581にのぼるので、自国が獲得できたLeverage(240)はこれと比較すると-340、すなわち「340の劣位」となるわけである。ちなみにPower Blocに引き込む為には、少なくとも200のLeverage Advantageを有することが必要である。

### ゲームバージョン

1.7.X

### MOD有無

フォントMODなど

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
優勢/劣勢で修正しました
