### ISSUE TITLE
影響力抵抗

### ISSUE THREAD

**Issue by Zousuikakka** [matanki-saito/vic3jpadvmod#916]
### スクリーンショット

![image](https://github.com/matanki-saito/vic3jpadvmod/assets/43299334/d8f67c18-eef7-4324-83b6-ac2f70692ab2)
![image](https://github.com/matanki-saito/vic3jpadvmod/assets/43299334/df44a5cd-19d5-409d-9c16-367a09e213a0)

### 問題の用語

影響力抵抗

### 英語版の表現

Leverage Resistance

### 希望する変更

（支配）抵抗力

### 変更の理由（概要）

Leverageの表記揺れなど

### 変更の理由（詳細）

Power Blocが自国に対してLeverageを保有しにくくなる度合いを表す。法律や人口によって定まり、その国が自身に対するLeverageをどの程度維持できるかを決定づける。Leverageと働きは似ているが、外交協定や経済依存度は自国に対しては存在し得ないので、その源泉は全く異なっている。Leverageを◯力と訳すなら対応する形で～力としたい。

### ゲームバージョン

1.7.X

### MOD有無

フォントMODなど

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by Zousuikakka** [comment]
訳案が定まらないためクローズとします
