### ISSUE TITLE
大韓帝国ディシジョン

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#917]
### スクリーンショット

![korean_empire](https://github.com/matanki-saito/vic3jpadvmod/assets/50406316/9a285d46-215a-45a4-a1e5-b9c76e1a6795)

### 問題部分

本文

### 問題のイベントタイトル

大韓帝国の宣言

### 問題のイベント本文（抜粋可）

韓国は2人の皇帝の領域に囲まれています。私たちの主権を守るためには、彼らと対等になるよう自らを高めなければなりません。

### 希望する変更（修正部分のみ）

朝鮮は2人の皇帝の領土に囲まれています。私たちの主権を守るためには、彼らと対等になるよう自らを高めなければなりません。

### 変更の理由（概要）

後述

### 変更の理由（詳細）

原文は「Korea is surrounded by the realms of two Emperors. In order to safeguard our sovereignty, we must elevate ourselves to become their equal.」。
１．朝鮮が大韓帝国に国号を改めるディシジョンなので、この時点ではまだ朝鮮であり、「韓国は」ではなく「朝鮮は」とするほうが正しいため。
２．ここでのレルムは単なる領域ではなく、領土や国家を指すため改訳したい。「皇帝の帝国」や「皇帝の国家」などとするとくどく感じるので、「皇帝の領土」とした。

### プレイ国家

朝鮮

### ゲームバージョン

1.7.X

### MOD有無

翻訳改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。
