### ISSUE TITLE
Advanced Research

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#918]
### スクリーンショット

![research](https://github.com/matanki-saito/vic3jpadvmod/assets/50406316/8fb82e1b-c8a7-4fb1-8159-673a5daf92d0)

### 問題の用語

高度な調査

### 英語版の表現

Advanced Research

### 希望する変更

先進的研究

### 変更の理由（概要）

ゲームメカニクスに合わせた変更

### 変更の理由（詳細）

power blocで選べる原則の一つ。技術発展を加速させる効果があり、ここでのresearchは調査ではなく研究を指すため。

### ゲームバージョン

1.7.X

### MOD有無

翻訳改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
提案通り修正しました。
