### ISSUE TITLE
【修正提案】学界

### ISSUE THREAD

**Issue by saarland68** [matanki-saito/vic3jpadvmod#92]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![image](https://user-images.githubusercontent.com/70930137/198333050-8357345a-ad91-4b5b-94a1-6e4b39d2bff4.png)

## 問題の用語（必須）
学界

## 英語版の表現（任意）
Academia

## 希望する変更（必須）
学術機関

## 変更の理由（必須）
内容が学問の世界という訳ではないと思われます

## ゲームバージョン（必須）

1.0.1

## DLC有無（必須）

無し

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1035214646816292926
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。
