### ISSUE TITLE
Goverment Slaves

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#920]
### スクリーンショット

![ja](https://github.com/matanki-saito/vic3jpadvmod/assets/50406316/2ba1cdee-6404-4e00-808b-8626c08574a4)

### 問題の用語

公奴

### 英語版の表現

Goverment Slaves

### 希望する変更

後述

### 変更の理由（概要）

分かりにくい造語のため改訳したい

### 変更の理由（詳細）

建設局などの、政府が使っている奴隷の維持費のこと。
事前に諮った中で出た案は「政府の奴隷」」「公用奴隷」「官有奴隷」。

### ゲームバージョン

1.7.X

### MOD有無

翻訳改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
チーム内で協議した結果、「官有奴隷」に改訳することとしました。
