### ISSUE TITLE
「虐げられた同胞」イベント

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#921]
### スクリーンショット

![check](https://github.com/matanki-saito/vic3jpadvmod/assets/50406316/7c5ea839-023f-4f12-9767-853de1406528)

### 問題部分

本文

### 問題のイベントタイトル

虐げられた同胞

### 問題のイベント本文（抜粋可）

"その結果、[SCOPE.gsInterestGroup('relevant_ig').GetName]が[SCOPE.sPoliticalLobby('relevant_lobby').GetName]と手を組んだ。"

### 希望する変更（修正部分のみ）

"その結果、[SCOPE.gsInterestGroup('relevant_ig').GetName]は[SCOPE.sCountry('relevant_country').GetName]への敵対姿勢を求めてロビー活動を開始した。"

### 変更の理由（概要）

上のエントリの訳文をコピペしているミス

### 変更の理由（詳細）

一つ上のキーと同じ訳をコピペしており、このエントリの翻訳となっていない。そのため変数の部分でエラーが起きている。

### プレイ国家

どこでも

### ゲームバージョン

1.7.X

### MOD有無

翻訳改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
提案通り修正しました。
