### ISSUE TITLE
Liberty Desire

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#923]
### スクリーンショット

![image](https://github.com/matanki-saito/vic3jpadvmod/assets/37979626/c2d28456-ba5b-4bb0-9e21-7b1f2856641f)

### 問題の用語

自由への願望

### 英語版の表現

Liberty Desire

### 希望する変更

独立欲求

### 変更の理由（概要）

ゲーム用語として使いづらい

### 変更の理由（詳細）

「独立欲求」はEU4で使われている訳

Liberty Desire　自由への願望　→　独立欲求
Liberty Desire Level　自由への願望レベル　→　独立欲求レベル
Weekly Liberty Desire　週単位の自由への願望　→　週毎の独立欲求
Weekly Liberty Desire for all Subjects　すべての従属国の週単位の自由への願望　→　全従属国の週毎の独立欲求
Weekly Liberty Desire Increase　自由への願望の週あたりの増加量　→　週毎の独立欲求増加量
Weekly Liberty Desire Decrease　自由への願望の週あたりの減少量　→　週毎の独立欲求減少量
Reduced Liberty Desire for Same Religion　同じ宗教に対する自由への願望の低下　→　同宗教に対する独立欲求低下

### ゲームバージョン

1.7.X

### MOD有無

日本語改善Mod

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通り修正しました。
