### ISSUE TITLE
チェックマークが表示されない

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#924]
### スクリーンショット

![image](https://github.com/matanki-saito/vic3jpadvmod/assets/37979626/c4acc042-a425-4b12-90b0-a7b69070b51a)
![image](https://github.com/matanki-saito/vic3jpadvmod/assets/37979626/586e7f5b-0a3f-4d6d-a55d-b09d1ccbac54)

### 問題のツールチップ

PowerBlocの原則説明ポップアップ

### 問題の表現

チェックマークの代わりに「はい」が表示される

### 希望する変更

表示の正常化

### 変更の理由（概要）

原因不明

### ゲームバージョン

1.7.X

### MOD有無

日本語改善Mod

**Comment by matanki-saito** [comment]
#671と同様にmod作成のScirpt修正により対処しました
