### ISSUE TITLE
認められるジャーナル

### ISSUE THREAD

**Issue by mochi115** [matanki-saito/vic3jpadvmod#925]
### 問題の用語

認められる

### 英語版の表現

Earning Recognition

### 希望する変更

承認の獲得

### 変更の理由（概要）

より自然な語に変更

### ゲームバージョン

1.7.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
報告ありがとうございます。提案通り修正しました。
