### ISSUE TITLE
送信

### ISSUE THREAD

**Issue by mochi115** [matanki-saito/vic3jpadvmod#926]
### スクリーンショット

![20240630122803_1](https://github.com/matanki-saito/vic3jpadvmod/assets/117048815/b032db5d-c21b-4ad6-8e49-c682c5300adf)

### 問題の用語

送信

### 希望する変更

確定

### 変更の理由（概要）

より自然な語に変更

### ゲームバージョン

1.7.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
長期間未対応となっていますが、チーム内で議論した結果だと原文が「Submit」で英語からしても違和感がある内容であり、原語の時点でややそぐわない単語選びになっている可能性があるため、今後原文が変更される可能性も考えて一旦保留とさせてください。
