### ISSUE TITLE
募兵事務局

### ISSUE THREAD

**Issue by mochi115** [matanki-saito/vic3jpadvmod#927]
### スクリーンショット

![image](https://github.com/matanki-saito/vic3jpadvmod/assets/117048815/a1a3e6ac-9a68-49f9-a763-71adbf2fd382)

### 問題の用語

募兵事務局

### 英語版の表現

Enlistment Offices

### 希望する変更

入隊事務所

### 変更の理由（概要）

原文に沿うように変更

### ゲームバージョン

1.7.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
提案ありがとうございます。提案通り修正しました。
