### ISSUE TITLE
関心の無効化/関心の有効化

### ISSUE THREAD

**Issue by mochi115** [matanki-saito/vic3jpadvmod#928]
### スクリーンショット

![image](https://github.com/matanki-saito/vic3jpadvmod/assets/117048815/11f34f6f-80c5-4033-b20e-1f3f1cef55b6)
![image](https://github.com/matanki-saito/vic3jpadvmod/assets/117048815/b1de4bea-2fd3-484c-ac7f-8a4646f0c50e)

### 問題の用語

関心の無効化/関心の有効化

### 英語版の表現

Inactive Interest/Active Interest

### 希望する変更

無効な関心/有効な関心

### 変更の理由（概要）

誤訳の修正

### ゲームバージョン

1.7.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
報告ありがとうございます。提案通り修正しました。
