### ISSUE TITLE
ファン・ディーメンの領地

### ISSUE THREAD

**Issue by kurutto115** [matanki-saito/vic3jpadvmod#929]
### スクリーンショット

![s-Victoria 3 2024_07_02 23_51_51](https://github.com/matanki-saito/vic3jpadvmod/assets/117251782/979cc602-29f6-4545-be85-8c8b18b00cd7)

### 問題の固有名詞：希望する変更

ファン・ディーメンの領地：ヴァン・ディーメンズ・ランド

### 変更の理由（概要）

日本語として不自然なため

### 変更の理由（詳細）

一般的な表記に変更する

### ゲームバージョン

1.7.X

### MOD有無

本プロジェクトMODのみ

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
起票ありがとうございます。以前は問題なかったのになぜ改悪されたのか気になるところですが、ひとまず修正しました。
