### ISSUE TITLE
【修正提案】医学学位

### ISSUE THREAD

**Issue by saarland68** [matanki-saito/vic3jpadvmod#93]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![image](https://user-images.githubusercontent.com/70930137/198334336-294cbf7c-b64d-4afe-98c4-75689ebabb08.png)

## 問題の用語（必須）
医学学位

## 英語版の表現（任意）
Medical Degrees

## 希望する変更（必須）
医学士

## 変更の理由（必須）

こちらのほうがより一般的と思われます

## ゲームバージョン（必須）

1.0.1

## DLC有無（必須）

無し

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1035215429439860767
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by saarland68** [comment]
修正せずクローズにします
