### ISSUE TITLE
海軍：艦隊名のマウスオンヒント・展開海域と態勢についてのツールチップ

### ISSUE THREAD

**Issue by flowlanss** [matanki-saito/vic3jpadvmod#930]
### スクリーンショット

![Naval_TT1](https://github.com/matanki-saito/vic3jpadvmod/assets/54560025/ffb353f9-b3ae-4936-b28e-723df5c90215)

### 問題のツールチップ

展開海域と態勢についてのツールチップ

### 問題の表現

```[Province.GetStateRegion.GetName] ([concept_presence]: [MilitaryFormation.GetSeaPresence|v%0])[AddLocalizationIf(MilitaryFormation.IsReadyToDefendNavalInvasion, 'FLEET_STATUS_READY_DEFEND_INVASION')]にいます```

### 問題箇所の英文

```At [Province.GetStateRegion.GetName] ([concept_presence]: [MilitaryFormation.GetSeaPresence|v%0])[AddLocalizationIf(MilitaryFormation.IsReadyToDefendNavalInvasion, 'FLEET_STATUS_READY_DEFEND_INVASION')]```

### 希望する変更

```[Province.GetStateRegion.GetName]にいます([concept_presence]: [MilitaryFormation.GetSeaPresence|v%0])
 [AddLocalizationIf(MilitaryFormation.IsReadyToDefendNavalInvasion, 'FLEET_STATUS_READY_DEFEND_INVASION')]```

### 変更の理由（概要）

語順に問題があるため

### 変更の理由（詳細）

艦隊の展開海域とその態勢・状態についてのツールチップだが、「～準備ができていますにいます」となってしまっている。
SSを例にすれば、「南シナ海にいます(展開度:100%) 南シナ海の海上ノードを狙う、あらゆる海軍の侵略を防衛する準備ができています」となるのが望ましい。
また、後の部分も「南シナ海海上ノードを標的とした、あらゆる上陸作戦に対する防衛準備ができています」あたりに変更したい。

### プレイ国家

イギリス

### ゲームバージョン

1.7.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。
