### ISSUE TITLE
司令部を帰還しなければなりません

### ISSUE THREAD

**Issue by kurutto115** [matanki-saito/vic3jpadvmod#931]
### スクリーンショット

![Victoria 3 2024_07_02 12_07_04](https://github.com/matanki-saito/vic3jpadvmod/assets/117251782/80d485ae-3cb6-4b92-bffd-c23afa0056f8)

### 問題のあるインターフェイス

艦隊敗北の通知

### 問題のテキスト

「艦隊名」は「地域名」司令部を帰還しなければなりません

### 希望する変更

「艦隊名」は「地域名」司令部に帰還しなければなりません

### 変更の理由（概要）

てにおはの間違い

### ゲームバージョン

1.7.X

### MOD有無

本プロジェクトMODのみ

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
誤字報告ありがとうございます。即時修正しました。
