### ISSUE TITLE
未だ動員

### ISSUE THREAD

**Issue by kurutto115** [matanki-saito/vic3jpadvmod#932]
### スクリーンショット

![Victoria 3 2024_07_04 14_10_42](https://github.com/matanki-saito/vic3jpadvmod/assets/117251782/783bb259-fc01-4e4d-9ab7-ed066cc5aecf)
![Victoria 3 2024_07_04 14_10_14](https://github.com/matanki-saito/vic3jpadvmod/assets/117251782/22e0a1db-34ff-4fe9-a1ff-7e3fb224b722)

### 問題のあるインターフェイス

上陸作戦の部隊選択画面

### 問題のテキスト

未だ動員 (Not yet Mobilized)
「部隊名」は今後動員 ("部隊名" will Mobilized)
「部隊名」は動員 ("部隊名" is Mobilized)

### 希望する変更

未動員
「部隊名」はこれから動員されます
「部隊名」は動員済みです

### 変更の理由（概要）

日本語として不自然なため

### 変更の理由（詳細）

上陸作戦を行う部隊を選択するウィンドウにおいて、動員していない部隊を選ぶと部隊名の下にまだ動員されていない旨が表示され、推定上陸作戦効率の下にこれから（作戦を指示すると自動的に）動員される旨が表示される

### ゲームバージョン

1.7.X

### MOD有無

本プロジェクトMODのみ

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通り修正しました。起票ありがとうございました。
