### ISSUE TITLE
適用できる概念法律がありません

### ISSUE THREAD

**Issue by kurutto115** [matanki-saito/vic3jpadvmod#933]
### スクリーンショット

![Victoria 3 2024_07_04 14_45_46](https://github.com/matanki-saito/vic3jpadvmod/assets/117251782/720ddfb2-1dd2-47fd-ada8-dfe375876e9f)

### 問題のツールチップ

従属国へ法改正が要求できない場合のマウスオンヒント

### 問題の表現

このグループには、「対象国」に適用できる概念法律がありません

### 問題箇所の英文

No Laws available to impose on "対象国" in this group

### 希望する変更

このグループには「対象国」に適用できる法律がありません

### 変更の理由（概要）

タイポ

### 変更の理由（詳細）

「概念」は不要

### プレイ国家

イギリス

### ゲームバージョン

1.7.X

### MOD有無

本プロジェクトMODのみ

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
誤字報告ありがとうございます。即座に修正しました
