### ISSUE TITLE
強制拒否を送付

### ISSUE THREAD

**Issue by kurutto115** [matanki-saito/vic3jpadvmod#934]
### スクリーンショット

![Victoria 3 2024_07_01 14_00_08](https://github.com/matanki-saito/vic3jpadvmod/assets/117251782/5782791c-80fc-4a06-9543-3773a733143c)

### 問題のあるインターフェイス

従属国に法改正を要求した通知

### 問題のテキスト

強制拒否を送付

### 希望する変更

強制的な要望の送付

### 変更の理由（概要）

誤訳

### 変更の理由（詳細）

原文では"Imposition demand sent"

### ゲームバージョン

1.7.X

### MOD有無

本プロジェクトMODのみ

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
提案ありがとうございます。チーム内で話し合った結果、「強制的な要望」よりは、さらに短く「強要」としたいという意見が出たため、「強要の送付」とすることにしました。
