### ISSUE TITLE
Koreaの和訳

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#935]
### スクリーンショット

![korea](https://github.com/matanki-saito/vic3jpadvmod/assets/50406316/84132338-ef1a-45fe-bb84-da04b7058bf9)

### 問題の固有名詞：希望する変更

韓国：朝鮮
朝鮮：韓国（または大韓帝国）

### 変更の理由（概要）

後述

### 変更の理由（詳細）

英語ではKorea/Korean/Empire of Koreaとなっているテキストについて、日本語では文脈によって朝鮮、韓国または大韓帝国と訳し分ける必要があるため。
大韓帝国を特別に指している場合は、原文がKoreaであれば韓国、Empire of Koreaであれば大韓帝国。
それ以外の当時の朝鮮王国を指す、ないしは朝鮮半島全体を指す場合は朝鮮と訳す。
例に挙げた画像は両班IGの説明テキストで、この場合は「朝鮮」と訳す方が適切である。
それ以外のKoreaについてもまとめてこのissueで訂正したい。

### ゲームバージョン

1.7.X

### MOD有無

翻訳改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
提案通り修正しました。
