### ISSUE TITLE
相互国外投資権をお互いに付与することになります

### ISSUE THREAD

**Issue by kurutto115** [matanki-saito/vic3jpadvmod#936]
### スクリーンショット

![Victoria 3 2024_07_06 6_15_44](https://github.com/matanki-saito/vic3jpadvmod/assets/117251782/cbd434af-d28b-4b06-ad1a-f63a5ab14b5a)

### 問題のあるインターフェイス

相互投資協定の提案画面

### 問題のテキスト

「自国」と「相手国」が相互**国外投資権**をお互いに付与することになります

### 希望する変更

「自国」と「相手国」が互いに**国外投資権**を付与します

### 変更の理由（概要）

日本語として不自然なため

### 変更の理由（詳細）

原文では"自国" and "相手国" will grant mutual **Foreign Investment Rights** to each otherだが、"mutual"と"each other"の両方を訳出すると日本語としては冗長

### ゲームバージョン

1.7.X

### MOD有無

本プロジェクトMODのみ

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
提案ありがとうございます。提案通り修正しました。
