### ISSUE TITLE
アメリカ圧力団体反対派の影響力

### ISSUE THREAD

**Issue by kurutto115** [matanki-saito/vic3jpadvmod#937]
### スクリーンショット

![Victoria 3 2024_07_06 6_15_44](https://github.com/matanki-saito/vic3jpadvmod/assets/117251782/08e83dd9-f4b1-4e56-84f2-7f2a266d2a21)

### 問題のあるインターフェイス

相互投資協定の提案画面

### 問題のテキスト

「自国」における「相手国」**圧力団体**賛成派の影響力
「自国」における「相手国」**圧力団体**反対派の影響力
「相手国」における「自国」**圧力団体**賛成派の**勢力**
「相手国」における「自国」**圧力団体**反対派の**勢力**

### 希望する変更

「A国」における親「B国」**圧力団体**の**勢力**
「A国」における反「B国」**圧力団体**の**勢力**

### 変更の理由（概要）

日本語として不自然なため

### 変更の理由（詳細）

原文では全て**Clout**となっている部分も何故か一部「影響力」と訳されて表記揺れしている

### ゲームバージョン

1.7.X

### MOD有無

本プロジェクトMODのみ

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通り修正しました。起票ありがとうございました。
