### ISSUE TITLE
イギリスとロシアを外交戦で支援するには

### ISSUE THREAD

**Issue by kurutto115** [matanki-saito/vic3jpadvmod#938]
### スクリーンショット

![s-Victoria 3 2024_07_05 7_32_51](https://github.com/matanki-saito/vic3jpadvmod/assets/117251782/4d6e0303-12b9-4fbb-8235-d5a5893046b9)

### 問題のツールチップ

外交戦で支援できない場合のマウスオンヒント

### 問題の表現

「自国」と「相手国」を外交戦で支援するには、両国間の関係が低すぎます（敵対またはそれ以下）

### 問題箇所の英文

Relations between "自国" and "相手国" are too low (Hostile or below) to support them in a Diplomatic play

### 希望する変更

「自国」が「相手国」を外交戦で支援するには、両国間の関係が低すぎます（敵対またはそれ以下）

### 変更の理由（概要）

誤訳

### 変更の理由（詳細）

元の文書に引っ張られて、てにをはが間違っている

### プレイ国家

イギリス

### ゲームバージョン

1.7.X

### MOD有無

本プロジェクトMODのみ

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通り修正しました。起票ありがとうございました。
