### ISSUE TITLE
Colonial Extraction

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#939]
### スクリーンショット

![colonial_extraction](https://github.com/matanki-saito/vic3jpadvmod/assets/50406316/78bacdfd-2413-4b4b-8f24-79aace77ae68)

### 問題の用語

植民地出の採取

### 英語版の表現

Colonial Extraction

### 希望する変更

植民地の搾取

### 変更の理由（概要）

誤字及び誤訳の修正

### ゲームバージョン

1.7.X

### MOD有無

翻訳改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
誤字修正扱いとして即時対応しました。
