### ISSUE TITLE
【修正提案】武器産業、軍需工場

### ISSUE THREAD

**Issue by saarland68** [matanki-saito/vic3jpadvmod#94]
＜ゲームシステム用語＞

## スクリーンショット（任意）
![image](https://user-images.githubusercontent.com/70930137/198341488-f03ed2cd-135f-412f-861e-8d6c0f2addd2.png)

## 問題の用語（必須）
武器産業
軍需工場

## 英語版の表現（任意）
Arms Industries
Munition Plants
## 希望する変更（必須）
武器工場
弾薬工場

## 変更の理由（必須）
武器と弾薬それぞれ工場があり軍需工場だと武器も含まれてしまうためです

## ゲームバージョン（必須）

1.0.1

## DLC有無（必須）

無し

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1035223086506704946
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by saarland68** [comment]
修正しました
「武器産業」→「武器工場」
「軍需工場」→「弾薬工場」
