### ISSUE TITLE
圧力団体結成時のフィード

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#940]
### スクリーンショット

![Victoria 3 Screenshot 2024 07 06 - 18 32 28 81](https://github.com/matanki-saito/vic3jpadvmod/assets/147261526/3f0dae87-b859-4f03-8835-24a90f4a10cc)

### 問題のあるインターフェイス

圧力団体結成時のフィードタイトル

### 問題のテキスト

```外国[concept_political_lobby]が結成されました```

### 希望する変更

国外で[concept_political_lobby]が結成

### 変更の理由（概要）

日本語として自然になるように

### ゲームバージョン

1.7.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
報告ありがとうございます、提案通り修正しました。なお結成フィードだけでなく解散フィードについても同様の修正を行いました。
