### ISSUE TITLE
権力ブロックへの招待ツールチップ

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#941]
### スクリーンショット

![Victoria 3 Screenshot 2024 07 07 - 16 42 24 27](https://github.com/matanki-saito/vic3jpadvmod/assets/147261526/c361df13-e906-4a90-ab8a-dfe993a74bdf)

### 問題のツールチップ

権力ブロックへの招待ツールチップ

### 問題の表現

Aに対するBの勢力の優位性が以上○○○（現在△△△）

### 希望する変更

Aに対するBの勢力の優位性が○○○以上（現在△△△）

### 変更の理由（概要）

変数が逆になっている

### プレイ国家

ブラジル

### ゲームバージョン

1.7.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
こちら他の条件文でも散見されるのでまとめて修正中でした。今日明日までには修正完了できる見込みです。今しばらくお待ちください。

**Comment by inarizushi0309** [comment]
条件文の簡易修正が完了しました。起票ありがとうございました。
