### ISSUE TITLE
技術の普及フィード

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#942]
### スクリーンショット

![Victoria 3 Screenshot 2024 07 06 - 20 47 14 67](https://github.com/matanki-saito/vic3jpadvmod/assets/147261526/fc740dd8-8fca-4993-9f42-04b70b427fdc)

### 問題のあるインターフェイス

技術の普及フィード

### 問題のテキスト

原文は 
da_knowledge_sharing_action_notification_name: "技術が[Country.GetName]で広まっています"
だが、[Country.GetName]の部分が表示されていない

バグの可能性もあるが、
英語版では
da_knowledge_sharing_action_notification_name: "Technologies spreading in [TARGET_COUNTRY.GetName]"
で呼び出している変数名が違う

### 希望する変更

技術が[国名]で普及　等

### 変更の理由（概要）

国名が表示されていない

### ゲームバージョン

1.7.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
変数ミスなので即時修正しました。起票ありがとうございました。
