### ISSUE TITLE
Lobby

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#943]
### スクリーンショット

![lobby](https://github.com/matanki-saito/vic3jpadvmod/assets/50406316/aa283d86-6387-4936-8ad4-7dce61a6bb45)

### 問題の用語

圧力団体

### 英語版の表現

Lobby/Lobbies

### 希望する変更

ロビー団体（文脈によっては単にロビー）

### 変更の理由（概要）

訳語統一

### 変更の理由（詳細）

ゲームコンセプトのLobby/Lobbiesについての改訳提案。
「圧力団体」は通常Interest Group（ゲームでは利益集団と訳している）の定訳であり、Lobbyに対してこの訳語を使うのは紛らわしい。またロビーという用語も日本語では十分に定着していると思われるため。
ゲーム中でランダム結成されるLobbyのほうはissue912で既に圧力団体からロビーに改訳されているため、そちらと訳語統一もしたい。

### ゲームバージョン

1.7.X

### MOD有無

翻訳改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。
