### ISSUE TITLE
こう着

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#945]
### スクリーンショット

![koucyaku](https://github.com/matanki-saito/vic3jpadvmod/assets/50406316/5fd3c8aa-f0ca-48eb-96cb-8b2ace364de2)

### 問題部分

本文

### 問題のイベント本文（抜粋可）

こう着

### 希望する変更（修正部分のみ）

膠着

### 変更の理由（概要）

交ぜ書きの修正

### 変更の理由（詳細）

公文書や新聞等では常用漢字を平仮名にする交ぜ書きをするが、ゲームのテキストは常用漢字に縛られる必要はないため、漢字表記に修正したい。

### プレイ国家

イギリス・ロシア

### ゲームバージョン

1.7.X

### MOD有無

翻訳改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
提案通り修正しました。
