### ISSUE TITLE
中国軍閥の名称

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#946]
### スクリーンショット

![chinas](https://github.com/matanki-saito/vic3jpadvmod/assets/50406316/685cbd19-3fc0-459b-884b-c73b0f434f8c)

### 問題の固有名詞：希望する変更

湖南派：湘系軍閥
広西派：桂系軍閥
安徽派：皖系軍閥
直隷派：直系軍閥
奉天派：奉系軍閥
山西派：晋系軍閥
新疆派：新疆軍閥
広東派：粤系軍閥
四川派：川系軍閥
山東派：山東軍閥（史実のモデル軍閥無し）
雲南派：滇系軍閥

### 変更の理由（概要）

英語の直訳から史実の名称に変更

### 変更の理由（詳細）

1.7.4で追加された、清崩壊後に誕生する軍閥。山東以外は史実の軍閥をモデルとしており、英語の直訳ではなく史実に準じた名称に改訳したい。

### ゲームバージョン

1.7.X

### MOD有無

翻訳改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
上で史実のモデル軍閥無しと書いた山東ですが、史実では直系の傘下に入って半独立勢力となっていた張宗昌がおり、これが直魯連軍と呼ばれています。
https://ja.wikipedia.org/wiki/%E5%BC%B5%E5%AE%97%E6%98%8C

もし仮に独立勢力となっていれば「魯系軍閥」と呼ばれていたと思われるので、山東軍閥ではなく魯系軍閥でもいいかなと思いました。
（魯は山東省の古称であり別名）

**Comment by starjard** [comment]
貴州派：黔系軍閥
が漏れてたので追加です。

**Comment by starjard** [comment]
チーム内で議論した結果、日本語で「〇〇派」の用例もあって強いて改訳するほどではないという意見も出たため、取り下げとしました。
