### ISSUE TITLE
Warlord

### ISSUE THREAD

**Issue by kurutto115** [matanki-saito/vic3jpadvmod#947]
### スクリーンショット

![s-Victoria 3 2024_07_11 23_46_32](https://github.com/matanki-saito/vic3jpadvmod/assets/117251782/b2fc6250-3f8d-4db7-a104-a23c840f8dca)
![Victoria 3 2024_07_11 23_46_32](https://github.com/matanki-saito/vic3jpadvmod/assets/117251782/131ad32d-a8d1-485c-a11a-b693925f20c7)
![Victoria 3 2024_07_11 23_46_43](https://github.com/matanki-saito/vic3jpadvmod/assets/117251782/4e54f80d-6c01-4d66-980b-dd6f31c52362)

### 問題の用語

Warlord

### 英語版の表現

Warlord

### 希望する変更

軍閥指導者

### 変更の理由（概要）

訳し漏れ

### 変更の理由（詳細）

政体「軍閥国家」の説明文における訳し漏れ
AIの戦略「中華統一」の説明では「武将」と訳されているが、時代を考えると「軍閥指導者」や「司令官」などが妥当と思われる

### ゲームバージョン

1.7.X

### MOD有無

本プロジェクトMODのみ

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通り修正しました。起票ありがとうございました。
