### ISSUE TITLE
分離主義者によるビル爆破

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/vic3jpadvmod#948]
### スクリーンショット

![20240712122023_1](https://github.com/user-attachments/assets/b9a255c4-a499-48aa-86ce-a863a18e8740)

### 問題部分

タイトル, 本文

### 問題のイベントタイトル

分離主義者によるビル爆破

### 問題のイベント本文（抜粋可）

分離独立運動の過激派は、政府ビル爆破の責任を主張し、

### 希望する変更（修正部分のみ）

タイトル：分離主義者による施設爆破
本文：分離独立運動の過激派は、政府施設爆破の犯行声明を出し、

### 変更の理由（概要）

誤訳のため

### 変更の理由（詳細）

1837年のロシアでも発生するイベントなので、「ビル」という訳は不適当。
buildingは他の部分で「施設」と訳されているため、それに合わせるのが良い。
また、「責任を主張し」と訳されているclaimed responsibility forは、この場合「犯行声明を出す」「犯行を認める」の意味だと思われる。

### プレイ国家

ロシア

### ゲームバージョン

1.7.X

### MOD有無

自作Mod多数

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by oooFUNooo** [comment]
原案どおりに修正しました
クローズします
