### ISSUE TITLE
司令官解任のツールチップ

### ISSUE THREAD

**Issue by kurutto115** [matanki-saito/vic3jpadvmod#949]
### スクリーンショット

![s-Victoria 3 2024_07_12 20_40_56](https://github.com/user-attachments/assets/2c50eaed-0ea4-4fff-a3e0-60ff6cc266fa)

### 問題のツールチップ

司令官を解任するコマンドのマウスオンヒント

### 問題の表現

指揮の人を解かれた場合、「キャラクター名」は将軍としての役割を失い、司令官階級を通じて「利益団体名」の勢力に影響を与えることができなくなります

### 問題箇所の英文

If relieved of command, "キャラクター名" will lose their role as General and cease to affect the Clout of the "利益団体名" through their Commander Rank

### 希望する変更

司令官の任を解かれた場合、「キャラクター名」は将軍としての役割を失い、階級に応じて「利益団体名」の勢力に影響を及ぼすことがなくなります

### 変更の理由（概要）

誤訳

### 変更の理由（詳細）

「指揮の人」という誤訳を修正するとともに、日本語として自然な表現に修正する

### プレイ国家

イギリス

### ゲームバージョン

1.7.X

### MOD有無

本プロジェクトMODのみ

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
司令官階級のところですが、[concept_commander_rank]で引っ張て来ていたので、そこだけ現状維持にしました
```司令官の任を解かれた場合、[Character.GetFullName]は[concept_general]としての役割を失い、[concept_commander_rank]に応じて[Character.GetInterestGroup.GetName]の[concept_clout]に影響を与えることができなくなります```
