### ISSUE TITLE
interest_groups内で使われる固有名詞

### ISSUE THREAD

**Issue by ChiefIdeologue** [matanki-saito/vic3jpadvmod#95]
## 問題の固有名詞と希望する変更（必須）

東方正教会：東方諸教会
イギリス国教会：聖公会
福音派：福音教会
スンニ派聖職者：スンナ派イスラム法学者
シーア派聖職者：シーア派イスラム法学者
大乗僧：大乗仏教僧
上座僧：上座部仏教僧
異教シャーマン：シャーマン
地主階級：地主ジェントリ
ユンカース：ユンカー
ユンカー地主：地主ユンカー
カルロス支持派：カルロス派
イザベル支持派：イサベル派
鉄道タイクーン：鉄道実業家
宮廷ハーレム：宮廷ハレム
中央集権主義者：中央主義者
官僚階級：文人
儒教学者：儒学者
幕府：佐幕派

## 変更の理由（必須）
日本語では一般的ではない表記であるため

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。議論の進捗についてご確認したい場合はお手数ですがDiscordのアカウントご用意後、下記にアクセスをお願い致します。
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1035239344203644959
*アクセス権が必要になりますので #アクセス権申請板 で申請をお願い致します。

**Comment by ChiefIdeologue** [comment]
修正が完了したため、クローズしました。
