### ISSUE TITLE
ペルシアが要請するMilitary Mission

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#950]
### スクリーンショット

なし

### 問題の用語

軍事任務団

### 英語版の表現

Military Mission

### 希望する変更

軍事使節団

### 変更の理由（概要）

一般的な訳ではないため

### 変更の理由（詳細）

ここでいうMilitary Missionは他国に派遣される軍事顧問からなる使節団を指すので「軍事使節団」と訳すのが一般的

### ゲームバージョン

1.7.X

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通り修正しました。
