### ISSUE TITLE
POPの仕事満足度に関するツールチップ

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#951]
### スクリーンショット

![image](https://github.com/user-attachments/assets/af1cde40-792b-486b-b5b4-9fbaac54ad9f)
![image](https://github.com/user-attachments/assets/36be9912-42e8-4061-9011-6a0c63d7bad5)

### 問題のツールチップ

州情報>中段のPOP選択>仕事の満足度マウスオーバー

### 問題の表現

①```これは、次の要因で[Pop.GetNextJobSatisfaction|0+]にすぐに更新されます:```
②```基本的な不満足度の$VALUE|0+=$```
③```$VALUE|0+=$ [concept_pop]を雇用したばかりだからです```
④```現在の (生活水準)と [Concept('concept_expected_sol', '$concept_expected_sol_short$')] (生活水準期待値) [concept_sol]の相違点からの$VALUE|0+=$```
⑤```現在の (生活水準) と[Pop.GetPopType.GetStrata] (階級の生活水準)用の[Pop.GetCountry.GetName]にある平均的な[concept_sol]の相違点からの$VALUE|0+=$```
⑥```現在の (生活水準) と[Pop.GetPopType.GetStrata] (階級の生活水準)用の[Pop.GetState.GetName]にある平均的な[concept_sol]の相違点からの$VALUE|0+=$```
⑦```[Pop.GetBuilding.GetName]（@money!$WORKPLACE_WAGE_RATE|v1$）と [Pop.GetCountry.GetName]（@money!$NORMAL_WAGE_RATE|v1$）にある[concept_building_wage]間にある#variable $DIFF|1$%#!の相対差からの$VALUE|0+=$```
⑧```$VALUE|0+=$[concept_pop]は現在の[Concept( 'concept_pop_income', '$concept_pop_income_short$')] (@money!$EXPENSES|v1$)で[Concept( 'concept_pop_income', '$concept_pop_income_expenses_short$' )] (@money!$INCOME|v1$分の余裕があるからです```
⑨```$VALUE|0+=$ [concept_pop]は[Concept( 'concept_pop_income', '$concept_pop_income_expenses_short$' )]分の余裕がほとんどないからです```
⑩```$VALUE|0+=$[concept_pop]は現在の[Concept( 'concept_pop_income', '$concept_pop_income_short$')] (@money!$EXPENSES|v1$)で[Concept( 'concept_pop_income', '$concept_pop_income_expenses_short$' )](@money!$INCOME|v1$)分の余裕がないからです```
⑪```[Pop.GetPopType.GetStrata]より高い地位である $RATIO|%v1$ [Concept('concept_pop_qualifications', '$concept_qualified$')]であることからの$VALUE|0+=$```
⑫```[Concept('concept_employment' ,'$concept_employed$')]であることからの$VALUE|0+=$```
⑬```獲得した[concept_dividends] (@money!$POP_DIVIDENDS|v1$)と[concept_budget_wages] (@money!$POP_WAGES|v1$)の#variable $DIVIDENDS_WAGES_RATIO|0$%#!の比率からの$VALUE|0+=$```
⑭```投資損失(@money!$POP_LOSSES|v1$)と[concept_budget_wages] (@money!$POP_WAGES|v1$)の#variable $LOSSES_WAGES_RATIO|0$%#!の比率からの$VALUE|0+=$```
⑮```$VALUE|0+=$: 政府報酬の回収に由来```
⑯```より良い[concept_employment]を探す```

### 問題箇所の英文

①```This will soon update to [Pop.GetNextJobSatisfaction|0+] due to:```
②```$VALUE|0+=$ from Base dissatisfaction```
③```$VALUE|0+=$ because the [concept_pop] has just been hired```
④```$VALUE|0+=$ from the difference between current (生活水準) and [Concept('concept_expected_sol', '$concept_expected_sol_short$')] (生活水準期待値) [concept_sol]```
⑤```$VALUE|0+=$ from the difference between current (生活水準) and average [concept_sol] in [Pop.GetCountry.GetName] for [Pop.GetPopType.GetStrata] (階級の生活水準)```
⑥```$VALUE|0+=$ from the difference between current (生活水準) and average [concept_sol] in [Pop.GetState.GetName] for [Pop.GetPopType.GetStrata] (階級の生活水準)```
⑦```$VALUE|0+=$ from the relative difference of #variable $DIFF|1$%#! between [concept_building_wage] in [Pop.GetBuilding.GetName] (@money!$WORKPLACE_WAGE_RATE|v1$) and [Pop.GetCountry.GetName] (@money!$NORMAL_WAGE_RATE|v1$)```
⑧```$VALUE|0+=$ because the [concept_pop] can afford its [Concept( 'concept_pop_income', '$concept_pop_income_expenses_short$' )] (@money!$EXPENSES|v1$) with its current [Concept( 'concept_pop_income', '$concept_pop_income_short$')] (@money!$INCOME|v1$)```
⑨```$VALUE|0+=$ because the [concept_pop] can barely afford its [Concept( 'concept_pop_income', '$concept_pop_income_expenses_short$' )]```
⑩```$VALUE|0+=$ because the [concept_pop] cannot afford its [Concept( 'concept_pop_income', '$concept_pop_income_expenses_short$' )] (@money!$EXPENSES|v1$) with its current [Concept( 'concept_pop_income', '$concept_pop_income_short$')] (@money!$INCOME|v1$)```
⑪```$VALUE|0+=$ from being $RATIO|%v1$ [Concept('concept_pop_qualifications', '$concept_qualified$')] for a higher strata than [Pop.GetPopType.GetStrata]```
⑫```$VALUE|0+=$ from being [Concept('concept_employment' ,'$concept_employed$')]```
⑬```$VALUE|0+=$ from the ratio of #variable $DIVIDENDS_WAGES_RATIO|0$%#! between earned [concept_dividends] (@money!$POP_DIVIDENDS|v1$) and [concept_budget_wages] (@money!$POP_WAGES|v1$)```
⑭```$VALUE|0+=$ from the ratio of #variable $LOSSES_WAGES_RATIO|0$%#! between investment losses (@money!$POP_LOSSES|v1$) and [concept_budget_wages] (@money!$POP_WAGES|v1$)```
⑮```$VALUE|0+=$ from collecting a government salary```
⑯```Looking for better [concept_employment]```

### 希望する変更

①```以下の要因により、まもなく[Pop.GetNextJobSatisfaction|0+]に更新されます:```
②```$VALUE|0+=$（基礎不満足度）```
③```$VALUE|0+=$（[concept_pop]が雇われたばかり）```
④```$VALUE|0+=$（現在の[concept_sol](生活水準)と[Concept('concept_expected_sol', '$concept_expected_sol_short$')](生活水準期待値)との差異）```
⑤```$VALUE|0+=$（現在の[concept_sol](生活水準)と[Pop.GetCountry.GetName]の平均的な[Pop.GetPopType.GetStrata](階級の生活水準)との差異）```
⑥```$VALUE|0+=$（現在の[concept_sol](生活水準)と[Pop.GetState.GetName]の平均的な[Pop.GetPopType.GetStrata](階級の生活水準)との差異）```
⑦```$VALUE|0+=$（[Pop.GetBuilding.GetName] (@money!$WORKPLACE_WAGE_RATE|v1$)と[Pop.GetCountry.GetName] (@money!$NORMAL_WAGE_RATE|v1$)との間の[concept_building_wage]格差#variable $DIFF|1$%#!）```
⑧```$VALUE|0+=$（[concept_pop]が現在の[Concept( 'concept_pop_income', '$concept_pop_income_short$')] (@money!$INCOME|v1$)で[Concept( 'concept_pop_income', '$concept_pop_income_expenses_short$' )] (@money!$EXPENSES|v1$)を賄えるため）```
⑨```$VALUE|0+=$（[concept_pop]が[Concept( 'concept_pop_income', '$concept_pop_income_expenses_short$' )]を辛うじて賄えるため）```
⑩```$VALUE|0+=$（[concept_pop]が現在の[Concept( 'concept_pop_income', '$concept_pop_income_short$')] (@money!$INCOME|v1$)で[Concept( 'concept_pop_income', '$concept_pop_income_expenses_short$' )] (@money!$EXPENSES|v1$)を賄えないため）```
⑪```$VALUE|0+=$（[Pop.GetPopType.GetStrata]上位$RATIO|%v1$の[Concept('concept_pop_qualifications', '$concept_qualified$')]である）```
⑫```$VALUE|0+=$（[Concept('concept_employment' ,'$concept_employed$')]である）```
⑬```$VALUE|0+=$（[concept_budget_wages] (@money!$POP_WAGES|v1$)比#variable $DIVIDENDS_WAGES_RATIO|0$%#!の[concept_dividends] (@money!$POP_DIVIDENDS|v1$)を獲得した）```
⑭```$VALUE|0+=$（[concept_budget_wages] (@money!$POP_WAGES|v1$)比#variable $LOSSES_WAGES_RATIO|0$%#!の投資損失(@money!$POP_LOSSES|v1$)をした）```
⑮```$VALUE|0+=$（官給）```
⑯```より良い[concept_employment]を探している```

### 変更の理由（概要）

見づらい

### プレイ国家

フランス

### ゲームバージョン

1.7.X

### MOD有無

日本語改善Mod

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通り修正しました。
