### ISSUE TITLE
従属国の独立欲求増減要因

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#952]
### スクリーンショット

![image](https://github.com/user-attachments/assets/63eb5c02-b8a6-47de-b91e-f1818e0e8b68)
![image](https://github.com/user-attachments/assets/46c5b0f0-deb8-409b-9057-a20c9f9caff5)

### 問題のツールチップ

外交画面>従属の独立欲求マウスオーバー

### 問題の表現

```$KEY$から[SelectLocalization(GreaterThan_CFixedPoint('(CFixedPoint)$VALUE$','(CFixedPoint)0'),'$VALUE|bo=2$','$VALUE|bu=2$')]```

### 問題箇所の英文

```[SelectLocalization(GreaterThan_CFixedPoint('(CFixedPoint)$VALUE$','(CFixedPoint)0'),'$VALUE|bo=2$','$VALUE|bu=2$')] from $KEY$```

### 希望する変更

```[SelectLocalization(GreaterThan_CFixedPoint('(CFixedPoint)$VALUE$','(CFixedPoint)0'),'$VALUE|bo=2$','$VALUE|bu=2$')]($KEY$)```

### 変更の理由（概要）

見づらい

### プレイ国家

フランス

### ゲームバージョン

1.7.X

### MOD有無

日本語改善Mod

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
以下議論に追加します

現行訳
```#v 1.5x#!倍を超える相対[concept_prestige]が[SCOPE.GetRootScope.GetDiplomaticPact.GetSecondCountry.GetSubjectType.GetName]に求められています（現在は#v [SCOPE.GetRootScope.GetDiplomaticPact.GetFirstCountry.GetRelativePrestige( SCOPE.GetRootScope.GetDiplomaticPact.GetSecondCountry )|v1]x#!）```
> 1.5x倍を超える相対威信が[従属国タイプ]に求められています（現在は[相対威信]x）

原文
```Relative [concept_prestige] above #v 1.5x#! multiplier desired for [SCOPE.GetRootScope.GetDiplomaticPact.GetSecondCountry.GetSubjectType.GetName] (Currently #v [SCOPE.GetRootScope.GetDiplomaticPact.GetFirstCountry.GetRelativePrestige( SCOPE.GetRootScope.GetDiplomaticPact.GetSecondCountry )|v1]x#!)```
修正案
```[SCOPE.GetRootScope.GetDiplomaticPact.GetSecondCountry.GetSubjectType.GetName]相手に必要な相対[concept_prestige]が#v 1.5倍#!超（現在#v [SCOPE.GetRootScope.GetDiplomaticPact.GetFirstCountry.GetRelativePrestige( SCOPE.GetRootScope.GetDiplomaticPact.GetSecondCountry )|v1]倍#!）```
> [従属国タイプ]相手に必要な相対威信が1.5倍超（現在[相対威信]倍）

これに類するものが他に：
LIBERTY_DESIRE_WEEKLY_CHANGE_PRESTIGE_DIFFERENCE_1_5_POSITIVE
LIBERTY_DESIRE_WEEKLY_CHANGE_PRESTIGE_DIFFERENCE_2_0_NEGATIVE
LIBERTY_DESIRE_WEEKLY_CHANGE_PRESTIGE_DIFFERENCE_2_0_POSITIVE
LIBERTY_DESIRE_WEEKLY_CHANGE_PRESTIGE_DIFFERENCE_3_0_NEGATIVE
LIBERTY_DESIRE_WEEKLY_CHANGE_PRESTIGE_DIFFERENCE_3_0_POSITIVE

**Comment by inarizushi0309** [comment]
追加分含め、原案通り修正しました。
