### ISSUE TITLE
ジャーナル：東のフロンティア

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#953]
### スクリーンショット

![Victoria 3 Screenshot 2024 07 15 - 18 38 40 47](https://github.com/user-attachments/assets/a23fb039-7734-4a83-aa56-e716388c91f8)

### 問題のツールチップ

ジャーナル：東のフロンティア　「大ホラーサーン地方を支配」のツールチップ

### 問題の表現

"[SCOPE.GetRootScope.Getcountry.GetAdjective]の大ホラーサーン地方の支配は数千年前までさかのぼるものの、ここ数世紀は、弱かったり、名目的だったり、安定していない。ナーディル・シャーの東方遠征では、ペルシアのホラーサーン支配が一時的に復活したものの、功績は長続きせず、その治世を超えることはなかった。\n\nナーディル・シャーが始めたことを、[ROOT.GetCountry.GetRuler.GetPrimaryRoleTitle] [ROOT.GetCountry.GetRuler.GetFirstName]が終わらせなければならない。大規模な遠征によって、ペルシャの東方支配を永続的に復活させるのだ。[SCOPE.sStateRegion('herat_scope').GetName]と東方への鍵は、この偉業の要となるだろう。"

### 問題箇所の英文

"While [SCOPE.GetRootScope.GetCountry.GetAdjective] claims to Greater Khorasan stretch back millennia, in recent centuries our control of the area have ranged from loose to nominal. Nader Shah's eastern campaigns briefly saw the restoration of Persian control to Khorasan, but his achievements proved fleeting and would not outlast his reign.\n\nWhat Nader Shah begun, [ROOT.GetCountry.GetRuler.GetPrimaryRoleTitle] [ROOT.GetCountry.GetRuler.GetFirstName] shall finish, with a grand campaign that will see Persian rule restored in the east for perpetuity. [SCOPE.sStateRegion('herat_scope').GetName], the Pearl of Khorasan and our key to the east will serve as the lynchpin of this great undertaking."

### 希望する変更

・冒頭の変数の修正
・「ペルシャ」表記を「ペルシア」に修正

### 変更の理由（概要）

構文ミス、表記揺れ

### 変更の理由（詳細）

・冒頭の変数[SCOPE.GetRootScope.Getcountry.GetAdjective]が表示されていない
（日本語版ではGetcountryとなっている部分が英語版ではGetCountryであり、これが原因？）
・文中に一箇所ペルシャと表記されている部分がある（スクリーンショット参照）他の部分はペルシアであり表記揺れ

### プレイ国家

ペルシア

### ゲームバージョン

1.7.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
誤字脱字の一環として即時修正しました。起票ありがとうございました。
