### ISSUE TITLE
ジャーナル：ペルシャを統合する

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#954]
### スクリーンショット

![Victoria 3 Screenshot 2024 07 15 - 18 45 06 41](https://github.com/user-attachments/assets/6f79482e-b53e-4c5a-a68a-61d0a80bf29a)

### 問題のあるインターフェイス

ジャーナル：ペルシャを統合する

### 問題のテキスト

タイトル：ペルシャを統合する
説明文：ペルシャの地方に対する政府の権限は…

### 希望する変更

タイトル：ペルシアを統合する
説明文：ペルシアの地方に対する政府の権限は…

### 変更の理由（概要）

表記揺れ

### 変更の理由（詳細）

ペルシアに表記を統一

### ゲームバージョン

1.7.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
他作業所内で確認できるペルシャ→ペルシアに修正しました。起票ありがとうございました。
