### ISSUE TITLE
ロビーが機会を申し出ます

### ISSUE THREAD

**Issue by kurutto115** [matanki-saito/vic3jpadvmod#955]
### スクリーンショット

![s-Victoria 3 2024_07_12 20_56_02](https://github.com/user-attachments/assets/953a7fed-8112-41b5-90eb-e9295dd419f4)

### 問題部分

本文

### 問題のイベントタイトル

```[SCOPE.sPoliticalLobby('relevant_lobby').GetName]が機会を申し出ます```

### 問題のイベント本文（抜粋可）

```
[SCOPE.sPoliticalLobby('relevant_lobby').GetName]が、[SCOPE.sCountry('third_party_country').GetName]を[SCOPE.GetRootScope.GetCountry.GetCustom('anti_lobby_opportunity_text_def')]機会の申し出があった。この申し出を受けるということは、[SCOPE.sCountry('relevant_country').GetAdjective]の利益に対立するということである。
```
（スクリーンショットでは以下の通り）
反フランス連盟がプロイセンを次の国と防衛協定を締結する：機会の申し出があった。この申し出を受けるということは、フランスの利益に対立するということである

### 問題のイベント選択肢

（特に問題無いので省略）

### 希望する変更（修正部分のみ）

「ロビー名」から「第三国」と「外交協定」を締結する機会の申し出があった。この申し出を受けるということは、「ロビーの対立国」の利益に対立するということである

### 変更の理由（概要）

変数呼び出しの問題

### 変更の理由（詳細）

英語と同じ変数を呼び出すと文章が破綻してしまうため修正したい

### プレイ国家

イギリス

### ゲームバージョン

1.7.X

### MOD有無

本プロジェクトMODのみ

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
「次の国と防衛協定を締結する：」に代表されるエントリの類似は以下の通り
> ①anti_lobby_proposal_embargo_def
> ②anti_lobby_proposal_rivalry_def
> ③anti_lobby_proposal_war_def
> ④anti_lobby_proposal_leave_power_bloc_def
> ⑤anti_lobby_proposal_break_alliance_def
> ⑥anti_lobby_proposal_break_trade_agreement_def
> ⑦anti_lobby_proposal_break_defensive_pact_def
> ⑧pro_lobby_proposal_defensive_pact_def
> ⑨pro_lobby_proposal_alliance_def
> ⑩pro_lobby_proposal_trade_agreement_def
> ⑪pro_lobby_proposal_power_bloc_def
> ⑫pro_lobby_proposal_power_bloc_invite_def
> ⑬pro_lobby_proposal_investment_agreement_def

**Comment by matanki-saito** [comment]
これらがイベント文の直下に配されていること、ロビーからの要求に関するジャーナルにこれらが使われていることが確認できなかったことから、イベント文にのみ使われる可能性が極めて高いです

**Comment by matanki-saito** [comment]
ですので「と防衛協定を締結する」と自然な形になるように修正することでこのiSSUEに対応できるかと思います。
具体的には以下の修正案になります
> ①establish an [concept_embargo] against　→　に対して[concept_embargo]を実施
> ②declare a [concept_rivalry] with　→　に対し[concept_rivalry]宣言を
> ③launch a [concept_diplomatic_play] against　→　に対し[concept_diplomatic_play]を開始
> ④leave the [concept_power_bloc] belonging to　→　が属する[concept_power_bloc]を離脱
> ⑤dissolve our [concept_alliance] with　→　との[concept_alliance]を解消
> ⑥dissolve our [concept_trade_agreement] with　→　との[concept_trade_agreement]を解消
> ⑦dissolve our [concept_defensive_pact] with　→　との[concept_defensive_pact]を解消
> ⑧establish a [concept_defensive_pact] with　→　との[concept_defensive_pact]を締結
> ⑨establish an [concept_alliance] with　→　との[concept_alliance]を締結
> ⑩sign a [concept_trade_agreement] with　→　との[concept_trade_agreement]を締結
> ⑪join the [concept_power_bloc] belonging to　→　が属する[concept_power_bloc]に参加
> ⑫extend an invitation to our [concept_power_bloc] to　→　に自国の[concept_power_bloc]へ招待
> ⑬establish a [concept_foreign_investment_rights] Agreement with　→　との[concept_foreign_investment_rights]を締結

**Comment by matanki-saito** [comment]
上記の内容を踏まえるとイベント本文の修正案は原案では不十分なので以下修正案を出します
タイトル
> [SCOPE.sPoliticalLobby('relevant_lobby').GetName]による機会の提供
本文
> [ロビー団体名]から、[第三国][指示内容]してはどうかと申し出があった。この申し出を受けるということは、[ロビーの対立国]の利益に対立するということである。

**Comment by inarizushi0309** [comment]
上記内容で修正しました。起票ありがとうございました。
