### ISSUE TITLE
外交戦の自信レベル要因

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#957]
### スクリーンショット

![image](https://github.com/user-attachments/assets/79e65fdf-1cff-4150-8d1b-b11317df4a26)

### 問題のツールチップ

外交戦画面>自身レベルマウスオーバー

### 問題の表現

①```基本値による#bold $VALUE|+=$#!```
②```$NAME|v$ [concept_ai_strategy]による#bold $VALUE|+=$#!```
③```どちらも強く支持していないことによる#bold $VALUE|+=$#!```
④```[Country.GetAdjective]の[concept_loans]の規模による#bold $VALUE|+=$#!```
⑤```[Country.GetAdjective]の[concept_gold_reserves]の規模による#bold $VALUE|+=$#!```
⑥```[Country.GetName]の[concept_devastation]による#bold $VALUE|+=$#!```
⑦```[Country.GetName]の[concept_turmoil]による#bold $VALUE|+=$#!```
⑧```[concept_native_uprising]による#bold $VALUE|+=$#!```
⑨```自国の[concept_subject]が[concept_diplomatic_play]に関与することによる#bold $VALUE|+=$#!```
⑩```$NAME|v$にいて[Country.GetAdjective]が関与することによる#bold $VALUE|+=$#!```
⑪```[Country.GetAdjective]軍の弱点による#bold $VALUE|+=$#!```
⑫```[Country.GetAdjective]軍の強みによる#bold $VALUE|+=$#!```
⑬```低[concept_rank]の参加者による#bold $VALUE|+=$#!```
⑭```[concept_neutrality]は$VALUE|v$以下になることはできません```
⑮```相対的な軍事力と[Concept('concept_mobilize_army', '$concept_mobilize_army_mobilization$')]レベルによる#bold $VALUE|+=$#!```
⑯```[Country.GetName]の[Concept('concept_loyalist','$concept_loyalists$')]の数による#bold $VALUE|+=$#!```
⑰```[concept_civil_war]または[concept_native_uprising]による#bold $VALUE|+=$#!```
⑱```短期間の[concept_war]による#bold $VALUE|+=$#!```
⑲```[Country.GetName]が[concept_bankruptcy]状態にあることによる#bold $VALUE|+=$#!```
⑳```引き下がれば併合される可能性があることによる#bold $VALUE|+=$#!```
㉑```$war_goal_contain_threat_type_name$のプレイによる#bold $VALUE|+=$#!```
㉒```#bold $VALUE|+=$#!: 主要な参加国の1つとの[concept_truce]に由来```

### 問題箇所の英文

①```#bold $VALUE|+=$#! from Base Value```
②```#bold $VALUE|+=$#! from $NAME|v$ [concept_ai_strategy]```
③```#bold $VALUE|+=$#! from No strong preference for either side```
④```#bold $VALUE|+=$#! from Size of [Country.GetAdjective] [concept_loans]```
⑤```#bold $VALUE|+=$#! from Size of [Country.GetAdjective] [concept_gold_reserves]```
⑥```#bold $VALUE|+=$#! from [concept_devastation] in [Country.GetName]```
⑦```#bold $VALUE|+=$#! from [concept_turmoil] in [Country.GetName]```
⑧```#bold $VALUE|+=$#! from [concept_native_uprising]```
⑨```#bold $VALUE|+=$#! from [concept_diplomatic_play] involves our [concept_subject]```
⑩```#bold $VALUE|+=$#! from [Country.GetAdjective] involvement in $NAME|v$```
⑪```#bold $VALUE|+=$#! from Weakness of [Country.GetAdjective] army```
⑫```#bold $VALUE|+=$#! from Strength of [Country.GetAdjective] army```
⑬```#bold $VALUE|+=$#! from Low [concept_rank] of participants```
⑭```[concept_neutrality] can never be less than $VALUE|v$```
⑮```#bold $VALUE|+=$#! from Relative military strength and level of [Concept('concept_mobilize_army', '$concept_mobilize_army_mobilization$')]```
⑯```#bold $VALUE|+=$#! from Number of [Concept('concept_loyalist','$concept_loyalists$')] in [Country.GetName]```
⑰```#bold $VALUE|+=$#! from [concept_civil_war] or [concept_native_uprising]```
⑱```#bold $VALUE|+=$#! from Short duration of [concept_war]```
⑲```#bold $VALUE|+=$#! from [Country.GetName] is in [concept_bankruptcy]```
⑳```#bold $VALUE|+=$#! from Would be annexed if they back down```
㉑```#bold $VALUE|+=$#! from $war_goal_contain_threat_type_name$ play```
㉒```#bold $VALUE|+=$#! from [concept_truce] with one of the primary participants```

### 希望する変更

①```#bold $VALUE|+=$#!(基本値)```
②```#bold $VALUE|+=$#!($NAME|v$の[concept_ai_strategy])```
③```#bold $VALUE|+=$#!(どちらにも強いこだわりはない)```
④```#bold $VALUE|+=$#!([Country.GetAdjective]の[concept_loans]規模)```
⑤```#bold $VALUE|+=$#!([Country.GetAdjective]の[concept_gold_reserves]規模)```
⑥```#bold $VALUE|+=$#!([Country.GetName]の[concept_devastation])```
⑦```#bold $VALUE|+=$#!([Country.GetName]の[concept_turmoil])```
⑧```#bold $VALUE|+=$#!([concept_native_uprising])```
⑨```#bold $VALUE|+=$#!(自国の[concept_subject]が[concept_diplomatic_play]に関与している)```
⑩```#bold $VALUE|+=$#!($NAME|v$における[Country.GetAdjective]の関与)```
⑪```#bold $VALUE|+=$#!([Country.GetAdjective]軍の弱さ)```
⑫```#bold $VALUE|+=$#!([Country.GetAdjective]軍の強さ)```
⑬```#bold $VALUE|+=$#!(参加国の[concept_rank]の低さ)```
⑭```[concept_neutrality]が$VALUE|v$未満になることはない```
⑮```#bold $VALUE|+=$#!(軍事力と[Concept('concept_mobilize_army', '$concept_mobilize_army_mobilization$')]レベルの比較)```
⑯```#bold $VALUE|+=$#!([Country.GetName]の[Concept('concept_loyalist','$concept_loyalists$')]の数)```
⑰```#bold $VALUE|+=$#!([concept_civil_war]または[concept_native_uprising])```
⑱```#bold $VALUE|+=$#!(短い[concept_war]期間)```
⑲```#bold $VALUE|+=$#!([Country.GetName]が[concept_bankruptcy]している)```
⑳```#bold $VALUE|+=$#!(引き下がった場合併合される)```
㉑```#bold $VALUE|+=$#!($war_goal_contain_threat_type_name$外交戦)```
㉒```#bold $VALUE|+=$#!(主要参加国の1つと[concept_truce]中)```

### 変更の理由（概要）

見づらい

### プレイ国家

フランス

### ゲームバージョン

1.7.X

### MOD有無

日本語改善Mod

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案に微修正を加え以下の内容で修正しました
①#bold $VALUE|+=$#!(基本値)
②#bold $VALUE|+=$#!($NAME|v$の[concept_ai_strategy])
③#bold $VALUE|+=$#!(どちらにも強いこだわりはない)
④#bold $VALUE|+=$#!([Country.GetAdjective]の[concept_loans]規模)
⑤#bold $VALUE|+=$#!([Country.GetAdjective]の[concept_gold_reserves]規模)
⑥#bold $VALUE|+=$#!([Country.GetName]の[concept_devastation])
⑦#bold $VALUE|+=$#!([Country.GetName]の[concept_turmoil])
⑧#bold $VALUE|+=$#!([concept_native_uprising])
⑨#bold $VALUE|+=$#!(自国の[concept_subject]が[concept_diplomatic_play]に関与している)
⑩#bold $VALUE|+=$#!($NAME|v$における[Country.GetAdjective]の関与)
⑪#bold $VALUE|+=$#!([Country.GetAdjective]軍の弱さ)
⑫#bold $VALUE|+=$#!([Country.GetAdjective]軍の強さ)
⑬#bold $VALUE|+=$#!(参加国の[concept_rank]の低さ)
⑭[concept_neutrality]が$VALUE|v$未満になることはない
⑮#bold $VALUE|+=$#!(軍事力と[Concept('concept_mobilize_army', '$concept_mobilize_army_mobilization$')]レベルの比較)
⑯#bold $VALUE|+=$#!([Country.GetName]の[Concept('concept_loyalist','$concept_loyalists$')]の数)
⑰#bold $VALUE|+=$#!([concept_civil_war]または[concept_native_uprising])
⑱#bold $VALUE|+=$#!(短い[concept_war]期間)
⑲#bold $VALUE|+=$#!([Country.GetName]が[concept_bankruptcy]している)
⑳#bold $VALUE|+=$#!(引き下がった場合併合される)
㉑#bold $VALUE|+=$#!($war_goal_contain_threat_type_name$外交戦)
㉒#bold $VALUE|+=$#!(主要参加国の1つと[concept_truce]中)
