### ISSUE TITLE
消費税ツールチップ

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#958]
### スクリーンショット

![Victoria 3 Screenshot 2024 07 15 - 21 58 55 64](https://github.com/user-attachments/assets/9dd8d6ad-089d-47cc-948e-05e2e85ae7a0)

### 問題のツールチップ

消費税追加時のツールチップ

### 問題の表現

```GOODS_INTERACTION_INSUFFICIENT_AUT: "少なくとも[concept_authority]の @aut!$REQVAL|0=+$ を所持する"```

### 問題箇所の英文

```GOODS_INTERACTION_INSUFFICIENT_AUT:1 "Have at least @aut!$REQVAL|0=+$ [concept_authority]"```

### 希望する変更

```GOODS_INTERACTION_INSUFFICIENT_AUT: "少なくとも[concept_authority]@aut!$REQVAL|0=+$を所持している"```

### 変更の理由（概要）

不要な助詞

### 変更の理由（詳細）

「の」は不要

### プレイ国家

ロシア

### ゲームバージョン

1.7.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。
