### ISSUE TITLE
商品のツールチップ

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#959]
### スクリーンショット

![Victoria 3 Screenshot 2024 07 15 - 22 09 26 38](https://github.com/user-attachments/assets/4332c066-3216-4f40-8acf-69ba60511a67)

### 問題のツールチップ

各商品のツールチップ

### 問題の表現

財力レベル○～○(△△△需要)のPOPにより消費されています

### 希望する変更

財力レベル○～○(△△△に対する需要)のPOPにより消費されています
財力レベル○～○(△△△への需要)のPOPにより消費されています　等

文字追加により改行されてしまうようなら、最後の「されています」を削ってもよいかと思います。

### 変更の理由（概要）

日本語として不自然なため

### プレイ国家

ロシア

### ゲームバージョン

1.7.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
$WEALTHDESC$の[Concept('concept_pop', '$concept_pops$')]により消費されています([Concept('concept_pop_needs','$concept_pop_needs_short$')]:#tooltippable #tooltip:$TAG$,POPNEED_DETAILS_TOOLTIP [POP_NEED.GetName]#!#!)

**Comment by matanki-saito** [comment]
上記内容で確定しました
