### ISSUE TITLE
【未訳】非同盟国への勢力圏の支配力ツールチップ

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#960]
### スクリーンショット

![image](https://github.com/user-attachments/assets/bf3bac48-5cc9-4891-8199-31a71c7ebeeb)

### 問題のツールチップ

勢力圏に属していない国家の情報画面>国旗マウスオーバー

### 問題の表現

```$POWER_BLOC_CURRENT_LEVERAGE_ADVANTAGE_OVER_COUNTRY$: #v [Country.GetLeverageAdvantage(GetPlayer.GetPowerBloc.Self)|0=+]#! 対 [Country.GetName] for [GetPlayer.GetPowerBloc.GetName]```

### 問題箇所の英文

```$POWER_BLOC_CURRENT_LEVERAGE_ADVANTAGE_OVER_COUNTRY$: #v [Country.GetLeverageAdvantage(GetPlayer.GetPowerBloc.Self)|0=+]#! over [Country.GetName] for [GetPlayer.GetPowerBloc.GetName]```

### 希望する変更

```$POWER_BLOC_CURRENT_LEVERAGE_ADVANTAGE_OVER_COUNTRY$: #v [Country.GetLeverageAdvantage(GetPlayer.GetPowerBloc.Self)|0=+]#! [Country.GetName]から[GetPlayer.GetPowerBloc.GetName]に対し```

### 変更の理由（概要）

未翻訳

### プレイ国家

フランス

### ゲームバージョン

1.7.X

### MOD有無

日本語改善Mod

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通り修正しました。
