### ISSUE TITLE
【未訳】leverage補正のツールチップ

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#962]
### スクリーンショット

なし

### 問題のツールチップ

不明

### 問題の表現

#header $concept_power_bloc_leverage$ Factor for [PowerBloc.GetName]#!
数値: $VALUE|v0$
$TOOLTIP_DELIMITER$
$BREAKDOWN$

### 問題箇所の英文

#header $concept_power_bloc_leverage$ Factor for [PowerBloc.GetName]#!
Value: $VALUE|v0$
$TOOLTIP_DELIMITER$
$BREAKDOWN$

### 希望する変更

#header [PowerBloc.GetName]への$concept_power_bloc_leverage$補正#!
数値: $VALUE|v0$
$TOOLTIP_DELIMITER$
$BREAKDOWN$

### 変更の理由（概要）

未翻訳

### ゲームバージョン

1.7.X

### MOD有無

日本語改善Mod

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通り修正しました。
