### ISSUE TITLE
ジャーナル：アフガン再統一

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#964]
### スクリーンショット

![Victoria 3 Screenshot 2024 07 16 - 17 45 02 67](https://github.com/user-attachments/assets/23079ddd-4fde-4243-8450-2651f023a695)

### 問題のツールチップ

ジャーナル：アフガン再統一 ロシアに要請ツールチップ

### 問題の表現

```TRIGGER_EVENT_COUNTRY: "$COUNTRY_NAME$が、イベント#variable $EVENT_NAME$#![ConcatIfNeitherEmpty(' ', '$DELAY_DESCRIPTION$')]を発動させます"```
```AFG_appeal_accept_tt: "彼らが前向きな関係を求める可能性が高まります。彼らに対し【concept_obligation】を負うことになります。"```

### 問題箇所の英文

```TRIGGER_EVENT_COUNTRY:0 "$COUNTRY_NAME$ gets the Event #variable $EVENT_NAME$#![ConcatIfNeitherEmpty(' ', '$DELAY_DESCRIPTION$')]"```
```AFG_appeal_accept_tt: "They will be more likely to pursue positive relationships with you and you will owe them an [concept_obligation]"```

### 希望する変更

```TRIGGER_EVENT_COUNTRY: "$COUNTRY_NAME$が、[ConcatIfNeitherEmpty(' ', '$DELAY_DESCRIPTION$')]にイベント#variable $EVENT_NAME$#!を発動させます"```
```AFG_appeal_accept_tt: "彼らが前向きな関係を求める可能性が高まります。彼らに対し[concept_obligation]を負うことになります。"```

### 変更の理由（概要）

変数ミスほか

### 変更の理由（詳細）

・TRIGGER_EVENT_COUNTRY　→　日本語として自然になるように修正
・AFG_appeal_accept_tt　→　【】が使われているせいで変数として認識されていないのを修正

### プレイ国家

カブール

### ゲームバージョン

1.7.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
変数から日数指定がない場合があるようなので、以下代替案を出します
```$COUNTRY_NAME$で、[ConcatIfNeitherEmpty(' ', '$DELAY_DESCRIPTION$に')]イベント#variable $EVENT_NAME$#!を発生します```

**Comment by inarizushi0309** [comment]
議論の結果、上記修正案で確定しました。起票ありがとうございました。

**Comment by matanki-saito** [comment]
修正案でも不自然な場合が見受けられたので、以下のように修正しました
```[ConcatIfNeitherEmpty(' ', '$DELAY_DESCRIPTION$')]$COUNTRY_NAME$で、イベント#variable $EVENT_NAME$#!が発生します```
