### ISSUE TITLE
軍勢選択画面：損耗のツールチップ

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#965]
### スクリーンショット

![Victoria 3 Screenshot 2024 07 16 - 17 42 13 52](https://github.com/user-attachments/assets/a9e644cd-dc9a-449e-bc13-c8dc824f667d)

### 問題のツールチップ

軍勢選択画面：損耗のツールチップ

### 問題の表現

```MILITARY_FORMATION_ATTRITION_DESC: "#header [MilitaryFormation.GetName]の[concept_attrition]#!\n現在: $MILITARY_FORMATION_ATTRITION_RISK_ICON_VAL$[Nbsp][MilitaryFormation.GetAverageAttritionPerWeek|%1^-]\n$TOOLTIP_DELIMITER$\n#indent_newline:3 [MilitaryFormation.GetName]の[Concept('concept_unit', '$concept_units$')]は、毎週 [MilitaryFormation.GetAverageAttritionPerWeek|%1^-] [concept_casualties]を被ります。平均(#v $CASUALTIES|0-$#! @manpower![Nbsp][concept_manpower])。要因:\n#indent_newline:3 $MILITARY_FORMATION_ATTRITION_RISK_ICON_VAL$[Nbsp]$VAL|0%-$ 毎週の [concept_attrition] リスク\n$BREAKDOWN$#!\n$MIN|0%v$ から $MAX|0%v$ $concept_casualties$ when subjected to $concept_attrition$#!"```

### 問題箇所の英文

```MILITARY_FORMATION_ATTRITION_DESC: "#header [concept_attrition] in [MilitaryFormation.GetName]#!\nCurrent: $MILITARY_FORMATION_ATTRITION_RISK_ICON_VAL$[Nbsp][MilitaryFormation.GetAverageAttritionPerWeek|%1^-]\n$TOOLTIP_DELIMITER$\n#indent_newline:3 [Concept('concept_unit', '$concept_units$')] in [MilitaryFormation.GetName] will suffer [MilitaryFormation.GetAverageAttritionPerWeek|%1^-] [concept_casualties] per week (#v $CASUALTIES|0-$#! @manpower![Nbsp][concept_manpower]) on average, due to:\n#indent_newline:3 $MILITARY_FORMATION_ATTRITION_RISK_ICON_VAL$[Nbsp]$VAL|0%-$ weekly [concept_attrition] risk\n$BREAKDOWN$#!\n$MIN|0%v$ to $MAX|0%v$ $concept_casualties$ when subjected to $concept_attrition$#!"```

### 希望する変更

```MILITARY_FORMATION_ATTRITION_DESC: "#header [MilitaryFormation.GetName]の[concept_attrition]#!\n現在: $MILITARY_FORMATION_ATTRITION_RISK_ICON_VAL$[Nbsp][MilitaryFormation.GetAverageAttritionPerWeek|%1^-]\n$TOOLTIP_DELIMITER$\n#indent_newline:3 [MilitaryFormation.GetName]の[Concept('concept_unit', '$concept_units$')]は、毎週[MilitaryFormation.GetAverageAttritionPerWeek|%1^-]の[concept_casualties]を出します。平均(#v $CASUALTIES|0-$#! @manpower![Nbsp][concept_manpower])。要因:\n#indent_newline:3 $MILITARY_FORMATION_ATTRITION_RISK_ICON_VAL$[Nbsp]$VAL|0%-$ 毎週の [concept_attrition] リスク\n$BREAKDOWN$#!\n$concept_attrition$を受けた場合の$concept_casualties$ $MIN|0%v$ から $MAX|0%v$#!"```

### 変更の理由（概要）

未訳の部分がある、他

### 変更の理由（詳細）

未訳の部分がある
その他、日本語として不自然な部分を修正

### プレイ国家

カブール

### ゲームバージョン

1.7.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
議論の結果、以下のように修正しました
```#header [MilitaryFormation.GetName]の[concept_attrition]#!
現在: $MILITARY_FORMATION_ATTRITION_RISK_ICON_VAL$[Nbsp][MilitaryFormation.GetAverageAttritionPerWeek|%1^-]
$TOOLTIP_DELIMITER$
#indent_newline:3 [MilitaryFormation.GetName]の[Concept('concept_unit', '$concept_units$')]は、毎週平均で[MilitaryFormation.GetAverageAttritionPerWeek|%1^-]の[concept_casualties](#v $CASUALTIES|0-$#!@manpower![Nbsp][concept_manpower])を被ります。要因:
#indent_newline:3 週毎の[concept_attrition]リスク[Nbsp]$MILITARY_FORMATION_ATTRITION_RISK_ICON_VAL$[Nbsp]$VAL|0%-$
$BREAKDOWN$#!
$concept_attrition$を受けた場合の$concept_casualties$[Nbsp]$MIN|0%v$～$MAX|0%v$#!```
> 第1軍団の軍事ユニットは、毎週平均で0.4%の死傷者(200@人員)を被ります。要因:
週毎の損耗リスク @5%
$BREAKDOWN$
損耗を受けた場合の死傷者 4%～12%
