### ISSUE TITLE
軍勢選択画面：攻撃/防御ツールチップ

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#966]
### スクリーンショット

![Victoria 3 Screenshot 2024 07 16 - 18 23 16 40](https://github.com/user-attachments/assets/bdf7965f-9573-4f83-acc2-853adddc518d)
![Victoria 3 Screenshot 2024 07 16 - 18 23 25 94](https://github.com/user-attachments/assets/81ee97b3-bcd8-41ab-b8d5-724ad6239972)

### 問題のツールチップ

軍勢選択画面 攻撃/防御ツールチップ

### 問題の表現

```MILITARY_FORMATION_OFFENSE_TOOLTIP: "#header [concept_offense]#!\n@unit_offense! [MilitaryFormation.GetAverageOffenseExcludeUnavailableManpower|1v] [concept_offense]時の平均\n$TOOLTIP_DELIMITER$\n@unit_offense! 完全な[concept_manpower]での[MilitaryFormation.GetAverageOffense|1v] [concept_offense]時の平均"```
```MILITARY_FORMATION_DEFENSE_TOOLTIP: "#header [concept_defense]#!\n@unit_defense! [MilitaryFormation.GetAverageDefenseExcludeUnavailableManpower|1v] [concept_defense]時の平均\n$TOOLTIP_DELIMITER$\n@unit_defense! 完全な[concept_manpower]での[MilitaryFormation.GetAverageDefense|1v] [concept_defense]時の平均"```

### 問題箇所の英文

```MILITARY_FORMATION_OFFENSE_TOOLTIP: "#header [concept_offense]#!\n@unit_offense! [MilitaryFormation.GetAverageOffenseExcludeUnavailableManpower|1v] [concept_offense] on average\n$TOOLTIP_DELIMITER$\n@unit_offense! [MilitaryFormation.GetAverageOffense|1v] [concept_offense] on average at full [concept_manpower]"```
```MILITARY_FORMATION_DEFENSE_TOOLTIP: "#header [concept_defense]#!\n@unit_defense! [MilitaryFormation.GetAverageDefenseExcludeUnavailableManpower|1v] [concept_defense] on average\n$TOOLTIP_DELIMITER$\n@unit_defense! [MilitaryFormation.GetAverageDefense|1v] [concept_defense] on average at full [concept_manpower]"```

### 希望する変更

```MILITARY_FORMATION_OFFENSE_TOOLTIP: "#header [concept_offense]#!\n@unit_offense!平均[concept_offense]力[MilitaryFormation.GetAverageOffenseExcludeUnavailableManpower|1v]\n$TOOLTIP_DELIMITER$\n@unit_offense!完全[concept_manpower]での平均[concept_offense]力[MilitaryFormation.GetAverageOffense|1v]"```
```MILITARY_FORMATION_DEFENSE_TOOLTIP: "#header [concept_defense]#!\n@unit_defense!平均[concept_defense]力 [MilitaryFormation.GetAverageDefenseExcludeUnavailableManpower|1v]\n$TOOLTIP_DELIMITER$\n@unit_defense!完全[concept_manpower]での平均[concept_defense]力[MilitaryFormation.GetAverageDefense|1v]"```

### 変更の理由（概要）

日本語として不自然なため

### プレイ国家

カブール

### ゲームバージョン

1.7.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
代替案
```#header [concept_offense]#!\n平均[concept_offense]力@unit_offense![MilitaryFormation.GetAverageOffenseExcludeUnavailableManpower|1v]\n$TOOLTIP_DELIMITER$\n完全[concept_manpower]での平均[concept_offense]力@unit_offense![MilitaryFormation.GetAverageOffense|1v]```

**Comment by inarizushi0309** [comment]
議論の結果、アイコンを数値の直前に来るようにする案で修正することになりました。起票ありがとうございました。
