### ISSUE TITLE
【不具合】軍の士気値が表示されない

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/vic3jpadvmod#967]
### スクリーンショット

![image](https://github.com/user-attachments/assets/cfaa88b7-305a-41e2-a67f-03bee6f96716)
![image](https://github.com/user-attachments/assets/04b1441e-b211-4001-a44e-30beca755067)

### 問題のあるインターフェイス

軍団情報画面

### 問題のテキスト

なし

### 希望する変更

なし

### 変更の理由（概要）

不具合

### ゲームバージョン

1.7.X

### MOD有無

日本語改善Mod

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
MOD作成スクリプトに対応のパッチを当てました
https://github.com/matanki-saito/vic3jpadvmod/commit/b787a547cca71b8f244d54ac7ca571cbcb287de2
