### ISSUE TITLE
選挙画面：予想投票数のツールチップ

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#968]
### スクリーンショット

![Victoria 3 Screenshot 2024 07 16 - 22 08 52 27](https://github.com/user-attachments/assets/e2f4e3a7-2941-4f38-855a-a322031b5aed)

### 問題のツールチップ

選挙画面：予想投票数のツールチップ

### 問題の表現

```PROJECTED_PARTY_POL_STR_FROM_VOTES: "[Party.GetName]は[concept_votes]の[Party.GetProjectedVotesDesc]を獲得すると予想されます\nこれはその票数から彼らに[Party.GetCurrentPollVotingPower|Kv] [concept_political_strength]を与えるでしょう。これは前回の選挙結果と比較すると#v [Party.GetCurrentPollVotingPowerDifference|K+=]#!です"```

```PARTY_POL_STR_FROM_VOTES: "前回の選挙では、彼らは[concept_votes]の[party.GetCurrentVotingPowerShare|%0v]を獲得しました\nこの[SelectLocalization(Party.GetCountry.IsInElectionCampaignPeriod, 'CURRENTLY', '')]は、[party.GetCurrentVotingPower|Kv] [concept_political_strength]をメンバーに与えます"```

### 問題箇所の英文

```PROJECTED_PARTY_POL_STR_FROM_VOTES: "[Party.GetName] is projected to get [Party.GetProjectedVotesDesc] of the [concept_votes]\nThis would give them [Party.GetCurrentPollVotingPower|Kv] [concept_political_strength] from Votes, which is #v [Party.GetCurrentPollVotingPowerDifference|K+=]#! compared to the result of the last Election"```

```PARTY_POL_STR_FROM_VOTES: "Last Election they got [Party.GetCurrentVotingPowerShare|%0v] of the [concept_votes]\nThis [SelectLocalization(Party.GetCountry.IsInElectionCampaignPeriod, 'CURRENTLY', '')]provides their Members with [Party.GetCurrentVotingPower|Kv] [concept_political_strength]"```

### 希望する変更

```PROJECTED_PARTY_POL_STR_FROM_VOTES: "[Party.GetName]は[concept_votes]の[Party.GetProjectedVotesDesc]を獲得すると予想されます\nこれはその票数から彼らに[concept_political_strength][Party.GetCurrentPollVotingPower|Kv]を与えるでしょう。これは前回の選挙結果と比較すると#v [Party.GetCurrentPollVotingPowerDifference|K+=]#!です"```

```PARTY_POL_STR_FROM_VOTES: "前回の選挙では、彼らは[concept_votes]の[party.GetCurrentVotingPowerShare|%0v]を獲得しました\nこれは[SelectLocalization(Party.GetCountry.IsInElectionCampaignPeriod, 'CURRENTLY', '')]、[concept_political_strength][party.GetCurrentVotingPower|Kv]をメンバーに与えています"```

### 変更の理由（概要）

日本語の不自然な部分の修正

### プレイ国家

イギリス

### ゲームバージョン

1.7.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
代替案として以下出します
```[Party.GetName]は[concept_votes]の[Party.GetProjectedVotesDesc]を獲得すると予想されます。\nこれにより、票数由来の[concept_political_strength]が[Party.GetCurrentPollVotingPower|Kv]与えられます。前回の選挙結果と比較すると#v [Party.GetCurrentPollVotingPowerDifference|K+=]#!です。```
> [政党名]は投票の[N%]を獲得すると予想されます。
> これにより、票数由来の政治力が[数値]与えられます。前回の選挙結果と比較すると[±数値]です。
```前回の選挙では、[concept_votes]の[party.GetCurrentVotingPowerShare|%0v]を獲得しました。\nこれは[SelectLocalization(Party.GetCountry.IsInElectionCampaignPeriod, 'CURRENTLY', '')]、構成員に[party.GetCurrentVotingPower|Kv]の[concept_political_strength]を与えています。```
> 前回の選挙では、投票の[N%]を獲得しました。
> これは[※]、構成員に[数値]の政治力を与えています。
> ※には「現在」が入る場合と何も入らない場合がある

**Comment by inarizushi0309** [comment]
議論の結果、上記修正案で確定しました。起票ありがとうございました。
