### ISSUE TITLE
国家の形成ツールチップ

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#969]
### スクリーンショット

![Victoria 3 Screenshot 2024 07 17 - 17 43 09 12](https://github.com/user-attachments/assets/eddd2f4e-4b2f-43ed-93fe-97287fc89911)

### 問題のツールチップ

国家の形成ツールチップ

### 問題の表現

○○○国家の形成へ行く

### 希望する変更

○○○国家の形成へ進む

### 変更の理由（概要）

日本語として自然な感じに

### プレイ国家

ヘラート

### ゲームバージョン

1.7.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。
