### ISSUE TITLE
【修正提案】Wood

### ISSUE THREAD

**Issue by clamm0363** [matanki-saito/vic3jpadvmod#97]
＜ゲームシステム用語＞

## スクリーンショット（任意）
※画像はドラッグ＆ドロップで貼り付けられます。
※できるだけ問題箇所の前後を含めて貼ってください。

## 問題の用語（必須）

木

## 英語版の表現（任意）

Wood

## 希望する変更（必須）

木材

## 変更の理由（必須）

資源としてより適切な用語にしたい

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

Grand Edition

## MOD有無（必須）

フォント置き換えMOD

**Comment by matanki-saito** [comment]
内部検討中です。進捗がありましたらここに報告します。校正メンバーと議論が必要である場合はお手数ですが#github議論板にて確認をお願い致します。
---
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1035252635814592542

**Comment by clamm0363** [comment]
議論の結果「軟材」となりました。

クローズします。
