### ISSUE TITLE
体制派と急進派グラフ選択時のツールチップ

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#970]
### スクリーンショット

![Victoria 3 Screenshot 2024 07 17 - 17 52 12 26](https://github.com/user-attachments/assets/dae6872a-b092-41d8-8b4b-6196a6a9a9d7)

### 問題のツールチップ

体制派と急進派グラフ選択時のツールチップ

### 問題の表現

```NEUTRALS_TOOLTIP: "#tooltip_header $NEUTRALS$#!\n[Country.GetName]の総人口#v [Country.GetTotalPopulation|*2]#!の中に#v [Country.GetNumNeutrals|*2]#!人の$NEUTRALS$がいます。"```

### 問題箇所の英文

```NEUTRALS_TOOLTIP: "#tooltip_header $NEUTRALS$#!\nThere are #v [Country.GetNumNeutrals|*2]#! $NEUTRALS$ in the total population of #v [Country.GetTotalPopulation|*2]#! in [Country.GetName]"```

### 希望する変更

```NEUTRALS_TOOLTIP: "#tooltip_header $NEUTRALS$#!\n[Country.GetName]の総人口#v [Country.GetTotalPopulation|*2]#!のうち#v [Country.GetNumNeutrals|*2]#!人が$NEUTRALS$です。"```

### 変更の理由（概要）

日本語として不自然なため

### 変更の理由（詳細）

体制派、急進派を選択した場合の文章は特に不自然ではありませんが、
上記中立の変更に合わせて文章を修正しても良いかと思います。

### プレイ国家

ヘラート

### ゲームバージョン

1.7.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
起票ありがとうございます。ご指摘の箇所だけでなく、国全体/IG×体制派/急進派/中立の計2×3=6エントリについて、この指摘を反映させる改訳を行いました。
