### ISSUE TITLE
州画面：生活水準選択時のツールチップ

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#971]
### スクリーンショット

![Victoria 3 Screenshot 2024 07 17 - 17 44 44 13](https://github.com/user-attachments/assets/f8132ae5-d165-4961-baff-edf3d68c831d)

### 問題のツールチップ

州画面　生活水準選択時のツールチップ

### 問題の表現

```NUM_SOL: "#header [State.GetName]の[concept_sol]#!\n現在の平均: [LabelingHelper.GetLabelForStandardOfLivingCFixedPoint(State.GetAverageStandardOfLivingAll)|v] (#tooltippable #tooltip:[State.GetTooltipTag],STATE_SOL_ALL [State.GetAverageStandardOfLivingAll|1v]#!#!)\n$TOOLTIP_DELIMITER$\n平均$EXPECTED_SOL_SHORT$: [LabelingHelper.GetLabelForStandardOfLivingCFixedPoint(State.GetExpectedStandardOfLivingAll)|v] (#tooltippable #tooltip:[State.GetTooltipTag],STATE_EXPECTED_SOL_ALL [State.GetExpectedStandardOfLivingAll|v1]#!#!)\n of [Concept('concept_pop', '$concept_pops$')]の[State.GetPopulationRatioBelowExpectedStandardOfLiving|%v1]の[concept_sol] $EXPECTED_SOL_SHORT$を下回っています"```

### 問題箇所の英文

```NUM_SOL:2 "#header [concept_sol]#! in [State.GetName]\nAverage Current: [LabelingHelper.GetLabelForStandardOfLivingCFixedPoint(State.GetAverageStandardOfLivingAll)|v] (#tooltippable #tooltip:[State.GetTooltipTag],STATE_SOL_ALL [State.GetAverageStandardOfLivingAll|1v]#!#!)\n$TOOLTIP_DELIMITER$\nAverage $EXPECTED_SOL_SHORT$: [LabelingHelper.GetLabelForStandardOfLivingCFixedPoint(State.GetExpectedStandardOfLivingAll)|v] (#tooltippable #tooltip:[State.GetTooltipTag],STATE_EXPECTED_SOL_ALL [State.GetExpectedStandardOfLivingAll|v1]#!#!)\n[State.GetPopulationRatioBelowExpectedStandardOfLiving|%v1] of [Concept('concept_pop', '$concept_pops$')] have a [concept_sol] below $EXPECTED_SOL_SHORT$"```

### 希望する変更

```NUM_SOL: "#header [State.GetName]の[concept_sol]#!\n現在の平均: [LabelingHelper.GetLabelForStandardOfLivingCFixedPoint(State.GetAverageStandardOfLivingAll)|v] (#tooltippable #tooltip:[State.GetTooltipTag],STATE_SOL_ALL [State.GetAverageStandardOfLivingAll|1v]#!#!)\n$TOOLTIP_DELIMITER$\n平均$EXPECTED_SOL_SHORT$: [LabelingHelper.GetLabelForStandardOfLivingCFixedPoint(State.GetExpectedStandardOfLivingAll)|v] (#tooltippable #tooltip:[State.GetTooltipTag],STATE_EXPECTED_SOL_ALL [State.GetExpectedStandardOfLivingAll|v1]#!#!)\n[Concept('concept_pop', '$concept_pops$')]の[State.GetPopulationRatioBelowExpectedStandardOfLiving|%v1]が[concept_sol]の$EXPECTED_SOL_SHORT$を下回っています"```

### 変更の理由（概要）

日本語として不自然なため（一部未訳）

### プレイ国家

ヘラート

### ゲームバージョン

1.7.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通り修正しました。起票ありがとうございました。
