### ISSUE TITLE
州の情報画面

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#972]
### スクリーンショット

![Victoria 3 Screenshot 2024 07 18 - 17 56 05 66](https://github.com/user-attachments/assets/66315c8f-9fd1-4f70-9dd8-32ee1809f0bf)

### 問題のあるインターフェイス

州の情報画面の補正一覧

### 問題のテキスト

```building_group_bg_oil_extraction_engineers_mortality_mult: "原油抽出にに就業している$engineers$の[Concept('concept_pop_growth', '$concept_pop_growth_mortality$')]"```

### 希望する変更

```building_group_bg_oil_extraction_engineers_mortality_mult: "原油抽出に就業している$engineers$の[Concept('concept_pop_growth', '$concept_pop_growth_mortality$')]"```

### 変更の理由（概要）

誤字の修正

### ゲームバージョン

1.7.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
誤字脱字扱いで即時修正しました。起票ありがとうございました。
