### ISSUE TITLE
施設建設時のツールチップ

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#973]
### スクリーンショット

![Victoria 3 Screenshot 2024 07 17 - 23 13 32 68](https://github.com/user-attachments/assets/a14d7235-63be-42e1-b481-c4f96d61556c)

### 問題のツールチップ

施設建設時のツールチップ

### 問題の表現

予想収益：○○○/週
○○○　予想される生産性

### 希望する変更

予想収益：○○○/週
予想生産性：○○○

### 変更の理由（概要）

表記の統一

### 変更の理由（詳細）

収益と生産性で表記が違うので統一したい

### プレイ国家

どこでも

### ゲームバージョン

1.7.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通り修正しました。起票ありがとうございました。
