### ISSUE TITLE
マップ上通知：施設建設完了時の通知

### ISSUE THREAD

**Issue by flowlanss** [matanki-saito/vic3jpadvmod#974]
### スクリーンショット

![20240718191002_1](https://github.com/user-attachments/assets/4e6f1233-9997-44d8-94cc-f2f2a9ba28c8)

### 問題のあるインターフェイス

マップ上の通知

### 問題のテキスト

```
[SCOPE.GetRootScope.GetBuilding.GetName]は、[SCOPE.GetRootScope.GetBuilding.GetState.GetName]において[SelectLocalization(GreaterThan_int32(SCOPE.GetRootScope.GetBuilding.GetExpansionLevel,'(int32)1'),'NOTIFICATION_BUILDING_EXPANDED_SUBSEQUENT_LEVEL','NOTIFICATION_BUILDING_EXPANDED_FIRST_LEVEL')]です
```

### 希望する変更

[SCOPE.GetRootScope.GetBuilding.GetName]が[SCOPE.GetRootScope.GetBuilding.GetState.GetName]において[SelectLocalization(GreaterThan_int32(SCOPE.GetRootScope.GetBuilding.GetExpansionLevel,'(int32)1'),'NOTIFICATION_BUILDING_EXPANDED_SUBSEQUENT_LEVEL','NOTIFICATION_BUILDING_EXPANDED_FIRST_LEVEL')]

### 変更の理由（概要）

重複表現

### 変更の理由（詳細）

現行
新設時：「伐採所は、四国において建設されましたです」
拡張時：「伐採所は、四国において拡張されましたです」

期待される文
新設時：「伐採所が四国において建設されました」
拡張時：「伐採所が四国において拡張されました」

「において」は少し迂遠な感じもして、「で」にしてもいいかもしれません(「伐採所が四国で建設されました」)

### ゲームバージョン

1.7.X

### MOD有無

日本語改善Mod、Universal Names、1.7.5Unofficial Hotfix Mod

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by flowlanss** [comment]
「伐採所が四国で建設されました」というフォーマットになるように修正しました。

**Comment by flowlanss** [comment]
クローズします
