### ISSUE TITLE
イベント：皇帝の摂政

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#977]
### スクリーンショット

![Victoria 3 Screenshot 2024 07 19 - 18 38 49 24](https://github.com/user-attachments/assets/a06a3c31-f7a7-4f07-8be2-caab07310ba2)

### 問題部分

本文

### 問題のイベントタイトル

皇帝の摂政

### 問題のイベント本文（抜粋可）

千年以上にわたって王のゲームと称賛されてきたチェスは、戦略的な洞察力を重視する。長期の戦略には犠牲とコスト計算、そして高い技能が必要だ。1人のプレイヤーがミスをすると、別のプレイヤーがボードをコントロールできることになります。

### 希望する変更（修正部分のみ）

千年以上にわたって王のゲームと称賛されてきたチェスは、戦略的な洞察力を重視する。長期の戦略には犠牲とコスト計算、そして高い技能が必要だ。1人のプレイヤーがミスをすると、別のプレイヤーがボードをコントロールできることになる。

### 変更の理由（概要）

文末の不統一

### 変更の理由（詳細）

文末を常体で統一したい。

### プレイ国家

ブラジル

### ゲームバージョン

1.7.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
誤字脱字と同じ扱いで即修正しました。起票ありがとうございました。
