### ISSUE TITLE
正当性不足のアラート

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#979]
### スクリーンショット

![Victoria 3 Screenshot 2024 07 19 - 22 52 07 94](https://github.com/user-attachments/assets/86fd8337-5a68-43cd-918c-4a50e5b4a63e)

### 問題のあるインターフェイス

正当性不足のアラート

### 問題のテキスト

これは政策パネルの憲法タブから行うことができます。

### 希望する変更

これは政策パネルの法律タブから行うことができます。

### 変更の理由（概要）

タブの名前の変更

### 変更の理由（詳細）

法律の変更を行うタブの名前は法律タブであり、修正したい

### ゲームバージョン

1.7.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。
