### ISSUE TITLE
戦争時の画面上部の国名が、途切れていたり変数が直接出ていたりする

### ISSUE THREAD

**Issue by WoodlandsGitHub** [matanki-saito/vic3jpadvmod#98]
## スクリーンショット（必須）
![image](https://user-images.githubusercontent.com/29177147/198365343-f686bb47-be5a-4e99-9c61-4c0c17879c8e.png)

## 問題のツールチップ（必須）

戦争時の画面、上部の戦争当事国の名前のツールチップ

## 問題の表現（必須）

急進的な[COUNTRY.GetDefinition.GetName]対～～～

## 問題箇所の英文（任意）

content_1_l_japanese.yml
generic_revolt_radical:0 "急進的な[COUNTRY.GetDefinition.GetName]"

## 希望する変更（必須）

変数名に国名が表示されてほしい

## 変更の理由（必須）

変数名そのままはおかしいので

## ゲームバージョン（必須）

1.0.3

## DLC有無（必須）

なし

## MOD有無（必須）

なし

**Comment by matanki-saito** [comment]
内部検討中です。進捗がありましたらここに報告します。校正メンバーと議論が必要である場合はお手数ですが#github議論板にて確認をお願い致します。
---
Discord:https://discord.com/channels/1022767005662724096/1033342609453752370/1035258773989773343

**Comment by BLACKTIGER-NB** [comment]
似たような現象起きたんですけどね。
```
「
![急進的ファシスト2](https://user-images.githubusercontent.com/75819188/200084270-0e2e8bed-efcb-4bcb-94cb-49cbf3c0f9e3.jpg)
![急進的ファシスト](https://user-images.githubusercontent.com/75819188/200084280-7a19c9f7-1afc-4c53-a1e2-a76458eae545.jpg)

急進的な」「ファシスト的な」オランダ領東インド
```
私はゲーム本体側の問題を疑いますね。
反乱関係は挙動があやしいです

ゲームverはたぶん1.03

**Comment by matanki-saito** [comment]
すみません、あらためてforumを確認したところ、かなり報告されている事例のようでした。
https://forum.paradoxplaza.com/forum/threads/victoria-iii-liberal-revolts-missing-country-names.1553731/

一旦QA側には伝わったとみなしてチケットはCloseしようと思います
