### ISSUE TITLE
上陸作戦画面タイトル

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#980]
### スクリーンショット

![Victoria 3 Screenshot 2024 07 19 - 22 53 25 33](https://github.com/user-attachments/assets/c8378476-8d83-4f41-a933-5313cd6ab5a2)

### 問題のあるインターフェイス

上陸作戦設定画面のタイトル

### 問題のテキスト

上陸作戦[地名]

### 希望する変更

[地名]に対する上陸作戦
[地名]への上陸作戦　　　等

### 変更の理由（概要）

日本語として不自然なため

### ゲームバージョン

1.7.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
議論の結果、「～上陸作戦」の形（助詞なし）になるよう修正しました。起票ありがとうございました。
