### ISSUE TITLE
人種隔離にマクランを強制する

### ISSUE THREAD

**Issue by kurutto115** [matanki-saito/vic3jpadvmod#981]
### スクリーンショット

![s-Victoria 3 2024_07_18 6_23_00](https://github.com/user-attachments/assets/217b7247-4b66-4d32-89bd-243e5f4920b5)

### 問題のツールチップ

従属国に法改正を強制するコマンドのマウスオンヒント

### 問題の表現

人種隔離にマクランを強制する
これにより、市民権法律のため、マクランはから国民至上人種隔離へと変更することを余儀なくされます

### 問題箇所の英文

Impose Racial Segregation on Makran
This would force Makran to change from National Supremacy to Racial Segregation as their Citizenship Law

### 希望する変更

マクランに人種隔離を強制する
これによりマクランは、市民権に関する法律を国民至上から人種隔離へと変更することを余儀なくされます。

### 変更の理由（概要）

語順のミス

### 変更の理由（詳細）

主に語順の誤りにより文章が乱れているのを修正したい

### プレイ国家

イギリス

### ゲームバージョン

1.7.X

### MOD有無

本プロジェクトMODのみ

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案に従い以下のように修正しました。起票ありがとうございました。
```#header [Law.GetName]に[Law.GetCountry.GetName]を強制する#!\n$TOOLTIP_DELIMITER$\n[SelectLocalization(Not(StringIsEmpty(GetDesc( Law.StartImposing ))), 'FORCE_SUBJECT_TRIGGERS', '' )]これにより[Law.GetCountry.GetName]は、[Law.GetGroup.GetName]に関する[concept_law]を[Law.GetActiveGroupLaw.GetName]から[Law.GetName]へと変更することを余儀なくされます。[ConcatIfNeitherEmpty('\n', SelectLocalization(Not(StringIsEmpty(Law.GetOnImposeDesc)), 'FORCE_SUBJECT_EFFECTS', '' ))]```

**Comment by kurutto115** [comment]
![s-Victoria 3 2024_07_24 20_50_32](https://github.com/user-attachments/assets/96be3c4e-6287-4e4d-bceb-2e823c20bc41)
１行目が修正されないままになっているので、修正いただけないでしょうか

**Comment by inarizushi0309** [comment]
修正漏れていました。失礼しました。
