### ISSUE TITLE
イベント：聖別式

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#982]
### スクリーンショット

![Victoria 3 Screenshot 2024 07 11 - 18 26 08 89](https://github.com/user-attachments/assets/43a5eae5-a25d-4949-9622-2fde00b97ebe)

### 問題部分

本文

### 問題のイベントタイトル

聖別式

### 問題のイベント本文（抜粋可）

cristo_redentor.2.f: "山に立ち込めた霧の中、投光器の光が一箇所に集中し、最後の作品を浮かび上がらせた。神の子羊は[SCOPE.sState('rio-state').GetCityHubName]を見下ろす大きな台座の上に立ち、両手を広げ、すべての人を迎え入れようとしていた。信奉者であろうと、工芸品の愛好家であろうと、今や誰もがこの技術の粋を集めた傑作を鑑賞することができる。"

### 希望する変更（修正部分のみ）

変数[SCOPE.sState('rio-state').GetCityHubName]がうまく表示されるように

### 変更の理由（概要）

変数記述ミス

### 変更の理由（詳細）

[SCOPE.sState('rio-state').GetCityHubName]がうまく表示されていない
'rio-state'の部分は英語版では'rio_state'となっており、これが原因と思われる

※関連イベントであるモニュメント・ウィークのイベント文にも同様の記述ミスがあり、
これも一緒に修正していただきたいです。

cristo_redentor.1.d: "[SCOPE.sState('rio-state').GetName]のカトリック集団はコルコバード山の頂上にイエス・キリスト像を建設する案を発表した。同組織はその建設に使われる多額の資金を集めている。"

### プレイ国家

ブラジル

### ゲームバージョン

1.7.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
誤字脱字ということで即時修正しました。起票ありがとうございました。
