### ISSUE TITLE
イベント：熱帯のパリ、マナウス

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#983]
### スクリーンショット

![Victoria 3 Screenshot 2024 07 08 - 23 59 08 66](https://github.com/user-attachments/assets/c16608e1-68da-4d4e-aa4f-2caefef0e541)

### 問題部分

本文

### 問題のイベントタイトル

熱帯のパリ、マナウス

### 問題のイベント本文（抜粋可）

amazonas.5.f: "[SCOPE.sState('amazon_state').GetCityHubName]にはあらゆる贅沢品が揃っている。ゴム男爵たちは競争心が強く、新たな流行は行き過ぎたほどの争いに発展する。街を歩くと、その暑さを除けば、まるでパリにいるような心地になれるだろう。"

### 希望する変更（修正部分のみ）

変数[SCOPE.sState('amazon_state').GetCityHubName]がうまく表示されるように

### 変更の理由（概要）

変数記述ミス

### 変更の理由（詳細）

[SCOPE.sState('amazon_state').GetCityHubName]がうまく表示されていない
'amazon_state'の部分は英語版では''amazonas_state_scope'となっており、これが原因と思われる

### プレイ国家

ブラジル

### ゲームバージョン

1.7.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
誤字脱字ということで即時修正しました。起票ありがとうございました。
