### ISSUE TITLE
制定中の法律のツールチップ

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#984]
### スクリーンショット

![Victoria 3 Screenshot 2024 07 04 - 17 55 54 49](https://github.com/user-attachments/assets/7f5c11f8-5719-4378-af47-8f8d22300563)

### 問題のツールチップ

制定中の法律のツールチップ

### 問題の表現

```LAW_ENACTMENT_PROGRESS: "#header [Concept('concept_enactment_of_laws', '$concept_enactment_of_laws_enacting$')] [Law.GetName]#!\n[Concept('concept_enactment_phase','$concept_enactment_phase_short$')]: [Law.GetCountry.GetCustom(Law.GetCurrentEnactmentPhaseKey)|v] (#v [Add_int32('(int32)1', Law.GetEnactmentPhase)]/[GetDefine('NPolitics','LAW_ENACTMENT_MAX_PHASES')]#!)\n$LAW_ENACTMENT_SETBACKS_LABEL$ [Law.GetEnactmentSetbackCount|-]/[Law.GetCountry.GetMaxLawEnactmentSetbacks|-]\n[SelectLocalization(EqualTo_CFixedPoint(Law.GetCountry.GetModifier.GetValueFor('country_cannot_enact_laws_bool'), '(CFixedPoint)0'), 'LAW_ENACTMENT_PROGRESS_NOT_STALLED', 'LAW_ENACTMENT_PROGRESS_STALLED')][ConcatIfNeitherEmpty('\n\n', Law.PredictLegitimacyChangeToEnactDesc)]\n$TOOLTIP_DELIMITER$\n$LAW_ENACTMENT_OUTCOME_BREAKDOWN$[AddLocalizationIf(Law.HasEnactmentLastCheckpoint,'LAW_ENACTMENT_LAST_CHECKPOINT')]"```

### 希望する変更

```LAW_ENACTMENT_PROGRESS: "#header [Law.GetName]を[Concept('concept_enactment_of_laws', '$concept_enactment_of_laws_enacting$')] #!\n[Concept('concept_enactment_phase','$concept_enactment_phase_short$')]: [Law.GetCountry.GetCustom(Law.GetCurrentEnactmentPhaseKey)|v] (#v [Add_int32('(int32)1', Law.GetEnactmentPhase)]/[GetDefine('NPolitics','LAW_ENACTMENT_MAX_PHASES')]#!)\n$LAW_ENACTMENT_SETBACKS_LABEL$ [Law.GetEnactmentSetbackCount|-]/[Law.GetCountry.GetMaxLawEnactmentSetbacks|-]\n[SelectLocalization(EqualTo_CFixedPoint(Law.GetCountry.GetModifier.GetValueFor('country_cannot_enact_laws_bool'), '(CFixedPoint)0'), 'LAW_ENACTMENT_PROGRESS_NOT_STALLED', 'LAW_ENACTMENT_PROGRESS_STALLED')][ConcatIfNeitherEmpty('\n\n', Law.PredictLegitimacyChangeToEnactDesc)]\n$TOOLTIP_DELIMITER$\n$LAW_ENACTMENT_OUTCOME_BREAKDOWN$[AddLocalizationIf(Law.HasEnactmentLastCheckpoint,'LAW_ENACTMENT_LAST_CHECKPOINT')]"```

### 変更の理由（概要）

日本語として自然になるように

### プレイ国家

ブラジル

### ゲームバージョン

1.7.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通り修正しました。起票ありがとうございました。
