### ISSUE TITLE
イベント：ヨーロッパの病人

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#985]
### スクリーンショット

![Victoria 3 Screenshot 2024 07 20 - 18 40 03 75](https://github.com/user-attachments/assets/83debe1a-9e38-4a61-81e9-e7c759b8b999)

### 問題部分

本文

### 問題のイベントタイトル

ヨーロッパの病人

### 問題のイベント本文（抜粋可）

```sick_man.1.f: "私たちは失墜したが、再び立ち上がることができる。良き前触れとして、私たちは何世紀にもわたって権力をみじめに維持してきたイェニチェリを解体し、ついに改革の可能性を手に入れたのです。まだやるべきことはたくさんあります。まず、真に近代的な軍隊でイェニチェリ軍団を置き換える必要があるのは言うまでもありません。しかし、それに加えて、文明の最高峰としての崇高なるポルトの地位を回復しなければなりません。また、教育、都市化、そして主権は、[ROOT.GetCountry.GetAdjectiveNoFormatting]における課題の最優先事項でなければなりません。"```

### 希望する変更（修正部分のみ）

```sick_man.1.f: "私たちは失墜したが、再び立ち上がることができる。良き前触れとして、私たちは何世紀にもわたって権力をみじめに維持してきたイェニチェリを解体し、ついに改革の可能性を手に入れた。まだやるべきことはたくさんある。まず、真に近代的な軍隊でイェニチェリ軍団を置き換える必要があるのは言うまでもない。しかし、それに加えて、文明の最高峰としての崇高なるポルトの地位を回復しなければならない。また、教育、都市化、そして主権は、[ROOT.GetCountry.GetAdjectiveNoFormatting]における課題の最優先事項である必要がある。"```

### 変更の理由（概要）

常体への統一

### 変更の理由（詳細）

常体と敬体が混在しているので、常体に統一したい

### プレイ国家

オスマン帝国

### ゲームバージョン

1.7.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
即時修正しました。起票ありがとうございました。
