### ISSUE TITLE
圧力団体結成時のフィードの文章

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#986]
### スクリーンショット

![Victoria 3 Screenshot 2024 07 07 - 22 25 47 00](https://github.com/user-attachments/assets/0838ede6-f4d9-4bf9-9099-d30146d22b28)

### 問題のあるインターフェイス

圧力団体結成時のフィード

### 問題のテキスト

```notification_foreign_political_lobby_created_from_catalyst_desc: "[SCOPE.sDiplomaticCatalyst('diplomatic_catalyst').GetDesc]の結果、[SCOPE.sPoliticalLobby('political_lobby').GetCountry.GetName]に[SCOPE.sPoliticalLobby('political_lobby').GetName|v]が結成されました\n\nこの新しい[Concept('concept_political_lobby','$concept_political_lobby_short$')]は、[SCOPE.sPoliticalLobby('political_lobby').GetMembersDesc]で構成されています"```

### 希望する変更

可能であれば変数[SCOPE.sDiplomaticCatalyst('diplomatic_catalyst').GetDesc]の中身を過去形にし、
（スクショの例であれば、「○○が△△の州を征服した」）
[SCOPE.sDiplomaticCatalyst('diplomatic_catalyst').GetDesc]結果、～
と繋げれば文章的に不自然さがなくなると思われます。

### 変更の理由（概要）

文章が不自然なため

### ゲームバージョン

1.7.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
[SCOPE.sDiplomaticCatalyst('diplomatic_catalyst').GetDesc]の中身を列挙します

**Comment by matanki-saito** [comment]
1.their historical relationship with [TARGET_COUNTRY.GetName]
> 彼らの[TARGET_COUNTRY.GetName]との歴史的な関係

2.[TARGET_COUNTRY.GetName] becoming diplomatically relevant
> [TARGET_COUNTRY.GetName]が外交的に重要な存在になります

3.[TARGET_COUNTRY.GetName] becoming diplomatically irrelevant
> [TARGET_COUNTRY.GetName]が外交的に重要でない存在になります

4.[TARGET_COUNTRY.GetName] funded the creation of a new [concept_political_lobby]
> [TARGET_COUNTRY.GetName]が新たな[concept_political_lobby]の結成に資金を提供しました

5.an increase in [concept_relations] with [TARGET_COUNTRY.GetName]
> [TARGET_COUNTRY.GetName]との[concept_relations]の向上

6.a decrease in [concept_relations] with [TARGET_COUNTRY.GetName]
> [TARGET_COUNTRY.GetName]との[concept_relations]の悪化

7.making a [concept_diplomatic_demand] against [TARGET_COUNTRY.GetName]
> [TARGET_COUNTRY.GetName]に対する[concept_diplomatic_demand]を実行

8.being the target of a [concept_diplomatic_demand] from [TARGET_COUNTRY.GetName]
> [TARGET_COUNTRY.GetName]の[concept_diplomatic_demand]のターゲットになります

9.launching a [concept_diplomatic_play] against [TARGET_COUNTRY.GetName]
> [TARGET_COUNTRY.GetName]に対する[concept_diplomatic_play]を開始

10.being the target of a [concept_diplomatic_play] from [TARGET_COUNTRY.GetName]
> [TARGET_COUNTRY.GetName]の[concept_diplomatic_play]のターゲットになります

11.becoming more autonomous from [TARGET_COUNTRY.GetName]
> [TARGET_COUNTRY.GetName]からさらに独立します

12.becoming less autonomous from [TARGET_COUNTRY.GetName]
> [TARGET_COUNTRY.GetName]にさらに依存します

13.becoming fully independent of [TARGET_COUNTRY.GetName]
> [TARGET_COUNTRY.GetName]から完全に独立します

14.becoming the [concept_overlord] of [TARGET_COUNTRY.GetName]
> [TARGET_COUNTRY.GetName]の[concept_overlord]になります

15.becoming a [concept_subject] of [TARGET_COUNTRY.GetName]
> [TARGET_COUNTRY.GetName]の[concept_subject]になります

**Comment by matanki-saito** [comment]
forming a [concept_diplomatic_pact] with [TARGET_COUNTRY.GetName]
> [TARGET_COUNTRY.GetName]と[concept_diplomatic_pact]を締結します

17.breaking a [concept_diplomatic_pact] with [TARGET_COUNTRY.GetName]
> [TARGET_COUNTRY.GetName]との[concept_diplomatic_pact]を破棄します

18.entering an [concept_alliance] or [concept_defensive_pact] with [TARGET_COUNTRY.GetName]
> [TARGET_COUNTRY.GetName]が[concept_defensive_pact]または[concept_alliance]関係になりました

19.breaking off an [concept_alliance] or [concept_defensive_pact] with [TARGET_COUNTRY.GetName]
> [TARGET_COUNTRY.GetName]の[concept_defensive_pact]または[concept_alliance]が解消されました

20.[TARGET_COUNTRY.GetName] declaring a [concept_rivalry] with [COUNTRY.GetName]
> [TARGET_COUNTRY.GetName]が[COUNTRY.GetName]との[concept_rivalry]を宣言します

21.[TARGET_COUNTRY.GetName] becoming allied to a [COUNTRY.GetAdjective] [Concept('concept_rivalry','$concept_rival$')]
> [TARGET_COUNTRY.GetName]が[COUNTRY.GetAdjective]の[Concept('concept_rivalry','$concept_rival$')]と同盟関係になります

22.[TARGET_COUNTRY.GetName] declaring a [concept_rivalry] against a [COUNTRY.GetAdjective] $concept_rival$
> [TARGET_COUNTRY.GetName]が[COUNTRY.GetAdjective]の$concept_rival$に対し[concept_rivalry]関係を宣言します

23.an increase in [concept_relations] with a [COUNTRY.GetAdjective] $concept_rival$
> [COUNTRY.GetAdjective]の$concept_rival$との[concept_relations]改善

24.a decrease in [concept_relations] with a [COUNTRY.GetAdjective] $concept_rival$
> [COUNTRY.GetAdjective]の$concept_rival$との[concept_relations]悪化

25.becoming enemies with [TARGET_COUNTRY.GetName] in a [concept_diplomatic_play]
> [concept_diplomatic_play]において[TARGET_COUNTRY.GetName]と敵同士になります

26.becoming allies with [TARGET_COUNTRY.GetName] in a [concept_diplomatic_play]
> [concept_diplomatic_play]において[TARGET_COUNTRY.GetName]と味方同士になります

27.[TARGET_COUNTRY.GetName] enforcing a [concept_war_goal] on [COUNTRY.GetName]
> [TARGET_COUNTRY.GetName]が[COUNTRY.GetName]に対する[concept_war_goal]を実行します

**Comment by matanki-saito** [comment]
28.[TARGET_COUNTRY.GetName] conquering a [concept_state] from [COUNTRY.GetName]
> [TARGET_COUNTRY.GetName]が[COUNTRY.GetName]の[concept_state]を征服します

29.[COUNTRY.GetName] changing their [concept_ai_strategy]
> [COUNTRY.GetName]が[concept_ai_strategy]を変更します

30.[TARGET_COUNTRY.GetName] showed their weakness by declaring [concept_bankruptcy]
> [TARGET_COUNTRY.GetName]は[concept_bankruptcy]を宣言して脆弱性を露呈しました

31.increasing ideological differences with [TARGET_COUNTRY.GetName]
> [TARGET_COUNTRY.GetName]との間のイデオロギー的な相違点が増加します

32.increasing ideological similiaries with [TARGET_COUNTRY.GetName]
> [TARGET_COUNTRY.GetName]との間のイデオロギー的な類似点が増加します

33.[TARGET_COUNTRY.GetName] being part of the the same [concept_power_bloc]
> [TARGET_COUNTRY.GetName]が同じ[concept_power_bloc]のメンバーです

34.[TARGET_COUNTRY.GetName] being part of different [Concept('concept_power_bloc','$concept_power_blocs$')]
> [TARGET_COUNTRY.GetName]が異なる[Concept('concept_power_bloc','$concept_power_blocs$')]のメンバーです

35.[COUNTRY.GetAdjective] strategic ambitions towards us (usually from a [concept_journal_entry])
> [COUNTRY.GetAdjective]の我が国に対する戦略的野心（通常は[concept_journal_entry]に由来）

36.[TARGET_COUNTRY.GetName] becoming a [COUNTRY.GetAdjective] [concept_unification_supporter]
> [TARGET_COUNTRY.GetName]が[COUNTRY.GetAdjective]の[concept_unification_supporter]になります

37.[TARGET_COUNTRY.GetName] ceasing to be a [COUNTRY.GetAdjective] [concept_unification_supporter]
> [TARGET_COUNTRY.GetName]が[COUNTRY.GetAdjective]の[concept_unification_supporter]をやめます

38.[TARGET_COUNTRY.GetName] requesting increasing autonomy
> [TARGET_COUNTRY.GetName]が自治権の拡大を要求します

39.[TARGET_COUNTRY.GetName] changed the autonomy level of [COUNTRY.GetName]
> [TARGET_COUNTRY.GetName]が[COUNTRY.GetName]の自治レベルを変更しました

40.[TARGET_COUNTRY.GetName] refused to increase the autonomy of [COUNTRY.GetName]
> [TARGET_COUNTRY.GetName]が[COUNTRY.GetName]の自治権の拡大を拒否しました

**Comment by matanki-saito** [comment]
41.[TARGET_COUNTRY.GetName] requesting control of their own [concept_market]
> [TARGET_COUNTRY.GetName]が自国の[concept_market]の管理権を要求します

42.[TARGET_COUNTRY.GetName] requesting an embassy from [COUNTRY.GetName]
> [TARGET_COUNTRY.GetName]が[COUNTRY.GetName]からの大使を要請しています

43.[TARGET_COUNTRY.GetName] requesting support for their regime
> [TARGET_COUNTRY.GetName]が政権の支持を要請しています

44.[TARGET_COUNTRY.GetName] requesting [COUNTRY.GetName] share knowledge of their [concept_technology]
> [TARGET_COUNTRY.GetName]が、[COUNTRY.GetName]が[concept_technology]知識を共有するよう要請しています

45.a [concept_diplomatic_incident] occurring between [COUNTRY.GetName] and [TARGET_COUNTRY.GetName]
> [concept_diplomatic_incident]が[COUNTRY.GetName]と[TARGET_COUNTRY.GetName]の間で発生します

46.a friendly [concept_political_lobby] becoming part of the [COUNTRY.GetAdjective] [concept_government]
> 友好的な[concept_political_lobby]が[COUNTRY.GetAdjective][concept_government]の一部となりました

47.a hostile [concept_political_lobby] becoming part of the [COUNTRY.GetAdjective] [concept_government]
> 敵対的な[concept_political_lobby]が[COUNTRY.GetAdjective][concept_government]の一部となりました

48.[TARGET_COUNTRY.GetName] [Concept('concept_nationalize','$concept_nationalized$')] a [COUNTRY.GetAdjective]-owned [concept_building]
> [TARGET_COUNTRY.GetName]が[COUNTRY.GetAdjective]所有の[concept_building]を[Concept('concept_nationalize','$concept_nationalized$')]

49.[TARGET_COUNTRY.GetName] declining an offer to join the [COUNTRY.GetPowerBloc.GetName]
> [TARGET_COUNTRY.GetName]が[COUNTRY.GetPowerBloc.GetName]への参加を辞退しました

50.[COUNTRY.GetName] was kicked out of [TARGET_COUNTRY.GetPowerBloc.GetName] by [TARGET_COUNTRY.GetName]
> [COUNTRY.GetName]は、[TARGET_COUNTRY.GetName]によって[TARGET_COUNTRY.GetPowerBloc.GetName]から追放されました

51.[TARGET_COUNTRY.GetName] exiled a character with one of our [concept_primary_cultures]
> [TARGET_COUNTRY.GetName]は[concept_primary_cultures]のキャラクター1人を追放しました

**Comment by matanki-saito** [comment]
52.[TARGET_COUNTRY.GetName] invited a sympathetic [concept_exile] from our country
> [TARGET_COUNTRY.GetName]は同調する[concept_exile]を我々の国に招聘しました

53.[TARGET_COUNTRY.GetName] invited an unsympathetic [concept_exile] from our country
> [TARGET_COUNTRY.GetName]は同調しない[concept_exile]を我々の国に招聘しました

54.[TARGET_COUNTRY.GetName] overtaking [COUNTRY.GetName] in the top #v [GetDefine('NDiplomacy','DIPLOMATIC_CATALYST_MIN_SCORE_POSITION_FOR_OVERTAKE')]#! [concept_prestige] rankings
> [TARGET_COUNTRY.GetName]が#v トップ[GetDefine('NDiplomacy','DIPLOMATIC_CATALYST_MIN_SCORE_POSITION_FOR_OVERTAKE')]#![concept_prestige]ランキングで[COUNTRY.GetName]を追い抜いています

55.from events or other reasons
> イベントやその他の理由から

56.from events or other reasons
> イベントやその他の理由から

57.gaining a land border with [TARGET_COUNTRY.GetName]
> [TARGET_COUNTRY.GetName]との地上境界線を獲得しています

58.losing their land border with [TARGET_COUNTRY.GetName]
> [TARGET_COUNTRY.GetName]との地上境界線を失いつつあります

59.the opening of the [TARGET_COUNTRY.GetMarket.GetName]
> [TARGET_COUNTRY.GetMarket.GetName]の開放

60.[COUNTRY.GetName] left the [TARGET_COUNTRY.GetPowerBloc.GetName]
> [COUNTRY.GetName]は[TARGET_COUNTRY.GetPowerBloc.GetName]を離脱しました

61.[TARGET_COUNTRY.GetName] had their [concept_government] overthrown by a [concept_revolution]
> [TARGET_COUNTRY.GetName]の[concept_government]が、[concept_revolution]によって倒されました

62.[TARGET_COUNTRY.GetName] became a [concept_recognized_power]
> [TARGET_COUNTRY.GetName]が[concept_recognized_power]になりました

63.[TARGET_COUNTRY.GetName] requesting decreasing autonomy
> [TARGET_COUNTRY.GetName]が自治権の縮小を要請しています。

**Comment by matanki-saito** [comment]
これらの修正案は以下の通り：
1.[TARGET_COUNTRY.GetName]との歴史的関係
2.[TARGET_COUNTRY.GetName]が外交的に重要な存在になったこと
3.[TARGET_COUNTRY.GetName]が外交的に重要な存在でなくなったこと
4.[TARGET_COUNTRY.GetName]が新たな[concept_political_lobby]結成に資金を提供したこと
5.[TARGET_COUNTRY.GetName]との[concept_relations]改善
6.[TARGET_COUNTRY.GetName]との[concept_relations]悪化
7.[TARGET_COUNTRY.GetName]に対する[concept_diplomatic_demand]
8.[TARGET_COUNTRY.GetName]による[concept_diplomatic_demand]の対象化
9.[TARGET_COUNTRY.GetName]に対する[concept_diplomatic_play]の開始
10.[TARGET_COUNTRY.GetName]による[concept_diplomatic_play]の対象化
11.[TARGET_COUNTRY.GetName]からの自治拡大
12.[TARGET_COUNTRY.GetName]からの自治縮小
13.[TARGET_COUNTRY.GetName]からの完全独立
14.[TARGET_COUNTRY.GetName]の[concept_overlord]化
15.[TARGET_COUNTRY.GetName]の[concept_subject]化
16.[TARGET_COUNTRY.GetName]との[concept_diplomatic_pact]の締結
17.[TARGET_COUNTRY.GetName]との[concept_diplomatic_pact]破棄
18.[TARGET_COUNTRY.GetName]との[concept_defensive_pact]・[concept_alliance]
19.[TARGET_COUNTRY.GetName]との[concept_defensive_pact]・[concept_alliance]解消
20.[TARGET_COUNTRY.GetName]が[COUNTRY.GetName]との[concept_rivalry]宣言をしたこと
21.[TARGET_COUNTRY.GetName]が[COUNTRY.GetAdjective]の[Concept('concept_rivalry','$concept_rival$')]と同盟関係になったこと
22.[TARGET_COUNTRY.GetName]が[COUNTRY.GetAdjective]の$concept_rival$に対し[concept_rivalry]関係を宣言したこと
23.[COUNTRY.GetAdjective]の$concept_rival$との[concept_relations]改善
24.[COUNTRY.GetAdjective]の$concept_rival$との[concept_relations]悪化
25.[concept_diplomatic_play]において[TARGET_COUNTRY.GetName]と敵同士になったこと
26.[concept_diplomatic_play]において[TARGET_COUNTRY.GetName]と味方同士になったこと
27.[TARGET_COUNTRY.GetName]が[COUNTRY.GetName]に対する[concept_war_goal]を実行したこと 
28.[TARGET_COUNTRY.GetName]が[COUNTRY.GetName]の[concept_state]を征服したこと
29.[COUNTRY.GetName]の[concept_ai_strategy]変更
30.[TARGET_COUNTRY.GetName]が[concept_bankruptcy]を宣言し弱みを見せたこと
31.[TARGET_COUNTRY.GetName]とのイデオロギー的差異の増大
32.[TARGET_COUNTRY.GetName]とのイデオロギー的類似点の増大
33.[TARGET_COUNTRY.GetName]が同じ[concept_power_bloc]のメンバーとなったこと

**Comment by matanki-saito** [comment]
上記修正案に伴う本題の原案に対する代替案はこうなります
```[SCOPE.sDiplomaticCatalyst('diplomatic_catalyst').GetDesc]により、[SCOPE.sPoliticalLobby('political_lobby').GetCountry.GetName]で[SCOPE.sPoliticalLobby('political_lobby').GetName|v]が結成されました

この新しい[Concept('concept_political_lobby','$concept_political_lobby_short$')]は、[SCOPE.sPoliticalLobby('political_lobby').GetMembersDesc]から成ります```
> ブラジルがアルゼンチンの州を征服したことにより、アルゼンチンで反ブラジル連盟が結成されました
> 
> この新しい圧力団体は、労働組合、実業家、軍部から成ります

**Comment by inarizushi0309** [comment]
長くなりましたが、上記内容で修正しました。起票ありがとうございました。
