### ISSUE TITLE
○○でソート

### ISSUE THREAD

**Issue by kurutto115** [matanki-saito/vic3jpadvmod#989]
### スクリーンショット

![s-Victoria 3 2024_07_22 23_50_28](https://github.com/user-attachments/assets/00500ea5-cee5-4a19-90ba-770f4436a94b)
![s-Victoria 3 2024_07_22 23_47_02](https://github.com/user-attachments/assets/9d57f5a7-ebfc-4722-809f-94e30ebd53aa)
![s-Victoria 3 2024_07_22 23_47_16](https://github.com/user-attachments/assets/5a65c377-5b3b-4cdd-a60f-e523c74aad45)

### 問題のあるインターフェイス

複数

### 問題のテキスト

○○でソート
○○順にソート
など

### 希望する変更

○○で並べ替える
など

### 変更の理由（概要）

表現の非統一

### 変更の理由（詳細）

並べ替えのツールチップに「ソート」と「並べ替え」が混在しているので後者に統一したい
また「○○順にソート」が「○○別にソート」と誤訳されている箇所も散見されるので合わせて修正したい

### ゲームバージョン

1.7.X

### MOD有無

本プロジェクトMODのみ

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
原案通り「で並べ替え」および「順」への統一で修正しました。起票ありがとうございました。
