### ISSUE TITLE
現在イギリスで制定済み中です

### ISSUE THREAD

**Issue by kurutto115** [matanki-saito/vic3jpadvmod#992]
### スクリーンショット

![s-Victoria 3 2024_07_24 20_51_04](https://github.com/user-attachments/assets/cf8f3e4c-af77-457c-ba39-eccb7be2635a)
![s-Victoria 3 2024_07_24 20_51_04](https://github.com/user-attachments/assets/e820cc8e-518d-4f15-94eb-83dcb11d7da6)

### 問題のあるインターフェイス

法律ウィンドウ

### 問題のテキスト

```
現在[Law.GetCountry.GetName]で[Concept('concept_enactment_of_laws','$concept_enactment_of_laws_enacted$')]中です
```

### 希望する変更

```
現在[Law.GetCountry.GetName]で[Concept('concept_enactment_of_laws','$concept_enactment_of_laws_enacting$')]です
```

### 変更の理由（概要）

誤訳

### 変更の理由（詳細）

原語では受け身で"Enacted"が使用されている箇所だが、$concept_enactment_of_laws_enacted$を完了形と解釈して「制定済み」と訳しているため、和文では齟齬が生じている

### ゲームバージョン

1.7.X

### MOD有無

本プロジェクトMODのみ

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
こちらチーム内で議論しましたが、$concept_enactment_of_laws_enacted$を「制定済み」から「制定」に変更し、これが使われているキーの接続する文章を全てチェックしたうえで修正したほうがより自然な日本語になるという結論になったため、そのように変更しました。
