### ISSUE TITLE
Interventionism

### ISSUE THREAD

**Issue by starjard** [matanki-saito/vic3jpadvmod#993]
### スクリーンショット

![interventionism](https://github.com/user-attachments/assets/e86c9916-7d27-46f0-8948-1ff2414afefd)

### 問題の用語

干渉主義

### 英語版の表現

Interventionism

### 希望する変更

介入主義

### 変更の理由（概要）

定訳への変更・訳語統一

### 変更の理由（詳細）

経済法の一つ。民間経済と政府介入の混合形態の経済法。
Interventionismは国際政治・軍事分野及び経済分野で使われるが、通常は介入と訳されることが多い。干渉主義と訳される場合もあるにはあるが、通常は国際政治・軍事分野の場合に使われて、経済分野のほうで使われることはあまりない。
またレッセフェールの説明文ではgovernment interventionsが政府の介入と訳されており、こちらと訳語の統一もしたいため。

### ゲームバージョン

1.7.X

### MOD有無

翻訳改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
提案通り修正しました。
