### ISSUE TITLE
我々の現在の戦争に加盟する

### ISSUE THREAD

**Issue by kurutto115** [matanki-saito/vic3jpadvmod#994]
### スクリーンショット

![s-Victoria 3 2024_07_25 15_50_11](https://github.com/user-attachments/assets/1cf1fb47-e694-4f8a-ba11-b009ea973a6a)

### 問題のあるインターフェイス

従属国アクション「軍へのアクセスを強化」の効果説明

### 問題のテキスト

「従属国」を我々の現在の戦争に加盟する

### 希望する変更

「従属国」を我々の現在の戦争に参加させる

### 変更の理由（概要）

日本語として不自然なため

### ゲームバージョン

1.6.X

### MOD有無

本プロジェクトMODのみ

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by starjard** [comment]
報告ありがとうございます。提案通り修正しました。
