### ISSUE TITLE
宗教会議と貿易同盟の結束力解説

### ISSUE THREAD

**Issue by kurutto115** [matanki-saito/vic3jpadvmod#995]
### スクリーンショット

![s-Victoria 3 2024_07_25 15_49_07](https://github.com/user-attachments/assets/0bd8b66d-0ddf-4d7a-8d56-dd201faaa212)
![s-Victoria 3 2024_07_25 15_49_23](https://github.com/user-attachments/assets/75a3eda5-05a3-4a70-8ee2-2fab80b1f794)
![s-Victoria 3 2024_07_25 15_52_05](https://github.com/user-attachments/assets/40a56329-453e-4447-9f22-574dc48dd354)
![s-Victoria 3 2024_07_25 15_52_17](https://github.com/user-attachments/assets/826c5980-6c20-4139-8c01-5942abd7cb9c)

### 問題のツールチップ

勢力圏の結束力のマウスオンヒント

### 問題の表現

```
#v [SCOPE.GetRootScope.GetCountry.GetPowerBloc.GetParticipantWithLowestLeaderReligionPercentage.GetLeaderReligionPercentage|%]#! ($identity_religious$) を持つ[concept_power_bloc_leader]の[concept_state_religion][SCOPE.GetRootScope.GetCountry.GetPowerBloc.GetParticipantWithLowestLeaderReligionPercentage.GetName]を信奉する人口が最も低い[concept_power_bloc]メンバー
```
（上記スクショにおける例）
0.00% (宗教会議) を持つ勢力圏リーダーの国教デンマークを信奉する人口が最も低い勢力圏メンバー（による-25.00）
```
#v [SCOPE.GetRootScope.GetCountry.GetPowerBloc.GetParticipantWithLowestEconomicDependenceOnLeader.GetEconomicDependenceOn(SCOPE.GetRootScope.GetCountry.Self)]#! ($identity_trade_league$) を持つ[concept_power_bloc_leader][SCOPE.GetRootScope.GetCountry.GetPowerBloc.GetParticipantWithLowestEconomicDependence.GetName]への[concept_economic_dependence]が最も低い[concept_power_bloc]メンバー
```
（上記スクショにおける例）
重要 (1.5) (貿易同盟) を持つ勢力圏リーダーザクセン＝コーブルク＝ゴータへの経済的依存度が最も低い勢力圏メンバー（による-25.00）

### 問題箇所の英文

```
#indent_newline:3 [concept_power_bloc_member] with lowest population following the [concept_power_bloc_leader]'s [concept_state_religion] and [concept_rank] ($identity_religious$)\n[SCOPE.GetRootScope.GetCountry.GetPowerBloc.GetParticipantWithLowestLeaderReligionPercentage.GetName] ([SCOPE.GetRootScope.GetCountry.GetPowerBloc.GetParticipantWithLowestLeaderReligionPercentage.GetRank]) with [SCOPE.GetRootScope.GetCountry.GetPowerBloc.GetParticipantWithLowestLeaderReligionPercentage.GetLeaderReligionPercentage|v%]#!
```
（上記スクショにおける例）
(-25.00 from) Power Bloc Member with lowest population following the Power Bloc Leader's State Religion and Rank (Religious Convocation)
 Denmark (Insignificant Power) with 0.00%
```
#indent_newline:3 [concept_power_bloc_member] with lowest [concept_economic_dependence] on the [concept_power_bloc_leader] and [concept_rank] ($identity_trade_league$)\n [SCOPE.GetRootScope.GetCountry.GetPowerBloc.GetParticipantWithLowestEconomicDependence.GetName] ([SCOPE.GetRootScope.GetCountry.GetPowerBloc.GetParticipantWithLowestEconomicDependence.GetRank]) with [SCOPE.GetRootScope.GetCountry.GetPowerBloc.GetParticipantWithLowestEconomicDependenceOnLeader.GetEconomicDependenceOn(SCOPE.GetRootScope.GetCountry.Self)]#!
```
（上記スクショにおける例）
(-19.63 from) Power Bloc Member with lowest Economic Dependence on the Power Bloc Leader and Rank (Trade League)
 Saxe-Coburg-Gotha (Insignificant Power) with Important (1.5)

### 希望する変更

```
#indent_newline:3 [concept_power_bloc_leader]の[concept_state_religion]を信奉する人口の割合が最も低い[concept_power_bloc_member]およびその[concept_rank] ($identity_religious$)\n#v [SCOPE.GetRootScope.GetCountry.GetPowerBloc.GetParticipantWithLowestLeaderReligionPercentage.GetLeaderReligionPercentage|%]#!を持つ[SCOPE.GetRootScope.GetCountry.GetPowerBloc.GetParticipantWithLowestLeaderReligionPercentage.GetName] ([SCOPE.GetRootScope.GetCountry.GetPowerBloc.GetParticipantWithLowestLeaderReligionPercentage.GetRank]) 
```
（例）
勢力圏リーダーの国教を信奉する人口の割合が最も低い勢力圏メンバーおよびそのランク (宗教会議)
 0.00%を持つデンマーク (小国) （による-25.00）
```
#indent_newline:3 [concept_power_bloc_leader]への[concept_economic_dependence]が最も低い[concept_power_bloc_member]およびその[concept_rank] ($identity_trade_league$) \n#v [SCOPE.GetRootScope.GetCountry.GetPowerBloc.GetParticipantWithLowestEconomicDependenceOnLeader.GetEconomicDependenceOn(SCOPE.GetRootScope.GetCountry.Self)]#!を持つ[SCOPE.GetRootScope.GetCountry.GetPowerBloc.GetParticipantWithLowestEconomicDependence.GetName] ([SCOPE.GetRootScope.GetCountry.GetPowerBloc.GetParticipantWithLowestEconomicDependence.GetRank]) 
```
（例）
勢力圏リーダーへの経済的依存度が最も低い勢力圏メンバーとそのランク (貿易同盟)
 重要 (1.5) を持つザクセン＝コーブルク＝ゴータ (小国) （による-19.63）

### 変更の理由（概要）

語順の乱れなど

### 変更の理由（詳細）

語順が乱れて意味不明になっている箇所の修正
合わせて原語から訳出されていない、対象の勢力圏メンバーのランクが影響することを追記

### プレイ国家

イギリス

### ゲームバージョン

1.7.X

### MOD有無

本プロジェクトMODのみ

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
https://paratranz.cn/projects/5456/strings?text=POWER_BLOC_COHESION_
関連エントリを一括修正したいと思います。以下列挙していきます

**Comment by matanki-saito** [comment]
1.[Concept('concept_power_bloc_leader','$concept_power_bloc_leader_extra_short$')] share of total [concept_prestige] ($identity_sovereign_empire$)
> [Concept('concept_power_bloc_leader','$concept_power_bloc_leader_extra_short$')]が総[concept_prestige]（$identity_sovereign_empire$）に占める割合

2.[Concept('concept_power_bloc_leader','$concept_power_bloc_leader_extra_short$')] [concept_legitimacy] ($identity_ideological_union$)
> [Concept('concept_power_bloc_leader','$concept_power_bloc_leader_extra_short$')] [concept_legitimacy]（$identity_ideological_union$）

3.#indent_newline:3 [concept_power_bloc_member] with highest [concept_liberty_desire] and [concept_rank] ($identity_sovereign_empire$) \n[SCOPE.GetRootScope.GetCountry.GetPowerBloc.GetParticipantWithHighestLibertyDesire.GetName] ([SCOPE.GetRootScope.GetCountry.GetPowerBloc.GetParticipantWithHighestLibertyDesire.GetRank]) with [SCOPE.GetRootScope.GetCountry.GetPowerBloc.GetParticipantWithHighestLibertyDesire.GetLibertyDesireLevelLabel]#!
> #indent_newline:3 [concept_liberty_desire]・[concept_rank]が最も高い[concept_power_bloc_member]($identity_sovereign_empire$)\n[SCOPE.GetRootScope.GetCountry.GetPowerBloc.GetParticipantWithHighestLibertyDesire.GetLibertyDesireLevelLabel]を持つ[SCOPE.GetRootScope.GetCountry.GetPowerBloc.GetParticipantWithHighestLibertyDesire.GetName]([SCOPE.GetRootScope.GetCountry.GetPowerBloc.GetParticipantWithHighestLibertyDesire.GetRank])#!

4.[Concept('concept_power_bloc_leader','$concept_power_bloc_leader_extra_short$')] share of total [concept_power_projection] ($identity_military_treaty_organization$)
> [Concept('concept_power_bloc_leader','$concept_power_bloc_leader_extra_short$')]が総[concept_power_projection]（$identity_military_treaty_organization$）に占める割合

**Comment by matanki-saito** [comment]
5.#indent_newline:3 [concept_power_bloc_member] member with highest [concept_infamy] and [concept_rank] ($identity_military_treaty_organization$)\n[SCOPE.GetRootScope.GetCountry.GetPowerBloc.GetParticipantWithHighestInfamy.GetName] ([SCOPE.GetRootScope.GetCountry.GetPowerBloc.GetParticipantWithHighestLibertyDesire.GetRank]) with #v [SCOPE.GetRootScope.GetCountry.GetPowerBloc.GetParticipantWithHighestInfamy.GetInfamy|-0]#!#!
> #indent_newline:3 [concept_infamy]が最も高い[concept_power_bloc_member]メンバーおよび[concept_rank]($identity_military_treaty_organization$)\n#v [SCOPE.GetRootScope.GetCountry.GetPowerBloc.GetParticipantWithHighestInfamy.GetInfamy|-0]#!を持つ[SCOPE.GetRootScope.GetCountry.GetPowerBloc.GetParticipantWithHighestInfamy.GetName] ([SCOPE.GetRootScope.GetCountry.GetPowerBloc.GetParticipantWithHighestLibertyDesire.GetRank])#!

**Comment by matanki-saito** [comment]
6.#indent_newline:3 [concept_power_bloc_member] with [concept_government_type] least compatible with the [concept_power_bloc_leader] and [concept_rank] ($identity_ideological_union$)\n[SCOPE.GetRootScope.GetCountry.GetName] ([SCOPE.GetRootScope.GetCountry.GetRank]): [SCOPE.GetRootScope.GetCountry.GetActiveLawFromGroup('lawgroup_governance_principles').GetName] and [SCOPE.GetRootScope.GetCountry.GetActiveLawFromGroup('lawgroup_distribution_of_power').GetName]\n[SCOPE.GetRootScope.GetCountry.GetPowerBloc.GetParticipantWithHighestLeaderLawProgressivenessDifference.GetName]: [SCOPE.GetRootScope.GetCountry.GetPowerBloc.GetParticipantWithHighestLeaderLawProgressivenessDifference.GetActiveLawFromGroup('lawgroup_governance_principles').GetName] and [SCOPE.GetRootScope.GetCountry.GetPowerBloc.GetParticipantWithHighestLeaderLawProgressivenessDifference.GetActiveLawFromGroup('lawgroup_distribution_of_power').GetName]#!
> #indent_newline:3 [concept_power_bloc_leader]と最も相性の悪い[concept_government_type]を持つ[concept_power_bloc]メンバー\n[SCOPE.GetRootScope.GetCountry.GetName]：[SCOPE.GetRootScope.GetCountry.GetActiveLawFromGroup('lawgroup_governance_principles').GetName]および [SCOPE.GetRootScope.GetCountry.GetActiveLawFromGroup('lawgroup_distribution_of_power').GetName]\n[SCOPE.GetRootScope.GetCountry.GetPowerBloc.GetParticipantWithHighestLeaderLawProgressivenessDifference.GetName]：[SCOPE.GetRootScope.GetCountry.GetPowerBloc.GetParticipantWithHighestLeaderLawProgressivenessDifference.GetActiveLawFromGroup('lawgroup_governance_principles').GetName]および[SCOPE.GetRootScope.GetCountry.GetPowerBloc.GetParticipantWithHighestLeaderLawProgressivenessDifference.GetActiveLawFromGroup('lawgroup_distribution_of_power').GetName]#! ($identity_ideological_union$)

**Comment by matanki-saito** [comment]
7.#indent_newline:3 [concept_power_bloc_member] with lowest [concept_relations] with the [concept_power_bloc_leader] and [concept_rank]\n[SCOPE.GetRootScope.GetCountry.GetPowerBloc.GetParticipantWithLowestLeaderRelations.GetName] ([SCOPE.GetRootScope.GetCountry.GetPowerBloc.GetParticipantWithLowestLeaderRelations.GetRank]) with #v [SCOPE.GetRootScope.GetCountry.GetPowerBloc.GetParticipantWithLowestLeaderRelations.GetRelationsWithDesc(SCOPE.GetRootScope.GetCountry.Self)] ([SCOPE.GetRootScope.GetCountry.GetPowerBloc.GetParticipantWithLowestLeaderRelations.GetRelationsWith(SCOPE.GetRootScope.GetCountry.Self)|+=])#!#!
> [concept_power_bloc_leader]との[concept_relations]が最も低い[concept_power_bloc]メンバー(#v [SCOPE.GetRootScope.GetCountry.GetPowerBloc.GetParticipantWithLowestLeaderRelations.GetRelationsWithDesc(SCOPE.GetRootScope.GetCountry.Self)] ([SCOPE.GetRootScope.GetCountry.GetPowerBloc.GetParticipantWithLowestLeaderRelations.GetRelationsWith(SCOPE.GetRootScope.GetCountry.Self)|+=]#!) を持つ[SCOPE.GetRootScope.GetCountry.GetPowerBloc.GetParticipantWithLowestLeaderRelations.GetName])

8.[SCOPE.GetRootScope.GetCountry.GetInterestGroupOfType('ig_devout').GetName] [concept_clout] ($identity_religious$)
> [SCOPE.GetRootScope.GetCountry.GetInterestGroupOfType('ig_devout').GetName] [concept_clout] ($identity_religious$)

9.[SCOPE.GetRootScope.GetCountry.GetInterestGroupOfType('ig_devout').GetName] is #v not#! in [concept_government] ($identity_religious$)
> [SCOPE.GetRootScope.GetCountry.GetInterestGroupOfType('ig_devout').GetName]は[concept_government] ($identity_religious$)に所属して#v いません#!

**Comment by matanki-saito** [comment]
10.#indent_newline:3 [concept_power_bloc_member] with lowest population following the [concept_power_bloc_leader]'s [concept_state_religion] and [concept_rank] ($identity_religious$)\n[SCOPE.GetRootScope.GetCountry.GetPowerBloc.GetParticipantWithLowestLeaderReligionPercentage.GetName] ([SCOPE.GetRootScope.GetCountry.GetPowerBloc.GetParticipantWithLowestLeaderReligionPercentage.GetRank]) with [SCOPE.GetRootScope.GetCountry.GetPowerBloc.GetParticipantWithLowestLeaderReligionPercentage.GetLeaderReligionPercentage|v%]#!
> #v [SCOPE.GetRootScope.GetCountry.GetPowerBloc.GetParticipantWithLowestLeaderReligionPercentage.GetLeaderReligionPercentage|%]#! ($identity_religious$)を持つ[concept_power_bloc_leader]の[concept_state_religion] [SCOPE.GetRootScope.GetCountry.GetPowerBloc.GetParticipantWithLowestLeaderReligionPercentage.GetName]を信奉する人口が最も低い[concept_power_bloc]メンバー

11.leading [Concept('concept_good','$concept_goods$')] producers in [concept_power_bloc] ($identity_trade_league$)
> [concept_power_bloc] ($identity_trade_league$)における最大の[Concept('concept_good','$concept_goods$')]生産者

12.[Concept('concept_power_bloc_leader','$concept_power_bloc_leader_extra_short$')] share of total [concept_gdp] ($identity_trade_league$)
> [Concept('concept_power_bloc_leader','$concept_power_bloc_leader_extra_short$')]が総[concept_gdp] ($identity_trade_league$)に占める割合

**Comment by matanki-saito** [comment]
13.#indent_newline:3 [concept_power_bloc_member] with lowest [concept_economic_dependence] on the [concept_power_bloc_leader] and [concept_rank] ($identity_trade_league$)\n [SCOPE.GetRootScope.GetCountry.GetPowerBloc.GetParticipantWithLowestEconomicDependence.GetName] ([SCOPE.GetRootScope.GetCountry.GetPowerBloc.GetParticipantWithLowestEconomicDependence.GetRank]) with [SCOPE.GetRootScope.GetCountry.GetPowerBloc.GetParticipantWithLowestEconomicDependenceOnLeader.GetEconomicDependenceOn(SCOPE.GetRootScope.GetCountry.Self)]#!
> #v [SCOPE.GetRootScope.GetCountry.GetPowerBloc.GetParticipantWithLowestEconomicDependenceOnLeader.GetEconomicDependenceOn(SCOPE.GetRootScope.GetCountry.Self)]#! ($identity_trade_league$)を持つ[concept_power_bloc_leader] [SCOPE.GetRootScope.GetCountry.GetPowerBloc.GetParticipantWithLowestEconomicDependence.GetName]への[concept_economic_dependence]が最も低い[concept_power_bloc]メンバー

14.#v $VALUE|+=2$#! from #v $NUM$#! independent [Concept('concept_power_bloc_member','$concept_power_bloc_members_short_non_leader$')]
> #v $VALUE|+=2$#!: 独立している#v $NUM$#![Concept('concept_power_bloc_member','$concept_power_bloc_members_short_non_leader$')]に由来

**Comment by matanki-saito** [comment]
修正案の簡易版
> $数値$ $理由$
> ※いつもの括弧づけにすると視認性が落ちやすいため、省いています
> 
> 1.威信合計に占めるリーダーの割合(主権帝国)
> 
> 2.リーダーの正当性(イデオロギー連合)
> 
> 3.独立欲求が最も高い勢力圏メンバーおよびそのランク(主権帝国)
> [国名]([国家ランク])の[独立欲求:レベル]
> 
> 4.戦力投射合計に占めるリーダーの割合(軍事条約)
> 
> 5.悪名が最も高い勢力圏メンバーおよびそのランク(軍事条約)
> [国名]([国家ランク])[悪名値]
> 
> 6.勢力圏リーダーと最も相容れない政体の勢力圏メンバーおよびそのランク(イデオロギー連合)
> [自国名]([自国家ランク]):[統治原理]・[権力の配分]
> [該当国名]:[統治原理]・[権力の配分]
> 
> 7.勢力圏リーダーとの関係が最も低い勢力圏メンバーおよびそのランク
> [国名]([国家ランク])[関係レベル](関係値)
> 
> 8.[宗教派閥名]の勢力(宗教会議)
> 
> 9.[宗教派閥名]が政府内にいない(宗教会議)
> 
> 10.勢力圏リーダーの国教を信奉する人口が最も低い勢力圏メンバーおよびそのランク(宗教会議)
> [国名]([国家ランク])[該当宗教人口%]
> 
> 11.勢力圏最大の商品生産国(貿易同盟)
> 
> 12.国内総生産合計に占めるリーダーの割合(貿易同盟)
> 
> 13.勢力圏リーダーへの経済依存度が最も低い勢力圏メンバーおよびそのランク(貿易同盟)
> [国名]([国家ランク])[経済依存レベル]#!
> 
> 14.$数値$#! 独立しているリーダーでない勢力圏メンバー$数値$カ国
