### ISSUE TITLE
ジャーナル：爆発的な成長を遂げる産業の条件文

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#996]
### スクリーンショット

![Victoria 3 Screenshot 2024 07 26 - 21 31 05 87](https://github.com/user-attachments/assets/22281ac8-7cac-4fe3-913e-c7c91e32251b)

### 問題のツールチップ

ジャーナル：爆発的な成長を遂げる産業のツールチップ

### 問題の表現

```je_shortform_building_mine_tooltip: "建設とはすなわち鉄、石炭、鉛、または硫黄の鉱山である"```

### 問題箇所の英文

```je_shortform_building_mine_tooltip:0 "Building is Iron, Coal, Lead, or Sulfur Mines"```

### 希望する変更

```je_shortform_building_mine_tooltip: "施設が鉄、石炭、鉛、または硫黄鉱山である"```

### 変更の理由（概要）

日本語として不自然なため

### 変更の理由（詳細）

他の同様の条件文が「施設は○○です」となっているが、できればこれも「施設が○○である」の形に修正したい

### プレイ国家

オスマン帝国

### ゲームバージョン

1.7.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
以下関連エントリ含め修正しました。
```Building is $building_munition_plants$```
```Building is $building_explosives_factory$```
```Building is Iron, Coal, Lead, or Sulfur Mines```
起票ありがとうございました。
