### ISSUE TITLE
保護国の支払額減額が取消された通知フィード

### ISSUE THREAD

**Issue by kurutto115** [matanki-saito/vic3jpadvmod#997]
### スクリーンショット

![s-Victoria 3 2024_07_25 18_07_14](https://github.com/user-attachments/assets/13f73095-3f7c-4a39-9725-d4d1765c3c4a)

### 問題のあるインターフェイス

通知フィード

### 問題のテキスト

[concept_subject]は【concept_overlord】に敬意を払うタイプです

### 希望する変更

[concept_subject]は[concept_overlord]に敬意を払うタイプです

### 変更の理由（概要）

括弧の間違いにより表示にバグがある

### ゲームバージョン

1.7.X

### MOD有無

本プロジェクトMODのみ

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
議論の結果、「[concept_subject]が[concept_overlord]に貢納を払うタイプである」で修正しました。起票ありがとうございました。
