### ISSUE TITLE
modifiers_l_japanese.ymlの翻訳の修正が元に戻っている

### ISSUE THREAD

**Issue by mochi115** [matanki-saito/vic3jpadvmod#998]
### 問題の用語

多数

### 希望する変更

再度修正

### 変更の理由（概要）

翻訳が元に戻っているため

### 変更の理由（詳細）

軽く確認したところパラドがキーを変更したみたいです。
確認お願いします。

### ゲームバージョン

1.7.X

### MOD有無

日本語改善MOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by matanki-saito** [comment]
このファイルは特殊な処理をしていて確認が必要なため時間いただきます

**Comment by matanki-saito** [comment]
このファイルは特殊な処理をしていて確認が必要なため時間いただきます

**Comment by matanki-saito** [comment]
以下で対応しました

■ 6/26以降にmodifierがキー名から外れた2611個のキー
　■ この内、値は変わらない1920個のキー
　　そのまま

　■ 値が変わった341個のキー
　　■ 変数名から$modifier_がなくなったのみの238個のキー
　　　そのまま
　　■ それ以外の103個のキー
　　　■ 翻訳ファイルの値を優先する53個のキー
　　　　そのまま
　　　■ 元のparatranzデータを優先する50個のキー
　　　　26日に追加されたエントリは削除、元のparatranzの登録データのキー名からmodifierを削除

■ 新規追加された350個のキー
　そのまま


キーの明細
https://gist.github.com/matanki-saito/52f1edf0ee8406aab191bedf98b04cd9

**Comment by matanki-saito** [comment]
次回のファイル更新まで復活させたmodifier_がついたキーがファイルに現れると思いますが、特に悪さしないものと考えて一旦そのままにします
