### ISSUE TITLE
州画面：生活水準選択時のツールチップ

### ISSUE THREAD

**Issue by wakkunteitoku2** [matanki-saito/vic3jpadvmod#999]
### スクリーンショット

![Victoria 3 Screenshot 2024 07 28 - 16 28 05 69](https://github.com/user-attachments/assets/7a81cbc9-2fc7-4428-827d-732404422c0d)

### 問題のツールチップ

州画面：生活水準選択時のツールチップ

### 問題の表現

POPの○％の生活水準期待値（最小）を下回っています

### 希望する変更

POPの○％が生活水準期待値（最小）を下回っています

### 変更の理由（概要）

助詞がおかしい

### 変更の理由（詳細）

#971での修正分

### プレイ国家

オスマン帝国

### ゲームバージョン

1.7.X

### MOD有無

日本語改善MOD、フォントMOD

**Comment by matanki-saito** [comment]
[自動応答] 内部検討中です。 進捗がありましたら追記いたします。
追加のコメントが有りましたら下記にコメントの形で続けるようにお願い致します。

**Comment by inarizushi0309** [comment]
誤字脱字の一環として即時修正しました。助詞のミス程度のものでしたら、Discordの「誤字脱字・文体揺れ議論」にて対応可能ですので、ご活用ください
